### ISSUE TITLE
Sync up C++ for 2.0

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1025]
Recent changes in the 1.7.x series will demand some resyncing of C++. It compiles now, but even some very basic tests fail (see especially #1009). I'm not sure @grendello will have time to do this, so it falls upon me. If nothing else, ensure there are C++ widget construction unit tests, and run those through.

**Comment by grendello** [comment]
In progress!

**Comment by dankamongmen** [comment]
[WILD CHEERS]
