### ISSUE TITLE
add ncinput_equal() predicate

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1059]
When working with arbitrary dynamic `ncinput`s (as `ncmenu_handle_input()` will need to), it would be good to have a canonical equivalence test. Introduce `ncinput_equal()` with the obvious implementation.

**Comment by dankamongmen** [comment]
`ncinput_equal_p()` does a field-by-field comparison for equality (excepting `seqnum`), returning 1 if the two are data-equivalent.

**Comment by joseluis** [comment]
wouldn't it make more sense to return a bool instead of an int here? I'm just porting this function to rust and my fingers refuse to write it as an int...

**Comment by dankamongmen** [comment]
> wouldn't it make more sense to return a bool instead of an int here? I'm just porting this function to rust and my fingers refuse to write it as an int...

It absolutely would, were C not a terribly broken language. In one of the great programming language design mistakes of all time, a bool in C is trivially (i.e. without a warning or cast) coercible to a pointer type.

Actually, wait, it's the other way. A pointer can be trivially coerced into a bool. Still bad, but not so bad. Yeah, this should be bool.

**Comment by dankamongmen** [comment]
> > wouldn't it make more sense to return a bool instead of an int here? I'm just porting this function to rust and my fingers refuse to write it as an int...
> Actually, wait, it's the other way. A pointer can be trivially coerced into a bool. Still bad, but not so bad. Yeah, this should be bool.

changed for 2.0.3.

**Comment by joseluis** [comment]
Fantastic! I didn't expect this outcome to be honest.


BTW I remember seeing multiple references to this return type in the documentation that should be updated.

I suspect that it must be somewhat tedious having to update docs everytime in multiple places.

**Comment by dankamongmen** [comment]
> Fantastic! I didn't expect this outcome to be honest.
> 
> BTW I remember seeing multiple references to this return type in the documentation that should be updated.
> 
> I suspect that it must be somewhat tedious having to update docs everytime in multiple places.

Ponte las pilas, nicholas! I sure dropped the ball here, thank you.
