### ISSUE TITLE
notcurses_directmode.3.md states that all other functions return 0 unsuccess however ncdirect_putstr return the number of characters written.

### ISSUE THREAD

**Issue by igo95862** [dankamongmen/notcurses#1072]
> All other functions return 0 on success, and non-zero on error.
https://github.com/dankamongmen/notcurses/blob/master/doc/man/man3/notcurses_directmode.3.md

The putstr returns the return of fprintf which is number of characters.
https://github.com/dankamongmen/notcurses/blob/master/src/lib/direct.cpp#L27

**Comment by dankamongmen** [comment]
Thank you! You're of course correct.

**Comment by dankamongmen** [comment]
I believe this to be fixed. It will be present in releases >= 2.0.2.
