### ISSUE TITLE
multipiles

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1078]
It would presumably be sometimes useful to be able to scribble on an `ncplane` while still rendering one's other planes. Currently, one can only safely do this by stashing the scribble plane underneath all others, and ensuring that every cell gets solved above you. Introduce `ncplane_decouple()` or some way to create a decoupled one in `ncplane_create()`, and also a method by which it can come back into the stack (`ncplane_move_top()` etc. might be sufficient).

Note that this means *all* links must be severed:
 * the plane cannot be the parent of any other coupled plane
 * the plane cannot be the child of any other coupled plane
 * the plane cannot have valid `above` or `below` links

this kinda suggests that you can't have interplane structure outside the stack, or else you'd have to move everything back at once. think this through before moving on it.

* [x] define new internal type `ncpile` and replace `notcurses` link in `ncplane`
* [x] implement internal `ncpile_destroy()`
* [x] create doubly-linked locked circular list of `ncpile`s in `notcurses`, free them in `notcurses_stop()`
* [x] add new internal function `make_ncpile()`
* [x] add new function `ncpile_create()`
* [x] implement family detach in `ncplane_reparent()`
* [x] accept equal arguments for `ncplane_reparent_family()`
* [x] implement zaxis detach in `ncplane_reparent_family()`
* [x] update `notcurses_drop_planes()` to drop all piles
* [x] call `ncpile_destroy()` for emptied ncpile in `ncplane_reparent_family()`
* [x] call `ncpile_destroy()` for emptied ncpile in `ncplane_destroy()`
* [x] update `ncplane_move_top()` to use plane's pile
* [x] update `ncplane_move_bottom()` to use plane's pile
* [x] update `ncplane_move_above()` to reject cross-pile moves
* [x] update `ncplane_move_below()` to reject cross-pile moves
* [x] implement cross-pile moves in `ncplane_reparent_family()`
* [x] add unit test for new pile via `ncpile_create()`
* [x] add unit tests for reparenting, check that `ncplane_pile()` differs as expected

**Comment by dankamongmen** [comment]
I don't want the ability to "swap out" an entire stack, or else we'd need ensure every stack has something fit as the standard plane. Instead, I'm thinking that you can extract an `ncplane`, and its bound planes come with it. Furthermore, you can create new planes bound to this extracted plane, and they will be "extracted".

To reinsert an extracted plane (and any bound planes), you'll reparent it. This handles the case where a bound plane is reinserted by itself -- the act of reparenting will decouple it from the extracted stack.

The "root" plane of an extracted stack will be bound to itself, just like the standard plane. This maintains the invariant that all planes are bound, without making a reference into the main stack. This seamlessly facilitates multiple extracted stacks.

So, extracting a plane:
 * removes it from its parent's bound list
 * binds it to itself
 * splices it out of the z-axis
 * splices all planes bound to it out of the z-axis
 * creates a new z-axis, and orders all extracted planes the same way

The one thing I don't like about this is that we lose z-axis information. Let's say we have planes 1, 2, 3, 4 from top to bottom. 2 is bound to 4; 1 and 4 are bound to 3; 3 is bound to itself. We extract 4. This gives us:

zaxis1: 1, 3
zaxis2: 2, 4

when we reparent 4, we now have 2, 4, 1, 3 (assuming reinserted planes go to the top of the z-axis). 3 is no longer between them. That's just how it goes, I suppose, when you're stuck fuck out of luck and lost in the ghetto.

**Comment by dankamongmen** [comment]
https://www.youtube.com/watch?v=3CE3fXWXwtg

probably going to go ahead and move on this

**Comment by dankamongmen** [comment]
what happens if you call `ncplane_move_bottom()` on such an extracted plane?

**Comment by dankamongmen** [comment]
This could just be `ncplane_reparent(n, NULL)`.

**Comment by dankamongmen** [comment]
Yes, together with #1109 we will pursue a glorious new era.

There will be no standard plane, and there will be no default stack. There will be planes and stacks, created as the user deems fit. `notcurses_render_stack()` will be introduced. Use it to render a stack. Rasterize the render.

Have a single plane occupying a single cell, forming the entirety of your single stack. Have thousands of stacks with millions of planes. Render as you see fit.

![destroy-the-old](https://user-images.githubusercontent.com/143473/98998267-ddb9c100-2503-11eb-95d1-d08f027b07f7.jpg)

**Comment by joseluis** [comment]
I like very much the ongoing ncplane refactor. This one specially... It will make planes a lot more fun to use.   

Do you think maybe there's a simpler API for horizontal alignment that doesn't involve a union? Or do you like the current solution a lot?

**Comment by dankamongmen** [comment]
> I like very much the ongoing ncplane refactor. This one specially... It will make planes a lot more fun to use.
> 
> Do you think maybe there's a simpler API for horizontal alignment that doesn't involve a union? Or do you like the current solution a lot?

i do not like it a lot.

i can't just map them onto the negatives, since you can place a place in the negatives.

i could eliminate the union aspect, and just treat it as two different "number lines" based on the flag, since ints and enums are handwave-equivalent-enough-for-this. then you're doing `.x = NCALIGN_CENTER`, which .... you know, i have no problem with that whatsoever, really.

i think this might require c++ to throw some `static_cast`s into the mix, but what's c++ without a tsunami of bracketed overwrought nonsense?

https://getyarn.io/yarn-clip/3998758f-e3f0-4485-9ef4-c0b6c54ea476

@joseluis i say we take this sad old `union` out behind the shed and put a bullet between its eyes. as i live in a Very Free Nation, that actually means two 10-round clips of 5.56 NATO rounds pumped into the union from my two Ruger AR-556s. should you ever visit Georgia, @joseluis , stop by and we'll go shoot the shit out of something.

**Comment by dankamongmen** [comment]
oh btw i know i wrote "stack" a lot above, but we're actually calling them "piles" because

a) stack has a very definite CS meaning and this is not it
b) i have a masters in nuclear engineering with shit to show for it and it's fun to say [pile](https://en.wikipedia.org/wiki/Chicago_Pile-1) goddamnit

if it was good enough for fermi it's certainly good enough for us

**Comment by dankamongmen** [comment]
for those (not) following along at home, here's what's brewing in the increasingly-inaccurately named `dankamongmen/multistack` branch:

```
* 2.0.5 (not yet released)
  * As promised, `ncplane_new()` has been marked as deprecated. It will be
    removed in 3.0. Use the strictly more powerful `ncplane_create()` instead,
    with its self-documenting `struct ncplane_options` argument. So long as
    the arguments to `ncplane_new()` do not have side-effects, calls can be
    mechanically translated to their `ncplane_create()` equivalents.
  * A single `struct notcurses` now supports multiple *planepiles* or simply
    *piles*. Planepiles do not exist as a type (any `ncplane` bound to itself
    is the root of a pile; the standard plane is always bound to itself, and
    thus there always exists a *standard pile*), but as a concept. A pile is
    made up of some root plane, and all planes recursively bound to that root.
    Multiple threads can freely operate on distinct piles, even rendering them
    concurrently (into distinct memory, obviously). A pile ceases to exist when
    all its planes are destroyed, or when its root plane is reparented into
    another pile. It is an error to call `ncplane_destroy()` on a root plane to
    which other planes are bound; `ncplane_genocide()` must be employed in this
    case. It remains impossible to reparent or destroy the standard plane.
  * A `NULL` `ncplane` can now be passed to `ncplane_create()` as its first
    argument; the created `ncplane` will root its own new pile. Similarly,
    `ncplane_reparent()` can now be provided the same `ncplane` for both
    arguments; the `ncplane` will root its own new pile (unless it already did,
    in which case this is a no-op). Planes outside the standard pile *are not
    rendered in a call to `notcurses_render()`*. An `ncplane` can be reparented
    into any existing pile.
  * `notcurses_render_pile()` has been added to render a particular pile.
    `notcurses_render()` now calls `notcurses_render_pile()` with the
    standard plane.
```

**Comment by dankamongmen** [comment]
i might not purge `ncplane_new()` because why break working code. I'm updating all the usages within the tree, though, and definitely marking it deprecated.

**Comment by dankamongmen** [comment]
The `ncplane_destroy()` not working on a root plane is an ugly wart, but we need that rule because otherwise, if two planes are bound directly to said root plane, what happens? The rootness is a spontaneous symmetry break. 

...which suggests, of course, a `root level` rather than a `root plane`. which is not a terrible idea, except the lingering asshair that is the standard plane kinda fucks this up. can other planes be on the same root plane as the standard plane? if the set of planes bound to some plane had to be a partition, then no, but so long as they can overlap, you would have to let one...but is that such a problem?

is this stupid and overthinking in response to what's only really a rather small departure from orthogonality?

i will ponder it. all input welcome.

**Comment by dankamongmen** [comment]
> is this stupid and overthinking in response to what's only really a rather small departure from orthogonality?

the more i think about it, this is absolutely the right thing to do. i don't like the fact that you can't reparent an entire level at once, but that's true for our current situation, also (you can't fix this with e.g. an `ncplane_adopt()` that takes all the bound planes of some other plane, because that breaks down for root planes). that's no big deal, though. loop over the fuckers.

oooooh what we could add is some kind of e.g. `ncplane_everybody_on_the_boat()` where you reparented not the specified plane, but the specified plane *and its recursive boundnexts*. yep, there we go. we'll want a better name.

so now if you have a root level with a single plane, and two planes are bound to it, and you do an `ncplane_destroy()` of the former, the latter two fall down into the root level. the boundnext pointer already serves to implement this level -- we simply relax the (now so clearly unnecessary, and until now implicit) restriction that the root plane have a `NULL` boundnext -- remember, the pile is not a data structure, occupies no memory, and cannot be address without aliasing some plane.

i'm glad i typed this all out, this is much, much, much better.

**Comment by dankamongmen** [comment]
Hrmmm actually there's a problem with this. So we've proposed decoupling a plane by reparenting against itself. This makes it a new pile. Under the proposal above, how would we extract a plane and add it to a root level of an existing pile? There's no way to do so. I don't think it particularly important, but it undermines the conceptual elegance of the entire approach--in which case the added complexity probably isn't worth it. Hrmmm.

(currently, you join a level by reparenting to the plane to which that level is bound. the planes of a root level are bound to themselves; you can only reparent underneath them).

**Comment by joseluis** [comment]
I think it's perfectly acceptable to have the limitation of only one plane for the root of a plane pile.

As long as we can have multiple planepiles detached from the main pile being rendered, and the flexibility of shuffling planes between piles I don't see a problem with that really.

**Comment by joseluis** [comment]
It would be nice to have the option of inserting a plane between two others, like adding a chain slab, on one side, and being able to insert a plane as a child and becoming a sibling of the preexisting children of the new parent, on the other...

**Comment by dankamongmen** [comment]
> It would be nice to have the option of inserting a plane between two others, like adding a chain slab, on one side, and being able to insert a plane as a child and becoming a sibling of the preexisting children of the new parent, on the other...

to insert c between a and b, reparent b to c and c to a. but maybe you meant as one call?

**Comment by dankamongmen** [comment]
> I think it's perfectly acceptable to have the limitation of only one plane for the root of a plane pile.
> 
> As long as we can have multiple planepiles detached from the main pile being rendered, and the flexibility of shuffling planes between piles I don't see a problem with that really.

i just really don't like that `ncplane_destroy()` can't be defined on root planes with these semantics. :/

**Comment by joseluis** [comment]
Yeah I meant in one call. 

Ideally (in my mind) the notcurses object would be the one having any plane appointed to render (does it need a particular size?). You could make `N`ble buffering by changing that pointer to another plane.

And maybe only allow destroying either childless planes or the whole tree of descendants? You could also either reparent any plane (alongside its children) or make it an orphan.

**Comment by dankamongmen** [comment]
Hrmmmm, I was writing out the rules, and realized something else: the `ncplane_destroy()` rule is insufficient for maintaining our invariants, unless we also prohibit a pile's root plane from being reparented elsewhere within its pile. This latter is a terrible restriction. Alright, root levels it is.

The fundamental problem arises from `ncplane_reparent()` being specified in terms of a parent plane. `ncplane_make_sibling()` would complete the operation set, but the two would have a grotesque overlap in the case of `C, A -> B :: A -> {B, C}`. You could do this with either `ncplane_reparent(C, A)` or `ncplane_make_sibling(C, B)`, which I don't like.

A far-out idea running counter to general trends (i.e. eliminating the standard plane): what if every pile was rooted by a standard plane? Reparenting something to itself would create a new pile AND a new standard plane for that pile: `x -> A :: { x,  S_p -> A }`. Then you make something a sibling of A by reparenting to `S_p`. Now, I don't at all want to do this, but if we had some virtual plane representing a pile...no, I don't like it.

We could of course have a hyperspecialized `ncplane_repile(A, B)` where B must be a root plane, `x -> A, B :: { x, { A, B } }`. Were we to do this, we'd probably **not** have `ncplane_reparent(A, A)` spawn a new pile; instead, `ncplane_repile(A, NULL)` would accomplish this. I think that might be the cleanest thing. `ncplane_reparent(A, A)` would remain a no-op, as it is now.

Hrmmmm....

**Comment by dankamongmen** [comment]
another idea to keep in mind: what if we dispensed with piles entirely, and instead allowed rendering to be initiated at some plane, and encompass only those planes recursively bound to it? i think this is not a great idea, but it's something to think about. it doesn't provide clean separation for threads, and we have a similar problem to that described above: are siblings of the plane rooting a render included in that render? so not a good approach, i think, but worth elucidating.

So if we went with the proposal above, we would have (for the immediate future, before defunding the standard plane):

* Every plane is bound to some plane.
* There is always a standard plane, and it is always bound to itself.
* A *pile* is rooted by a set of one or more *root planes*.
* When a new plane is created, a `ncplane* n` is provided:
  * if `n` is not `NULL`, the new plane is bound to `n`, and becomes a sibling of the planes bound to `n`
  * the new plane is otherwise bound to itself, and has no siblings, and thus becomes the root plane of a new pile
* A plane is a root plane iff it is bound to itself.
  * Corollary: the standard plane is always a root plane
  * Corollary: there always exists at least one pile, having as a root plane the standard plane
  * Corollary: Repiling a root plane to itself is a no-op
* A pile is merely a concept -- it has no unique store/address
  * Corollary: the root planes of a pile are the means to refer to a pile
  * Corollary: `ncplane_repile(A, x)` is equivalent for all x∈P such that x is a root plane of P
  * Corollary: Repiling a root plane to a subling plane is a no-op 
* If the last root plane of a pile is reparented elsewhere in the pile, or destroyed, its bound planes become root planes, and are reparented to themselves. They remain siblings.
  * Corollary: if the last root plane of a pile is destroyed, the pile ceases to exist
  * Corollary: if the last root plane of a pile is genocided, the pile ceases to exist
* If the last root plane of a pile is repiled into an existing pile, the pile ceases to exist
* It is an error to call `ncplane_repile(x, B)` when B is not a root plane
* `notcurses_stop()` destroys all planes across all piles

So the action matrix for `x = ncplane_create(B)`, `ncplane_reparent(x, B)`, and `ncplane_repile(x, B)` becomes

  **B**
|                            | NULL               |  non-root | root plane, not splane | standard plane | 
|-----------------------|---------------------|--------------|------------------------------|----------------------|
|ncplane_create() |  new pile          | B->x        |  B->x                           | B->x                  |
|ncplane_reparent(x),x is not root| error         |   B->x  | B->x                              | B->x                 |
|ncplane_reparent(x),x is root       | error       | B->x                            | B->x                |B->x|
|ncplane_reparent(x),x is stdplane| error        | error                            | error | error |
|ncplane_repile(x), x is not root | new pile | error | error | error |
|ncplane_repile(x), x is root | error | error | {B, x} | {B, x} |
|ncplane_repile(x), x is stdplane | error | error | error | error |
|ncplane_reparent(x), x is `NULL` | undef | undef | undef | undef |
|ncplane_repile(x), x is `NULL` | undef | undef | undef | undef |

am i missing anything?

**Comment by dankamongmen** [comment]
Hrmmm, there's another thing to consider. We render from top to bottom, but are keying our rendering here off of the root plane (which has no relation to its position on the z-axis). When we call `notcurses_render()` on a `struct notcurses*`, we have the top plane readily available. We have no such O(1) path under this scheme. Hrmm.

![images](https://user-images.githubusercontent.com/143473/99191906-d7af2480-273d-11eb-99de-ec1f6fc3e216.jpeg)

**Comment by dankamongmen** [comment]
OK, I'm absolutely not accepting an O(N) pointer chase at the top of the render. Gonna need to step back and think about this a good deal more. Shit.

**Comment by dankamongmen** [comment]
Further thought is still required. In the meantime, I realize @joseluis  might not realize I'm totally serious.

![mpv-shot0006](https://user-images.githubusercontent.com/143473/99197745-47370b00-2762-11eb-99f6-0ad28cbe663d.jpg)

America! <3

**Comment by joseluis** [comment]
@dankamongmen OMG that... looks dangerous...

**Comment by dankamongmen** [comment]
Insight(?): we've been expressing piles in terms of the root plane(s), because that's the pivot upon which repiling/reparenting turns. but other than that, there's no real need to keep track of the root plane. we can *identify* root planes in O(1) (check to see if they're bound to themselves), and that's the only direction we approach root planes from. sooooo...the logical thing is to refer to piles by their *top plane*, not their *root plane* (at least for `notcurses_render_pile()`. 

this comes down to an O(N) pointer chase *at pile creation time* (as opposed to for each render), and this can be elided if the user happens to have knowledge of what the topmost plane of the new pile will be (not at all an unreasonable expectation).

so reparenting will continue to turn on root planes, but rendering will be invoked on a topmost plane (or whatever plane you want to consider topmost), and planes from the pile below said plane. the user must identify this top plane, implicitly or explicitly. for the standard pile, it's of course always available in O(1) via `notcurses_top()`.

i think this just might fly.

**Comment by dankamongmen** [comment]
It occurs to me that all analysis is based on the principle that "a pile is not an object, but instead a concept"; is that the best way to move forward? A `pile` could be extracted from a `notcurses`, taking with it:

* stdplane (as root plane(s))
* top
* bottom

Now `ncplane_move_{top, bottom}` are defined on a `pile`, rather than a `notcurses`, as is `ncplane_repile()`. This greatly simplifies the action matrix above, while providing O(1) access to the z-axis extrema and root(s) for a given pile. This might be the way to go.

**Comment by joseluis** [comment]
I like it. I believe there must be a simple way to manipulate planes both separately and in an ordered bunch. We can could that bunch a pile, a list... It should be simple and fast for the common case. If there's a need of a more complicated structure to manage a bunch of planes, it should be possible to do it with separate unbounded planes.

**Comment by joseluis** [comment]
BTW would it be a FIFO stack? meaning it's gonna be rendered from top to bottom, and planes are added to the top?

It may be nice then to have the standard operations for manipulating the stack, [like in forth](http://wiki.laptop.org/go/Forth_stack_operators).

**Comment by dankamongmen** [comment]
> BTW would it be a FIFO stack? meaning it's gonna be rendered from top to bottom, and planes are added to the top?
> 
> It may be nice then to have the standard operations for manipulating the stack, [like in forth](http://wiki.laptop.org/go/Forth_stack_operators).

it will not, which is why i have renamed it a pile =]

**Comment by dankamongmen** [comment]
OK, I think I've got an acceptable plan now. Action items follow, with reasoning:

0) new *internal* type `ncpile` will be added

We pretty much have to have this struct, which I'd originally hoped to forgo. Why? Well, we need both a zaxis (for rendering) and a bindtree (for...binding). While most of the space for these data structures is inlined into the relevant `ncplane` structs, we need a handle on the zaxis top (for starting the render of a pile in O(1)) at minimum. I don't like the idea of making the user externally track the top of a pile's zaxis (as they would need do if we simply changed `notcurses_render()` to take an `ncplane`), nor do I like the idea of rendering requiring an O(N) walk up the zaxis. Rendering from an `ncplane` handle requires only the O(1) pile lookup now, so there's no need for the user to track the pile.

It is *possible* that we will keep the `ncpile` *concept* internal, though I don't think so -- a user calling `ncplane_render()` on an `ncplane` presumably expects to start rendering from that ncplane; a user calling `ncplane_move_top()` on two `ncplane`s A+B presumably expects an action on A+B, not A+B's pile. I'm unsure. It's a matter of taste, not of technology. So these will likely be renamed with `ncpile`, but the actual type will never be referenced externall.

1) `ncplane` will no longer point directly to `struct notcurses`
2) `ncplane` will point to `ncpile`
3) `ncpile` will point to `struct notcurses`

This way, we can reach both pile and containing context in two O(1) pointer derefs, requiring only one additional pointer per pile for this tracking. Looking up a notcurses struct from an ncpile doesn't seem to happen frequently enough that the extra pointer deref would have much effect on performance.

4) A new flag will be added to `ncplane_options`, `NCPLANE_OPTION_NEWPILE`, creating the new `ncplane` on a new `ncpile`.

This allows the cleanest creation of a pile, when it's known that a new plane is intended to start one. Extracting a plane from an existing pile is going to have some overhead, as we'll see below.

5) An `ncplane` reparented to itself becomes the root plane of a new pile, unless it is already a root plane, in which case the reparenting is a no-op. Bound planes and siblings *do not* join it in the new pile. The new zaxis contains of one member.

This action is currently a no-op in all cases. Since a plane parented to itself is a root plane, this makes total sense as an expansion of the funtion. Creation of and extraction from zaxes is O(1).

6) A new function, `ncplane_make_sibling()`, will be added.

This allows an `ncplane` to be made a sibling of another. `ncplane_reparent(ncplane_parent(A))` doesn't work if A is a root plane (sadly), else this would be mere semantic sugar. This function is being added to cover the case where we want to make a plane part of the root set of a pile. I imagine this will be a very rare event, and hesitate to add this function, but it doesn't make anything more complex -- it's just something of a wart.

An alternative would be to have root planes return an `ncpile` as their parent, to which one could reparent a plane. This has several downsides: it exposes `ncpile`, it requires `ncplane_parent()` to return either an `ncplane` or an `ncpile`, and it requires `ncplane_reparent()` to accept either an `ncplane` or an `ncpile`. I feel the approach of `ncplane_makesibling()` is less an overall wart.

A second alternative would be to say "fuck it" and not introduce this function at all. That's such a hit to conceptual simplicity that I can't countenance it. But maybe I'm missing something...?

Note that a sibling is also created via `ncplane_dup()`.

7) A new function, `ncplane_reparent_family()`, will be added. This function works the same way as `ncplane_reparent()`, except that it brings along any bound planes.

This is an extension of what already exists after implementing (5), since the current `ncplane_reparent()` does not bring along bound planes (they are rebound to the plane's original parent). Note that extracting child planes, if they exist, requires a traversal of the originating zaxis having both O(N) time and O(N) state--a semi-expensive operation. Piles are ideally created at `ncplane_create()` time, and operated on from there. When reparenting a family within the same pile, there's no need for these O(N) operations, as the zaxis is not changed.

This is entirely orthogonal to the overall goals of this change, and who knows, maybe we won't do it.

8) Reparenting an `ncplane` to an `ncplane` within another pile places it immediately above the new parent on the zaxis. Reparenting an `ncplane` as a family sees the same behavior, with all moved children placed atop the reparented plane, retaining their z-order from the source pile.

There's no logic to where we place the reparented plane within the new pile's zaxis, so we pick a place -- above the new parent. The most reasonable alternatives would be either the top or bottom of the new zaxis. There's no real reason to pick any of them -- it's an O(1) splice no matter what -- and this seems most natural.

Just as they do now, bound planes are reparented to the parent of the reparented plane. If the reparented plane is a root plane, any bound planes now become root planes.

9) When no references exist to an `ncpile`, it is destroyed.

This is one reason to keep the `ncpile` struct hidden -- we know there are no references outstanding once we detach the last `ncplane`. This doesn't require reference counting or anything like that; we just kill the pile when a plane which is all of a root, childless, and siblingless is detached.

10) `notcurses_render()` is loosely deprecated, and operates on the standard plane's pile.

We will deemphasize `notcurses_render()`, but there's no immediate need to get rid of it.

11) `ncpile_render_buffer()` will be added, taking as its argument an `ncplane`, and operating on its pile.

Pretty self-explanatory. I prefer this to `ncplane_render_buffer()` to emphasize that we start rendering at the pile's top plane, not at the provided plane. `ncpile_render_buffer()` called on any plane from the standard pile is equivalent to `notcurses_render_to_buffer()`.

12) It is an error to concurrently rasterize rendered buffers, including rasterizing one while calling `notcurses_render()` (which implicitly rasterizes).

I should hope that the reasoning for this is obvious. I list it primarily to emphasize that rasterizing buffers in a different order from how they were rendered is perfectly legal, since the rasterization optimizations based on the currently-rendered state are not relevant to the process of rendering.

13) `notcurses_stop` will continue to clean up all state.

No need to manually ensure all `ncplane`s are destroyed; `notcurses_stop()` continues to handle this.

14) It is legal to concurrently mutate distinct piles in any way one dreams.

The entire point of this exercise. This mainly just means we don't want to have any concurrently-accessed global list of ncpiles, nor any data structure that contains planes from multiple piles. I think we need to have the former to ensure proper `notcurses_stop()` cleanup; that's fine, we'll just throw a lock around it (mutating this list will be a rare operation). This list will take the form of a doubly-linked list to ensure O(1) splicing.


This seems entirely backwards-compatible with the old school (save that `ncplane_reparent()` now has an action for what was previously a no-op (but silly) case). I'm willing to break people who were relying on this no-op (a survey of known Notcurses projects does not suggest that anyone is). It adds very little overhead:

 * state: three 64-bit pointers per pile
 * time: only O(N) operation is extracting the planes from a pile's zaxis when calling `ncplane_reparent_family()`

yet opens up a bold new world of parallelism and flexibilty, and doesn't complicate the way for #1109 (at which time we'll have a fully Copernican universe).

https://www.youtube.com/watch?v=ikMAH7k3pz4

**Comment by dankamongmen** [comment]
I like this. The question comes down now to whether we want to cut 2.0.5 now, or wait for this. 2.0.5 carries some good fixes for `notcurses-view`, lots of rust changes, `ncdirect_render_image()` fix, manpage fixes, and the `horiz` change...hrmm. I'm thinking maybe we go ahead and cut 2.0.5, given tomorrow's [presentation](https://mdco2.mini.debconf.org/talks/6-notcurses-making-terminals-do-things-that-were-never-intended/)...yeah.

**Comment by dankamongmen** [comment]
Oh wait we don't need that new option; we can just accept a `NULL` for the first argument to `ncplane_create()`, right right.

**Comment by dankamongmen** [comment]
* [ ] define new internal type `ncpile` and replace `notcurses` link in `ncplane`
* [ ] implement internal `ncplane_destroy()`
* [ ] create doubly-linked locked circular list of `ncpile`s in `notcurses`, free them in `notcurses_stop()`
* [ ] add new internal function `ncpile_create()`
* [ ] accept `NULL` for `ncplane_create()`, call `ncpile_create()` in `ncplane_new_internal()`
* [ ] implement family detach in `ncplane_reparent()`
* [ ] accept `NULL` for `ncplane_reparent_family()`
* [ ] implement zaxis detach in `ncplane_reparent_family()`
* [ ] call `ncpile_destroy()` for emptied ncpile in `ncplane_reparent_family()`
* [ ] update `ncplane_move_top()` to use plane's pile
* [ ] update `ncplane_move_bottom()` to use plane's pile
* [ ] update `ncplane_move_above()` to reject cross-pile moves
* [ ] update `ncplane_move_below()` to reject cross-pile moves
* [ ] implement cross-pile moves in `ncplane_reparent_family()`
* [ ] add new function `ncpile_render()`
* [ ] reimplement `notcurses_render_to_buffer()` using `ncpile_render()`
* [ ] add new function `notcurses_rasterize_buffer()`
* [ ] reimplement `notcurse_rasterize()` using `notcurses_rasterize_buffer()`

**Comment by dankamongmen** [comment]
FUCK. if we pass `NULL` to `ncplane_create()`, how do we get to the `notcurses*` object? arrrrrrrhgrhrgr

**Comment by dankamongmen** [comment]
that sucks so much, ugh.

we can either:
a) break backwards compat on `ncplane_create()`, which i'm not willing to do
b) require a non-`NULL` `ncplane`, which is used only to get the `notcurses` struct. we'll add back the `NCPLANE_OPTIONS_NEWPILE` flag. this wouldn't be too terrible, except you can't use it to bootstrap in the absence of a standard plane, and the `ncplane` argument is arbitrary
c) add `ncplane_make_root(notcurses*, ncplane*N0, ncplane*N1)` in place of `ncplane_makesibling()`.  a `NULL` `N1` would make a new pile. a root `N1` would make `N0` a sibling of `N1.
d) add `ncplane_create_newpile(notcurses*, ncplane_options *nopts)` which always creates a new pile.

**Comment by dankamongmen** [comment]
> that sucks so much, ugh.
> 
> we can either:
> a) break backwards compat on `ncplane_create()`, which i'm not willing to do
> b) require a non-`NULL` `ncplane`, which is used only to get the `notcurses` struct. we'll add back the `NCPLANE_OPTIONS_NEWPILE` flag. this wouldn't be too terrible, except you can't use it to bootstrap in the absence of a standard plane, and the `ncplane` argument is arbitrary
> c) add `ncplane_make_root(notcurses*, ncplane*N0, ncplane*N1)` in place of `ncplane_makesibling()`. a `NULL` `N1` would make a new pile. a root `N1` would make `N0` a sibling of `N1. d) add `ncplane_create_newpile(notcurses*, ncplane_options *nopts)`which always creates a new pile. e) add the new flag`NCPLANE_OPTIONS_NEWPILE`, and a new field to `ncplane_options`at the end. this field takes a`notcurses`, and is only valid in the presence of `NCPLANE_OPTIONS_NEWPILE`. if `NEWPILE`is provided, this must be set to a valid`notcurses`, and `n` is ignored.
> 
> i'm thinking either d or e.

went with e.

**Comment by dankamongmen** [comment]
we don't need `ncplane_makesibling()` after all:

* you can make a normal sibling by reparenting to the desired sibling's parent
* you can make a root sibling, should this unlikely situation arise, by reparenting 'n' and the desired siblings to a temporary plane at the root of a new pile, then destroying the temporary plane. convoluted as hell, but it closes the theoretical gap, and who cares so long as it's possible?

good.

**Comment by dankamongmen** [comment]
If a plane is created with {y, x}=={1, 1}, and it is bound to a plane at {2, 2}, it is logically at {3, 3}.

when we reparent it (especially as a root plane), does it remain at {3, 3}? or go to {1, 1}? i think the answer is {1 + `margin_t`, 1 + `margin_l`}; that makes the most sense.

**Comment by dankamongmen** [comment]
> and when a plane becomes a root plane, throw `margin_t` and `margin_l` into it via sum.

yeah, that appears to work.

**Comment by dankamongmen** [comment]
Closing this as done; I've moved the rendering changes to new bug #1135.
