### ISSUE TITLE
Improve resolution

### ISSUE THREAD

**Issue by ton** [dankamongmen/notcurses#1079]
See: https://github.com/trashhalo/imgcat/issues/3

Maybe this idea is already employed by Notcurses, if not, I think Notcurses can profit as well?

**Comment by dankamongmen** [comment]
We're already doing this -- this is the "halfblock blitter", aka `NCBLIT_2x1`. We actually go beyond this with the Quadblitter `NCBLIT_2x2`, which uses quadrants and three-fourth quadrants. Indeed, we might go even further with the Hexblitter (#1071).

If you're not seeing this high level of resolution, you're likely not setting `LANG` to a UTF-8 encoding.

**Comment by dankamongmen** [comment]
Closing this as already implemented. If you're having problems getting this level of resolution, let me know.
