### ISSUE TITLE
add utf16 output forms for the benefit of thrice-accursed windows

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1092]
Windows, sadly, loves UTF16. It is likely that we would need to handle UTF16 from Windows applications. We should support emitting UTF16 as output, perhaps. See #463.

**Comment by WSLUser** [comment]
UTF8 is definitely fully supported on Windows though there's no denying that older win32 programs certainly love utf-16 more. In fact, the Windows Terminal team created a library for dealing with utf-8  conversion to utf-16. https://github.com/microsoft/terminal/blob/main/src/inc/til/u8u16convert.h. Maybe that may help.

**Comment by dankamongmen** [comment]
> UTF8 is definitely fully supported on Windows though there's no denying that older win32 programs certainly love utf-16 more. In fact, the Windows Terminal team created a library for dealing with utf-8 conversion to utf-16. https://github.com/microsoft/terminal/blob/main/src/inc/til/u8u16convert.h. Maybe that may help.

thanks for the tip! as a Microsoft employee, i really ought learn something about our stuff one day.

**Comment by WSLUser** [comment]
I had no idea you are an MS employee. All their libraries were created specifically for them to use, so it may need some adaption for use in this project but since they both have C++, it certainly makes that job a good bit easier. Doing this for something like Python will be an extreme pain though (I've had so many battles trying to get something written in python 2 utf-8 compatible when converting it to python 3. It's why adhering to the standards should be done, life becomes much easier for everyone then for stuff like this.)

**Comment by dankamongmen** [comment]
> I had no idea you are an MS employee.

As of about three months ago =]. I'm working on their satellite/space team.

> All their libraries were created specifically for them to use, so it may need some adaption for use in this project but since they both have C++, it certainly makes that job a good bit easier. Doing this for something like Python will be an extreme pain though (I've had so many battles trying to get something written in python 2 utf-8 compatible when converting it to python 3. It's why adhering to the standards should be done, life becomes much easier for everyone then for stuff like this.)

I'm going to look into all of this over the Thanksgiving break, I think/hope.

**Comment by dankamongmen** [comment]
see @magiblot's comment in #463:

> UTF-16 support is certainly not necessary. You can interact with the console in UTF-8 as long as you configure the console codepage properly. Additionally, since 2018, UTF-8 is also supported in the C Runtime. So you can write a fully capable Unicode application on Windows without a single wide char, and I find it a good idea to encourage users to do so. The problem in notcurses will be that all interfaces assuming wchar_t to be 32-bit (if there are any) will be ill-formed on Windows.

i think we're freeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
