### ISSUE TITLE
eliminate concept of standard plane

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1109]
This has never been necessary. It's not like it serves as a backstop, ensuring every cell is solved when rendering, since it can be made transparent on all three axes (glyph, fg, bg). The only reason it ever existed was to facilitate porting of NCURSES programs, with its implicit `screen`.

With that said, code everywhere expects it to exist. We don't want to break them. `notcurses_stdplane()` and `notcurses_stddim_yx()`, then, must continue to exist as expected. That's easy enough: we will continue to track a special plane as we did the standard plane, but we will create it upon the first external reference to it, rather than upon `struct notcurses` creation.

The documentation will then be changed to place less emphasis on the standard plane. The behavior of `notcurses_stdplane()` and friends will be documented, but as a quaint holdover from a less elegant age.

cast off this taint, and become taintless!

**Comment by dankamongmen** [comment]
As part of this, we will need to keep the actual screen geometry in the `struct notcurses`, rather than inferring it from the stdplane's geometry.

**Comment by dankamongmen** [comment]
*Axiom: Without actively deprecating the standard plane, it will never go away.*

I'm not then sure how feasible this is, given that the standard plane is referred to in every existing bit of notcurses code. Which, let's admit, is not terribly many. But it won't win us friends to invalidate every single bit of code in existence in the name of conceptual simplicity, and I'm a man who loves conceptual simplicity more than anything save bacon breakfasts, yelling at tornados from one of my many non-functioning pickup trucks, and shooting endangered species with recoilless rifles, as I first did upon becoming an american man, the most magnificent kind of man in the world. but i digress.

If someone doesn't want to work with the standard plane, they create a new pile immediately, and never have to deal with the standard plane. In the meantime, the 99% who *do* get it without a bunch of pretending it doesn't exist, without a bunch of conditional code implementing the backwards compatibility, without needing to think about piles until they need to for performance reasons, without cursing our names as they render their garments and wear sackclothes (bible reference. christianity, baby! america!)

We shall retain the standard plane, and its standard pile, and those who eschew them can violently fight it out with those who do not in the comments section on Reddit, should we ever (God and President willing) have enough users that they can have a good fight, or as the rest of the world calls it, soccer.

closing as nonfix, and continuing to drink.

**Comment by joseluis** [comment]
I'm seriously considering not exposing the stdplane in the higher level rust wrappers.

**Comment by dankamongmen** [comment]
> I'm seriously considering not exposing the stdplane in the higher level rust wrappers.

that's fine, but if you're going to do that, i would also eliminate any concept of the standard pile, i.e. do not export `notcurses_render()` but only `ncpile_render()`. force your user to create their first plane in a new pile by calling `ncpile_create()`. if you try to hide the concept of the standard plane, but have them working in the standard pile, there will be all manner of confusion as they e.g. try to walk the z-axis and find this mystery plane that they can't destroy.

it'll also be a bit confusing for rustaceans to read the man pages / C documentation and see all this talk of standard planes and piles, but if you write sufficiently good rust documentation / examples, that oughtn't be a problem.

other than that, i think that's a totally viable approach, and wish you warm luck with it.

**Comment by joseluis** [comment]
That's very good info. I will ponder on it.
