### ISSUE TITLE
pypandoc not in dependencies ?

### ISSUE THREAD

**Issue by thenger** [dankamongmen/notcurses#1110]
Hello,
I tried to install notcurses with pip3 and got `ModuleNotFoundError: No module named 'pypandoc'`

```
#> pip search notcurses
notcurses (2.0.4)  - Blingful TUI construction library (python bindings)
#> pip install notcurses
Defaulting to user installation because normal site-packages is not writeable
Collecting notcurses
  Downloading notcurses-2.0.4.tar.gz (10 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3ml5axfz/notcurses/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3ml5axfz/notcurses/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_owqvegc
         cwd: /tmp/pip-install-3ml5axfz/notcurses/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3ml5axfz/notcurses/setup.py", line 5, in <module>
        import pypandoc
    ModuleNotFoundError: No module named 'pypandoc'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Shouldn't pypandoc be in the requirements ?

**Comment by dankamongmen** [comment]
It certainly should. Thanks for the report! I'll get this fixed ASAP.

**Comment by dankamongmen** [comment]
Reproduced failure locally. Should have a fix momentarily.

**Comment by dankamongmen** [comment]
@thenger , perhaps you can assist me here (I am not a Python expert). I would normally place dependencies in `setup.py`, yes? But since I am importing `pypandoc` in `setup.py` itself, that doesn't work. Can I use `setup.cfg` for this, perhaps?

**Comment by dankamongmen** [comment]
The only method I've found thus far is putting pypandoc in `requirements.txt`, and using the following sequence to install:

```
pip install -r requirements.txt
python setup.py install
```

but i don't think this helps people trying to install directly from PyPi, like you are. Ugh.

**Comment by dankamongmen** [comment]
OK, I think I might have a solution, though it's grotesque.

**Comment by dankamongmen** [comment]
I'm not certain that this is going to work, but hopefully it will? Let me know if you continue to see problems, @thenger . Thanks!
