### ISSUE TITLE
make NCBLIT_3x2 the default for NCSCALE_STRETCH once it works in most terminals

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1114]
`NCBLIT_3x2` is superior to `NCBLIT_2x2` when there's proper font support (it's stictly superior regarding aspect ratio as well as resolution, 1.5:1 instead of 2:1). While we probably don't want to make it the `NCBLIT_DEFAULT` choice for `NCBLIT_STRETCH` just yet, due to font problems (see e.g. #1099), it ought eventually become the default. Reminder to investigate regularly, and switch when satisfied.

**Comment by dankamongmen** [comment]
kitty 0.19.2 came out today in Debian Unstable, but my fix for sextants isn't yet present (it'll be in 0.19.3, not yet released). I don't think we can make this switch until that's at least in Unstable.

**Comment by dankamongmen** [comment]
Sooooooooooooooooooooooooooooooooo i'm wondering whether we might not check for an environment variable, and if that environment variable is set, use `NCBLIT_3x2` for `NCBLIT_DEFAULT`+`NCSCALE_STRETCH`. This environment variable won't be *necessary* for use of sextants (`NCBLIT_3x2` will always get you sextants if they're available, and we'll still change the default at some point), but it'll get them.  Maybe.

**Comment by dankamongmen** [comment]
We also need wait for everyone to have glibc 2.32, which brings in necessary Unicode 13 changes.

**Comment by dankamongmen** [comment]
Since we're now already doing grisly per-emulator stuff (see kitty fix from #1117), we might as well turn this on for terminals we know to support it. Cat's out of the bag on this one. First thing we'll need do is move `ncvisual_default_blitter()` into the library (it's currently an inline).

**Comment by dankamongmen** [comment]
> We also need wait for everyone to have glibc 2.32, which brings in necessary Unicode 13 changes.

this has been invalidated by the move to direct blitting.

i'm thinking i'll turn it on for any `TERM` containing `vte` or `kitty`, maybe also `gnome` (though I think the proper TERM for `gnome-terminal` is `vte-256color`).

**Comment by dankamongmen** [comment]
urk, there's no pretty way to do this, since `ncvisual_default_blitter()` doesn't take any big state objects (`notcurses`/`ncdirect`), and this is clearly a stateful decision. we'd need be able to pass in a third argument (new function so as not to break compat) to indicate whether we'd decided sextants were good in this environment. i guess that's not *such* an uncouth thing...

**Comment by dankamongmen** [comment]
About to turn this on...

**Comment by dankamongmen** [comment]
looks like i busted the rust wrappers. i can fix this, but @joseluis seems to be doing some Christmas Day hacking of his own, so i'll leave it to him for the moment: https://drone.dsscaw.com:4443/dankamongmen/notcurses/5124

**Comment by joseluis** [comment]
happy hacking christmas @dankamongmen , I broke the tests earlier before by forgetting to include a couple of files with necessary changes.

**Comment by dankamongmen** [comment]
Alright, 2.1.2 distributed this for kitty and VTE. We'll enable others as they come available, and make it the general default once most everything supports it.
