### ISSUE TITLE
rust: bye bye no_std

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1119]
It turns out the very very early decision of making the rust bindings no_std was misguided in retrospective.

It was easy then, but didn't anticipate how much it's costing me in time and lack of fun to devise ugly workarounds that would be fast and beautifil having access to parts of the standard library, like all the IO...

Funnily enough we don't have any real need to support embeded systems. So it's a PITA wihout real advantages. Therefore I'll make a commit removing all the no_std related stuff from the code.

@dankamongmen we will no longer need to depend on libc_print and cstr_core.

**Comment by dankamongmen** [comment]
outstanding! i will continue to try to package `libc_print` for debian, but appreciate it no longer being a blocker.

**Comment by dankamongmen** [comment]
not sure if you're aware, but the rust unit tests have been failing in our autobuilder for about four releases now.

most recent: https://drone.dsscaw.com:4443/dankamongmen/notcurses/4597/2/2
first: https://drone.dsscaw.com:4443/dankamongmen/notcurses/4595/2/2

I notice:

```
warning: unused import: `std::ffi::CString`
1618	 --> examples/full-text.rs:3:5
1619	  |
1620	3 | use std::ffi::CString;
1621	  |     ^^^^^^^^^^^^^^^^^
1622	  |
1623	  = note: `#[warn(unused_imports)]` on by default
1624	
1625	warning: unused macro definition
1626	  --> examples/full-text.rs:13:1
1627	   |
1628	13 | / macro_rules! cstring {
1629	14 | |     ($s:expr) => {
1630	15 | |         CString::new($s).unwrap().as_ptr();
1631	16 | |     }
1632	17 | | }
1633	   | |_^
1634	   |
1635	   = note: `#[warn(unused_macros)]` on by default
1636	
1637	    Finished test [unoptimized + debuginfo] target(s) in 20.57s
1638	     Running target/debug/deps/libnotcurses_sys-69f0383df9295c7b
1639	
1640	running 68 tests
```

**Comment by dankamongmen** [comment]
> not sure if you're aware, but the rust unit tests have been failing in our autobuilder for about four releases now.
> 
> most recent: https://drone.dsscaw.com:4443/dankamongmen/notcurses/4597/2/2
> first: https://drone.dsscaw.com:4443/dankamongmen/notcurses/4595/2/2
> 
> I notice:
> 
> ```
> warning: unused import: `std::ffi::CString`
> 1618	 --> examples/full-text.rs:3:5
> 1619	  |
> 1620	3 | use std::ffi::CString;
> 1621	  |     ^^^^^^^^^^^^^^^^^
> 1622	  |
> 1623	  = note: `#[warn(unused_imports)]` on by default
> 1624	
> 1625	warning: unused macro definition
> 1626	  --> examples/full-text.rs:13:1
> 1627	   |
> 1628	13 | / macro_rules! cstring {
> 1629	14 | |     ($s:expr) => {
> 1630	15 | |         CString::new($s).unwrap().as_ptr();
> 1631	16 | |     }
> 1632	17 | | }
> 1633	   | |_^
> 1634	   |
> 1635	   = note: `#[warn(unused_macros)]` on by default
> 1636	
> 1637	    Finished test [unoptimized + debuginfo] target(s) in 20.57s
> 1638	     Running target/debug/deps/libnotcurses_sys-69f0383df9295c7b
> 1639	
> 1640	running 68 tests
> ```

That warning clearly has nothing to do with this, on further exploration.

I added an `env TERM=xterm` to the drone `cargo t` invocation. That might fix this. If so, you probably still want to look into what's going on (perhaps a missed error check?) -- I doubt that a segfault is what you want if `TERM` is unset.

**Comment by dankamongmen** [comment]
Yeah, that fixed it, but see my comments above.

**Comment by joseluis** [comment]
The error seems to be caused by calling `notcurses_canchangecolor()` in the unit test... Since the other two things in there are starting and stopping notcurses, which doesn't fail in other tests...

```
Caused by:
--
process didn't exit successfully: `/drone/src/rust/target/debug/deps/libnotcurses_sys-69f0383df9295c7b --test-threads 1 --nocapture` (signal: 11, SIGSEGV: invalid memory reference)
test notcurses::test::notcurses_canchangecolor ...
```

**Comment by dankamongmen** [comment]
> The error seems to be caused by calling `notcurses_canchangecolor()` in the unit test... Since the other two things in there are starting and stopping notcurses, which doesn't fail in other tests...
> 
> ```
> Caused by:
> --
> process didn't exit successfully: `/drone/src/rust/target/debug/deps/libnotcurses_sys-69f0383df9295c7b --test-threads 1 --nocapture` (signal: 11, SIGSEGV: invalid memory reference)
> test notcurses::test::notcurses_canchangecolor ...
> ```

You definitely can't call `notcurses_canchangecolor()` on a `NULL` `struct notcurses`. If `notcurses_init()` fails, are you failing out of the unit test?

**Comment by joseluis** [comment]
hmmm... you're right, I  thought I already have done a test just for notcurses_init but no. So I just made it.

I also enabled the `--no-fail-fast` cargo option, for drone, so that it will run all the tests even if some fail, which should give us a more complete picture when something goes wrong.

**Comment by dankamongmen** [comment]
woo-hoo, thanks!
