### ISSUE TITLE
comparable API version

### ISSUE THREAD

**Issue by umlaeute** [dankamongmen/notcurses#1131]
It would be great if we were able to detect the notcurses-version at compile time.

Currently the `notcurses/version.h` header gives us the version information as strings, making it great for doing runtime-checks, but not for compile-time checks:

https://github.com/dankamongmen/notcurses/blob/a2cc5f096adb3991f264d96657b45a050fa8df2a/tools/version.h.in#L5-L8

Something like the following (taken from the famouse linux `KERNEL_VERSION` macro) might help:

~~~C
#define NOTCURSES_VERSION             \
    ( (@notcurses_VERSION_MAJOR@<<16) \
    + (@notcurses_VERSION_MINOR@<< 8) \
    +  @notcurses_VERSION_PATCH@)
~~~

or (producing human-readable versions):

~~~C
#define NOTCURSES_VERSION                \
    ( (@notcurses_VERSION_MAJOR@ *10000) \
    + (@notcurses_VERSION_MINOR@ *  100) \
    +  @notcurses_VERSION_PATCH@)

~~~

### reasoning
While it seems that [notcurses2 is committed to providing a stable API](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=975029#5), this seems to be not entirely true.
cf:
>  [version 2.0.5 has an incompatible change to `ncplane_options`, plus some other functions](https://salsa.debian.org/multimedia-team/snd/-/blob/master/notcurses_s7.c#L14)

It would be nice if we could catch the API-version during compilation (even with simple build-systems)

The above suggestion (version2) would allow us to do something like:

~~~C
#if (defined NOTCURSES_VERSION) && (NOTCURSES_VERSION > 20005)
//...
#else
# warning old notcurses version detected! proceeding anyhow
//...
#endif
~~~

**Comment by dankamongmen** [comment]
Completely agreed; I'll have something out ASAP.

**Comment by dankamongmen** [comment]
OK, a human-readable version is already provided via `notcurses_version()`, and it's the real version string, not the weird totally-comparable one. I've changed around `version.h` to provide everything else you've requested, and am putting a PR up now.

**Comment by dankamongmen** [comment]
@umlaeute , please take a look at #1136, and let me know if it covers everything you'd like here.

**Comment by dankamongmen** [comment]
I've gone ahead and merged #1136, which I believe to solve this problem. If you agree, please close this bug. If you disagree, let me know what I've missed =]. Thanks for the report, and sorry for the changes that made this necessary!

**Comment by umlaeute** [comment]
thanks. should work.

one note though (before i close this):
> a human-readable version is already provided via notcurses_version(), and it's the real version string, not the weird totally-comparable one

well my "human-readable version" was meant for developers to be able to quickly add the proper `#if` clause.
e.g.
~~~C
#if (NOTCURSES_VERNUM_ORDERED > 20005)
~~~

is much easier to read than:

~~~C
#if (NOTCURSES_VERNUM_ORDERED > 131077)
~~~

the problem with the latter is, that even i as a programmer (who deals a bit with power-of-two numbers), have a hard time to convert a version `2.0.5` to `131077`, whereas i can do the calculations for `20005` in my head...

the linux-kernel provides a macro, so you could actual do:

~~~C
#if (NOTCURSES_VERNUM_ORDERED > NOTCURSES_VERSION(2,0,5))
~~~

which is even more readable (and doesn't expose the implementation of how to get the ordered-version number to the "user")

**Comment by dankamongmen** [comment]
> thanks. should work.
> 
> one note though (before i close this):
> 
> > a human-readable version is already provided via notcurses_version(), and it's the real version string, not the weird totally-comparable one
> 
> well my "human-readable version" was meant for developers to be able to quickly add the proper `#if` clause.
> e.g.
> 
> ```c
> #if (NOTCURSES_VERNUM_ORDERED > 20005)
> ```
> 
> is much easier to read than:

Yeah it certainly is. Alright, I can revise this, or if you'd like to submit a PR, I can merge that. Either way, I'll try to have this resolved in the most perfect possible fashion by this evening. Thanks for your attention to detail, and interest in the project!

**Comment by dankamongmen** [comment]
Alright, I think the way to do this is your last remark: I'll introduce a macro accepting `(major, minor, patch)`, suitable for opaque comparison to `NOTCURSES_VERNUM_ORDERED`. I'll add this momentarily, and it'll be present in 2.0.8/2.1.0.

Thanks for staying on this and helping make it be the best solution possible!

**Comment by dankamongmen** [comment]
I think with https://github.com/dankamongmen/notcurses/commit/e3b2c91999ef7ca8b3ba7d0f3a4be7817f4660c9 we're where we want to be. Please reopen if you have further concerns. Thanks for the quality report!

**Comment by umlaeute** [comment]
looks great.
