### ISSUE TITLE
Support strikethrough text

### ISSUE THREAD

**Issue by MasFlam** [dankamongmen/notcurses#1138]
There is an escape for this, and many terminals nowadays support it, for example kitty and kde konsole. It frankly strikes me (pardon the pun) that `NCSTYLE_STRIKETHROUGH` isn't a thing.

**Comment by dankamongmen** [comment]
Oh neat. Alright, all we would need is the control sequences that drive this. `terminfo(5)` doesn't document any such sequences, but if they exist, we can use them, and I can submit a patch to terminfo for inclusion. Do you happen to know the necessary control sequences? I'm happy to support them, and we have plenty of room in the 16 bits of the stylemask.

**Comment by MasFlam** [comment]
The sequence is `\e[9m`. As far as terminfo entries go, when I use `man terminfo` and search `/strike` then this is what matches:
```
Variable booleans    Capname    TCapcode    Description
[...]
erase_overstrike     eo         eo          can erase overstrikes with a blank
[...]
over_strike          os         os          terminal can overstrike
[...]
```
And I think those are of interest here

**Comment by dankamongmen** [comment]
So far as I can tell, those are capabilities for printer-oriented terminals that use real overstrikes. I just checked VTE, Kitty, and Alacritty, and none of them list these capabilities (use `infocmp -e` to see the running terminal's (or rather the defined `TERM` variable's) capabilities).

So I'm happy to add this escape, but I am worried by the fact that we'll have no way to detect support :/. It also won't be present in the `ncv` bitarray, of course, but that's rather less of a concern.

I can send a patch to terminfo regarding strikethrough, but attempts to have terminfo extended have not met with much success, sadly :(. I'll go ahead and prepare a PR and see how it looks on a few terminals. If the major terminals work with it, I'm all for it. If it craps out on some, I'll be more hesitant without an ability to detect support.

**Comment by dankamongmen** [comment]
I could always start augmenting terminfo with our own hard-won discoveries, based off `TERM`. I've not wanted to open that door, but it's not an unreasonable row to hoe...

**Comment by MasFlam** [comment]
That's what the Go library [tcell](https://github.com/gdamore/tcell) I think is doing, since they have a `StrikeThrough` entry. The `terminfo/` directory contains their built-in database, and you can load data from the system terminfo too. Although they might just hard-code it themselves? I dunno. But if there's no way to know if a terminal supports the feature, maybe a separate function to tell notcurses that I want it to be enabled would be possible? The user could be for example prompted beforehand and such information could be relayed onto notcurses.

**Comment by dankamongmen** [comment]
Yeah I'm thinking that if we do add this, I'm going to wrap it in some `NOTCURSES_OPTION_EXTRASEQUENCES` or something, that you have to manually enable. Callers can then rig that up to their MVC however they'd like. Either way, I'm doing this now.

**Comment by dankamongmen** [comment]
Is there any way to turn it off other than a blanket `sgr`? I'll go look.

**Comment by dankamongmen** [comment]
Ahhh looks like SGR 29 turns it off, good good.

**Comment by dankamongmen** [comment]
Hey, it works, how about that.

**Comment by dankamongmen** [comment]
Well, it works **sometimes**. It looks like it can't be used with any other properties? Maybe my bug, who knows yet.

output of `sgr-direct` follows. note strikethrough at 00000200.

![2020-11-25-194019_802x1057_scrot](https://user-images.githubusercontent.com/143473/100294881-1d49c980-2f56-11eb-87d1-b836e0cc5b01.png)

**Comment by dankamongmen** [comment]
> Edit: And according to their data the following terminals support it: Konsole, Simple Terminal (st), xterm-kitty, xterm, xterm-88color, xtern-256color, alacritty & tmux. So out of the most used ones that don't have support, GNOME comes to mind.

remember that gnome-terminal is just a skin of VTE, so results there are likely the same for all other VTE terminals (xfce4-terminal), etc.

nonetheless, xfce4-terminal 0.8.9.2 (Xfce 4.14) as packed in arch seems to work, at least when no other styles are used. see above.

**Comment by dankamongmen** [comment]
i am seeing the same behavior from alacritty and kitty (only 0x200 shows strikethrough), so maybe it is my bug after all? if anyone can generate strikethrough with some other style and show me, that would let me know immediately.

**Comment by dankamongmen** [comment]
Alright, let me know if you see any deficiencies with this. Hack on! It'll be present in 2.1.0/2.0.8.

**Comment by MasFlam** [comment]
You said that you had problems mixing strikethrough with other styling, and my build of notcurses also has problems with it (I'm on kitty btw). But when I go to `echo -e 'abc \e[9;4;7m def \e[m ghi'`, it mixes strikethrough+underline+reverse without a problem. This might be a bug on notcurses side maybe then?
![image](https://user-images.githubusercontent.com/19764975/100318323-21a9cd00-2fbe-11eb-8479-d7be716057cb.png)
Wha output I can see from notcurses is also random at times:
* in `sgr-full` `a = strikethrough` is not strikethrough
* in `agr-direct` only `00000200` is strikethrough

in `sgr` there is no strikethrough because only 9 bits of the style bitmask are tested.

**Comment by dankamongmen** [comment]
Yeah, definitely looks like we've got a bug to shake loose, then. Thanks for the extra details! I'll look into this shortly.

**Comment by dankamongmen** [comment]
Confirmed that `echo -e 'abc \e[9;4;7m def \e[m ghi'` yields underline+strike+reverse in VTE. Alright, I'll get this working today.

**Comment by dankamongmen** [comment]
Closer...
![2020-11-27-152217_802x902_scrot](https://user-images.githubusercontent.com/143473/100482104-5bfd9200-30c4-11eb-9e4d-6e1dffbb880f.png)

**Comment by dankamongmen** [comment]
I think both italics and struck might be broken when used in conjunction with other SGR options in fullscreen mode. Actually, hrmmm, italic bold works. Interesting.

**Comment by dankamongmen** [comment]
Better.

![2020-11-27-152819_802x902_scrot](https://user-images.githubusercontent.com/143473/100482385-33c26300-30c5-11eb-9fa2-804cbd802b56.png)

**Comment by dankamongmen** [comment]
Need to verify direct mode, but fullscreen mode looks perfect. Thanks a lot for the report and staying on this, as italics had been broken in the same way for lord knows how long.

**Comment by dankamongmen** [comment]
I've verified that we can now use reverse + underline + bold + blink + italic + struckthrough.

**Comment by dankamongmen** [comment]
Looking at `sgr-direct`, I suspect that things are still less than perfect in direct mode, likely the same way that they were broken in fullscreen mode. I seem to recall @joseluis semireporting something along these lines months ago when he was first wrapping direct mode.

**Comment by dankamongmen** [comment]
Boom! Fixed `sgr-direct`:

![2020-11-27-154131_802x902_scrot](https://user-images.githubusercontent.com/143473/100483451-0a0a3b80-30c7-11eb-90af-d25e2ff88add.png)

**Comment by MasFlam** [comment]
Damn, that was quick! Thanks!

**Comment by dankamongmen** [comment]
> Damn, that was quick! Thanks!

=] thanks for the great issue writeup! https://www.youtube.com/watch?v=JFyr74uwvvs
