### ISSUE TITLE
package up for nixos

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1148]
it's the dance craze that's sweeping penguin nation, the time-tested overuse of 'x' plus newfangled rollback. we should get into nixos, and "into" guix if "getting into guix" even makes sense. jon paprocki was supposedly going to get us into nixos, but seems to have given up the effort, so good luck getting a job with this scathing google hit dr. paprocki j/k hollllla

**Comment by mcbeth** [comment]
I have a simple derivation for nixos, but notcurses-input, notcurses-tetris, and notcurses-view drop right back to the prompt immediately.  It is complaining about my ```$LANG```, en_US.UTF-8, but I doubt that's the problem.  notcurses-demo runs fine with some weirdness on the emoji part (and a couple others), probably because I'm experimenting with fonts right now.

The derivation will be a little more filled out in nixpkgs (there's some metatags, we can make the optional features optional rather than on/off, etc), but I can at least help walk you through some of it...

```
with import <nixpkgs> {} ;
stdenv.mkDerivation {
  name = "notcurses";
  src = fetchFromGitHub {
    owner = "dankamongmen";
    repo = "notcurses";
    rev = "v2.0.9";
    sha256 = "08qx35k0slcnlc5xlmbif9rzscrp3d0gp6nx2vk6g1rvdx22d8i3";
  };

  buildInputs = [ cmake pkgconfig ffmpeg libunistring ncurses pandoc];

  cmakeFlags = "-DUSE_QRCODEGEN=OFF";
}
```

**Comment by xaverdh** [comment]
for reference there is a nixpkgs pr now [here](https://github.com/NixOS/nixpkgs/pull/106993)

**Comment by dankamongmen** [comment]
> for reference there is a nixpkgs pr now [here](https://github.com/NixOS/nixpkgs/pull/106993)

awesome!

**Comment by mcbeth** [comment]
It's looking pretty good, more flexible than what I had hacked together.  Here's to hoping.

**Comment by dankamongmen** [comment]
Do I need do anything to push this forward, or is it fine to leave this in y'alls' capable hands?

**Comment by mcbeth** [comment]
The nixpkg folks are typically overwhelmed with pull requests.  If this takes too long, there's things we can do to poke them and get it through.  My first pull request there took a week or so.  I'll be keeping an eye on it.

**Comment by dankamongmen** [comment]
in the words of your namesake,

> If it were done when ‘tis done, then ‘twere well
> It were done quickly. 

thank you so very much for your efforts here! i was willing to spin up a nix VM to work on this, but was very much hoping someone else might take it.

**Comment by dankamongmen** [comment]
Let me ask y'all a few things:

* NixOS is a rolling release, right? So I needn't watch for release freezes?
* Is there any restriction on how often the recipe should be updated?
* How long does it usually take to go from recipe update PR to update in the published archive?
* What else ought I be aware of when scheduling Notcurses releases?

Thanks =]

**Comment by mcbeth** [comment]
So, I'm only the maintainer for spigot for nixpkgs, and my experience is that for "trivial" updates (update the version and hash), the approval has been almost immediate.

You mention installing a VM for Nix, which is a good thing, but I'll point out for a moment that you can do Nix development on other distributions with pretty good assurance that'll work on NixOS too.  Particularly on "simpler" infrastructure like notcurses (I've really only had problems with how nix handles GL/Vulkan on non-NixOS distributions)

**Comment by drbeefsupreme** [comment]
> jon paprocki was supposedly going to get us into nixos, but seems to have given up the effort, so good luck getting a job with this scathing google hit dr. paprocki j/k hollllla

Forgive me, I had virtually no experience writing software build scripts for C/C++ the normal way, let alone the Nix way, so a single weekend turned out to not be enough time to get that far. I've been learning a lot in the past week though!

> NixOS is a rolling release, right? So I needn't watch for release freezes?
No, stable releases every 6 months. The next one was just moved back from 2021.03 to 2021.05, though - not sure if that pattern will continue. There is an unstable channel though.

I don't know the answer to the rest of the questions but since I'd like to become a NixOS contributor I'll investigate and get back to you.

**Comment by drbeefsupreme** [comment]
I did some digging and asked some questions.

> Is there any restriction on how often the recipe should be updated?

No. Updating the recipe for every version is acceptable and encouraged.

> How long does it usually take to go from recipe update PR to update in the published archive?

Once the PR is merged it usually ends up on the nixos-unstable channel (from which the release branch will be cut) within a couple of days. The main reason this could be delayed are build issues.

> What else ought I be aware of when scheduling Notcurses releases?

The next release is May 2021, and the plan is for it to be May/November going forward. This is mostly to make it easier to work with KDE and Gnome's release schedule.

Feature freeze typically happens about a month before release, after which additional changes to packages are discouraged unless its to fix build issues.

There is an experimental feature called Nix flakes which makes the builds even closer to the deterministic ideal, and they are intended to replace channels, but it is not expected that they will be required for the 21.05 release. That being said, it would be cool to make a notcurses flake and I'd like to give that a shot.

**Comment by dankamongmen** [comment]
thanks for the info @drbeefsupreme !

We have been accepted into NixOS today, at 2.1.0. I'm probably going to try submitting the 2.1.2 update ASAP, just to get some experience with their workflow (feel free to beat me to it!). Closing.
