### ISSUE TITLE
Is there a specific C version that is targeted?

### ISSUE THREAD

**Issue by igo95862** [dankamongmen/notcurses#1160]
I.E. C11 or GNU11?

I used a bit of GNU extensions in my code. I think they are supported in clang as well.

**Comment by grendello** [comment]
clang supports most GNU extensions, yes. Regardless, I'd say C11 should be the goal if Windows support is ever to be considered (MinGW is fine but a bit of a pita when you need to use anything else except for the barebones provided with the compiler)

**Comment by dankamongmen** [comment]
> clang supports most GNU extensions, yes. Regardless, I'd say C11 should be the goal if Windows support is ever to be considered (MinGW is fine but a bit of a pita when you need to use anything else except for the barebones provided with the compiler)

what he said. please avoid GNUisms unless you know them to be supported by MSVC.

**Comment by grendello** [comment]
Or use them sparingly and carefully, whenever there's a justified advantage (e.g. branch prediction attributes in performance-critical sections or some other intrinsics that bring actual advantage) wrapped in compiler detection voodoo :)

**Comment by dankamongmen** [comment]
sure. if we really need such a thing, i'd appreciate you doing
something along the lines of

#ifdef BELOVED_REGIMES
#define MYCRAPPYATTR __attribute__ ((some-crappy-attr))
#else
#define MYCRAPPYATTR
#endif

as is done for API in notcurses.h. limit this to internal.h if
at all possible.
