### ISSUE TITLE
package up rust for fedora

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1163]
With the successful completion of #355, we'll have our Rust bindings available in Debian. It would be a fine thing to get in Fedora as well. There, I don't believe I'll need go through any regulatory layer; we just need ensure we have our deps available, and if not, package them up ourselves. Those **will** require a review, so we might as well start this process up early. Fedora 34 is scheduled to be branched 2021-02-09.

**Comment by dankamongmen** [comment]
Looks like we need package up cty here, as well:

```
Error: 
 Problem: nothing provides requested (crate(cty/default) >= 0.2.1 with crate(cty/default) < 0.3.0)
```

other than that, i was able to use `rust2rpm libnotcurses-sys` and get a pretty decent-looking specfile.

**Comment by dankamongmen** [comment]
I should go ahead and package up rust-cty for Fedora, although I'll need find someone to do a review swap with.

**Comment by dankamongmen** [comment]
I've packaged up `serial_test_derive`:
```
[localhost](0) $ ls -l /var/lib/mock/fedora-rawhide-x86_64/result/
total 268
-rw-rw-r--. 1 dank mock  34730 2020-12-08 09:16 build.log
-rw-rw-r--. 1 dank mock   2080 2020-12-08 09:14 hw_info.log
-rw-rw-r--. 1 dank mock  18826 2020-12-08 09:15 installed_pkgs.log
-rw-rw-r--. 1 dank mock 172139 2020-12-08 09:16 root.log
-rw-rw-r--. 1 dank mock  11801 2020-12-08 09:16 rust-serial_test_derive-0.5.1-1.fc34.src.rpm
-rw-rw-r--. 1 dank mock   7069 2020-12-08 09:16 rust-serial_test_derive+default-devel-0.5.1-1.fc34.noarch.rpm
-rw-rw-r--. 1 dank mock  11845 2020-12-08 09:16 rust-serial_test_derive-devel-0.5.1-1.fc34.noarch.rpm
-rw-rw-r--. 1 dank mock   1020 2020-12-08 09:16 state.log
[localhost](0) $ sudo dnf localinstall /var/lib/mock/fedora-rawhide-x86_64/result/rust-serial_test_derive-devel-0.5.1-1.fc34.noarch.rpm 
Last metadata expiration check: 5:50:34 ago on Tue 08 Dec 2020 03:27:28 AM EST.
Dependencies resolved.
================================================================================
 Package                            Arch    Version         Repository     Size
================================================================================
Installing:
 rust-serial_test_derive-devel      noarch  0.5.1-1.fc34    @commandline   12 k
Installing dependencies:
 rust-proc-macro2+default-devel     noarch  1.0.24-1.fc34   rawhide       9.8 k
 rust-proc-macro2+proc-macro-devel  noarch  1.0.24-1.fc34   rawhide       9.8 k
 rust-proc-macro2-devel             noarch  1.0.24-1.fc34   rawhide        44 k
 rust-quote+default-devel           noarch  1.0.7-2.fc33    rawhide       8.7 k
 rust-quote+proc-macro-devel        noarch  1.0.7-2.fc33    rawhide       8.8 k
 rust-quote-devel                   noarch  1.0.7-2.fc33    rawhide        35 k
 rust-syn+clone-impls-devel         noarch  1.0.53-1.fc34   rawhide        12 k
 rust-syn+default-devel             noarch  1.0.53-1.fc34   rawhide        12 k
 rust-syn+derive-devel              noarch  1.0.53-1.fc34   rawhide        12 k
 rust-syn+full-devel                noarch  1.0.53-1.fc34   rawhide        11 k
 rust-syn+parsing-devel             noarch  1.0.53-1.fc34   rawhide        12 k
 rust-syn+printing-devel            noarch  1.0.53-1.fc34   rawhide        12 k
 rust-syn+proc-macro-devel          noarch  1.0.53-1.fc34   rawhide        12 k
 rust-syn-devel                     noarch  1.0.53-1.fc34   rawhide       197 k
 rust-unicode-xid+default-devel     noarch  0.2.1-2.fc33    rawhide       8.1 k
 rust-unicode-xid-devel             noarch  0.2.1-2.fc33    rawhide        22 k

Transaction Summary
================================================================================
```

**Comment by dankamongmen** [comment]
I've created all four necessary specfiles: rust-cty, rust-serial_test_derive, rust-serial_test, and rust-libnotcurses_sys.

Now to submit these...

**Comment by dankamongmen** [comment]
[fedora-rust-specfiles.tar.gz](https://github.com/dankamongmen/notcurses/files/5659898/fedora-rust-specfiles.tar.gz)

**Comment by dankamongmen** [comment]
https://nick-black.com/tabpower/fedora-rust/rust-cty.spec
https://nick-black.com/tabpower/fedora-rust/rust-serial_test_derive.spec
https://nick-black.com/tabpower/fedora-rust/rust-serial_test.spec
https://nick-black.com/tabpower/fedora-rust/rust-libnotcurses-sys.spec

**Comment by dankamongmen** [comment]
i've asked @dcantrell if he has anyone to recommend for reviewing this stack

**Comment by dankamongmen** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1907014
https://bugzilla.redhat.com/show_bug.cgi?id=1907015
https://bugzilla.redhat.com/show_bug.cgi?id=1907016
https://bugzilla.redhat.com/show_bug.cgi?id=1907017

**Comment by dankamongmen** [comment]
serial-test and serial-test-derive are in.

**Comment by dankamongmen** [comment]
`rust-cty` is approved and about to go in! that's the last necessary dep. https://bugzilla.redhat.com/show_bug.cgi?id=1907014

**Comment by dankamongmen** [comment]
https://pagure.io/releng/fedora-scm-requests/issue/31962 requests the home for `rust-cty`

**Comment by dankamongmen** [comment]
We got feedback on https://bugzilla.redhat.com/show_bug.cgi?id=1907017, which I will address. Hopefully my module request for `rust-cty` gets approved today, in which case I can upload that, and then we'll be ready to roll once rust-libnotcurses-sys gets approved.

**Comment by dankamongmen** [comment]
It appears that we need a license file in the crate source itself. @joseluis , do you know whether we can do a symlink and have it work with cargo? Eh, shit in a hat, let's just copy the file; the two aren't really bound by anything (I know @joseluis mentioned relicensing to MIT+Apache2).

**Comment by dankamongmen** [comment]
I've just uploaded `rust-cty` 0.2.1 to Fedora Rawhide Core. =]

**Comment by dankamongmen** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1907017 has been updated to point at fresh 2.1.8 materia, including the all-important `LICENSE`. Hopefully it gets approved. I uploaded `rust-cty` for `f33`; it doesn't look like it'll make it into `f32`, fair enough.

**Comment by WSLUser** [comment]
Once in Fedora, do you think you can cross add to CentOS 7.9 or is that too old to be supported? Also would it be likely to even be accepted?

**Comment by dcantrell** [comment]
You can't add it to CentOS 7.9, but you can add it to EPEL-7.  EPEL branches live in the Fedora package repos, so all you need to do is request that branch in the notcurses repo and build it there.

**Comment by dankamongmen** [comment]
@WSLUser I never interact directly with CentOS. So far as I'm aware, CentOS forks off from RHEL (until it dies at the end of this year). I've tried adding Notcurses to EPEL before, but have had little success, due to an ancient CMake. I've got an open bug on it at #851.

Last I looked into it, there would be a newer CMake sometime this year, at which point it ought be straightforward. I even looked into supporting older CMake, but it was a pretty significant loss of functionality, and the only thing worse than spending time writing CMake is spending time backporting to older CMake.

**Comment by dankamongmen** [comment]
aaaaaaaand we are GO! requesting git module now

[dank@localhost fedpkg]$ fedpkg request-repo rust-libnotcurses-sys 1907017
https://pagure.io/releng/fedora-scm-requests/issue/32031
[dank@localhost fedpkg]$ 

who here thinks they already know the work of maya angelou?!?!

**Comment by dankamongmen** [comment]
Also, I got the branch made for `rust-cty` in f32, so `rust-libnotcurses-sys` ought be going there, also. OK! w00t!

**Comment by dankamongmen** [comment]
> @WSLUser I never interact directly with CentOS. So far as I'm aware, CentOS forks off from RHEL (until it dies at the end of this year). I've tried adding Notcurses to EPEL before, but have had little success, due to an ancient CMake. I've got an open bug on it at #851.
> 
> Last I looked into it, there would be a newer CMake sometime this year, at which point it ought be straightforward. I even looked into supporting older CMake, but it was a pretty significant loss of functionality, and the only thing worse than spending time writing CMake is spending time backporting to older CMake.

Huh, according to https://bugzilla.redhat.com/show_bug.cgi?id=1756974, while EPEL8 indeed lacks a modern cmake, EPEL7 has 3.18? how does that work? anyway, let me request a epel-7 branch and see what's good.

**Comment by WSLUser** [comment]
Probably CentOS 8 is becoming abandoned since that is going EOL this year while CentOS 7 still has 3 years to go.

**Comment by dankamongmen** [comment]
> Probably because CentOS 8 is becoming abandoned since that is going EOL this year while CentOS 7 still has 3 years to go.

probably? that epel7 would have newer packages than epel8 was not something i had considered, to my discredit. i expect to have notcurses in epel7 shortly after being granted the branch. it would have been there months ago. [shakes fist at sky]

**Comment by dankamongmen** [comment]
it seems the Fedora Project took a personal day, but hopefully we'll get our modules and branches monday.

**Comment by dankamongmen** [comment]
we got our module! building now. getting `BuildError: package rust-libnotcurses-sys not in list for tag f34-updates-candidate` but we'll hopefully figure that out shortly.

**Comment by dankamongmen** [comment]
We successfully build an x86_64 package, but most other architectures fail; see #1339. I'm going to go ahead and close this bug as a success since all the procedural work is done.
