### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by mimi89999** [dankamongmen/notcurses#1168]
Hello,
I just downloaded the version at tag `v2.0.9` on my Debian testing system, built it and run tests, but they failed:
```
===============================================================================
/home/michel/git/notcurses/tests/visual.cpp:4:
TEST CASE:  Visual
  LoadImageCreatePlane

/home/michel/git/notcurses/tests/visual.cpp:26: FATAL ERROR: REQUIRE( ncv ) is NOT correct!
  values: REQUIRE( NULL )

===============================================================================
/home/michel/git/notcurses/tests/wide.cpp:10:
TEST CASE:  Wide

/home/michel/git/notcurses/tests/wide.cpp:12: FATAL ERROR: REQUIRE( nullptr != nc_ ) is NOT correct!
  values: REQUIRE( NULL != NULL )

===============================================================================
/home/michel/git/notcurses/tests/zaxis.cpp:5:
TEST CASE:  ZAxis

/home/michel/git/notcurses/tests/zaxis.cpp:7: FATAL ERROR: REQUIRE( nullptr != nc_ ) is NOT correct!
  values: REQUIRE( NULL != NULL )

===============================================================================
[doctest] test cases:      40 |      35 passed | 5 failed | 1 skipped
[doctest] assertions: 8496695 | 8496689 passed | 6 failed |
[doctest] Status: FAILURE!
```

**Comment by dankamongmen** [comment]
Hey there! Can you tell me what your `LANG` and `TERM` settings are?

**Comment by mimi89999** [comment]
```
$ echo $LANG && echo $TERM
fr_FR.utf8
xterm-256color
```

**Comment by dankamongmen** [comment]
> ```
> $ echo $LANG && echo $TERM
> fr_FR.utf8
> xterm-256color
> ```

thanks. let me look into the particular failures you posted here, and see if there's some manner of similarity between them. is this an x86?

**Comment by mimi89999** [comment]
`x86_64`

**Comment by dankamongmen** [comment]
OK, so looking into this:

* the `Visual` test is happening here: `    auto ncv = ncvisual_from_file(find_data("changes.jpg"));`
* the `zaxis` and `wide` failures are very early (they can't get a `struct notcurses`); these are just happening because some other, earlier test is failing

so it looks to me like `notcurses-tester` just can't find its input data. How are you running it? `make test` will run it ala:

`notcurses-tester -p ../data`

and you need that `-p ../data`, or else anything that has to load a file is going to break.


did you just run it as `notcurses-tester`? or did you possibly run it from some other directory? ooooooh i bet if you just did a `cmake` in the top level, this breaks -- i ought fix it for that case.

**Comment by dankamongmen** [comment]
if you're running it out of the toplevel, can you please try

`notcurses-tester -p data`

and see if that works?

**Comment by dankamongmen** [comment]
Actually, that does work, because CMake knows to call `notcurses-tester` with the correct directory explicitly. I can reproduce your exact failures by running `notcurses-tester` without a `-p` option, though. Is that possibly what's going on?

**Comment by dankamongmen** [comment]
I could put in a warning at the beginning if `datadir` doesn't exist. This won't help if it does exist but contains the wrong data, of course, but there's a limit to what we can do here.

Note that this won't require `-p`, which we don't want to do -- `notcurses-tester` with no arguments ought work properly when installed (it'll look by default to `/usr/share/notcurses` or `/usr/local/share/notcurses`). It'll just look at `datadir` post-options-processing.

**Comment by dankamongmen** [comment]
I've changed `notcurses_init()` to treat `setup_signals()` failures as non-fatal, which eliminates the "every unit test fails once one fails" problem. That's been annoying for a long time.

**Comment by dankamongmen** [comment]
I've changed up `tests/main.cpp` to check that it can access `changes.jpg` in the `datadir` on startup, and exit with failure if not:

```
[grimes](130) $ ./notcurses-tester 
Running with LANG=en_US.UTF-8
Running with TERM=vte-256color
Couldn't open /usr/local/share/notcurses/changes.jpg. Supply directory with -p.
[grimes](1) $ 
```

if I'm correct as to the problem you're seeing, this will now make the problem obvious.

**Comment by dankamongmen** [comment]
Based on the failure pattern you posted, I'm pretty certain that this was the problem. Please reopen if you disagree. Otherwise, thanks for reporting this and ensuring it was improved.

**Comment by dankamongmen** [comment]
Hey @mimi89999 , did this work for you?

**Comment by mimi89999** [comment]
Hello,
Sorry for the delay. This did not work for me.
```
cmake -B build \
                -DCMAKE_INSTALL_PREFIX=/usr \
                -DCMAKE_INSTALL_LIBDIR=lib \
                -DBUILD_SHARED_LIBS=True \
                -DCMAKE_BUILD_TYPE=None \
                -DUSE_PANDOC=off \
                -DUSE_QRCODEGEN=off \
                -DUSE_PYTHON=off
make -C build && make -C build test
[...]
Running tests...
Test project /home/michel/git/notcurses/build
    Start 1: ncpp_build
1/7 Test #1: ncpp_build .......................   Passed    0.08 sec
    Start 2: ncpp_build_exceptions
2/7 Test #2: ncpp_build_exceptions ............   Passed    0.05 sec
    Start 3: sgr-full
3/7 Test #3: sgr-full .........................   Passed    0.05 sec
    Start 4: sgr-direct
4/7 Test #4: sgr-direct .......................   Passed    0.05 sec
    Start 5: rgb
5/7 Test #5: rgb ..............................   Passed    0.05 sec
    Start 6: rgbbg
6/7 Test #6: rgbbg ............................   Passed    0.05 sec
    Start 7: notcurses-tester
7/7 Test #7: notcurses-tester .................***Failed   36.39 sec

86% tests passed, 1 tests failed out of 7

Total Test time (real) =  36.93 sec

The following tests FAILED:
	  7 - notcurses-tester (Failed)
Errors while running CTest
make: *** [Makefile:126 : test] Erreur 8
make : on quitte le répertoire « /home/michel/git/notcurses/build »
```

**Comment by dankamongmen** [comment]
This might be related to #1197, which I'm finally got a path on now.
