### ISSUE TITLE
using `cell_load_egc32` with a Rust char

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1177]
I just realized that the new `cell_load_egc32()` function's body is exactly the same as `cell_load_char()`'s one, so it suffers from the same problem I encountered in the Rust bindings. That was receiving a 4byte [`char`](https://doc.rust-lang.org/std/primitive.char.html) only shows something when the value it contains is up to 7bits.

FWIW a Rust  `char` is really a `Unicode Scalar Value`: *(Any Unicode code point except high-surrogate and low-surrogate code points. In other words, the ranges of integers `0` to `D7FF16` and `E00016` to `10FFFF16` inclusive.)*

**Comment by joseluis** [comment]
It does work well with cell_load() though. So I made a constructor that wraps all that up in a single call, and the Rust bindings can live with that.

**Comment by dankamongmen** [comment]
See #1176. I'm adding unit tests for this now, so I ought understand what you're saying soon, hopefully. Are you saying that if you call `cell_load_egc32()` with say 🌿 (UTF-8 f09f8cbf, U+1F33F HERB), you don't get anything? You're passing the UTF-8 encoding, not the Unicode character, right? it sounds like you're passing the Unicode code point. it wants a UTF-8 encoded EGC of 4 or fewer bytes (a proper superset of the Unicode characters). is that a problem? we use utf-8 everywhere in the API except for a function that turns u32 into utf8; i don't think adding this as u32 makes much sense.

**Comment by dankamongmen** [comment]
and btw the work in #1176 will turn that kind of thing into an error very shortly (unless the unicode value happens to map to some valid utf-8).

**Comment by dankamongmen** [comment]
```
// Load a 7-bit char 'ch' into the cell 'c'.
static inline int
cell_load_char(struct ncplane* n, cell* c, char ch){
  cell_release(n, c);
  char gcluster[2];
  gcluster[0] = ch;
  gcluster[1] = '\0';
  return cell_load(n, c, gcluster);
}

// Load a UTF-8 encoded EGC of up to 4 bytes into the cell 'c'.
static inline int
cell_load_egc32(struct ncplane* n, cell* c, uint32_t egc){
  cell_release(n, c);
  char gcluster[sizeof(egc) + 1];
  egc = htole(egc);
  memcpy(gcluster, &egc, sizeof(egc));
  gcluster[4] = '\0';
  return cell_load(n, c, gcluster);
}
```

they now go through the One True Path of `cell_load()->pool_load()->pool_load_direct()->[black magic]` and are thus properly validated like anything else.

**Comment by joseluis** [comment]
Uf, I'm sorry, I got confused and assumed a unicode code point was valid utf-8, hmmmmm. Ok I guess that if there's no option to pass a unicode point then I'll keep using utf-8 string slices, which is fine.

**Comment by dankamongmen** [comment]
Cool, closing this. Please reopen if you see further work to be done.
