### ISSUE TITLE
Fix the rust doc tests failing with a couple of imported C comment blocks

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1180]
Some time ago I disabled ([commit](https://github.com/dankamongmen/notcurses/commit/92350b4694193231bd6bbd6c9caa5fd5c9fbf018)) the automatic testing of the documentation examples because that was the only way to avoid the errors bindgen has with the box-drawing characters in the documentation of ``ncmultiselector_options, and `ncselector_item`. E.g.:

```
test target/debug/build/libnotcurses-sys-2adb8ef690bb45eb/out/bindings.rs - bindings::ffi::ncmultiselector_options (line 7508) ... error: unknown start of token: \u{256d}
 --> /home/joseluis/.cargo/target/debug/build/libnotcurses-sys-2adb8ef690bb45eb/out/bindings.rs:7509:1
  |
3 | ╭───────────────────╮
  | ^

error: unknown start of token: \u{2500}
 --> target/debug/build/libnotcurses-sys-2adb8ef690bb45eb/out/bindings.rs:7509:2
  |
3 | ╭───────────────────╮
  |  ^
  |
help: Unicode character '─' (Box Drawings Light Horizontal) looks like '-' (Minus/Hyphen), but it is not
```

But now that the documentation is growing and in need of examples, I'd like to be able to turn that on again. 

Since there seems to be no solution from the bindgen part, I propose is to subtly split out the affected ascii art lines in notcurses.h for the affected types.

**Comment by dankamongmen** [comment]
Does this not seem like something one of us could probably fix in bindgen?

**Comment by dankamongmen** [comment]
Either way, I can move these to `USAGE.md`, or eliminate them if already there. But this seems like a shortcoming in bindgen! Does it handle such characters when they're in e.g. constants etc.?

**Comment by dankamongmen** [comment]
and wait, why doesn't it blow up on the `typedef enum ncblitter_e` at the beginning, which is absolutely dropping with UTF-8?

**Comment by dankamongmen** [comment]
I already have these same diagrams in `USAGE.md`, so you're welcome to pull them if we need, but this really does feel like a shortcoming in bindgen that we ought report if not step up and fix ourselves. with rust's frequent releases, such a fix would come back to us pretty quickly, i suspect.

**Comment by joseluis** [comment]
This is a known issue in bindgen since 2017. You can enter the rabbit hole from the links in my linked comment in my first post.

The current fix works because bindgen is configured to treat all the comment lines immediately above the imported types and functios as documentation comments. So it tries to convert them into Rust doc comments. We want that in order to have documentation for the automatically binded functions...  But we can't filter out specific comments from bindgen yet.

Ideally, with time, I should manually recreate the automatic bindgen bindings, with consistent doc comments and the same types in parameters as the ones defined in the Rust bindings, but for now it's good enough as it is.

**Comment by dankamongmen** [comment]
got it, missed the link, thanks!
