### ISSUE TITLE
"ncls -h" hides user input

### ISSUE THREAD

**Issue by kusky3** [dankamongmen/notcurses#1194]
After running `ncls -h` terminal user input is suppressed (like stty -echo).

notcurses 2.0.9
tested on alacritty and st

**Comment by dankamongmen** [comment]
Thanks for the report! I don't believe I've been seeing this behavior, but let me try to reproduce it. What's the return code from the `ncls` process? You can get this with `echo $?` immediately after `ncls` terminates.

**Comment by dankamongmen** [comment]
oh this is just with `-h`? got it.

**Comment by kusky3** [comment]
it's 130

**Comment by dankamongmen** [comment]
yep, i see the problem. thanks! fixing this now.

**Comment by kusky3** [comment]
is it possible to render images and to the left side of the terminal?

**Comment by dankamongmen** [comment]
Fixed in master. This fix will be present in 2.0.11/2.1.0.

As for the left side, it is not supported at the moment, but oughtn't be hard to add. Please file a feature request, and I'll try to get it in for 2.1.0 =]. Thanks a lot for this report! What an embarrassing bug.

**Comment by dankamongmen** [comment]
@kusky3 i went ahead and filed #1195 about left-justification in `ncls`. We ought also get centering for free. Look for this in 2.2.0.

**Comment by kusky3** [comment]
Thank you so much

**Comment by dankamongmen** [comment]
no problem! i assume you're using arch (you filed the out-of-date notice on me yesterday, right?) -- if so, 2.0.11 is in the AUR now, and you ought see this fix =].

**Comment by kusky3** [comment]
you're right, that's why i reported the bug for 2.0.9. i thought i was running the latest version.
