### ISSUE TITLE
update rustc version in drone

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1220]
could we update the rustc version in drone? and even better, could it be always the latest stable?

**Comment by dankamongmen** [comment]
it can always be the latest one packaged by the relevant distro, since i'm primarily testing to ensure we can build properly on various distros. is one particularly out of date? i update the drone images monthly or so. i can have them run updates internally before building, just every so often updates will be broken and it breaks the builds.

**Comment by joseluis** [comment]
It's 1.43 on ubuntu focal, which is the only image that currently tries to build the rust sources.

I believe nearly everyone uses rustup usually to install and manage the rust versions. Is that requirement necessary for the packaging process?

They constantly stabilize features on each version. For example the reason the build fails now is because I used conditionals in a const function, a feature stabilized in 1.47.

It'd be good to know if there's a maximum rustc version that I must use for the bindings.

**Comment by dankamongmen** [comment]
the focal one is super-old. they only have notcurses 1.7.4 and won't be taking any newer ones. i ought move that to ubuntu hirsute.

i'd like to remain packageable, yes, but our rolling juggernaut of a head only needs be packageable on rolling, somewhat up-to-date distros. if you can build on debian unstable and fedora rawhide, we're 100% good, mad decent even.

**Comment by dankamongmen** [comment]
updating drone images is one of the less rewarding elements of this project, so they're not quite as tight a ship as i try to keep otherwise

**Comment by joseluis** [comment]
Ok then debian and fedora images will need to have rustc installed. Should the install commands be included in `.drone.yml`?

**Comment by joseluis** [comment]
BTW I'm seeing it wrong or the [rust compilation lines I added for fedora](https://github.com/dankamongmen/notcurses/commit/04b10741d420d7e6aa978558d3eb2426d6a79cf0#diff-b54b39f1afced2465e1f3641db9d5bbf4f3a7fcf890996dfedd3c197bcb7f8c7R75-R80) are [not being run](https://drone.dsscaw.com:4443/dankamongmen/notcurses/5025/4/2)?

**Comment by dankamongmen** [comment]
> BTW I'm seeing it wrong or the [rust compilation lines I added for fedora](https://github.com/dankamongmen/notcurses/commit/04b10741d420d7e6aa978558d3eb2426d6a79cf0#diff-b54b39f1afced2465e1f3641db9d5bbf4f3a7fcf890996dfedd3c197bcb7f8c7R75-R80) are [not being run](https://drone.dsscaw.com:4443/dankamongmen/notcurses/5025/4/2)?

indeed. that is...odd.

it is possible that drone is configured to only allow `.drone.yml` changes from me to take effect, aka "secure mode". dim recollections of this. also possible i'm imagining things.

gimme a second.

**Comment by dankamongmen** [comment]
fedora rawhide will give you rustc 1.48 and cargo 1.48 shortly

**Comment by dankamongmen** [comment]
debian unstable will give you rustc 1.48 and cargo 1.48 shortly.

**Comment by dankamongmen** [comment]
```
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
1134	  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
1135	  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
1136	  cargo:rerun-if-changed=build/wrapper.h
1137	
1138	  --- stderr
1139	  thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\', \'libclang-*.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.56.0/src/lib.rs:1922:31
1140	  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

do you need some manner of clangy thing?

**Comment by joseluis** [comment]
clang seems to be a [requirement for bindgen](https://rust-lang.github.io/rust-bindgen/requirements.html)

**Comment by joseluis** [comment]
> it is possible that drone is configured to only allow `.drone.yml` changes from me to take effect, aka "secure mode". dim recollections of this. also possible i'm imagining things.

it's weird also that only happens for fedora and not for the debian build...

**Comment by dankamongmen** [comment]
> > it is possible that drone is configured to only allow `.drone.yml` changes from me to take effect, aka "secure mode". dim recollections of this. also possible i'm imagining things.
> 
> it's weird also that only happens for fedora and not for the debian build...

yeah. i have no idea what's going on here. i will look into it.

as for the clang requirement, i'll install it, and submit an upstream patch including the dependency.

**Comment by dankamongmen** [comment]
dankamongmen/unstable_builder:2020-12-17a contains clang, and ought build the rust extensions. we'll know shortly...

**Comment by dankamongmen** [comment]
https://drone.dsscaw.com:4443/dankamongmen/notcurses/5033

**Comment by dankamongmen** [comment]
debian unstable build now gets past bindgen and hits:

```
   Compiling serial_test v0.5.1
1109	   Compiling libnotcurses-sys v2.1.1 (/drone/src/rust)
1110	error[E0061]: this function takes 4 arguments but 3 arguments were supplied
1111	  --> src/cells/test/methods.rs:14:15
1112	   |
1113	14 |     let _c3 = NcCell::with_all('c', 0, 0);
1114	   |               ^^^^^^^^^^^^^^^^ ---  -  - supplied 3 arguments
1115	   |               |
1116	   |               expected 4 arguments
1117	   | 
1118	  ::: src/cells/methods.rs:12:5
1119	   |
1120	12 |     pub const fn with_all(ch: char, width: u8, stylemask: NcStyleMask, channels: NcChannelPair) -> Self {
1121	   |     --------------------------------------------------------------------------------------------------- defined here
1122	
1123	error[E0061]: this function takes 4 arguments but 3 arguments were supplied
1124	  --> src/cells/test/reimplemented.rs:21:14
1125	   |
1126	21 |     let c2 = NcCell::with_all(' ', 0, 0x0011223300445566);
1127	   |              ^^^^^^^^^^^^^^^^ ---  -  ------------------ supplied 3 arguments
1128	   |              |
1129	   |              expected 4 arguments
1130	   | 
1131	  ::: src/cells/methods.rs:12:5
1132	   |
1133	12 |     pub const fn with_all(ch: char, width: u8, stylemask: NcStyleMask, channels: NcChannelPair) -> Self {
1134	   |     --------------------------------------------------------------------------------------------------- defined here
1135	
```

**Comment by joseluis** [comment]
ouch, forgot to update the tests

**Comment by dankamongmen** [comment]
i'm so confused by what's going on with fedora, and at the same time so very uninterested in figuring it out

**Comment by dankamongmen** [comment]
we have a clean debian unstable build! thanks much @joseluis

**Comment by dankamongmen** [comment]
closing this. i will at some point debug what the hell's going on with the fedora drone build.
