### ISSUE TITLE
add -t (time) option to notcurses-view

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1229]
See #1222. It might be useful to have `-k` in `notcurses-view` imply `-q` and prevent a prompt from being used. If we do this, `-k` ought restrict us to a single argument on the command line.

**Comment by dankamongmen** [comment]
I think a better approach might be a `--time` argument. If `--time` is provided, no prompt is displayed, and `--time 0` is supported.

**Comment by kusky3** [comment]
> I think a better approach might be a `--time` argument. If `--time` is provided, no prompt is displayed, and `--time 0` is supported.

if i understand correctly to me this sounds like the best considering we get slideshows with framerate.

**Comment by dankamongmen** [comment]
> if i understand correctly to me this sounds like the best considering we get slideshow with framerate.

exactly, and there's not a confusing conflation of alternative screen with prompting, much better.
