### ISSUE TITLE
strange descriptions for ncplane_set_base and ncplane_set_base_cell

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1238]
In the description of `ncplane_set_base` it says: *this function must be called with an empty 'egc'. 'egc' must be a single extended grapheme cluster.*

And in `ncplane_set_base_cell`: *Set the ncplane's base nccell to this nccell.* (...) *this function must be called with a zero 'c'.*

Isn't that contradictory? I mean, why would they need to be empty/zero if they are used to change the base cell?

**Comment by dankamongmen** [comment]
>  this function must be called with an empty 'egc'

This applies to the first part of the sentence:

> Erasing the ncplane does not reset the base cell; this function must be called with an empty 'egc'.

you call with an empty 'egc' to empty the egc of the base cell. erasing the plane does not do so. i.e. if you have a plane with all kinds of crazy crap on it, with a base cell of 'A', and call `ncplane_erase()`, you're going to have an ncplane of all 'A's.

i'll express this a better way, thanks!
