### ISSUE TITLE
investigate gstreamer as a multimedia backend

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1241]
@joseluis pointed out after our #1101 misdventure that gstreamer is a thing, and it looks like it satisfies a lot of the things i was hoping to get from libvlc. in particular, it's supported on recent windows. maybe it's a good option?

**Comment by dankamongmen** [comment]
Also, it looks like gstreamer is in Fedora Core, so if it has video codecs there, I'd say it probably ought replace OIIO on fedora.

**Comment by dankamongmen** [comment]
note that while most examples talk about ogg-decode and vorbis-decode and generally suggest we need know the type of the file, which would suck, but there is an 'autoplugger' concept (see chapter 20 of https://gstreamer.freedesktop.org/data/doc/gstreamer/head/manual/manual.pdf) that ought hendle its dendels.

**Comment by dankamongmen** [comment]
`gst-launch-1.0 filesrc location=data/notcursesII.mkv \! decodebin \! videoconvert \! autovideosink` seems to handle detection of different types just fine. we just need to get it treating us as a sink, and we ought be good!

**Comment by dankamongmen** [comment]
https://cgit.freedesktop.org/gstreamer/gst-plugins-base/tree/tests/examples/snapshot/snapshot.c

**Comment by kaniini** [comment]
A problem with gstreamer pipelines is that they want to control everything -- you fire up a pipeline and receive telemetry from it as video/audio data is delivered asynchronously to your sink.

I'm not sure how effectively the current notcurses multimedia support maps onto gstreamer.

**Comment by dankamongmen** [comment]
if there's any way to pause and unpause it, we can just drive that state machine (similarly to how i'd intended to handle libvlc), telling it to ignore its own timing information. if not, it's surely just a matter of buffering =].

**Comment by dankamongmen** [comment]
https://gstreamer.freedesktop.org/documentation/tutorials/playback/playbin-usage.html?gi-language=c looks good

**Comment by dankamongmen** [comment]
https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/blob/master/tests/examples/snapshot/snapshot.c looks even better

**Comment by WSLUser** [comment]
Question: Would something like [PipeWire](https://github.com/PipeWire/pipewire) work for notcurses? Or is that a whole other lane entirely meant for other types of applications, not TUI apps?

**Comment by dankamongmen** [comment]
pipewire is written primarily by one of the gstreamer folks, i believe, and thus has a similar dataflow model. with that said, i don't think it does visual codecs?

**Comment by WSLUser** [comment]
I haven't really had a chance to play with Pipewire since it's not really disseminated as a default package to replace pulseaudio yet. It does say it's still in preview. So basically have to determine if pulseaudio supports visual codecs. I'm not entirely sure since most of my experience working with it is mostly getting my WSL distros to produce sound.  Gstreamer still seems like the best method forward here and maybe as a potential optimization (we'd need some comparisons first), we could use pipewire for audio codecs.

**Comment by WSLUser** [comment]
Maybe you could gawk something out of https://github.com/PipeWire/pipewire. The README could be interpreted to support visual codecs but I think you'd have to find the where the codec support is in the code to know for sure.

**Comment by dankamongmen** [comment]
i don't think we'll be adding any image-processing backends for kicks; there's enough of a pain maintaining the two we have.
