### ISSUE TITLE
consider parsing /etc/os-release for ncneofetch logo

### ISSUE THREAD

**Issue by kaniini** [dankamongmen/notcurses#1246]
`/etc/os-release` has provisions for discovering a system logo and distribution name.

Though Alpine does not use systemd, we do provide an `/etc/os-release` file.

https://www.freedesktop.org/software/systemd/man/os-release.html

**Comment by dankamongmen** [comment]
thanks for the heads-up, will do! expect this in 2.1.2.

**Comment by dankamongmen** [comment]
so we *do* parse `/etc/os-release`; see `linux_ncneofetch()` in main.c. i don't see an actual `LOGO` entry in alpine's, at least as of `VERSION_ID=3.12_alpha20200428`. i actually don't see any alpine logo on my alpine box in `/usr` -- is there one i ought be looking for?

**Comment by dankamongmen** [comment]
> By default, apps should look in $HOME/.icons (for backwards compatibility), in $XDG_DATA_DIRS/icons and in /usr/share/pixmaps (in that order). 

I'm going to implement `get_xdg_logo()` in `ncneofetch` to check these locations when a logo is specified in `/etc/os-release`.

**Comment by dankamongmen** [comment]
erp, one annoyance here is that we're rendering the palette + logo in one thread, and in another thread we're getting all the info that we put in the info box. we'd need to feed the `/etc/os-release` info into the draw thread somehow (and block on it), or do that lookup before drawing anything (probably the easiest solution).

i am now looking it up in the info thread, so we have the logic to grab LOGO from `/etc/os-release`.

@kaniini , you never answered -- does Alpine have a logo anywhere i can add to ncneofetch?

**Comment by kaniini** [comment]
Alpine doesn't have its logo packaged yet.  That's something being addressed though.  I'll send a patch when its done.

**Comment by dankamongmen** [comment]
oh wait, we get `fetched_info` as the first step of `ncneofetch()`. so it *is* available for `display_thread`. ok, let's finish this up for 2.1.4.

**Comment by dankamongmen** [comment]
We now support a `LOGO` entry in `/etc/os-release`, with or without quotes. It always preempts any logo we might have hardcoded. We also now use the 3x2 sexblitter when available via `NCBLIT_DEFAULT` + `NCSCALE_SCALE_HIRES`. It looks much better:

![2021-01-03-135318_802x1417_scrot](https://user-images.githubusercontent.com/143473/103486321-0c00a200-4dcb-11eb-832a-4cfb2ea8ec90.png)
