### ISSUE TITLE
add scaling options that use high-res without stretch

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1250]
Right now, `NCSCALE_NONE` and `NCSCALE_SCALE` are capped at aspect-ratio-preserving `NCBLIT_2x1`. I'd like to expose them to higher-res blitters like `NCBLIT_3x2`, especially now that we have some default support for them (see #1114). My first thought is to add two new scaling options, `NCSCALE_HIRES` and `NCSCALE_SCALE_HIRES` or something, and these do the overall scaling like their brethren, but with higher resolution (less space required for `NCSCALE_HIRES`, and less lossage and/or space for `NCSCALE_SCALE_HIRES`). I'm not sure this is the best way to do it, though, so I'd love to hear counterproposals.

**Comment by joseluis** [comment]
This would be nice to have while we wait for sixel support, that could be a while...

**Comment by dankamongmen** [comment]
holy CRAP this is going to make `ncls` look tremendously better

![2020-12-25-182926_882x1057_scrot](https://user-images.githubusercontent.com/143473/103143150-29ed4900-46df-11eb-93c0-eb39f127584d.png)
![2020-12-25-182935_882x1057_scrot](https://user-images.githubusercontent.com/143473/103143151-2b1e7600-46df-11eb-83db-9e7ef7ec8db1.png)

hey @kusky3 you're gonna dig this, merry christmas!

**Comment by dankamongmen** [comment]
and now with #1252 fixed, we'll also be properly transparent =]. shocked that that was broken for so long =[.

this is just about done on the `dankamongmen/sex-scale` branch. Need to fix up the `eagle` and `dragon` demos, which are doing something odd.

**Comment by kusky3** [comment]
> holy CRAP this is going to make ncls look tremendously better
stop abusing our terminals
> hey @kusky3 you're gonna dig this, merry christmas!
thank you, happy holidays!
