### ISSUE TITLE
templates for issues

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1251]
do you think we could have an `Other` template (for example), without any customization, labels, etc?

**Comment by dankamongmen** [comment]
sure, i only added that stuff to get a higher "community best practices" score and thus one fine day be selected for some kind of frontpage display or other honor

**Comment by dankamongmen** [comment]
should be there now.

**Comment by joseluis** [comment]
Thanks!

**Comment by dankamongmen** [comment]
Wait, do you not see the "open a blank issue" at the bottom of the table? Is this not what you want?

![2020-12-27-235412_1430x457_scrot](https://user-images.githubusercontent.com/143473/103190428-eb05f180-489e-11eb-8601-e25bfcf0677e.png)

**Comment by dankamongmen** [comment]
removed the seemingly redundant OTHER template. if this "blank issue" capability isn't available to you, ping me and i'll add it back. trying to keep a tight ship! =]

**Comment by joseluis** [comment]
Oooooh... there it is, a link for ants, I see it now. thanks you!

**Comment by dankamongmen** [comment]
> Oooooh... there it is, a link for ants, I see it now. thanks you!

i eagerly hope that this was a zoolander reference. you jitterbug!
