### ISSUE TITLE
About the in-sync publishing of the rust wrappers

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1254]
Currently they are version bumped and published at the same time as a new notcurses version is published.

But that doesn't make sense, since in practice the rust wrappers doesn't really match the new notcurses version, but the previous one, both in features and documentation.

Until the necessary changes are made to match the new version, as documented in the release notes, I believe the wrappers shouldn't be published under the new version number.

I'm thinking there should probably be a different script to bump & publish the wrappers, for convenience.

**Comment by dankamongmen** [comment]
So at that point we're just honestly talking about the two diverging, version-wise, no?

Would a synchronized, agreed-upon release process be better?

I'm down for either, but if they're going to have their own versioning, they should go in their own repo IMHO. it doesn't do anyone good to look at the notcurses repo at version 2.1.3 and know it contains rust wrappers last released at 2.1.2.

I'm thinking it should probably be my responsibility, before I release, to add rust wrappers/updates for a release if you haven't done it. I don't know what are your thoughts? I like how all components come out at one time right now, but you're right, the appeal of that is undermined if it's not a coherent release.

**Comment by joseluis** [comment]
Well...  I don't know about the agreed-upon release process. I think that demands a kind of commitment I'm not really sure I would be able to hold for long...

I was thinking more of a delayed release... but since you don't think it's good to have them together unsynced in the same repo, which I can understand, a separate repo could be an option.

A separate repo also reflects on the fact that they're different projects in practice, using different languages, with different development needs, and a different commit history...   That would mean a cleaner commit history for the C library too...

It's funny because a creator normally does its project in one language, and other people create and manage their wrappers over it on their own. You have imposed a big task over your shoulders trying to keep all of these different pieces in sync by yourself. And it's been able to go very far in just one year. That's unbelievable.

And there's also the other rust wrappers repo (notcurses-rs), which I'm lately wondering about, since it turns out I've been able to expose a dual C-style and Rust-style API through libnotcurses-sys itself (in a way that feels very natural). The thing is I don't feel as much need for notcurses-rs right now as I thought I would. But it could still be useful, since it has more freedom to depend on more crates, not being tied to package distribution bureaucracy, and  it could also have deeper links with the Rust ecosystem... We'll see...

For now I'm focusing on leaving the wrappers in a good state, with a good design, working, documented, and with examples and test hopefully :)  And I believe until they're finished they're not gonna be really in sync with the C library. In fact I can't even be sure everything I already wrapped works...  The version number right now is more of a declaration of intentions rather than a guarantee.

**Comment by dankamongmen** [comment]
> It's funny because a creator normally does its project in one language, and other people create and manage their wrappers over it on their own. You have imposed a big task over your shoulders trying to keep all of these different pieces in sync by yourself. And it's been able to go very far in just one year. That's unbelievable.

=]

i think you're the primary owner of the rust wrappers -- like it or not =] -- and you ought do what you think is wisest, and works best for you. i agree that a synchronized release sounds like kind of a downer for all involved, and i want to keep this project a happy, rollicking one (in a year that has seen me get divorced and some other personal crap, Notcurses has been my great joy, and i want to retain that joy). so: you decide what you'd like to do, and what i need do to support you, and tell me. should you one day leave, and i inherit the rust wrappers back, i'll do what i think best. but until then, i trust you and rely on you to do it right.

**Comment by joseluis** [comment]
That's very kind of you thank you. Although I don't know about being the owner, maybe more like a parent figure :D   Ok I'm thinking...

Now that the Rust wrappers have grown to represent more than 24% of the codebase, may be a good moment to let them have their own space, by moving ot of their parents home and renting their own apartment.

What do you think about cloning the current repo into `dankamongmen/libnotcurses-sys`, removing everything except the `rust/` folder (moving its contents to the root), configuring drone testing, making me a colaborator and... I don't know if I'm missing anything, but that'd be the gist of it.

Heh! it turns out there's an *official* way to do this subfolder splitting [using `git subtree`](https://stackoverflow.com/questions/359424/detach-move-subdirectory-into-separate-git-repository/17864475#17864475)

And finally, regarding version numbering, I think the synchronization shuold be mostly be at the higher version number level. That means when notcurses bumps to 3.x the Rust wrappers should do that as well, (after they make the necessary changes ofc). Otherwise they shouldn't be in a perfect sync for the lower version numbers...

Does that sound good to you?

**Comment by dankamongmen** [comment]
this all sounds reasonable. i'll get to it sometime before the new year.

**Comment by joseluis** [comment]
Does this mean you plan to release 2.2 in the next 2 days?

**Comment by dankamongmen** [comment]
> Does this mean you plan to release 2.2 in the next 2 days?

no

**Comment by dankamongmen** [comment]
Just as a heads up, I'm planning on cutting 2.1.5 as soon as the `animate` demo is done, so in the next few days. Ought I change anything about the release process?

**Comment by joseluis** [comment]
i just noticed this. but I don't think so.

**Comment by dankamongmen** [comment]
ok i'm closing this as i do the 2.1.8 sweep, as i think it's gone as far as things can in a notcurses bug. feel free to reopen (or start a conversation thingie) to discuss further.
