### ISSUE TITLE
ncls ought not "render" text files

### ISSUE THREAD

**Issue by kusky3** [dankamongmen/notcurses#1267]
notcurses-view and ncls showing a text file as if it is an image, is this an intended behaviour? if yes, what does it depend on?

version: 2.1.3
exit code: 0
how to reproduce: `ncls cursed.txt` or `notcurses-view cursed.txt`
[cursed.txt](https://github.com/dankamongmen/notcurses/files/5758139/cursed.txt)

**Comment by dankamongmen** [comment]
It is indeed intended behavior. We use ffmpeg (libavcodec et al) or OpenImageIO for media rendering. For each file we see, I feed that to the appropriate library's open function. If they want to decode it, they decode it.

Running `mplayer cursed.txt` renders the text file. notcurses will thus do so as well, when built against ffmpeg.

If you need some kind of functionality to not render certain files, it would probably be filename-regex-based, and I've gotta admit it would not be my highest priority, but I wouldn't close it as WONTFIX or anything. Let me know what you need, or please close this bug if I've answered your question satisfactorily. Thanks!

```
[schwarzgerat](0) $ ffprobe fast.txt 
ffprobe version 4.3.1-5 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 10 (Debian 10.2.0-15)
Input #0, tty, from 'fast.txt':
  Duration: 00:00:00.56, start: 0.000000, bitrate: 46 kb/s
    Stream #0:0: Video: ansi, pal8, 640x400, 25 fps, 25 tbr, 25 tbn, 25 tbc
[schwarzgerat](0) $ 
```

**Comment by dankamongmen** [comment]
Hrmmm. Maybe we want such a regex capability, but the more I think about it, we oughtn't be rendering text files in `ncls` by default (if explicitly supplied to `notcurses-view`, that's another thing). mainly this is because i feel if we're going to "render a text file", we ought render it as text. and this is `ncls`, not `nccat`.

so i might look into detecting that format, and excluding it. i'm pretty sure i can do that with libav. not sure about oiio.

**Comment by joseluis** [comment]
Another alternative is to [white|black]list file extensions.

**Comment by dankamongmen** [comment]
> Another alternative is to [white|black]list file extensions.

> If only it were all so simple! If only there were evil people somewhere insidiously committing evil deeds, and it were necessary only to separate them from the rest of us and destroy them. But the line dividing good and evil cuts through the heart of every human being. And who is willing to destroy a piece of his own heart? Thus it is that no cruelty whatsoever passes by without impact. Thus it is that we always pay dearly for chasing after what is cheap.
—Aleksandr Solzhenitsyn, The Gulag Archipelago, Vol. 2

![quote-i-mean-if-10-years-from-now-when-you-are-doing-something-quick-and-dirty-you-suddenly-edsger-dijkstra-59-63-07](https://user-images.githubusercontent.com/143473/103432044-63262d00-4ba7-11eb-94cf-d1919e22fd88.jpg)

**Comment by kusky3** [comment]
> Let me know what you need, or please close this bug if I've answered your question satisfactorily.

yes, thanks. I just wanted to know why that happens.
