### ISSUE TITLE
ncdirect_putstr and the avoidance of double default

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1269]
why does `ncdirect_putstr` is made to fail when both the provided channel and the ncdirect context are marked as using the default color? It puzzled me out while investigating why something was failing.

https://github.com/dankamongmen/notcurses/blob/7e20a25482546dcc36e581f65bfb4aea78f8ec07/src/lib/direct.cpp#L27-L31

With that rule disabled the function seems to work well.

**Comment by dankamongmen** [comment]
looking at it, i'm not immediately sure. let me percolate on that for a moment.

**Comment by dankamongmen** [comment]
ok this function is madness. no idea what i was thinking.

**Comment by dankamongmen** [comment]
That `ncdirect_fg_default_p()` needs be `ncdirect_set_fg_default()`, of course. Thanks, good find!
