### ISSUE TITLE
Suggest listing commands to prepare, build, and run, on Ubuntu

### ISSUE THREAD

**Issue by MaxBarraclough** [dankamongmen/notcurses#1294]
I think it would be helpful for the documentation to fully list the commands necessary to get `notcurses` up and running on a fresh Ubuntu instance. Here are the commands I had to run:

```bash
$ sudo apt-get update

$ sudo apt-get install  build-essential cmake pkgconf libavcodec-dev libncurses-dev libreadline-dev libavformat-dev libswscale-dev doctest-dev libunistring-dev libqrcodegen-dev pandoc

$ cmake -G "Unix Makefiles"

$ make

$ sudo make install

$ sudo ldconfig

$ notcurses-demo
```

**Comment by dankamongmen** [comment]
I'm interested in making things easier to install, but I feel this is pretty well covered by `Building` in `README.md`. Perhaps it ought be extracted into `BUILDING.md` or `INSTALL.md` (neither of these exist currently), and made more explicit? What are your thoughts?

**Comment by dankamongmen** [comment]
I've created the new file `INSTALL.md`, and linked to it from `README.md`. `INSTALL.md` contains the information specified above, plus much more. The relevant information has been purged from `README.md`. Please reopen this issue if you feel this an incomplete solution.

**Comment by MaxBarraclough** [comment]
A couple of further points:

I had trouble with the `apt-get install` command listed in `INSTALL.md`, on a fresh Ubuntu instance. I had to install two additional packages to get `cmake .` to play ball:

    sudo apt-get install  libunistring-dev doctest-dev

I also had to run `sudo ldconfig` before `notcurses-tester` would run.

**Comment by dankamongmen** [comment]
Added.

**Comment by MaxBarraclough** [comment]
Also, might not be of interest but the following command runs faster than the `git clone`:

    curl --location https://github.com/dankamongmen/notcurses/tarball/master -o - | tar -xzf -
