### ISSUE TITLE
Document necessary environment variables to run correctly in PuTTY

### ISSUE THREAD

**Issue by MaxBarraclough** [dankamongmen/notcurses#1295]
I suggest that the documentation should be more explicit on which terminal emulators are able to support notcurses, for instance that the widely used PuTTY terminal emulator is not able to.

Related to this, I'm seeing that the table on [this page](https://github.com/dankamongmen/notcurses/blob/master/TERMS.md) isn't rendering correctly when viewed on GitHub.

**Comment by dankamongmen** [comment]
Wow, it sure isn't! :( Thanks for the heads-up.

I'd like to get things running on PuTTY. Does it run on Linux?

**Comment by dankamongmen** [comment]
`TERMS.md` is now properly formatted; thanks a lot for letting me know. That's been broken for a minute :(.

**Comment by dankamongmen** [comment]
Alright, it looks like Debian ships putty 0.74, let me run some quick tests with it.

**Comment by dankamongmen** [comment]
PuTTY works perfectly for me once i set `TERM=putty-256color` and `COLORTERM=24bit`. Are you using a correct `TERM` value? If you're not using this `TERM`/`COLORTERM` config, please try it out.

**Comment by dankamongmen** [comment]
![2021-01-16-183838_1184x1062_scrot](https://user-images.githubusercontent.com/143473/104827292-0fb01200-582a-11eb-962c-67218674093b.png)

**Comment by dankamongmen** [comment]
I've updated `TERMS.md` with this information for PuTTY. IMHO, notcurses works on PuTTY just fine, and if it doesn't, it's due to user error (it is critical to set the correct `TERM`). As I already discuss the importance of `TERM` in the `README.md`, I'm not sure how much clearer I can make this.

Please reopen if you see further issues with PuTTY or `TERMS.md`. Thanks for the report!

**Comment by dankamongmen** [comment]
One thing I ought do is submit a patch to PuTTY's terminfo description exposing support for `ccc`, as it appears PuTTY implements this, but doesn't advertise it.

**Comment by dankamongmen** [comment]
https://lists.gnu.org/archive/html/bug-ncurses/2021-01/msg00024.html

**Comment by MaxBarraclough** [comment]
I'm still having trouble getting it to work properly in PuTTY (PuTTY 0.74 on Windows 10). Might be user-error on my part but as far as I can see I'm doing what the docs say.

Following TERMS.md, under PuTTY's *Connection* > *Data* I added two entries:

    ┌───────────┬────────────────┐
    │ TERM      │ putty-256color │
    ├───────────┼────────────────┤
    │ COLORTERM │ 24bit          │
    └───────────┴────────────────┘

but `notcurses-tetris` doesn't look right (screenshot attached). I tried shrinking down the font size to bump up the dimensions of the terminal but this didn't improve things. After terminating `notcurses-tetris` I'm shown this message:

    Term: 54x197 xterm (xterm terminal emulator (X Window System))
    
     notcurses 2.1.5 by nick black et al
      54 rows 197 cols (166.22KiB) 16B cells 8 colors
      compiled with gcc-10.2.0, little-endian
      terminfo from ncurses 6.2.20200212
      avformat 58.45.100 avutil 56.51.100 swscale 5.7.100
    
     Warning! Colors subject to https://github.com/dankamongmen/notcurses/issues/4
      Specify a (correct) TrueColor TERM, or COLORTERM=24bit.
![puttyIssue](https://user-images.githubusercontent.com/1122128/104846061-83a4f580-58d0-11eb-99ff-003334c98469.png)

**Comment by dankamongmen** [comment]
hey, i came off like something of an asshole i think when i said "other problem are user error"; i really appreciate the quality bug report, and will get to the bottom of it. keep 'em coming for sure!

**Comment by dankamongmen** [comment]
>  Warning! Colors subject to https://github.com/dankamongmen/notcurses/issues/4   Specify a (correct) TrueColor TERM, or COLORTERM=24bit.

Can you try rerunning `notcurses-tetris` with `COLORTERM=24bit`?

**Comment by dankamongmen** [comment]
Here's what I see with `TERM=putty-256color` and `COLORTERM=24bit`. 

![2021-01-17-094726_494x314_scrot](https://user-images.githubusercontent.com/143473/104846536-04e89200-58a9-11eb-83ce-84a67423fb10.png)

it's not the best-looking rendition I've ever seen, but it's approximately right. In fact, I think there's been a general regression in `notcurses-tetris`; I don't think we want to be using quadblitter here. Let me see if I can fix that up right quick.

How does `notcurses-demo -p ../data` look?

**Comment by dankamongmen** [comment]
I just modified the background image for tetris, and it looks much better now IMHO.

**Comment by MaxBarraclough** [comment]
I've tested the tetris program again on another fresh Ubuntu instance, using the same SSH environmental variables as before:

    ┌───────────┬────────────────┐
    │ TERM      │ putty-256color │
    ├───────────┼────────────────┤
    │ COLORTERM │ 24bit          │
    └───────────┴────────────────┘

I've included a screenshot of the PuTTY config as well as the result. Strange that this doesn't match up with what you're seeing. Are you using PuTTY for Windows?

I tried `notcurses-demo  -p data` and it misrendered, looking much like my tetris screenshot from yesterday.

![puttyConf](https://user-images.githubusercontent.com/1122128/104917040-c88d6280-598a-11eb-9c74-968dc4333b28.png)
![tetris](https://user-images.githubusercontent.com/1122128/104917048-cc20e980-598a-11eb-9c71-fb806cc13f76.png)

I then noticed the *Terminal-type string* field in PuTTY, which is apart from the environment variables. Changing that from *xterm* to *putty-256color* seemed to help somewhat, see below:

![tetris-changedTerminalType](https://user-images.githubusercontent.com/1122128/104917755-b9f37b00-598b-11eb-9822-a481f51d7f78.png)

**Comment by dankamongmen** [comment]
Ahhh, I'm glad to hear it--I was beginning to wonder whether I was losing my mind =]. And no, I am testing pretty exclusively on Linux and FreeBSD -- despite being a Microsoft employee, I don't really do anything on Windows =].

I'm not even familiar with the term "SSH environment variables". What do you mean by this?

Maybe I can make it clearer that I mean UNIX environment variables in `TERMS.md` or even `README.md`. I didn't know it was an ambiguous term. Either way, it seems this bug is indeed resolved? Thanks for sticking with it!

**Comment by MaxBarraclough** [comment]
> I'm not even familiar with the term "SSH environment variables". What do you mean by this?

I was thinking of the PuTTY fields group named *Environment variables*, visible in the screenshot of my PuTTY config. Perhaps it just sets environment variables for the shell session? Not something I know much about.
