### ISSUE TITLE
issue palette save-restore on startup-shutdown

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1296]
Kitty added a most excellent pair of control sequences (see https://sw.kovidgoyal.net/kitty/protocol-extensions.html):

> <ESC>]30001<ESC>\  # push onto stack
<ESC>]30101<ESC>\  # pop from stack
These escape codes save/restore the colors, default background, default foreground, selection background, selection foreground and cursor color and the 256 colors of the ANSI color table.

These seem most desirable to add to our initialization/teardown sequence, and a welcome addition to the repertoire (well done @kovidgoyal!) Indeed, I asked about something like this almost a full decade ago:

https://stackoverflow.com/questions/8686368/how-can-the-original-terminal-palette-be-acquired-preferably-using-ncurses-rout

Apparently XTerm 357 added some version of these, as well: https://www.mail-archive.com/xorg@lists.x.org/msg06419.html. I don't see any corresponding terminfo entries :(.

But yeah, emit these wherever they're supported. Currently, a change to the palette in Notcurses is persistent.

**Comment by kovidgoyal** [comment]
If you are adding support for new things, you might also be interested in: https://github.com/kovidgoyal/kitty/issues/3248

And I suggest using the Xterm control codes for this, as kitty supports both but xterm only one.

**Comment by dankamongmen** [comment]
> If you are adding support for new things, you might also be interested in: [kovidgoyal/kitty#3248](https://github.com/kovidgoyal/kitty/issues/3248)

absolutely, see #1243 

> And I suggest using the Xterm control codes for this, as kitty supports both but xterm only one.

that is indeed my plan, though i'm not seeing what i expect in kitty 0.19.3. here's xterm with XT{PUSH,POP,REPORT}COLORS (slightly cleaned up):

```sh
[schwarzgerat](0) $ echo -e '\e[#R'
^[[?1;1#Q[schwarzgerat](0) $ 
[schwarzgerat](127) $ echo -e '\e[#Q'
[schwarzgerat](0) $ echo -e '\e[#R'
^[[?0;1#Q[schwarzgerat](0) $ echo -e '\e[#Q'
[schwarzgerat](0) $ echo -e '\e[#R'
^[[?0;1#Q[schwarzgerat](0) $ echo -e '\e[#P'
[schwarzgerat](0) $ echo -e '\e[#R'
^[[?1;1#Q
```

but kitty doesn't seem to be following that, nor do the 30001/30101 codes seem to work, unless i'm doing something wrong. for instance, if i run CSI # P (XTPUSHCOLORS):

```sh
[schwarzgerat](0) $ echo -ne '\e[#P'
P[schwarzgerat](0) $ 
```

i then set my default background color with

```sh
[schwarzgerat](0) $ echo -ne "\033]11;rgb:53/18/6f\007"
```

i would now expect CSI # Q to restore my previous background, but it does not (it does in xterm). what am i missing?
```

**Comment by kovidgoyal** [comment]
The following script works fine for me with kitty master (though as far as I know there are no changes in this area since 0.19.3):

```sh
echo -e "\033[#P"
echo -e "\033]11;rgb:53/18/6f\007"
echo "Press Enter to restore background"
read
echo -e "\033[#Q"
echo "Background restored, press Enter to quit"
read
```

**Comment by dankamongmen** [comment]
confirmed that your script works. let's go ahead and get this in.

**Comment by dankamongmen** [comment]
looks like xterm and kitty support this; i'm not seeing much support elsewhere.
