### ISSUE TITLE
notcurses-view is no longer being generated, as of commit c1ea096d3

### ISSUE THREAD

**Issue by MaxBarraclough** [dankamongmen/notcurses#1303]
I'm building on Ubuntu 20.10/AArch64.

I'm finding that as of commit `c1ea096d3`, the `notcurses-view` executable is not being generated. (I'm still seeing the issue in the latest commit, `9cf2925f4`.)

The issue does not appear in commit `05193af66`, which is the parent of commit `c1ea096d3`.

**Comment by dankamongmen** [comment]
`ncplayer` (see #1299), and know that master is in some flux at the moment (see #339 and #1301). it should work, but i won't be shocked if it doesn't :/.

**Comment by dankamongmen** [comment]
basically i looked at all the terminal-blitting apps that can serve as backends to `neofetch`, and `notcurses-view` was about twice as long as any of them. `ncplayer` it is. =]

**Comment by MaxBarraclough** [comment]
I'd missed that [it was renamed](https://github.com/dankamongmen/notcurses/issues/1298#issuecomment-762739439). Yes, `ncplayer` runs.

**Comment by dankamongmen** [comment]
Just as a heads up, the chaos that I referred to this morning (Eastern Freedom Time) has been resolved. Everything ought be more or less working once more. See #1301 and #1305 if you're interested in the upheaval and its final(?) resolution. We're seeing some very minor shakeout (e.g. #1309, which you might actually need watch out for if using `ncplayer`), but things ought be mostly functional once more. Quite a major change over the past two days.

#1309 will be annihilated after i dream the dreams of ten thousand dead drunkards.
