### ISSUE TITLE
`NCOPTION_SUPPRESS_BANNERS` breaks default colors in a non standard plane

### ISSUE THREAD

**Issue by ton** [dankamongmen/notcurses#1314]
I have a status line in my application that can be used to display an overview of all keyboard shortcuts. The status line has a default background color and is in a separate plane. Initially, the status line is drawn correctly with the right background and foreground color. When the user presses '?', the status line will print some application shortcut descriptions. 

I notice that when I suppress notcurses banners using `NCOPTION_SUPPRESS_BANNER`, when the help is displayed in the status line, the text is not printed with the background color for the status line plane:

Initial view (the gray line is the status bar of the application, the rest is tmux):

![initial](https://user-images.githubusercontent.com/157002/105579227-7c289500-5d85-11eb-996f-57bf0a5a336b.png)

After pressing '?' without `NCOPTION_SUPPRESS_BANNER`:

![good](https://user-images.githubusercontent.com/157002/105579226-7b8ffe80-5d85-11eb-93d3-70984f456612.png)

After pressing '?' with `NCOPTION_SUPPRESS_BANNER`:

![bad](https://user-images.githubusercontent.com/157002/105579224-7af76800-5d85-11eb-8d67-482d01e6bd10.png)

The following program reproduces the problem:

```
#include <locale.h>
#include <notcurses/notcurses.h>
#include <stdlib.h>

static struct ncplane *make_status_line_plane(struct ncplane *std_plane) {
  struct ncplane_options opts = {0};
  opts.rows = 1;
  opts.cols = ncplane_dim_x(std_plane);
  opts.y = ncplane_dim_y(std_plane) - 1;
  opts.x = 0;

  nccell c = CELL_CHAR_INITIALIZER(' ');
  cell_set_bg_rgb8(&c, 0x20, 0x20, 0x20);

  struct ncplane *status_line_plane = ncplane_create(std_plane, &opts);
  ncplane_set_base_cell(status_line_plane, &c);
  return status_line_plane;
}

static void print_status_line(struct ncplane *plane) {
  ncplane_putstr_aligned(plane, 0, NCALIGN_LEFT, " ?: help");
}

static void print_help(struct ncplane *plane) {
  const int width = ncplane_dim_x(plane);
  ncplane_erase(plane);
  ncplane_putstr_aligned(
      plane, 0, NCALIGN_LEFT,
      " j/k: scroll up/down   C-B/C-F: page up/down   q: quit");
  ncplane_putstr_aligned(plane, 0, NCALIGN_RIGHT,
                         "press any key to close help ");
}

int main(int argc, char **argv) {
  setlocale(LC_ALL, "");

  notcurses_options opts = {0};
  opts.flags = NCOPTION_SUPPRESS_BANNERS;

  struct notcurses *nc;
  if ((nc = notcurses_core_init(&opts, NULL)) == NULL) {
    return EXIT_FAILURE;
  }

  struct ncplane *std_plane = notcurses_stdplane(nc);
  struct ncplane *status_line_plane = make_status_line_plane(std_plane);

  ncplane_move_top(status_line_plane);

  struct ncinput input = {0};
  bool quit = false;
  while (!quit) {
    print_status_line(status_line_plane);
    notcurses_render(nc);
    notcurses_getc_blocking(nc, &input);
    switch (input.id) {
    case '?':
      print_help(status_line_plane);
      notcurses_render(nc);
      notcurses_getc_blocking(nc, &input);
      ncplane_erase(status_line_plane);
      break;
    case 'q':
      quit = true;
      break;
    }
  }

  notcurses_stop(nc);
}
```

Is this an issue in the program above, or maybe a bug in notcurses itself?

I am using notcurses 2.1.7. My terminal is `st` 0.8.4. Ouput from `export | egrep 'LANG|LC_CTYPE|TERM'`:

```
LANG=en_US.UTF-8
TERM=tmux-256color
TERMINAL=st
TERMINFO=/home/ton/.local/share/terminfo
```

**Comment by ton** [comment]
Ha, I noticed that when I run the program above outside tmux, the problem goes away. I do get the following output on the terminal though:

```
Warning: already added escape (got 0x10000c, wanted 0x10007b)
Warning: already added escape (got 0x100009, wanted 0x10007c)
Warning: already added escape (got 0x10000b, wanted 0x10007d)
Warning: already added escape (got 0x10000a, wanted 0x10007e)
```

Ouput from `export | egrep 'LANG|LC_CTYPE|TERM'` outside tmux:

```
LANG=en_US.UTF-8
TERM=st-256color
TERMINAL=st
TERMINFO=/home/ton/.local/share/terminfo
```

**Comment by dankamongmen** [comment]
Just wanted to say this is one hell of an outstanding bug report, and I will be on it as soon as I'm done taping this FOSDEM presentation -- so sometime tonight! Thank you so much for the report!

**Comment by dankamongmen** [comment]
Alright, finally got some time to read this. `tmux` (and `screen`, and `mosh`) are difficult; I don't have much experience with them, and they obviously throw a level of indirection into things. Nonetheless, this is a weird result, and I intend to explore it.

I've seen the "already added escape" when using `st` myself. Indeed, there's a comment in `input.c`:

```
  // it appears that multiple keys can be mapped to the same escape string. as
  // an example, see "kend" and "kc1" in st ("simple term" from suckless) :/.
  if((*cur)->special != NCKEY_INVALID){ // already had one here!
    fprintf(stderr, "Warning: already added escape (got 0x%x, wanted 0x%x)\n", (
  }else{
```

and indeed, when I run st, we see both `kend` and `kc1` are defined to `\E[4~`:

```
[schwarzgerat](0) $ infocmp -a | egrep kend\|kc1
        ka3=\E[5~, kb2=\EOu, kbs=^?, kc1=\E[4~, kc3=\E[6~,
        kel=\E[1;2F, kend=\E[4~, kf1=\EOP, kf10=\E[21~,
[schwarzgerat](0) $ export | grep TERM
declare -x COLORTERM="truecolor"
declare -x TERM="st-256color"
[schwarzgerat](0) $
```

The upshot of this is that sequence `\E[4~` always looks like `kend`, and never `kc1`. I can't imagine a situation where this would really matter -- in `xfce4-terminal`, `kc1` is left undefined (likewise kitty). 

So I'm not too worried about that, though I think the suckless people probably ought kill these duplicate definitions. I just took a look at st.suckless.org and didn't see a place to file a bug in the thirty seconds I bothered to spend =].

I'll look into the tmux business -- very strange that the `SUPPRESS_BANNER` option would have such an effect. And you say exiting tmux resolved the problem? You were running `st` where it worked?

If necessary, would it be possible to take a look at your source?

Thanks for the report!

**Comment by dankamongmen** [comment]
btw i really dig the look of your program

**Comment by ton** [comment]
Thanks for the pointers! Indeed I found a couple of duplicate definitions in my `st.info` file similar to `kc1` judging by the name (`ka1`, `ka3`, `kc1`, and `kc3`). Removing these duplicates fixes the warnings when running the program above directly in st, but it does not fix the background coloring issue within a tmux session.

What does fix the tmux coloring issue though is just setting `TERM=st-256color` within tmux! So I'm not sure what is going on...I've attached my `tmux-256color.info` file, maybe it is useful to figure out what is going on in tmux: [tmux-256color.info.gz](https://github.com/dankamongmen/notcurses/files/5869930/tmux-256color.info.gz). I think now it is just as likely a bug in `tmux`  or `st`? I'm using the tmux 3.1c.

When I have more time I'll try to do some debugging myself as well to figure out what is going on.
 
> I'll look into the tmux business -- very strange that the `SUPPRESS_BANNER` option would have such an effect. And you say exiting tmux resolved the problem? You were running `st` where it worked?

What fixed it indeed was running the program directly in st, not within a tmux session.

> If necessary, would it be possible to take a look at your source?

I assume you mean the `st` code? It is here: https://github.com/ton/st/tree/personal.

> Thanks for the report!

Thank you for the detailed reply! Good luck @ FOSDEM with the presentation ;)

**Comment by dankamongmen** [comment]
I'm going to spin up a tmux + st environment today and see if I can duplicate this.

> I assume you mean the st code?

nah i meant your code, which i see is available. Alright, I hope to have something intelligent to report back by tomorrow.

**Comment by dankamongmen** [comment]
Hrmmm. I don't seem to be reproducing this, unless I misunderstand something. I took your sample code from above and compiled it against the current notcurses head. I've put this on the branch `dankamongmen/1314`. When I compile and run it, the text gets the grey background, as expected.

`xfce4-terminal`, `vte-256color`

![2021-02-02-020307_802x902_scrot](https://user-images.githubusercontent.com/143473/106564127-cda9f000-64fa-11eb-8669-7ecffba6f32d.png)

i'm about to go to sleep, but i'll look into it further tomorrow. this is the last blocker on 2.1.8.

**Comment by dankamongmen** [comment]
a quick `valgrind` pass doesn't show any uninitialized conditionals/accesses.

**Comment by ton** [comment]
I found it is only a problem in `tmux` for me. I do not have any time short-term to look into this, in two weeks I have more time and I'll build against a debug version of notcurses to see what is going on. Please do not keep this from releasing new versions of `notcurses` :) It is not a major issue (at least for me). Thanks so much for your effort on this and notcurses, I really enjoy using it!

**Comment by dankamongmen** [comment]
> I found it is only a problem in `tmux` for me. I do not have any time short-term to look into this, in two weeks I have more time and I'll build against a debug version of notcurses to see what is going on. Please do not keep this from releasing new versions of `notcurses` :) It is not a major issue (at least for me). Thanks so much for your effort on this and notcurses, I really enjoy using it!

duh, right, that's what i get for trying to fix things when i've been up all night. ok, tonight an adventure with tmux! tally-ho!

**Comment by dankamongmen** [comment]
OK, I can reproduce this now in `tmux`. I've also learned enough about tmux to do basic configuration, ala:

```
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",vte-256color:Tc"
```

with these plus `COLORTERM=24bit`, i'm able to get proper `notcurses-demo` output, so that's a start. I think this is probably resolvable.

**Comment by dankamongmen** [comment]
whoa, when I enter `vim` in `tmux-direct`, it has a terrible blue background, and everything is wonky. This doesn't happen with `tmux-256color` + `COLORTERM=24bit`, interesting. I think vim doesn't love the `foo-direct` `TERM` settings.

**Comment by dankamongmen** [comment]
ok, so just notes to myself...a base cell is in play, with 0x20/0x20/0x20 background, on this status line plane. it doesn't look like the colors are being set at all for the plane, so we would expect the base cell colors to be substituted in for both channels at all points (indeed, that's the only way the base cell could properly be generating the background where text exists)...so yeah, that base cell background ought definitely be getting substituted in at all cells. let's verify that first -- the output of `paint()` ought be all cells with a 0x20/0x20/0x20 background. i assume that's right, since we see the right behavior outside of tmux.

so the next step is rasterization. it looks like `tmux-256color` **does not** export an `oc` capability; eh, that's to be expected with the lack of `ccc`. there's also no `bce`. `op` is the expected `\E[39;49m`.

**Comment by dankamongmen** [comment]
```
x: 1 nobackground: 0
RAST 0000006a [j] to 58/1 cols: 1 0000000040202020
x: 2 nobackground: 0
RAST 0000002f [/] to 58/2 cols: 1 0000000040202020
x: 3 nobackground: 0
RAST 0000006b [k] to 58/3 cols: 1 0000000040202020
x: 4 nobackground: 0
RAST 0000003a [:] to 58/4 cols: 1 0000000040202020
x: 5 nobackground: 0
RAST 00000020 [ ] to 58/5 cols: 1 0000000040202020
x: 6 nobackground: 0
RAST 00000073 [s] to 58/6 cols: 1 0000000040202020
x: 7 nobackground: 0
RAST 00000063 [c] to 58/7 cols: 1 0000000040202020
x: 8 nobackground: 0
RAST 00000072 [r] to 58/8 cols: 1 0000000040202020
x: 9 nobackground: 0
RAST 0000006f [o] to 58/9 cols: 1 0000000040202020
x: 10 nobackground: 0
```

channels are right in the solved frame. this is either a rasterization bug, or something with tmux.

**Comment by dankamongmen** [comment]
```
RAST 00000020 [ ] to 58/79 cols: 1 0000000040202020
x: 1 nobackground: 0
x: 1 eliding BG RGB
RAST 0000006a [j] to 58/1 cols: 1 0000000040202020
x: 2 nobackground: 0
x: 2 eliding BG RGB
RAST 0000002f [/] to 58/2 cols: 1 0000000040202020
x: 3 nobackground: 0
x: 3 eliding BG RGB
RAST 0000006b [k] to 58/3 cols
```

if we're emitting an `op` in there, we can't be eliding the background RGB. is this due to the split-`op` optimization? perhaps tmux doesn't support that? let's see...

**Comment by dankamongmen** [comment]
also interesting: at first, the background shows up everywhere, as expected. when we hit '?', it goes away behind non-space characters. when we hit '?' again, it's still gone at the non-space characters *from the previous write*. it's not like we restore the background when we get to the second '?' screen.`main()` runs `ncplane_erase()` following a `notcurses_getc_blocking()`, before it calls `print_status_line()` again. we detect the damage correctly -- here's the switch back to '?', note the elisions at offsets 74 and 79, which are exactly the two columns which still have their proud grey backgrounds:

```
GONNA EMIT THEM DEFAULTS
NEEDN'T EMIT SHIT
x: 72 nobackground: 0
x: 72 eliding BG RGB
RAST 00000020 [ ] to 58/72 cols: 1 0000000040202020
GONNA EMIT THEM DEFAULTS
NEEDN'T EMIT SHIT
x: 73 nobackground: 0
x: 73 eliding BG RGB
RAST 00000020 [ ] to 58/73 cols: 1 0000000040202020
GONNA EMIT THEM DEFAULTS
NEEDN'T EMIT SHIT
x: 75 nobackground: 0
x: 75 eliding BG RGB
RAST 00000020 [ ] to 58/75 cols: 1 0000000040202020
GONNA EMIT THEM DEFAULTS
NEEDN'T EMIT SHIT
x: 76 nobackground: 0
x: 76 eliding BG RGB
RAST 00000020 [ ] to 58/76 cols: 1 0000000040202020
GONNA EMIT THEM DEFAULTS
NEEDN'T EMIT SHIT
x: 77 nobackground: 0
x: 77 eliding BG RGB
RAST 00000020 [ ] to 58/77 cols: 1 0000000040202020
GONNA EMIT THEM DEFAULTS
NEEDN'T EMIT SHIT
x: 78 nobackground: 0
x: 78 eliding BG RGB
RAST 00000020 [ ] to 58/78 cols: 1 0000000040202020
```

**Comment by dankamongmen** [comment]
whether writing a banner or not, we're emitting two and only two serious ops in the rasterization series, an FgOP and an SETAB.

**Comment by dankamongmen** [comment]
so, as far as i can tell, this is a `tmux` bug. we emit a `setab 32,32,32` (32 == 0x20), and once we have, we ought not get a default background when we write new characters. i'm going to file a bug on this at https://github.com/tmux/tmux/issues, though first i'm going to extract the rasterized string and make sure. i need to do some dayjob first, though, but by the end of the day today EST i ought either have a fix or an upstream bug filed. thanks for your patience!

**Comment by dankamongmen** [comment]
here's our output when redirected to a file:

```
00000000: 1b5b 3539 3b31 481b 5b33 396d 1b5b 3438  .[59;1H.[39m.[48
00000010: 3b32 3b33 323b 3332 3b33 326d 203f 3a20  ;2;32;32;32m ?: 
00000020: 6865 6c70 2020 2020 2020 2020 2020 2020  help            
00000030: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000040: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000050: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000060: 2020 2020 2020 2020 2020 2020 1b5b 3247              .[2G
00000070: 6a2f 6b3a 2073 6372 6f6c 6c1b 5b43 7570  j/k: scroll.[Cup
00000080: 2f64 6f77 6e1b 5b32 3447 432d 422f 432d  /down.[24GC-B/C-
00000090: 463a 1b5b 4370 6167 651b 5b43 7570 2f64  F:.[Cpage.[Cup/d
000000a0: 6f77 6e1b 5b34 3847 713a 1b5b 4371 7570  own.[48Gq:.[Cqup
000000b0: 7265 7373 1b5b 4361 6e79 1b5b 436b 6579  ress.[Cany.[Ckey
000000c0: 1b5b 4374 6f1b 5b43 636c 6f73 651b 5b43  .[Cto.[Cclose.[C
000000d0: 6865 6c70 1b5b 3247 3f3a 2068 656c 7020  help.[2G?: help 
000000e0: 2020 201b 5b43 2020 2020 2020 201b 5b32     .[C       .[2
000000f0: 3447 2020 2020 2020 2020 1b5b 4320 2020  4G        .[C   
00000100: 201b 5b43 2020 2020 2020 201b 5b34 3847   .[C       .[48G
00000110: 2020 1b5b 4320 2020 2020 2020 1b5b 4320    .[C       .[C 
00000120: 2020 1b5b 4320 2020 1b5b 4320 201b 5b43    .[C   .[C  .[C
00000130: 2020 2020 201b 5b43 2020 2020 1b5b 3f31       .[C    .[?1
00000140: 681b 3d1b 5b33 393b 3439 6d1b 5b6d 0f1b  h.=.[39;49m.[m..
00000150: 5b33 393b 3439 6d1b 5b6d 0f              [39;49m.[m.
```

**Comment by dankamongmen** [comment]
that 1b5b3247 is ESC, '[', 1, 'G', an `hpa` sequence (horizontal position absolute), as expected. hrmmm, but what are those `[C` and `[24G` sequences?

**Comment by dankamongmen** [comment]
the `[C` is a `cuf1`

**Comment by dankamongmen** [comment]
the `[24G` is just another `hpa` forward. they're all positional escapes, and ought not be affecting styling.

**Comment by dankamongmen** [comment]
to close that out, the `[39` is our FgOP and `[48` is of course our SETAB 20,20,20

**Comment by dankamongmen** [comment]
hrmmm, though...go into a tmux and run the following:

`tput setab 32 && echo -n " herp derp                    " && tput hpa 1 && sleep 3 && echo "foo frah frap frick"`

we do *not* see the behavior we're seeing in the Notcurses program. so maybe we're writing something extra that redirecting to a file is hiding from us? hrmmm.

**Comment by dankamongmen** [comment]
> hrmmm, though...go into a tmux and run the following:
> 
> `tput setab 32 && echo -n " herp derp " && tput hpa 1 && sleep 3 && echo "foo frah frap frick"`
> 
> we do _not_ see the behavior we're seeing in the Notcurses program. so maybe we're writing something extra that redirecting to a file is hiding from us? hrmmm.

```
[schwarzgerat](2) $ ( tput setab 32 && echo -n " herp derp                    " && tput hpa 1 && sleep 3 && echo "foo frah frap frick" ) | xxd
00000000: 1b5b 3438 3b35 3b33 326d 2068 6572 7020  .[48;5;32m herp 
00000010: 6465 7270 2020 2020 2020 2020 2020 2020  derp            
00000020: 2020 2020 2020 2020 1b5b 3247 666f 6f20          .[2Gfoo 
00000030: 6672 6168 2066 7261 7020 6672 6963 6b0a  frah frap frick.
[schwarzgerat](0) $ 
```

**Comment by dankamongmen** [comment]
ok, i'm gonna go ahead and cut 2.1.8, but we're definitely getting to the bottom of this.

**Comment by dankamongmen** [comment]
> ok, i'm gonna go ahead and cut 2.1.8, but we're definitely getting to the bottom of this.

alright, back on this; it's blocking 2.2.0.

**Comment by dankamongmen** [comment]
oh shit, i wonder if this is somehow interaction with the tmux status bar? surely not, one would think...but let's lock it out...

**Comment by dankamongmen** [comment]
nope! `set -g status off` disables the status bar, but we still see the problem.

**Comment by dankamongmen** [comment]
as expected, amending `ncpile_rasterize_inner()` thusly "fixes" the issue:

```
diff --git src/lib/render.c src/lib/render.c
index 9bcd5696b..604df916c 100644
--- src/lib/render.c
+++ src/lib/render.c
@@ -1010,9 +1010,10 @@ notcurses_rasterize_inner(notcurses* nc, const ncpile* p, FILE* out){
           nc->rstate.bgelidable = false;
         }else if(!cell_bg_default_p(srccell)){ // rgb background
           cell_bg_rgb8(srccell, &br, &bg, &bb);
+          /*
           if(nc->rstate.bgelidable && nc->rstate.lastbr == br && nc->rstate.lastbg == bg && nc->rstate.lastbb == bb){
             ++nc->stats.bgelisions;
-          }else{
+          }else*/{
             if(term_bg_rgb8(nc->tcache.RGBflag, nc->tcache.setab,
                             nc->tcache.colors, out, br, bg, bb,
                             nc->tcache.bg_collides_default)){
```

but it loses a crucial optimization, so that's a no-go. but what does this tell us?

**Comment by dankamongmen** [comment]
so yeah, somehow our background state is being reset between rasterizations. so we ought be able to isolate that from between what we output, and the `tpus` series above...if we can find no difference (i thought we already performed this differential analysis, but maybe not?), we need to check and ensure there's not perhaps something we're emitting only when connected to a real terminal (as opposed to redirected)

**Comment by dankamongmen** [comment]
so we're moving with `hpa` wherever we're not damaged (and those cells are correct), i would think...and we do see some `hpa` in there...but we also seem to see a lot of `cuf1`? do cut `hpa` down to `cuf1` when we're only moving 1?

**Comment by dankamongmen** [comment]
> so we're moving with `hpa` wherever we're not damaged (and those cells are correct), i would think...and we do see some `hpa` in there...but we also seem to see a lot of `cuf1`? do cut `hpa` down to `cuf1` when we're only moving 1?

indeed we do. but it's only the characters that we're *printing* that are losing their backgrounds.

**Comment by dankamongmen** [comment]
so yeah, all we do is emit a `hpa` to offset 2. we look exactly like the `tpus`-based output in that regard. i mean, the **exact** same: tputs:

```
.[48;5;32m herp 
00000010: 6465 7270 2020 2020 2020 2020 2020 2020  derp            
00000020: 2020 2020 2020 2020 1b5b 3247 666f 6f20          .[2Gfoo 
```

us:

```
.[48
00000010: 3b32 3b33 323b 3332 3b33 326d 203f 3a20  ;2;32;32;32m ?: 
00000020: 6865 6c70 2020 2020 2020 2020 2020 2020  help            
00000030: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000040: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000050: 2020 2020 2020 2020 2020 2020 2020 2020                  
00000060: 2020 2020 2020 2020 2020 2020 1b5b 3247              .[2G
00000070: 6a2f 6b3a 2073 6372 6f6c 6c1b 5b43 7570  j/k: scroll.[Cup
```

our 48 looks slightly different...could that possibly be it?

here's the entirety of the relevant operation:
```
write(3, "\33[?1002;1006l", 13)         = 13                                                                                                                                                                                                                                                                                                           
brk(0x55b162793000)                     = 0x55b162793000                                                                                                                                                                                                                                                                                               
fcntl(0, F_GETFL)                       = 0x402 (flags O_RDWR|O_APPEND)                                                                                                                                                                                                                                                                                
fcntl(0, F_SETFL, O_RDWR|O_APPEND|O_NONBLOCK) = 0                                                                                                                                                                                                                                                                                                      
brk(0x55b1627b7000)                     = 0x55b1627b7000                                                                                                                                                                                                                                                                                               
write(3, "\33[?1h\33=", 7)              = 7                                                                                                                                                                                                                                                                                                            
write(3, "\33[?25l", 6)                 = 6                                                                                                                                                                                                                                                                                                            
write(3, "\33[?1049h", 8)               = 8                                                                                                                                                                                                                                                                                                            
write(3, "\33[H\33[J", 6)               = 6                                                                                                                                                                                                                                                                                                            
ioctl(3, TIOCGWINSZ, {ws_row=70, ws_col=80, ws_xpixel=1280, ws_ypixel=2240}) = 0                                                                                                                                                                                                                                                                       
brk(0x55b1627e5000)                     = 0x55b1627e5000                                                                                                                                                                                                                                                                                               
mmap(NULL, 180224, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f48e3129000                                                                                                                                                                                                                                                            
write(1, "\33[70;1H\33[39m\33[48;2;32;32;32m ?: help                                                                        ", 108) = 108                                                                                                                                                                                                              
ppoll([{fd=0, events=POLLIN|POLLRDHUP}], 1, NULL, [], 8) = 1 ([{fd=0, revents=POLLIN}])                                                                                                                                                                                                                                                                
write(1, "\33[?1h\33=\33[39;49m\33[m\17", 19) = 19                                                                                                                                                                                                                                                                                                     
read(0, "?", 1)                         = 1                                                                                                                                                                                                                                                                                                            
ppoll([{fd=0, events=POLLIN|POLLRDHUP}], 1, {tv_sec=0, tv_nsec=0}, [], 8) = 0 (Timeout)                                                                                                                                                                                                                                                                
ioctl(3, TIOCGWINSZ, {ws_row=70, ws_col=80, ws_xpixel=1280, ws_ypixel=2240}) = 0                                                                                                                                                                                                                                                                       
write(1, "\33[2Gj/k: scroll\33[Cup/down\33[24GC-B/C-F:\33[Cpage\33[Cup/down\33[48Gq:\33[Cqupress\33[Cany\33[Ckey\33[Cto\33[Cclose\33[Chelp", 104) = 104                                                                                                                                                                                                
ppoll([{fd=0, events=POLLIN|POLLRDHUP}], 1, NULL, [], 8) = 1 ([{fd=0, revents=POLLIN}])                                                                                                                                                                                                                                                                
read(0, "q", 1)                         = 1                                                                                                                                                                                                                                                                                                            
ppoll([{fd=0, events=POLLIN|POLLRDHUP}], 1, {tv_sec=0, tv_nsec=0}, [], 8) = 0 (Timeout)                                                                                                                                                                                                                                                                
ioctl(3, TIOCGWINSZ, {ws_row=70, ws_col=80, ws_xpixel=1280, ws_ypixel=2240}) = 0                                                                                                                                                                                                                                                                       
write(1, "\33[2G?: help    \33[C       \33[24G        \33[C    \33[C       \33[48G  \33[C       \33[C   \33[C   \33[C  \33[C     \33[C    ", 104) = 104                                                                                                                                                                                                
ppoll([{fd=0, events=POLLIN|POLLRDHUP}], 1, NULL, [], 8) = 1 ([{fd=0, revents=POLLIN}])                                                                                                                                                                                                                                                                
read(0, "q", 1)                         = 1                                              
```

**Comment by dankamongmen** [comment]
hrmm. we emit this after printing `?: help                         `, right before reading `?`:

`write(1, "\33[?1h\33=\33[39;49m\33[m\17", 19) = 19 `

what is this?

**Comment by dankamongmen** [comment]
\33 is octal for ESC so `ESC[?1hESC=ESC[39;49mESC[m\17`

**Comment by dankamongmen** [comment]
`ESC[39;49m` is an `op` and is 100% what's fucking us

**Comment by dankamongmen** [comment]
> `ESC[39;49m` is an `op` and is 100% what's fucking us

yeah because @ton is using default foreground color, and thus there's no problem with this. but the background gets killed. the cells we skip over with `hpa` or `cuf` aren't affected, but anything we touch gets cleared. that's 100% what's going on here. alright, time to figure out why we're emitting this `op`, and the problem will be solved, huzzah.

**Comment by dankamongmen** [comment]
so we have the 108-byte `write()`, corresponding (presumably) to `notcurses_render()`. then there's a `ppoll()` on stdin, then we `write()` the crap string to stdout, then we `read()` the '?' from stdin. is this possibly related to input?

**Comment by dankamongmen** [comment]
what what what?

i added a `sleep(5)` immediately before the `getc()` in `handle_input()` (i.e. after the poll for `block_on_input()`), and this is what we see:

```
write(1, "\33[70;1H\33[39m\33[48;2;32;32;32m ?: help                                                                        ", 108) = 108                                                                                                                                                                                                              
ppoll([{fd=0, events=POLLIN|POLLRDHUP}], 1, NULL, [], 8) = 1 ([{fd=0, revents=POLLIN}])                                                                                                                                                                                                                                                                
clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=5, tv_nsec=0}, 0x7ffc13263f70) = 0                                                                                                                                                                                                                                                                          
write(1, "\33[?1h\33=\33[39;49m\33[m\17", 19) = 19                                                                                                                                                                                                                                                                                                     
read(0, "?", 1)   
```

so yeah, this is somehow being emitted between the `poll()` and the `read()`. indeed, it's being emitted between the **`sleep()`** and the `read()`(!?). is this possibly glibc? surely not...and why would it depend on our terminal? let's deode the remainder of the mystery string...
```

**Comment by dankamongmen** [comment]
```
ESC[?1hESC=
ESC[39;49m
ESC[m\17
```

`smkx=\E[?1h\E=`
`op=\E[39;49m`
`sgr0=\E[m\017`

so that's `smkx` + `op` + `sgr0`, pretty much a terminal reset. where the fuck is it coming from?

**Comment by dankamongmen** [comment]
is it possible we're not flushing output in initialization?!?!...and then doing a direct `write()` in rasterization...and only then flushing somehow? we do write `smkx` in `interrogate_terminfo()`...

**Comment by dankamongmen** [comment]
nope, that's the `write(3, "\33[?1h\33=", 7)` early on.

**Comment by dankamongmen** [comment]
switching to `read()` from `getc()` fixes the issue. **WHY?!?!?!**

**Comment by dankamongmen** [comment]
does tmux possibly shim `getc()` or something?

**Comment by dankamongmen** [comment]
i don't see anything immediately obvious in the `tmux` source code, but that's quite definitely what's happening. calling `getc()` is emitting (the first time only) a terminal properties reset. changing it to `read()` bypasses this. i have no idea where this behavior is coming from, and intend to get to the bottom of it, but @ton , i believe we have a fix for you.

**Comment by dankamongmen** [comment]
I believe this to be fixed. The fix will be present in 2.2.0, and 2.1.9 before that (if 2.1.9 is released). Please verify. Thanks for the report, and your patience, @ton !

**Comment by ton** [comment]
I can confirm this issue is now fixed, thanks!

**Comment by dankamongmen** [comment]
> I can confirm this issue is now fixed, thank you!

awesome, thanks for the high-quality report and your patience =]

**Comment by ton** [comment]
My pleasure, it was interesting to read how you finally squashed this one. Nice approach on documenting your though process while debugging code; I might adapt it, it is great as a documentation to refer to later on as well!

**Comment by dankamongmen** [comment]
> My pleasure, it was interesting to read how you finally squashed this one. Nice approach on documenting your though process while debugging code; I might adapt it, it is great as a documentation to refer to later on as well!

i smoke too much weed not to write down what i'm thinking
