### ISSUE TITLE
write a better screen/tmux

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1332]
Anything involving `screen`, `tmux` or even `mosh` has been unpleasant and underwhelming. It is becoming obvious that, just like Curses, these are products of old thinking, and outdated modalities. We've got just about everything necessary to write One Screen Manager/Multiplexor to Rule Them All with very little additional code.

I think we ought marinate on a badass name, and move forward once inspiration strikes on that front.

This of course has ramifications on #381 and possibly others.

https://user-images.githubusercontent.com/143473/107105251-4e1a6a80-67f3-11eb-872d-df54a42dc53f.mp4

**Comment by WSLUser** [comment]
So ignoring the session stuff, an actual pane is actually pretty decent with Windows Terminal and is based on WinUI (Mono could be used for Linux if considering the UI part only) .  This may make no difference to this issue but figured a good example for the panes at least should be mentioned. Also there is an enhancement project to make screen to make it look better, byobu: https://www.byobu.org/ and might provide a source of inspiration as well.

**Comment by dankamongmen** [comment]
> So ignoring the session stuff, an actual pane is actually pretty decent with Windows Terminal and is based on WinUI (Mono could be used for Linux if considering the UI part only) . This may make no difference to this issue but figured a good example for the panes at least should be mentioned. Also there is an enhancement project to make screen look better, byobu: https://www.byobu.org/ and might provide a source of inspiration as well.

for some reason i've spent over a decade thinking `byobu` to be a disk space analyzer

**Comment by WSLUser** [comment]
I've personally never used it but I have heard some good things about it. I'm used to running plain old screen if I need to keep a session running for a long running script.

**Comment by dankamongmen** [comment]
> I've personally never used it but I have heard some good things about it. I'm used to running plain old screen if I need to keep a session running for a long running script.

from what i've seen, screen doesn't support TrueColor aside from in specially-compiled variants of screen5. given that alacritty doesn't support scrollback natively, and encourages tmux etc to effect this, i'm suddenly more interested in quality multiplexor support.

what's the common term for these tools (screen, tmux, etc)? multiplexors? screen managers?

**Comment by WSLUser** [comment]
They're referred to as multiplexers typically. Also screen uses xterm-screen, There's some color support but that's likely being provided by the terminal. In Windows Terminal, I ssh to a Linux server then enter screen.  If you do `echo $TERM` it comes back as `screen.xterm-256color`. Interestingly running screen on ITerm2 provides a $TERM of `screen`. So Mac is a bit different.

**Comment by dankamongmen** [comment]
I think I'm coming into agreement with @kovidgoyal that this kind of thing belongs in the terminal emulator itself, if anywhere. closing this up as a NONFIX.

**Comment by kovidgoyal** [comment]
Hurray a convert :)
