### ISSUE TITLE
get an ubuntu lts 20.04 backport

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1356]
I've got notcurses 2.2.2 built in a Focal PPA:

```sh
sudo add-apt-repository ppa:dankamongmen/notcurses
sudo apt-get update
```

but it would be better to be in Backports, using the following procedure: https://wiki.ubuntu.com/UbuntuBackports

I think we ought do this shortly after the Hirsute debian freeze (https://discourse.ubuntu.com/t/hirsute-hippo-release-schedule/18539 claims this week). So 2.2.2 sounds good. We need fetch the Hirsute package, change it up, and get `debdiff` results. Things we'll have to change:

* release in `debian/changelog`
* probably not version number, assuming it was changed for us on hirsute import
* `debian/*.install` needs `{DEB_HOST_MULTIARCH}` replaced with `*`
* change `debcompat` level to 12 from 13 in `debian/control`

once it builds, get the `debdiff` output between hirsute and focal, and also `notcurses-tester` and `notcurses-demo` output. then submit it all with `requestbackport`. it's unlikely that `backportpackage` will work for us, as i expect source changes to be necessary.

**Comment by dankamongmen** [comment]
I've made a `debdiff` with minimal changes (none to `debian/changelog`, since apparently none were made for the hirsute import).

[focal.diff.txt](https://github.com/dankamongmen/notcurses/files/6019494/focal.diff.txt)

**Comment by dankamongmen** [comment]
https://bugs.launchpad.net/focal-backports/+bug/1916430

**Comment by TamaMcGlinn** [comment]
Perhaps a silly question, but what is the package name? I was expecting the README installation instructions to also say:

```
sudo apt install notcurses
```

but they don't, and I get "E: Unable to locate package notcurses"

**Comment by dankamongmen** [comment]
> Perhaps a silly question, but what is the package name? I was expecting the README installation instructions to also say:
> 
> ```
> sudo apt install notcurses
> ```
> 
> but they don't, and I get "E: Unable to locate package notcurses"

Depends on the distro. Since you're asking on a Ubuntu Focal-related issue, the answer is that it's not yet available in Ubuntu Focal, and won't be unless I get my backport added (see link above). In Debian-derived systems like Ubuntu, the packages are:

* `notcurses-bin`: `notcurses-demo`, `ncplayer`, and other binaries built from notcurses
* `libnotcurses-core-dev`: development files for the core library
* `libnotcurses-dev`: development files for the entire library, including multimedia
* `libnotcurses++-dev`: development files for C++
* `libnotcurses2`: shared library including multimedia
* `libnotcurses-core2`: core shared library
* `libnotcurses++2`: c++ core shared library

there are some others for python etc.

if you want to install on ubuntu focal, the best method is either building from source, or using my ppa:

https://launchpad.net/~dankamongmen/+archive/ubuntu/notcurses

btw, this kind of question kinda belongs in the [discussion area](https://github.com/dankamongmen/notcurses/discussions), rather than random bugs, but don't worry about it =].

**Comment by dankamongmen** [comment]
According to https://www.reddit.com/r/Ubuntu/comments/mukw0d/does_anyone_watch_for_ubuntu_backports_bugs/gv6isgl, the "backports pocket is effectively dead". Certainly there has been no response to / action on the bug I filed. Closing this up as NONFIX =[.
