### ISSUE TITLE
serenity os

### ISSUE THREAD

**Issue by sp00ck** [dankamongmen/notcurses#1359]
Meybe moving this lib to  SerenityOS ?
https://github.com/SerenityOS/serenity

**Comment by dankamongmen** [comment]
i'm unfamiliar with serentity. so this is its own kernel, not linux or freebsd? hrmm. i'd be happy to assist in a port+package, but i don't have a serentityos install here, and don't see acquiring one as particularly high on my list of priorities =]. 

are these all the packages/ports currently available? https://github.com/SerenityOS/serenity/tree/master/Ports not too many! 

the packaging system looks pretty alpinish, nothing too difficult there.

so....unless i wake up one day just jonesing to install a new OS, i don't see myself making progress on this anytime soon. i will, however, leave the bug open, and if any SerentityOS users/hax0rs want to try getting it going, i'll be more than happy to offer any help and assistance i can.

**Comment by sp00ck** [comment]
this is just idea. nothing more.

**Comment by dankamongmen** [comment]
i took a deeper look into Serenity today, @sp00ck , and it seems pretty cool! i went ahead and filed an issue in their tracker to introduce myself and get this effort started.

**Comment by dankamongmen** [comment]
they shut me right down, with the claim that Serenity has a "strict policy of using no third-party libraries". glad i asked!
