### ISSUE TITLE
add graphing widgets (histogram etc)

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#136]
We ought add the ability to draw graphs (histograms at least are present in the Curses Development Kit). Ours ought of course look much better :D. Once we have them, an awesome demo would be collecting the results of each demo, and graphing them at the end (total time, FPS, etc.). This is probably a post-1.0 activity.

**Comment by dankamongmen** [comment]
@jart i have no idea if you'd be interested, but if you wanted to take this on, I bet you could do a really good job with it.

**Comment by dankamongmen** [comment]
https://pypi.org/project/plotille/

**Comment by dankamongmen** [comment]
https://github.com/Evizero/UnicodePlots.jl

**Comment by dankamongmen** [comment]
I really like what's going on here:

https://github.com/yaronn/blessed-contrib (python)
https://github.com/fdehau/tui-rs (rust)

**Comment by jart** [comment]
Sorry but I can't contribute to projects with GPL runtime libraries.

**Comment by dankamongmen** [comment]
These would be useful for #162, which I've just scheduled for 1.0.0. So it would be awfully nice to get some of these done -- at least horizontal histograms -- by that time.

**Comment by dankamongmen** [comment]
> These would be useful for #162, which I've just scheduled for 1.0.0. So it would be awfully nice to get some of these done -- at least horizontal histograms -- by that time.

Though, honestly, block characters are probably superior to Braille for horizontal histograms. I think we actually can get more resolution that way (8 v 2 per cell). So let's do that for horizontal histograms, but look at an overarching graph-creation API that unifies both. A user shouldn't need to know whether their graph is being rendered with blocks or dots.

**Comment by jart** [comment]
You downvoted me? :cry:

Would a scripted subprocess be sufficient for now? I wrote this just now, for you, since I love your project and want to help it be successful: https://gist.github.com/jart/2b2f1322f08a7a7457128559cdc7683c

With minimal effort, you could incorporate embed this script into your program using the gas `.incbin` directive and then fork+exec a subprocess. I don't know if you care about pure WIN32 (i.e. no cygwin and msys) but you'd basically have to rewrite the script in c++ to download derasterize and then launch it via `CreateProcess()` which is fine since it only links KERNEL32.

You could also embed the source code to derasterize (licensed isc), write your own equation lexer/parser, and feed it into the rendering algorithm.

**Comment by dankamongmen** [comment]
> You downvoted me? 
> 
> Would a scripted subprocess be sufficient for now? I wrote this just now, for you, since I love your project and want to help it be successful: https://gist.github.com/jart/2b2f1322f08a7a7457128559cdc7683c
> 
> With minimal effort, you could embed this script into your program using the gas `.incbin` directive and then fork+exec a subprocess. I don't know if you care about pure WIN32 (i.e. no cygwin and msys) but you'd basically have to rewrite the script in c++ to download derasterize and then launch it via `CreateProcess()` which is fine since it only links KERNEL32.
> 
> You could also embed the source code to derasterize (licensed isc), write your own equation lexer/parser, and feed it into the rendering algorithm.
> 
> ![derasterize-gnuplot](https://user-images.githubusercontent.com/49262/71416485-76f29700-2615-11ea-8df4-a1f5f741834e.png)

Only downvoted your inability to participate, @jart !

**Comment by dankamongmen** [comment]
Alright, finally started getting some thoughts down here. First off, sample plots (especially time series) using braille/blockchunks/etc:

```c
// Plots. Given a rectilinear area, an ncplot can graph samples along some axis.
// There is some underlying independent variable--this could be measurement
// number, or measurement time. Samples are tagged with this variable, which
// should never fall, but may grow non-monotonically. The desired range in terms
// of the underlying independent variable is provided at creation time. The
// desired domain can be specified, or can be autosolved. Granularity of the
// dependent variable depends on glyph selection.
//
// For instance, perhaps we're sampling load as a time series. We want to
// display an hour's worth of samples in 40 columns and 5 rows. We define the
// x-axis to be the independent variable, time. We'll stamp at second
// granularity. In this case, there are 60 * 60 == 3600 total elements in the
// range. Each column will thus cover a 90s span. Using vertical blocks (the
// most granular glyph), we have 8 * 5 == 40 levels of domain. If we report the
// following samples, starting at 0, using autosolving, we will observe:
//
// 60   -- 1%       |domain:   1--1, 0: 20 levels
// 120  -- 50%      |domain:  1--50, 0: 0 levels, 1: 40 levels
// 180  -- 50%      |domain:  1--50, 0: 0 levels, 1: 40 levels, 2: 40 levels
// 240  -- 100%     |domain:  1--75, 0: 1, 1: 27, 2: 40
// 271  -- 100%     |domain: 1--100, 0: 0, 1: 20, 2: 30, 3: 40
// 300  -- 25%      |domain:  1--75, 0: 0, 1: 27, 2: 40, 3: 33
//
// At the end, we have data in 4 90s spans: [0--89], [90--179], [180--269], [270
// The first two spans have one sample each, while the second two have two
// samples each. Samples within a span are averaged (FIXME we could probably do
// better), so the results are 0, 50, 75, and 62.5. Scaling each of these out
// of 90 and multiplying by 40 gets our resulting levels. The final domain is
// 75 rather than 100 due to the averaging of 100+25/2->62.5 in the third span,
// at which point the maximum span value is once again 75.
//
// The 20 levels at first is a special case. When the domain is only 1 unit,
// and autoscaling is in play, assign 50%.
```

**Comment by dankamongmen** [comment]
We now have simple one-row plots over a range, with automatic windowing. Need to implement the various drawing types, and need to make it multi-row, but the hard part is done.

**Comment by dankamongmen** [comment]
We now have multirow plots in `dankamongmen/plots`. =]

**Comment by dankamongmen** [comment]
We now have multiglyph plots in `dankamongmen/plots`. =]

**Comment by dankamongmen** [comment]
We've got basic histograms now using five different sets of glyphs. 

![2020-04-03-075517_722x857_scrot](https://user-images.githubusercontent.com/143473/78358019-7d7f9b80-7580-11ea-9346-014e09b58f58.png)

looking pretty decent, if i do say so myself!

**Comment by dankamongmen** [comment]
now with lerps

![2020-04-03-081548_722x857_scrot](https://user-images.githubusercontent.com/143473/78359589-5aa2b680-7583-11ea-85d3-503f1005aa75.png)

**Comment by dankamongmen** [comment]
I'm calling this as working sufficiently well for 1.3.0. Shut it down!
