### ISSUE TITLE
honor maximum sprixel size / color register count

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1389]
In XTerm, a sprixel cannot exceed certain dimensions on either side, defined by `XTerm*maxGraphicSize`. The vt340 could reportedly do 800x480. We should determine and respect this limit.

**Comment by WSLUser** [comment]
> The vt340 could reportedly do 800x480.

Did you check xterm docs if newer VT terminals did more (or better)? 800x480 seems like a full screen if not the greatest resolution, would a sprixel then be the entire image? If so, then we'd need to account for the modern era and at least allow 1920x1080, which should fill an entire HD monitor. Supporting 4k resolution would be a different challenge as I don't think the dimensions change, just the amount of pixels being output. Likely we'd still want to stick to the 800x480 as a sane default for the dimension since I'd think we'd still want some space below the image to type into the terminal when in fullscreen mode.

**Comment by dankamongmen** [comment]
> Did you check xterm docs if newer VT terminals did more (or better)? 800x480 seems like a full screen if not the greatest resolution, would a sprixel then be the entire image? If so, then we'd need to account for the modern era and at least allow 1920x1080, which should fill an entire HD monitor. Supporting 4k resolution would be a different challenge as I don't think the dimensions change, just the amount of pixels being output. Likely we'd still want to stick to the 800x480 as a sane default for the dimension since I'd think we'd still want some space below the image to type into the terminal when in fullscreen mode.

you can definitely do bigger, and XTerm allows you to configure this. i would ideally not use a limit unless we actively detect one, which as far as i know is fine so long as `xterm` allows discovery and no one else enforces limits.

**Comment by WSLUser** [comment]
Hmm...I do wonder if it's a terminal's responsibility or not to determine those limits. I guess to some point you'd need to to ensure the terminal doesn't get too small or too large so that's a responsibility but beyond that, I might think a terminal application would set the limits. Whether ncurses does so though is a different story. If they don't, then you probably shouldn't either.

**Comment by dankamongmen** [comment]
It looks like we can read this with:

```
          CSI ? Pi ; Pa ; Pv S  Set or request graphics attribute (XTSMGRAPHICS), xterm.
               Pi = 1  item is number of color registers.
               Pi = 2  item is Sixel graphics geometry (in pixels).
               Pi = 3  item is ReGIS graphics geometry (in pixels).
               Pa = 1  read attribute.
               Pa = 2  reset to default.
               Pa = 3  set to value in Pv.
               Pa = 4  read the maximum allowed value.
```

**Comment by dankamongmen** [comment]
We're now reading the number of color registers on xterm successfully. Hey @dnkl  does `foot` support `XTSMGRAPHICS`?

**Comment by dnkl** [comment]
Yes it does!

**Comment by dankamongmen** [comment]
> Yes it does!

w00t w00t!

**Comment by dnkl** [comment]
(if you have a fairly recent git version installed, all supported escapes are documented in `man foot-ctlseq`).

**Comment by dankamongmen** [comment]
> (if you have a fairly recent git version installed, all supported escapes are documented in `man foot-ctlseq`).

`foot-ctlseqs` (note the `s`), unless i'm missing something

**Comment by dnkl** [comment]
> foot-ctlseqs (note the s), unless i'm missing something

Aye, my bad :D

**Comment by dankamongmen** [comment]
> (if you have a fairly recent git version installed, all supported escapes are documented in `man foot-ctlseq`).

i see you have Window Manipulation stuff set up for pixel reporting. do you fill in the `ws_{y,x}pixel` values in response to  a `TIOCGWINSZ` `ioctl(2)`?

**Comment by dnkl** [comment]
I do!

**Comment by dnkl** [comment]
And, the reported pixel values **exclude** the margins. I.e. you _can_ use it to calculate the cell dimensions.

**Comment by dankamongmen** [comment]
> And, the reported pixel values **exclude** the margins. I.e. you _can_ use it to calculate the cell dimensions.

taste, you have taste.

**Comment by dankamongmen** [comment]
Looks like the response on these is `CSI [ ? Pa ; 0 ; Max_x ; Max_y S`

**Comment by dankamongmen** [comment]
Hrmmm, it would appear that this value (at least in `xterm`) depends on the *current* window geometry:

` 80 cols (11px) Sixel ColorRegs: 16 Max_x: 880 Max_y: 1411`

i then horizontally maximize, and get:

` 312 cols (11px) Sixel ColorRegs: 16 Max_x: 1980 Max_y: 1414`

yuck. we'd need at the very least reread these on geometry changes. i was assuming they were interface limits, and you figured out window pixels via any of the ways one figures out window pixels. this makes it significantly less valuable, urk.

i really don't want to go sticking a terminal query/reply in the resize code, yeargh. `xterm` can delay responses to things like this multiple seconds when it's being heavily worked.

alas, poor Yorick! ugh. alright, probably not going to use the geometry values for now, but it'll be good to have the number of color registers. i took `xterm` down to the default(?) 16 color registers, and libsixel had horrible output, far worse than us. nice =].

**Comment by dankamongmen** [comment]
There's now the question of how to plumb these values through to the blitters. Maybe `unsigned cellpixx` needs to become a `union`?

**Comment by dnkl** [comment]
> Hrmmm, it would appear that this value (at least in xterm) depends on the current window geometry:

`\E[?2;1;0S` will give you the **current** geometry, which depends on the window geometry.

`\E[?2;4;0;S` gives you the **maximum** geometry (as configured by `xterm*maxGraphicSize`).

**Comment by dankamongmen** [comment]
> `\E[?2;4;0S` gives you the **maximum** geometry (as configured by `xterm*maxGraphicSize`).

ahhh, i was thinking 4 was the maximum the app itself supported. i'm guessing this isn't really documented anywhere other than code? if so, people are surely going to have different semantics for it :(.

**Comment by dankamongmen** [comment]
> > `\E[?2;4;0S` gives you the **maximum** geometry (as configured by `xterm*maxGraphicSize`).
> 
> ahhh, i was thinking 4 was the maximum the app itself supported. i'm guessing this isn't really documented anywhere other than code? if so, people are surely going to have different semantics for it :(.

like, the semantics you describe make no sense for color registers, for example

**Comment by dnkl** [comment]
The **current** value, for both colors and pixels, also depend on the application set value (i.e `\E[?2;3;PvS`).

So, for colors, **current** reports whatever value the application has set with `\E[?1;3;PvS` (defaulting to `xterm*maxGraphicSize` in XTerm's case). **maximum** returns whatever maximum value the application supports. I believe this is fixed at 1024 in XTerm.

For geometry, the semantics is more confusing, and not well documented. Foot will report the smallest value of the window geometry, and the sixel max geometry. In XTerm, **maximum** returns the value of `xterm*maxGraphicSize`, and this cannot be changed at runtime. I.e. as far as I know, geometry cannot be changed in XTerm. In foot, `\E[?2;3;x;yS` will change the **maximum** geometry.

**Comment by dankamongmen** [comment]
(1) thanks for the detailed explanation, that makes this much more useful assuming it's implemented that way everywhere and (2) did you get this from source diving or some documented source? i'm trying to gauge the likelihood that semantics on this diverge across terminals, in which case i'd maybe rather just ignore it and do the best i can.

**Comment by dnkl** [comment]
> did you get this from source diving or some documented source

Mostly running XTerm and doing `echo ...` and seeing what it replies with. Occasionally diving into the source code when I fail to see a pattern.

As for judging the likelihood of diverging behavior... I _just_ put up this PR for foot: https://codeberg.org/dnkl/foot/pulls/400. So... kind of likely?

**Comment by dankamongmen** [comment]
oh so your comment implies i can step up the number of color registers from within my application if the user hasn't tricked out their `~/.Xresources`. though hrmmm, that might be "rude".

**Comment by dnkl** [comment]
> oh so your comment implies i can step up the number of color registers from within my application if the user hasn't tricked out their ~/.Xresources. though hrmmm, that might be "rude".

Correct. Might be rude, but considering XTerm defaults to 16 colors(?), you might not have a choice... I'm fairly sure the defaults in XTerm has more to do with being true to what it is emulating (i.e. a VT340), than being sane.

**Comment by dankamongmen** [comment]
> Correct. Might be rude, but considering XTerm defaults to 16 colors(?), you might not have a choice... I'm fairly sure the defaults in XTerm has more to do with being true to what it is emulating (i.e. a VT340), than being sane.

if there is anything in this world of which we can be sure, it is this

**Comment by dankamongmen** [comment]
i think that's `XTerm*decGraphicsID: 340` btw, as distinct from `XTerm*decTerminalID: 420`.

**Comment by dnkl** [comment]
> i think that's XTerm*decGraphicsID: 340 btw, as distinct from XTerm*decTerminalID: 420.

Ooohh, didn't know about that one! :D

**Comment by dankamongmen** [comment]
Alright, we're now plumbing these through. In addition, i'm using *get maximum* with the geometry. This looks good!
