### ISSUE TITLE
add libgpm support

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1405]
@klamonte asked the other day in #1369 whether we supported mouse input in the console through GPM. i feel for sure i've seen this work before, but attempting to demonstrate it with tip of master on my arch laptop failed just now. look into this. we ought be able to work with gpm just fine AFAIK.

**Comment by dankamongmen** [comment]
https://bbs.archlinux.org/viewtopic.php?id=225660 apparently there's a libgpm?

**Comment by dankamongmen** [comment]
so there is!

**Comment by dankamongmen** [comment]
ok, yep, that's what we'd need do. NCURSES programs can get gpm events if NCURSES has been linked against libgpm. we're not an NCURSES program. we thus need link against libgpm ourselves.

```c
/* the following is a heavy thing ... */                                                                                     
extern int gpm_consolefd; /* liblow.c */                                                                                     
```

ahhh this is some solid 90s shit right here. this header has never heard of AIDS.

**Comment by dankamongmen** [comment]
alright, so it looks like gpm support would require:

* setting up a (linux? linux-and-bsd?)-only optional dep on libgpm in CMake
* documenting the new option
* updating packaging for a ~dozen systems to mention the new optional dep
* code to (when libgpm is present) attempt to connect to gpm *when the mouse is enabled*
* code to read from libgpm, which must be interleaved with regular reading
* code to disconnect when the mouse is disabled

**Comment by dankamongmen** [comment]
added connect + close + binding code

**Comment by dankamongmen** [comment]
so i'm thinking about how annoying it will be to multiplex the input functionality, and wondering whether we oughtn't just throw up a thread to watch GPM (after we've connected), and have that side-supply the input buffer. i think we might one day move to controlling input in our own context+thread anyway, so this isn't that crazy an idea.

**Comment by dankamongmen** [comment]
in the `dankamongmen/libgpm-thread` branch we're now spawning (and reaping) a thread, and i've verified that it does get results from `Gpm_GetEvent()`. now we just need to translate those into standard input sequences, and enqueue them into the input layer. we'll need some kind of function exported for that last. shouldn't be tough.

**Comment by dankamongmen** [comment]
```c
                                                                                                                             
typedef struct Gpm_Event {                                                                                                   
  unsigned char buttons, modifiers;  /* try to be a multiple of 4 */                                                         
  unsigned short vc;                                                                                                         
  short dx, dy, x, y; /* displacement x,y for this event, and absolute x,y */                                                
  enum Gpm_Etype type;                                                                                                       
  /* clicks e.g. double click are determined by time-based processing */                                                     
  int clicks;                                                                                                                
  enum Gpm_Margin margin;                                                                                                    
  /* wdx/y: displacement of wheels in this event. Absolute values are not                                                    
   * required, because wheel movement is typically used for scrolling                                                        
   * or selecting fields, not for cursor positioning. The application                                                        
   * can determine when the end of file or form is reached, and not                                                          
   * go any further.                                                                                                         
   * A single mouse will use wdy, "vertical scroll" wheel. */                                                                
  short wdx, wdy;                                                                                                            
}              Gpm_Event;
```

this is the lovely structure we'll be interpreting

**Comment by dankamongmen** [comment]
first off, we need to mask the events so that we're only receiving them when a button is pressed (ala terminal-driven mouse reporting). right now we get events whenever the mouse is moved.

**Comment by dankamongmen** [comment]
huh, people are probably going to want the option to get events whenever the mouse moves, won't they? for popup tooltips and that kind of thing. huh.

**Comment by dankamongmen** [comment]
i've set `eventMask` to `DOWN | UP | DRAG` (leaving out `MOVE`), and this gets us only the events we want.

one thing i've noticed is that once we start, the mouse "cursor" is no longer visible. might need to emit c1000?

just need to shunt the events into the input layer, and this is done.

**Comment by dankamongmen** [comment]
i've added `ncinput_shovel()` for external agents to dump into the input buffer

**Comment by dankamongmen** [comment]
ok, initial support is in. we'll want to refine this -- we're not handling modifiers, for one.

**Comment by klamonte** [comment]
FYI Alpine Linux just fixed a minor issue in libgpm: https://gitlab.alpinelinux.org/alpine/aports/-/issues/12982

**Comment by dankamongmen** [comment]
nice. i think (well, just confirmed) that i forgot to add `-DUSE_GPM=on` to my Alpine APKBUILD for 2.3.18 anyway, so thanks for saving me the time to debug this when i do for the next release =].

**Comment by dankamongmen** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/25017

**Comment by klamonte** [comment]
@dankamongmen I just discovered this today: https://github.com/textshell/minivcmouse

Looks like a way to access mouse on the raw linux console without GPM.  Just in case you hadn't seen it yet, wanted to pass it along.

**Comment by dankamongmen** [comment]
oh interesting let's see if it gets any traction

**Comment by AutumnMeowMeow** [comment]
VTM is doing it too, and he outlined some of the problems he saw with GPM:

https://github.com/netxs-group/vtm/issues/125#issuecomment-1033680605
