### ISSUE TITLE
ncplayer margins not working with -k in master

### ISSUE THREAD

**Issue by ivoanjo** [dankamongmen/notcurses#1411]
Please include the following data:
* `export | egrep 'LANG|LC_CTYPE|TERM'`
```bash
declare -x COLORTERM="truecolor"
declare -x GNOME_TERMINAL_SCREEN="/org/gnome/Terminal/screen/2b518144_8157_497f_8c7e_5d0d825f6e7d"
declare -x GNOME_TERMINAL_SERVICE=":1.110"
declare -x LANG="en_GB.UTF-8"
declare -x LANGUAGE="en_GB:en"
declare -x LC_CTYPE="pt_PT.UTF-8"
declare -x TERM="xterm-256color"
```
* notcurses version (available from `notcurses-demo i`) `notcurses 2.2.3 by nick black et al on xterm-256color`
* terminal name + version `gnome-terminal 3.36.2-1ubuntu1~20.04`

---

Hello and thanks a lot for notcurses -- it's really cool tech!

I'm trying to use `ncplayer` to render images on the terminal. In the default mode, I can specify margins and they work as expected, but when using `-k`, the margins don't show up.

**Comment by dankamongmen** [comment]
This is a completely valid and accurate bug report, though I'm trying to figure out what, exactly, top and bottom margins would mean in a `-k` context. `-k` is using "Direct Mode" (see `notcurses_direct(3)`), which is line-oriented rather than screen-oriented, and doesn't take margin arguments. To be honest, I'd never considered margins in conjunction with `-k`; if I had, I'd likely have simply made them mutually exclusive.

With your bug, however, I'm thinking that left and right margins could be useful in the context of `ncplayer -k`; they wouldn't be very hard to (artificially) implement.

What exactly are you hoping to achieve? Would left and right margins be sufficient for your use case? If so, I'll likely implement them for `-k`, and document that only left and right margins have meaning with `-k`.

Thanks for this thought-provoking bug report!

**Comment by ivoanjo** [comment]
Indeed, good point: left/right margins would be enough for my use-case.

What I was trying to do (and I shouldn't) is pipe the output of `ncplayer` into `git commit` and because `git log` always adds a margin, I need to resize my terminal to get it to show up correctly:

[![](https://ivoanjo.me/img/image-in-commit.gif)](https://ivoanjo.me/blog/2021/03/14/embedding-images-in-commit-logs/)

**Comment by dankamongmen** [comment]
> [![](https://camo.githubusercontent.com/a45c826c2edab97da68f9f9f9be0dfd174f782cc633bbbb141c02a62ff41c79c/68747470733a2f2f69766f616e6a6f2e6d652f696d672f696d6167652d696e2d636f6d6d69742e676966)](https://ivoanjo.me/blog/2021/03/14/embedding-images-in-commit-logs/)

LOL yessssssssssssssssssss let the result of eighteen months of my life be memes in git commit messages. i love it.

ok, i'm going to implement left and right margins for `ncplayer -k`. i might or might not implement top and bottom margins for the `stretch` case, probably not (i fundamentally dislike the impedance mismatch of row margins and line-oriented output).

thanks a lot for this report! i'll try to get it done no later than tomorrow's end; it'll definitely be in 2.3.4.

**Comment by dankamongmen** [comment]
i've gotta say this really made my day

**Comment by ivoanjo** [comment]
Ahaha I'm glad my awful idea paid off :)

**Comment by dankamongmen** [comment]
Hrmmm, this will be less simple than hoped. Our direct mode API provides `ncdirect_render_frame()` and `ncdirect_raster_frame()`; neither accept the full `ncvisual_options` structure that would have made this easy. Hrmm. We pass a `ncscale_e` into `ncdirect_render_frame()`, and the geometry decisions are all made internally to that.

man, `ncplayer` doesn't even expose alignment, like `ncls` does. I should probably add that. I was going to suggest trying `-snone -acenter` for an immediate solution--which might actually work with `ncls`, come to think of it (nope: `ncls` doesn't accept `-s`. wtf.)

alright, if i want to do this, i'm going to need to generalize `ncdirect_render_frame()`, there's no non-disgusting way around that. thankfully, `ncdirect_render_frame()` is pretty new, and i don't think anyone external is calling it. probably just want to take a `ncvisual_options` there.

`ncls` should also be extended to accept `-s` for scaling, and `ncplayer` should be extended to accept `-a` for alignment.

**Comment by dankamongmen** [comment]
`ncvisual_options` also gets us subcropping from the image, should we ever want that. the placement options seem a bit much, though. if you're going to have those, you pretty much need an ncdirect analogue of `ncvisual_geom()`. but they're exactly what we need for simulating margins here....alright, let's add `ncvisual_geom()` and switch `ncdirect_render_frame()` over to an `ncvisual_option`, where `y` will be ignored.

**Comment by dankamongmen** [comment]
> `ncvisual_options` also gets us subcropping from the image, should we ever want that. the placement options seem a bit much, though. if you're going to have those, you pretty much need an ncdirect analogue of `ncvisual_geom()`. but they're exactly what we need for simulating margins here....alright, let's add `ncvisual_geom()` and switch `ncdirect_render_frame()` over to an `ncvisual_option`, where `y` will be ignored.

you *can't* easily introduce an `ncdirect_geom()`, though, because `ncdirect_render_frame()` takes the input file directly. argh!

**Comment by dankamongmen** [comment]
hrmmm. in general, there's no way to tell `ncdirect_render_frame()` the precisely desired output geometry. there isn't in `ncvisual_render()`, either, but there you're rendering to a particular plane whose geometry you *do* control. hrmmmmm. perhaps a maximum length argument to `ncdirect_render_frame()`, which defaults to the screen width? yes, i suppose that would work. feels kinda hokey and non-general, though.

**Comment by dankamongmen** [comment]
btw you might want to use `scalehi` instead of just `scale` @igo95862

**Comment by dankamongmen** [comment]
ok, i've now got the margins being factored in for `scale`, `scalehi`, and `stretch`. i now need to employ them in the rasterizing (right now you just get a smaller image, all the way on the right).

**Comment by dankamongmen** [comment]
ok, i've got a first cut of this. things seem to mainly be working, but they're not yet perfect. @ivoanjo, how would this look for you?

![2021-03-14-223242_802x1417_scrot](https://user-images.githubusercontent.com/143473/111096126-38e0dc00-8515-11eb-898b-f9adf99dbcce.png)

**Comment by dankamongmen** [comment]
Hrmmm, while this is working for `pixel`, it appears to be quite broken for cell-based blitters. Reopening to finish.

**Comment by dankamongmen** [comment]
Alright, it ought be working better now, though it's going to center within the sum of the margins, rather than honoring them particularly (ie -m 0,4,0,20 is going to put you with 12 columns on either side). rigourizing that is complicated, for dumb reasons. i'll get on it, but hopefully this is enough to move you along. pixel graphics do honor a split margin.

**Comment by ivoanjo** [comment]
:ok_hand: perfect for trolling commit messages, thanks!

**Comment by dankamongmen** [comment]
awesome, let me know if you see any problems =]

**Comment by dankamongmen** [comment]
oh, and since you're using cell blitting, you might want to look at `scalehi` as opposed to `scale`.
