### ISSUE TITLE
explore cell-partitioned pixel graphics

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1422]
see the comment on #1388 beginning with the fortuitous phrase "holy jesus". if we precut pixel graphics down into cell-granular regions (only necessary for rendered mode), all the special case code for pixel stuff goes away, and they just become their own cells, one sprixel per cell. that would wreck the sprixel cache, but we would no longer need such a thing--yank it out. we use our standard damage detection for all invalidation -- no need for tricky invalidation maps. we set NOBACKGROUND if we can to avoid a bg emission. this completely eliminates the problem of a graphic both below and above text. it eliminates almost every logical problem. furthermore, this eliminates the sixel quantization problem (almost) entirely, as we'd need a small, fixed number of colors for each cell. a 12 * 14 cell can only have up to 168 colors, for instance.

there are two issues:
* we need to verify terminals can responsively deal with as many sixels as it has cells (where most of them are *not* being redrawn each frame), and
* we need to ensure the increased bandwidth costs aren't overwhelming. they'd only be suffered when using pixel graphics, and are as follows:
  * more overhead from per-graphic fixed costs
  * (sixel only) more overhead from more color registers
  * (sixel only) less ability to use RLE

this is the most exciting idea i've had in weeks, maybe months! if this works, it changes everything. a bold new future!

**Comment by dankamongmen** [comment]
this also depends on being able to jigsaw together sixels perfectly, but so does any scheme involving partitioning of the graphic.

@dnkl , how would `foot` deal with thousands of cell-sized graphics?

**Comment by dankamongmen** [comment]
if this works without slowing terminals to a crawl, it's definitely The True Way. everything about this (save the added bandwidth) is great. amortized, it might not even be more bandwidth, due to the reduced need to repaint the sprixel (though that's fast on kitty due to references, so no dice there, but most of the overhead is sixel-only).

**Comment by dnkl** [comment]
> how would foot deal with thousands of cell-sized graphics?

Great question... reasonably well would be my guess. But there will be a performance hit, for sure.

* There aren't any limitations to the _number_ of sixels; they are stored in a resizable list
* The list is sorted, allowing many operations that need to iterate the list to break out early. For example, when rendering, we can break out as soon as we hit a sixel that is higher up in the scrollback, and not currently visible. Of course, if all of those thousands of sixels are visible at the same time, we'll always have to iterate the entire list.
* There is a simple form of damage tracking:
   - At least one dirty grid cell will cause **all** sixels on that **row** to be re-rendered
       - But only the areas covering said row(s).
   - Cells are dirtied whenever you print text or sixel data to them.
* Sixels with `P2=1` (i.e. where empty pixels are transparent) will first render the (dirty) cells beneath, and then blit the sixel on top.
* Sixels with `P2=0|2` will render the sixel directly, and skip the cells beneath.
* Rendering in foot is normally multi-threaded (on a per-row basis). However, rows touched by sixels with `P2=1` will be rendered single threaded.

If you do implement this, I'd be very interested in benchmark numbers :)

**Comment by dnkl** [comment]
> * Sixels with P2=1 (i.e. where empty pixels are transparent) will first render the (dirty) cells beneath, and then blit the sixel on top.
> * Sixels with P2=0|2 will render the sixel directly, and skip the cells beneath.

In other words, foot would appreciate it if you only emit `P2=1` sixels when it's actually needed ;)

**Comment by dankamongmen** [comment]
I don't think this will work at all, nor would breaking up graphics into horizontal lines (which would be a nice halfway point). Sixels are six pixels. If a cell isn't a multiple of six pixels, you're going to end up with a gap between your rows (indeed, we saw this behavior very early in pixel graphics development). So yeah, a beautiful idea, one which probably would have failed due to induced performance problems, and one which fundamentally won't work in any case.

Le sigh. Oh well, at least we have an answer on this without having to go code it up.

Now, you *could* do this with the Kitty protocol. But I don't think the small possible performance gain offsets two vastly different methodologies (and it would most likely be a performance hit anyway) -- the big win was the massive elimination of complexity.

Terminal authors contemplating a new graphics protocol: define it in terms of cells, sharing a palette if a palette is needed. Or don't. I'm not a cop.

**Comment by dankamongmen** [comment]
So I might have given up on this too quickly. It works just fine with kitty. It's not cleanly matched to Sixel, but clever use of transparent regions could make it so. Imagine our cells are 20px high. A 40 px high image by 1 column would be:

* cell 0: 4 sixels covering 24 pixels, representing 20 pixels, with the bottom 4 being transparent
* cell 1: 4 sixels covering 24 pixels, representing 20 pixels, with the bottom 4 being transparent

so we would have up to 25% overhead on a 20-pixel cell (more generally, (6 - (height % 6 ? height % 6 : 6)) / height). that's gross, but it could work, especially since we'd only have overhead in Sixel, and it has RLE, and the transparent area is perfect for RLE...

**Comment by dankamongmen** [comment]
One downer here is that we would almost certainly have to update the cursor manually after each one of these was emitted.

More damningly, I took a 600x600 image, and broke it into different sixels. It was very, *very* slow on xterm. Let's not bother pursuing this just to have our hearts broken.
