### ISSUE TITLE
ncplayer doesn't reliably show text / refresh for bitmap graphics

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1432]
There are some issues running `ncplayer -bpixel` in both Kitty and xterm. It is enough to use any image along with `-sstretch` (the default). Small graphics not occupying the screen don't run into this problem. This only affects `ncplayer` without `-k`; when used with `-k`, no text is generated (by design).

Kitty: using a fullscreen bitmap graphic *with nothing on the top line* (i.e. `warmech.bmp` with `-sstretch`), we see "press any key to advance", but not the frame nor the time. again, with `-snone` we see all three. using a fullscreen graphic (i.e. `worldmap.png` with `-sstretch`), we see no text. Switching to other blitters has no visible effect.

xterm: with a fullscreen graphic, we see "press key to advance", but once again no time/frame. switching to another blitter shows the blitter name, but not the frame count/time, suggesting that only new output (i.e. damaging output) is being made visible.

both work pretty much as expected with `-k`, so this is almost certainly related to z-axis stuff and damage detection. this ought then be a good check on #1388.

**Comment by dankamongmen** [comment]
If i start `ncplayer` in kitty without `-bpixel`, and then switch to pixel, we see the frame/time info for a brief second before the image is rendered, destroying it all. so yeah, it sounds like an invalidation problem there.

**Comment by dankamongmen** [comment]
I'm not actually sure we're printing "above" the graphic for this stuff, in which case this would be the expected behavior.

**Comment by dankamongmen** [comment]
hrmmm, all of it is being printed to the standard plane, it would appear.

**Comment by dankamongmen** [comment]
the image itself is likewise being printed to the standard plane. we need to go ahead and make an executive decision about mixing bitmaps and text on a single plane. i'm pretty strongly against the idea, as it just doesn't make sense to me. in any case, *this* printing needs to happen on a distinct plane.

also, regardless of the above, i don't think bitmaps ought ever be allowed to print to the standard plane, since the way we indicate deletion of a bitmap is rendering another to the same plane, or destroying the containing plane. since you can't destroy the standard plane....

**Comment by dankamongmen** [comment]
I'm now blocking bitmap rendering to the standard plane, and have updated the documentation to reflect this. It will be rejected with an error. This of course breaks `ncplayer -bpixel` outside of direct mode, so fixing that up now...

**Comment by joseluis** [comment]
It also makes more sense to me to not allow mixing bitmaps and and text in a single plane. In a way, that would be like trying to mix vector and bitmap layers in the same layer in a graphic editor... but that's not possible. You can group them though, which would be the equivalent of having both planes (a pixel plane and a text plane) in the same pile. I think

**Comment by dankamongmen** [comment]
Yeah, the more i think about it, bitmap + text in the same plane never makes sense (except if they were kept strictly apart, but that sounds like a tremendous pain in the ass for no benefit). i think i'm going to come down on that side. the only worry then is:
* if you blit a bitmap onto a plane that already had text, is that an error?
* we have to throw a check into every single text output function, and will surely miss some

you can't (assuming current infrastructure) just refuse preexisting planes at the `ncvisual_render(NCBLIT_PIXEL` entry point, because otherwise there's no way to scale bitmaps. actually, there *is* `ncvisual_resize()` so maybe we could just lock all of them out (i.e. always create a new plane in this case), which eliminates the first question above. hrmm. maybe that's a good idea.

i didn't know that about graphic editors refusing combination of vector+bitmap, but it makes me feel like yeah this is the right thing to do. i thought most of them were just one-or-the-other (i.e. gimp vs inkscape).

**Comment by joseluis** [comment]
about the first bullet point, what about adding a bool to the plane metadata to indicate if its a pixel plane or a text plane, enforcing that comprobation for text and pixel operations. That's simple enough. We could also have a function to switch the plane from one type or another, ant that's the function that should ever error, if the user hasn't made sure to delete it before, or best of all let the user choose one or the other with a bool parameter...

> we have to throw a check into every single text output function, and will surely miss some

I don't think I'm familiar with what surrounds this

> i didn't know that about graphic editors refusing combination of vector+bitmap, but it makes me feel like yeah this is the right thing to do. i thought most of them were just one-or-the-other (i.e. gimp vs inkscape).

they are specialized, yes. And I don't think gimp or inkscape allows general vector or bitmap layers respectively, but krita does have boh types of layers and more, like filters, and I'm sure it's not the only one. But even gimp has text layers, which are a kind of vector layers, and krita can import bitmaps, which appear in its own layer, so I guess a little bit they do.

**Comment by dankamongmen** [comment]
> about the first bullet point, what about adding a bool to the plane metadata to indicate if its a pixel plane or a text plane,

we do exactly this (overloading the `NULL`ness or non-`NULL`ity of the `sprite` pointer)

> enforcing that comprobation for text and pixel operations. That's simple enough.

simple enough yes, hard to remember also yes. i guarantee you that i will one day add a function that forgets this check, because i am not thinking of bitmap graphics when i'm thinking of, say, text layout. i agree that this is likely what we'll do, it's just also fundamentally inelegant software engineering.

ideally this would be solved with types.

which i oftentimes wonder, ought we not just solve it with types? have the two paths of `ncvisual` diverged in spirit, if not in effect? and if so, ought we not honor that reality? how difficult would that make decay from `NCBLIT_PIXEL`? do we *want* decay from `NCBLIT_PIXEL`? or are these just unavoidable birthing pains from integrating a fundamentally different kind of output into our cell/glyph-based model, and if we do it elegantly enough, they won't be pains for users? i am unsure.

> We could also have a function to switch the plane from one type or another, ant that's the function that should ever error, if the user hasn't made sure to delete it before, or best of all let the user choose one or the other with a bool parameter...

we coulllllld but plane creation is so cheap that i'm not sure i see the point. maybe. we'll see. if they become different types, no way. and i'm thinking `ncvisual_render(NCBLIT_PIXEL` should always require a `NULL` plane in the `ncvisual_options`, so long as `ncvisual_resize()` does what i think.

another thing is that with sprixels, we've got what i've been calling the "transparence-annihilation" matrix, and we'd do well to be able to automatically propagate this from one instance of a bitmap to another. i'm not sure how to best express that in the API. thinking on it some more, though, i'm not sure propagation is so important. so leave that one in the air (basically, we need to know, for each bitmap, where it has transparent pixels, and where it has been printed on top of. for the former, we need update the text when it changes, since it's visible. for the latter, we need to carve transparent chunks out of the images in kitty).

**Comment by dankamongmen** [comment]
things seem to be pretty much working in kitty now

**Comment by dankamongmen** [comment]
i'm getting a weird effect in `xterm` where it works if we *start* on pixel, but moving there from another blitter scrolls, see below:


https://user-images.githubusercontent.com/143473/111955711-3b68a600-8ac0-11eb-9657-fa6aeab04e34.mov

**Comment by joseluis** [comment]
> ideally this would be solved with types.

yes I was thinking if it was in Rust I'd use different types and validate them in compile time, but I'm not sure how to approach that in C. 

> we coulllllld but plane creation is so cheap that i'm not sure i see the point

If it's indeed very cheap then it wont be necessary to be able to change between one type and another...

Regarding the mechanics of the intermixed layers with transparent pixels and cells... Maybe it would be a good idea to start a discussion to clearly state the constraints and narrow down the possible solutions... I currenly don't know whtat's possible and what's not...

**Comment by dankamongmen** [comment]
read #1388 in all its meandering glory, and the bugs linked to it. it's all in there. i'm pretty sure i've explored the design space to its limits. definitely ask about anything that's unclear.

**Comment by dankamongmen** [comment]
ok, so the current situation is:

* kitty: it works when you start on pixel. if you start elsewhere, though, or move off pixel to something else, and you're a fullscreen image, we do not see the legend. when playing a video, you see the legend for the first frame. also, switching among blitters in a video tends to result in an exit, definitely a regression (i think this might be #1470).
* xterm: even if you start on pixel, you don't see the legend. furthermore, if you go somewhere else, then come back to pixel, it scrolls one line off the top. just for fun, switching from pixel to braille fucks up the legend, but switching from pixel to anything else doesn't. sigh.

i think i'm going to fix #1470 first, because exiting all the time during experimentation sucks.

**Comment by dankamongmen** [comment]
with #1470 fixed, we no longer exit when switching blitters mid-video, but tend not to get any output. so that's still a big major regression, probably fallout from the vertical alignment work? i dunno. but everything else above stands.

**Comment by dankamongmen** [comment]
now remember, ncplayer is writing everything (except subtitles) to one plane, which ideally we won't even support, and certainly doesn't work well. so this is not a general failure of the bitmap engine, but my own stupidity. let's lift the legend up onto its own one-line plane, as we ought always have done. that ought fix the loss of legend.

**Comment by dankamongmen** [comment]
wait, that is a falsehood. we print to the standard plane sure enough, but we blit to a different plane, one we stick under the standard plane, which is set to be transparent. kinda gross and counterintuitive imho, though it does jive with not allowing planes to mix. so this *is* presumably a failure of the bitmap engine.

**Comment by dankamongmen** [comment]
so, we're drawing the bitmap twice upon a switch to pixel in kitty. it's bitmap 1 each time. ok, the second draw is for the "press any key to continue". either way, it's not that the bitmap engine is failing, but that we're scrolling. chunli's show is a row above in `-bpixel` where it is in any other blitter.

**Comment by dankamongmen** [comment]
ok, in `ncplayer`, if i make the first plane 5 rows short, that's honored when we start with `-bpixel`. you can see the gap. when you come back through, though, it is *not*, and thus we scroll off. that's what's going on -- it's an `ncplayer` issue after all.

**Comment by dankamongmen** [comment]
yeah, our plane is getting resized:

```c
ncplane_resize_internal:569:70x93 @ 0/0 → 70/93 @ 0/0 (keeping 70x93 from 0/0)               
ncplane_resize_internal:569:65x93 @ 0/0 → 70/93 @ 0/0 (keeping 65x93 from 0/0)  
```

how is that happening?

**Comment by dankamongmen** [comment]
it's happening in the resize callback(!). why is that being called? ohhhhhh because we hadn't rendered prior to that...ahhh! a very deep bug! fascinating, ok, how to handle this? so this means `notcurses_term_get_yx()` and `ncplane_dim_yx()` on the standard plane and all that jazz work before we raster, but once we do, we run a resize callback. alright.

so one, that points at an issue: this would break after a resize , because we're always going to the max. we need something like #1472 to do this properly. in that case, this resize is no problem. hrmm, i'm tempted to just fix it that way, then.

**Comment by dankamongmen** [comment]
> so one, that points at an issue: this would break after a resize , because we're always going to the max. we need something like #1472 to do this properly. in that case, this resize is no problem. hrmm, i'm tempted to just fix it that way, then.

except we won't need this once kitty 0.20.0 comes out, right? so maybe just accept the hit for now (#1472 looks ugly to fix), and move the resize around. except i'm loathe to touch that area of the code (resize is perhaps the trickiest area)...nah, let's do it right.

**Comment by dankamongmen** [comment]
With the resolution of the first half of #1472, all kitty problems seem to have been resolved =]. the legend is always available, we never scroll the pixel player, and we can switch freely between blitters. w00t!

**Comment by dankamongmen** [comment]
kitty also now works perfectly when resized while playing a video in bitmap mode.

**Comment by dankamongmen** [comment]
xterm works perfectly switching between blitters, but obscures the legend, which we knew to be happening. ok! we're in a much better place. to get xterm working, we need preserve surgery, which is #1457 . i think we can call this done!
