### ISSUE TITLE
reconsider use of sixel scrolling

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1433]
We were using sixel scrolling as defined by xterm by default, and @dnkl chimed in to support its use, but having read up on it last night, i'm unconvinced. We never want scrolling in at least rendered mode, from *anything*. This might be suitable and indeed desired for direct mode, but I don't think it's something we want in rendered mode.

**Comment by dankamongmen** [comment]
erp, over in https://github.com/alacritty/alacritty/pull/4763, @ayosec says wrt SixelScrolling "*If disabled, new graphics are inserted at top-left*, and they are limited by the height of the window". we certainly don't want the former. we *do* want the latter, though. argh.

**Comment by dnkl** [comment]
Yup, that's correct. This is why I suggested using mode 8452 - to avoid scrolling when emitting sixels at the bottom row.

**Comment by dankamongmen** [comment]
> Yup, that's correct. This is why I suggested using mode 8452 - to avoid scrolling when emitting sixels at the bottom row.

ahh, i missed that! le mot juste!

**Comment by dankamongmen** [comment]
there's some good discussion of 8452 here https://github.com/mintty/mintty/issues/572

**Comment by dankamongmen** [comment]
does 8452 require 80, or does it stand alone?

```
CSI ? Pm h
          Set Mode, xterm.  xterm has these additional private Set Mode values:
            Ps = 8 0  ⇒  Sixel scrolling.
            Ps = 1 0 7 0  ⇒  use private color registers for each graphic.
            Ps = 8 4 5 2  ⇒  Sixel scrolling leaves cursor to right of graphic.
```

looks like it stands alone. oooh i like the ability to turn on private color registers, too.

**Comment by dankamongmen** [comment]
and it looks like we can just emit this once, not once per sixel.

**Comment by dankamongmen** [comment]
Done! We now use 8452, and only print it the once, when we verify that sixels are supported. Thanks @dnkl !

**Comment by dankamongmen** [comment]
hrmm. even with this setting, `xterm` at least *does* scroll when i hit the bottom-right cell in the terminal =[.

here's leaving out the last column; everything works:
![2021-03-22-031516_938x1417_scrot](https://user-images.githubusercontent.com/143473/111953327-d52e5400-8abc-11eb-8d64-190ac7053c15.png)

here's leaving out the last row; everything works:
![2021-03-22-031541_938x1417_scrot](https://user-images.githubusercontent.com/143473/111953373-e4ad9d00-8abc-11eb-923e-2f634ba7268f.png)

but if i include both, i scroll:
![2021-03-22-031609_944x1440_scrot](https://user-images.githubusercontent.com/143473/111953412-f55e1300-8abc-11eb-9e2e-9d4304f11a52.png)

**Comment by dankamongmen** [comment]
nevermind, that's kitty, i'm stupid. i wonder why kitty scrolls, and whether anything can be done about it...

**Comment by dnkl** [comment]
That's... Annoying. I was hoping it wouldn't be doing that considering its behavior with normal text.

Fwiw, foot will not scroll, even when printing a sixel to the bottom right corner. Not that that helps with xterm...

**Comment by dnkl** [comment]
😂
