### ISSUE TITLE
problems rendering images in direct mode

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1434]
ncdirect_render_image  (and ncdirect_render_frame + ncdirect_raster_frame) are not working well for me either. The images appear all black, even in xterm.

**Comment by dankamongmen** [comment]
Yep, just noticed this myself. Very recent breakage. Looking into it now.

**Comment by dankamongmen** [comment]
yeah, `ncls` is completely smashed as well, as would be expected.

**Comment by dankamongmen** [comment]
Summary as i'm seeing it:

* direct mode image blit with pixel works (where pixels are supported)
* direct mode with cell blitters is broken
* rendered mode works about as expected with either

so this is just a direct mode, cell blitter problem.

**Comment by dankamongmen** [comment]
hrmmm, this might have been broken for longer than i thought :/.

**Comment by dankamongmen** [comment]
a4c8aee8bd24b35027068c5dd65528a34f2b923a at least appears to have correct behavior. bisecting now.

**Comment by dankamongmen** [comment]
bisecting from 103eb7fe01d7535bafd37f371f44a6c67f07d339 now...

**Comment by dankamongmen** [comment]
ahhh yes this seems plausible

```
b282c2055b5947551f64ce3a1510462ab7761520 is the first bad commit
commit b282c2055b5947551f64ce3a1510462ab7761520
Author: nick black <dankamongmen@gmail.com>
Date:   Mon Mar 15 02:45:59 2021 -0400

    [visual] move placey/placex into cell union
```

**Comment by dankamongmen** [comment]
it looks like it's placing the output below the background for some reason?

![2021-03-21-180016_880x1057_scrot](https://user-images.githubusercontent.com/143473/111922281-4e9f5580-8a6f-11eb-8f90-9a9619eb688f.png)

**Comment by dankamongmen** [comment]
ok so it's being blitter too far down into the target plane, almost certainly. which is going to come from `placey`/`placex`. Presumably these were 0 before coming from direct mode, and no longer are?

**Comment by dankamongmen** [comment]
yeahhhhhhhhhhhh. oh shit, this raises a real question: if we decay from `NCBLIT_PIXEL` to something else, we presumably sent a `blitterargs.pixel`...but we'll suddenly be looking for a `blitterargs.cell`. shit. well, that's all internal; we ought be able to patch that up. anyway, our bug here is in `ncdirect_render_frame()`, which is only ever seeing up `blitterargs.pixel`. yeah that's it for sure.

**Comment by dankamongmen** [comment]
yep, pleace is coming in as 21/0, that's exactly it.

**Comment by dankamongmen** [comment]
got it.
