### ISSUE TITLE
notcurses compilation error

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1446]
suddenly I can't compile notcurses anymore...

```
[ 57%] Building CXX object CMakeFiles/notcurses++.dir/src/libcpp/Utilities.cc.o
[ 57%] Built target sgr-full
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_ot_layout_script_select_language'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_blob_create_from_file'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_glib_script_from_script'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_ot_var_named_instance_get_design_coords'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_ot_tags_from_script_and_language'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined reference to `hb_glib_script_to_script'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_ot_var_get_axis_infos'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined reference to `hb_buffer_set_invisible_glyph'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_ot_metrics_get_position'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ncneofetch.dir/build.make:101: ncneofetch] Error 1
make[1]: *** [CMakeFiles/Makefile2:408: CMakeFiles/ncneofetch.dir/all] Error 2
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_ot_layout_script_select_language'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_blob_create_from_file'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_glib_script_from_script'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_ot_var_named_instance_get_design_coords'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_ot_tags_from_script_and_language'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined reference to `hb_glib_script_to_script'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_ot_var_get_axis_infos'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined reference to `hb_buffer_set_invisible_glyph'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_ot_metrics_get_position'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/caps-rendered.dir/build.make:101: caps-rendered] Error 1
make[1]: *** [CMakeFiles/Makefile2:1400: CMakeFiles/caps-rendered.dir/all] Error 2
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_ot_layout_script_select_language'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_blob_create_from_file'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_glib_script_from_script'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_ot_var_named_instance_get_design_coords'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_ot_tags_from_script_and_language'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined reference to `hb_glib_script_to_script'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_ot_var_get_axis_infos'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined reference to `hb_buffer_set_invisible_glyph'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined reference to `hb_ot_metrics_get_position'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/tree.dir/build.make:101: tree] Error 1
make[1]: *** [CMakeFiles/Makefile2:1345: CMakeFiles/tree.dir/all] Error 2
[ 57%] Linking CXX shared library libnotcurses++.so
[ 57%] Built target notcurses++
make: *** [Makefile:141: all] Error 2
```

what has changed?

**Comment by dankamongmen** [comment]
sacre bleu! treachery!

**Comment by dankamongmen** [comment]
pango sounds like an ffmpeg thing. can you compile with `-DUSE_MULTIMEDIA=none`? does `ffmpeg` load?

**Comment by dankamongmen** [comment]
all that `hb_*` shit is surely harfbuzz

**Comment by dankamongmen** [comment]
i'd like to think that this has nothing to do with me

**Comment by joseluis** [comment]
after rebooting I can't start the xserver so there must have been corruption in my system. good news is probably just me. I'm gonna have to reinstall... oh well

**Comment by dankamongmen** [comment]
> after rebooting I can't start the xserver so there must have been corruption in my system. good news is probably just me. I'm gonna have to reinstall... oh well

you respond to a non-starting x server by reinstalling? why, rescuing the x server is one of the great joys of being a linux user! The Feast of What the Fuck is This Doing in my xorg.conf is my favorite time of year.

anyway, i'm closing this under the assumption your machine is filled with javanissen demons.

**Comment by joseluis** [comment]
heh, i tinkered for about an hour before deciding to reinstall since i was getting nowhere... there wasnt even logs being filled when trying to start it, just a blinking cursor...

**Comment by joseluis** [comment]
Ok, reopening, because I reinstalled my system, which now works, but I still have the same error trying to compile notcurses :(

**Comment by joseluis** [comment]
> `-DUSE_MULTIMEDIA=none`

adding this it does indeed compile

**Comment by joseluis** [comment]
but now notcurses-demo core dumps, and the image examples panics too

**Comment by joseluis** [comment]
I guess loading images depends on multimedia...

**Comment by joseluis** [comment]
Ok solved.... more or less.

I removed my /usr/local/ directory. And now it compiles with multimedia. Something in there was confusing the linker. And now the images works... but notcurses-demo keeps core dumping...

**Comment by dankamongmen** [comment]
is your libav the one full of demons

**Comment by joseluis** [comment]
Must be. If there was clear a list of dependencies I should have... I could purge the packages and reinstall the recommended version...

**Comment by dankamongmen** [comment]
any love here? i can come peek around in your machine if you'd like.

**Comment by dankamongmen** [comment]
@joseluis mi hombre, anything i can do to assist here?

**Comment by joseluis** [comment]
hello there, sorry for not responding! I ended up switching the focus of my attention after all those problems arised. I'll give it another go soon, I hope. BTW what distro do you recommend? Maybe it's time to change.

**Comment by dankamongmen** [comment]
> hello there, sorry for not responding! I ended up switching the focus of my attention after all those problems arised. I'll give it another go soon, I hope. BTW what distro do you recommend? Maybe it's time to change.

ahhh that is what i feared =[. understood! i run debian unstable on my workstation and arch on my laptop. if this is a valid breakage on a non-demon-infested machine, i would like to resolve it though. is this a fresh install, pretty much? of what? i can try to reproduce it here.

**Comment by joseluis** [comment]
> what TERM value do you have for kitty? it recommends xterm-kitty

aaaah, that fixes it. I don't know why I thought notcurses would automatically detect the kitty terminal independently of my TERM env var.

>  i'm still of two minds regarding sprixels going to a different type than ncplane. it's a really difficult decision. i'll try to come to a conclusion soon. would love to hear your feedback to e.g. #1388.

Ok, I'll open a discussion so we can chat a bit about all this without the pressure of being on an [unrelated|closed] issue.

**Comment by dankamongmen** [comment]
> > what TERM value do you have for kitty? it recommends xterm-kitty
> 
> aaaah, that fixes it. I don't know why I thought notcurses would automatically detect the kitty terminal independently of my TERM env var.

it should, via interrogation. it just doesn't yet.
