### ISSUE TITLE
support kitty fixed-cursor graphic directive

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1447]
See https://github.com/kovidgoyal/kitty/issues/3411. It looks like kitty will be adding a directive to its graphics protocol, which will keep the cursor unmoved. This ought allow us to blit into the lowerrightmost cell without scrolling the image away. Hopefully there will be some backwards-compatible way to detect this, or at least emitting it won't kill older kitty versions.

**Comment by kovidgoyal** [comment]
You want to detect it simply detect the kitty version, as described here: https://sw.kovidgoyal.net/kitty/kittens/query_terminal.html

As for using it on older kitties, kitty ignores graphics commands that contain keys it does not know about. Which meansthe image wont be displayed. So you can also detect it by sending C=some large number. and then querying the cursor position. If the cursor has moved, you are ona  kitty that understands the C key. If it has not, you are on old kitty.

**Comment by dankamongmen** [comment]
Ahhh, we've already solved this in #1733. We can show full-screen graphics in kitty now in both rendered and direct mode just fine, huzzah.
