### ISSUE TITLE
add a resize callback which puts the plane back within its parent plane

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1478]
I'm imaging that this would be used in e.g. the demo's HUD. We don't want necessarily to realign the HUD on a parent window resize, but we *do* want to ensure it's back on screen. This new resize callback, `ncplan_resize_placewithin()` or somehing, will:

~~* [ ] shrink the subject plane, if necessary, to fit within its parent plane, keeping the upper left~~
* [ ] bring the subject plane to the closest origin within the parent plane such that it is entirely contained

**Comment by MasFlam** [comment]
What combination of the two though? If the plane is resized to fit, then we don't need to move it. Unless what you meant was moving the subject plane to fit within the parent plane only if it is possible without resizing, and if that's not possible only then shrink the subject plane without moving it. But then there's the question of what happens if the subject plane is entirely off the parent and too big at the same time.

**Comment by dankamongmen** [comment]
> What combination of the two though? If the plane is resized to fit, then we don't need to move it. Unless what you meant was moving the subject plane to fit within the parent plane only if it is possible without resizing, and if that's not possible only then shrink the subject plane without moving it. But then there's the question of what happens if the subject plane is entirely off the parent and too big at the same time.

so one, it's important to remember you can always write your own ad hoc resize callback to do whatever behavior you want. i'm just trying to anticipate common cases. and indeed, maybe this isn't common enough to justify its own function and attendant API/concept bloat.

i was thinking this function would be used for child planes which are always intended to be completely contained within their parents. the motivating example is `notcurses-demo`'s HUD (the little window that shows timings and frame counts for the past 3 demos). i recently assigned the FPS graph `ncplane_resize_realign()` to put it back on the bottom of its parent. before that, if we had a vertically maximized terminal to start, and then it shrunk vertically (from either the top or bottom), the FPS graph was left offscreen. if you then enlarged the window, you could find it.

that's been fixed, but the HUD has not. shrink the window, and it's offscreen and invisible. i want to drag it back into the parent at the point closest to where it now is. there's a chance that the parent plane can no longer fit the child, so we shrink it if necessary.

so i'm envisioning:
* if the child is larger than the resized parent in either dimentions, it is cropped to fit
* it is then brought into the parent plane at the closest point. to state this precisely, we place the child plane such that (a) it's entirely within the parent (guaranteed by above) and (b) the new (child) origin minimizes the distance from the current (child) origin 

again, if this isn't a generally useful pattern, i'll just one-off it for the demo HUD and be done with it. i don't want to clutter the API with ten thousand resize callbacks.

**Comment by dankamongmen** [comment]
one thing i don't like here is that we shrink, but we can't grow back. that makes it unsuitable for the HUD. let's drop the shrinking aspect, and just move the plane if necessary.

**Comment by dankamongmen** [comment]
seems to work well enough.
