### ISSUE TITLE
Linker error in v2.2.5

### ISSUE THREAD

**Issue by dontlaugh** [dankamongmen/notcurses#1505]
Full disclosure: I'm new to C and CMake. But I was playing around this afternoon and something that used to link doesn't anymore with v2.2.5

```
/usr/bin/ld: notcurses/libnotcurses-core.so.2.2.5: undefined reference to `update_sample_uint64_t'
/usr/bin/ld: notcurses/libnotcurses-core.so.2.2.5: undefined reference to `update_sample_double'
```

I'm assuming these are templated out here: https://github.com/dankamongmen/notcurses/blob/master/src/lib/plot.c

Here's my project, if you suspect I'm doing something else wrong in CMake. I'd like to include notcurses as a submodule rather than install from the AUR, if possible. https://git.de.limited/coleman/tui-practice

----

The other info:
```
env | egrep 'LANG|LC_CTYPE|TERM'
LANGUAGE=en_US:en
LANG=en_US.UTF-8
TERM=xterm-kitty
COLORTERM=truecolor
TERMINFO=/usr/lib/kitty/terminfo
```
Notcurses v2.2.5
And my terminal is Kitty 0.19.3

**Comment by MasFlam** [comment]
Yeah the function has only an `inline void` definition so that's surely causing the linker errors.

@dankamongmen I'm just gonna again mention [a way](https://github.com/MasFlam/notcurses/blob/linegraphs/src/lib/linegraph.c) for improving plot.c, sorry for bothering you so much about it :P

**Comment by dankamongmen** [comment]
my fault! i'll clean this up and look at your suggestion @MasFlam . i should have this fixed today, sorry @dontlaugh .

**Comment by dankamongmen** [comment]
Sorry, I've been wrapped up in my dayjob more than usual of late. So `update_sample_uint64_t` is internal to notcurses; it ought never have been exported. Were you calling it directly? I don't see any such call in the sample code to which you linked, but perhaps I'm missing something.

Almost all notcurses functions begin with `notcurses` or `ncplane` or whatnot; exported plot functions all begin with `ncplot`. `update_sample_T` were never intended to be exported to the user, and aren't present in the installed headers.

If you were using them directly, you want `nc[DU]plot_add_sample()` or `nc[DU]plot_set_sample()`. Those will link just fine.

Are you saying that notcurses itself was failing to link?

**Comment by dankamongmen** [comment]
If you were directly `#includ`ing `plot.h` to get `update_plot()`, that was never intended to work, and would break if notcurses was updated and you didn't rebuild. To be safe, only include functions from `notcurses.h` and/or `direct.h` -- put another way, only files from `include/notcurses` in the source tree, never files from `src/lib`. But perhaps I'm misunderstanding you?

**Comment by dontlaugh** [comment]
It could very well be something wrong with my build. I'm a CMake newbie, and I'm attempting to keep the notcurses dependency local, in a submodule. So I'm making things harder on myself. Don't sweat it too hard. :+1:

**Comment by dankamongmen** [comment]
So I think you're directly including notcurses into your source tree. That can be made to work, but typically you install it via your system's package manager, or build it independently and do a "make install". When that happens, the intended headers are put into e.g. `/usr/include` and the library is put in e.g. `/usr/lib`. The headers in `src/lib` are not going to  be copied in, because they're not meant to be installed, because they're not meant for the end user.

So long as you ponly ever include `notcurses.h` and/or `direct.h`, you ought be fine. The interfaces there are stable.

**Comment by dankamongmen** [comment]
Don't hesitate to ask if you have more questions, though! Your current code can probably be made to work if you just change any `update_sample_foo` to `ncdplot_set_sample()` or `ncuplot_set_sample()`.

**Comment by dankamongmen** [comment]
feel free to reopen this if it looks like what i'm describing isn't your problem
