### ISSUE TITLE
pixels per cell & pixel rendering bug in alacritty

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1507]
I was making some tests to determine the number of pixels per cell, and I found it's varies with font size... e.g. in Alacritty with a 12p font it's 10x19 and with a 18p font is 14x28...

Right now I have to find it manually. I print a visual delimiter around a cell over which I will render an ncvisual made of random color pixels.

This is the result on each terminal (at 4x):

**In Kitty:**
![kitty-9x18_4x](https://user-images.githubusercontent.com/5832068/113611086-5275cf00-964e-11eb-982d-3dbc3793c062.png)

**In Alacritty:** (the ncvisual seems to delete every cell until the end of the line)
![alacritty-10x19_4x](https://user-images.githubusercontent.com/5832068/113617301-79d09a00-9656-11eb-8a28-7f5d10714d58.png)
![alacritty-14x28_2x](https://user-images.githubusercontent.com/5832068/113617671-ec417a00-9656-11eb-9d2e-b567811b6744.png)

**In Xterm:**:
![xterm-6x13_4x](https://user-images.githubusercontent.com/5832068/113612188-c6fd3d80-964f-11eb-9e1b-50e73f2df2b9.png)

**Comment by kovidgoyal** [comment]
You dont need to find pixels per cell manually. Use TIOCGWINSZ https://sw.kovidgoyal.net/kitty/graphics-protocol.html#getting-the-window-size  xterm and kitty both will give you the window size and cell count allowing you to calculate the number of pixels per cell. I think alacritty added support for it too a little while back.

**Comment by joseluis** [comment]
Thank you very much @kovidgoyal, it works in Alacritty too.

This would be the Rust version:
```rust
let mut ws: libc::winsize = unsafe { std::mem::zeroed() };
unsafe { libc::ioctl(0, libc::TIOCGWINSZ, &mut ws) };
let cell_y = ws.ws_ypixel / ws.ws_row;
let cell_x = ws.ws_xpixel / ws.ws_col;
println!(
    "rows,cols={},{}; term y,x={},{}; cell y,x={},{}",
    ws.ws_row, ws.ws_col, ws.ws_ypixel, ws.ws_xpixel, cell_y, cell_x
);
```

**Comment by dankamongmen** [comment]
@joseluis we already have this information (via `TIOCGWINSZ`) in the `tinfo` structure:

```c
  // we use the cell's size in pixels for pixel blitting. this information can
  // be acquired on all terminals with pixel support.
  int cellpixy;   // cell pixel height, might be 0
  int cellpixx;   // cell pixel width, might be 0
```

we refresh this whenever we rasterize. i could export this to the user, but `ncvisual_geom()` is designed to do the kind of thing i suspect you're trying to do.

by the way, know that current XTerm has a bug where it doesn't update these values when the font or font size changes. I reported it just last week. it does properly update them on a cell geometry change.

**Comment by joseluis** [comment]
> we already have this information (via `TIOCGWINSZ`) in the `tinfo` structure:

@dankamongmen but AFAICT that's an internal structure not available in the API therefore I have no means of reading that from Rust. Could it be made available?

**Comment by dankamongmen** [comment]
> > we already have this information (via `TIOCGWINSZ`) in the `tinfo` structure:
> 
> @dankamongmen but AFAICT that's an internal structure not available in the API therefore I have no means of reading that from Rust. Could it be made available?

yeah, sure. like i said i was thinking `ncvisual_geom()` would be sufficient, but i can see plenty of use cases where you would want to know these explicitly. let me think of the most useful form...

**Comment by dankamongmen** [comment]
> yeah, sure. like i said i was thinking `ncvisual_geom()` would be sufficient, but i can see plenty of use cases where you would want to know these explicitly. let me think of the most useful form...

the kinda crappy thing here is that plenty of terminal emulators don't fill these fields in

**Comment by dankamongmen** [comment]
ugh, also this function would only ever work after calling `notcurses_check_pixel_support()`. bleh. maybe i ought just do that on demand after all...

**Comment by dankamongmen** [comment]
```c
// Retrieve pixel geometry for the display region ('pxy', 'pxx'), each cell                  
// ('celldimy', 'celldimx'), and the maximum displayable bitmap ('maxbmapy',                 
// 'maxbmapx'). Note that this will call notcurses_check_pixel_support(),                    
// possibly leading to an interrogation of the terminal. If bitmaps are not                  
// supported, 'maxbmapy' and 'maxbmapx' will be 0. Any of the geometry                       
// arguments may be NULL.                                                                    
API void ncplane_pixelgeom(struct ncplane* n, int* RESTRICT pxy, int* RESTRICT pxx,          
                           int* RESTRICT celldimy, int* RESTRICT celldimx,                   
                           int* RESTRICT maxbmapy, int* RESTRICT maxbmapx)                   
  __attribute__ ((nonnull (1)));   
```

**Comment by dankamongmen** [comment]
OK, I've added `ncplane_pixelgeom()`. Currently, it won't work if `TIOCGWINSZ` doesn't have support for pixels, which is true on some terminals. It might transitively call `notcurses_check_pixel_support()`, meaning it might lead to a terminal interrogation. I think it provides all information you might possibly want.
