### ISSUE TITLE
knowing the length of an ncplane_rgba() created array

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1508]
In order to implement the binding for [ncplane_rgba()](https://dankamongmen.github.io/notcurses/rustdoc/libnotcurses_sys/fn.ncplane_rgba.html) I need to convert the returned raw mutable pointer into a rust slice with [slice::from_raw_parts_mut()](https://doc.rust-lang.org/core/slice/fn.from_raw_parts_mut.html). The problem is you need to know the lenght of the array for that.

It would be awesome if the ncplane_rgba outputted the array lenght as well. Maybe changing the return type to the length and having an additional parameter to put there the pointer for the array.

If that's not possible, I'll calculate that value paralelly in the function, even when len_y and/or len_x are not specified in the arguments checking the plane dimensions and such.

What do you think?

**Comment by joseluis** [comment]
I've ended up calculating it manually, it was easy. Although it's untested... it should work.

**Comment by dankamongmen** [comment]
you know the length of an `ncplane_rgba()` row just by looking at the plane geometry, do you not?

**Comment by joseluis** [comment]
yes, I can get it with `ncplane_dim_y/x - begy/x` if it's not provided in `leny/x`

**Comment by dankamongmen** [comment]
cool, so it's O(1) for you -- you said "calculate it in parallel", and i thought you meant "spin up a thread and do some concurrency", and that worried me =]. so i think this can be closed?

oh actually you need to know blitter scaling to do this right, don't you? ok i can see how this calculation might be error-prone. agreed that it would be useful to return it. hrmmm. 

i started thinking "this should just return an `ncvisual`." which is exactly what `ncvisual_from_plane()` does. i'm wondering why i export this function at all.... it's difficult to use correctly.

**Comment by dankamongmen** [comment]
ehhh i guess because maybe they want to take up a raw pixel buffer and then do external image processing on it. yeah, best to keep that functionality public.

so the real equation would be, afaict:

pixel count = `leny` * `lenx` * `blitterscaley` * `blitterscalex`
row size: `lenx` * `blitterscalex`
column size: `leny` * `blitterscaley`

i don't see how the plane's dimensions are involved. you're asking for `leny` x `lenx` cells, and each cell yields between 1 and 8 pixels depending on `blit`. `NCBLIT_BRAILLE` yields 2 columns of pixels per column of cells, and 4 rows of pixels per row of cells. a 1x1 `leny`x`lenx` with `NCBLIT_BRAILLE` yields 8 pixels in 4 rows of 2. an 80x24 `lenx`x`leny` with `NCBLIT_BRAILLE` is 80 * 2 * 24 * 4 == 15360 pixels in 96 rows of 160 pixels. the same with `NCBLIT_1x1` yield 1 pixel in the former case, and 1920 pixels in 24 rows of 80 in the latter.

**Comment by dankamongmen** [comment]
I've deprecated `ncplane_rgba()` in favor of `ncplane_as_rgba()`, which the former now wraps.

**Comment by joseluis** [comment]
> i thought you meant "spin up a thread and do some concurrency", 

lol, I meant in paralell to the calculations notcurses must be already doing internally =)

> i don't see how the plane's dimensions are involved. you're asking for leny x lenx cells

Well, as the ncplane_rgba says: `Either or both of 'leny' and 'lenx' can be specified as -1 to go through the boundary of the plane.` I don't have them, so I think I have to calculate them from the plane boundaries...

> each cell yields between 1 and 8 pixels depending on blit

I'm realizing maybe I don't understand what this function does then. I thought it would output rgba pixels in NCBLIT_PIXEL format, using tinfo's pixels per cell... What's stored in the array if it depends on different BLIT modes? Maybe the function needs a little bit more of explanation?

**Comment by dankamongmen** [comment]
`ncplane_rgba()` tries to make a pixel bitmap out of the contents of the plane. with `NCBLIT_1x1`, you can make a pixel from each space/full block. with `NCBLIT_2x1`, you can make two pixels from each space/fullblock/halfblock. etc...

**Comment by joseluis** [comment]
> I've deprecated `ncplane_rgba()` in favor of `ncplane_as_rgba()`, which the former now wraps.

Ok I'll try it when it's available

**Comment by dankamongmen** [comment]
the main purpose of this function is "you blitted an ncvisual, and destroyed the ncvisual, and now need to get it back". well, that's what `ncvisual_from_plane()` is intended to do. this lets you get the raw pixels to do some other processing.

**Comment by dankamongmen** [comment]
Yeah. I honestly don't see it getting used very much.

**Comment by joseluis** [comment]
I think it's usefule for doing screenshots of rendered things.

I'm eager to try your new ncplane_as_rgba when you push it. Will it give array size info?

**Comment by dankamongmen** [comment]
> I'm eager to try your new ncplane_as_rgba when you push it. Will it give array size info?

it returns pixel geometry of the allocated bitmap, which i think is what you're asking for.

**Comment by joseluis** [comment]
BTW is there any way to have something similar but not just for a single plane, but for the whole notcurses render?

**Comment by dankamongmen** [comment]
> BTW is there any way to have something similar but not just for a single plane, but for the whole notcurses render?

it could be added, especially for e.g. `notcurses_render_to_buffer()` or whatever that's called.

it could also be added to e.g. `ncpile_rasterize()`, or `ncpile_render()` probably makes more sense, actually.

**Comment by dankamongmen** [comment]
05082fc above adds `ncplane_as_rgba()`.

**Comment by joseluis** [comment]
Ok, perfect. That solves it.

The problem I've encountered is that the function fails when I put some text in the plane :S

The [`issue-rgba`](https://github.com/dankamongmen/notcurses/blob/master/rust/examples/issue-rgba.rs) example illustrates it....

**Comment by dankamongmen** [comment]
> Ok, perfect. That solves it.
> 
> The problem I've encountered is that the function fails when I put some text in the plane :S
> 
> The [`issue-rgba`](https://github.com/dankamongmen/notcurses/blob/master/rust/examples/issue-rgba.rs) example illustrates it....

yep. `Only glyphs from the specified blitset may be present.`

**Comment by joseluis** [comment]
Aaaaaahhhm, ok this is solved then
