### ISSUE TITLE
xray in xterm leaves cruft on each frame

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1537]
Running `xray` in sixel environments like `xterm` leaves a small amount of cruft from each frame, building up to a screenful of cruft at demo's end. This is almost certainly due to oscillation between `OPAQUE`, `MIXED`, and `TRANSPARENT` among non-annihilated cells on frame change, identified in the sprixel state machine analysis I performed tonight.

**Comment by dnkl** [comment]
FWIW, this doesn't happen in foot. Are you seeing it in any other terminal than XTerm?

I always thought this (the xray issue) was due to XTerm's way of drawing transparent sixels; writing a sixel on top of a sixel in XTerm doesn't actually erase; old image(s) will still be visible through the transparent areas of the new sixel.

In other words, to erase a sixel in XTerm, you need to either overwrite it with text, or erase it with text erase escapes.

**Comment by dankamongmen** [comment]
> In other words, to erase a sixel in XTerm, you need to either overwrite it with text, or erase it with text erase escapes.

heh yes i just wrote up a (semi-)lengthy bit on this. https://github.com/dankamongmen/notcurses/blob/30cb74428fefdb7ab7e3cd2f2a1d4bd91c853eab/src/lib/internal.h#L55

```c
// elements of the T-A matrix describe transparency and annihilation at a
// per-cell basis, making up something of a state machine. when a sprixel
// plane is first created, the TAM is (meaninglessly) initialized to all
// zeroes (SPRIXCELL_OPAQUE). during the construction of the sprixel from
// an RGBA frame, OPAQUE entries are possibly marked MIXED or TRANSPARENT.
// subsequent sprixels blitted to the same plane will reuse the TAM, and
// retain any SPRIXCELL_ANNIHILATED entries, cutting them out of the
// sprixel.
//
// sixel can transition to ANNIHILATED via a no-op; kitty can transition
// to ANNIHILATED only by wiping the cell (removing it from the sprixel via
// all-0 alphas), deleting the bitmap, and displaying it once more. sixel
// bitmaps are removed by obliterating them with new output, while kitty
// bitmaps are removed by a fixed-length terminal escape. an important
// implication is that sixels cannot be progressively reduced by emitting
// progressively more transparent sixels atop one another--to remove a
// cell from a Sixel sprixel, it is necessary to print a glyph. the same
// goes for Kitty sprixels, but there we delete and rerender bitmaps
// in toto without glyph involvement....
```

**Comment by dankamongmen** [comment]
> FWIW, this doesn't happen in foot. Are you seeing it in any other terminal than XTerm?
> I always thought this (the xray issue) was due to XTerm's way of drawing transparent sixels; writing a sixel on top of a sixel in XTerm doesn't actually erase; old image(s) will still be visible through the transparent areas of the new sixel.

xterm is indeed the only place where i see it, for the reason you describe. this will be handled generically for sixel by appropriately oscillating between `OPAQUE`, `MIXED`, and `TRANSPARENT` on RGBA sprixelation time. from the link above:

```c
// rendering a new RGBA frame into the same sprixel plane can result in changes
// between OPAQUE, MIXED, and TRANSPARENT. an OPAQUE sprixcell which becomes
// TRANSPARENT or MIXED upon rendering a new RGBA frame must damage its cell,
// since the glyph underneath might have changed without being emitted. the
// new glyph must be emitted prior to redisplay of the sprixel.
```

**Comment by dankamongmen** [comment]
we see the same thing in `kitty` if we do, say, `./ncplayer -bpixel ../data/notcursesIII.mkv -k -sscale -a`.

**Comment by dankamongmen** [comment]
> we see the same thing in `kitty` if we do, say, `./ncplayer -bpixel ../data/notcursesIII.mkv -k -sscale -a`.

we're just not calling `sprite_delete()` here, this ought be easy enough to fix up.

**Comment by dankamongmen** [comment]
> > we see the same thing in `kitty` if we do, say, `./ncplayer -bpixel ../data/notcursesIII.mkv -k -sscale -a`.
> 
> we're just not calling `sprite_delete()` here, this ought be easy enough to fix up.

not as easy as hoped -- we normally hit `sprite_delete()` via the render path, and it's awash with `notcurses` referenes. we'd need extract the kitty directive, make that its own function, and call it from `sprite_delete()`. then we'd call this new function from `ncdirect_stream()`.

**Comment by dankamongmen** [comment]
ok, the `kitty -k` case is resolved. `xterm xray` is outstanding.

**Comment by dankamongmen** [comment]
so solving this is going to be messy, and introduce so much overhead that we probably want to special-case it for XTerm. essentially, to do it properly, we'd have to reprint every cell that's underneath a `SPRIXCELL_MIXED` or `SPRIXCELL_OPAQUE` (i.e. underneath any drawn pixels) sprixcell if it shifts to `SPRIXCELL_TRANSPARENT` or `SPRIXCELL_MIXED` (i.e. any undrawn pixels). that's going to introduce hella flicker anywhere that's transitioning to `SPRIXCELL_MIXED`. we won't suffer the flicker if we only handle transitions to `SPRIXCELL_TRANSPARENT`, but it'll still be a lot of overhead output.

i'm inclined to let this slide to 3.0 at least. `wezterm` doesn't show this problem, nor does `alacritty`, nor does `foot`. not even `mlterm`, off in its own world, exhibits this behavior. and fixing it will be *expensive*.

**Comment by dankamongmen** [comment]
see if #1619 might be a solution to this (big P2=0 blasts). it would probably just lead to flicker =[.

**Comment by dankamongmen** [comment]
> so solving this is going to be messy, and introduce so much overhead that we probably want to special-case it for XTerm. essentially, to do it properly, we'd have to reprint every cell that's underneath a `SPRIXCELL_MIXED` or `SPRIXCELL_OPAQUE` (i.e. underneath any drawn pixels) sprixcell if it shifts to `SPRIXCELL_TRANSPARENT` or `SPRIXCELL_MIXED` (i.e. any undrawn pixels). that's going to introduce hella flicker anywhere that's transitioning to `SPRIXCELL_MIXED`. we won't suffer the flicker if we only handle transitions to `SPRIXCELL_TRANSPARENT`, but it'll still be a lot of overhead output.

yep, this is what we have to do. let's go ahead and do it and see how badly performance suffers. it only needs be done with sixel.

**Comment by dankamongmen** [comment]
if i recall correctly, we're now seeing this under foot's new regime according to @dnkl.

**Comment by dnkl** [comment]
> if i recall correctly, we're now seeing this under foot's new regime

You are correct :)

**Comment by dankamongmen** [comment]
i've made an initial change which rectifies the multiplicity of our orca in alacritty, and scrubs up behind `xray` *in a sufficiently small terminal*. 

before:

![2021-06-30-231008_800x801_scrot](https://user-images.githubusercontent.com/143473/124058953-52406200-d9f8-11eb-8614-996d1cb9a898.png)

after:

![2021-06-30-230854_800x801_scrot](https://user-images.githubusercontent.com/143473/124058848-27560e00-d9f8-11eb-95ef-a3a4d6e530ba.png)

**Comment by dankamongmen** [comment]
alright, i have a PR now that makes everything perfect, so far as i can tell. tested in alacritty, foot, and xterm, with and without margins.

**Comment by dankamongmen** [comment]
@dnkl , `xray` ought be working cruftlessly in `foot` once more =].

**Comment by dnkl** [comment]
Tested, and looks good!
