### ISSUE TITLE
Scaled visuals are smaller than they should be

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1558]
coming from: https://github.com/dankamongmen/notcurses/issues/1546#issuecomment-821980361

I found a difference in size between an scaled visual and an inflated one, on the pixel-cell rust example.
![image](https://user-images.githubusercontent.com/5832068/115147248-6cee7600-a05a-11eb-9079-4faed65d5118.png)

Scaling a 18x9 px visual by 4 renders a 69x35 px image:
![image](https://user-images.githubusercontent.com/5832068/115147162-fbaec300-a059-11eb-8fb7-363fbc99e1ba.png)

But it should be 18 * 4 and 9 * 4 = 72x36 px. 

On the other side inflated visual does indeed have the right size:

![image](https://user-images.githubusercontent.com/5832068/115147116-b5f1fa80-a059-11eb-8c67-1adbc131b15f.png)

Here they are on top of each other (augmented 16 times):

![image](https://user-images.githubusercontent.com/5832068/115147071-8c38d380-a059-11eb-9f50-3bbc1c45bc05.png)

**Comment by dankamongmen** [comment]
```
Scaling a 18x9 px visual by 4 renders a 69x35 px image:
```

what does this mean? the only place where this would make sense, AFAIK, would be `ncvisual_inflate()`.

**Comment by joseluis** [comment]
It means that in the pixel-cell example I:
- create a pixel buffer with 18x9 pixels which occupy exactly 1 cell.
- create a plane 4 cells wide and 4 cells high.
- render the ncvisual in that plane, with NCSCALE_SCALE,
- and the rendered image, as screenshoted and measured comes short in size by a few pixels.

**Comment by dankamongmen** [comment]
ahhh. you want `NCSCALE_STRETCH`. i think that'll accomplish what you want.

**Comment by joseluis** [comment]
using NCSCALE_STRETCH gives an image of 71x35:
![image](https://user-images.githubusercontent.com/5832068/115147984-df148a00-a05d-11eb-94ba-4107d2f59f4e.png)

**Comment by dankamongmen** [comment]
hrmm but it seems `NCSCALE_SCALE` ought work as well. i see where you're coming from.

so 4*9==36 which is just fine for sixel...

hrmmm, yes, this seems to be a bug. and `_STRETCH` is shorting you 1 pixel in each direction, huh? ¡Qué lástima! El lobo es una cosa incognoscible, he said. Lo que se tiene en la trampa no es mas que dientes y forro. El lobo propio no se puede conocer. Lobo o to que sabe el lobo. Tan como preguntar to que saben las piedras. Los arboles. El mundo.

**Comment by joseluis** [comment]
Yes, I believe we are on the same page now :D

**Comment by dankamongmen** [comment]
Cuidado, hay una trampa de lobos enterrado en el sprixel!

**Comment by dankamongmen** [comment]
:D :D :D

**Comment by dankamongmen** [comment]
sorry, i'm on tape 3 of Cormac McCarthy Teaches Español and its all lobos and fuego

**Comment by joseluis** [comment]
I was wondering what was all that about :upside_down_face: Cuidado con las trampas de lobos.

**Comment by dankamongmen** [comment]
¿Y por eso soy hereje, por eso y nada más? very little buenos tardes amigo in mr. mccarthy's language tapes

**Comment by dankamongmen** [comment]
yeah, i'm seeing this in a unit test

![2021-04-18-102406_376x373_scrot](https://user-images.githubusercontent.com/143473/115149043-37349780-a030-11eb-91b3-8098835c315e.png)

treachery!

**Comment by dankamongmen** [comment]
61 rows (23px) 80 cols (11px)
pblit: 23x11 <- 0x0 of 23/11 stride 44 @0x0 0x55d350edb7f0 11
pblit: 89x43 <- 0x0 of 23/11 stride 44 @0x0 0x559f1055b7f0 11 <----- `NCSCALE_SCALE`
pblit: 92x44 <- 0x0 of 92/44 stride 176 @0x0 0x559f10565000 11

**Comment by dankamongmen** [comment]
ok, i think i've got this resolved. good catch!

**Comment by joseluis** [comment]
yes. now it scales perfectly :)

**Comment by dankamongmen** [comment]
https://www.youtube.com/watch?v=QfPeHqdZZOw w00t w00tt yeah this has smoothed several rough edges in `notcurses-demo` i'd convinced myself weren't really there, huzzah, good work
