### ISSUE TITLE
probably ought rename channel_* -> ncchannel_*, ugh

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1570]
If we're truly prefixing everything with `nc`, we need change over `channel_*` functions to `ncchannel_*`, which sounds like a tremendous pain in the ass, but yeah, probably ought be done. Queue this for 3.0.

**Comment by joseluis** [comment]
and don't forget about the palette too :stuck_out_tongue:

**Comment by dankamongmen** [comment]
> and don't forget about the palette too

it is known!

**Comment by joseluis** [comment]
god save the namespace!

**Comment by dankamongmen** [comment]
All the `channel_*` functions are converted to `ncchannel_`. Need to get `channels_*` next, and this will be done. Probably gonna do it for 2.3.0.

**Comment by dankamongmen** [comment]
Alright, we've got 'em all, I think. =]
