### ISSUE TITLE
do better programmatic terminal detection

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1581]
If we can identify the terminal precisely using interrogation, that's the way we ought do it, possibly overriding even a `TERM` variable. I like @dnkl 's idea from "Programmatically checking if running in foot"

> Foot does not set any environment variables that can be used to identify foot (reading TERM is not reliable since the user may have chosen to use a different terminfo). You can instead use the escape sequences to read the Secondary and Tertiary Device Attributes (secondary/tertiary DA, for short). The tertiary DA response is always \EP!|464f4f54\E\\, where 464f4f54 if FOOT in hex. The secondary DA response is \E[>1;XXYYZZ;0c, where XXYYZZ is foot's major, minor and patch version numbers, in decimal, using two digits for each number. For example, foot-1.4.2 would respond with \E[>1;010402;0c. Note: not all terminal emulators implement tertiary DA. Most implement secondary DA, but not all. All should however implement Primary DA. Thus, a safe way to query the terminal is to request the tertiary, secondary and primary DA all at once, in that order. All terminals should ignore escape sequences they do not recognize. You will have to parse the response (which in foot will consist of all three DA responses, all at once) to determine which requests the terminal emulator actually responded to.

**Comment by klamonte** [comment]
You may find this thread interesting: https://github.com/mintty/mintty/issues/881

**Comment by klamonte** [comment]
How do I force the notcurses-demo to assume sixel support?  I'm testing it against my terminal widget (BTW thank you for exposing yet more bugs on my part :-) ), and I do expose sixel support in DA1 (4) the demo isn't picking that up.

**Comment by dankamongmen** [comment]
> EDIT: I think I figured it out. notcurses is being run inside a slave pty without ws_xpixel/ypixel reporting, so notcurses disables pixel output. Forcing it to support bitmaps gets me lovely sixel output. I threw a comment over in #1368 .

yep, without cell-pixel geometry i don't attempt to use bitmaps. i'm pondering throwing in a fallback where i get the window/framebuffer pixel geometry, and divide out the cell geometry, yielding a cell-pixel geometry. besides the obvious annoying polyfurcation across various backends, window decorations seem like an issue here. i'm not above saying "get a working terminal emulator", and ideally fixing up the linux kernel framebuffer's implementation (or maybe it works? i forget), but if a situation like this breaks things, that's no good. thanks for the heads-up @klamonte !

**Comment by dankamongmen** [comment]
> You may find this thread interesting: [mintty/mintty#881](https://github.com/mintty/mintty/issues/881)

hot shit! thank you!

**Comment by dankamongmen** [comment]
I think that between #1798 and #1761, this is done.
