### ISSUE TITLE
Thread out the xray demo

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1607]
See #1602. I think we could get a good bit of performance (at least in Sixel, probably less so in Kitty) by using two piles and threading things up. One thread rasterizes and writes, while the other decodes the next frame and gets it ready to go. We still want to do the work in that bug, but hopefully this might get things better in the 2.3.0 timeframe.

**Comment by dankamongmen** [comment]
This seemed very simple at first, but I realize now that something complicates it -- the TAM is a per-`ncplane` thing, but when we're using the same media in two threads like this, we need it to be "shared" (maybe not a single copy, but definitely orchestrated) among planes in multiple piles. How best to do that? I absolutely don't want to do a truly shared mechanism, that's just asking for trouble (and serialization). Also, the TAM isn't available until rendering is done (but before rasterization). It technically doesn't matter too much for `xray`, but I imagine this will be one of the more popular multipile scenarios, so it would be good to give it some serious thought.

**Comment by dankamongmen** [comment]
I'm thinking this is less a big deal than it first seemed. You can touch a pile while *rasterizing*, just not while *rendering*. Just swap in the other plane. It'll register as needing a wipe, and get one. The alternative is to have a TAM transferred between planes, but then we would have to conform the receiving plane to it, which would be expensive. Just take the one-time hit.

So with that said, the easiest thing to do here would seem to be get rid of the call to `ncvisual_stream()`, and instead have two threads, with two piles. One pile contains the frame as being written out. The other pile contains one plane, onto which the other thread is rendering the next frame manually using `ncvisual_decode()`. Hell, it can render any number of upcoming frames, really (we probably want a small window so as to not blow out RAM). One thread writes, one renders. Alternatively, we could have both threads do both tasks -- when one is done rasterizing, the other can begin to rasterize. This keeps the bitmap data (probably significantly larger than all other data combined) on a single core, rather than crossing each time. It's a bit more complex, but probably better.

**Comment by dankamongmen** [comment]
My first attempt at threading this out definitely got us to 99% of time being spent in the 'W' phase (writing), which is exactly what we'd expect from an optimized version. This is promising!

**Comment by dankamongmen** [comment]
about a 20% speedup on a reasonably-sized xterm (i'd expect this to increase as the geometry increases). now i'm seeing a 30% reduction in kitty, where i wasn't expecting much speedup at all. sweet! need to smooth the rough edges but this ought improve performance significantly. basically, look at your current `xray` results. you probably have RAW={0, 0, w < 99}. whatever percentage of time is unaccounted for (i.e. 30% if you have RAW={0, 0, 70}) is going to now be spent writing, so with the numbers just mentioned, you'd expect a 30% runtime cut.

**Comment by dankamongmen** [comment]
on my laptop:

xterm goes from 73% W to 98% W, with a runtime drop from 54.76s to 38.36s, about a 30% cut.
kitty goes from 52% W to 98% W , with a runtime drop from 25.87s to 18.06s.
`foot` under wayland, we go from 9% W (9.9xs) to ... 9% W (9.9xs), suggesting that it's keeping up with our writes just fine (or that i fucked something up).

**Comment by joseluis** [comment]
I just tested this branch, and I get a segmentation fault during the first 3 seconds or so in kitty, xterm, alacritty...: but only in the big 2560x1440 screen:
```strace
fstat(4, {st_mode=S_IFREG|0644, st_size=3255, ...}) = 0
read(4, "\32\1\25\0\34\0\17\0i\1\242\5xterm-kitty|KovIdTTY"..., 32768) = 3255
read(4, "", 28672)                      = 0
close(4)                                = 0
ioctl(3, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
ioctl(3, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
ioctl(3, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
ioctl(3, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
ioctl(3, TIOCGWINSZ, {ws_row=78, ws_col=284, ws_xpixel=2556, ws_ypixel=1404}) = 0
write(3, "\33[?1h", 5)                  = 5
ioctl(3, TIOCGWINSZ, {ws_row=78, ws_col=284, ws_xpixel=2556, ws_ypixel=1404}) = 0
fcntl(0, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(0, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
mmap(NULL, 356352, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f38e97a6000
write(3, "\33[39;49m", 8)               = 8
write(3, "\33(B\33[m", 6)               = 6
write(3, "\33]104\7", 6)                = 6
write(3, "\33[?1002;1006l", 13)         = 13
write(3, "\33_Ga=d\33\\", 8)            = 8
write(3, "\33[?1h", 5)                  = 5
write(3, "\33[?25l", 6)                 = 6
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(0x88, 0x219), ...}) = 0
write(1, "\33[38;5;50m\n", 11
)          = 11
futex(0x7f38f392db94, FUTEX_WAKE_PRIVATE, 2147483647) = 0
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache", O_RDONLY) = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=27002, ...}) = 0
mmap(NULL, 27002, PROT_READ, MAP_SHARED, 4, 0) = 0x7f38f3aa7000
close(4)                                = 0
futex(0x7f38f38b2634, FUTEX_WAKE_PRIVATE, 2147483647) = 0
write(1, " notcurses 2.2.8 by nick black e"..., 57 notcurses 2.2.8 by nick black et al on xterm-kitty
) = 57
write(1, "  78 rows (18px) 284 cols (9px) "..., 126  78 rows (18px) 284 cols (9px) (346,12KiB) 48B crend 256 colors+RGB
) = 126
write(1, "  compiled with gcc-9.3.0, 16B l"..., 51  compiled with gcc-9.3.0, 16B little-endian cells
) = 51
write(1, "  terminfo from ncurses 6.2.2020"..., 37  terminfo from ncurses 6.2.20200212
) = 37
write(1, "  avformat 58.29.100 avutil 56.3"..., 54  avformat 58.29.100 avutil 56.31.100 swscale 5.5.100
) = 54
ioctl(2, TCGETS, {B38400 opost isig -icanon -echo ...}) = 0
write(2, "\33[38;5;203m", 11)           = 11
write(2, "\33(B\33[m", 6)               = 6
write(3, "\33[?1049h", 8) = ?
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

In the small 1920x1080 screen it finishes in 74 seconds ( down from 94), but it shows a lot of ghosting/artifacts? And FPS doesn't work:
![image](https://user-images.githubusercontent.com/5832068/116678257-6391d180-a9a9-11eb-8ff4-4f945ac80757.png)

![image](https://user-images.githubusercontent.com/5832068/116677739-d8b0d700-a9a8-11eb-992c-c2707897d495.png)

**Comment by dankamongmen** [comment]
yep, like i said, rough edges =]

**Comment by dankamongmen** [comment]
all of the difficulty here is in keeping two sprixels distinct despite the fact that we rely on a reference to kill it, which happens during the rendering cycle. i'll figure it out sometime today. it's absolutely possible, i just need figure out a way to do it sanely, ideally without library changes or shared, complex ownership.

**Comment by dankamongmen** [comment]
alright, i think i figured out the right way to do this (same end result):

each thread renders to a new pile each iteration
before rendering, eliminate the previous sprixel plane (left in the pile by the other thread) (NULL first iteration)
insert your plane into the standard pile
render+raster that fucker
plane gets collected, no contest while rendering to new pile, all good

let me go knock this out

**Comment by dankamongmen** [comment]
yes, this worked perfectly =]

**Comment by dankamongmen** [comment]
well, it's misplaced for some reason (too far down). but no crashing, and W=98%+

**Comment by dankamongmen** [comment]
70 rows (20px) 149 cols (10px) kitty goes from 5 to 15 fps, nice

**Comment by dnkl** [comment]
Niiice! Makes me wish I had a threadripper :D

Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz, 8 cores, 16 SMT:

Kitty
```
 notcurses 2.2.8 by nick black et al on xterm-kitty
  93 rows (23px) 349 cols (11px) (507,14KiB) 48B crend 256 colors+RGB
  compiled with gcc-10.2.0, 16B little-endian cells
  terminfo from ncurses 6.2.20200212
  avformat 58.76.100 avutil 56.70.100 swscale 5.9.100

487 renders, 475,39ms (604,95µs min, 976,15µs avg, 10,43ms max)
487 rasters, 145,27ms (138,01µs min, 298,31µs avg, 361,39µs max)
487 writes, 169,82s (800,52µs min, 348,71ms avg, 396,49ms max)
19,27GiB (33,87KiB min, 40,52MiB avg, 40,60MiB max)
0 failed renders, 0 failed rasters, 0 refreshes
RGB emits:elides: def 1213:14900558 fg 34528:2024259 bg 14141:435926
Cell emits:elides: 15351838/15861788 (50,82%) 99,99% 98,32% 96,86%
Sprixel emits:elides: 486/0 (0,00%)

             runtime│ frames│output(B)│    FPS│%r│%a│%w│TheoFPS║
══╤════════╤════════╪═══════╪═════════╪═══════╪══╪══╪══╪═══════╣
 1│    xray│ 170,76s│    486│  19,27Gi│    2,8│ 0│ 0│99│   2,85║
══╧════════╧════════╪═══════╪═════════╪═══════╧══╧══╧══╧═══════╝
             170,76s│    486│  19,27Gi│
```

Foot
```
 notcurses 2.2.8 by nick black et al on foot
  93 rows (23px) 348 cols (11px) (505,69KiB) 48B crend 256 colors+RGB
  compiled with gcc-10.2.0, 16B little-endian cells
  terminfo from ncurses 6.2.20200212
  avformat 58.76.100 avutil 56.70.100 swscale 5.9.100

487 renders, 815,75ms (602,02µs min, 1,68ms avg, 7,62ms max)
487 rasters, 147,67ms (140,12µs min, 303,21µs avg, 535,88µs max)
487 writes, 75,07s (576,90µs min, 154,15ms avg, 335,51ms max)
313,46MiB (6,63KiB min, 659,10KiB avg, 1,54MiB max)
0 failed renders, 0 failed rasters, 0 refreshes
RGB emits:elides: def 758:496822 fg 36914:867400 bg 14433:420670
Cell emits:elides: 932683/30190361 (97,00%) 99,85% 95,92% 96,68%
Sprixel emits:elides: 972/0 (0,00%)

             runtime│ frames│output(B)│    FPS│%r│%a│%w│TheoFPS║
══╤════════╤════════╪═══════╪═════════╪═══════╪══╪══╪══╪═══════╣
 1│    xray│ 103,69s│    486│ 313,43Mi│    4,7│ 0│ 0│72│   6,39║
══╧════════╧════════╪═══════╪═════════╪═══════╧══╧══╧══╧═══════╝
             103,69s│    486│ 313,43Mi│
```
