### ISSUE TITLE
Git master Build Failing Dec 2019

### ISSUE THREAD

**Issue by clort81** [dankamongmen/notcurses#161]
Hi!  Very cool idea.  I do some unicode textart and would like to try this out.

On arm (aarch64) and devuan, make fails here:  I don't know how to fix, sorry.

```
$ cmake ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Checking for module 'tinfo>=6.1'
--   Found tinfo, version 6.1.20191019
-- Checking for module 'libavutil>=56.0'
--   Found libavutil, version 56.31.100
-- Checking for module 'libavformat>=57.0'
--   Found libavformat, version 58.29.100
-- Checking for module 'libswscale>=5.0'
--   Found libswscale, version 5.5.100
-- Found GTest: /usr/lib/aarch64-linux-gnu/libgtest.a (Required is at least version "1.9") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/projects/notcurses/build

$ make
Scanning dependencies of target notcurses
[  2%] Building C object CMakeFiles/notcurses.dir/src/lib/enmetric.c.o
[  4%] Building C object CMakeFiles/notcurses.dir/src/lib/fade.c.o
[  6%] Building C object CMakeFiles/notcurses.dir/src/lib/input.c.o
/home/user/projects/notcurses/src/lib/input.c:209:9: error: conflicting types for ‘notcurses_getc’
 wchar_t notcurses_getc(notcurses* nc, const struct timespec *ts, sigset_t* sigmask){
         ^~~~~~~~~~~~~~
In file included from /home/user/projects/notcurses/src/lib/internal.h:12,
                 from /home/user/projects/notcurses/src/lib/input.c:4:
/home/user/projects/notcurses/include/notcurses.h:231:9: note: previous declaration of ‘notcurses_getc’ was here
 API int notcurses_getc(struct notcurses* n, const struct timespec* ts, sigset_t* sigmask);
         ^~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/notcurses.dir/build.make:89: CMakeFiles/notcurses.dir/src/lib/input.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:277: CMakeFiles/notcurses.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by dankamongmen** [comment]
Huh, sure enough. I guess that's compiling for me because wchar_t is int on my platform, and unsigned or something on yours. Should be fixed now.

**Comment by dankamongmen** [comment]
If you have the time, it would be awesome if you could run `notcurses-input` on your platform (assuming it builds now), mash some keys (throw in some Unicode if you're comfortable doing so), and make sure everything looks like. Just start pressing keys once it comes up. It ought look like this:

![2019-12-18-110927_6x3_scrot](https://user-images.githubusercontent.com/143473/71102386-66aa6a00-2186-11ea-9ce4-b013b384f3eb.png)

Thanks a ton!

**Comment by clort81** [comment]
Builds now without issues.    notcurses-input displays whatever i paste to it. 

notcurses-demo shows a blank box for some of the unicode languages, but I conclude that's due to missing fonts.

Demo video looks to update with the same fps as I get with raw ANSI escape codes.  Tested with xfce4-terminal and kitty. Very fast with kitty, but kitty seems to have problems with some of the chinese fonts. (the box with text in demo isn't boxshaped)

Thanks for doing this.  I've been waiting a long time. :)

**Comment by dankamongmen** [comment]
Thanks for doing the testing; I'm relieved to hear that the input layer works on a differently-defined `wchar_t`. Yes, missing characters are almost certainly due to missing fonts, though some of the boxes simply have long ranges of undefined characters.

The box in the uniblock demo will be disfigured by (1) glyphs differently represented than `wcwidth()` would lead one to think or (2) certain BiDi interactions. It's a lot better now than it was naively :). I'm looking to lock this down perfectly, but I'm not sure how without querying the font.

Enjoy it! There's much more coming.
