### ISSUE TITLE
track a per-pile absx/absy

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1615]
Currently, any margins are accessible only via checking the `absy`/`absx` params in the standard plane. These ought be properties of piles, not planes, IMHO. Even if the margins ought be the same across all piles, reaching into the standard plane from another pile during rendering/rasterization is a thread safety issue.

**Comment by dankamongmen** [comment]
we also ought make the `tinfo` our source of truth of the most recently `ioctl()`-reported cell geometry, as discussed in #1525

**Comment by dankamongmen** [comment]
wouldn't we just duplicate the margins into each pile? margins are a property of the *context*, **not** of piles.

so really they belong in `termdesc`. that eliminates the thread safety issue, while keeping them in one place.

`absy`/`absx` then remain properties of planes, as they ought, interpreted relative to the margins of `termdesc`. there's no reason to have any of this in the pile structure.

**Comment by joseluis** [comment]
BTW I'm not sure this is 100% related but it made me remember the following sentence from: https://notcurses.com/notcurses_visual.3.html#options ?

>"If n was NULL (new plane), they specify the origin of the new plane relative to the standard plane"

shouldn't it say relative to the terminal dimensions or termsize?

**Comment by dankamongmen** [comment]
> > "If n was NULL (new plane), they specify the origin of the new plane relative to the standard plane"
> shouldn't it say relative to the terminal dimensions or termsize?

they're the same thing, no? the standard plane is guaranteed to be the same size as the visual area (terminal size minus margins).

**Comment by joseluis** [comment]
the standard plane does have the size of the terminal, but when you use that term, it seems too specific, and if you are working with other piles without touching the standard plane it can be confusing to refer to the standard plane as a reference...

I'm finding these things while I'm working on the higher level rust wrappers where I'm not using the concept of the standard plane, and I'm trying to simplify and clarify the concepts...

**Comment by dankamongmen** [comment]
sure, if that seems clearer i'll make that change

**Comment by joseluis** [comment]
That was a source of confusion for me sometimes. In general I think is clearer to refer to the desired properties directly instead to an object that encarnate those properties, because the object can be mistaked for the needed thing, not the properties. And if the object is an example, clarify it as such.

**Comment by dankamongmen** [comment]
so the margin information is already stored in the context. it's then reduced to the `absy`/`absx`/`row`/`cols` of the standard plane. we want the standard plane to accurately reflect the visual area's geometry. other root planes may or may not, but ought respect the margins. but margins are only relevant to rendering (and resizing of the standard plane) -- everywhere else, we have to work around them.

so i say we *stop putting the margins in the standard plane's `abs{yx}`*. rendering will get them out of the `struct notcurses*`, as will resize. they'll be 0 for the standard plane at all times, simplifying numerous functions.

**Comment by dankamongmen** [comment]
oh wow, i think `notcurses_resize_internal()` is super broken when we're rendering anything but the standard pile. it is always called on the standard plane from `notcurses_resize()`:

```c
// Check for a window resize on the standard pile.                                                         
static int                                                                                                 
notcurses_resize(notcurses* n, int* restrict rows, int* restrict cols){                                    
  pthread_mutex_lock(&n->pilelock);                                                                        
  int ret = notcurses_resize_internal(notcurses_stdplane(n), rows, cols);                                  
  pthread_mutex_unlock(&n->pilelock);                                                                      
  return ret;                                                                                              
}
```

and likewise `notcurses_render()` always calls `ncpile_render()` with the standard plane:

```c
int notcurses_render(notcurses* nc){                                                                       
//fprintf(stderr, "--------------- BEGIN RENDER\n");                                                       
//notcurses_debug(nc, stderr);                                                                             
  ncplane* stdn = notcurses_stdplane(nc);                                                                  
  if(ncpile_render(stdn)){                                                                                 
    return -1;                                                                                             
  }                                                                                                        
  int i = ncpile_rasterize(stdn);                                                                          
//fprintf(stderr, "----------------- END RENDER\n");                                                       
  return i;                                                                                                
}
```

but we can call `ncpile_render()` with any plane, and it calls directly through to `notcurses_resize_internal()`:

```c
int ncpile_render(ncplane* n){                                                                             
  struct timespec start, renderdone;                                                                       
  clock_gettime(CLOCK_MONOTONIC, &start);                                                                  
  notcurses* nc = ncplane_notcurses(n);                                                                    
  ncpile* pile = ncplane_pile(n);                                                                          
  // update our notion of screen geometry, and render against that                                         
  notcurses_resize_internal(n, NULL, NULL);                                                                
  if(engorge_crender_vector(pile)){                                                                        
    return -1;                                                                                             
  }                                                                                                        
  // FIXME notcurses_stdplane() doesn't belong here #1615                                                  
  ncpile_render_internal(n, pile->crender, pile->dimy, pile->dimx,                                         
                         notcurses_stdplane(nc)->absy,                                                     
                         notcurses_stdplane(nc)->absx);                                                    
  clock_gettime(CLOCK_MONOTONIC, &renderdone);                                                             
  pthread_mutex_lock(&nc->statlock);                                                                       
  update_render_stats(&renderdone, &start, &nc->stats);                                                    
  pthread_mutex_unlock(&nc->statlock);                                                                     
  return 0;                                                                                                
}
```

=[

**Comment by dankamongmen** [comment]
alright, i think i've got this working, and i've eliminated a great many references to `stdplane` from all over the place. root planes at the origin of the viewing area now have an origin of 0,0, instead of one equivalent to the top and left margins (this refers to internal variables; they were all normalized for user accesses, and have been for some time). when we need to check the margins, we use `nc->margin_t` and `nc->margin_l` everywhere now, in a wholly threadsafe way.

one thing i noticed is that `notcurses_resize_internal()` might not be taking margins into account when resizing. need to verify that.

this could stand a lot of testing, to be sure. `dankamongmen/unify-margins` branch.

**Comment by dankamongmen** [comment]
generally looking good. i think `ncplane_mergedown_simple()` might be broken, as we're getting a failure in `Fills::MergeDownUni`.
