### ISSUE TITLE
ultramegaok demo

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#162]
1.0.0 will, Allah willing, include the ultramegaok demo. Just how ultra, mega, and ok it will be remains to be seen.

Putting it together as envisioned in the shower just now will require:
* mouse events, stretch in and of itself (#165 , complex probably)
* pulsing text, shouldn't be tough (#163 , not too tough)
* braille graphs (#136, large issue)
* demo generics (to get timing for each, etc.) (#164 , should be simple)
* and a demo carrier (this bug, probably a day's work to get perfect)

but oh man wouldn't it be phat!

https://www.youtube.com/watch?v=kkG616A2byo

**Comment by dankamongmen** [comment]
We now have mouse input (#165) and demo generics (#164). Braille graphs and pulsing text aren't strictly necessary, but they'd be nice gets. With the former two, though, I think we ought aim to have some form of ULTRAMEGAOK done for 1.0.0.

We'll need two more pieces I haven't enumerated here:

* hook up mouse events to moving an ncplane, easy
* persistent top-level event listener that performs those moves based on mouse events -- easy -- *and* somehow republishes other events for demo subcode

I think the latter is best accomplished by swapping out direct calls to `notcurses_getc_*()` in the demos with calls to a new `demo_getc()` implemented in `demo.c`. The latter will launch a persistent thread which watches for input events. Mouse events will result in ncplane moves. Other events will be added to an internal queue, from which `demo_getc()` will read. That all seems simple enough.

Ultra! Mega! OK!

**Comment by dankamongmen** [comment]
We've got our toplevel event handler. We can move on this with just what we have.

ULTRAMEGAOK demo is not a standalone demo, per se. An ncplane is created prior to running the first demo, at the bottom of the screen. it is 5 lines at max, and 40 columns. This will function as a HUD throughout the demo. It will have a horizontal histogram featuring up to 5 demos. this histogram will graph FPS by demo. 

in addition to the histogram, we will display the FPS as a %6.1f. bam!

this subplane can be freely moved around the display using the mouse. bam!

if we get pulsing text working, we will pulse the running demo's name. bam!

if we implement CELL_ALPHA_BLEND (#191), we will have a translucent background. bam! until then, use a black background.

ideally it will be updated prior to each render. bam! at a minimum it must be updated prior to each demo.

https://www.youtube.com/watch?v=NH4xWbGF1DA. bam!

**ULTRAMEGAOK**

**Comment by jart** [comment]
If you want to do a demo, you have to be as extreme as possible.

What I'd like to see happen is [derasterize](https://github.com/jart/derasterize) block rendering in 3D with ray tracing of generated surfaces mapped through perlin's noise function inside a 24-bit ANSI UNICODE pseudo-teletypewriter display running on bare metal.

**Comment by jart** [comment]
This single header only project is really good, and has most of the algorithms you'd need (e.g. tile generator, noise function, etc.) to build the sort of demo I described in my previous comment: https://github.com/nothings/stb
