### ISSUE TITLE
unsound notcurses_stats_alloc

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1633]
the rust linter complains about notcurses_stats_alloc:

```rust
pub unsafe extern "C" fn notcurses_stats_alloc(
    nc: *const notcurses
) -> *mut ncstats
```
[source](https://rust-lang.github.io/rust-clippy/master/index.html#mut_from_ref)
```
This lint checks for functions that take immutable references and return mutable ones.
This is trivially unsound, as one can create two mutable references from the same (immutable!) source.
```

I guess it would be sounder to change this function:
```c
API ALLOC ncstats* notcurses_stats_alloc(const struct notcurses* nc)
  __attribute__ ((nonnull (1)));
```
to:
```c
API ALLOC ncstats* notcurses_stats_alloc(struct notcurses* nc)
  __attribute__ ((nonnull (1)));
```

**Comment by dankamongmen** [comment]
here's the actual implementation:

```c
ncstats* notcurses_stats_alloc(const notcurses* nc __attribute__ ((unused))){   
  return malloc(sizeof(ncstats));                                               
}
```

as you can see, this is safe. what would make more sense is to drop the argument entirely, or better yet mark it as `((unused))` in the header file, assuming that will quiet down the soundness checker. i'll add that annotation, and we can see what happens!

**Comment by dankamongmen** [comment]
I've added an `unused` annotation to the include file. Does that help?

**Comment by dankamongmen** [comment]
Gonna assume so; closing this up for 2.3.0. Please reopen if the problem persists.
