### ISSUE TITLE
add ncblit_rgb_{packed, loose}()

### ISSUE THREAD

**Issue by kaniini** [dankamongmen/notcurses#1634]
i have a framebuffer that contains RGB data packed in 32-bit words.  adding an alpha channel is possible, but slows down my code.  it would be nice if we could just have the blitter assume 100% opacity instead.

**Comment by dankamongmen** [comment]
I'll do you one better and accept opacity as a parameter across the entirety of the region. I should be able to do this today.

**Comment by kaniini** [comment]
sounds great.  right now i have a lot of loops adding alpha channels to things, which is not great :)

**Comment by dankamongmen** [comment]
we probably want an `ncvisual_from_rgb()` along with `ncblit_rgb()`, for orthogonality if nothing else.

**Comment by dankamongmen** [comment]
fuck it, i can just add `ncblit_rgb()` for loose RGB (meaningless A) and `ncblit_rgb_packed()` for tight RGB. the former will want a linesize which is a multiple of 4; the latter will want a linesize which is a multiple of 3. the former will, for now, suffer an intermediate allocation and an extra copy. the latter will suffer an extra copy. if these prove to be performance problems, i can pipe this format info all the way forward to the blitters for `ncblit_*()`. `ncvisual_from_*()` is SoL; i'm not very interested in making `ncvisual` a multiformat deal. RGBA, ride or die.

**Comment by dankamongmen** [comment]
Added. I'm probably gonna throw some unit tests on these before closing the bug up.

**Comment by kaniini** [comment]
> If I understand you correctly, you have 4 bytes per pixel, just with a meaningless alpha value? You use "packed" and "32-bit words" together; I would think the first to mean "24-bit words", but the latter would seem to contradict that.

It's 32-bit words: `(r << 24 | g << 16 | b << 8) | 0xff`.  I want to just ignore the lowest 8 bits and assume alpha is always `0xff`.

In technical parlance, this is sometimes called `RGBX_8888` encoding.  It's a popular encoding for framebuffers which will not be composited further.

**Comment by kaniini** [comment]
Yep, looks like `ncblit_rgb_loose()` does what I need.
