### ISSUE TITLE
Include static functions in cffi

### ISSUE THREAD

**Issue by scauligi** [dankamongmen/notcurses#1636]
I didn't see a script to generate the `build_notcurses.py` anywhere in the repo so I'm not sure if you're manually editing that file or automatically generating it.

While we're waiting for the better python bindings to take fruition, it would be great to have a fuller cffi API available, e.g. access to `notcurses_getc_nblock`.
From my own testing, these can still be included in the `cdef` portion of the cffi even though they're static functions in `notcurses.h`.

If the `build_notcurses.py` isn't automatically generated then I'm happy to submit a PR adding the missing functions.

Related, the `#define` constants such as `NCOPTION_NO_ALTERNATE_SCREEN` can also be moved into the `cdef` and can then be accessed via `lib`.

**Comment by dankamongmen** [comment]
It is not automatically generated, though a means to do so would be warmly welcomed. I had difficulties directly including `static inline` functions into the python many months ago, but if you've found a way to do so that works, I would absolutely merge any PR.
