### ISSUE TITLE
build notcurses-doc package on Alpine

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1638]
From what I can tell, we don't currently make our man pages available on Alpine. There's a `$pkgname-doc` listed in `subpackages`, but we use `USE_PANDOC=off` in the `build` stanza, and never download the pregenerated documentation tarball (like we do on Gentoo and FreeBSD).

We ought download the documentation tarball, unpack it, and install the man pages into the appropriate Alpine-blessed location. These ought be included in `notcurses-doc`.

Tagging the ever-vivacious @kaniini in case she has any tips. If this is trivial, let's get it done for 2.3.0. If it's not, 3.0.0 it is.

**Comment by kaniini** [comment]
yes, your assumptions are right

**Comment by dankamongmen** [comment]
Let's go ahead and get this done for the 2.3.0 Alpine update.

**Comment by dankamongmen** [comment]
with these changes, `abuild unpack` leaves the precious manpages in `src/`, ripe for installation

**Comment by dankamongmen** [comment]
> with these changes, `abuild unpack` leaves the precious manpages in `src/`, ripe for installation

...so it doesn't look like we need do anything in the `prepare` stanza

**Comment by dankamongmen** [comment]
> doc()
Subpackage function for the $pkgname-doc package whose job is only to collect documentation folders from $pkgdir nothing more. Without specifying a custom doc() function, abuild will call its internal doc() function, which in turn calls default_doc().
default_doc() will move "$pkgdir"/usr/share/{doc,man,info,html,sgml,licenses,gtk-doc,ri,help} to $subpkgdir.
Overriding this function is strongly discouraged. Packaging docs should be done in the package() function while letting abuild automatically collect the doc folders.
Important: For default_doc() to be called as in no doc(), you need to explicitly add subpackages="$pkgname-doc".

so we don't want to override this, but rather just ensure things are installed into `/usr/share/man/manX` by `package`

**Comment by dankamongmen** [comment]
alright, i think i got it, verified with `apk manifest` of the resulting `notcurses-doc-2.3.0-r0.apk`

**Comment by dankamongmen** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/21272
