### ISSUE TITLE
honor lenx/leny in ncvisual rendering

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1661]
Towards the end of 2.2.x development, I believe `leny` and `lenx` from `ncvisual` started to be ignored. We need be honoring them. I think this flows all the way to `ncdirect` breakage as reported in #1659.

**Comment by dankamongmen** [comment]
let's get this done for 3.0.1

**Comment by dankamongmen** [comment]
i've added a unit test for this case, which does indicate that we're failing to honor these limits. @dnkl this will definitely fix up the `maxx` issue you reported.

**Comment by dankamongmen** [comment]
`ymax` and `xmax` are now honored in ncdirect

**Comment by dankamongmen** [comment]
alright, i think we've got this working. i'd like to add another unit test, where we start with a 2-wide ncvisual, one pixel white, one pixel black. feed in a `NCSCALE_STRETCH` to a plane some n > 1 wide, with lenx capped at 1. all the results ought be the same color.

**Comment by dankamongmen** [comment]
> alright, i think we've got this working. i'd like to add another unit test, where we start with a 2-wide ncvisual, one pixel white, one pixel black. feed in a `NCSCALE_STRETCH` to a plane some n > 1 wide, with lenx capped at 1. all the results ought be the same color.

this one is necessary to make sure len is being applied only to the source spec and not the scaled spec.

**Comment by dnkl** [comment]
Thanks! I'll hopefully have some time to test this weekend.
