### ISSUE TITLE
ncdirect_cursor_yx() fails with "Unexpected result from terminal: 13"

### ISSUE THREAD

**Issue by dnkl** [dankamongmen/notcurses#1664]
This started happening after I pulled the new `ncdirectf_*()` changes, and started using the new APIs.

`ncdirect_cursor_yx()` now fails with _"Unexpected result from terminal: 13"_.

Before this call, I'm doing (on multiple images):

* `ncdirectf_from_file()`
* `ncdirectf_geom()`
* `ncdirectf_render()`
* `ncdirectf_free()`

That's it, after that I'm doing the `ncdirect_cursor_yx()` call, which now fails.

**Comment by dnkl** [comment]
I can do a bisection. Just thought I'd post this, without much more info, in case you already have an idea of what's going on.

**Comment by dankamongmen** [comment]
13 is a newline, and it sounds like perhaps input from you? i don't think i'm filtering out escapes from the terminal and separating them from possible user input. are you generating that CR?

**Comment by dankamongmen** [comment]
`ncdirect_cursor_yx()` frightens me. i tried using it to implement something a few weeks ago, and ran into problems with its heavy use. i suspect this comes down to a general interleaving of return escapes with stdin (embarrassing admission: when i started this project, a year and a half ago, through when i wrote the input layer, i didn't understand there were escapes for me to read other than special keys. it shows.)

**Comment by dankamongmen** [comment]
if you wanna link your code, i'll happily reproduce over here. what i said above doesn't seem to apply to what you're describing with regard to changes, hrmmm.

oh and i mean you're always more than welcome to join in on debugging; i just was embarrassed, ha, and didn't want you thinking you had to spend your time debugging to get things looked at =] sorry if it came off as dismissive or in any way unappreciative

**Comment by dnkl** [comment]
> 13 is a newline

But of course 🤦

> and it sounds like perhaps input from you?

Then I _think_ what's happening is it's waiting for the response (which it _should_ be receiving), but fails to parse it and then I hit enter and it sees that.

Yup, the number changes depending on which key I press. After pressing a key, I see half of the cursor query response in the prompt.

> oh and i mean you're always more than welcome to join in on debugging; i just was embarrassed, ha, and didn't want you thinking you had to spend your time debugging to get things looked at =] sorry if it came off as dismissive or in any way unappreciative

Nah, don't worry about that. I believe in spending a few moments trying to get a feeling for the problem. At the very least it often results in better bug reports.

**Comment by dnkl** [comment]
> if you wanna link your code, i'll happily reproduce over here. what i said above doesn't seem to apply to what you're describing with regard to changes, hrmmm.

It's not online anywhere. Attaching it here instead.
[lsi.txt](https://github.com/dankamongmen/notcurses/files/6489776/lsi.txt)

**Comment by dnkl** [comment]
hmm, looks like maybe the problem is on my side after all; I think my program gets stuck in the while loop, causing us to spend most of the time in `ncdirect_cursor_yx()`.

**Comment by dnkl** [comment]
Yup, this one's on me. Sorry for wasting your time :/

I'm using unscaled image dimensions when checking if an image fits. There's an image that larger than the terminal window, causing it to get stuck on that image.
