### ISSUE TITLE
add tabular data display widget

### ISSUE THREAD

**Issue by MasFlam** [dankamongmen/notcurses#1679]
At some point it'd be worth making a widget for displaying tabular data, and by that I mean something in the likes of what `top` does. It is fairly similar to `nctree` or `ncselector`, but data would be organized in rows, each containing one value for each of the previously defined columns. Definitely a more complex widget to implement, but most likely worth the effort.

**Comment by dankamongmen** [comment]
hrmm is this #910

**Comment by MasFlam** [comment]
It is, my bad I didn't notice the previous issue
