### ISSUE TITLE
Process stays running after main() returns

### ISSUE THREAD

**Issue by MasFlam** [dankamongmen/notcurses#1698]
I encountered the problem while working on [a snake game](https://github.com/MasFlam/notcurses-snake).

As far as interaction with notcurses goes, the program creates an `ncvisual` (using `ncvisual_from_rgba()`) of width equal to `notcurses_stddim_x()` and height equal to `2*notcurses_stddim_y()`. It is then blitted with `NCBLIT_2x1` and `NCSCALE_NONE` onto the standard plane. Other than that, the program creates a plane atop the standard plane when it is paused, and when the player loses. It also reads input with `notcurses_getc_nblock()` every couple hundred milliseconds, or continuously iff receiving unbound input.

When the program is supposed to close,  `notcurses_stop()` is called and `main()` returns but the process doesn't end, and instead it starts ramping up the CPU forever. (until I send a SIGINT through Ctrl-C) I never fork the process myself nor do any other IO than what is done through notcurses. Also, the hang only occurs after the program is running for enough time to grow the snake long enough to be able to lose the game.

Aaaand I just realized that when I quit the game after a couple of seconds, I get this output:
```
double free or corruption (fasttop)
Aborted
```
So I have no idea currently if I have bugs in my memory management code or if notcurses is even at fault here...

Terminal: kitty
Notcurses version: 2.3.1

**Comment by MasFlam** [comment]
Is rendering `ncvisual`s to the standard plane even allowed? I tried doing that with `NCBLIT_PIXEL`, it didn't work and with loglevel debug I got something in the lines of `Won't blit to the standard plane`. If it isn't, could this be the reason?

**Comment by dankamongmen** [comment]
gonna look into this today, thanks for the report!

**Comment by dankamongmen** [comment]
> Is rendering `ncvisual`s to the standard plane even allowed? I tried doing that with `NCBLIT_PIXEL`, it didn't work and with loglevel debug I got something in the lines of `Won't blit to the standard plane`. If it isn't, could this be the reason?

it is definitely the case that `NCBLIT_PIXEL` cannot be rendered to the standard plane (it's the very first line of the internal function `ncvisual_render_pixels()`. but that's no reason a program would "keep running"...

**Comment by dankamongmen** [comment]
> When the program is supposed to close, notcurses_stop() is called and main() returns but the process doesn't end, and instead it starts ramping up the CPU forever.

i fundamentally don't understand how this could be the case. if you return from `main()`, that's equivalent to calling `exit()`. from https://en.cppreference.com/w/c/language/main_function:

> 2) If the return type of the main function is compatible with int, then the return from the initial call to main (but not the return from any subsequent, recursive, call) is equivalent to executing the exit function, with the value that the main function is returning passed as the argument (which then calls the functions registered with atexit, flushes and closes all streams, and deletes the files created with tmpfile, and returns control to the execution environment).

so unless you have something registered with `atexit()`, your program should be done -- that's the "returns control to the execution environment".

why do you think you've returned from `main()`?

regarding your double-free, have you tried running under `valgrind`? something like `valgrind --tool=memcheck` ought be very useful.

**Comment by dankamongmen** [comment]
hey @MasFlam , was `valgrind` able to make anything clear? i'm thinking i want to close this, as i just can't imagine notcurses having this effect, but i'd also like to make sure you get your problem solved.

**Comment by MasFlam** [comment]
Sorry for not responding. I'm currently on vacation without any way to really do anything with this. If we can leave the issue open for a week and a half longer or so, I promise I'll look into this again when I'm back.

**Comment by dankamongmen** [comment]
no worries at all mang, have a great time!

**Comment by dankamongmen** [comment]
If you'd like, just upload or mail (nickblack@linux.com) your source, and I'll check it out.

**Comment by MasFlam** [comment]
For some reason I never ran it with valgrind (why‽‽‽). There was some terrible, ugly and unholy memory code in one of the functions (what was i thinking‽). The code (fixed) is [here](https://github.com/MasFlam/notcurses-snake). Sorry for holding the issue up for literally months :|

I'm not sure though why bad memory management would make the program stall like in the original issue. `printf()`s right before `return 0` were `printf()`ing and yet the process didn't die, ever. Maybe it received sigsegv but the handler broke (for example because my code overwrote some notcurses data)?

Also which release renamed `CHANNELS_RGB_INITIALIZER` and got rid of `char32_t`? I usually glance at release notes every time but I must have missed it.
