### ISSUE TITLE
Can’t render sixels unless built with USE_MULTIMEDIA?

### ISSUE THREAD

**Issue by db48x** [dankamongmen/notcurses#1699]
It appears that notcurses must be built with multimedia support before it can render anything to sixels, even if you’ve loaded or created the image data itself. The pixel_cell example prints the error message “Error: NcError { int: -1, msg: "NcVisual.render()" }” when it tries to do it.

Have I missed something, or is this an oversight?

**Comment by dankamongmen** [comment]
No, you ought be able to able to render an `ncvisual` that you created via e.g. `ncvisual_from_rgba()`. The only function that ought fail due to a multimedialess build is `ncvisual_from_file()`. Can you show me some sample code?

**Comment by dankamongmen** [comment]
if you're using `NCBLIT_PIXEL` (which i assume you are, since you mention sixels), did you call `notcurses_check_pixel_support()`?

**Comment by db48x** [comment]
I left out some critical information: I’m using Rust :)

```
error[E0308]: mismatched types
   --> src/cli/writer.rs:359:20
    |
359 |     vframe1.render(nc, &voptions).expect("couldn’t render image to sixels");
    |                    ^^ expected struct `notcurses`, found struct `ncdirect`
    |
    = note: expected mutable reference `&mut notcurses`
               found mutable reference `&mut ncdirect`
```

I wasn’t calling `check_pixel_support`, but adding that in doesn’t fix it…

```rust
    use libnotcurses_sys::*;
    //let mut nc = NcDirect::new().expect("couldn’t create ncdirect");
    let mut nc = Notcurses::without_altscreen().expect("couldn’t initalize notcurses");
    let _ = nc.check_pixel_support();
    let vframe1 = NcVisual::from_bgra(dt.get_data_u8(), img_dim.1 as u32, (img_dim.0 * 4) as u32, img_dim.0 as u32).expect("couldn’t create visual");
    let voptions = NcVisualOptions::without_plane(1, 2, 0, 0, img_dim.1 as u32, img_dim.0 as u32, NCBLIT_2x2, 0, 0);
    vframe1.render(nc, &voptions).expect("couldn’t render image to sixels");
    nc.render().expect("failed to render anything");
    vframe1.destroy();
    nc.stop();
```

Although not shown here, `check_pixel_support` is returning `Ok(true)`.

**Comment by dankamongmen** [comment]
nice work @joseluis in #1700!

**Comment by dankamongmen** [comment]
@joseluis is the author of the Rust wrappers, and I'm guessing he's figured out what's up. @db48x , does his change in #1700 rectify your issue? i know blitting is working in master in C. if it's working in Rust in general, your code is likely hitting some error of mine, and i'll look into it tonight. sorry for the delay -- it was a long weekend here in the USA, and i'm just getting back on things now.

**Comment by db48x** [comment]
No worries about delays; I’m very much in weekend mode myself.

Although #1700 does fix a rather important bug, it’s not quite enough to fix the problem. For example, if I uncomment line 32 of example-1699.rs, then instead of rendering a purple square of pixels it prints an error.

**Comment by joseluis** [comment]
@db48x I've updated the example, could you try running it again? It works for me in xterm and kitty 20.3, like this:
![image](https://user-images.githubusercontent.com/5832068/120290815-fa142400-c2c2-11eb-8dbf-f759ac3e3117.png)

If it doesn't work for you, it'd be useful to know the error it gives you, what terminal & exact version are you using, and the result of the command `uname -a`.

**Comment by dankamongmen** [comment]
i'm going to hold off on cutting 2.3.2 until we know what's up here. the example code is likewise working for me :( @db48x if you could provide the output of `caps-rendered` (assuming you built notcurses from source), that would be very helpful. it's possible that this is some sixel effect arising from scaling heights.

output will look like this:
```
[schwarzgerat](0) $ ./caps-rendered 

 notcurses 2.3.1 by nick black et al on xterm-kitty
  70 rows (20px) 107 cols (10px) (117.03KiB) 48B crend 256 colors+RGB
  compiled with gcc-10.2.1 20210110, 16B little-endian cells
  terminfo from ncurses 6.2.20201114
  avformat 58.79.100 avutil 56.74.100 swscale 5.10.100
 Colors: 256 rgb: y ccc: y setaf: y setab: y
 sgr: y sgr0: y
 op: y fgop: y bgop: y
 rows: 70 cols: 107 rpx: 20 cpx: 10 (1400x1070)
 RGBA pixel graphics supported
 UTF8: y quad: y sex: y braille: y images: y videos: y
 background of 0x000000 is considered transparent
 cup: y vpa: y hpa: y
[schwarzgerat](0) $ 
```

**Comment by db48x** [comment]
One moment; I will definitely give it a try.

**Comment by db48x** [comment]
Ok, interesting.

In xterm -ti vt340 I get this:

> pixel support: Ok(true)
> Error: NcError { int: -1, msg: "NcVisual.render()" }
>  db48x  ~  src  notcurses  rust 

Meanwhile in Alacritty I get this odd result:

![Screenshot from 2021-06-01 01-56-08](https://user-images.githubusercontent.com/228849/120296403-9b957880-c2b7-11eb-8349-7ddd090b9468.png)

 notcurses 2.3.1 by nick black et al on alacritty
  35 rows (29px) 154 cols (12px) (84.22KiB) 48B crend 256 colors+RGB
  compiled with gcc-7.5.0, 16B little-endian cells
  terminfo from ncurses 6.1.20180127

 Warning! Notcurses was built without multimedia support.
 Colors: 256 rgb: y ccc: y setaf: y setab: y
 sgr: y sgr0: y op: y fgop: y bgop: y
 rows: 35 cols: 154 rpx: 29 cpx: 12 (1015x1848)
 didn't detect bitmap graphics support
 UTF8: y quad: y sex: n braille: y images: n videos: n
 background isn't interpreted as transparent
 cup: y vpa: y hpa: y

 notcurses 2.3.1 by nick black et al on xterm
  40 rows (25px) 154 cols (12px) (96.25KiB) 48B crend 8 colors+RGB
  compiled with gcc-7.5.0, 16B little-endian cells
  terminfo from ncurses 6.1.20180127

 Warning! Notcurses was built without multimedia support.

 Warning! Advertised TrueColor but no 'ccc' flag
 Colors: 8 rgb: y ccc: n setaf: y setab: y
 sgr: y sgr0: y op: y fgop: y bgop: y
 rows: 40 cols: 154 rpx: 25 cpx: 12 (1000x1848)
 max sixel size: 0x4096 colorregs: 256
 UTF8: y quad: n sex: n braille: y images: n videos: n
 background isn't interpreted as transparent
 cup: y vpa: y hpa: y

**Comment by dankamongmen** [comment]
@db48x , it looks like #1705 (just found by @joseluis , who is absolutely killing it of late) is probably responsible for your issues. this is a core notcurses problem, and i'm looking to fix it over the next few hours. thanks a lot for your patience.

**Comment by joseluis** [comment]
@db48x Alacritty doesn't really support pixels yet, so the output you see is it the NcVisual rendered using the next best BLITTER available.

@dankamongmen thanks you are too kind. This is what happens when you leave me alone in danger for the weekend :P

**Comment by dankamongmen** [comment]
reproducing this locally now. it's actually caught by our unit tests, i think, just our CI runs with `TERM=crapfactory` or something and thus doesn't execute this test, bah!

**Comment by db48x** [comment]
> @db48x , it looks like #1705 (just found by @joseluis , who is absolutely killing it of late) is probably responsible for your issues. this is a core notcurses problem, and i'm looking to fix it over the next few hours. thanks a lot for your patience.

That does look like a good bug to fix :dagger: 

However, note that I don’t get any pixel output at all, just an error message. There is, it would seem, more than one bug.

https://www.youtube.com/watch?v=zdmzGPAsDqM

> @db48x Alacritty doesn't really support pixels yet, so the output you see is it the NcVisual rendered using the next best BLITTER available.

Hmm. My Alacritty _does_ support pixels, and I thought I had modified notcurses to notice that. But even that shouldn’t be necessary; my Alacritty replies with `\E[?6;4c` in response to Send Device Attributes.

**Comment by db48x** [comment]
Ok, after poking at the code a bit more I see that it wants `\E[?6;4;c`. With Alacritty modified to include the extra semicolon, then notcurses detects that pixels are supported and I get the same failure to scale in the pixel-cell example, and the correct rendering in the issue-1699 example.

**Comment by db48x** [comment]
Hey, my program is getting pixels on the screen! They’re in the wrong place, but this is progress.
