### ISSUE TITLE
render pixels to NcDirect

### ISSUE THREAD

**Issue by db48x** [dankamongmen/notcurses#1707]
Apparently this can be done in C, but not when using the Rust bindings.

```Rust
let mut nc = NcDirect::new()?
// …
vframe1.render(nc, &voptions)?
```

This just gets you an error report from the type checker, because the `render` method wants a NotCurses object rather than an NcDirect.

Perhaps the easiest fix would be a `render_direct` method?

**Comment by dankamongmen** [comment]
yeah, this ought not require anything more than wrapping the `ncdirectf_*()` functionality (for a maximally flexible solution). even simpler would be wrapping `ncdirect_render_image()`, which is a one-shot deal.

**Comment by dankamongmen** [comment]
(but yeah, all blitters are supported in direct mode, as can be seen with `ncplayer -k`)

**Comment by db48x** [comment]
@joseluis already fixed this the other day:

```rust
let mut nc = NcDirect::new()?;
let vframe1 = NcDirectF::from_bgra(…)?; // see also other constructors
vframe1.ncdirect_render(nc, NCBLIT_PIXEL, NCSCALE_NONE, 0, 0)?;
nc.raster_frame(v, NCALIGN_LEFT)?;
```

**Comment by dankamongmen** [comment]
w00t ok awesome
