### ISSUE TITLE
enable quadrants+sextants in wezterm

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1715]
quadrants look pretty good (sextants are another story) in wezterm 20210502 (verified with `caps-rendered`). we don't have a match for `wezterm` just yet, but we ought get one, and enable quadrants.

**Comment by wez** [comment]
https://github.com/wez/wezterm/issues/584 is our issue tracking perfect block drawing glyphs, with https://github.com/wez/wezterm/pull/588 as a slow-moving-but-not-abandoned PR to implement them.

**Comment by dankamongmen** [comment]
you're my hero, ferris bueller

**Comment by wez** [comment]
I added just the sextant block glyphs to the nightly build just now.  I don't appear to have a font that has those glyphs, so I based this entirely off my one pass through page 3 of https://unicode.org/charts/PDF/U1FB00.pdf this evening. Let me know if it looks weird, or if you need the smooth mosaic glyphs too!

**Comment by dankamongmen** [comment]
i will test shortly, hot shit!

**Comment by dankamongmen** [comment]
testing as soon as build completes. before:

![2021-06-12-113552_1920x1080_scrot](https://user-images.githubusercontent.com/143473/121781383-71bf3a00-cb72-11eb-89ab-850761e9454a.png)

**Comment by dankamongmen** [comment]
running into a linking issue

```
  = note: /usr/sbin/ld: /home/dank/src/wezterm/target/release/deps/libfreetype-d6297c198392dce3.rlib(ftinit.o):(.data.rel.ro.ft_default_modules+0x80): undefined reference to `ft_sdf_renderer_class'
          /usr/sbin/ld: /home/dank/src/wezterm/target/release/deps/libfreetype-d6297c198392dce3.rlib(ftinit.o):(.data.rel.ro.ft_default_modules+0x88): undefined reference to `ft_bitmap_sdf_renderer_class'
```

but i think this is because i updated the submodules past where they are in upstream wezterm. doing a build in a fresh checkout.

**Comment by dankamongmen** [comment]
glorious!

![2021-06-12-115151_1920x1080_scrot](https://user-images.githubusercontent.com/143473/121781834-9a483380-cb74-11eb-921c-b8948bb0a73e.png)

is there any way for me to programmatically detect this feature? if not, i'm inclined to turn it on unconditionally when wezterm is detected, but i assume you have a better understanding of when new versions hit distros -- if you'd rather i hold off, let me know.

**Comment by dankamongmen** [comment]
one little thing while i have you here, @wez : your half blocks don't appear to meet. see the circled glyphs:

![broken-halves](https://user-images.githubusercontent.com/143473/121781997-79cca900-cb75-11eb-99c4-87b9e8bc48e1.png)

that lower half ought be rising to the same level where the upper half starts, or things will look weird. i assume you're drawing these yourself, rather than using the font? if so, it looks like the lower half needs to be raised, as opposed to the upper half truncated (i don't think the lower half is coming all the way up to the middle).

**Comment by dankamongmen** [comment]
i did a quick visual inspection of all your sextant glyphs, and they look correct. nice work!

**Comment by dankamongmen** [comment]
it looks like we can detect the wezterm version with its environment variables:

```
declare -x TERM_PROGRAM="WezTerm"
declare -x TERM_PROGRAM_VERSION="20210610-204057-2e7dc70e"
```

i'll be doing this in #1759, which is a dependency of this bug.

**Comment by wez** [comment]
re: halves not matching up, which codepoints are those; the ones in the `0x2580` block range or some others?

**Comment by dankamongmen** [comment]
> re: halves not matching up, which codepoints are those; the ones in the `0x2580` block range or some others?

```

[grimes](0) $ unicode U+2584 U+2580
U+2584 LOWER HALF BLOCK
UTF-8: e2 96 84 UTF-16BE: 2584 Decimal: &#9604; Octal: \022604
▄
Category: So (Symbol, Other); East Asian width: A (ambiguous)
Unicode block: 2580..259F; Block Elements
Bidi: ON (Other Neutrals)


U+2580 UPPER HALF BLOCK
UTF-8: e2 96 80 UTF-16BE: 2580 Decimal: &#9600; Octal: \022600
▀
Category: So (Symbol, Other); East Asian width: A (ambiguous)
Unicode block: 2580..259F; Block Elements
Bidi: ON (Other Neutrals)


[grimes](0) $ 
```

**Comment by dankamongmen** [comment]
alright, i've now got detection code that identifies WezTerm based off `TERM_PROGRAM` **iff `TERM` contains the string `xterm`**, and enables sextants iff `strcmp(TERM_PROGRAM_VERSION, "20210610") >= 0`. it all appears to work properly.

 old wezterm in `/usr/bin`, note `sextants: n`

![2021-06-12-130306_960x650_scrot](https://user-images.githubusercontent.com/143473/121783774-90c3c900-cb7e-11eb-8d4a-bff9570ffa20.png)

new wezterm in home, note `sextants: y`

![2021-06-12-130404_960x1057_scrot](https://user-images.githubusercontent.com/143473/121783793-acc76a80-cb7e-11eb-8561-bc418610a7ce.png)

**Comment by wez** [comment]
I just pushed a tweak to the half block rendering (really, all the 1/8th block rendering)

**Comment by dankamongmen** [comment]
sexblitter is now default in wezterm

![2021-06-12-131547_960x650_scrot](https://user-images.githubusercontent.com/143473/121784149-565b2b80-cb80-11eb-9287-d05ce59246c8.png)

yay!

**Comment by wez** [comment]
looks great!

**Comment by dankamongmen** [comment]
hrmmm, i'm thinking you might have one sextant off. i see sufficiently many strange regions (look around Montevideo, Rio de Jianaro, Washington DC and all its dread statism, Pretoria, Addis Ababa, etc.) that my autism meter goes to 10. i'll look into this and let you know whether there are truly any malformed glyphs.

**Comment by dankamongmen** [comment]
here's successive blitters in wezterm
![2021-06-12-132521_960x650_scrot](https://user-images.githubusercontent.com/143473/121784401-d03fe480-cb81-11eb-98a2-24ecfb206690.png)
![2021-06-12-132535_960x650_scrot](https://user-images.githubusercontent.com/143473/121784402-d0d87b00-cb81-11eb-8cef-63b51ae011b3.png)
![2021-06-12-132543_960x650_scrot](https://user-images.githubusercontent.com/143473/121784403-d0d87b00-cb81-11eb-8683-f5d909d60374.png)
![2021-06-12-132550_960x650_scrot](https://user-images.githubusercontent.com/143473/121784404-d0d87b00-cb81-11eb-9ad3-d051908cbd9b.png)
![2021-06-12-132555_960x650_scrot](https://user-images.githubusercontent.com/143473/121784405-d0d87b00-cb81-11eb-9887-222ed1d700c3.png)
![2021-06-12-132610_960x650_scrot](https://user-images.githubusercontent.com/143473/121784406-d0d87b00-cb81-11eb-8717-c78e05c213a6.png)

definitely looks like we're one glyph off in the sextants. i'll lock this down.

**Comment by dankamongmen** [comment]
found the bad glyph! pr incoming
