### ISSUE TITLE
multimedia-free implementation won't scale images in blit

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1718]
We allow a target geometry to be specified using `ncvisual_options`, and both the FFMpeg and OIIO implementations of `ncvisual` will implicitly scale an image, when necessary, prior to blitting. This is not a persistent scaling -- the scaled output is used for the blit, and then discarded. Without these implementations, we simply call `rgba_dispatch()`, and proceed sans scaling. This is unexpected, and a hole in the API. Use the new `bitmap_resize()` (implemented for `NCSCALE_INFLATE`) along this path to perform an implicit scaling, suitable for use with our blitters.

* [X] document which functions need a multimedia backend in `notcurses_visual.3`
* [X] remove all code from the `none` backend
* [X] eliminate unnecessary `AVFrame` from `ffmpeg_blit()`
* [x] extract `ffmpeg_resize_internal()` from `ffmpeg_blit()`, call it from `ffmpeg_resize()`
* [X] ~extract `oiio_resize_internal()` from `oiio_blit()`, call it from `oiio_resize()`~ *it would actually be really difficult to do this with OIIO due to API details, so we're not*
* [x] add `visual_resize_internal` field to `visual_implementation` interface, and initialize it in ffmpeg ~and oiio~
* [x] expand the no-backend case of `visual_resize_internal()` to perform any necessary scaling/cropping
* [x] call `visual_resize_internal()` before calling (now massively-reduced) `visual_blit`
  * except with OIIO, bleh
* [x] add a unit test for implicit scaling, and make sure it diagnoses the current case as broken

at the end, we'll have cut down the backends significantly, and we'll be able to perform inline scaling without a multimedia engine (admittedly using crappy non-interpolative `INFLATE`)

**Comment by dankamongmen** [comment]
currently, the implicit resizing is embedded directly into `{ffmpeg,oiio}_blit()`. this duplicates code against `{ffmpeg,oiio}_resize()`, and makes it impossible to do an implicit resize from outside the blitting context.

instead, let's extract the resize code from `*_blit()`, reduce `*_resize()` to a wrapper around the resize which sets up the `ncvisual_details()` (eliminating the code duplication). we can then call the implicit resizer in `ncvisual_render_{cells,pixels}()` for all paths, then call the blitter. this way, we don't need any special logic in those two functions.

finally, i'd like to get rid of the `none` implementation. this ought be nothing more than trivial wrappers around `libnotcurses-core` to facilitate linking. since we already do minimal graphics in `libnotcurses-core`, and they're the same as what's in `none` (theoretically), we shouldn't need any other code in `none`.

**Comment by dankamongmen** [comment]
> finally, i'd like to get rid of the `none` implementation. this ought be nothing more than trivial wrappers around `libnotcurses-core` to facilitate linking. since we already do minimal graphics in `libnotcurses-core`, and they're the same as what's in `none` (theoretically), we shouldn't need any other code in `none`.

hah! and note that `none_resize()` is missing the `pad_for_image()` fix that's present in `ncvisual.c`. Yeah, we gotta rid ourselves of this dumb idea.

**Comment by dankamongmen** [comment]
we should probably document exactly which functions require a multimedia engine, and which don't.

**Comment by dankamongmen** [comment]
alright, in the `dankamongmen/inflate-scale-deux` branch, i've pruned down the `none` implementation. it is now nothing more than the definition of a pointer.

**Comment by dankamongmen** [comment]
a quick survey of `ffmpeg_resize()` and `oiio_resize()` suggest that the internal `visual_resize()` API will need the following signature:

`uint32_t* visual_resize(const ncvisual* ncv, int rows, int* stride, int cols, const blitterargs* bargs)`

where `rows` and `cols` are in pixels, and `stride` is in bytes. the return value is a naked block of RGBA pixels, `stride` bytes per row of `cols` pixels, total size of `stride` * `rows`.

this comes from the signature of `visual_blit()` (it leaves out the `const blitset*`, not needed for resize). `stride` is an OUT parameter; the input stride is known from the `ncvisual` structure itself, as are the number of source rows and columns, and the location of the source data.

there's one annoyance here: cleanup isn't as simple as `free()`ing the return value. in FFmpeg, we need two `av_freep()` calls, only one of which corresponds to the data. i don't see any cleanup in OIIO, suggesting we replace the actual source data, violating the definition of our API. whoops! the OIIO `oiio_blit()` actually looks pretty FUBAR overall, and could use some TLC. hrmmm, though, looking at `ffmpeg.c`, maybe we can get rid of `sframe` in `ffmpeg_blit()`, and then we **could** just `free()` the actual data? hot shit, if it works! let's try...

**Comment by dankamongmen** [comment]
indeed, it appears that we can do the "implicit resize" (i.e. resize to naked data, without modifying the `ncvisual`) without an `AVFrame` just fine! w00t w00t!

**Comment by dankamongmen** [comment]
so, with that proven out (and just now committed, natch), i think we're down to a `free()` for each implementation in the epilogue. except OIIO, of course, but we'll presumably get there...

**Comment by dankamongmen** [comment]
@db48x , you're almost certainly running into issues arising from this bug. Essentially, everything you're putting in an `ncvisual_options` struct is being more or less ignored when used without a multimedia backend. I'm working on it as we speak.

**Comment by dankamongmen** [comment]
so, the question comes down to whether we can use a common epilogue, or need introduce a new callback....wait, can't we just embed the specific epilogue into `*_blit()` as we do now? hrmm, we'd need carry over a bit of state (hah, literally a bit) indicating whether or not the input data was to be destroyed. or actually, if we're unafraid to be a bit hacky, we could just compare the data to be blitted against the `data` field in the relevant `ncvisual`, hah! yeah let's do that. fuck the world; save yourself.

**Comment by dankamongmen** [comment]
I went ahead and added a unit test, and it did indeed fail on the `none` implementation until the last commit. Unfortunately, it's now also showing up a problem on OIIO, perhaps related to #1723 and #1722.

**Comment by db48x** [comment]
> @db48x , you're almost certainly running into issues arising from this bug. Essentially, everything you're putting in an `ncvisual_options` struct is being more or less ignored when used without a multimedia backend. I'm working on it as we speak.

Sadly I must report that notcurses works perfectly for my use–case, where I simply never scale anything.

**Comment by dankamongmen** [comment]
> > @db48x , you're almost certainly running into issues arising from this bug. Essentially, everything you're putting in an `ncvisual_options` struct is being more or less ignored when used without a multimedia backend. I'm working on it as we speak.
> 
> Sadly I must report that notcurses works perfectly for my use–case, where I simply never scale anything.

oh! i thought everything was still breaking horribly for you. great!
