### ISSUE TITLE
height difference in inflate vs scale for sixels

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1728]
See the last comments in #1705 for background. We've got a situation where it seems `NCSCALE_SCALE` and `ncvisual_inflate()` ought be generating the same height, but they're off by some number of rows less than 6 (it's almost certainly related to padding out sixels--i haven't seen this happen in kitty).

**Comment by dankamongmen** [comment]
ok, i've got a unit test now which reproduces this. i can confirm that i inflate a cell-sized bitmap by 4x, and it results in 5 lines, as predicted in #1705:

```c
===============================================================================
/home/dank/src/dankamongmen/notcurses/src/tests/bitmap.cpp:5:
TEST CASE:  Bitmaps
  InflateVsScale

/home/dank/src/dankamongmen/notcurses/src/tests/bitmap.cpp:356: ERROR: CHECK( 4 == ncplane_dim_y(ninf) ) is NOT correct!
  values: CHECK( 4 == 5 )

```

**Comment by dankamongmen** [comment]
we're 23x11 here -> 92x44, and indeed we see:

```
RENDERING: 90/44
RENDERING: 92/44
```

**Comment by dankamongmen** [comment]
so inflating 23 pixel rows by 4 leads to 92, which is not a multiple of 6. so it requires 96 pixel rows, which requires 5 cell rows.

meanwhile the scaling one doesn't have a fifth row to write even transparent sixels into. it only has 4 rows. and the most pixel rows that 4 cell rows can have is 92, which means the most sixel rows it can have is 90. we can't draw the bottom two rows of pixels, because that would require a fifth row.

so this is the correct behavior. if you used the new `NCVISUAL_OPTIONS_NONINTERPOLATION` flag (#1576) with a 4x4 plane, you would likewise get 90x44 pixels, or more meaningfully 15x44 sixels.

**Comment by dankamongmen** [comment]
@joseluis what are your thoughts here? i'm thinking that if i made the `ncplane` going into `ncvisual_render()` 5 rows tall and 4 columns wide, and used `NCSCALE_SCALE`, we'd get equal results. let me test that.

**Comment by dankamongmen** [comment]
yep!

**Comment by joseluis** [comment]
Ok.. but how is that this is true for xterm, but kitty shows a correctly sized scaled cell? I'll tell you more in the PR.

**Comment by dankamongmen** [comment]
> Ok.. but how is that this is true for xterm, but kitty shows a correctly sized scaled cell? I'll tell you more in the PR.

because kitty does not have a 6-row unit in which one draws, but instead single-row granularity. it's RGBA, not Sixel.

**Comment by dankamongmen** [comment]
for more details: if given a number of rows which is evenly divisible by 6, happy day. we draw exactly that number of sixels (columsn * quotient). if the number of rows is not a multiple of the cell height, so it goes; we only partially fill the cell. this usually means we blow away the cell and have to redraw it, leading to flicker, so this is best avoided if possible.

otherwise, we try to add (6 - (rows % 6)) transparent rows to the sixel, "rounding up". these will be drawn transparently (the pixels will never be specified). this makes us use P2=0 instead of P2=1 if we were using P2=1, which is unfortunate, but other than that it's no big deal.

otherwise, if we can't get the extra rows, we can only truncate our bitmap, removing (rows % 6) rows entirely.
