### ISSUE TITLE
expose noninterpolative scaling in direct mode and ncplayer, unfuck ncvisual_inflate()

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1738]
@dankamongmen  I've just added NCVISUAL_OPTION_NOINTERPOLATE to the rust bindings, and it works. Thank you for finishing it so quickly! I just updated the pixel-cell example to include it.

In that example I compare interpolative scaling, non-interpolative scaling, inflate and resize... And I also checked that ncvisual_resize always uses interpolation, even when using the NCVISUAL_OPTION_NOINTERPOLATE flag. That made me think.

1. Have you thought about maybe removing ncvisual_inflate and/or using ncvisual_resize in the same way scaling works now, for consistency, if not as a substitution as an alternative? 

2. And another issue is that downsizing to less than the original size makes the subsequent ncvisual_render fail... I don't remember if that's already in the roadmap or a nonfix...

**Comment by dankamongmen** [comment]
> 1. Have you thought about maybe removing ncvisual_inflate and/or using ncvisual_resize in the same way scaling works now, for consistency, if not as a substitution as an alternative?

yes, i had a minor breakdown at myself last night about `ncvisual_inflate()`, see all-caps comments in #1576. i at one point went into the bathroom, looked hatefully into the mirror, and yelled DO YOU THINK THIS IS SOME KIND OF GAME, YOU SWAGGERLESS CRETIN?

> 2. And another issue is that downsizing to less than the original size makes the subsequent ncvisual_render fail... I don't remember if that's already in the roadmap or a nonfix...

nooooooooooooooooooooooooooooo, i thought we fixed this? i have a unit test for this, even: `Bitmaps::SprixelMinimize`

**Comment by dankamongmen** [comment]
we might maybe wanna add a flag to `ncplayer` to allow use of noninterpolative scaling, i dunno

**Comment by dankamongmen** [comment]
i'm super pissed off about the diffculty of exposing it in the direct mode API, due to a stupid decision i made not one, but twice (not accepting a `ncvisual_options` in direct mode).

**Comment by dankamongmen** [comment]
and we probably oughtn't add it to `ncplayer` until we've exposed it in direct mode, or else it won't work with `-k`.

**Comment by dankamongmen** [comment]
fucking direct mode i hate you direct mode

**Comment by dankamongmen** [comment]
i think we ought just rewrite `ncdirectf_render()` to take an `ncvisual_options`. `ncdirectf_render()` was introduced pretty recently, though i know it already has rust wrappers...@joseluis what are your thoughts here? i'd do it in a branch, so we could sync the changes (or probably i can just make the rust changes myself). anyone out there in Notcurses land gonna be pissed off by this?

**Comment by dankamongmen** [comment]
> i think we ought just rewrite `ncdirectf_render()` to take an `ncvisual_options`. `ncdirectf_render()` was introduced pretty recently, though i know it already has rust wrappers...@joseluis what are your thoughts here? i'd do it in a branch, so we could sync the changes (or probably i can just make the rust changes myself). anyone out there in Notcurses land gonna be pissed off by this?

yeah, we need do this to sanely implement `ncdirect_stream()` anyway, which currently is marred with several FIXMEs (`ncdirect_stream()` **does** take an `ncvisual_options`).

**Comment by dankamongmen** [comment]
@joseluis if you look at `dankamongmen/direct-noninterpolative`, i've got the necessary `ncdirectf_render()` change in there now.

**Comment by dankamongmen** [comment]
and, as expected:

```rust
	   Compiling libnotcurses-sys v2.3.2 (/drone/src/rust)
188s
3287	error[E0061]: this function takes 3 arguments but 6 arguments were supplied
194s
3288	   --> src/visual/methods.rs:523:17
194s
3289	    |
194s
3290	523 |                 crate::ncdirectf_render(ncd, self, blitter, scale, max_y as i32, max_x as i32)
194s
3291	    |                 ^^^^^^^^^^^^^^^^^^^^^^^ ---  ----  -------  -----  ------------  ------------ supplied 6 arguments
194s
3292	    |                 |
194s
3293	    |                 expected 3 arguments
194s
3294	    | 
194s
3295	   ::: /drone/src/rust/target/debug/build/libnotcurses-sys-8d43744d70e4f6e0/out/bindings.rs:3:240694
194s
3296	    |
194s
3297	3   | ..."] pub fn ncdirectf_render (n : * mut ncdirect , frame : * mut ncdirectf , vopts : * mut ncvisual_options) -> * mut ncdirectv ; } exte...
194s
3298	    |       ---------------------------------------------------------------------------------------------------------------------------- defined here
```

**Comment by dankamongmen** [comment]
alright, this is ready to go once we get the rust update, and brings the full power of non-interpolative scaling (plus other things) to `ncdirectf_render()`. a good change for the future; unfortunate that it was so disruptive.

**Comment by dankamongmen** [comment]
`ncplayer` now accepts `-n` to force non-interpolative scaling. tested with both `-k` (direct mode) and without.

**Comment by joseluis** [comment]
> @joseluis if you look at `dankamongmen/direct-noninterpolative`, i've got the necessary `ncdirectf_render()` change in there now.

@dankamongmen I've just fixed it.

I'm just wondering why ncdirectf_render needs a mutable reference to the ncvisual options, but for ncvisual_render a const reference is enough?

**Comment by dankamongmen** [comment]
> > @joseluis if you look at `dankamongmen/direct-noninterpolative`, i've got the necessary `ncdirectf_render()` change in there now.
> 
> @dankamongmen I've just fixed it.
> 
> I'm just wondering why ncdirectf_render needs a mutable reference to the ncvisual options, but for ncvisual_render a const reference is enough?

because i'm a great big stupid person, great catch, thanks homie! w00t w00t!

**Comment by dankamongmen** [comment]
> > > @joseluis if you look at `dankamongmen/direct-noninterpolative`, i've got the necessary `ncdirectf_render()` change in there now.
> > 
> > 
> > @dankamongmen I've just fixed it.
> > I'm just wondering why ncdirectf_render needs a mutable reference to the ncvisual options, but for ncvisual_render a const reference is enough?
> 
> because i'm a great big stupid person, great catch, thanks homie! w00t w00t!

updated to be const

**Comment by dankamongmen** [comment]
if that downsize failure you referenced in the original commit is still happening, @joseluis , definitely let me know. otherwise, i think this is all good, and represents a great burst of sanity in ncdirect.

![Screenshot_2021-06-09_07-00-39](https://user-images.githubusercontent.com/143473/121343210-6d83ea00-c8f0-11eb-8061-a381b38edc2a.png)

left: non-interpolative right: bicubic default, both in direct mode

**Comment by joseluis** [comment]
> because i'm a great big stupid person, great catch, thanks homie! w00t w00t!

you know, you may be big, or even a person, but unless you consider stupid to work your heart out every day in this amazing piece of technology, you are not stupid by any means. Thanks homie to you man.

> updated to be const

the rust part too I see, thanks

**Comment by joseluis** [comment]
> if that downsize failure you referenced in the original commit is still happening, @joseluis , definitely let me know. 

Ok I'll have to create a minimal example first

**Comment by joseluis** [comment]
opened in #1751

**Comment by dankamongmen** [comment]
> > because i'm a great big stupid person, great catch, thanks homie! w00t w00t!
> 
> you know, you may be big, or even a person, but unless you consider stupid to work your heart out every day in this amazing piece of technology, you are not stupid by any means. Thanks homie to you man.

awww i just saw this and it made me tear up a little <3
