### ISSUE TITLE
Would blessed be a good python API to use for this project?

### ISSUE THREAD

**Issue by WSLUser** [dankamongmen/notcurses#1744]
https://github.com/jquast/blessed/i seems to be a good project to use for anything TUI related wrt python.  I would like to ask @dankamongmen and @igo95862 (who has added the python bindings here) what you think of this library and if it's practical for use here. It's designed for ncurses so it may help fill in some of the compatibility issues. I browsed through the project and the original source that it has forked from and while it could use some changes I see are not yet considered (either in the issues or PRs), it wouldn't be very difficult to update the library to fit the needs of this project if needed or improve it in general. Or maybe we could use a tweaked version of the project simplified for only what's needed in this project. Of course if we consider the current python bindings optimal for this project, we can forget about the library. 

This issue is raised merely to bring discussion and if an actionable item comes out of it, we can repurpose the issue for that (or create a new one).

**Comment by dankamongmen** [comment]
i mean, i don't understand how it would play a role here. it's a python core. if people want to write python, they can use it. i don't see any reason why you would want to write notcurses with a blessed backend. if there's functionality from blessed we want, let's implement it -- in the core.
