### ISSUE TITLE
ncvisual_render fails when downsizing an ncvisual 

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1751]
I've created a [minimal example](https://github.com/dankamongmen/notcurses/blob/master/rust/examples/issue-1751.rs)

**Comment by dankamongmen** [comment]
alright, let's run this down. not sure how we're still seeing failures here, but i'll get it worked out. thanks for the test case!

**Comment by dankamongmen** [comment]
immediately reproduced on kitty using tip of master:

```
Error: NcError { int: -1, msg: "NcVisual.render(Notcurses, &NcVisualOptions)" }
```

**Comment by dankamongmen** [comment]
hey @joseluis , when i run this, my terminal isn't properly reset. is there any rustish way you could get `notcurses_stop()` into the default exit path, so unless someone explicitly demands otherwise, doing the `foo()?` idiom calls it? i think that would serve your users well, if so.

**Comment by dankamongmen** [comment]
ok so you have `H` and `W`, and you set those up in your `ncvisual_options` as `leny` and `lenx`. That means "render through pixel H, W", but your resized image is only `H/2` and `W/2`. you could resolve this in two ways:

* use `H/2` and `W/2` in the `ncvisual_options`, or
* use 0 and 0 instead of explicit `H`/`W` at all

**Comment by dankamongmen** [comment]
confirmed that this fixes your problem:

```rust
diff --git rust/examples/issue-1751.rs rust/examples/issue-1751.rs
index 5e01423d4..4ec95fe97 100644
--- rust/examples/issue-1751.rs
+++ rust/examples/issue-1751.rs
@@ -9,7 +9,7 @@ fn main() -> NcResult<()> {
     // create a white rectangle
     let buffer = vec![255; H as usize * W as usize * 4];
     let v = NcVisual::from_rgba(buffer.as_slice(), H, W * 4, W)?;
-    let vo = NcVisualOptions::without_plane(0, 0, 0, 0, H, W, NCBLIT_PIXEL, 0, 0);
+    let vo = NcVisualOptions::without_plane(0, 0, 0, 0, H/2, W/2, NCBLIT_PIXEL, 0, 0);
 
     // BUG: render function fails when downsizing
     v.resize(H / 2, W / 2)?;
```

**Comment by dankamongmen** [comment]
btw, a Tip: this kind of thing has diagnostics, so if you set `loglevel` to `error` or higher, you'll get the error printed out to `stderr`.

**Comment by joseluis** [comment]
> hey @joseluis , when i run this, my terminal isn't properly reset. is there any rustish way you could get `notcurses_stop()` into the default exit path, so unless someone explicitly demands otherwise, doing the `foo()?` idiom calls it? i think that would serve your users well, if so.

@dankamongmen yeah well... I was thinking about that. This would be the Drop trait, that you can implement for a type *that you have created* in order to automatically run a destructor method when it goes out of scope.

I've [already implemented it](https://github.com/dankamongmen/notcurses-rs/blob/master/src/notcurses.rs#L13-L18) for the higher level rust bindings, for which I'm slowing designing the API. Since that type is created in the crate.

The problem is that in libnotcurses-sys crate I'm not creating new structures that wrap the C types, instead I'm [type aliasing](https://github.com/dankamongmen/notcurses/blob/master/rust/src/notcurses/mod.rs#L80-L82) them, and the disadvantage is in that case I can't implement Drop.

I don't remember all the trade-offs that made me settle with this decision, but I may try to revert it and see what I find.

> confirmed that this fixes your problem:

Aargh... thank you. Another blind spot of mine while using the API.

> ```rust
> let vo = NcVisualOptions::without_plane(0, 0, 0, 0, 0, 0, NCBLIT_PIXEL, 0, 0);
> ```

I'm not a fan of the verbose C API very much, that's why in the design of the API for `notcurses-rs` I'm trying to avoid the "functions with a lot of parameters" pattern, and the Options structures... and use the builder pattern instead. E.g.: 

[example/plane.rs](https://github.com/dankamongmen/notcurses-rs/blob/master/examples/plane.rs) (WIP)
```rust
let mut p1 = Plane::build().rows(20).cols(40).new_pile(&mut nc)?;
let mut p2 = Plane::build().rows(10).cols(10).y(2).x(3).in_pile(&mut p1)?;
```

**Comment by dankamongmen** [comment]
oh, completely agreed about the verbosity of the C, and that the rust decisions you've made are good ones

**Comment by dankamongmen** [comment]
> oh, completely agreed about the verbosity of the C, and that the rust decisions you've made are good ones

when the Universe was still young nobody had really thought of default parameters

**Comment by joseluis** [comment]
> when the Universe was still young nobody had really thought of default parameters

well, Rust doesn't have default parameters either so I guess we've come full circle :D
