### ISSUE TITLE
add undercurl as a style

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1758]
At least kitty and wezterm, and probably others, support undercurl. Add `NCSTYLE_UNDERCURL` and the necessary code to support it, where available.

**Comment by dankamongmen** [comment]
it looks like both wezterm and kitty are using `Smulx=\E[4\:%p1%dm`, and alacritty also has this defined, though not in the terminfo database entry *i* have for it, odd.

https://github.com/kovidgoyal/kitty/pull/3725
https://github.com/wez/wezterm/issues/415

**Comment by dankamongmen** [comment]
So it looks like underline and undercurl (and double underline) are mutually exclusive.

That's actually good, because we want to be able to color the underline etc., which there's no way to do through the `set_styles()` interface. BUT we can add a function to configure the current underline state...except where would we then put this in rendered mode? it makes sense as a per-`nccell` thing...but we only have 4 bits free in the `nccell`.

hrmmmm. hrmmmmmmmmmmm.

for direct mode, it's trivial, since we just need a single current state, which we just pass through.

**Comment by dankamongmen** [comment]
![2021-06-14-014502_1072x674_scrot](https://user-images.githubusercontent.com/143473/121844529-290e9a80-ccb2-11eb-934f-1ce7f694784f.png)

**Comment by WSLUser** [comment]
Not relevant at the moment but for awareness Windows Terminal supports underline and double underline. There's also a request to get all the Kitty extended underlines supported including undercurl: https://github.com/microsoft/terminal/issues/7228

**Comment by dankamongmen** [comment]
sweet! i hope to be compiling on Windows very soon.

does microsoft terminal run on anything but windows? if so, i can add support for it now.

**Comment by WSLUser** [comment]
No, most of the VT support comes from the open console (aka conhost). Most of the code should be portable to Windows Terminal though. Also you'd need to use a different UI framework first or use something like Uno. Don't want to contaminate this issue with anything unrelated but
