### ISSUE TITLE
New function ncvisual_from_rgb

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1767]
I belive it would be very handy to have an `ncvisual_from_rgb()` function to read rgb data from a buffer without the alpha byte, and apply the same alpha to all pixels, through an additional argument. With a signature like:

```c
API ALLOC struct ncvisual* ncvisual_from_rgb(const void* rgb, int rows,
                                              int rowstride, int cols, unsigned char alpha);
```

I'm encountering the case where having to interface with the output of other libraries that doesn't deal with alpha makes it somewhat cumbersome.

And maybe in that case it should also be added `ncvisual_from_bgr` for completion?

**Comment by dankamongmen** [comment]
I'm pretty sure I already added something like this in response to a request from dear @kaniini , let me go check...

**Comment by dankamongmen** [comment]
```c
// Supply an alpha value [0..255] to be applied throughout. linesize must be                               
// a multiple of 3 for this RGB data.                                                                      
API int ncblit_rgb_packed(const void* data, int linesize,                                                  
                          const struct ncvisual_options* vopts, int alpha);                                
                                                                                                           
// Supply an alpha value [0..255] to be applied throughout. linesize must be                               
// a multiple of 4 for this RGBx data.                                                                     
API int ncblit_rgb_loose(const void* data, int linesize,                                                   
                         const struct ncvisual_options* vopts, int alpha);                                 
```

so that looks like exactly what you want? minus the `bgr` completeness.

**Comment by dankamongmen** [comment]
oh this doesn't create a visual, though. ok, we can add

```c
ncvisual* ncvisual_from_rgb_packed(...);
ncvisual* ncvisual_from_rgb_loose(...);
```

and maybe

```c
ncvisual* ncvisual_from_bgr_packed(...);
ncvisual* ncvisual_from_bgr_loose(...);
```

does BGR really come up when you're not doing 32-bit words? i assumed that was a relic of endianness issues.

**Comment by joseluis** [comment]
I personally don't care about bgr at all. So maybe we can leave that out.

**Comment by joseluis** [comment]
Although if it's left out it will probably came again in the future by some else...

**Comment by dankamongmen** [comment]
I've defined the two RGB functions. need to add unit tests.

**Comment by dankamongmen** [comment]
hah, good thing i wrote that unit test, whoops!

**Comment by dankamongmen** [comment]
and that one, jfc
