### ISSUE TITLE
allow to render any pile to a buffer or a file

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1770]
Currently there's only notcurses_render_to_buffer and notcurses_render_to_file, which I presume work only on the standard pile.

**Comment by dankamongmen** [comment]
yeah. i don't think i've ever ended up using these, so their usefulness seemed questionable.

perhaps the thing to do is to add `ncpile_render_to_buffer()` and `ncpile_render_to_file()` and deprecate the existing two, for removal in ABI3.

**Comment by dankamongmen** [comment]
i've removed the Ncpp::Notcurses wrappers, as they'd be calling deprecated functions. I don't immediately see how to add them to Ncpp::Pile (and maybe they would go in Ncpp::Plane)? Ncpp::Pile looks awfully sus to me overall. these functions are unimportant enough that i'm just not gonna worry about the C++ right now.

**Comment by dankamongmen** [comment]
@igo95862 i commented out `Notcurses_render_to_buffer()` and `Notcurses_render_to_file()` with a FIXME (your CI caught the breakage, while mine did not -- odd!). sorry about that breakage; the fix ought hopefully be pretty obvious.

**Comment by igo95862** [comment]
>  while mine did not -- odd!

It not odd. Yours does not compile new python binds.

I will fix it this evening.
