### ISSUE TITLE
need an ncdirect_canget_cursor()

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1790]
`notcurses-tester` is breaking on FreeBSD because my terminfo database got blown away, and is not now advertising u7 support. We ought expose an `ncdirect_canget_cursor()`, a static inline atop the new `nccapabilities` structure. This raises a question: this will be (for now) predicated on the existence of the u7 terminfo entry. That means a `static inline` implementation would either:

* need this duplicated as a boolean in `nccapabilities`, or
* need it otherwise exposed from `struct tcache`

I don't particularly care to expose `tcache`, but duplication also seems undesirable. Perhaps this ought not be `static inline` after all? And maybe this ought also require being connected to an actual tty.

Either way, once this is present, wrap all tests calling `ncdirect_cursor_yx()` in `ncdirect_canget_cursor()`.

**Comment by joseluis** [comment]
@dankamongmen this make me wonder... why is this not a thing on full mode? if there are notcurses_cursor_enable|disable functions and plane cursor positioning...

**Comment by dankamongmen** [comment]
because we don't have any way to retrieve the cursor's position in rendered mode. in rendered mode, we control the output. the cursor (ought be) is exactly where we placed it.
