### ISSUE TITLE
maybe make the background of the new logo transparent

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1795]
So that it plays better with dark mode:

Right now with white background:
![image](https://user-images.githubusercontent.com/5832068/122637389-9c6b3e80-d0ee-11eb-913f-a4e34e12a8d8.png)

And with transparent background:
![image](https://user-images.githubusercontent.com/5832068/122637401-b73db300-d0ee-11eb-951e-57ead68b40c0.png)

my edited version of the logo is not perfect though, since there is a tiny whiteish border on the left and right parallelograms, but just as an idea:

![notcurses-logo-transparent](https://user-images.githubusercontent.com/5832068/122637480-3501be80-d0ef-11eb-93cd-b2b0fffa5bae.png)

**Comment by joseluis** [comment]
this thing is so small I think I'm just gonna close this to not distract from more important things...

**Comment by dankamongmen** [comment]
hah, i agree, but the guy who made it for me is going to do a vectorized version; i'll wait until then.
