### ISSUE TITLE
kitty no longer shows ncvisuals

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1796]
tried with the latest kitty version 21.1 and also 20.3, 21.1 and 19.3...

meanwhile xterm, alacritty and wezterm does show them.

**Comment by dankamongmen** [comment]
i am most certainly showing visuals in kitty.

![2021-06-19-195045_1072x1417_scrot](https://user-images.githubusercontent.com/143473/122658133-a8c7b980-d137-11eb-8538-3aa7309a7f96.png)

what is `notcurses-info` showing in terms of the "et al on..." line, and the "rgba pixel graphics supported" line?

**Comment by dankamongmen** [comment]
also, what version of kitty is this? i'm using some recent features and not yet checking the version, and that might be biting us here.

**Comment by dankamongmen** [comment]
ahhh you said you tried multiple versions of kitty.

ummm, hrmm. does `kitty +kitten icat path/to/some/image.png` work as expected?

**Comment by dankamongmen** [comment]
i've got this from `interp` in kitty right now

![2021-06-20-072631_1115x579_scrot](https://user-images.githubusercontent.com/143473/122672291-ddb82880-d198-11eb-8872-af7a949687c4.png)

**Comment by dankamongmen** [comment]
xterm looks good...

![2021-06-20-072735_884x556_scrot](https://user-images.githubusercontent.com/143473/122672316-02ac9b80-d199-11eb-91d7-508de92b52dd.png)

**Comment by dankamongmen** [comment]
alacritty looks good

![2021-06-20-072928_800x726_scrot](https://user-images.githubusercontent.com/143473/122672392-47d0cd80-d199-11eb-92b1-87762128c947.png)

**Comment by dankamongmen** [comment]
i don't know, man; you seem to have these catastrophic setup problems from time to time. let me know whether that `kitten` above works.

**Comment by joseluis** [comment]
It seems solved now. I recompiled with the current main and it does now show pixels

**Comment by dankamongmen** [comment]
yay! i was not looking forward to digging into that =D
