### ISSUE TITLE
extract terminal version from query responses

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1798]
While I don't really look forward to heuristics based off details like terminal version, if we want to e.g. support older versions of kitty, it will be necessary to do so (for instance, I'm freely using the C=1 functionality introduced in 0.20.0). when a terminal provides its version in response to a query, we ought go ahead and make that available to our `termdesc` logic. 

also, we ought document all the terminal queries and such that we send, and how we use the responses.

**Comment by dankamongmen** [comment]
Contour version is available following "contour " in the `XTVERSION` response.
XTerm version is available in parentheses following "XTerm" in the `XTVERSION` response.
Kitty version is available via a `XTGETTCAP` iirc.
WezTerm version is available following "Contour " in the `XTVERSION` response.

**Comment by kovidgoyal** [comment]
FYI I added XTVERSION support to kitty a while ago as well, https://github.com/kovidgoyal/kitty/commit/057084a70869296c5cec399868f19f3d0d792ea9

**Comment by dnkl** [comment]
> FYI I added XTVERSION support to kitty a while ago as well, kovidgoyal/kitty@057084a

Same for foot: https://codeberg.org/dnkl/foot/commit/c3274fd97e7469c0261a7cbd0d4f4095bf96ca1f

**Comment by dankamongmen** [comment]
> FYI I added XTVERSION support to kitty a while ago as well, [kovidgoyal/kitty@057084a](https://github.com/kovidgoyal/kitty/commit/057084a70869296c5cec399868f19f3d0d792ea9)

oooh nice i'll likely use this, great

**Comment by dankamongmen** [comment]
`notcurses 2.3.4 by nick black et al on XTerm 366`

sweet!

**Comment by dankamongmen** [comment]
ok, kitty added XTVERSION 6 days ago in 0.21.2, and foot seven days ago. so i'm going to go ahead and write version acquisition as it *was* supported, and if someone is using a new `XTVERSION`-capable instance, it'll get pulled out of there instead. hrmmm, which means i need be prepared for the version to be specified more than once.

**Comment by dankamongmen** [comment]
kitty version was `P+q6b697474792d71756572792d76657273696f6e` (at least according to `kitten query_terminal`), egads.

foot's version was in the secondary device attributes response, the query for which i actually just removed tonight due to it "not yielding any information of value"

i think i might just hope for newest versions from y'all, and use `XTVERSION` across the board

**Comment by dankamongmen** [comment]
`notcurses 2.3.4 by nick black et al on Contour 0.2.0-unreleased-master-96b8f89`

**Comment by dankamongmen** [comment]
recent kitty gives it to us like this, which means if we can get MLTerm to support `XTVERSION`, we ought be able to drop our `
XTGETTCAP[TN]` entirely:

`read(0, "\33]11;rgb:0000/2222/1111\33\\\33P>|kitty(0.21.1)\33\\\33`

**Comment by dankamongmen** [comment]
`notcurses 2.3.4 by nick black et al on Kitty 0.21.1`

**Comment by dankamongmen** [comment]
recent foot gives it to us like this

`33\\\33P>|foot(1.7.2-365-g7632e16)\33\\\33[?1`

**Comment by dankamongmen** [comment]
![2021-06-21-210905_1024x600_scrot](https://user-images.githubusercontent.com/143473/122846960-ef064f80-d2d4-11eb-9e9a-70e68af18e73.png)

**Comment by dankamongmen** [comment]
w00t alright!

**Comment by dankamongmen** [comment]
`notcurses 2.3.4 by nick black et al on WezTerm 20210613-233622-35b26767`
