### ISSUE TITLE
limit max bitmap height for xterm, in the geometry report by ncplane_pixelgeom

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1810]
I noticed no pixels were rendered when the terminal is maximized, so I've checked that the max bitmap width is limited to 1000 in the pixel geometry report, but not the height, so when height is greater than 1001 pixels are no longer rendered. (1001 pixels is 78 rows in my case, and still renders).

![image](https://user-images.githubusercontent.com/5832068/122964351-757b6980-d387-11eb-8f8a-903148a125fd.png)

**Comment by dankamongmen** [comment]
hrmmm, i thought it would get capped at 1001 (well 996 technically), which is what you would want, right?

**Comment by dankamongmen** [comment]
> hrmmm, i thought it would get capped at 1001 (well 996 technically), which is what you would want, right?

(i mean, clearly it's not, but that *is* what you would want?)

**Comment by joseluis** [comment]
I just want to be able to trust the max_bitmap_* fields so that it works in all terminals :smile:

**Comment by joseluis** [comment]
BTW I found the bug when finishing the [cpu stats :chart_with_upwards_trend: example](https://github.com/dankamongmen/notcurses-rs/blob/master/examples/plotters-cpustat.rs) on the hi-lvl rust wrappers, if you want to try it.

**Comment by dankamongmen** [comment]
> BTW I found the bug when finishing the [cpu stats chart_with_upwards_trend example](https://github.com/dankamongmen/notcurses-rs/blob/master/examples/plotters-cpustat.rs) on the hi-lvl rust wrappers, if you want to try it.

FUCKING SWEET

**Comment by dankamongmen** [comment]
so the issue here is it's saying you can do 1000x1014 but in reality you can only do 1000x1000?

**Comment by dankamongmen** [comment]
give that a spin

**Comment by dankamongmen** [comment]
if it looks like a solid fix, i think this is 2.3.5.

**Comment by dankamongmen** [comment]
did this hold for you, @joseluis ? if so, i'm closing this and cutting 2.3.5.

**Comment by joseluis** [comment]
> did this hold for you, @joseluis ? if so, i'm closing this and cutting 2.3.5.

yes @dankamongmen it does work for me, go ahead
