### ISSUE TITLE
kitty not showing pixels again (not a notcurses problem)

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1811]
I'm not sure whether this is a problem with notcurses, with kitty, with my system or everything at the same time. It seems kitty is not very reliable for me lately. Normally is the terminal that works best for pixels, except that every now and then it stops showing pixels completely.

I'm opening this issue basically hoping to find some hints to solve this...

running `notcurses-demo` for example makes kitty output many lines like these to stderr:
```
[173 18:43:14.622966] [PARSE ERROR] DCS sequence too long, truncating.
[173 18:43:14.623002] [PARSE ERROR] Unrecognized DCS code: 0x30
[173 18:43:14.624047] [PARSE ERROR] Unknown char after ESC: 0x5c
[173 18:43:23.775430] [PARSE ERROR] CSI code S has unsupported start modifier: S or end modifier: S
[173 18:43:23.775456] [PARSE ERROR] CSI code S has unsupported start modifier: S or end modifier: S
[173 18:43:23.775464] [PARSE ERROR] CSI code S has unsupported start modifier: S or end modifier: S
OSError: [Errno 22] Invalid argument: '/home/joseluis/.cache/kitty'
```

**Comment by dankamongmen** [comment]
> OSError: [Errno 22] Invalid argument: '/home/joseluis/.cache/kitty'

it's this that's breaking things. https://github.com/dankamongmen/notcurses/issues/1653 goes through how i debugged one of these. if you're getting this error, nothing's going to be able to display images in your kitty environment.

**Comment by dankamongmen** [comment]
i edited the title because it was instilling despondency into my heart each time i saw it, and then i'd remember what this was

**Comment by dankamongmen** [comment]
Though I ought add that Kitty has been broken for versions < 0.20.0 since I added `C=1` maybe a month ago, and only got fixed tonight.

**Comment by dankamongmen** [comment]
any idea what was up?

**Comment by joseluis** [comment]
don't know what broke it, but the solution was to set that global env var specifying the desired cache directory path, and it had to be set at /etc/... , to be loaded before my user local env context.
