### ISSUE TITLE
notcurses_cursor_enable ignores position in version 2.3.4

### ISSUE THREAD

**Issue by schottstaedt** [dankamongmen/notcurses#1812]
In notcurses 2.3.4 (as opposed to 2.2.2 -- I haven't tried other versions), notcurses_cursor_enable just displays the cursor at 0,0.  (Actually in LXTerminal I can't see any cursor, but that may be my fault).  Here is a program that shows the difference:

#include <notcurses/notcurses.h>
#include <unistd.h>

int main(int argc, char **arg)
{
  int x, y;
  struct notcurses *nc;
  nc = notcurses_core_init(NULL, NULL);
  notcurses_cursor_enable(nc, 0, 12);
  sleep(1);
  notcurses_cursor_enable(nc, 0, 4);
  notcurses_refresh(nc, &x, &y);
  sleep(1);
  notcurses_stop(nc);
}

In 2.2.2 the cursor starts at 0,12, then moves to 0,4, but in 2.3.4 it sits at 0,0.

**Comment by dankamongmen** [comment]
on it asap, should be within the next few hours. thanks for the report!

**Comment by dankamongmen** [comment]
i think i've got a fix. 2.3.5 is probably coming out tonight or early tomorrow, so you won't have a long wait.

**Comment by dankamongmen** [comment]
after purging a truly poorly-considered conditional, my basic tests are working once more. i'll hit it a bit more, but hopefully that was the issue.

**Comment by schottstaedt** [comment]
Thanks very much!
