### ISSUE TITLE
move away from sgr

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1818]
i don't much care for `sgr`. it takes a galaxy worth of parameters, many of them confusing and unlikely imho to be used. it sets all other styles, except when it doesn't. likewise, `sgr0` unsets other styles, and even colors (sometimes). when possible, i say we ought do granular changes to styles.

i think almost all styles can be individually turned *on*, but less so *off*.

**Comment by dankamongmen** [comment]
along with this, we should probably junk a few styles, or at the very least simulate them with colors:

* `NCSTYLE_DIM`: not a vt100 thing, not on linux console, can simulate with rgb or rgbccc
* `NCSTYLE_STANDOUT`: can be synthesized, not a real mode
* `NCSTYLE_BLINK`: not widely supported, can be simulated with `_pulse()`, is annoying
* `NCSTYLE_INVIS`: what's the use case here, exactly?
* `NCSTYLE_PROTECT`: we already don't support this
* `NCSTYLE_REVERSE`: can be synthesized with colors, right? does this work with transparency? probably not?

if we threw out all of these, or even all save one, we could restrict the stylebits to 8 bits, recovering a byte in the styleword, which could surely be put to good use -- color for the undercurl, perhaps?

**Comment by dankamongmen** [comment]
heads up to @joseluis and @igo95862

**Comment by dankamongmen** [comment]
alright, all we have left are `UNDERCURL`, `UNDERLINE`, `BOLD`, `ITALIC`, and `STRUCK`. too bad we can't get rid of one more and be down to an even 4 bits =] (well, maybe we could merge UNDERCURL and UNDERLINE, but we'd just need a bit elsewhere to distinguish them). we could perhaps use 9 of the leftover stylemask bits for underline/curl coloring, giving us 3 bits per channel. if we put an undercurl/underline distinguishing bit in the channels (easily enough done), we'd have 12 bits in the stylemask, and could go to 4 bits per channel, almost 6% of the color space lol.

**Comment by dankamongmen** [comment]
so i think at this point we could drop `sgr`, right? falling back to it, perhaps, if no `bold` or `smul` capabilities exist, but `sgr` does?

**Comment by joseluis** [comment]
> along with this, we should probably junk a few styles, or at the very least simulate them with colors:

I liked the handiness of having reverse & blink available as text styles... How would the alternative/simulation be? Does custom styling need to be implemented manually by users using channels and... timers?

**Comment by dankamongmen** [comment]
> I liked the handiness of having reverse & blink available as text styles... How would the alternative/simulation be? Does custom styling need to be implemented manually by users using channels and... timers?

reverse you just switch the background and foreground, easy peasy.

blink isn't very widely supported:

kitty: n
alacritty: claims support, doesn't seem to work
vte: y
contour: claims support, doesn't seem to work
foot: y
xterm: y
mlterm: y

ok, wider support than i expected.

there is of course `ncplane_pulse()`, which IMHO looks better than blinking =]

i can put blink back if we want it. that doesn't mean we can't move off SGR.

**Comment by dankamongmen** [comment]
as part of this, i want `term_setstyles()` from direct and rendered mode united.

**Comment by dankamongmen** [comment]
hrmmm, it looks like '\e[22m` turns bold off, but has no terminfo entry

**Comment by dankamongmen** [comment]
and `\e[25m` shuts off blink, huzzah. I've added back `NCSTYLE_BLINK`.

**Comment by joseluis** [comment]
> and `\e[25m` shuts off blink, huzzah. I've added back `NCSTYLE_BLINK`.

After playing with it, I'm changing my opinion on its usefullness. I think you were right to remove it.

**Comment by dankamongmen** [comment]
> > and `\e[25m` shuts off blink, huzzah. I've added back `NCSTYLE_BLINK`.
> 
> After playing with it, I'm changing my opinion on its usefullness. I think you were right to remove it.

blink? yeah, a lot of terminals claim support and then don't actually implement it. i would not be sad to see it go.

right now we have the following occupancy of the 16 style bits:

```c
#define NCSTYLE_MASK      0xffffu                                              
#define NCSTYLE_ITALIC    0x0020u                                              
#define NCSTYLE_UNDERLINE 0x0010u                                              
#define NCSTYLE_UNDERCURL 0x0008u                                              
#define NCSTYLE_BOLD      0x0004u                                              
#define NCSTYLE_STRUCK    0x0002u                                              
#define NCSTYLE_BLINK     0x0001u                                              
#define NCSTYLE_NONE      0        
```

so we're using six, leaving ten free. we have four free bits in the channels, for a total of fourteen. if we recovered the BLINK bit, we'd have fifteen. the next thing that we might want to use these precious bits for is coloring of the underline, available in several modern terminals. with 15 bits, we'd have an even five bits per RGB channel for the underline....at the cost of every free bit we have. that's 32 intervals of 8 each for each channel, perhaps rather more richness than an underline needs.

i'm uncomfortable with the idea of devoting all remaining free space to underline coloring, so i'd probably hold it at 12. so losing BLINK doesn't gain us much at this point. with that said, i'd rather remove it now rather than later, especially post-abi3.

**Comment by dankamongmen** [comment]
alternatively, we could get rid of blink and have those 15 bits, and use 6 to support 10-bit color, and 9 to provide 3-bit color to the underlines. no terminals currently support 10-bit color, nor have i seen any plans to do so.

**Comment by dankamongmen** [comment]
i just spoke with @wez of WezTerm, and he said 10-bit color is not out of the question. so i think 3-bit underline color and reserving six bits for a 10-bit color future is the way to go here. if it never materializes, having six bits in our quiver is no bad thing. goodbye, BLINK!

**Comment by joseluis** [comment]
Good, I agree this seems like the most sensible decision. 

But what would be the internal mechanics that goes from the 3 bit color store there to the real color shown? I want to understand what kind of control are we going to have. Is it an interpolation to the nearest 8bit color?

**Comment by dankamongmen** [comment]
> Good, I agree this seems like the most sensible decision.
> 
> But what would be the internal mechanics that goes from the 3 bit color store there to the real color shown? I want to understand what kind of control are we going to have. Is it an interpolation to the nearest 8bit color?

well on a 10-bit terminal, it would go directly through. i'd almost certainly restructure the `nccell` structure so that the 30RGB bits of each channel are contiguous, and aligned within bytes however 10bpc RGBA is structured by computer vision/imaging libraries; we'll also want to see what kind of escape sequence arises to handle this.

**Comment by joseluis** [comment]
I mean the 3-bit underline color on 8 bit terminals. How each 3-bit color will be translated to 8-bit for rendering? I'm trying to picture how it will work to have 8 colors for the underlines and how it relates to the rest (rgb, palette, sixel quantization...)

**Comment by dankamongmen** [comment]
i mean the obvious implementation is to shift the three bits five bits left, defining 8 equally-spaced intervals that then either end with 5 zeros or 5 ones, each 32-wide. we could use a better conversion, one with e.g. gamma correction.
