### ISSUE TITLE
ubuntu test action has been failing due to missing package

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1819]
Since at least last evening, the ubuntu test github action has been failing, due to some pulse package it can't find. Will we need be keeping this manually up to date? If not, when ought it be expected to recover?

https://github.com/dankamongmen/notcurses/runs/2900051668 is an example

**Comment by igo95862** [comment]
Should be fixed now: https://github.com/dankamongmen/notcurses/actions/runs/967072404

Apparently `apt update` should have been run before installing packages.

**Comment by igo95862** [comment]
@dankamongmen Seems like the issue has been fixed
