### ISSUE TITLE
add PNG-encoding capability for efficient graphics transmission

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1821]
I wouldn't doubt encoding a PNG, sending it, and having kitty decode it is faster than sending raw RGBA (that's the whole point of #1695). I cannot overstate my lack of interest in writing a PNG encoder, so let's get one.

I'm thinking we want this even in the no-multimedia-layer case, since you can still make graphics from supplied RGBA etc. (i.e. you don't need to open and decode a file), and libpng is much, much smaller than ffmpeg/OIIO. With that said, OIIO can definitely export PNGs, and ffmpeg probably can as well. We might want to use those "native" capabilities when those libraries are present. For now, though, just find a good, small, fast png library -- or say fuck it, and use libpng blindly -- and write one bit of code for that.

Wait until we've done the initial benchmarking in #1695 before pursuing this.

**Comment by dankamongmen** [comment]
as seen in #1695, initial benchmarking was positive. let's proceed on this.

**Comment by dankamongmen** [comment]
This is also going to be pretty much necessary for #1420, which doesn't appear to take any kind of bulk inline data.

@gnachman, i looked over the protocol documentation, and have a few questions if you wouldn't mind.

**Comment by gnachman** [comment]
Happy to help.

**Comment by dankamongmen** [comment]
> Happy to help.

you're a champion. i asked some questions over in #1420; please reply at your convenience and leisure.

**Comment by dankamongmen** [comment]
we now build a PNG from an arbitrary `ncvisual` with the routines in src/lib/png.c.

**Comment by dankamongmen** [comment]
we'll need update our Alpine and Fedora builders to include zlib development packages. when we do, update the fedora-style deps in `INSTALL.md` as well.

**Comment by spinicist** [comment]
Hi, was this functionality removed? I can no longer see a `src/lib/png.c`. I tried compiling notcurses without ffmpeg or OpenImageIO, and when I try to blit an ncvisual_from_rgba I see characters printed to the terminal (in Kitty):
```
^[[1;1R^[P>|kitty(0.29.2)^[\^[P1+r544e=787465726d2d6b69747479^[\^[P0+r524742^[\^[P1+r687061=5c455b2569257031256447^[\^[[>1;4000;29c^[]4;0;rgb:0000/0000/0000^
```
etc...

**Comment by dankamongmen** [comment]
it was definitely not removed. all that code was moved to `sprite.c`. what terminal are you using?

**Comment by spinicist** [comment]
I tried both Kitty and the MacOS terminal. Same problem (although slightly different characters at the beginning).

My code worked with notcurses installed via Homebrew. @quyykk kindly wrote a vcpkg port of notcurses that I tried to use https://github.com/microsoft/vcpkg/pull/33655 and then sadly this problem occurred.

Would you prefer it if I opened another issue and what other information can I provide?

**Comment by spinicist** [comment]
To add that after some messing around, I managed to make vcpkg compile the notcurses binaries. `notcurses-demo` demonstrates the same behaviour - it simply prints the following to Kitty:
```
R>|kitty(0.30.0)1+r544e=787465726d2d6b697474790+r5247421+r687061=5c455b25692570312564471;4000;30c4;0;rgb:0000/0000/00004;1;rgb:cccc/0404/03034;2;rgb:1919/cbcb/00004;3;rgb:cece/cbcb/00004;4;rgb:0d0d/7373/cccc4;5;rgb:cbcb/1e1e/d1d14;6;rgb:0d0d/cdcd/cdcd4;7;rgb:dddd/dddd/dddd4;8;rgb:7676/7676/76764;9;rgb:f2f2/2020/1f1f4;10;rgb:2323/fdfd/00004;11;rgb:ffff/fdfd/00004;12;rgb:1a1a/8f8f/ffff4;13;rgb:fdfd/2828/ffff4;14;rgb:1414/ffff/ffff4;15;rgb:ffff/ffff/ffff4;16;rgb:0000/0000/00004;17;rgb:0000/0000/5f5f4;18;rgb:0000/0000/87874;19;rgb:0000/0000/afaf4;20;rgb:0000/0000/d7d74;21;rgb:0000/0000/ffff4;22;rgb:0000/5f5f/00004;23;rgb:0000/5f5f/5f5f4;24;rgb:0000/5f5f/87874;25;rgb:0000/5f5f/afaf4;26;rgb:0000/5f5f/d7d74;27;rgb:0000/5f5f/ffff4;28;rgb:0000/8787/00004;29;rgb:0000/8787/5f5f4;30;rgb:0000/8787/87874;31;rgb:0000/8787/afaf4;32;rgb:0000/8787/d7d74;33;rgb:0000/8787/f
```
