### ISSUE TITLE
write spec for zero-copy pty

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1822]
Copying sucks rhino dick (almost all the time), as does in-band signaling (most of the time). Ptys have served well for fifty years, but it's time for something better.

Given the adoption of application-synchronized updates (see #1813), we're already framing a set of atomic writes over the pty. The obvious next step is moving the bulk data to a zero-copy shared memory, and restricting the pty to ASU updates and queries+replies. Essentially, we're separating out a fast data plane and a slower control plane. Even if we can't run a zero-copy `mmap` over ssh (yet), this still has the big advantage that the standard Williams automaton needn't run on the data plane IMHO, meaning an end to base64-encoding of our bulkiest data (and thus a 25% bandwidth savings over any scheme employing base64).

I'm thinking there will be a new capability to query using Device Attributes, or DECRQM $420, or some new query. Either way, it ought be exposed as a terminfo extension capability (and thus maybe shouldn't be in DevAttr). If the capability is present, we can use a new control sequence to open a data plane (nothing here is a final suggestion):

`DECDANKREQ` = DEC something ; Pi ; String ST
Pi = 0 => Local file / shared memory segment
       1 => `AF_UNIX` socket
String: path accessible by terminal process

The file SHOULD NOT have non-volatile backing, but needn't be true SysV shared memory (and probably shouldn't). This file SHOULD be large enough to hold any single output frame (but a frame larger than the file can be spilled, see below). No more data can be queued at any given time than the size of this file in bytes. This doesn't apply to a domain socket.

`AF_UNIX` sockets can be forwarded over SSH since OpenSSH 6.7; I haven't worked out the exact mechanics yet, but ideally this would provide a fast dataplane mechanism for remote clients.

If, at any time following receipt of `DECDANKREQ`, the terminal encounters an error reading from the dataplane, it MUST write an error to the pty, and stop using the plane. A `SIGWINCH` SHOULD be delivered after this error is written. The error should take the form of a proper control sequence `DECDANKRPT`.

We add a new escape, Frame Ready. Frame Ready takes the form

`DECSOSODANK` = DEC something ; Pi z
Pi = N > 0 => length of frame in bytes up to 2**31
       0 => drop the data plane (henceforth a `DECNODANK`), responds with `DECDANKRPT` with `Ps=0`
Remember, Pi is written as an ascii number, and legal values could thus be up to 10 bytes (for a 1GB+ frame)

`DECDANKRPT` = DEC whatever ; Pi ; Ps ST
Pi = number of frames acted upon (*read **and** displayed*) from this dankchannel
Ps = code for why it's being torn down
Ps = 0 = processed a `DECNODANK`
     = 1 = timeout (can only happen on socket or maybe if using volatile shared memory)
     = 2 = frame spec too large (bigger than min of shared memory size and 2**31)
     = 3 = other I/O error while reading
     = 4 = read length didn't match advertised length
     = 5 = screen/cell geometry changed (maybe)

The terminal MAY enforce an arbitrary timeout on receipt of advertised frames from the dataplane.

While the terminal has a dataplane active, it is free to process pty writes as normal. It never processes dataplane input until directed to by a Frame Ready message. At that point, it goes to read the specified number of bytes plus 4, which all ought be available (they might not in the case of a UNIX domain socket over a network, but they ought be arriving forthrightly). Until it has read the specified number of bytes, it MUST not act on any newer messages, except that it MAY act on a `DECNODANK` where `Pi=0`. Other input on the pty MUST NOT be displayed until preceding Frames are displayed, and SHOULD be made visible before any subsequent Frames. It MAY read the control messages to clear the receive queue and possibly process `DECNODANK` out-of-band. When the data path is dropped due to `DECNODANK`, a `DECDANKRPT` ought be sent like any other situation. The terminal MUST NOT read beyond the data explicitly accounted for via Frame Ready messages.

When using shared memory, there is a four-byte in-band header, indicating the length of the frame. This value MUST match the advertised length from the Frame Ready, or else the terminal sends a `DECDANKRPT` with `Ps=4` (and stops using the dataplane). If it does not match, the terminal MAY act on the mismatch before the remaining Frame has been read in its entirety. Once the frame has been *read* (not necessarily *displayed*), if shared memory is being used, the terminal must set the MSB of this header word to 1 (the word is treated as little-endian by all parties). The client MUST NOT overwrite the header or payload of an advertised Frame until it has thus been ACKed by the terminal. Note that the size of the shared memory is thus an upper limit on the amount of data in flight at one time; take Little's Law into account when sizing the shared memory. A recommended size is 4GB (note that the entire shared memory *need not* be resident). This SHOULD somehow be controllable by the user, probably, but it MUST NOT be required configuration. *note: how does the client efficiently detect this ACK? remember, the shared memory might be operating over a network mount, so local signals and process-shared semaphores etc. won't fly*

Frames SHOULD be treated as atomic updates akin to application-synchronized updates.

This system could admit multiple data paths, but I can't think of any great reason to. I guess you could write multiple frames out in parallel, serializing on the Frame Readys? I'd argue at that point that you're writing too many goddamned frames--there's no point in overwhelming the terminal.

Will there only be one UNIX socket possible per ssh connection? That seems lame. If so, how do we deal with multiple processes potentially trying to use it? This is fundamentally worse than multiple clients in an pure byte-streaming setup, as their Frame Readys could get all overlapped and fucked.

I'm thinking that maybe we drop the dataplane whenever we get a geometry (cell or window) change. I kinda wish that `SIGWINCH` blew away my outstanding output somehow, or at least let me reliably do so. It of course can't, but we're starting afresh. If the geometry changes, frames en route simply don't possibly seem valid (unless they're provably within the new region, but even then you have potential `am` (in the terminfo sense) weirdness). And remember, you get a frame count in the `DECDANKRPT`, so you can scoop any messages you wanted to retransmit out of the dataplane and queue them back up, or otherwise alter them¹.

that's enough for now, i think.

this is all very raw, but RFC. i'd be interested in feedback from @klamonte, @dknl, @kovidgoyal, the usual gang. i doubt @ThomasDickey is interested in such radical departures from the norm, but his feedback would obviously be worth its weight in gold.

¹ Hell, part of me wants to say "drop the data plane whenever some stupid console message gets crapped all over my visible area, invalidating my idea of what's there", but you don't destroy earth's sun in one day.

**Comment by dankamongmen** [comment]
so right now i assemble all my writes and crap into a POSIX memstream, then dump that into a kernel buffer for the pipe (1 copy), and then the emulator must read that from the kernel buffer (1 copy, 2 total). instead, this allows me to assemble directly into the ringbuffer, which is already mmap()ed into the terminal's address space. it can then operate directly on the ringbuffer for 0 wholesale copies. i like it.

one problem is if you're spooling out into the ringbuffer, but end up with a frame bigger than 2GB (why are your frames so large?). but that's no problem -- zorch your spooled data thus far onto the pty, and finish there ("spilling", as mentioned above). it's no slower than before. you never send a Frame Ready before you're done (unlike Begin ASU), so the data written thus far couldn't have been used yet. your next frame starts where the aborted one did. ride that sweet sweet ringbuffer.

**Comment by kovidgoyal** [comment]
The major problem with this is, as always, SSH. While you *can* forward
sockets over ssh, that has to be done at the time the connection is
established, it cannot be done by a client running inside a pty
allocated by ssh, at least as far as I know, would love to be proven
wrong.

**Comment by dankamongmen** [comment]
We'll need some way of specifying what control sequences belong in the data plane. In Notcurses, I differentiate between escapes I write to the controlling terminal and ones I write to standard out. 

> The major problem with this is, as always, SSH. While you _can_ forward
> sockets over ssh, that has to be done at the time the connection is
> established, it cannot be done by a client running inside a pty
> allocated by ssh, at least as far as I know, would love to be proven
> wrong.

yep, but this can be done via a wrapper ala `ssh-agent`. getting such a wrapper into distro user profiles is something i can imagine happening.

**Comment by dankamongmen** [comment]
> yep, but this can be done via a wrapper ala `ssh-agent`. getting such a wrapper into distro user profiles is something i can imagine happening.

or maybe people have to run it for themselves at first if they care, as i did ssh-agent for what feels like a decade. but even if it meant gently nudging N distros to do something (once a good solution was determined), that's easier than nudging even just N terminal authors -- i've been doing plenty of both lately =]. distros are large groups with documented processes etc, and in the end the user can, again, do it themselves. but even if the remote scheme was a catch-as-catch-can affair, there's something to be said for a reliable local solution imho.

i came up with the drop-dataplane-on-geometry-change idea as an afterthought, but hell, just that would make it worthwhile to me (see `DECDANKRPT` `Ps=5`)

**Comment by kovidgoyal** [comment]
On Thu, Jun 24, 2021 at 01:49:32AM -0700, Nick Black wrote:
> yep, but this can be done via a wrapper ala `ssh-agent`. getting such a wrapper into distro user profiles is something i can imagine happening.

Not sure I follow. Say I ssh into myserver from bash running inside
kitty, like this:

ssh myserver

Then I run some program that wants to display images, like this:

dancing-dank

How is dancing-dank going to open a forwarded socket to the original
machine? Keeping in mind that I could actually have done something like

ssh myserver-gateway
ssh myserver  # run on myserver-gateway

to end up on myserver.

**Comment by kovidgoyal** [comment]
On Thu, Jun 24, 2021 at 01:54:17AM -0700, Nick Black wrote:
> > yep, but this can be done via a wrapper ala `ssh-agent`. getting such a wrapper into distro user profiles is something i can imagine happening.
> 
> or maybe people have to run it for themselves at first if they care, as i did ssh-agent for what feels like a decade. but even if it meant gently nudging N distros to do something (once a good solution was determined), that's easier than nudging even just N terminal authors -

🤣 World peace is easier than nudging N terminal authors to do anything.

> - i've been doing plenty of both lately =]. distros are large groups with documented processes etc, and in the end the user can, again, do it themselves. but even if the remote scheme was a catch-as-catch-can affair, there's something to be said for a reliable local solution imho.
> 
> i came up with the drop-dataplane-on-geometry-change idea as an afterthought, but hell, just that would make it worthwhile to me (see `DECDANKRPT` `Ps=5`)

If we are going to effectively restrict this to local transmission only,
why not just use the existing design in the kitty graphics protocol for
local transmission?

**Comment by dankamongmen** [comment]
if anyone ever has interest in implementing this or something like it, comment here. closing until then.
