### ISSUE TITLE
make rendered mode easier to use in a shell environment

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1823]
direct mode and rendered mode are at heart differentiated by whether output is generated outside of notcurses.

with that said, we could do a lot to make rendered mode more useful in a traditional scrolling shell environment. i'm basically thinking some combination of:

* don't use the alternate screen
* don't set a base cell that draws over all the screen (don't lose preexisting text above us)
* initialize the virtual cursor on the standard plane to wherever it was at program start
* set the standard plane to scroll
* at exit, cursor is placed after the last output
* [profit]

i don't think this needs to be a `notcurses_core_init()` option, and probably shouldn't, but it ought at least be tested and documented, and some examples written, and rough spots identified and ironed out.

**Comment by dankamongmen** [comment]
maybe plot this out with the work i'm doing on `notcurses-info`. i'd like to generate all that output in a notcurses rendered mode context, but have it usable in the shell.

**Comment by dankamongmen** [comment]
i think maybe `NCOPTION_PRESERVE_CURSOR` would be a satisfactory solution to cursor placement on both startup and shutdown, and is the right way to do that. the only time we don't know the cursor location in rendered mode is startup, and this closes that hole (when we want to) without a new genrally-useless function.

**Comment by dankamongmen** [comment]
the banners need be integrated into this. sample the cursor *after* the intro banner is printed.

**Comment by dankamongmen** [comment]
so what happens when we, say, create an `ncselector` in this configuration? i think we'd want it displayed, causing scrolling if necessary. but we need it to stay coherent and self-contained. well, that points to one and only one solution: a plane bound to a scrolling plane is affected by the the latter's virtual line number. exciting! but dangerous!

**Comment by dankamongmen** [comment]
But that brings up a good point--for this to work, scrolling on the standard plane has to be paired with an actual scroll of the visible area.

**Comment by dankamongmen** [comment]
Looks like you can already set the standard plane's scrolling mode, good good.

**Comment by dankamongmen** [comment]
ok, getting there! we have the option implemented. we need to check it on shutdown, and if it's set, place the cursor at the logical row based on the standard plane. we need bump the cursor down if we print init banners. and i think that's it!

**Comment by dankamongmen** [comment]
hot damn looks to be working perfectly

![2021-06-24-183955_1072x1417_scrot](https://user-images.githubusercontent.com/143473/123341206-94126980-d51b-11eb-94d6-f55e2555cd70.png)

this is big!

**Comment by dankamongmen** [comment]
@joseluis , you'll want to be aware of this, i think

**Comment by dankamongmen** [comment]
only problem left is that we always put the cursor at the bottom at the end of rendered mode, which fucks us up when we're not starting at the bottom. need to check for `NCOPTIONS_PRESERVE_CURSOR` there.

**Comment by dankamongmen** [comment]
oh, we probably ought use the `notcurses->cursor_{y,x}` instead of inventing new ones down in the termdesc stack.

**Comment by dankamongmen** [comment]
got that handled. only remaining issue is accounting for init banner relative to initial cursor placement.

**Comment by dankamongmen** [comment]
![2021-06-24-185402_1072x1417_scrot](https://user-images.githubusercontent.com/143473/123342333-8e1d8800-d51d-11eb-93ef-0f44c2cb9961.png)

yes!

**Comment by dankamongmen** [comment]
gotta knock out some unit test breakage, and test te hell out of this, but **sweet**!

**Comment by joseluis** [comment]
@dankamongmen is this only going to work with the standard plane?

I'm trying to think of the best way to use this with the hi-lvl rust wrappers that don't have the concept of the standard plane...

**Comment by dankamongmen** [comment]
> @dankamongmen is this only going to work with the standard plane?
> I'm trying to think of the best way to use this with the hi-lvl rust wrappers that don't have the concept of the standard plane...

hrmmmmmmmmm. so this feature isn't all the way there yet -- i haven't yet developed anything very serious with it (just `notcurses-info`), and i'm sure it might change a little. for one, i haven't yet locked down how extra planes will interact, just some vague thoughts about "planes bound to a scolling plane ought scroll". but i think the latter might be enough -- need to experiment.

so right now, i'd think that via whatever mechanism you allow this mode to be entered, it needs to internally mark the standard plane as scrolling, and do the other steps outlined above. those needn't be exposed to the user. and what i think is going to happen is that when you have a plane bound to a scrolling standard plane, and that former plane goes beyond the bottom of the visual area at render time, scrolling will encompass said plane, not just the standard plane. so it all falls out. i just need to make sure that works properly. does that make any sense?

**Comment by dankamongmen** [comment]
![2021-06-26-180335_1072x1417_scrot](https://user-images.githubusercontent.com/143473/123526893-d74e1300-d6a8-11eb-854b-7ff12c1b88de.png)

**Comment by joseluis** [comment]
yes it makes sense.

So I guess I could internally get the cursor position from the standard plane, duplicate it, move it to its own pile, enable scrolling, and work over it. right?

**Comment by joseluis** [comment]
BTW the output of `notcurses-info` appears for me like this:
![image](https://user-images.githubusercontent.com/5832068/123528868-6da32880-d6eb-11eb-8738-d68ad057c842.png)

I'm using `--version`: `wezterm 20210618-221225-e3fdef7f`.

Before the colors commits  it was like this:
![image](https://user-images.githubusercontent.com/5832068/123528887-8dd2e780-d6eb-11eb-9b4e-9f3949d72847.png)

**Comment by dankamongmen** [comment]
> BTW the output of `notcurses-info` appears for me like this:
> I'm using `--version`: `wezterm 20210618-221225-e3fdef7f`.

sacre bleu! sounds like i need dig out the laptop. thanks for the heads-up!

**Comment by dankamongmen** [comment]
> So I guess I could internally get the cursor position from the standard plane, duplicate it, move it to its own pile, enable scrolling, and work over it. right?

hrmmmm i see a problem here. you presumably would want to be writing arbitrarily much data to this secondary plane, and having the screen scroll with it. so normally you could just set *that* plane scrolling, and it would do exactly that -- but it *wouldn't* interact with preexisting text, etc. because we need to truly scroll the screen, and normally we just logically scroll within the plane. so no, that wouldn't work, at least the way i'm seeing this working. hrmm.

it would work if you moved the secondary plane down a row each time you wanted a true screen scroll, but that sounds difficult to know -- i'm trying to make this largely no-effort for the user. hrmmmmmmmmmmmm.

**Comment by joseluis** [comment]
> it would work if you moved the secondary plane down a row each time you wanted a true screen scroll, but that sounds difficult to know -- i'm trying to make this largely no-effort for the user. hrmmmmmmmmmmmm.

@dankamongmen is there a specific thread I should be monitoring for this topic?

**Comment by dankamongmen** [comment]
> @dankamongmen is there a specific thread I should be monitoring for this topic?

#1883 is probably where remaining design will be going on, feel encouraged to chime in
