### ISSUE TITLE
get nix package up to date

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1833]
NixOS is currently shipping 2.2.4. released early in March. When we get 2.3.7 out, let's go ahead and encourage an update with a friendly PR.

**Comment by dankamongmen** [comment]
https://github.com/NixOS/nixpkgs/pull/129499

**Comment by Mic92** [comment]
merged.

**Comment by dankamongmen** [comment]
> merged.

thanks much homie!
