### ISSUE TITLE
use SM-based ASU escapes

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1850]
> CSI Pm h  Set Mode (SM).
            Ps = 2  ⇒  Keyboard Action Mode (KAM).
            Ps = 4  ⇒  Insert Mode (IRM).
            Ps = 1 2  ⇒  Send/receive (SRM).
            Ps = 2 0  ⇒  Automatic Newline (LNM).

2026 is the ASU mode `Ps` when it's advertised in discovery, see #1845.

**Comment by dankamongmen** [comment]
> CSI Pm l  Reset Mode (RM).
            Ps = 2  ⇒  Keyboard Action Mode (KAM).
            Ps = 4  ⇒  Replace Mode (IRM).
            Ps = 1 2  ⇒  Send/receive (SRM).
            Ps = 2 0  ⇒  Normal Linefeed (LNM).

**Comment by dankamongmen** [comment]
we're using ?2026[hl] when it is advertised, and setting up DCS using heuristics. i've verified that we send 2026h/2026l in foot and contour. we send DCS to kitty and alacritty. i've removed VTE heuristics for ASU, due to it not actually doing anything with them.

i think this is all straight now. thanks @dnkl  and @kovidgoyal for clearing this up!

**Comment by WSLUser** [comment]
having just looked at this issue for Windows terminal when searching for another issue, I found my way here. From what I understand, DCS shouldn't be encouraged for this particular sequence and rather the 2026. Are you doing anything to choose usage of 2026 over DCS if both are supported by a terminal? Iterm2 for example, also recently added support for 2026, so it would be better to ensure one mode wins over the other.

**Comment by dankamongmen** [comment]
> having just looked at this issue for Windows terminal when searching for another issue, I found my way here. From what I understand, DCS shouldn't be encouraged for this particular sequence and rather the 2026. Are you doing anything to choose usage of 2026 over DCS if both are supported by a terminal? Iterm2 for example, also recently added support for 2026, so it would be better to ensure one mode wins over the other.

yes, if 2026 is advertised, i always use it (and i query for it on everything but a linux console).
