### ISSUE TITLE
large chunks of kitty graphics escapes are showing up on output

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1864]
Every so often -- maybe once every other `xray` run -- I'm seeing large chunks of base64-encoded text dumped to the output when running Kitty. I think this started around the time we got Synchronized Updates going. The presence of base64 indicates graphics, which would generally trigger SUs -- is it possible we're hitting some Kitty SU timeout that interrupts the control sequence? I would expect that hitting such a timeout would allow information to continue coming in within a given escape, but maybe there's a bug?

See if we can reproduce this with SUs disabled. If so, go looking in kitty for an issue.

**Comment by dankamongmen** [comment]
![2021-07-01-031957_1072x1417_scrot](https://user-images.githubusercontent.com/143473/124082882-39957380-da1b-11eb-9896-32814ed8b1b7.png)

here's an example. at the same time, the console is full of

```
[182 03:20:02.954725] [PARSE ERROR] Pending mode stop command issued while not in pending mode
[182 03:20:03.001765] [PARSE ERROR] Pending mode stop command issued while not in pending mode
[182 03:20:03.046850] [PARSE ERROR] Pending mode stop command issued while not in pending mode
[182 03:20:03.091718] [PARSE ERROR] Pending mode stop command issued while not in pending mode
[182 03:20:03.141268] [PARSE ERROR] Pending mode stop command issued while not in pending mode
[182 03:20:03.185259] [PARSE ERROR] Pending mode stop command issued while not in pending mode
[182 03:20:03.228897] [PARSE ERROR] Pending mode stop command issued while not in pending mode
[182 03:20:03.280649] [PARSE ERROR] Pending mode stop command issued while not in pending mode
[182 03:20:03.316743] [PARSE ERROR] Pending mode stop command issued while not in pending mode
```

this is kitty 0.19.3 from Debian Unstable. the same thing happens with 0.21.1, but i don't think the console gets crapped up like this.

**Comment by dankamongmen** [comment]
yeah, looks like my hunch was right, that "Pending mode stop" means we hit a stop-ASU while outside of an ASU, which i'm thinking means either

* we timed out, or
* we inserted some character which reset the escape

i suspect the first issue to be our problem. but why would that abort the graphic?

**Comment by kovidgoyal** [comment]
It shouldnt abort the graphic, however, this code path is not tested very well, so it could be a bug. You should try with kitty master, where the pending mode has been re-implemented to use the same VT parser as the main mode and should therefore be more robust.

**Comment by dankamongmen** [comment]
> It shouldnt abort the graphic, however, this code path is not tested very well, so it could be a bug. You should try with kitty master, where the pending mode has been re-implemented to use the same VT parser as the main mode and should therefore be more robust.

i've definitely seen the graphic-dumped-to-output problem on master, though i don't believe i've seen the error message on the console. actually, nevermind, i run master via a keyboard shortcut, so i wouldn't have a console on which to see said error messages. let me freshen up my build and run it from a terminal.

**Comment by dankamongmen** [comment]
this ought be easily enough verified by printing half of a graphic, sleeping, and then finishing it up. i'll check.

**Comment by dankamongmen** [comment]
alright, i've got a fresh 0.21.2 build now

**Comment by dankamongmen** [comment]
still seeing the message with 0.21.2, and i'm now running into "Unknown char after ESC: 0x5c". i'll track all this down and make sense of it. still quite possible that this is my bug.

**Comment by dankamongmen** [comment]
```
[182 03:47:46.263810] [PARSE ERROR] CSI code S has unsupported start modifier: S or end modifier: S
[182 03:47:46.263831] [PARSE ERROR] CSI code S has unsupported start modifier: S or end modifier: S
[182 03:47:46.263835] [PARSE ERROR] CSI code S has unsupported start modifier: S or end modifier: S
[182 03:47:46.387499] Pending mode stop command issued while not in pending mode
[182 03:47:48.432005] [PARSE ERROR] Failed to parse GraphicsCommand command payload with error: base64 encoded data must have a length that is a multiple of four
[182 03:47:48.435729] [PARSE ERROR] Unknown char after ESC: 0x5c
[182 03:47:48.450771] Pending mode stop command issued while not in pending mode
```

**Comment by dankamongmen** [comment]
`[182 03:47:48.435729] [PARSE ERROR] Unknown char after ESC: 0x5c` looks like it got an unexpected `ST`, which would make sense if it broke the graphic, as they end with `ST`.

**Comment by kovidgoyal** [comment]
I think whats happening is the timeout is being reached in the middle of accumulating an graphics APC code. If you can repro it reliably I'd appreciate a dump of the bytes that cause it.

**Comment by dankamongmen** [comment]
should have a repro within 10min, will file you a bug my mang

**Comment by dankamongmen** [comment]
yep, confirmed that this is yours. filing a bug with repro case.

**Comment by dankamongmen** [comment]
bug filed. assuming my interpretation is correct, i'm going to disable SUs in kitty until this issue is addressed (ideally, an SU abort would have no effect on an ongoing graphic). since SU is primarily useful in a context involving graphics (and then only when they're being moved around or modified), this makes it much less appealing. i'll cheerfully reenable once a version is out that fixes this (or if i'm incorrect in my analysis, of course).

**Comment by dankamongmen** [comment]
hrmmm! i commented out the code enabling ASU for kitty, and still saw this. so maybe i'm wrong about everything here! =/

**Comment by kovidgoyal** [comment]
You shouldn't need SU with graphics anyway, the graphics protocol is
pretty carefully designed to allow for atomic operations with small
escape codes. The idea being you load the image first and then PUT it on
the screen after loading. The PUT operation is just a few bytes in size
so doesnt require SU.

**Comment by dankamongmen** [comment]
> You shouldn't need SU with graphics anyway, the graphics protocol is
> pretty carefully designed to allow for atomic operations with small
> escape codes. The idea being you load the image first and then PUT it on
> the screen after loading. The PUT operation is just a few bytes in size
> so doesnt require SU.

as opposed to `a=T`? i can go ahead and do that if that's desirable. does interrupting an SU break other escapes, though? like if i send a bunch of ASCII characters, each with a different RGB fg + bg, there's what, 9--11 bytes of escape for every byte of glyph, so any timeout would be overwhelmingly likely to interrupt a `setaf` or `setab`.

**Comment by kovidgoyal** [comment]
Yes a=T is a convenience for simple scripts. As for whether it affects different escape codes I can only say after I have identified the bug, if any.

**Comment by dankamongmen** [comment]
confirmed that without SU we're not running into this problem. of course, we get a bit of flicker back in `intro`. we'll see if load+PUT can't eliminate that...in another bug.

**Comment by kovidgoyal** [comment]
On Thu, Jul 01, 2021 at 02:19:01AM -0700, Nick Black wrote:
> confirmed that without SU we're not running into this problem. of course, we get a bit of flicker back in `intro`. we'll see if load+PUT can't eliminate that...in another bug.


Note that you would pretty much have to do that anyway. That is because
pending mode is not an infinite buffer. In kitty it's capped at 1MB. If
you transmit more than that it will get aborted even without a timeout,
leading to flicker. This will apply to all terminal emulators, since I
doubt any terminal implements pending mode with an infinite buffer.

**Comment by dankamongmen** [comment]
> On Thu, Jul 01, 2021 at 02:19:01AM -0700, Nick Black wrote: confirmed that without SU we're not running into this problem. of course, we get a bit of flicker back in `intro`. we'll see if load+PUT can't eliminate that...in another bug.
> Note that you would pretty much have to do that anyway. That is because pending mode is not an infinite buffer. In kitty it's capped at 1MB. If you transmit more than that it will get aborted even without a timeout, leading to flicker. This will apply to all terminal emulators, since I doubt any terminal implements pending mode with an infinite buffer.

interesting! i don't think i've seen that in practice, and i definitely send more than 1MB at times. the `xray` demo, for instance, shows no flicker for me on kitty, and is certainly writing more than 256K 4Bpp pixels. but i'm going to move to this anyway, so it's all good.
