### ISSUE TITLE
How do you import the package on a venv ? 

### ISSUE THREAD

**Issue by chromafunk** [dankamongmen/notcurses#1866]
I'm trying to use notcurses in python, but I'm using a venv. If I install the packages system-wide, I can't import it, and if I install it via pip it can't find the headers : 

```
Collecting notcurses
  Using cached notcurses-2.3.7.tar.gz (5.3 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/xavier/bot_visuals/.venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h8ym5tor/notcurses/setup.py'"'"'; __file__='"'"'/tmp/pip-install-h8ym5tor/notcurses/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-h8ym5tor/notcurses/pip-egg-info
         cwd: /tmp/pip-install-h8ym5tor/notcurses/
    Complete output (25 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-h8ym5tor/notcurses/setup.py", line 35, in <module>
        setup(
      File "/home/xavier/bot_visuals/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/xavier/bot_visuals/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 447, in __init__
        _Distribution.__init__(self, {
      File "/usr/lib/python3.8/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/home/xavier/bot_visuals/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 740, in finalize_options
        ep.load()(self)
      File "/home/xavier/bot_visuals/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 747, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/usr/lib/python3/dist-packages/cffi/setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/usr/lib/python3/dist-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/usr/lib/python3/dist-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "src/notcurses/build_notcurses.py", line 14, in <module>
        with open('../include/notcurses/notcurses.h') as fp:
    FileNotFoundError: [Errno 2] No such file or directory: '../include/notcurses/notcurses.h'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

what's the common procedure to install the package on a python venv ?

**Comment by dankamongmen** [comment]
i have no idea personally, though perhaps @igo95862 or @scauligi might.

**Comment by dankamongmen** [comment]
if we don't hear from one of them by this evening, i'll look into virtualenvs and see what needs be done. sorry i don't know off the top of my head; i don't use python much =[.

**Comment by dankamongmen** [comment]
hrm what's going on here is it's trying to compile the python extension module, and can't find the headers, which would usually be in /usr/include (if notcurses was installed via package manager) or /usr/local/include (if installed from source)

**Comment by dankamongmen** [comment]
have you installed libnotcurses (if using your package manager, possibly `libnotcurses-dev`)? if not, you'll want to install it from source (you'll need ffmpeg and some other deps; see `INSTALL.md`).

**Comment by chromafunk** [comment]
yeah I'd work with notcurses in C++ straight, but I need a library that plots to braille chars that is only available for Python ... I want to make a tabbed terminal plotte, I hope to find luck with this seemingly amazing library because there is not other combination that suits my needs for this project

**Comment by dankamongmen** [comment]
> yeah I'd work with notcurses in C++ straight, but I need a library that plots to braille chars that is only available for Python ... I want to make a tabbed terminal plotter, I hope to find luck with this seemingly amazing library because there is not other combination that suits my needs for this project

i hate to suggest changing things up, but notcurses can most certainly do braille plots! `notcurses-demo` uses them by default, in fact. but so long as you have the `libnotcurses.so` and the include files installed, your python module ought be able to compile.

**Comment by chromafunk** [comment]
no problem, any suggestion is welcome. I have been trying many different things for the last two weeks and I have finally found notcurses ... does the plotting is this complete by chance ? https://github.com/tammoippen/plotille

**Comment by dankamongmen** [comment]
> no problem, any suggestion is welcome. I have been trying many different things for the last two weeks and I have finally found notcurses ... does the plotting is this complete by chance ? https://github.com/tammoippen/plotille

all it presents is a sliding window over some independent variable, in which you can store samples. compared to that thing:

* we have nothing like the symbolic language. they're giving you a FORTRAN; notcurses gives you assembly
* right now it's all histograms, but there's an active bug on line plots like these #511 

you could reproduce what they have here with #511 done, but you'd basically have to (for this example) run `sin()` over your range, and add the results as samples. so it definitely has a lot of functionality i don't plan for notcurses =\.

**Comment by chromafunk** [comment]
thank you for the information :) I indeed need something exactly like that, so what I was planning pass the graph output of that plotting library to a graphical tab system made with notcurses. Do you think this would be possible ?

**Comment by dankamongmen** [comment]
taking it over without any kind of transformation (i.e providing VTspeak to notcurses for output on a plane) is exactly what @tomek-szczesny is working on with #1554. until then, you'd have to ... do nasty things, unless you wanted to lose the coloring. how felicitous that he stepped up to work on this recently!

**Comment by tomek-szczesny** [comment]
Yeah I'm working on it right now. I hope to get at least colors and utf-8 parsed by the end of the week. But depending on your goals, you may need to wait a little while for more complete VT support. Or get your hands dirty and help me out ;) I'm doing this just because I need it for my project just like you do. ;)

**Comment by chromafunk** [comment]
the only thing I really need is to be able to pass the output of plotille, which will be updated "real-time", to a tabbed interface made with notcurses. For the rest of elements on-screen I think it can be covered with notcurses itself since It's just text being updated every second. I'm here to help :) but I don't think I have enough level to get hands-dirty on something like this ... I'm available to anything you might need, tho, since I really need this ASAP

**Comment by tomek-szczesny** [comment]
No worries, I'm not even a coder. ;) The VT emulation thing is more of a tedious work than hardcore coding challenge. One thing you may want to do is to identify which exact terminal controls you are most interested in. For example, I use `toilet --gay .` as a reference for examining and testing color coding. Your application might need something more, such as cursor movement or whatever.

```
mctom@Tomusiomat-ARM:~$ toilet --gay .
       
       
       
       
       
   #   
       
       
mctom@Tomusiomat-ARM:~$ toilet --gay . | hd
00000000  20 20 20 20 20 20 20 0a  20 20 20 20 20 20 20 0a  |       .       .|
*
00000020  20 20 20 20 20 20 20 0a  20 20 20 1b 5b 30 3b 31  |       .   .[0;1|
00000030  3b 33 35 3b 39 35 6d 23  1b 5b 30 6d 20 20 20 0a  |;35;95m#.[0m   .|
00000040  20 20 20 20 20 20 20 0a  20 20 20 20 20 20 20 0a  |       .       .|
00000050
```

The # character is actually bright magenta, and this way I can confirm that implementing SGR portion of [ANSI](https://en.wikipedia.org/wiki/ANSI_escape_code) controls should handle it.

You may try something similar and finding which escape codes are present in your output. Generally stuff after `0x1b` bytes is the most interesting.

IF you're serious about dedicating some time to help us out, there are a few easy C functions to implement, such as translating [FG and BG](https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit) 4-bit color codes into notcurses calls: `ncplane_set_fg_rgb8();` or  `ncplane_set_bg_rgb8();`respectively. However @dankamongmen would have to pick which color pallete he likes the most. ;)

**Comment by chromafunk** [comment]
yeah I'm in ... where do I start ? Do I need to download the source code ? :P

let me know about that palette and I'll get right in

**Comment by tomek-szczesny** [comment]
Well, this work lives on my HDD for now and is not strictly a part of the library, but an external prototype that we hope to incorporate into the library if it works nicely. I'll create a repo for this very purpose tomorrow and invite you over to add some code.

If you are in great haste, you may just use that code directly and independently, and not wait for the notcurses update. PErsonally I think that it is possible to have something working till the end of sunday.

Oh, and the following 8-bit table ought to be translated as well. I think there is a formula that governs their pattern, but can't say where did I see it last time.

**Comment by chromafunk** [comment]
I'm not exactly in great haste, but I would like to get this thing working just reasonably soon, since I still need to finish some other parts of the software I'm working on.  By no means I want to hurry you, of course.

with this` EDIT: For now, just start drafting the function and we'll tailor it to the existing code later on.`

you mean this ? :` IF you're serious about dedicating some time to help us out, there are a few easy C functions to implement, such as translating FG and BG 4-bit color codes into notcurses calls: ncplane_set_fg_rgb8(); or ncplane_set_bg_rgb8();`

**Comment by tomek-szczesny** [comment]
Yep, yep. In order to parse these nasty VTcodes and get any colors from external processes, we'll need functions that translate both 4-bit and 8-bit color codings into notcurses calls. I'll create a template for you tomorrow that I hope to see you filling with pure joy of hackin :)

**Comment by chromafunk** [comment]
sure, let me know and I'll get right in :)

**Comment by tomek-szczesny** [comment]
Alright, got not much time because apparently it's still a working day, but I set up a playground for you. Feel free to fill in these functions and if you succeed and feel like doing some more, I'll be happy to toss some more minor jobs at you. :)
https://github.com/tomek-szczesny/notcurses-vt-proto/blob/main/vt_colors.c

I'll add the rest of the prototype during the central european evening. :)

**Comment by chromafunk** [comment]
thanks to @tomek-szczesny for the effort on making notcurses translate plotille plots. Now that I have been ( kinda ) introduced to how notcurses works, I think I will code my module on C / C++, since we are calling the python plots via popen. We've talked about making a widget / library for ncurses with native, extended support for scientific braille-based plotting, which is something underdeveloped and much needed, which we believe would greatly fit in to ncurses. Thank you @dankamongmen for your help as well. I'm going to keep on asking annoying questions about ncurses, and for now I'm closing this since as I said I don't think I'll end up using python besides for the plotting output.
