### ISSUE TITLE
int ncplane_cursor_move(struct ncplane* n, int y, int x);

### ISSUE THREAD

**Issue by tomek-szczesny** [dankamongmen/notcurses#1881]
Relative cursor move within a plane.

There are at least 6 reasons for it:
![scrn-2021-07-04-16-36-30](https://user-images.githubusercontent.com/44300715/124389121-0f2b0b00-dce6-11eb-9632-bb5c351fddfa.png)

**Comment by dankamongmen** [comment]
```c
// move a plane relative to its current position. negative is up/left. pass 0 to hold an axis constant.
static inline int
ncplane_moverel_yx(ncplane* n, int y, int x){
  return ncplane_move_yx(n->absy + y, n->absx + x);
}
```

**Comment by dankamongmen** [comment]
i'll throw this in `notcurses.h`.

**Comment by dankamongmen** [comment]
> ```c
> // move a plane relative to its current position. negative is up/left. pass 0 to hold an axis constant.
> static inline int
> ncplane_moverel(ncplane* n, int y, int x){
>   return ncplane_move_yx(n->absy + y, n->absx + x);
> }
> ```

Oooh this has a BUG because it could hit -1, stupid me!

**Comment by dankamongmen** [comment]
oh, but shit, you want relative cursor moves, not relative plane moves!

well, you got relative plane moves, lol. whoops.

**Comment by tomek-szczesny** [comment]
Yeah, I was just about to call 112 because I thought I had a stroke or something..

**Comment by dankamongmen** [comment]
> Yeah, I was just about to call 112 because I thought I had a stroke or something..

IT'S AMERICAN FREEDOM DAY SAY 911 AND FIRE AN AUTOMATIC WEAPON

**Comment by tomek-szczesny** [comment]
Fuck me, indeed it is! Yet another excuse to get Burbur King for a dinner tonight.

**Comment by dankamongmen** [comment]
so what are we envisioning here? same as `ncplane_moverel()`, where you specify two dimensions? that doesn't really handle your "begin next line" and "end prev line" cases, but all six are really just `ncplane_cursor_yx() + ncplane_dim_yx() + bounds check + ncplane_cursor_move_yx()` (need do the bounds check to avoid passing -1 to `ncplane_cursor_move_yx()`). i can do 'em, but i imagine you can too, and map them more closely to exactly what you need? or i can write them when i get back in an hour or so.

**Comment by dankamongmen** [comment]
> so what are we envisioning here? same as `ncplane_moverel()`, where you specify two dimensions? that doesn't really handle your "begin next line" and "end prev line" cases, but all six are really just `ncplane_cursor_yx() + ncplane_dim_yx() + bounds check + ncplane_cursor_move_yx()` (need do the bounds check to avoid passing -1 to `ncplane_cursor_move_yx()`). i can do 'em, but i imagine you can too, and map them more closely to exactly what you need? or i can write them when i get back in an hour or so.

i will, incidentally, be returning with at least two AR-15s and a glock .45! w00t!

**Comment by tomek-szczesny** [comment]
I know I can do relative cursor moves using absolute ones, but I was thinking this is something that may be in common demand from end users. More like a feature request, feel free to ignore it if you disagree. ;)
In that case I'll develop it myself in my proto, so it could be implemented into the library later on.. But there is still a risk you'll reject my whole work ;P

Incidentally, I was at a shooting range a few days ago. I think I handled Glock for the first time in my life. All bullets hit the target, that's what matters. ;)

**Comment by tomek-szczesny** [comment]
But anyway, my vision is to do relative moves using x and y. It may handle first 4 cases on its own, and the following two in conjunction with absolute move along one axis. If relative moves could wrap around the plane boundaries, that would be easy enough to move a cursor to the beginning of the line using absolute move, and then one step further.

**Comment by joseluis** [comment]
I also ended up adding relative movement methods to the Rust wrappers for the ncplane, it's handy to have them since they're a common need.

**Comment by tomek-szczesny** [comment]
https://github.com/dankamongmen/notcurses/pull/1885/commits/98721fd31fbc9f97a8e9b58c5dbc29342b5cb9ab

**Comment by dankamongmen** [comment]
so this is done, right?

**Comment by tomek-szczesny** [comment]
> so this is done, right?

Surely is! #1885
