### ISSUE TITLE
Allow absolute cursor move along only one axis

### ISSUE THREAD

**Issue by tomek-szczesny** [dankamongmen/notcurses#1882]
```
// Move the cursor to the specified position (the cursor needn't be visible).
// Returns -1 on error, including negative parameters, or ones exceeding the
// plane's dimensions.
int ncplane_cursor_move_yx(struct ncplane* n, int y, int x);
```

Perhaps a negative x or y argument could be used for that.

So a newline could be implemented as: 
[ncplane_cursor_move(n, 1, 0)](https://github.com/dankamongmen/notcurses/issues/1881)
ncplane_cursor_move_yx(n, -1, 0)

**Comment by dankamongmen** [comment]
requested functionality already exists.

the man pages are much more authoritative than `USAGE.md`. i recommend consulting them, and anywhere you find gaps, i welcome patches!

**Comment by dankamongmen** [comment]
i've updated `USAGE.md`, `notcurses_planes.1`, and `notcurses.h`. I think we're done here.

**Comment by tomek-szczesny** [comment]
Great minds think alike, I guess. :)
