### ISSUE TITLE
scrolling planes ought scroll up their bound planes

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1883]
If a plane is scrolling, and it has subplanes, those subplanes ought scroll along with it. This is particularly important for the scrolling-standard-plane case. Right now, this is necessary to properly draw a sprixel in `notcurses-info` that scrolls up with the other output, and proving out this concept is central to the whole idea.

**Comment by joseluis** [comment]
I realized there's something I don't understand. Are not the subplanes just planes on the same pile as a root plane? How could there be different subplanes inside a single pile? You don't speak about sub-planes on the man pages so I'm not sure I have the right picture.

**Comment by dankamongmen** [comment]
note that the rendering engine will need to know about screen scrolling, or else it's going to redraw a bunch of stuff (the entire screen, effectively, since it'll think everything's one line off), massively hurting performance.

**Comment by dankamongmen** [comment]
good news, everyone! i figured it all out while on a walk. i'll write it up in a bit, gotta hop for work.

**Comment by dankamongmen** [comment]
https://github.com/dankamongmen/notcurses/discussions/1853 describes my plans, RFC

**Comment by dankamongmen** [comment]
be sure we observe `NCPLANE_OPTION_FIXED`, introduced in #1909

**Comment by dankamongmen** [comment]
ok, so what happens when we scroll a bound plane partially or entirely off the plane to which it is bound?

i'm inclined to think it ought work "like the real world" -- the subplane would scroll up until it is entirely distinct from the supraplane, at which point further scrolling would no longer move it. essentially, the rule becomes "when a plane is scrolling, subplanes intersecting it scroll along with it." i think that's reasonable. we do not destroy the plane once it's scrolled off or anything -- that's still up to the user.

properly doing this will require the ability to draw partial bitmaps. this need is evident even in `notcurses-info`: when the logo scrolls with the text, it can gradually scroll off the top of the screen. this is handled by the terminal normally, but we'll need deal with it explicitly. in general, this would solve #1539 as well. so maybe we ought attack #1539 as a prerequisite for this functionality.

**Comment by dankamongmen** [comment]
very promising: the first attempt does indeed fix `notcurses-info` when used at the bottom of the screen, which did not work before. unfortunately, it breaks the case where it's run at the top, which did work =].

**Comment by dankamongmen** [comment]
YAY the logo is now always correctly placed!!!!

**Comment by dankamongmen** [comment]
i am all that is man, baby!

![2021-07-18-163153_887x1057_scrot](https://user-images.githubusercontent.com/143473/126081339-5c8ef5e7-bbf5-4b6e-91ef-626250bd31f0.png)

**Comment by dankamongmen** [comment]
hrmm we can get this `notcurses-info` fix independently of the scrolling change, though...it's just a matter of displaying the logo after the rest. hrmm.
