### ISSUE TITLE
Where is egcpool.h?

### ISSUE THREAD

**Issue by tomek-szczesny** [dankamongmen/notcurses#1887]
I'm trying to use the flashy new `utf8_codepoint_length(unsigned char c)` but compiler says I declare it right here. What the hell?

The function is defined in egcpool.h and I don't see it installed on my system.

Is this something that can be used only internally by the library itself?

```
mctom@Tomusiomat-ARM:~/git$ ls /usr/local/include/notcurses/
direct.h  nckeys.h  ncseqs.h  notcurses.h  version.h
```

**Comment by dankamongmen** [comment]
it's in `src/lib`. it's an internal-only header (not installed, not intended for end-user inclusion). you ought be able to `#include` it with double quotes, i.e. `#include "egcpool.h"`. but i'm pretty sure `internal.h` already includes it?

**Comment by tomek-szczesny** [comment]
Ok, so I'll use it once I port my stuff to notcurses. For now I copied it to my source ;)

**Comment by tomek-szczesny** [comment]
Thanks for explanation. This is what I was thinking, just wanted to make sure.
