### ISSUE TITLE
konsole doesn't consume full SUM lookup

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1888]
We lookup SUM via the control sequence `\x1b[?2026$p`. Konsole doesn't consume the `p` here, and thus it pops onto stdout. Do we need it?

**Comment by dankamongmen** [comment]
Yep, definitely need the `p` (tested with contour and foot).

**Comment by dankamongmen** [comment]
Konsole also freaks out about Tertiary Device Attributes, which I submitted a PR for https://invent.kde.org/utilities/konsole/-/merge_requests/416#note_262363 (detailed in #1807).

**Comment by dankamongmen** [comment]
I don't want to crap up our initialization/detection process for this. Let's just submit another PR to konsole to cover this, and tell people to run the newest version.

**Comment by j4james** [comment]
Note that one of the main selling points of mode 2026 (over the `DCS` equivalent) was that it could safely be used without having to check if the terminal supported it. So unless it's essential to minimize bandwidth usage, you really shouldn't _have_ to query `DECRQM` for this.

It's also worth mentioning that there may be other terminals that have the same problems as Konsole with the `DECRQM` query. I know old versions of the Linux console and VTE has issues (but I guess you can just tell people they need to upgrade in that case), and there are a couple of Windows terminal emulators that I think probably still can't cope with `DECRQM` (not sure if you intend to support Windows clients though).

**Comment by dankamongmen** [comment]
> It's also worth mentioning that there may be other terminals that have the same problems as Konsole with the `DECRQM` query. I know old versions of the Linux console and VTE has issues (but I guess you can just tell people they need to upgrade in that case), and there are a couple of Windows terminal emulators that I think probably still can't cope with `DECRQM` (not sure if you intend to support Windows clients though).

definitely hoping to support windows, and always deeply appreciative of your wisdom!

**Comment by dankamongmen** [comment]
Thanks to the solution introduced for #2019, as of 2.3.13, we no longer see this spillage.
