### ISSUE TITLE
rename ncplane_genocide()

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1907]
If I'm perpetrating a genocide upon you, I'm making an attempt to kill your ancestors, as well. We do not do this in `ncplane_genocide()`, and thus it is misnamed. The going idea is the slightly-less-*Восточный фронт*ish `ncplane_family_destroy()`, which has the side benefit of sounding more like a gasline explosion than a crime against humanity.

See the discussion in #1853.

**Comment by joseluis** [comment]
Is this internal function going to be part of the public API?

**Comment by dankamongmen** [comment]
i chose Восточный фронт over the perhaps-better-known Ostfront because i don't understand why we're letting the people who lost name the front. hell, call it the Гео́ргий Константи́нович Жу́ков front.

**Comment by dankamongmen** [comment]
oh this is internal only, not such a possible big deal then
