### ISSUE TITLE
add NCPLANE_OPTION_FIXED

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1909]
See the discussion in #1853. This flag indicates that the created plane ought not be moved when its parent plane is scrolled (if the parent plane is *moved*, the plane will still move with it). Maybe `NOSCROLL` is a better name? But to me that sounds like "yeah, i don't want scrolling on this plane" (which is the default, but an orthogonal thing).

**Comment by joseluis** [comment]
here are some name ideas in case you like them: NCPLANE_OPTION_DETACHED_SCROLL, NCPLANE_OPTION_UNTIED_SCROLL

**Comment by dankamongmen** [comment]
Definition and documentation are in.
