### ISSUE TITLE
weird kitty image placement issue with scrolling

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1910]
I haven't figured this all out yet, but this is looking like a possible kitty bug?

So far as I understand, the position where I load a graphic `a=t` shouldn't matter; it's where I present the graphic (make it visible) that has effects. But it *does* seem to have an effect. I've got a 4-row graphic on a 70-row terminal. I load the graphic, display some text (some of it causing the terminal to scroll), and then make the graphic visible. The graphic is always made visible at 66;49. If I load the graphic at row 55 or above, this works. If i load the graphic at row 56 or below, it never becomes visible.

this is true even if i go somewhere high up to present. it's like when the scrolling happens, it somehow blows away my loaded, but not yet visible, graphic.

i'm working on a small example for this. very annoying.

**Comment by dankamongmen** [comment]
also, while i'm seeing far fewer of them, i'm growing pretty certain that i'm still seeing kitty graphic spills when using SUMode despite using the tip of trunk. =[ not certain enough to file a report there yet, but keep an eye on this.

**Comment by dankamongmen** [comment]
yep one just happened

![2021-07-09-090116_816x1417_scrot](https://user-images.githubusercontent.com/143473/125081642-3c840a00-e094-11eb-9894-1d639f146a2c.png)

**Comment by kovidgoyal** [comment]
See if this helps: https://github.com/kovidgoyal/kitty/commit/3c84a530e2f0ffa130bf89c1e3a735e35df589f1

**Comment by dankamongmen** [comment]
> See if this helps: [kovidgoyal/kitty@1d9626d](https://github.com/kovidgoyal/kitty/commit/1d9626d493515edf10af961f9e8df22e7de45e45)

testing it now, thanks! i didn't want to report it as a kitty bug until i was confident it wasn't my own stupidity.

**Comment by dankamongmen** [comment]
> See if this helps: [kovidgoyal/kitty@1d9626d](https://github.com/kovidgoyal/kitty/commit/1d9626d493515edf10af961f9e8df22e7de45e45)

i've only done initial testing, but this does appear to fix it. nice!

my workaround is sufficiently grotesque that i'm probably not going to worry about doing it on older versions, and just tell people to run newer kitty.

**Comment by dankamongmen** [comment]
leaving this open to watch out for SuMode graphic breakups, at least until i write something to try and trigger it and satisfy myself.

**Comment by dankamongmen** [comment]
nah let's close this and open another bug if we see that problem again. for the record, this issue was fixed upstream during kitty 0.21.2 development.
