### ISSUE TITLE
decimal comma breaks unit tests

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#192]
https://www.reddit.com/r/linux/comments/edo49w/notcurses_091_released_multimediacapable_tui/ in this thread, reddit user "mikedebian" reports a unit test failure on arch x86_64 glibc 2.30.

```
95% tests passed, 6 tests failed out of 118

Total Test time (real) =   7.95 sec
The following tests FAILED:
21 - NotcursesPrefix.Maxints1024 (Failed)
26 - NotcursesPrefix.PowersOfTwoAsTens (Failed)
27 - NotcursesPrefix.PowersOfTenAsTwos (Failed)
28 - NotcursesPrefix.PowersOfTenMinusOne (Failed)
29 - NotcursesPrefix.PowersOfTenPlusOne (Failed)
30 - NotcursesPrefix.PowersOfTenMinusOneAsTwos (Failed)
Errors while running CTest
make: *** [Makefile:107: test] Error 8
:: Unable to build notcurses - makepkg exited with code: 4
```

**Comment by dankamongmen** [comment]
He reported that he was able to manually build the package, but no word on unit testing/demo success yet.

**Comment by mikedebian** [comment]
Entering the build directory and typing in make install works. I am able to run the notcurses-demo manually from that directory or from the global installed files.

make test is where it fails.

`Errors while running CTest`        
                                                                                                                                                                                                                                                                                                   
`make: *** [Makefile:107: test] Error 8`

Here output from make test

[https://pastebin.com/Hdw7pwyc](url)

**Comment by dankamongmen** [comment]
```
/home/mxl/notcurses/src/notcurses-0.9.1/tests/enmetric.cpp:70: Failure
Expected equality of these values:
  gold
    Which is: "7,99Ei"
  buf
    Which is: "7.99Ei"
/home/mxl/notcurses/src/notcurses-0.9.1/tests/enmetric.cpp:73: Failure
Expected equality of these values:
  gold
    Which is: "8,00Ei"
  buf
    Which is: "8.00Ei"
```

European vs American number separators. Fix going in now!

**Comment by dankamongmen** [comment]
Looks like to handle this properly I need to use `localeconv(3)` to get a `struct lconv*`, and then use the `decimal_point` element to build up the gold answer.

**Comment by dankamongmen** [comment]
The unit tests now pass with `LANG` defined to either `be_BY.UTF-8` or good ol' freedom-filled `en_US.URF-8`. Thanks so very much for your help, debianmike! You're a good man, and thorough.

**Comment by mikedebian** [comment]
Will you please update the aur accordingly? Thanks!

**Comment by dankamongmen** [comment]
Yep. I need to cut an actual release to do so; I'll go ahead and do that now.

**Comment by dankamongmen** [comment]
Just cut 0.9.2, should be on AUR within the half-hour.
