### ISSUE TITLE
whiteout demo hangs on macOS

### ISSUE THREAD

**Issue by michaelsbradleyjr** [dankamongmen/notcurses#1936]
Following the merge of #1923, I synced with `master` and built with `PKG_CONFIG_PATH` set/exported appropriately.

The whiteout demo (spec `w` ) hangs indefinitely and I need to ctrl+c, but all the other demos run as expected (a couple of them have artifacts, can be more precise in another issue/s).

Since it seems @dankamongmen didn't have a problem running the whiteout demo from a linux machine connected remotely to my Mac mini, perhaps it's something that only manifests in terminal emulators running on macOS itself. I tried with iTerm2, Kitty, and Alacritty.

**Comment by dankamongmen** [comment]
reproduced, thanks a lot for the report! i'm guessing that this is due to OSX lacking support for most of Unicode 13...except so does FreeBSD, and we don't see this problem there. i'll see what can be done; thanks for the report!

**Comment by dankamongmen** [comment]
it's definitely spinning in there, so some kind of livelock...

**Comment by dankamongmen** [comment]
on mine, it's repeatedly getting stuck at 2/45

**Comment by dankamongmen** [comment]
alright, so we can now hit `ncplane_putegc` and, on an invalid unicode, get a ulen of 0 i'm presuming

**Comment by dankamongmen** [comment]
yep

**Comment by dankamongmen** [comment]
`whiteout` now runs properly on mac.

**Comment by michaelsbradleyjr** [comment]
https://user-images.githubusercontent.com/194260/126370095-cfa7c364-b3bd-4528-a580-0a0c07eed6e7.mp4

**Comment by dankamongmen** [comment]
https://github.com/dankamongmen/notcurses/issues/1936#issuecomment-883573449

> Works great!
> 
>  Kapture.2021-07-20.at.12.37.22.mp4

the little bits of misplacement are due to `wcwidth()` disagreements with actual glyph width, which has been an issue on all platforms since day 1. we may or may not have a solution for it in the future. thanks for verification!
