### ISSUE TITLE
[rust] issue with _IO_FILE structure in MacOs

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#1938]
As seen in #1937, the struct [_IO_FILE automatically created by bindgen in linux](https://dankamongmen.github.io/notcurses/rustdoc/libnotcurses_sys/ffi/struct._IO_FILE.html) doesn't exist in MacOs [(build log)](https://github.com/dankamongmen/notcurses/runs/3069492019?check_suite_focus=true).

I'm currently using it for the NcFile wrapper struct, right now only for the debug function... Since the C library expects to receive that exact structure, at least in linux... It would be useful to see what equivalent structure, if any, is created in macos.

In anycase I never liked the current solution for file, similarly to the sigset problem we had some time ago... It never felt sturdy or portable.

I'm gonna push a commit to remove NcFile in macos, in order to allow it to compile. And we'll see later if it can be fixed.

**Comment by dankamongmen** [comment]
`_IO_FILE` is just a synonym for the standard `FILE*`, i'm pretty sure. i'd try to use `FILE*` in all your rust wrappers rather than this glibc-ism. i don't think `_IO_FILE` will even work on other linux libcs like musl.

**Comment by joseluis** [comment]
In the bindgen bindings the opposite is true. `FILE` is an alias of `_IO_FILE`:
```rust
pub type FILE = _IO_FILE;
pub struct _IO_FILE {
...
```

What I like the least is that I can't use [libc's `FILE`](https://docs.rs/libc/0.2.98/libc/enum.FILE.html) because it is an opaque enum that is not accepted by the C notcurses functions that expect the public [`_IO_FILE` struct](https://dankamongmen.github.io/notcurses/rustdoc/libnotcurses_sys/ffi/struct._IO_FILE.html)... That's why I have to unsafely convert from one type to another in [`file.rs`](https://github.com/dankamongmen/notcurses/blob/master/rust/src/file.rs#L64-L73) to interface between the Rust and C code...

And I don't have a mac so I don't know what's happening in there.

If someone can compile notcurses in macos (@michaelsbradleyjr ?) and share the newly created `target/debug/build/libnotcurses-sys-*/out/bindings.rs` file I could take a peek and compare.
