### ISSUE TITLE
MAP_SHARED_VALIDATE unavailable in macOS

### ISSUE THREAD

**Issue by michaelsbradleyjr** [dankamongmen/notcurses#1941]
I rebased #1937 to pick up the latest changes on `master`. The macOS build is now failing during `make`:

https://github.com/dankamongmen/notcurses/runs/3078788075?check_suite_focus=true

```
/Users/runner/work/notcurses/notcurses/src/lib/png.c:266:20: error: use of undeclared identifier 'MAP_SHARED_VALIDATE'
                   MAP_SHARED_VALIDATE |
```

**Comment by dankamongmen** [comment]
zounds! thanks for the heads up, will fix ASAP

**Comment by dankamongmen** [comment]
this was just an improvement over `MAP_SHARED`; it's not necessary for any functionality. we now only use it where defined, falling back to `MAP_SHARED`.
