### ISSUE TITLE
verify support for stupid asshole osx

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#195]
Much as it pains me, we probably ought try to pick up some of that OS X market share. I flat-out refuse to pursue Windows. I don't have any OS X hardware, so ... patches welcome? Testing welcome? Hey @plotfi have apple give me a computer to support notcurses on.

**Comment by klamonte** [comment]
Some pointers for OSX:

* You can generate OSX icons for Linux with [icsutils](https://dentrassi.de/2014/02/25/creating-mac-os-x-icons-icns-on-linux/)
* An app bundle dmg is just an iso with a special structure.  It can be created on Linux also.  [Here](https://gitlab.com/klamonte/tjide/tree/master/build/osx) is one example.
* Alt-{something} keystrokes on OSX generally do not result in ESC-{something} as they do under xterm with metaSendsEscape.  Instead it is Cmd-{something}, IF that setting is enabled in the Terminal.app / iTerm2 profile.
* OSX fixed-width fonts generally suck for line-drawing / CP437 glyphs.  If you need something that really looks like "VGA" but with Unicode codepoints, [this TTF version of Terminus](http://files.ax86.net/terminus-ttf/) is pretty good, it might be worth pointing your users to if they complain of missing glyphs.

**Comment by jaroslov** [comment]
Trying to build on a bare-bones macOS dies when looking for 'tinfo>=6.1;ncursesw>=6.1'. The terminfo on latest macOS is 5.7; the ncursesw is 5.7. Both are 2008 vintage. That was a shit year — not as shit as 2020 — but still pretty shit.

**Comment by jaroslov** [comment]
`brew install ncurses` drops 6.2 into a 'keg', but the CMakeFile isn't playing ball.

**Comment by kdheepak** [comment]
I'm also interested in using `notcurses` on osx, and ran into the same issues mentioned above. I'm wondering if there's any potential ideas for working around this?

**Comment by Charadon** [comment]
Yeah, that's where progress ends for Windows also, it gets stuck at not finding uchar.h.

**Comment by dankamongmen** [comment]
oh hey holy shit, i missed all the action on this bug! catching up....

**Comment by dankamongmen** [comment]
https://github.com/dankamongmen/notcurses/runs/1101716635?check_suite_focus=true we now have a github action CI for macos, meaning this might move forward!

**Comment by jaroslov** [comment]
HAWT.

**Comment by kdheepak** [comment]
Has the CI for macos been dropped again? I don't see it in the latest commits.

**Comment by dankamongmen** [comment]
there's never been any ci for mac, so far as i'm aware?

**Comment by dankamongmen** [comment]
https://drone.dsscaw.com:4443/dankamongmen/notcurses/ if you can see this, this is all the ci i know of

**Comment by kdheepak** [comment]
Sorry, I thought your previous comment here in this thread suggested that there might have been a CI at some point: https://github.com/dankamongmen/notcurses/issues/195#issuecomment-691063305

**Comment by dankamongmen** [comment]
> Sorry, I thought your previous comment here in this thread suggested that there might have been a CI at some point: [#195 (comment)](https://github.com/dankamongmen/notcurses/issues/195#issuecomment-691063305)

oh no problem, just wanted to make sure we hadn't stood up some OS X CI without me knowing =]

**Comment by dankamongmen** [comment]
recent events have me hoping that this will see life by 3.0.0 this fall

**Comment by dankamongmen** [comment]
Initial OSX support is present. It currently requires exporting several directories as `PKG_CONFIG_PATH`, which will obviously need to get fixed. Other than that, everything seems to work.
