### ISSUE TITLE
make and submit a Notcurses brew

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1962]
it's about that time! let's get packaged into Homebrew.

this will need answers to #1933 and #1945, but i think it's otherwise about ready to go.

@michaelsbradleyjr , do you have any experience/cache in this field? i.e. do they already know you over there? are you at all interested in shepherding this through? it's not generally a particularly rewarding experience imho, though maybe the homebrew community is particularly wonderful; if you want to handle it, i'll be (further) in your debt; if not, totally understood, and i'll take up the spade and put my shoulder to the wheel.

**Comment by michaelsbradleyjr** [comment]
> do you have any experience/cache in this field? i.e. do they already know you over there? are you at all interested in shepherding this through? it's not generally a particularly rewarding experience imho, though maybe the homebrew community is particularly wonderful; if you want to handle it, i'll be (further) in your debt

According to my life choices, almost nobody in the world  *knows me*, personally nor professionally, anywhere on the Internet nor in real life-decades+ (except for a few, ❤️ you peoples).

Regardless, I'll look into what it takes to publish official Homebrew and MSYS2 packages.

**Comment by WSLUser** [comment]
Keep in mind, Homebrew also has a linux version and if you're creating a package, you'll want to be sure notcurses is available for both Mac and Linux via brew. At that point, maybe you could create a snap and/or flatpak package too.

**Comment by dankamongmen** [comment]
moving on this once #1972 is resolved

**Comment by dankamongmen** [comment]
> moving on this once #1972 is resolved

and #1972 is down!

**Comment by dankamongmen** [comment]
here's a first go

```
class Notcurses < Formula                                                                               
  desc "Blingful character graphics/TUI library"                                                        
  homepage "https://nick-black.com/dankwiki/index.php/Notcurses"                                        
  url "https://github.com/dankamongmen/notcurses/archive/refs/tags/v2.3.11.tar.gz"                      
  sha256 "9cdd868c6546cf1c2cf800ed2a054139b7377527493cdc4b71aced860de0d670"                             
  license "Apache-2.0"                                                                                  
                                                                                                        
  depends_on "cmake" => :build                                                                          
  depends_on "doctest" => :build                                                                        
  depends_on "pandoc" => :build                                                                         
  depends_on "pkg-config" => :build                                                                     
  depends_on "ffmpeg"                                                                                   
  depends_on "libunistring"                                                                             
  depends_on "readline"                                                                                 
  uses_from_macos "zlib"                                                                                
                                                                                                        
  def install                                                                                           
    system "cmake", "-S", ".", "-B", "build", *std_cmake_args                                           
    system "cmake", "--build", "build"                                                                  
    system "cmake", "--install", "build"                                                                
  end                                                                                                   
                                                                                                        
  test do                                                                                               
    system "#{bin}/notcurses-tester"                                                                    
  end                                                                                                   
end                
```

**Comment by dankamongmen** [comment]
note that it breaks if you have `uses_from_macos "ncurses"`

**Comment by dankamongmen** [comment]
hrmm, testing suggests that this isn't building `notcurses-tester` for whatever reason. as a result, our test stanza doesn't run properly. i've definitely got `doctest` listed as a build dep...

**Comment by dankamongmen** [comment]
https://github.com/Homebrew/discussions/discussions/1893

**Comment by WSLUser** [comment]
How does adding linux support to your formula look?

**Comment by dankamongmen** [comment]
> How does adding linux support to your formula look?

no idea! i would imagine not too difficult? it's right up there about five comments up.

**Comment by dankamongmen** [comment]
it looks like linuxbrew and homebrew are two different PRs

**Comment by dankamongmen** [comment]
alright, i now have homebrew building and running the test suite. i'll send in this PR upon releasing 2.3.12.

**Comment by WSLUser** [comment]
I've noticed that most authors just do both in the homebrew repo and the brew devs push the linux parts, probably through some automated means.

**Comment by dankamongmen** [comment]
i have cut 2.3.12, and i think we're ready to go with a submission here.

**Comment by dankamongmen** [comment]
https://github.com/Homebrew/homebrew-core/pull/82112

godspeed, little doodle

**Comment by dankamongmen** [comment]
we have an LGTM

**Comment by dankamongmen** [comment]
we are queued for merge =] =] =]

w00t!

**Comment by dankamongmen** [comment]
and yes, @WSLUser , it does look like we get a linuxbrew for free

**Comment by michaelsbradleyjr** [comment]
I'm very happy to see this day come!

**Comment by dankamongmen** [comment]
> I'm very happy to see this day come!

wouldn't have happened without you, my good mang!

**Comment by dankamongmen** [comment]
play them classics

[![ignition](http://img.youtube.com/vi/Xjho-zVgDXo/0.jpg)](http://www.youtube.com/watch?v=Xjho-zVgDXo "ignition")

**Comment by WSLUser** [comment]
I'll have to check if brew lets me install on a Linux distro like Clear LInux that doesn't have notcurses packaged up already. If there's issues, I'll be sure to raise bugs.

**Comment by WSLUser** [comment]
Ok, so notcurses formula is automatically sent to the linux brew repo but that means nothing unless you also target linux. 

Where you have defined the various MacOS versions, you also need to put `sha256 x86_64_linux *hash*`

**Comment by dankamongmen** [comment]
> Where you have defined the various MacOS versions, you also need to put `sha256 x86_64_linux *hash*`

are you certain? we show up in Repology for Linuxbrew...

https://repology.org/project/notcurses/versions

**Comment by WSLUser** [comment]
I tried installing on Debian and it's not coming up for whatever reason. I checked out a few other formulas and noticed they had that tag defined, sometimes with sub-parameters, this lead me to believe notcurses needed to add it too.

**Comment by WSLUser** [comment]
I think you are confusing distribution packaging with the linuxbrew packaging.

**Comment by WSLUser** [comment]
https://formulae.brew.sh/formula/notcurses#default This is what you have to check for brew. As shown there, Linux isn't supported. The entry I put needs to be added first.

**Comment by michaelsbradleyjr** [comment]
Might be relevant:

https://github.com/Homebrew/homebrew-core/pull/82112#issuecomment-889206164

> Oops, Linux will fail as we haven't bottled `ffmpeg` yet. We can ignore that.

**Comment by WSLUser** [comment]
It's included as a dependency unless something more needs to happen with it? I've never created formulas so not sure if there's more stuff needing to be done there.

**Comment by WSLUser** [comment]
Well despite the million things that were pulled in by brew, notcurses is able to get installed. It looks like the CI was removed for Linux for the initial submission but not for the next one. I did notice the ncurses formula needs to update one of it's dependencies but that's not your problem.
