### ISSUE TITLE
Pixel blitter in ncls not working on the linux console

### ISSUE THREAD

**Issue by MasFlam** [dankamongmen/notcurses#1964]
Wanted to test out the shiny new console graphics and `ncplayer -b pixel` works just fine for me, but `ncls -b pixel` does not, instead outputting a whole bunch of rhombi.

Please include the following data:
* `export | egrep 'LANG|LC_CTYPE|TERM'`
```
declare -x LANG="en_US.UTF-8"
declare -x LANGUAGE="en_US:en"
declare -x TERM="linux"
```
* notcurses version (available from `notcurses-demo i`) – 2.3.11
* terminal name + version – Linux console

**Comment by dankamongmen** [comment]
dup of #1959

**Comment by dankamongmen** [comment]
yeah it doesn't work in direct mode yet =[ i'm gonna fix it up ASAP

**Comment by MasFlam** [comment]
Ah for some reason didn't connect the dots on this one. thanks though!
