### ISSUE TITLE
rewrite plot.c with _Generic

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#1976]
`plot.c` is a horrible stinking wasteland populated with gigantic, ungainly macros implementing a poor man's typegenericism. these days (well, since c11) we have `_Generic`. i think it ought be sufficient to eliminate the macroness of this code.

**Comment by WSLUser** [comment]
I'd try going by the latest C standard and not something old. It would make things easier to maintain and likely allow improvements to be made more easily.

**Comment by dankamongmen** [comment]
so `_Generic` is strictly a mapping of expression type to expression. you can't really use it in any way i can see to get polymetric polymorphism--you still have to write all the functions twice. we might be able to get a bit of cleanup, let's see.
