### ISSUE TITLE
building on macOS fails if `make install` files are not removed before next cmake+make

### ISSUE THREAD

**Issue by michaelsbradleyjr** [dankamongmen/notcurses#1986]
Per my comments in #1933, in recent days I found myself unable to build notcurses on my macOS laptop, even though it builds successfully in a near identical environment.

I thought again about what could be different between my laptop and macOS builds in GitHub Actions.

The only thing that came to mind is that at one point locally I ran `sudo make install` and never deleted the various notcurses files placed under `/usr/local/`, while in GHA the filesystem is fresh for every build.

I tried deleting the installed files, then tried another round of `cmake` and `make` in my clone of notcurses (current `master`) and it works!

So it seems the files installed under `/usr/local/` by `sudo make install` can interfere with later attempts to build notcurses.

Is this a common gotcha that I didn't know about? A peculiarity of using these tools on macOS? Or does it seem like a bug of some kind?

**Comment by michaelsbradleyjr** [comment]
I realize that once notcurses is available via `brew`, few macOS would have the occasion to run `sudo make install` after building it themselves, but still seems good to understand the nature of the problem.

**Comment by dankamongmen** [comment]
> Is this a common gotcha that I didn't know about?

it is the bane of one's existence, and the worst possible way to waste several hours. i count on about four a year.

>  A peculiarity of using these tools on macOS? 

a peculiarity of preferring `/usr/local/lib` to `/usr/lib`, which is usually what you want, hence installing them there.

one strategy is to do all temporary development involving writing to `/usr/local` in an OS-level or even system-level VM, but i find that even more annoying than the alternative.

sorry for the timewaste! it happens to the best of us =[. this has never happened to you before?

![You-Are-Fucked_Up](https://user-images.githubusercontent.com/143473/126907762-1a7cf8a0-f437-4ffe-aeac-02f12ac5aedf.jpg)

**Comment by dankamongmen** [comment]
oh i see what you mean they were installed by the brew system, and you were upgrading? erp, yeah, that seems.....counterproductive if brew doesn't guard against that.

**Comment by michaelsbradleyjr** [comment]
> this has never happened to you before?

Not that I remember, but at least I know to watch out for it now. Thanks!

> oh i see what you mean they were installed by the brew system, and you were upgrading? erp, yeah, that seems.....counterproductive if brew doesn't guard against that.

No, installed with `sudo make install`.

But after installing with `brew`, it will be interesting to check if that results in the same kind of interference when building locally in my clone of the repo. Will leave this issue open for now and report back.

I haven't tried working with the formula you posted in #1962, hope to experiment with it this evening.

**Comment by dankamongmen** [comment]
been thinking about this and i think we ought be cool? 

btw that was kind of an obnoxious image to post; i hope i didn't offend you at all. just making sure =]

**Comment by michaelsbradleyjr** [comment]
No offense taken. 😄 

Once the package is available via `brew` (or if that homebrew-core PR is up I can try the formula locally before it's published), I was going to install it and then check if there's interference when running `make` in a clone of the repo.

**Comment by dankamongmen** [comment]
the homebrew PR is up at https://github.com/Homebrew/homebrew-core/pull/82112

**Comment by michaelsbradleyjr** [comment]
After `brew install notcurses`, in my local clone of the notcurses repo (up-to-date with current `master`) I did:
```
$ git clean -dfx && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release && make -j16
```

It worked correctly.

**Comment by dankamongmen** [comment]
so, i think that a change i'm about to make will resolve this, which would be nice, since right now you effectively can't build a local Notcurses if you have the brew poured. i'm adding `BEFORE` to the various `target_include_directories` directives, to check them before system headers. that ought address this.

**Comment by dankamongmen** [comment]
yeah, the `dankamongmen/libgpm` branch has a fix, i think, and it'll be merged soon.
