### ISSUE TITLE
either get vs2015-level c99 support or get rid of all %zu

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2007]
We use the C99 `%zu` printf specifier to print `size_t` values. MSVC didn't support this until VS2015, it would seem, and it raises warnings on our Windows action builds.

Is our compiler that old, or are we perhaps not enabling some C99 functionality that requires an option?

If we can't get this working, we'll need cast everywhere and use `%llu` or something equally grotesque.

https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=msvc-160#size-prefixes-for-printf-and-wprintf-format-type-specifiers claims it, as do many stackoverflow posts.

@michaelsbradleyjr maybe you can figure out what's going on?

```c
D:/a/notcurses/notcurses/src/lib/notcurses.c:945:30: warning: unknown conversion type character 'z' in format [-Wformat=]
91
  945 |     fbuf_printf(f, "\n%s%s, %zuB %s cells\nterminfo from %s zlib %s\n",
92
      |                              ^
```

**Comment by michaelsbradleyjr** [comment]
I *think* the discussion here is related: https://github.com/msys2/MSYS2-packages/issues/2538.

**Comment by michaelsbradleyjr** [comment]
I tried passing `-D __USE_MINGW_ANSI_STDIO=1` to cmake, but I still get the `warning: unknown conversion type character 'z'`, so maybe that's not the thing to do in UCRT64. I'll ask in the MSYS2 discord server.

**Comment by michaelsbradleyjr** [comment]
Should have been `-DCMAKE_C_FLAGS="-D__USE_MINGW_ANSI_STDIO=1"`. Even so, that still doesn't make the warnings re: `%z` go away. Still researching...

**Comment by WSLUser** [comment]
When it comes to Visual Studio, you want to support as new as possible. MSVC has had many changes and is far better though still not as great as cmake today than it was for VS 2015.  Things compiled with later MSVC should still remain compatible on Windows versions that existed prior to newer versions of VS.

**Comment by dankamongmen** [comment]
there aren't very many of these left in the codebase. i can probably just cast-and-convert the remaining handful. crazy lame, though.

**Comment by dankamongmen** [comment]
> When it comes to Visual Studio, you want to support as new as possible. MSVC has had many changes and is far better though still not as great as cmake today than it was for VS 2015. Things compiled with later MSVC should still remain compatible on Windows versions that existed prior to newer versions of VS.

we're trying to target the newest version, so far as i can tell. my question is why we're getting this warning despite using a compiler of what seems sufficient vintage. who knows; it's possible that this is a gcc bug (since we're not using visual studio at all in this environment).

**Comment by WSLUser** [comment]
> it's possible that this is a gcc bug (since we're not using visual studio at all in this environment).

It's possible to build and debug with gcc with VS though mostly geared towards doing so on WSL but it still works for compiling Windows binaries too. I forget which option in the settings you need though presumably if you load the project in VS from WSL, it should automatically provide you with the option for debugging with gcc.

**Comment by dankamongmen** [comment]
i just ended up removing or otherwise working around all %zu specifiers. may god have mercy on my soul.
