### ISSUE TITLE
Ctrl/shift + pgup/down return -1 from getc()

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2028]
Running `notcurses-input`, I pressed ctrl+pgup, and it immediately exited. It looks like pgup/pgdown together with shift and/or ctrl returns -1 from `notcurses_getc()`, an unexpected result. What's going on here?

**Comment by dankamongmen** [comment]
so it looks like without the modifiers, we get escape followed by 91, 53, and 126, "[5~" aka `kpp`. but with a modifier, we get 91, 53, 59 aks "[5;" which is the prefix of `kPRV` and numerous other `kPRVn`.

**Comment by dankamongmen** [comment]
alright, i've added these to the special keys we handle, and we no longer exit. indeed, we properly identify pgup/pgdown, though we're not yet associating modifiers with them.

**Comment by dankamongmen** [comment]
there seem to be several others which have the same effect -- ctrl+insert, ctrl+home, etc.

**Comment by dankamongmen** [comment]
`kHOMn`, `kICn`, `kLFTn`, `kENDn`, what fun!

**Comment by klamonte** [comment]
FYI here were my mappings for those, and you can see the modifiers:

https://gitlab.com/klamonte/lcxterm/-/blob/master/source/input.c#L522

When extended_keynames was off, I would also parse them directly:

https://gitlab.com/klamonte/lcxterm/-/blob/master/source/input.c#L103

**Comment by dankamongmen** [comment]
i actually set up the modifiers two days ago, and just never tagged this issue. https://github.com/dankamongmen/notcurses/blob/master/src/lib/input.c#L733

but i'm not sure i got them all, so i'll look through your reference, thanks as always @klamone!

**Comment by dankamongmen** [comment]
hahahahaha definitely misread `to_qodem_keystroke keynames` as `to_goddamn_keystroke keynames` at first =D
