### ISSUE TITLE
investigate disabling scroll for entire screen when not in cli mode

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2035]
When we're in rendered mode, but not scrolling the standard plane, we never want wayward output to cause us to scroll. Investigate whether we can define the entire screen to be a non-scrolling region (typically used for e.g. status bars), to protect against wayward output causing us to scroll. I kinda doubt that it'll work, but check it out.

**Comment by dankamongmen** [comment]
using `tput csr` with XTerm suggests that at least one line must be allowed to scroll. using e.g. `tput csr 0 0` appears to be a no-op, while `tput csr 0 1` has exactly the expected effect (the top line, and only the top line, scrolls). restricting scrolling to a single line would mean that that line could encrap itself, but others wouldn't unexpectedly scroll; this might be worth pursuing.

**Comment by dankamongmen** [comment]
quick experimentation suggests that doing a `csr 0 1` does indeed prevent `whiteout` from undesirably scrolling on the linux console, whereas `whiteout` otherwise does scroll. hrmmm.

it occurs to me that this also might allow us to draw sixels on the bottom row. exciting!

ok, this seems worth pursuing!

**Comment by dankamongmen** [comment]
`notcurses-demo` seems to run pretty much alright with this set, no obvious problems.

**Comment by dankamongmen** [comment]
hrmmm, the terminfo documentation says you're not allowed to move the cursor outside of the scrolling region. that's not particularly good. maybe they mean a visible cursor, not just the drawing point? in that case we could just forgo using this when the hardware cursor is enabled? i think we need reach out to someone more expert and inquire.

**Comment by j4james** [comment]
> it occurs to me that this also might allow us to draw sixels on the bottom row. exciting!

I had this idea as well, but technically Sixel images are not meant to be displayed below the bottom margin, so on a decent terminal emulator you won't see anything at all.

And for those terminals that do display images below the margin, most of them still won't clip the image if it extends past the bottom of the viewport, so you will typically get some sort of display corruption (it varies from terminal to terminal).

If you could guarantee the image would fit, you might be OK, but then you probably wouldn't need a hack like this. And it's still not going to work universally - XTerm in particular will try and render the image inside the margin area which is obviously not what you want.

**Comment by dankamongmen** [comment]
@j4james got it. i'm gonna verify your statements, but i suspect them to be correct, in which case this isn't going to be a winning plan for at least the bottom-row-sixel aspect.

with that said, i'm thinking this still might be helpful for avoiding unwanted scrolling due to terminals disagreeing with `wcwidth()`. the only place where i really see this happening is on the Linux console, where it happens quite often with the `whiteout` demo. since on the Linux console i draw by writing directly into an `mmap()` of the framebuffer, we have the happy coincidence that graphics wouldn't be affected by this. in that case, i might use this technique on the linux console only (`TERMINAL_LINUX` in notcurses terms).

**Comment by j4james** [comment]
> i'm thinking this still might be helpful for avoiding unwanted scrolling due to terminals disagreeing with `wcwidth()`

Yeah, that definitely makes sense. The behavior of `LF` below the bottom margin is well defined, and shouldn't cause the screen to scroll. Most terminals handle this correctly in my experience.

**Comment by dankamongmen** [comment]
great, i'm going to go ahead and throw this in and see what manner of thing results.

**Comment by dankamongmen** [comment]
hrmm the Grandmaster has this to say https://unix.stackexchange.com/questions/169509/how-to-use-esc-sequences-to-make-terminal-region-scrollable

**Comment by dankamongmen** [comment]
> Best practice does not attempt to use cursor-addressing outside the scrolling region, so there will be a lot of setting/resetting of the scrolling region, each time the program switches between the two sections of the screen.

it would be nice to know the justification for this best practice. this isn't worth it. let's see what happens.

**Comment by dankamongmen** [comment]
also, at the end of execution (or whenever someone enables scrolling on the standard plane at runtime), i'm going to want to disable this. i don't see any way to disable it other than a full reset of the terminal. we can `csr` back to our idea of geometry, but there's no way to make that atomic, we could miss signals, etc.

i wonder, if we've specified an explicit scrolling region, and the windows is enlarged, is our scrolling region reset? updated?

**Comment by dankamongmen** [comment]
hrmmmm. since `ncplane_set_scrolling()` can be called at any time, we'd need a way to indicate to the rendering cycle that we needed this emitted; we can't just emit it from that context. bah! i'm not carrying around state and checking it every render to cater to this cockeyed proposal. sending it back to god!

**Comment by j4james** [comment]
> it would be nice to know the justification for this best practice.

I suspect this may be because he was talking about curses, in which case the `csr` operation would not necessarily refer to `DECSTBM`, so its defined behavior would be more limited.

> i wonder, if we've specified an explicit scrolling region, and the windows is enlarged, is our scrolling region reset? updated?

Interesting question. I've just tried two terminals now: the one reset and the other retained the existing region as best it could. I'm curious now to see which approach is most common, but it's probably not something you'd want to depend on either way.
