### ISSUE TITLE
Weird corruption in PIP video in view demo

### ISSUE THREAD

**Issue by dnkl** [dankamongmen/notcurses#2037]
For some revisions now, I've seen what looks like a corrupted left-hand border of the PIP video of the rocket launch (the sixel one) in the view demo. See attached screenshot.

![grim-bfcce3f8-f941-11eb-bcfb-3c9180265d07](https://user-images.githubusercontent.com/14031526/128758386-1b21cbe8-5a43-433b-b5d6-4deb37d57aa4.png)

It doesn't happen, as far as I can tell, in XTerm (but it is _slooow_). I.e. this could very well be a foot issue. Though, this used to work, and there hasn't been any sixel changes in foot recently.

I can try to bisect notcurses, if you don't feel like spending time on this somewhat vague bug report?

```
notcurses 2.3.12 on foot 1.8.2-84-g496f5056
33 rows (15px) 106 cols (7px) 495x742 48B crend 256 colors+RGB
gcc-11.1.0, 16B LE cells
terminfo from ncurses 6.2.20200212 zlib 1.2.11
avformat 58.76.100 avutil 56.70.100 swscale 5.9.100
```

**Comment by dankamongmen** [comment]
yeah that doesn't look right. i'm a bit crushed today and would welcome a bisect assist. if you don't get to it, i'll attempt to reproduce in a local foot. i know i haven't seen this in kitty, but that's an entirely different protocol.

**Comment by dnkl** [comment]
Be happy to do it. No time today unfortunately, but hopefully tomorrow.

**Comment by dnkl** [comment]
God I'm stupid... this isn't a notcurses issue, it's caused by a recent change to the renderer in foot. Not really related to sixels, but obviously affects them.

Really sorry for having @dankamongmen being my rubber duck... :|

Will post a ref to the foot bug tracker once I've written up an issue report there.

**Comment by dnkl** [comment]
https://codeberg.org/dnkl/foot/pulls/675
