### ISSUE TITLE
linux console bleeds kitty graphics query through

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2050]
The Linux virtual console doesn't properly consume the APC we send to query for kitty graphics, bleeding everything starting with the `_G` through to stdout. I'm unsure why our cursor location hack isn't hiding this (we ought find out), but it would be even better if we simply didn't bleed this through. Either don't send the kitty query for the linux vconsole (as we already filter several others), or send the kernel a patch to consume APCs. Or both.

**Comment by dankamongmen** [comment]
ok, we do hide the bleed when we're printing at the top left (i.e. in `notcurses-info`, but in `ncneofetch` (which i was working on, see #2030), we have space there, and the output isn't obliterated. indeed, i don't see much we can do in that case. we'll have to handle it via one or both of the other suggested options.

**Comment by dankamongmen** [comment]
i've moved it to IDQUERIES, eliminating the problem.

**Comment by dankamongmen** [comment]
> It would be great if you sent the kernel a patch to consume APCs. I'd love for this to be reality but not sure how 

yeah that's my plan, but this got us working for now

**Comment by klamonte** [comment]
If a patch goes to the kernel, also have it consume Privacy Message sequences.  That would round it out for maintaining a clean display.

**Comment by dankamongmen** [comment]
> If a patch goes to the kernel, also have it consume Privacy Message sequences. That would round it out for maintaining a clean display.

great call. i think i'll put this together this weekend.

**Comment by klamonte** [comment]
I spoke too soon.  It also bleeds DCS sequences (e.g. sixel).  So DCS, APC, and PM.
