### ISSUE TITLE
deal with bce terminals when scrolling

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2054]
When a terminal has `bce` advertised, we should reset the background color to the default before executing any physical scrolls. Otherwise, if a background color is active, we bring in a new line with that color as background.

I know kovid has posted a deal of bile regarding `bce`, and while I don't recall exactly what he's said, I get the general impression that the semantics of `bce` aren't universal.

From the XTerm FAQ:

> The xterm-color value for $TERM is a bad choice for modern xterm because it is commonly used for a terminfo entry which happens to not support bce. Complicating matters, FreeBSD (after dithering for a few years on the matter) introduced a bastardized version which implies the opposite sense of bce, (because it uses SGR 39 and 49), but does not set it. After lengthy discussion, FreeBSD began using the terminal descriptions which I've written. The most recent XFree86 version's terminal description corresponds to xterm-xfree86 (also distributed with ncurses). I have continued to make changes; the most recent version is simply named xterm-new (also distributed with ncurses). The term "bce" stands for "back color erase". Terminals such as modern xterm and rxvt implement back color erase, others such as dtterm do not. (Roughly half of the emulators that I know about implement bce). When an application clears the screen, a terminal that implements back color erase will retain the last-set background color. A terminal that does not implement back color erase will reset the background color to the default or initial colors. Applications that paint most of the screen in a single color are more efficient on terminals that support back color erase. Inevitably, there are tradeoffs and issues with standardization of the feature as noted in the ncurses FAQ. Unsurprisingly, ncurses supports xterm's behavior. Curses libraries that support color know about bce and do the right thing – provided that you tell them what the terminal does. That is the whole point of setting $TERM. The "xterm-color" description distributed with ncurses does not list bce, because it was applied originally to a terminal type which does not implement back color erase. It will "work" for modern xterm, though less efficient. Some other applications such as the slang library have hardcoded support for terminals that implement back color erase. Given the "xterm-color" description, those will be efficient – and fortuitously work. However, slang (through version 1.4.0) did not work properly for the terminals that xterm-color was designed for. See this page for an example of (n)curses and slang running on dtterm. That bug in slang is reported to be fixed for succeeding versions, though your application may require changes to use this fix. (The demo which comes with slang to illustrate the use of bce does not work properly, for instance).

From the NCURSES FAQ:

> Even if your terminal supports the back color erase (bce) feature, you may still have problems using it. We can blame the standard (ISO-6429 aka ECMA-48 aka "ANSI"). It is too simplistic, being descriptive rather than prescriptive. What is that, you might ask? It means that the standards writers used existing simplified descriptions by developers for the features rather than decomposing the features into distinct parts—and then making precise descriptions of those for testing compatibility of various implementations. The standard does not go into enough detail to prescribe a particular behavior. Back color erase covers many (usually) related features, because there are many control sequences which might affect color, depending on the implementation. Here is a list—for each item there is probably at least one terminal type which differs from ncurses' assumptions. The list shows terminfo names with the standard control name, if any, in parentheses:

well, what i've observed is that on some terminals, when we scroll, we scroll with the background color filled in. if i can avoid doing that, that's enough for me, so far as i can tell. this ought be effected by simply clearing the background color when physically scrolling (will it only affect explicit newlines?). in direct mode, we would want to clear the background color, then restore it; in rendered mode, it is sufficient to clear it (and update the rendering state to reflect this); it'll be changed if necessary. either way, our abstraction is: no, there's no bce.

**Comment by dankamongmen** [comment]
as a good example, `ncneofetch` in the linux console now drags a bunch of white lines into the logo, where it did not before the work on #2030. make sure we've eradicated these.

**Comment by dnkl** [comment]
I'm still seeing this on foot and XTerm in ncwidth. This is with notcurses 0b61b3cd47b8a14a05d75596dd22f5d7d449c7fe, which should have the fix included (`notcurses-info` does say `bce+`).

![notcurses-bce](https://user-images.githubusercontent.com/14031526/129439996-7f08c0d7-5fdc-4edc-ad83-182e4834401f.png)

**Comment by dankamongmen** [comment]
oh `ncwidth` has many problems, i need to go fix it. this is longstanding behavior.

**Comment by dankamongmen** [comment]
`ncwidth` isn't installed so it's kinda a lowest-priority deal

**Comment by dankamongmen** [comment]
and in any case, `ncwidth` is using direct mode, and thus wouldn't be affected by this. that does remind me i ought migrate it to cli mode, though.
