### ISSUE TITLE
remove support for the iTerm2 graphics protocol

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2060]
As explained in #1987, the author of iTerm2 is opposed to cells and graphics sharing a cell, and thus has no plans to implement transparency (as we define it) for graphics (@gnachman states that it does honor transparency, which it does in a sense, but that transparency is only with regards to the background color, not any glyphery). Combined with iTerm2's prompting to save a file when one attempts to display a graphic, this pretty much makes it unsuitable for the Notcurses model. Remove the iTerm2 protocol support, which right now only serves to make us look incompetent.

macOS users can of course use Kitty or WezTerm to get glyph-aware transparency.

Let's go ahead and yank this by 2.3.14.

**Comment by klamonte** [comment]
> Combined with iTerm2's prompting to save a file when one attempts to display a graphic, this pretty much makes it unsuitable for the Notcurses model.

It is annoying that the download is the default, but "inline=1" did work for me to just get an image to iTerm2 without the download notification.

But my specific hurdles with it were:
* No direct way to detect support for it besides not-future-proof terminal fingerprinting.
* Incomplete documentation on what the various aspect ratio / pixel vs cell options actually do.  mintty clarified some of that, but I had to do trial-and-error experimentation to really get anywhere, and then it was wezterm that actually got me to the finish line.
* At one time (maybe still) I could not get the images to actually match the pixel dimensions of the cells in iTerm2.  (It had the same problem with sixel.)  Worked fine in mintty and wezterm though.
* iTerm2's implementation was really really slow two years ago.  That may be better now though, I dunno.

**Comment by dankamongmen** [comment]
i'll have to verify that i was using `inline=1`; thanks for the datum.

i didn't know mintty supported iTerm2's protocol. but it also appears to support sixel, so i'd be picking sixel there based off XTSMGRAPHICS responses alone.

> * iTerm2's implementation was really really slow two years ago.  That may be better now though, I dunno.

i'm actually thinking i might have acted rashly here. while the lack of graphic-on-glyph transparency makes it kinda useless to me in many contexts, it'll work fine for the more CLIy (as opposed to TUIy) applications that seem to dominate real use. except do i then lock it out when the user is attempting to use it in a graphic-on-glyph context? do i only support it in CLI mode? hrmmmm.

and iTerm2 does *dominate* among macOS users, so far as i can tell. so it's unfortunate to lose all functionality for those users... if i only supported it in CLI mode, i wouldn't need to do the annoying wipe/restore logic... hrmm.

yeah i think i'll probably revert this.

**Comment by gnachman** [comment]
inline=1 will not prompt to download. You should be able to get it pixel-perfect, and if you can't I can help with that. I have just quit my job and will work on iTerm2 full time so getting support for a per-cell side table is now more likely to happen, but probably not in the next month or two as I need to deal with the launch of the next version of macOS.
