### ISSUE TITLE
cmake: need kill off pkgconfig requirement if we're ever to natively build on windows

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2066]
if we're going to support building from VS, which i think we ought, we probably don't want a pkg-config dep. eliminate it on windows, replacing it there with the best practice, whatever that is.

**Comment by WSLUser** [comment]
Since you'll need to generate dlls on Windows, using a dll loader ought to be sufficient for this.

**Comment by WSLUser** [comment]
Using ProcessExplorer would also help in determining which dependencies you're running on Windows so you can ensure the you link them appropriately.

**Comment by dankamongmen** [comment]
i know what dpeendencies i have. i don't know how to find them on a given install.

**Comment by WSLUser** [comment]
Yeah ProcessExplorer will help with that. There are other utilities as well but that one also lets you see perf too.

**Comment by dankamongmen** [comment]
so i think we just drop all the `pkgconfig`-related stuff in a Windows context, and that closes up this issue.

**Comment by dankamongmen** [comment]
oh hrmmm but we *do* want this in the MSYS2 environment, hrmm hrmm.

**Comment by dankamongmen** [comment]
i think we can just use `if(MSVC)`
