### ISSUE TITLE
orca looks a bit bebarnacled in wezterm

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2076]
I am definitely leaning towards this being a WezTerm bug, but I'm not going to accuse @wez until I'm sure it's not ours.

Here's `intro` in kitty. Note that Natasha the Orca is cleanly hidden by the FPS graph and HUD:

![2021-08-19-003835_1251x1417_scrot](https://user-images.githubusercontent.com/143473/130008749-cdc66788-0bec-43a9-a19b-5a959584557e.png)

Here's `intro` in WezTerm 20210818-091943-4a809b40 without Kitty graphics enabled:

![2021-08-19-003752_959x1417_scrot](https://user-images.githubusercontent.com/143473/130008833-32986fde-7f4b-4904-b4a1-71f303fcedd3.png)

and with Kitty enabled:

![2021-08-19-003616_1180x1417_scrot](https://user-images.githubusercontent.com/143473/130008849-2c3d736a-119c-42af-b373-f539e5adc523.png)

note how in *both* WezTerm configurations, there's a bit of the tire hiding the upper-left part of the FPS graph.

so either i'm miscomputing the hide in both sixel and kitty logic, and yet it works everywhere else, or WezTerm is shitting all over our dreams like a feculent freddie kreuger. let's see if we can find the bug before wez does and then taunt him with quotes from Ivanhoe

**Comment by dankamongmen** [comment]
it is of course completely possible that this is a cell-pixel geometry thing and indeed our bug.

**Comment by wez** [comment]
FWIW, when you mentioned the `statepixel` test previously, it looked to me like the cell-sized bitmap was slightly off position-wise on the first pass, and then weirdly doubled up on the second pass.  I don't know if that is related to this.  

> or WezTerm is shitting all over our dreams like a feculent freddie kreuger. 

I would totally buy that this is a wezterm issue. I wonder if there's something a bit off in a reply/report returned from wezterm?

> let's see if we can find the bug before wez does and then taunt him with quotes from Ivanhoe

I'm simultaneously dreading and looking forward to this!

**Comment by dankamongmen** [comment]
here's what i'm seeing on my laptop; there's not as much interference, but definitely still some. 39 rows (26px) 88 cols (12px) 1014x1056.

![2021-08-19-032344_1060x1057_scrot](https://user-images.githubusercontent.com/143473/130026042-f83b7618-f240-4d37-8370-c414b8aa1437.png)

**Comment by dankamongmen** [comment]
kitty on laptop looks fine at 50 rows (21px) 80 cols (11px) 1050x880

**Comment by wez** [comment]
>  feculent freddie kreuger

I can't help but think of this as an Ubuntu release code name

**Comment by dankamongmen** [comment]
> I'm simultaneously dreading and looking forward to this!

> “Those who remarked in the countenance of this young hero a dissolute audacity mingled with extreme haughtiness ... could not yet deny to his countenance that sort of comeliness which belongs to an open set of features, well formed by nature, modeled by art to the usual rules of courtesy, yet so far frank and honest, that they seemed as if they disclaimed to conceal the natural working of the soul.”
                
I've always regarded this as a statement on the market failure of the Itanium and in general the false promises of EPIC. Very prescient indeed on the part of Sir Walter Scott.

**Comment by dankamongmen** [comment]
[e.txt](https://github.com/dankamongmen/notcurses/files/7018942/e.txt)

alright, this is the first frame containing the orca. this is using: 55 rows (25px) 87 cols (11px) 1375x957. the orca is PNG image data, 300 x 515.

so 55 rows on the screen, of which 6 ought be almost entirely text (looking at it, the frame has another error, this one probably mine -- the back of the wheel ought be visible, where not obstructed by the FPS graph).

orca is loaded here: `^[[34;59H^[_Gf=32,s=300,...`

so we're starting at row 34. 515 pixels tall over 25 pixels per cell height indicate 20.6 rows. ceil(34 + 20.6) == 55, so everything checks out thus far.

so to settle whose fault this is, there ought be 15 cell rows of RGBA output in our image, followed by nothing but 0-alpha data. if that's the case, wezterm is letting 0-alpha materia bleed through. if we are sending alphaful data past the 375th pixel, we're fucked up. verily, as Nelly warned us, rather than fucking the game, we'll have allowed the game to fuck us.

**Comment by dankamongmen** [comment]
at 300 pixels wide, 375 rows yield 112500 pixels. at 4Bpp plus base64 encoding, that's 600000B. at 4096 bytes per chunk, that's chunk 147. if we have anything with an alpha in chunk 148+, we're the donkey-raping shiteaters of this pair.

**Comment by dankamongmen** [comment]
oh right we're using full animation here. so we're gonna write it, then send in some wipes. ok, well the wipes ought have no alphaful material, end of story. if they do, it's our bug. if they don't, it's wezterm.

**Comment by dankamongmen** [comment]
in fact it ought suffice to ensure all the wipes are equal, which i'm certain they will be, given that they're constants. @wez looking like yours, gonna go verify.

**Comment by dankamongmen** [comment]
```
schwarzgerat](0) $ while read -r line ; do echo "$line" | sha256sum ; done < ~/e.txt
f368e9a0c9f9c8925242fd764ea391d4ec5ac6a2f06ac78e9af631f8108106e0  -
c22a8bbe65dda3217f83e0ca2c7d6cf47702b90891e8c7b4556ade11bfeaed65  -
0818e0d0c54406083310070ba77620c94cdab78d208c67875c500113d86bce9a  -
bab748d5ca1e6dd4b4a9eee7eb4ba119dfeb9cc10b251f76e5fa3284f61194cf  -
d1fe03982cea0d33c0a489d0a3b34925b6761bde6348369acc57f15c88908133  -
0052cbebfa544caca277e4242400d5939eb7150c751aadfb03034f3e05d37a9e  -
f250584f037cfef59d4751baa36e75d64807b95fca2414cdd24bfc6c1cf5017b  -
979dda1a68618282e8f0ff1ef0865cc549968cfb861ce0b538da0911b3271ca5  -
9cec3bd20a8513b2d4310155c02c789141fb8612bdd040d2c1b26db5f56d04e6  -
a15d5422c6e0691ff09a5712423eecf6ddba870e9527f37e85379cbc50a68889  -
7918d07a31fb287ca377f12a61f43419378d279dfa8338e079c9c40e80ef28b6  -
8aa853203fb6ada518eb1980d284c49f925961d79058e61fe4103e0b23489e2b  -
5433f7b581c8600e2f166b0563e6954325388c49c54e400d3b74ff12a0fc13ea  -
49f406163c4354a688e9075d61567ca458eec866d89b616973207ce02826cd93  -
233d830c46175c5dc89d327c4b9fa1f66f565079696b905dc71a40b02ff9f791  -
636d0a517606c6a54e24cfa10703ca13a63654333f4b1a06da93d264171e3f5c  -
9f790edadf8bf9a94e89aab60292a29410d60a6292c424aa2040ffb8de8f0ed3  -
c3d6743358bc8fb35403172347261d2192e764c6cd83e66fc51bf16699e85495  -
b3bef30c10ce1a4eafd78eeb26261724544bc1f47a3814e287aca23abbbeb38c  -
ef3205764d030b7d96bc1981130e10bf81f21b7c7efd24a0df5e90c414f900aa  -
d1e8d343dcf903fb2fb2786b71c889111f9b4514a98807fabf0aeb158903670f  -
d1c2ef36c3a425a592d49d73e11b17662c8e0a4bd27bfae27dd3df860f6acd6e  -
2144fa0fe02fec68e22beed420bc57d49af6b1eb488d3bfd001f068acc20b8d2  -
612587d64e42c9ff077b2dca74bd7d6237c02f0c19a5f4586ba4110f40a1cf1a  -
904417014e9fef4e82def856d3460aaecef93ab90f84dbd240d283c
...
```

```
[schwarzgerat](0) $ while read -r line ; do echo "$line" | sed -e 's/x=...,y=...,//' | sha256sum; done < ~/e.txt | uniq
8fdb5965229ede35807aa7691327236af601df35ef3f3f4b8b43025c57141d89  -
[schwarzgerat](0) $
```

yeah this ain't on ol' dixie flatline

**Comment by dankamongmen** [comment]
let's get on this and get a minimal test case we can show wez

**Comment by dankamongmen** [comment]
i'm thinking the thing to do is generate an image which is just a grid of cell inlays, and cover part of it. that really ought be enough. make it small and give him the raw output capture.

**Comment by dankamongmen** [comment]
this got resolved upstream, hurrah
