### ISSUE TITLE
terminal unusable after running any notcurses program

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#2093]
using latest version from repo, after running any notcurses program I can't use the terminal any more, like if input was disabled.

**Comment by WSLUser** [comment]
Could you list what programs you use (outside of Nick's personal projects) in https://github.com/dankamongmen/notcurses/issues/2017

**Comment by dankamongmen** [comment]
> using latest version from repo, after running any notcurses program I can't use the terminal any more, like if input was disabled.

erp! best thing to do might be to run `./notcurses-info > out.txt` and attach `out.txt`. that's certainly no good. which terminal?

**Comment by dankamongmen** [comment]
also, until you exit, is the program you're running working fine?

**Comment by joseluis** [comment]
> erp! best thing to do might be to run `./notcurses-info > out.txt` and attach `out.txt`.

done: [out.txt](https://github.com/dankamongmen/notcurses/files/7041652/out.txt) (using wezterm)

> which terminal?

every terminal I've tried (alacritty, xterm, wezterm...)

> also, until you exit, is the program you're running working fine?

yes, until then everything seems to works fine, even the input.

**Comment by dankamongmen** [comment]
weird...all of that looks pretty much right, and if i `cat out.txt` in WezTerm, it shows up, and my terminal is fine afterwards....
![2021-08-24-153404_800x1417_scrot](https://user-images.githubusercontent.com/143473/130678671-8f6bce8a-2b87-4a78-bee3-7f8908878110.png)

**Comment by dankamongmen** [comment]
likewise, `cat Download/out.txt` works fine in XTerm and Alacirtty....shows the sixel and everything.

**Comment by dankamongmen** [comment]
i assume that if you `cat out.txt`, your terminal is left in the undesirable state?

**Comment by joseluis** [comment]
> i assume that if you `cat out.txt`, your terminal is left in the undesirable state?

Interesting! If I cat out.txt the terminal works fine afterwards!

**Comment by joseluis** [comment]
> Could you list what programs you use (outside of Nick's personal projects) in #2017

sure! when I have some publishable, for now they're just private experiments...

**Comment by dankamongmen** [comment]
are these possibly direct mode programs? if so i might have just found the culprit

**Comment by joseluis** [comment]
> are these possibly direct mode programs? if so i might have just found the culprit

yes and no, I mean, it happens with both full mode and direct mode...

**Comment by dankamongmen** [comment]
fuck i think i missed a commit from my windows vm

**Comment by dankamongmen** [comment]
alright just fixed a grotesuqe pair of oversights, one each in direct and rendered, maybe this solves your mysterious problem.

**Comment by joseluis** [comment]
> alright just fixed a grotesuqe pair of oversights, one each in direct and rendered, maybe this solves your mysterious problem.

fixed! thanks :smile:

**Comment by dankamongmen** [comment]
ugh, sorry to welcome you back with such an inauspicious state of affairs; i got called to real work suddenly this morning and didn't throw in my outstanding commits from my windows vm =[
