### ISSUE TITLE
get cell geometry in mintty

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2098]
On Windows builds, we don't compile in termios (wasn't this originally due to it being unsupported, though? which would invalidate this entire issue?). That's fine for Windows Terminal, where we can successfully use `GetConsoleMode()` and `SetConsoleMode()`. These fail in e.g. MSYS2, though, leading me to suspect we want termios there. Either way, fix up `notcurses-input.exe` in mintty (it works properly in Windows Terminal).

**Comment by dankamongmen** [comment]
> Ps = 1 4  ⇒  Report xterm text area size in pixels.   <--------------------------------------
Result is CSI  4 ;  height ;  width t
            Ps = 1 4 ;  2  ⇒  Report xterm window size in pixels.
          Normally xterm's window is larger than its text area, since it
          includes the frame (or decoration) applied by the window
          manager, as well as the area used by a scroll-bar.
          Result is CSI  4 ;  height ;  width t
            Ps = 1 5  ⇒  Report size of the screen in pixels.
          Result is CSI  5 ;  height ;  width t
            Ps = 1 6  ⇒  Report xterm character cell size in pixels.
          Result is CSI  6 ;  height ;  width t
            Ps = 1 8  ⇒  Report the size of the text area in characters.  <----------------------
          Result is CSI  8 ;  height ;  width t
            Ps = 1 9  ⇒  Report the size of the screen in characters.
          Result is CSI  9 ;  height ;  width t


are you feeling lucky?

**Comment by dankamongmen** [comment]
verified that '\e[18t' gets the cell geometry in mintty, w00t...

**Comment by dankamongmen** [comment]
we now send the '\e[18t' cell geometry query, and parse a response. if we get one, it replaces the `default_rows` and `default_cols` in the `tinfo` structure, and will thus bubble up and be used if we can't use an `ioctl` or such.

we might want to add code to explicitly send one when we get a `SIGWINCH` or any other change notification, but that's outside the scope here. i verified in kitty that we handle the response, and would expect this to work in MinTTY. unfortunately, it looks like we're not sending queries to mintty on windows, presumably because we go to use `GetStdHandle()`, and it fails. `isatty()` always appears to return 0 within MSYS2 (see https://mingw-users.narkive.com/kxtQ2FYb/isatty-within-cygwin), so we don't send the queries, nor read the responses.

hrmmmmmmmmm....

**Comment by dankamongmen** [comment]
maybe on windows we just make `isatty()` reduce to true? the only problem is when something's running wholly outside of a terminal environment, and thus nothing is going to respond to the queries. we will then block indefinitely. but that kind of daemonized execution seems less likely on windows(?)... let's try it out, and see if it succeeds within our CI. if it does, i think that's grotesque, but it just might work.

**Comment by dankamongmen** [comment]
why can't one successfully open `/dev/tty` in mintty? you can `cat` it. that's very odd....a mystery!

**Comment by dankamongmen** [comment]
i'm now extracting a response from mintty, but not yet reading it, apparently.

![2021-08-28-184152_1438x1056_scrot](https://user-images.githubusercontent.com/143473/131232728-6317fa59-4f8a-4eb5-aff0-578539d91a6a.png)

**Comment by dankamongmen** [comment]
we ingest the responses if i press enter. so we need to somehow effect true cbreak mode within MSYS2 for this to work. on the plus side, we *do* successfully extract pixel and cell geometry both from MinTTY after enter is pressed.

**Comment by dankamongmen** [comment]
ok, with an enter pressed, everything now works:

![2021-08-28-193545_1438x1056_scrot](https://user-images.githubusercontent.com/143473/131233518-d69109ef-9f41-4bfc-8aee-f18fed6d682b.png)

we just need a working cbreak for cygwin/msys2!

**Comment by dankamongmen** [comment]
alright, let's make a new issue on cbreak for msys2. this works.

**Comment by BrianInglis** [comment]
You should also be able to test *Cygwin* `mintty` under *Wine*, under *Windows* using `ssh` to *Debian*, or *Debian* `WSL` using the `wsltty` package variant of `mintty` with `wslbridge` (or whatever interface is currently required) installed on both ends. 
*Cygwin* `mintty` also supports *DEC* *Regis* and *Sixel* graphics and *Tek4014* emulation. 
Most of the active emulator developers cooperate in an an informal group improving interoperability and standardizing queries for newer features. 
*Cygwin* `mintty` responds to my `bash` function `xterm-info` as follows: 
```
$ xterm-info
type features   VT420wpSeNThcrl ^[[c            ^[[?64;1;2;4;6;9;15;21;22;28;29c$
type version    mintty v3.5.1-0 ^[[>c           ^[[>77;30501;0c$
window position 3 px 210+120    ^[[13t          ^[[3;210;120t$
window size     4 px 875x881    ^[[14;2t        ^[[4;881;875t$
text position   3 px 219+152    ^[[13;2t        ^[[3;219;152t$
text size       4 px 840x840    ^[[14t          ^[[4;840;840t$
text chars      8 ch 120x60     ^[[18t          ^[[8;60;120t$
char size       6 px 7x14       ^[[16t          ^[[6;14;7t$
screen chars    9 ch 274x77     ^[[19t          ^[[9;77;274t$
screen size     5 px 1920x1080  ^[[15t          ^[[5;1080;1920t$
window status   1 open          ^[[11t          ^[[1t$
```
whereas *Debian* `lxterminal` shows:
```
$ xterm-info
type features	VT525wN		^[[c		^[[?65;1;9c$
type version	VT525 v64.2-1	^[[>c		^[[>65;6402;1c$
window position	3 px 0+0	^[[13t		^[[3;0;0t$
window size	4 px 840x675	^[[14;2t	^[[4;675;840t$
text position	3 px 0+0	^[[13;2t	^[[3;0;0t$
text size	4 px 840x675	^[[14t		^[[4;675;840t$
text chars	8 ch 120x45	^[[18t		^[[8;45;120t$
screen chars	9 ch 160x53	^[[19t		^[[9;53;160t$
window status	1 open	 	^[[11t		^[[1t$
```
and `u/xterm` does not respond with much info:
```
$ xterm-info
type features   VT420wpeNTLqWhcr ^[[c		^[[?64;1;2;6;9;15;16;17;18;21;22;28c$
type version    VT420 v368-0    ^[[>c           ^[[>41;368;0c$
screen size     5 px 1122x799   ^[[15t          ^[[5;799;1122t$
```

**Comment by dankamongmen** [comment]
i'm getting the cell-pixel geometry via queries now =] i'm pretty sure, anyway
