### ISSUE TITLE
need cbreak mode (no echo, no line buffering) for MSYS2

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2116]
See #2098. We're now sending queries to MinTTY, and getting replies. The problem is that we're in canonical mode, not cbreak mode, and thus the user needs to hit enter to start parsing the input =[. This is a blocker for working in MSYS2.

`cbreak()` from NCURSES doesn't accomplish anything. On Windows Terminal, we use `SetConsoleMode()`, and that works. On true UNIX, we use termios. I don't see any way to do it for cygwin yet, though =[.

**Comment by dankamongmen** [comment]
![2021-08-28-194840_1438x1056_scrot](https://user-images.githubusercontent.com/143473/131233718-537225c7-3fda-41f3-8def-7056e7227d86.png)

things are working decently now once we press enter, so let's get this fixed.

**Comment by dankamongmen** [comment]
ok, after some research....

it appears that in Cygwin/MSYS2, we get a pipe, not a console, as our standard handles. so `SetConsoleMode()` is not expected to work on it...but we might be able to use `SetNamedPipeHandleState()` to set it non-blocking. but i don't think that will necessarily have any effect on our input remaining line-buffered, which is presumably higher up in the stack.

**Comment by dankamongmen** [comment]
as predicted, checkin of the query code has broken our windows autobuild, due to this issue.

ok. it **MUST** be possible to do this, or vim wouldn't work in msys2. so we know it *can* be done.

**Comment by dankamongmen** [comment]
i mean, it's possible that this isn't a keyboard line discipline thing, and we just have line buffering on stdin, right? but we're using the `read()` call to get input...but who knows what Cygwin emulations that goes through...

**Comment by dankamongmen** [comment]
if it was a keyboard/console thing, then it wouldn't be affecting our autobuilds, n'est-ce pas? so maybe there's actually line buffering by default in the actual goddamned windows pipe?

**Comment by dankamongmen** [comment]
all experimentation with `SetNamedPipeHandleSettings()` etc. including `setvbuf()` yielded null results

**Comment by dankamongmen** [comment]
i think we ought checkout the Vim source code. `src/iscygpty.c` is clearly checking for a cygwin/msys environment (and confirms that stdin there is a pipe): https://fuchsia.googlesource.com/third_party/vim/+/refs/tags/v8.0.0049/src/iscygpty.c

so let's find what calls that, and proceed from there.

**Comment by klamonte** [comment]
Thinking out loud... Any chance it isn't cbreak(), but rather buffered I/O?  glibc for example buffers I/O when isatty() returns <= 0.

**Comment by dankamongmen** [comment]
> Thinking out loud... Any chance it isn't cbreak(), but rather buffered I/O? glibc for example buffers I/O when isatty() returns <= 0. It's why I spawn shells using either 'script' or 'ptypipe', which basically do forkpty() behind the scenes, and give glibc a tty so that it actually sends data. But that would be more cygwin's job to do when spawning notcurses, not the other way around.

well i tried disabling buffering with `setvbuf()`, but that yielded null results. you can't disable buffering on named pipes as you can console handles; there's just blocking-or-nonblocking and bytes-vs-messages. we're already in byte mode, and nonblocking wouldn't help us, because content isn't being delivered to the pipe until enter is pressed (as verified with `PeekNamedPipe()`, and i also tested with nonblocking out of desperation).

**Comment by dankamongmen** [comment]
@j4james, you seem a knowledgeable guy...any ideas here?

**Comment by j4james** [comment]
Sorry, I'll be of no help here. I've not used MSYS2 before.

**Comment by dankamongmen** [comment]
an idea...we're using stdin rather than ttyfd for all windows builds...what if we restricted that to true windows somehow (easily enough determined: windows build, not `TERM_MSTERMINAL`). does that then work? i doubt it, but let's try.

**Comment by dankamongmen** [comment]
i took a good look at the NCURSES source code to see if @thomasdickey had some secrets. look at `ncurses/win32con/win_driver.c`. it looks like maybe we have to find and connect to the underlying console object powering our pipes.

**Comment by dankamongmen** [comment]
i don't think that's intended for windows-native binaries....but maybe we don't *want* a windows-native binary for *running* inside of msys2? i.e. we ought build our native windows stuff there, but we ought *also* build msys2 binaries for running within mintty.

yes. i suspect that this is The Way.

**Comment by dankamongmen** [comment]
yeah, it's looking like that's correct. basically, we can build UCRT binaries for windows in MSYS2, but they won't work there. within MSYS2, we'd want to be running a MSYS2 binary, which can then use its termios implementation.

@michaelsbradleyjr does this sound plausible to you?

**Comment by michaelsbradleyjr** [comment]
> @michaelsbradleyjr does this sound plausible to you?

It does seem plausible.

Looking back over the msys2 website, at the bottom of the [Terminals](https://www.msys2.org/wiki/Terminals/) page, there's this:
> **Mixing MSYS2 and Windows**
> MSYS2 allows some inter-operation between a MSYS2 program and Windows console and between a Windows program and MSYS2 terminal emulators. For basic stuff, it works fine. Anything more complicated, like colored text, TUIs and line editing, is a lottery -- it can work, it can break.

I think that's the situation you've been dealing with.

So, recasting the revised approach in terms of [environments](https://www.msys2.org/docs/environments/):
* If one builds a notcurses program in the MSYS2 UCRT64 environment, then the executable should be run in Windows Terminal; it will be expected to not run correctly in Mintty.
* If one builds a notcurses prograam in the MSYS2 MSYS environment, then the executable should be run in Mintty for that environment; it will be expected to not run correctly in Windows Terminal. It probably won't run correctly in Mintty for a different environment, e.g. MSYS2 UCRT64, but I'm not sure about that.

I'm guessing it will be important for cmake and the headers, etc. to distinguish between MSYS2 UCRT64 and MSYS2 MSYS.

---

I've been really busy with work. I'll try to catch up on some other issues you mentioned me in recently.

**Comment by dankamongmen** [comment]
another place where this principle would seem to apply is in input handling: for Microsoft Terminal, we want to use `WaitForMultipleObjects()`, and there is no `poll()`. But that doesn't work within MSYS2, where we will want to use `poll()` from its runtime.

so what i see happening here is we'd split the Windows workflow into two distinct workflows. one installs the MSYS runtime and uses that environment setup; one installs the UCRT runtime and uses that environment setup. only the first would run tests, since we're not simulating the true UCRT environment. the first, however, ought now have full termios + poll support, and thus tests ought succeed there.

the only point of the second workflow would be (a) to ensure the UCRT build is still working (as in generating a binary) and (b) perhaps to build releases for distribution.

with that said, whether or not the first workflow is really useful is questionable. i guess it's nice to be able to run the unit tests on windows, but we're not building `notcurses-tester` there, and doing so is not the highest priority of mine. we'd run a few simple checks, but i'm unsure it justifies an entire workflow of its own. then again, we're not paying for them, so....

but that's what we're gonna need to do to get working MSYS binaries, from what i can tell, and getting working MSYS binaries is necessary for us to run any manner of windows testing in CI. if all this is correct, it also means we'll *never* be able to build binaries in the UCRT MSYS2 setup that will then work within that setup, which is kind of a bummer (though i think we could build a binary in the MSYS MSYS2 setup which then works within the UCRT MSYS2 setup, so long as the right msys packages are installed). yeah, that gets me down.

before we do *any* of this work, verify that a MSYS-native binary actually does work, as in both termios and poll function as expected.

i'm sorely tempted to move this to 3.0.0, as it's a good bit of work that only really benefits the native msys environment. i want to get 2.4.0 out this weekend, ideally. i hate admitting defeat, though. ugh.

**Comment by mintty** [comment]
Windows applications are not fully compatible with pty-based terminal interaction. The new Windows ConPTY support can bridge the functional gap. Cygwin provides this support since 3.2.0. MSYS is derived from cygwin but disables ConPTY support by default. Try `MSYS=enable_pcon mintty` or just `mintty -P on`.

**Comment by dankamongmen** [comment]
> Windows applications are not fully compatible with pty-based terminal interaction. The new Windows ConPTY support can bridge the functional gap. Cygwin provides this support since 3.2.0. MSYS is derived from cygwin but disables ConPTY support by default. Try `MSYS=enable_pcon mintty` or just `mintty -P on`.

i will do so asap; thank you kind tty!

**Comment by dankamongmen** [comment]
alright, I've added a FAQ entry about `mintty -P on` (thanks @mintty!). ideally, we would detect the absence of ConPTY, and exit out rather than locking up. still more ideally, we would do whatever vim is doing to work in unmodified MSYS. this works for now.
