### ISSUE TITLE
C++ wrappers

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#212]
I grow wear of C-style error checking in demos etc. We should publish and maintain a canonical set of C++ wrappers. They should be referenced in the primary README, but the API reference ought take the form of another document. My three primary thoughts here are:

(1) as close to a header-only implementation as is possible, very thin wrapper
(2) the primary goal is to replace tedious error checking with exceptions
(3) they ought be logically separate from the C core. ideally, they won't have any data access that regular client code doesn't have (i.e., don't go poking around inside ncplanes or the notcurses object). it ought be possible to disable installation of C++ headers (though by default they will be installed). they probably ought generate a distinct Debian package (again, ideally only a `-dev` package since this would ideally be a headers-only implementation).

@grendello let me know via private communication that he was working on this, so i'll leave it in his court for the time being.

**Comment by dankamongmen** [comment]
Just saw an email from @grendello that I'd apparently missed for two weeks or so. Gonna respond to that -- ideally we'd get these in 1.1.0.

BTW, i didn't mention it above, but we'd definitely want to introduce RAII as part of this effort.

**Comment by grendello** [comment]
The wrappers are up for review: https://github.com/grendello/notcursespp

**Comment by dankamongmen** [comment]
Hey @grendello , ideally this would be packaged with the main library IMHO (and the current C++ tools would be updated to use it -- `notcurses-planereel`, `notcurses-view`, and `notcurses-input`. Are you opposed to including this in the main library? If not, can you make it a fork and PR? Sorry for the annoyance :(.

**Comment by grendello** [comment]
Yep, I think it makes sense putting it directly in this repo. Will open the PR when I get some free time, hopefully soon

**Comment by dankamongmen** [comment]
https://github.com/dankamongmen/notcurses/pull/265 has been merged thanks to the HUGE effort from @grendello. Happy to have you aboard, my man.

**Comment by grendello** [comment]
Hey, cool! :)) Glad to be able to contribute something :) I'll keep an eye on changes to the C API, but if I miss something, ping me and I'll update ASAP :)
