### ISSUE TITLE
take advantage of kitty keyboard protocol

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2131]
I thought i had a bug on this, but i guess not? https://sw.kovidgoyal.net/kitty/keyboard-protocol/ seems a reasonable thing to support. it would have a few parts:

* [x] move to the alternate screen before doing queries
* [x] lex the kitty protocol elements
* [x] query for support with `CSI ? u`
* [x] watch for support response of form `CSI ? flags u`
* [x] request stepup with `CSI = flags ; 1 u`
* [x] push the current keyboard handling state at startup with `CSI > u`
* [x] pop the keyboard handling state at exit with `CSI < u`
* [ ] synthesize SIGINT and SIGQUIT

so throw the query into our initial query string. initialize `keyflags` to 0. if we get a `CSI ? flags u` response, write `flags` to `keyflags`, and emit stepup `CSI = flags ; 1 u` and push `CSI > u`.

decode the inputs regardless of what flags said.

at exit, if we pushed, pop with `CSI < u`.

**Comment by dankamongmen** [comment]
looks like the kitty keyboard protocol disables the standard line discipline:

> With this flag turned on, all key events that do not generate text are represented in one of the following two forms:
CSI number; modifier u
CSI 1; modifier [~ABCDEFHPQRS]
This makes it very easy to parse key events in an application. In particular, ctrl+c will no longer generate the SIGINT signal, but instead be delivered as a CSI u escape code.

**Comment by dankamongmen** [comment]
i've started the `dankamongmen/kitty-keyboard` branch for this.

**Comment by dankamongmen** [comment]
looks like we also need to make the switch to the alternate screen (if we intend to do it) before sending any of this, as the keyboard context is per-screen. added another item.

**Comment by dankamongmen** [comment]
looks like there's some limited support for this using `XTMODKEYS`, of which i was unaware.

**Comment by dankamongmen** [comment]
yeah we definitely need to move our push and set after `smcup`; this is why we remain in markedup mode following exit from `notcurses-input` currently.

**Comment by dankamongmen** [comment]
shit, this means we can't do `setupterm()` after sending the query string. unless we hardcoded `smcup` and always fired it off....gross, but that *would* work.

**Comment by dankamongmen** [comment]
we need to leave the alternate screen in most `interrogate_terminfo()` failures now...

**Comment by dankamongmen** [comment]
alright, i've completed the handling of level 1, except we need to turn ctrl+{c, q, \} into SIGINT and friends.

**Comment by dankamongmen** [comment]
hrmmm, arrow keys are having unexpected results.

**Comment by dankamongmen** [comment]
regarding synthesis of `SIGINT` and friends...if we want to do this properly, we need to do it immediately, not based on when the client asks for input. this pretty much mandates our own input thread. this is probably a good idea anyway, for a number of reasons. let's make an issue for it.

**Comment by dankamongmen** [comment]
I'm moving this back to 3.0.0, but it'll be the first thing we work on post 2.4.0, after finishing the necessary prework in #2136. With that said, I think I want to move the improved automaton into 2.4.0, so I'll do a partial merge today.

**Comment by dankamongmen** [comment]
i merged up the automaton work.

**Comment by dankamongmen** [comment]
> i merged up the automaton work.

this is resolved if we add the windows special keys, oddly enough....

**Comment by dankamongmen** [comment]
here's a problem: F1 is generating `\e[Pu`, when it seems it ought be generating SS3 P (from the kitty docs) or '\e[OP` (the terminfo value). @kovidgoyal, any idea?

**Comment by kovidgoyal** [comment]
F1-F4 are affected by cursor key mode. smcup/rmcup in terminfo.

**Comment by dankamongmen** [comment]
> F1-F4 are affected by cursor key mode. smcup/rmcup in terminfo.

right, so i would expect (from the table at https://sw.kovidgoyal.net/kitty/keyboard-protocol/#legacy-functional-keys) SS3 P for F1, but i'm instead getting CSI P. kf1 is `\e[OP`. i also see `F1 1 P or 11 ~` under https://sw.kovidgoyal.net/kitty/keyboard-protocol/#functional-key-definitions, but nowhere do i see CSI P, which is what i'm receiving.

**Comment by dankamongmen** [comment]
indeed under "Bugs in fixterms" you've got "Incorrectly claims special keys are sometimes encoded using CSI letter encodings when it is actually SS3 letter in all terminals newer than a VT-52, which is pretty much everything.", but i'm receiving CSI, not SS3.

**Comment by kovidgoyal** [comment]
For F1 I get

kitty sh -c "tput smkx; showkey -a"

```
^[OP 	27 0033 0x1b
 	79 0117 0x4f
 	80 0120 0x50
```

**Comment by kovidgoyal** [comment]
Or are you saying you are getting the CSI form with the first level of disambiguate?

**Comment by dankamongmen** [comment]
> Or are you saying you are getting the CSI form with the first level of disambiguate?

^^^^ this

**Comment by dankamongmen** [comment]
ie i have sent smcup followed by `\e=1u` by this time, and have not sent rmcup.

**Comment by dankamongmen** [comment]
Press any keys - Ctrl-D will terminate this program

^[[P 	27 0033 0x1b
 	91 0133 0x5b
 	80 0120 0x50

**Comment by kovidgoyal** [comment]
yes that's by design, the SS3 encoding is legacy mode only. in
disambiguate mode all the function keys use CSI. This is documented in
https://sw.kovidgoyal.net/kitty/keyboard-protocol/#functional-key-definitions

In any case notcurses should support all three forms to cover the widest
collection of terminals. They are all unique, so there is no issue with
that.

**Comment by dankamongmen** [comment]
> In any case notcurses should support all three forms to cover the widest
> collection of terminals. They are all unique, so there is no issue with
> that.

.nodnod, that's exactly my intention

> yes that's by design, the SS3 encoding is legacy mode only. in
> disambiguate mode all the function keys use CSI. This is documented in
> https://sw.kovidgoyal.net/kitty/keyboard-protocol/#functional-key-definitions

it says `F1 1 P or 11 ~`, but i'm just getting CSI P, *not* CSI 1 P.

**Comment by kovidgoyal** [comment]
yes 1 is the default if no number is specified. Press a modifier and you will see the 1

**Comment by dankamongmen** [comment]
ahh.

**Comment by dankamongmen** [comment]
alright, we're once again handling all function keys in all known configurations. need to get this `127u` alias for backspace.

**Comment by dankamongmen** [comment]
I think we're good to go for a merge here. I think there's a few more definitions I've not yet added, which we'll want to. Synthesis of signals is critical, but can't really be done properly until #2136 is complete, which I don't intend to do in 2.4.0.
