### ISSUE TITLE
ncneofetch on macOS always claims Big Sur

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2158]
See #2138 for background information. Right now, "Big Sur" is hardcoded in `fetch.c`. We ought look up the proper, real version of macOS. Thanks @dandee for pointing this out!

**Comment by dankamongmen** [comment]
yeah, sure enough:

```c
static const distro_info*                                                                                        
xnu_ncneofetch(fetched_info* fi){                                                                                
  static distro_info fbsd = {                                                                                    
    .name = "OS X",                                                                                              
    .logofile = "/System/Library/PrivateFrameworks/LoginUIKit.framework/Versions/A/Frameworks/LoginUICore.framewo
  };                                                                                                             
  fi->neologo = get_neofetch_art("Darwin");                                                                      
  fi->distro_pretty = strdup("OS X 11.4 (Big Sur)"); // FIXME                                                    
  return &fbsd;                                                                                                  
}         
```

**Comment by dankamongmen** [comment]
hrmmm, the `kern.osrelease` sysctl returns 20.5.0, which is the XNU version and not the macOS version...

**Comment by dankamongmen** [comment]
would `kern.osproductversioncompat: 10.16` be the correct thing?

**Comment by dankamongmen** [comment]
```
[cobra-la](0) $ sysctl -a | grep osproductversion
kern.osproductversion: 11.4
kern.osproductversioncompat: 10.16
[cobra-la](0) $ 
```

so `kern.osproductversion` is probably what we want

**Comment by dankamongmen** [comment]
i don't have any idea how we'd get the "Big Sur" etc without some kind of mapping table, for which i don't have the data, but we're now printing:

"macOS 11.4"

acquired using `sysctlbyname`. the only worry is that this might be new 11.x functionality, in which case, well, if we build somewhere without it, we'll hopefully get a bug report.

**Comment by dandee** [comment]
For more detailed OS version you could use something like that:

```
#include <Carbon/Carbon.h>

NSString *operatingSystemVersionString = [[NSProcessInfo processInfo] operatingSystemVersionString];

printf("macOS %s", [operatingSystemVersionString UTF8String]);
```

to get:

```
macOS Version 10.14.6 (Build 18G9323)
```

**Comment by dankamongmen** [comment]
> NSString *operatingSystemVersionString = [[NSProcessInfo processInfo] operatingSystemVersionString];

whoa what kind of syntax is that?! is that some apple extension they built into clang? i've never seen C like that.

**Comment by dankamongmen** [comment]
btw @dandee did this work properly on your machine? if you have time to test

**Comment by dandee** [comment]
That's Objective-C code that can be used alongside C/C++ (when you rename your source code file to .mm) It works on my machine, it's a part of my hobby project :)

**Comment by michaelsbradleyjr** [comment]
> i don't have any idea how we'd get the "Big Sur" etc without some kind of mapping table, for which i don't have the data...

See: https://en.wikipedia.org/wiki/Macintosh_operating_systems#Desktop
