### ISSUE TITLE
nonblocking input doesn't work

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#2169]
with the latest source, all the examples using ncinput via rust bindings stopped working well. For example [full-input.rs](https://github.com/dankamongmen/notcurses/blob/master/rust/examples/full-input.rs) is a minimal example.

And in the notcurses-rs repo, all the plotters examples stopped responding to input, and they also don't refresh the visuals anymore when they.

Examples:
```
cargo re plotters-systemstat --features="plotters,systemstat"
cargo re plotters-examples --features="plotters"
cargo re plotters-3d-projection --features="plotters"
```

I've just replaced the usage of notcurses_getc by notcurses_get in the bindings but that doesn't seem to make any difference.

**Comment by dankamongmen** [comment]
erp! alrightie, i might revert the input thread commit. it's pretty experimental, though i'm not seeing such bad problems with it myself...

the plotters definitely oughtn't be affected. strange.

**Comment by dankamongmen** [comment]
if you have time, it would be nice to know if the plots in `notcurses-demo` and `notcurses-input` are working for you. they definitely are for me.

**Comment by joseluis** [comment]
> if you have time, it would be nice to know if the plots in `notcurses-demo` and `notcurses-input` are working for you. they definitely are for me.

yeah, they seem to work well, both the plots and the input.

but when I ran notcurses-demo in wezterm, I think during the uniblock part I had **hundreds** of popups like this appear in my screen, 
![image](https://user-images.githubusercontent.com/5832068/133605812-37e036a5-1d5e-42a7-b473-83d9af4b9873.png).  I've added the `warn_about_missing_glyphs=false` setting, but just so you're aware that's a thing.

**Comment by joseluis** [comment]
> the plotters definitely oughtn't be affected. strange.

I'm sorry, I'm not referring to the notcurses plotters. But to to the examples that use the plotters rust crate, that I named them plotters-*. those examples have input and that's what's stopped working.

I haven't created the bindings to the notcurses plotter yet.

**Comment by dankamongmen** [comment]
> > if you have time, it would be nice to know if the plots in `notcurses-demo` and `notcurses-input` are working for you. they definitely are for me.
> 
> yeah, they seem to work well, both the plots and the input.
> 
> but when I ran notcurses-demo in wezterm, I think during the uniblock part I had **hundreds** of popups like this appear in my screen,
> ![image](https://user-images.githubusercontent.com/5832068/133605812-37e036a5-1d5e-42a7-b473-83d9af4b9873.png). I've added the `warn_about_missing_glyphs=false` setting, but just so you're aware that's a thing.

yeah you can get rid of them with `warn_about_missing_glyphs`:

```
[schwarzgerat](0) $ cat ~/.config/wezterm/wezterm.lua 
local config = {
  warn_about_missing_glyphs = false,
  enable_kitty_graphics = true,
}
return config
[schwarzgerat](0) $ 
```

or by setting up font fallback to unifont (i think). `uniblocks` runs slow as hell in wezterm, and i'm unsure why.

**Comment by dankamongmen** [comment]
> I'm sorry, I'm not referring to the notcurses plotters. But to to the examples that use the plotters rust crate, that I named them plotters-*. those examples have input and that's what's stopped working.
> 
> I haven't created the bindings to the notcurses plotter yet.

ahhh ok so just graphics. so probably (possibly) along the same lines as #2170. good deal.

**Comment by joseluis** [comment]
Ok more details regarding the input issues.

blocking input works well, but nonblocking always returns -1. For example:
```rust
    let mut input3 = NcInput::new_empty();
    let ts = ffi::timespec { tv_sec: 0, tv_nsec: 0 };
    loop {
        println!("before nblock");
        let key = unsafe {
            notcurses_get(nc, &ts, &mut input3) // is returning -1
        };
        println!("after nblock. key = `{}` ({})", key, key as i32);
        match key {
            032..=127 => break,
            _ => (),
        }
        sleep![0, 100];
    }
```

only loops one time and gets unresponsive the second time notcurses_get() is called. This is the result:
```
before nblock
after nblock. key = `4294967295` (-1)
before nblock

```

**Comment by joseluis** [comment]
BTW we can migrate this issue to the new repository if you think it's more appropriate there.

**Comment by dankamongmen** [comment]
nah let me look into it, very possibly my problem

**Comment by dankamongmen** [comment]
just gotta look at it later, working for the moment

**Comment by dankamongmen** [comment]
ok, i forgot `pthread_timed_condwait()` directly returns its `errno`s. fixed that up. thanks for finding that!

**Comment by dankamongmen** [comment]
i expect that this fixes your nonblocking input problems. please reopen if not.

**Comment by joseluis** [comment]
> i expect that this fixes your nonblocking input problems. please reopen if not.

It's not fixed yet. It keeps getting frozen on subsequent calls. The only change is that the function now returns 0 the first time.
```
before nblock
after nblock. key = `0` (0)
before nblock
```

**Comment by dankamongmen** [comment]
i can reproduce locally, thanks

**Comment by dankamongmen** [comment]
oh i see what's up. we're using an absolute deadline now, as opposed to a delay bound. i probably need to restore the old behavior, though the newer behavior is in ways better. let me get that fixed up.

**Comment by dankamongmen** [comment]
so yeah sending {0, 0} for the timeout means you're always going to time out. that's why you're not getting any data. alright, will fix.

**Comment by joseluis** [comment]
Good!

BTW is that timeout struct supposed to be configurable and useful for the lib users? Or doesn't need to be public for anything?

**Comment by dankamongmen** [comment]
i'm not sure what you mean. they must be able to decide what goes into that struct, yes. oh! maybe you're missing the fact that it provides a bounded, non-trivial wait. you can say `tv_sec = 5, .tv_nsec=0` and block for up to 5 seconds. does that answer your question?

**Comment by dankamongmen** [comment]
fixed, updated documentation

**Comment by joseluis** [comment]
> i'm not sure what you mean. they must be able to decide what goes into that struct, yes. oh! maybe you're missing the fact that it provides a bounded, non-trivial wait. you can say `tv_sec = 5, .tv_nsec=0` and block for up to 5 seconds. does that answer your question?

Maybe, I mean... I've only seen it used for `*_get_nblock` functions with {0, 0}. But since `_get` accepts it as a parameter one could customize it... I have to play with it to undestand the effect.

IIUC setting timespec with 1 second would be equivalent to the old delay behaviour of `*_get_nblock` + 1 second sleep, right?

**Comment by joseluis** [comment]
> fixed, updated documentation

it's not commited to the master branch. But I've tried compiling the new branch and it does seem to fix it for me :) good work

**Comment by dankamongmen** [comment]
> it's not commited to the master branch. But I've tried compiling the new branch and it does seem to fix it for me :) good work

![losin-my-motherfuckin-mind](https://user-images.githubusercontent.com/143473/133845084-dcc55558-6c40-4850-b2b0-752365202aa5.jpg)
