### ISSUE TITLE
unite our two control sequence automata

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2183]
We have two automata we traverse to handle control escapes -- the one handled by `pump_control_read()`, and the special key trie. as a result, we have two distinct control loops, and two distinct states. this last is horrible, as there's no well-defined map of state changes effected by one on the other.

unite these two automata. given that special keys require a dynamic state machine (it's prepared based on terminfo data), a wholly explicit controlflow-based automaton (like that used in `pump_control_read()`) won't work. we need a dataflow-based one, as used by our trie traversal.

so we'll need add some special node types to our trie, basically the same we have from the other automaton:
* accumulate a number
* accumulate a string
* accumulate a hex-encoded string, which is just a special case of either of the previous 2
...and that's it, i think? pretty easy. let's do it up right

**Comment by dankamongmen** [comment]
so right now a trienode just has an (optional) Σ-index (there is no index on terminating nodes). we will add a word for an aggregated numeric, string (pointer), an `NCKEY`, or function pointer to each node. since no sequences end in numerics or strings, this ought be sufficient for all nodes. the function pointer indicates an accepting state, and is invoked upon transition (since there are no valid prefixes, all accepting states are terminal states). we'll need a 4-way type; this can be two bits, but we'll likely just use a full int:

TRIE_NUMERIC
TRIE_STRING
TRIE_SPECIAL
TRIE_FXN

where `TRIE_SPECIAL` combined with `NCKEY_INVALID` (0) indicates a transitory node.

state-wise, we'll want an array of trienode pointers, equivalent in length to the longest path in the trie. we can calculate this as we build the trie, and allocate the array upon completion of trie construction. from this path plus the in-trie state, we can recreate any path without keeping the actual characters, meaning we can replay failed escapes as input without keeping external state.

Escape is handled distinctly, and always takes us to the `STATE_ESCAPE` node. this way we needn't have a Σ-index on terminal nodes, saving memory (each index is about 1K, with 128 ways and 8 bytes per pointer). Escape remains the initial node; we are **not** going to process standard UTF8 via the control trie. upon an escape while in-trie, we replay the path and return to ESC. upon a standard termination (non-0 `TRIE_SPECIAL` or any `TRIE_FXN`), we play in the special or execute on the fxn, and then move to NULL (do **not** move directly to `STATE_ESCAPE`).

we'll break apart the control-flow automaton, turning them into functions invoked on `TRIE_FXN` and (possibly manual) constructions. i don't think it's worth coming up with a little regexy DSL to do algorithmic construction -- there simply aren't enough `TRIE_FXN`s.

so for instance let's say we need recognize `\e[num:num:numu`, that would be

`NULL` Esc-> `STATE_ESC` [-> `STATE_CSI` 0-9-> `TRIE_NUMERIC`
 0-9-> loop
 :-> `TRIE_SPECIAL`[0] 0-9-> `TRIE_NUMERIC`
  0-9->loop
  :-> `TRIE_SPECIAL`[0] 0-9-> `TRIE_NUMERIC`
   0-9->loop
   u-> `TRIE_FXN`

where that `TRIE_FXN` takes the three aggregated numerics, evaluates them, and calls the relevant function. we then move back to `NULL`. any Escape along the way moves us to `STATE_ESC` following a replay along the path. any invalid follow moves us to `NULL` following a replay along the path.

that ought work.

**Comment by dankamongmen** [comment]
also, trienodes ought hold an `ncinput`, not their own weird assemblage of `ncinput`.

**Comment by dankamongmen** [comment]
ok, i've gotta stop tonight, but very good progress. i've gone ahead and done a DSL, with `\N` as a numeric accumulator, `\S` as a string accumulator, and literals otherwise. we'll want `\H` as the hash, and we might need a Kleene closure for drainage purposes. the constaints for numeric transitions are too tight right now--i've had to comment out the special keys for now, but we'll need add them back. that same principle would apply to any Kleene.

i've converted about half of the CF automaton over to DF -- mouse, kitty, cursor location, and geometry.

when using the kitty protocol, we probably ought not try to match old-school alts/ctrls.

so this will be done soon. `dankamongmen/unifytries` branch.

**Comment by dankamongmen** [comment]
well, we have verified that unknown sequences even when interleaved with the initial query responses now get replayed as input, which is good! exactly what we expected.

![2021-09-23-233808_910x1057_scrot](https://user-images.githubusercontent.com/143473/134614435-b880a500-8d58-48d4-a5a6-59ae56d2a4d1.png)

**Comment by dankamongmen** [comment]
we're now starting up despite entirely bypassing `pump_control_read()`, yay! we'll be done soon.

**Comment by dankamongmen** [comment]
so we still need convert:
* SUM support
* remainder of DA1
* DA2
* XTGETTCAP
* XTVERSION

which means implementing `\S` for ST_terminated string and `\H` for hash-encoded string. and then i do believe we're done!

**Comment by dankamongmen** [comment]
a gigantic pain in the ass, this has been, but it's worth it.

one issue i'm running into now is that we've got e.g. `\e[\N;\N;\Nt` for the geometry callbacks. problem is, we've also got `\e[2~` and friends as special keys. the way we currently operate, the first is going to build the following automaton:

esc -> csi ->[0-9] numeric -> semi...
                     numeric->[0-9] self
                     
so there's just three nodes until the semi, with the csi taking all numeric paths to the third node, and it taking all numeric paths back to itself. we then come along and try to add `\e[2~`, and run right into said numeric. the true expansion would be:

esc -> csi -> 2 -> tilde(term)
                        2->[0-9] numeric
csi->[0-1,3-9] numeric

so how do we get there from here without building up a full Glushkov engine? if we built the cflow following the special keys, that would be a good start; we'd have the static automaton already detailed. so assuming that, we come in with:

esc -> csi -> 2 -> tilde(term)

and need to add the other links. i think that's easy enough: at the node where we transition to numeric, see if we have an existing transition to a numeric. if so, take it. otherwise, see if we have any existing numeric *links* (i.e. a numeric candidate to something other than a `TYPE_NUMERIC` node). if not, create a new `TYPE_NUMERIC`, and add all 10 links. if we do, see if there are any missing numeric links. if there are, create a new `TYPE_NUMERIC` and fill them in. then, follow all existing numeric links, and fill in any missing numeric links so that they go to this new node. follow the automaton out through any existing numeric links, repeating this pattern.

erp!

beyond that: we're properly extracting versions now. we're properly extracting all geometries. we're properly extracting kitty graphics messages. we're properly extracting sixel. we still need support \H for hex-encoded data, at which point we'll get XTGETTCAP. i've not yet ported DA2, i've not yet ported the alacritty-specific logic, and i think my DA1 port is incomplete. closing in on done, though.

**Comment by dankamongmen** [comment]
i've completed out the DA1 handling, though it requires fixing the numeric problem described above.

**Comment by dankamongmen** [comment]
first light! `notcurses-info` now starts and runs just fine in an XTerm. well, almost fine -- it doesn't print the init banner. but everything else appears to work, including default background discovery, sixel discovery, etc., and no responses are leaked through.

on kitty, we're still leaking some through.

just about done =].

**Comment by dankamongmen** [comment]
ok, i'm now taking up the kitty keyboard response, but we're getting the wrong value. we *do* need the array of movements to reconstruct this kind of thing, as we need to return to the correct node to pick up `->number`, ugh. on the plus side, this will eliminate all the boilerplate crap currently leading each callback.

**Comment by dankamongmen** [comment]
man, this is a much harder problem than i thought at first, ugh

**Comment by dankamongmen** [comment]
we've got kitty starting without any runoff now, though we need to break down XTGETTCAP still:

`tcap_cb:766:TCAP: 544e=787465726d2d6b69747479`

**Comment by dankamongmen** [comment]
issues still seen:

* [ ] XTerm bleeds through the back half of its DA1 (seen in `notcurses-input`)
* [ ] Kitty bleeds through cursor reports (seen in `notcurses-info`)
* [ ] XTerm doesn't print the intro banner until we're at the bottom of the screen (`notcurses-info`)
* [ ] WezTerm's DA1 doesn't reach terminating state, and thus doesn't start (`notcurses-info`)
* [ ] Alacritty bleeds through a `\e[?1;2S` in `notcurses-input` and a cursor report in `notcurses-info`

**Comment by dankamongmen** [comment]
got the cursor report bleeding staunched

**Comment by dankamongmen** [comment]
the alacritty bleedthrough is `\e[?1;2S`, so apparently one can't reduce the number of color registers in Alacritty, which answers a question i've had since @christianparpart asked #2065. anyway let's expand the automaton to handle that...

**Comment by dankamongmen** [comment]
got it, no more leakage in alacritty nor kitty

**Comment by dankamongmen** [comment]
alacritty version is now recognized

**Comment by dankamongmen** [comment]
wezterm DA1 is `\e[?65;4;6;18;22c`

**Comment by dankamongmen** [comment]
oh interesting that's outside the DA1 responses listed in https://invisible-island.net/xterm/ctlseqs/ctlseqs.html. is that intended @wez? it's no problem, just a bit surprising.

**Comment by dankamongmen** [comment]
wezterm now starts just fine

**Comment by dankamongmen** [comment]
ahhh, we bleed a bit in wezterm, thoguh: `\e[=00000000\;6;18;22c`. that looks like DA3/TDA?

**Comment by dankamongmen** [comment]
wait no that's `\e[=00000000\e\\` (i.e. terminated with ST) and then the rest is probably coming off of DA1 or something.

**Comment by dankamongmen** [comment]
the bleed on wezterm is now down to `;6;18;22c`

**Comment by dankamongmen** [comment]
i think our drain (`\D`) is calling its function too early

**Comment by wez** [comment]
> oh interesting that's outside the DA1 responses listed in https://invisible-island.net/xterm/ctlseqs/ctlseqs.html. is that intended @wez? it's no problem, just a bit surprising.

The 65?  I can't remember where I got that from, but the comments here suggest that I knew that it meant vt500:

https://github.com/wez/wezterm/blob/ca89181098d10dbb82ccfb1cd4945f48a1293a9b/term/src/terminalstate/mod.rs#L1036-L1041

**Comment by dankamongmen** [comment]
https://github.com/wez/wezterm/blob/ca89181098d10dbb82ccfb1cd4945f48a1293a9b/term/src/terminalstate/mod.rs#L1036-L1041

VT510 is claimed to be 64 [here](https://vt100.net/docs/vt510-rm/DA1.html), not that i care nor think you ought

VT525 claims 65 [here](http://web.mit.edu/dosathena/doc/www/ek-vt520-rm.pdf), 64 for VT520

looks like VTE returns 65

may a thousand flowers bloom

**Comment by wez** [comment]
<img src="https://media2.giphy.com/media/l0G16Wn8gB6nkYTHW/giphy.gif?cid=790b76119a46105522b8d3b33bab05d1d0c2645e9948d9f6&rid=giphy.gif&ct=g">

**Comment by dankamongmen** [comment]
https://user-images.githubusercontent.com/143473/135388705-8ea73ed3-bbfa-49c5-b10c-972dc5c92036.mp4

**Comment by dankamongmen** [comment]
wezterm now starts without any bleed, 'twas a bug in our Kleene reduction

**Comment by dankamongmen** [comment]
this also fixed the XTerm bleed. i no longer see bleeding with any terminal. =]

**Comment by dankamongmen** [comment]
btw wez while i've got your attention, i added some info to https://github.com/wez/wezterm/issues/1063

**Comment by dankamongmen** [comment]
mlterm bleeds with `\e[?1;3;0S`

**Comment by dankamongmen** [comment]
mlterm is handled

**Comment by dankamongmen** [comment]
st is fine

**Comment by dankamongmen** [comment]
VTE bleed: `\e[?1;1S\e[?2;1S\e[?1;1S`

**Comment by dankamongmen** [comment]
no more bleed for VTE

**Comment by dankamongmen** [comment]
hyper is fine

**Comment by dankamongmen** [comment]
contour is fine

**Comment by dankamongmen** [comment]
so we only have one more problem that i see: in all terminals, the intro banner is printed over, unless we're at the bottom. presumably a missing cursor location lookup in `init_banner()`?

**Comment by dankamongmen** [comment]
hrmmm. when redirected, and we then cat the redirected output, the same thing happens with 2.4.3 (which does *not* exhibit this behavior when not redirected). maybe this is related to #2114?

**Comment by dankamongmen** [comment]
got the last issue resolved. =]

**Comment by dankamongmen** [comment]
nope, one more problem: we're getting a stray 'u' in `notcurses-demo` on kitty only.

**Comment by dankamongmen** [comment]
ok, if i throw a `sleep()` in before the render in `notcurses-info`, and press ctrl-c, the `u` is printed following the ctrl-c:

![2021-09-30-040208_1453x448_scrot](https://user-images.githubusercontent.com/143473/135412291-efa2c4e1-86c3-4850-8cac-606060204d67.png)

**Comment by dankamongmen** [comment]
hrmmmm it seems to be `KKEYBOARD_POP`...

**Comment by dankamongmen** [comment]
oh this is an old version of kitty (0.19.3). yeah, looks like popping the keyboard protocol results in a `u` in 0.19.3 (it looks like the keyboard protocol was introduced in 0.20.0):

```
[schwarzgerat](0) $ echo -e '\e[<u'
u
[schwarzgerat](0) $ 
```

**Comment by dankamongmen** [comment]
we should probably just refrain from emitting a `KKEYBOARD_POP` unless we got a response to `\e[?u`. We're currently sending it unconditionally.

**Comment by dankamongmen** [comment]
got it, fixed
