### ISSUE TITLE
new input subsystem is broken on windows

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2192]
Since introducing the new input subsystem, no Notcurses programs start on Windows, either in the MSYS environment or Windows Terminal. In both cases, we're blocking on terminal responses.

**Comment by dankamongmen** [comment]
ok, i've got `notcurses-input` working now, except that we lock up at shutdown. does posix cancellation work on windows?

**Comment by dankamongmen** [comment]
achieving the above requires setting `rifd` high no matter the response from `WaitForMultipleObjects()` (it's currently always returning no events). so i'd rather get that latter fixed.

**Comment by dankamongmen** [comment]
looks like we're drawing `ERROR_INVALID_HANDLE` (6).

**Comment by dankamongmen** [comment]
we weren't initializing `ictx->stdinhandle`. that helps =].

**Comment by dankamongmen** [comment]
ok, yeah, `notcurses-input` now works without any other changes. we're still seeing the failure on shutdown.

**Comment by dankamongmen** [comment]
alright, for now i'm just skipping destruction of the input layer on windows. this is obviously an unacceptable longterm solution, but we need to get 2.4.2 out.

**Comment by dankamongmen** [comment]
huh, it seems to be working fine now? at least in Windows Terminal. hrmmm.

**Comment by dankamongmen** [comment]
redirection from a file does *not* work, but everything else seems to run fine

**Comment by WSLUser** [comment]
> does posix cancellation work on windows?

The NT kernel does support some POSIX syscalls since at it's root origins, it provided a POSIX layer. Win11 may be different but I think that support remains. Would need to dig deeper into the history of Windows (again) to see what POSIX support exists and how much of it remains available for use today.

**Comment by WSLUser** [comment]
> redirection from a file does not work, but everything else seems to run fine

You should be able to resolve that. You need to call a Windows API for that.

On a side note, since minimal AF_Unix support exists on Windows, how much easier might that make things for you in general?

**Comment by dankamongmen** [comment]
alright, master is working great. let's make a new bug on the redirection from file issue, but windows is alive once more.
