### ISSUE TITLE
fixing stylemask related functions parameter & return type

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#2200]
I started fixing `ncdirect_styles` parameter to be const, like the analogous `ncplane_styles` function, but then I've found more related things I could fix a little. So I changed the return type to `uint16_t` for the public API functions that return a stylemask. Those are `nccell_styles`, `ncdirect_styles`, `ncdirect_supported_styles` and `notcurses_supported_styles`.

What I've not dared to change are the private `unsigned supported_styles` field from the `tinfo` structure in the `termdesc.h` file, nor the `term_supported_styles` return type, but maybe they ought to be updated too.

**Comment by dankamongmen** [comment]
whooooooa there homie; why are you exporting anything from `termdesc.h`? that's not installed, and is not suitable for external inclusion.

**Comment by joseluis** [comment]
> whooooooa there homie; why are you exporting anything from `termdesc.h`? that's not installed, and is not suitable for external inclusion.

not exporting that, just diving into the rabbit hole from the public api to see the root of the declared types... I wasn't sure whether just casting to u16 was enough.

Is what I actually did in the commits ok?

**Comment by dankamongmen** [comment]
> Is what I actually did in the commits ok?

no. you've broken ABI compatibility, i believe.

a program already compiled against notcurses will be expected an
unsigned to be returned. without a recompile, it will handle the
new, likely smaller return value improperly.

also, whenever you change public function signatures, they need
be updated in the USAGE.md and man pages in doc/man/man3.

**Comment by joseluis** [comment]
I'm sorry, I've reverted the changes.

**Comment by dankamongmen** [comment]
> I'm sorry, I've reverted the changes.

no problem, man, thanks!

**Comment by joseluis** [comment]
Would you like to leave this open to tackle this somewhen in the future?

**Comment by dankamongmen** [comment]
I've gone ahead and added this to #1777, where I'm listing all the things to change upon movement to ABI3. I'l go ahead and close this one up. In the meantime, you may assume that no values greater than 0xffff will be returned from these functions.
