### ISSUE TITLE
switch DECSDM default over

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2204]
Most terminals I regularly work with have adapted to the true semantics of DECSDM (see #1782 and @j4james). we should probably go ahead and shift our default over, and track terminals which invert the "new" semantics.

i had already made the change for XTerm-369, though that change has not yet been released.

**Comment by dankamongmen** [comment]
so as i'm understanding it:

When Sixel Scrolling is enabled, the sixel is emitted at the current cursor location, and a displayed sixel will scroll the terminal as necessary. Sixel Scrolling is also known as DECSDM.
80l will be understood to *enable* Sixel Scrolling
80h will be understood to *disable* Sixel Scrolling

unfortunately, many terminals interpret this in an inverted sense, where 80h enables the mode, and 80l disables the mode.

so emitting 80l will sometimes enable DECSDM, and sometimes disable DECSDM. what about the defaults? well, even at patchlevel 359, with DECSDM correctly set by 80l, XTerm appears to default to **no** sixel scrolling. so even if we were willing to assume the default to still be in play, it's not reliable. so we need to emit something.

so, from now on, we'll emit 80l in the hope of getting people to switch over (i.e. if they work the old way, Notcurses will be obviously buggy). it would be nice if we could get a terminfo capability for this, but i'm not holding my breath, so we'll have to just special-case old versions as we come across them.

i'm going to go ahead and make these changes tonight.

**Comment by j4james** [comment]
> XTerm appears to default to no sixel scrolling. so even if we were willing to assume the default to still be in play, it's not reliable. so we need to emit something.

Sorry I forgot to mention this. Thomas has actually committed a fix for this already. It's a bit weird, because there's a `sixelScrolling` option which is now essentially backwards (if I'm reading the code correctly). But at least the default behaviour is correct, and `DECSDM` works correctly, so I'm not going to complain.

**Comment by dankamongmen** [comment]
> Sorry I forgot to mention this. Thomas has actually committed a fix for this already. It's a bit weird, because there's a `sixelScrolling` option which is now essentially backwards (if I'm reading the code correctly). But at least the default behaviour is correct, and `DECSDM` works correctly, so I'm not going to complain.

eh, that doesn't mean everyone else has a good default, or that no one has changed it before us, so it wouldn't really change anything. good to hear regarding Grandmaster Dickey, though.

**Comment by dankamongmen** [comment]
> When Sixel Scrolling is enabled, the sixel is emitted at the current cursor location, and a displayed sixel will scroll the terminal as necessary. Sixel Scrolling is also known as DECSDM.
> 80l will be understood to _enable_ Sixel Scrolling
> 80h will be understood to _disable_ Sixel Scrolling

this was all backwards, anyone reading it in the future

**Comment by klamonte** [comment]
Is there an option to get notcurses-demo to not touch DECSDM at all?

It seems like it tries to fingerprint xterm, and if it sees version < 370 issue CSI ? 80 l, otherwise CSI ? 80 h.

The bad news is that terminals that are not fingerprinted correctly but _do_ the correct DECSDM behavior will have 80h sent to them, and then Natasha and the spaceships are stuck in the corner. :(

**Comment by dankamongmen** [comment]
@klamonte spake:

> Is there an option to get notcurses-demo to not touch DECSDM at all?

i am incredibly loathe to add options. nobody uses them, and those who do use them badly. let's look at this more closely...

> It seems like it tries to fingerprint xterm, and if it sees version < 370 issue CSI ? 80 l, otherwise CSI ? 80 h.

aye. this should only happen on a definite XTerm identification, i.e. i queried the terminal and it responded saying it was XTerm. i do not do this based off `TERM`, which i figure to be regularly incorrect.

> The bad news is that terminals that are not fingerprinted correctly but _do_ the correct DECSDM behavior will have 80h sent to them, and then Natasha and the spaceships are stuck in the corner. :(

by "not fingerprinted correctly", do you mean:

* i did not identify them definititvely, and am just using `TERM`, or
* i mistakenly definitively identified them as XTerm, or
* they are answering and claiming to be XTerm

the latter i would regard as an upstream bug and be very much against accommodating. the second option i can hopefully fix. the former should not be resulting in any term-specific DECSDM; i ought be using the default. if you're saying i ought use the old default, i'm maybe not opposed to that (though it will make @j4james ever so sad), since terminals which are using the correct interpretation are more likely to be correctly fingerprinted IMHO.

**Comment by dankamongmen** [comment]
> the latter i would regard as an upstream bug and be very much against accommodating. the second option i can hopefully fix. the former should not be resulting in any term-specific DECSDM; i ought be using the default. if you're saying i ought use the old default, i'm maybe not opposed to that (though it will make @j4james ever so sad), since terminals which are using the correct interpretation are more likely to be correctly fingerprinted IMHO.

or maybe you're suggesting i not set it at all by default? ehhhhh i'm not sure how i feel about that; working under the assumption that "the world copies XTerm", older terminals will generally have undesirable DECSDM semantics by default, no?

**Comment by klamonte** [comment]
I'm suggesting the default be to not to set it at all, and only issue 80h when you need DECSDM behavior.  Old terminals default to scrolling sixel, unless they support DECSDM, it which case we have to know _which_ form of DECSDM.

@j4james found me a while ago: https://gitlab.com/klamonte/jexer/-/issues/79

> So was there a reason you needed to change the mode? Regardless of how they interpret DECSDM, every terminal I've tested has had sixel scrolling enabled by default, so I wouldn't have thought it necessary to enable it explicitly.

**Comment by dankamongmen** [comment]
> > So was there a reason you needed to change the mode? Regardless of how they interpret DECSDM, every terminal I've tested has had sixel scrolling enabled by default, so I wouldn't have thought it necessary to enable it explicitly.

it was my understanding that even XTerm didn't scroll by default, and you had to set the `sixelScrolling` resource to `true`. The XTerm-370 man page contradicts me on this. if these claims are correct (and i have no reason to doubt you or @j4james), then no emission by default certainly seems a better approach.

the best approach might be a cursor location report followed by a 1-cell emission followed by a cursor location report, much like how i used to detect CLR inversion (kmscon inverts y and x, ugh).

as i recall, @dnkl gave me early feedback on this when i was but a wee lad of the terminals. care to chime in buddy?

**Comment by dankamongmen** [comment]
> the best approach might be a cursor location report followed by a 1-cell emission followed by a cursor location report, much like how i used to detect CLR inversion (kmscon inverts y and x, ugh).

(unfortunately, widespread failure to implement transparency as expected makes this a nonstarter)

**Comment by j4james** [comment]
> it was my understanding that even XTerm didn't scroll by default, and you had to set the `sixelScrolling` resource to `true`. The XTerm-370 man page contradicts me on this. if these claims are correct (and i have no reason to doubt you or @j4james), then no emission by default certainly seems a better approach.

At the time of my testing (I think around May last year), all terminals I knew off were scrolling by default, but there may have been a point further back in time where someone didn't have scrolling enabled, because that's apparently why lsix originally added the `DECSDM` sequence. I'd be surprised if you could detect a name and version number from a terminal that far back though.

> older terminals will generally have undesirable DECSDM semantics by default, no?

Again at the time of my initial testing, I think the split was exactly 50/50. The only terminal I'm aware of now that doesn't have `DECSDM` correct is Darktile, and that crashes so easily I don't think it's realistically usable for sixel.

IMO, the safest option, if you want scrolling, is to do nothing. If you really want to make sure it's turned on, though, then you should do so by disabling `DECSDM`, and only enable `DECSDM` if you're absolutely positive that you're dealing with a terminal that has it backwards.

**Comment by dankamongmen** [comment]
> IMO, the safest option, if you want scrolling, is to do nothing. If you really want to make sure it's turned on, though, then you should do so by disabling `DECSDM`, and only enable `DECSDM` if you're absolutely positive that you're dealing with a terminal that has it backwards.

yep, i think yourself and mlle klamonte have the right of it here; see @2587, which i will be implementing forthwith, definitely for 3.0.6 (i remain embroiled in #2573).

**Comment by klamonte** [comment]
> The only terminal I'm aware of now that doesn't have DECSDM correct is Darktile, and that crashes so easily I don't think it's realistically usable for sixel.

Bit of a shame because it does have sixel, but crashes or gets its mouse input messed up so quickly that it is unusable for Jexer.  I'm hoping it gets fixed and joins the rest of the survivors. ;-)

**Comment by dankamongmen** [comment]
> Again at the time of my initial testing, I think the split was exactly 50/50. The only terminal I'm aware of now that doesn't have `DECSDM` correct is Darktile, and that crashes so easily I don't think it's realistically usable for sixel.

i'm not too worried about supporting imaginary terminals

**Comment by dankamongmen** [comment]
> i'm not too worried about supporting imaginary terminals

huh, 2.7K stars, well call me an asshole

**Comment by dankamongmen** [comment]
> huh, 2.7K stars, well call me an asshole

shoulda called it danktile IMHO

**Comment by dankamongmen** [comment]
> shoulda called it danktile IMHO

```
[schwarzgerat](0) $ make
./scripts/build.sh
[schwarzgerat](0) $ 
```

[runs make]
[watches it for five seconds or so]
[no output]
[returns 0]


![download](https://user-images.githubusercontent.com/143473/151686125-f57ef41d-33e6-4ff9-9014-a198cfc25ddd.jpeg)

**Comment by dankamongmen** [comment]
how the fuck did `darktile` just corrupt the settings *of the terminal from which i launched it*? i hate this world, and everything in it

**Comment by dankamongmen** [comment]
alright yeah `darktile` aggressively crashed upon pretty much any attempt to do anything.

[![good times, good times](http://img.youtube.com/vi/l0WG0B2JYLQ/0.jpg)](http://www.youtube.com/watch?v=l0WG0B2JYLQ "good times, good times")

back to chasing perf

**Comment by j4james** [comment]
> shoulda called it danktile IMHO

It actually used to be known as "aminal" - it was listed as one of the supported terminals in the [libsixel readme](https://github.com/saitoha/libsixel/blob/6a5be8b72d84037b83a5ea838e17bcf372ab1d5f/README.md). But the new version is apparently a complete rewrite, so maybe the original version was less buggy.

**Comment by dankamongmen** [comment]
> It actually used to be known as "aminal" - it was listed as one of the supported terminals in the [libsixel readme](https://github.com/saitoha/libsixel/blob/6a5be8b72d84037b83a5ea838e17bcf372ab1d5f/README.md). But the new version is apparently a complete rewrite, so maybe the original version was less buggy.

this has been remedied at

https://github.com/libsixel/libsixel/blob/master/md/Supported%20terminals.md

thanks

**Comment by dnkl** [comment]
I think all that needs to be said has already been said here; I'm with @j4james and @klamonte ; you're probably best off by leaving DECSDM at its default value.

**Comment by klamonte** [comment]
> > i'm not too worried about supporting imaginary terminals
> 
> huh, 2.7K stars, well call me an asshole

Stars aren't everything.  And you've got 2k yourself. :)

(I've got a more cranky take on apparent popularity [here](https://gitlab.freedesktop.org/terminal-wg/specifications/-/issues/24#note_532568) when people were discussing the frustrations of getting TE authors to agree on anything...)

**Comment by dankamongmen** [comment]
> (I've got a more cranky take on apparent popularity [here](https://gitlab.freedesktop.org/terminal-wg/specifications/-/issues/24#note_532568) when people were discussing the frustrations of getting TE authors to agree on anything...)

oh i was amused. i don't get down about this shit. https://tv.getyarn.io/yarn-clip/5c56d421-414e-4044-929b-685bc0534d13
