### ISSUE TITLE
support sixel when advertised even in the absence of XTSMGRAPHICS

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2229]
see the comments by @j4james and myself in https://github.com/dankamongmen/notcurses/commit/bbb778b7de2509266761b5faf9cc7cb514581856 for necessary background information. when DA1 advertises sixel support, we ought drive it, even in the absence of an XTSMGRAPHICS response. such terminals probably only support 16 colors, with a palette shared by text, but we can drive them.

if we're going to do this, we probably ought make the number of colors accessible by client code (we might already do this, per a long-ago request of @joseluis ?), so they can decide whether 16 is unacceptable and instead manually fall back to cell blitting.

**Comment by dankamongmen** [comment]
it looks like this might apply to MinTTY, where i'm getting a VT420-style DA1 including the '4' for Sixel, but no `XTSMGRAPHICS` responses.

**Comment by dankamongmen** [comment]
pretty sure VTE has not yet been merged, right? i mean, i can obviously go check easily enough myself.

**Comment by j4james** [comment]
> pretty sure VTE has not yet been merged, right?

Yeah. A few of the Sixel implementations are on unmerged branches or forks.

**Comment by dankamongmen** [comment]
this support is actually really trivial to add, once i just swallow hard and accept i'm going to cast these poor sixels into a void of unknown color dimension.

[![yeaaaah](http://img.youtube.com/vi/j0XBlNSxyrw/0.jpg)](http://www.youtube.com/watch?v=j0XBlNSxyrw "yeaaaah")

**Comment by dankamongmen** [comment]
alright imma take a stab at this in the `dankamongmen/sixelmania` branch while watching GT hopefully kick the shit out of those lacross wannabes at Duke this afternoon.
