### ISSUE TITLE
add ncplane_move_family_{top, bottom}()

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2232]
See @joseluis 's question in #2202. I'm removing `ncplane_boundlist()`, which was poorly-considered and ought never have been introduced. This was serving to help us lift the backing bitmap plane up with the FPS plot. Replace it with new functions `ncplane_move_family_top()` and `ncplane_move_family_bottom()`, and ensure `NCBLIT_PIXEL` plots continue to work in `notcurses-demo`.

**Comment by dankamongmen** [comment]
The problem with this is that we'll either need walk the entire z-axis, pulling out our descendants and reattaching them, or we'll need to walk our descendants, and then sort them. Since z-axis position isn't a datum we keep around, we'd basically have to go find it.

so it's either:
* extract main, walk descendants, determine relative z-indices, remap, or
* extract main, walk above, test for descendance, move to top if so, walk below, test for descendance, move to bottom of new stack if so

so the second seems obviously better. we could further improve it by counting the number of descendants, and ending our walk once we've found all of them. counting the descendants is precisely N steps on N children. it's most likely that (a) child planes are nearby and (b) there are fewer children than there are overall planes, in which case this will save substantial time when there are many planes. if there are not many planes, nothing will be slow. the only downside is when there are many planes and they're all our children, which seems weird enough that i'll accept the poor performance.

**Comment by dankamongmen** [comment]
ugh we probably want `ncplane_move_family_above()` and `ncplane_move_family_below()`, too.

**Comment by dankamongmen** [comment]
Skeletons are there now; still need to do the guts.

**Comment by dankamongmen** [comment]
i've now implemented `_top()` and `_bottom()` (though not yet `_above()` nor `_below()`). they ought get some unit tests. also see the ongoing saga in #2235.

**Comment by dankamongmen** [comment]
Implemented `_above()` and `_below()`, reimplemented `_top()` and `_bottom()` in terms of them, added unit testing.

**Comment by dankamongmen** [comment]
our `FamliyBottom` test is generating unexpected results, however...

**Comment by dankamongmen** [comment]
resolved

**Comment by joseluis** [comment]
hey @dankamongmen  one question, why the new functions `ncplane_move_family_[above|below]` doesn't return anything but `ncplane_move_[above|below]` can return an error, specially when the latter are used inside the former?

**Comment by dankamongmen** [comment]
> hey @dankamongmen one question, why the new functions `ncplane_move_family_[above|below]` doesn't return anything but `ncplane_move_[above|below]` can return an error, specially when the latter are used inside the former?

good call, fixed, thanks!
