### ISSUE TITLE
misidentifying mintty as windows terminal

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2248]
When running `mintty -P on` in MSYS2, we identify the terminal as `TERM_MSTERMINAL`, due to it now properly acquiring the ConsoleHandles (OH SHIT this explains how to solve #2244 subissue 3 -- just *exit* on Windows if we can't get the handles!). That's an insufficient litmus now that @mintty has shown us the power of `mintty -P on`. Continue to run detection after acquiring the handles, and prefer MinTTY on a hard match. Fall back to MSTERMINAL.

**Comment by dankamongmen** [comment]
Also, we probably want to use terminfo with MinTTY, as it works within MSYS2.

**Comment by dankamongmen** [comment]
waiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiit

i just idly ran `echo -e '\e[>q'` in a `mintty` using ConPTY, and yet got a return of mintty.

have i been smoking crack? @j4james, how is that possible?

...

**Comment by dankamongmen** [comment]
yep, i just read mintty on an XTVERSION from `notcurses-info`, and had a heart palpitation

**Comment by j4james** [comment]
I tried to explain this before in https://github.com/dankamongmen/notcurses/issues/2105#issuecomment-906574179:
> In some cases it [conpty] will pass through a sequence directly if it doesn't understand it, but the chances of that working correctly are slim.

XTVERSION isn't currently recognised by conhost so it's passed through to the conpty client.

**Comment by dankamongmen** [comment]
ahhhh! well that explains that (and also the timings i'm seeing). but it will not pass through sixel, right? huh in that case it's almost worse than useless. =\

**Comment by j4james** [comment]
It doesn't pass through DCS sequences, and even it did, sixel wouldn't really work beyond the most basic scenarios.

**Comment by dankamongmen** [comment]
i'm moving the IDQUERIES to the front of the line, so that mintty has a decent chance of replying to XTVERSION before ConPTY responds with DA1, though that's still racy =\

**Comment by dankamongmen** [comment]
not only is it racy, it's bad racy -- the mintty response almost always comes micro- or even milliseconds after the DA1. bleh! i guess it doesn't matter overmuch, since we wouldn't be able to use most of mintty's features anyway....hrmmm, no, wait, i can drive sixel through to mintty just fine, even in ConPTY mode:

![2021-12-08-020704_1683x759_scrot](https://user-images.githubusercontent.com/143473/145163979-2a7ac611-f2e6-4592-96ba-07602cebf91f.png)

riddles abound tonight! ok, we need to go ahead and identify it, then. perhaps `$TERM` is sensible here? i know it's not usually set in the windows environment, but mintty seems to set it reliably, whether launched as MSYS2 or "Git Bash" (well, the latter sets `TERM` to `xterm`, but `TERM_PROGRAM` to `mintty`). we still wouldn't have a DA1 reporting sixel, but we can just expert-system it. ooohhhhhhhhhhhhhhhh omg are we going to have working bitmaps on Windows this evening?

> “Rather than sleep, Tibbets crawled through the thirty-foot tunnel to chat with the waist crew, wondering if they knew what they were carrying. "A chemist's nightmare," the tail gunner, Robert Caron, guessed, then "a physicist's nightmare." "Not exactly," Tibbets hedged. Tibbets was leaving by the time Caron put two and two together:
'Tibbets stayed a little longer, and then started to crawl forward up the tunnel. I remembered something else, and just as the last of the Old Man was disappearing, I sort of tugged at his foot, which was still showing. He came sliding back in a hurry, thinking maybe something was wrong. "What's the matter?"
I looked at him and said, "Colonel, are we splitting atoms today?"
This time he gave me a really funny look, and said, "That's about it.”

**Comment by dankamongmen** [comment]
we have liftoff; we're properly identifying mintty (no version, though...)

![2021-12-08-022000_2255x1032_scrot](https://user-images.githubusercontent.com/143473/145165578-7fef712c-42a6-4262-8767-a0326c4e248a.png)

**Comment by dankamongmen** [comment]
wwe're picking up the version now

**Comment by dankamongmen** [comment]
ok, we're not yet able to display bitmaps in mintty, because we're not getting pixel geometry. Our `\e[14t` is presumably coming back late (it works on the shell). alright, we detect mintty now. we'll work out bitmaps later. close!

**Comment by j4james** [comment]
> i can drive sixel through to mintty just fine, even in ConPTY mode:

This is likely because it's using an old version of conhost, prior to when we added DCS parsing, so the DCS sequences probably were being passed through at that point. It will likely stop working for you at some point in the future. And as I've said before, even when it appears to be working, it's not going to be working correctly.
