### ISSUE TITLE
ncvisuals no longer correctly positioned in xterm <357

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#2252]
all ncvisuals are rendered at 0,0 when using xterm

**Comment by dankamongmen** [comment]
seeing xterm 369 work just fine with 
![2021-10-09-104333_884x1415_scrot](https://user-images.githubusercontent.com/143473/136662729-d4af9336-ef45-4403-9173-7e32e010f215.png)

working on xterm 369 with notcurses 2.4.5

**Comment by dankamongmen** [comment]
see #1782

**Comment by joseluis** [comment]
OK!

I'm using the xterm packaged from my distro, version 353.
And the latest notcurses from master.

**Comment by dankamongmen** [comment]
> I'm using the xterm packaged from my distro, version 353. And the latest notcurses from master.

ahhh, ok, i might have fucked up the xterm version check then; i don't think i tested with a sub-369. let's see.

**Comment by dankamongmen** [comment]
i sure did, augh, good find!

**Comment by dankamongmen** [comment]
hopefully what i just pushed ought fix it, ugh

**Comment by joseluis** [comment]
Mmmm no, it still suffers from the same problem.

For example, the orca in notcurses-demo remains at the top left corner, as well as any other positioned ncvisual.

**Comment by dankamongmen** [comment]
can you give me a quick screencap of `notcurses-info`? stderr logs from `notcurses-info -v` might also prove very useful. thanks!

**Comment by joseluis** [comment]
sure

![image](https://user-images.githubusercontent.com/5832068/136666172-90fd785d-2376-4d47-a9c3-a5a167839f5c.png)
[info-stderr.txt](https://github.com/dankamongmen/notcurses/files/7315974/info-stderr.txt)
[info-stdout.txt](https://github.com/dankamongmen/notcurses/files/7315976/info-stdout.txt)

**Comment by dankamongmen** [comment]
so since it can't recognize XTerm (because it's not getting an `XTVERSION` response), it can't compare versions, and that's why we're getting the failure. the real problem here is that we're not getting an XTVERSION response. why? hrmmmm

**Comment by joseluis** [comment]
> is this possibly being run in screen/tmux?

no, it's standalone, run with `xterm -tn vte340`

**Comment by dankamongmen** [comment]
this xterm definitely does not respond to XTVERSION.

**Comment by dankamongmen** [comment]
with the change i just committed, we identify XTerm, though not yet get its version, and i don't see any sixels at all.

probably not gonna work on this anymore tonight, but ought get it pretty quickly tomorrow omrning.

**Comment by dankamongmen** [comment]
we now extract these older versions from DA2

**Comment by dankamongmen** [comment]
so i can't get *any* sixels to display *anywhere* using this older xterm =[. i'm now at least extracting the version properly etc. @joseluis i assume there has been no change in behavior?

**Comment by dankamongmen** [comment]
and when i do a primary device attributes request, we **do not** see the '4' indicating sixel support:

`[schwarzgerat](0) $ 64;1;2;6;9;15;16;17;18;21;22;28c`

so how are you seeing sixels with this build at all?

**Comment by dankamongmen** [comment]
> sure
> 
> ![image](https://user-images.githubusercontent.com/5832068/136666172-90fd785d-2376-4d47-a9c3-a5a167839f5c.png) [info-stderr.txt](https://github.com/dankamongmen/notcurses/files/7315974/info-stderr.txt) [info-stdout.txt](https://github.com/dankamongmen/notcurses/files/7315976/info-stdout.txt)

i'm not seeing a sixel here anywhere....?

**Comment by dankamongmen** [comment]
```
[schwarzgerat](0) $ echo -e '\e[c\e[?2;1;1S'
[schwarzgerat](0) $ 64;1;2;6;9;15;16;17;18;21;22;28c2;0;880;552S
```

**Comment by joseluis** [comment]
oh man, don't worry too much about this ass old version of xterm that in two years will be forgotten.

I'm about 1000x times more excited about #2258. I'll close this in a moment if that will help you focus on that one!

**Comment by dankamongmen** [comment]
i mean, there's no cost to leaving it open... but I do now have us identifying the version of pre-XTVERSION XTerm, which is a Good Thing, and we've opened the discussion on #2257, which is a Necessary if Unpleasant Thing, and we fixed a real bug in DECSDM inversion detection in XTerm, which is a Very Good Thing, and we're working as exepected when I test under XTerm 353 as packaged in Ubuntu Focal, which is a Reassuring Thing Though Also a Confusing Thing Given Your Claims, so sure i'm happy to close this up.
