### ISSUE TITLE
valgrind reports leaks when using ncvisuals

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#2266]
I was trying to fix memleaks in the rust bindings when passing mutable strings to C and having interesting lifetime problems, but it turns out I was also getting errors when using ncvisuals, and when trying to debug them I found out valgrind also detects errors in the C code, like the `pixel`, and `interp` *pocs*.

@dankamongmen does it happen for you too? or is my system just a bit tad strange? 

`valgrind --leak-check=full -s BIN` to replicate

**Comment by dankamongmen** [comment]
that was just a failure to release in `interp`, not a general thing. i fixed it up.

you'll always see those `tiparm()` ones thanks to terminfo.

**Comment by dankamongmen** [comment]
in the log you post, everything i see is coming from the dynamic linker, due to libav. all that `_dl_init()` stuff is libav being sloppy.

**Comment by dankamongmen** [comment]
to be a bit more verbose:
* all that `_dl_init()` comes from libav opening other libraries
* ...because libav can't be "destructed" as it were (to the best of my knowledge)
* it only happens once per library that is opened, so there's a firm ceiling on it
* nothing to see here, move along
