### ISSUE TITLE
we're not drawing unicode 13 properly on macos

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2285]
Thanks to @christianparpart for pointing this out to me about a week ago, but i hadn't looked into it yet.

open up `include/notcurses/ncseqs.h` in vim. observe that, say, `NCANGLESBR` is perfectly visible.

run `notcurses-info`. we do not see any of these glyphs.

i'd just been thinking that they were unavailable on macOS, but that's clearly not the case. figure out what we're doing wrong here. maybe this is the same problem as #2117, if we're lucky.

**Comment by dankamongmen** [comment]
all the sextants are similarly visible in vim, but not in `notcurses-demo`. hrmmm this smells of a 16-bit `wchar_t` issue.

**Comment by dankamongmen** [comment]
naively ignoring a `wcwidth()` result of -1 does not solve our problem, before:

![2021-10-20-040314_618x532_scrot](https://user-images.githubusercontent.com/143473/138052969-cf49ee12-3187-489f-ab18-73184fa99e23.png)

after:

![2021-10-20-040327_672x502_scrot](https://user-images.githubusercontent.com/143473/138052988-9b7a0e6e-ebdd-4309-bd7f-7463e14d989f.png)

**Comment by dankamongmen** [comment]
oh that looks like an iterm problem. we get these same results in vim. in kitty running on macos now, we have success!

**Comment by christianparpart** [comment]
what TEs did you use in these screenshots?
