### ISSUE TITLE
FreeBSD wcwidth returns 1 for emoji

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#229]
See #196. We have four unit tests failing on FreeBSD due to this. I'm inclined to just change the unit tests to use more common Unicode for which FreeBSD's `wcwidth()` works? Anyway, this doesn't need to be a 1.0.0 thing.

**Comment by dankamongmen** [comment]
I haven't seriously used FreeBSD in a few years, but I seem to recall a number of Ports requiring glibc rather than FreeBSD libc. It seems hella lame, but I think that would standardize our behavior across the two platforms in this regard.

I assume the width of the emoji is indeed 2? These tests were running in the console. Check that. We might be the ones in the wrong here.

Perhaps we ought be using ICU for this? Nah....that's not a solution. Remember, doing this properly *requires knowledge of the font and font rendering system*. ICU is not going to save us.

**Comment by dankamongmen** [comment]
Hey @yurivict, any knowledge you might be able to share regarding this issue would be appreciated.

**Comment by yurivict** [comment]
We should first make it builds on FreeBSD and create a port.

If you have a set of patches, please merge it into the master and I should be able to create a port.

I don't know much about ```wcwidth``` or emojis.
