### ISSUE TITLE
set default color registers based on DA1 in absence of XTSMGRAPHICS

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2309]
If a terminal indicates sixel via feature 4, but does not answer XTSMGRAPHICS with a number of color registers, we currently assume 256. here's some better data, according to the `xterm` man page:

               Result   decTerminalID
               ───────────────────────
                    4             125
                    4             240
                    4             241
                    4             330
                   16             340
                    2             382
                 1024           other

we ought build these in based off `TERM`/DA1,

**Comment by j4james** [comment]
Note that those values aren't a reflection of how sixel is supported in the wild - it's just the XTerm internal mapping, and in reality it wouldn't even apply to XTerm, because there is no correlation between XTerm's DA response and the palette size.

That said, I am in favor of this approach, and I think there is at least one terminal (not counting the actual hardware terminals) where this could help detect that only 16 colors are supported. But for the "other" case, I'd probably recommend defaulting to 256 colors rather than 1024.

**Comment by dankamongmen** [comment]
> Note that those values aren't a reflection of how sixel is supported in the wild - it's just the XTerm internal mapping, and in reality it wouldn't even apply to XTerm, because there is no correlation between XTerm's DA response and the palette size.

are you saying that these are not the correct number of color registers for the hardware being emulated? given what xterm is going for here, that seems a bug if so.

> That said, I am in favor of this approach, and I think there is at least one terminal (not counting the actual hardware terminals) where this could help detect that only 16 colors are supported. But for the "other" case, I'd probably recommend defaulting to 256 colors rather than 1024.

yep, i'll be doing this regardless since i don't (yet) support more than 256 colors

**Comment by j4james** [comment]
I should also mention that you're going to need to use the DA2 response for this, otherwise you won't be able to tell the difference between a VT330, a VT340, and a VT382. And note that there are a few different VT382 variants with different DA2 responses.

**Comment by dankamongmen** [comment]
> The bottom line is you're almost always guaranteed to get the wrong result on XTerm, but that probably doesn't matter if you're still querying `XTSMGRAPHICS`.

ahhh grokked, ok thanks for the explanation. yes, `XTSMGRAPHICS` always trumps inferred values.

**Comment by dankamongmen** [comment]
these aren't values that come out of DA1 anyway, duh.
