### ISSUE TITLE
clarification on the docs for ncvisual_geom

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#2321]
I suspect this sentence is wrong and it should end with: "*as calling with a **non** NULL 'n'*". Could it be the case?

```c
// if 'n' is NULL, only cdimy/cdimx, blitter,
// scaley/scalex, and maxpixely/maxpixelx are filled in; this is the same as
// calling with a NULL 'n' and a default 'vopts'. 
```

**Comment by dankamongmen** [comment]
I should probably just kill that last line; it means what it says, but is redundant. Good eye!

**Comment by dankamongmen** [comment]
oh yeah it looks like i'd already killed that line in `USAGE.md`.
