### ISSUE TITLE
make mouse movement available without button press

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2322]
Currently, we only report mouse events when a button is pressed. It's possible to get all movement events if we want to (we explicitly restrict things to button tracking currently). This is necessary for things like mouseovers etc. With that said, many clients do not need nor want all these events.

Let's augment `notcurses_mouse_enable()` with an option allowing pure moves to be returned. This ought also govern our setup of the mouse (be sure we get GPM also), as there's no point in handling a bunch of events we're just going to filter.

This will be an API/ABI break, so we either need implement a new function and deprecate the old one, or do this at 3.0.0. Hrmm.

Necessary for my current dream of #2319.

**Comment by dankamongmen** [comment]
i mean we could also just add e.g. `notcurses_mouse_enable_full()` or something but that seems a bit gauche

**Comment by dankamongmen** [comment]
ughghghghghghg ok imma introduce `notcurses_mice_{enable,disable}()` and deprecate `notcurses_mouse_{enable,disable}`.

```c
#define NCMICE_MOVE_EVENT         0x1
#define NCMICE_PRESS_EVENT       0x2
#define NCMICE_RELEASE_EVENT   0x4
#define NCMICE_DRAG_EVENT          0x8

int notcurses_mice_enable(struct notcurses* nc, unsigned eventmask);

static inline int
notcurses_mice_disable(struct notcurses* nc){
  return notcurses_mice_enable(nc, 0);
}
```

there we go. ugh, annoying.

**Comment by dankamongmen** [comment]
by the way, it looks like xterm.js removed UTF8 mouse mode in 2019...but alacritty only supports UTF8, not sgr. ugh =[

**Comment by dankamongmen** [comment]
got it working, except it looks like presses

**Comment by dankamongmen** [comment]
while we're doing this, we ought be sending all this mouse crap to `ttyfd`, *not* `ttyfp`. if there's no tty, there's no point doing this.

**Comment by dankamongmen** [comment]
closed in 0f5aec510a7acc9854f9d79a7d98a82db7a202bf

**Comment by joseluis** [comment]
@dankamongmen I believe it'd make more sense to rename `NCMICE_[MOVE|BUTTON|DRAG]_EVENT` to `NCMICE_[MOVE|BUTTON|DRAG]_EVENTS` (plural) for consistency, since as happens with `NCMICE_NO_EVENTS` and `NCMICE_ALL_EVENTS` they all signify allowing plural events of the indicated type.

**Comment by dankamongmen** [comment]
> @dankamongmen I believe it'd make more sense to rename `NCMICE_[MOVE|BUTTON|DRAG]_EVENT` to `NCMICE_[MOVE|BUTTON|DRAG]_EVENTS` (plural) for consistency, since as happens with `NCMICE_NO_EVENTS` and `NCMICE_ALL_EVENTS` they all signify allowing plural events of the indicated type.

yeah makes sense. I was thinking something like notcurses_all_events is multiple types of events but that doesn't make any sense.
