### ISSUE TITLE
ncneofetch on linux shows "(null) (0 cores)" on aarch64

### ISSUE THREAD

**Issue by alex3kov** [dankamongmen/notcurses#2336]
```
$ export | egrep 'LANG|LC_CTYPE|TERM'`
declare -x COLORTERM="\"truecolor\""
declare -x LANG="\"en_GB.UTF-8\""
declare -x LESS_TERMCAP_mb="\"[1;32m\""
declare -x LESS_TERMCAP_md="\"[1;32m\""
declare -x LESS_TERMCAP_me="\"[0m\""
declare -x LESS_TERMCAP_se="\"[0m\""
declare -x LESS_TERMCAP_so="\"[01;33m\""
declare -x LESS_TERMCAP_ue="\"[0m\""
declare -x LESS_TERMCAP_us="\"[1;4;31m\""
declare -x TERM="\"foot\""
```
* notcurses version 2.4.8 (installed from AUR
* foot 1.9.2

ncneofetch output:
```                                   
│Linux 5.14.14-1-ARCH                                    Arch Linux ARM│
│RAM: 3.04GiB/3.77GiB                                    Processes: 613│
│DM: sway                                              Shell: /bin/bash│
│RGB TERM: foot 1.9.2                                      Screen0: 0x0│
│LANG: en_GB.UTF-8                                            UID: 1000│
│                           (null) (0 cores)                           │
```
lscpu (notice it's ARM's hybrid A72+A53):
```
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          6
On-line CPU(s) list:             0-5
Vendor ID:                       ARM
Model name:                      Cortex-A53
Model:                           4
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Stepping:                        r0p4
CPU max MHz:                     1416.0000
CPU min MHz:                     408.0000
BogoMIPS:                        48.00
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
Model name:                      Cortex-A72
Model:                           2
Thread(s) per core:              1
Core(s) per socket:              2
Socket(s):                       1
Stepping:                        r0p2
CPU max MHz:                     1800.0000
CPU min MHz:                     408.0000
BogoMIPS:                        48.00
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Branch predictor hardening
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

```

**Comment by dankamongmen** [comment]
i'm not sure i'll be able to get to this for 3.0.0, but i'll try to.

sway is wayland, right? right now we're `exec()`ing `xrandr` to get screen geometry (see `fetch_x_props()`). i'll need figure out how to get it on wayland (contributions welcome! this ought be an easy change to make, just pattern-replace on `fetch_x_props()`).

for cpu information on Linux, i parse `/proc/cpuinfo`:

```
[schwarzgerat](0) $ cat /proc/cpuinfo  | egrep 'core id|model name|vendor_id' | sort -u | tail -n3
core id		: 9
model name	: AMD Ryzen Threadripper 3970X 32-Core Processor
vendor_id	: AuthenticAMD
[schwarzgerat](0) $ 
```

could you be so kind as to paste `/proc/cpuinfo` here? i can add that immediately.

**Comment by alex3kov** [comment]
>sway is wayland, right? right now we're `exec()`ing `xrandr` to get screen geometry (see `fetch_x_props()`). i'll need figure out how to get it on wayland (contributions welcome! this ought be an easy change to make, just pattern-replace on `fetch_x_props()`).

Yes, it's wayland - getting resolution will be more challenging as each wayland
compositor has its own means of doing such things, there's no such thing as a
central X server that handles resolution/IO. For sway:
```
swaymsg -t get_outputs | jq -r '.[]|.current_mode|.width,.height'
1920
1080
```

>could you be so kind as to paste `/proc/cpuinfo` here? i can add that immediately.

I aim to please:
```
processor: 0
BogoMIPS: 48.00
Features: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer: 0x41
CPU architecture: 8
CPU variant: 0x0
CPU part: 0xd03
CPU revision: 4

processor: 1
BogoMIPS: 48.00
Features: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer: 0x41
CPU architecture: 8
CPU variant: 0x0
CPU part: 0xd03
CPU revision: 4

processor: 2
BogoMIPS: 48.00
Features: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer: 0x41
CPU architecture: 8
CPU variant: 0x0
CPU part: 0xd03
CPU revision: 4

processor: 3
BogoMIPS: 48.00
Features: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer: 0x41
CPU architecture: 8
CPU variant: 0x0
CPU part: 0xd03
CPU revision: 4

processor: 4
BogoMIPS: 48.00
Features: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer: 0x41
CPU architecture: 8
CPU variant: 0x0
CPU part: 0xd08
CPU revision: 2

processor: 5
BogoMIPS: 48.00
Features: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer: 0x41
CPU architecture: 8
CPU variant: 0x0
CPU part: 0xd08
CPU revision: 2
```

**Comment by dankamongmen** [comment]
i think i just committed a fix for ARM core count detection on `master`.

**Comment by dankamongmen** [comment]
so no real model name in that output, le sigh. i can at least identify the architecture in that case.

**Comment by alex3kov** [comment]
And you can detect the presence of sway with this:
```sh
$ swaymsg -t get_version
sway version 1.6.1
```

I would gladly contribute a patch if ncneofetch was written in POSIX sh or
something on that level, but it's C - never did any serious programming in it,
I'll probably break all those pointers :)

**Comment by dankamongmen** [comment]
#2341 is handling the wayland part. for 3.0.0, i just want to make sure we detect ARM and the number of cores.

**Comment by dankamongmen** [comment]
@alex3kov could you verify that `master` is showing the core count, instead of 0? thanks!

**Comment by alex3kov** [comment]
On Sat, Nov 13, 2021 at 11:50:52PM -0800, nick black wrote:
***@***.*** could you verify that `master` is showing the core count, instead of 0? thanks!
It does: "(null) (6 cores)"

**Comment by alex3kov** [comment]
***@***.*** could you verify that `master` is showing the core count, instead of 0? thanks!

Tried to find more specific CPU model info in system dirs to deal with that
(null), not a whole lot of luck:
---
$ ag a72 /run /proc /dev /sys 2>/dev/null
/run/udev/data/+platform:pmu_a72
2:E:ID_PATH=platform-pmu_a72
3:E:ID_PATH_TAG=platform-pmu_a72
$ ag rk3399 /run /proc /dev /sys 2>/dev/null
/run/udev/data/c81:1
4:E:ID_V4L_PRODUCT=rockchip,rk3399-vpu-enc

/run/udev/data/c81:2
4:E:ID_V4L_PRODUCT=rockchip,rk3399-vpu-dec

/run/udev/data/+pci:0000:00:00.0
6:E:ID_MODEL_FROM_DATABASE=RK3399 PCI Express Root Port
---
On this SBC (RockPro64) PCIe is actually wired out, don't know if it would show
up on models where it's not.

**Comment by dankamongmen** [comment]
yeah, i'm pondering this. i'm thinking i'll fall back to the compile-time architecture (wouldn't be anything more specific than ARM) in the absence of information in `/proc/cpuinfo`. that'll at least eliminate the `(null)`.

i'm not personally inclined to spend much time expanding `ncneofetch`'s capabilities here, especially for hardware i don't have to test with. it's more meant as a notcurses demonstration tool than a true hardware explorer. i'd of course welcome patches, but if i can eliminate the `(null)`, that's probably going to be good enough for me to call this done.

**Comment by dankamongmen** [comment]
with the latest `ncneofetch`, you ought see "arm (6 cores)" or "aarch64 (6 cores)". that's as good as this is going to get right now, but it seems a solid improvement from where we started =].

**Comment by alex3kov** [comment]
>with the latest `ncneofetch`, you ought see "arm (6 cores)" or "aarch64
>(6 cores)". that's as good as this is going to get right now, but it
>seems a solid improvement from where we started =].

Fully agree. Tested latest commit, "aarch64 (6 cores)" looks good
enough.
I think ncneofetch has potential to add some serious bling to one's
terminals and showcase notcurses' capabilities to casual users. The demo
is nice but it's not like I'm going to run it more than once, you know?

**Comment by dankamongmen** [comment]
of course. thanks for helping test this ARM business. go build stuff! =]
