### ISSUE TITLE
ncplayer: is it possible to display an image without any scaling?

### ISSUE THREAD

**Issue by alex3kov** [dankamongmen/notcurses#2337]
For example, I have a 1280x720 image and running in 1920x1080 resolution (sway 1.6.1, foot 1.9.2). I tried `-s none` and all the other `-s` values but it stretches the image to entire terminal - in different ways, all of them looking horribly pixelated :)
Is it possible to make it do the same thing `img2sixel` from libsixel does - simply display a crisp 1280x720 image in the terminal?

**Comment by dankamongmen** [comment]
Aleksei left as an exercise for the reader:
> For example, I have a 1280x720 image and running in 1920x1080 resolution (sway 1.6.1, foot 1.9.2). I tried `-s none` and all the other `-s` values but it stretches the image to entire terminal - in different ways, all of them looking horribly pixelated :)
> Is it possible to make it do the same thing `img2sixel` from libsixel does - simply display a crisp 1280x720 image in the terminal?

`./ncplayer -bpixel -snone imgname` definitely ought not be
performing any scaling. you're sure it is?

**Comment by dankamongmen** [comment]
![2021-11-11-064229_1453x1410_scrot](https://user-images.githubusercontent.com/143473/141292324-e58c1a45-ff26-4d20-8a8d-faa779854140.png)

`-k` keeps things on the current screen rather than going to the alternate screen. is this not what you want?

**Comment by alex3kov** [comment]
Thanks @dankamongmen , tried all this, some notes here:
* `-b pixel` indeed doesn't perform scaling. It's just not obvious at all what "blitter" is so I didn't try it at first :)
* `-k` reproduces `img2sixel`'s behavior of basically `cat`-ing the image into terminal, cool
* `img2sixel` handles at least this image better. Original is here: https://mekboy.xyz/kitten_mushroom_720p.jpg, look what happens with sclera in these screenshots: https://mekboy.xyz/scr_1636637528.png https://mekboy.xyz/scr_1636637506.png, `ncplayer` gives the kitten a cataract or something :)

**Comment by dankamongmen** [comment]
absolutely agreed that libsixel has better image quality (**and** performance, ugh) than Notcurses does on sixel; i've got an open bug on that (#1452, #1724). it's a weak spot for us, but I expect to have it closed by the end of 2021. kitty graphics, available in kitty and wezterm, are better than any sixel implementation (due to sixel's limited number of colors). but thanks for the motivation! =]

regarding "blitter", i hadn't realized that the term might not be obvious, but perhaps you're right. what's a better name for the term? "blitter" is all over the API, so i don't really want to change it, but if there's a much better alternative, i'll consider it.

there's (at least) one bug with `ncplayer -k`: if you're near the bottom of the screen, it'll scroll one line too few, causing some overprint on the previous line. i ought have this bug fixed pretty soon (definitely in 3.0.0).

thanks for your feedback! now that you've got `-bpixel`, that sounds like it solves your question? i'm going to mark this closed, but feel free to reopen it if you have further questions. hack on!

**Comment by alex3kov** [comment]
> kitty, wezterm

Python and Rust. No and hell no if I can avoid it, respectively. I don't want to fry my SBC bootstrapping Rust.

> regarding "blitter", i hadn't realized that the term might not be obvious, but perhaps you're right. what's a better name for the term? "blitter" is all over the API, so i don't really want to change it, but if there's a much better alternative, i'll consider it.

Having read [this](https://en.wikipedia.org/wiki/Blitter) I'm still not sure what it means in this context - how much data to copy from the image file to memory, something like that? Maybe leave it as "blitter" in API parts where low-level programmers will use it but change it only in user-facing cli parameters (`-s scale` instead of `-b blitter`)?

> there's (at least) one bug with ncplayer -k: if you're near the bottom of the screen, it'll scroll one line too few, causing some overprint on the previous line. i ought have this bug fixed pretty soon (definitely in 3.0.0).

Happens to me too.

**Comment by dankamongmen** [comment]
> Python and Rust. No and hell no if I can avoid it, respectively. I don't want to fry my SBC bootstrapping Rust.

totally understood. i'll give sixel improvement some more priority, then. thanks for the feedback.

> Having read [this](https://en.wikipedia.org/wiki/Blitter) I'm still not sure what it means in this context - how much data to copy from the image file to memory, something like that? Maybe leave it as "blitter" in API parts where low-level programmers will use it but change it only in user-facing cli parameters (`-s scale` instead of `-b blitter`)?

so given an image, notcurses can render it in different ways:

* pixel (requires graphics support)
* braille (requires font+terminal support)
* unicode sextants
* unicode quadrants
* unicode halfblocks
* spaces

basically, by blitter i just mean "what means are we using to turn this pixel image into something you can view on this terminal?"

> Happens to me too.

yep, just letting you know it's known and will be fixed soon.

**Comment by alex3kov** [comment]
> basically, by blitter i just mean "what means are we using to turn this pixel image into something you can view on this terminal?"

OK, got it. The most immediately visible effect of this parameter is scale though. Any value except 'pixel' basically just trashes my terminal, not sure why end users would need it in a seemingly user-facing `ncplayer` utility.

**Comment by alex3kov** [comment]
> absolutely agreed that libsixel has better image quality (and performance, ugh) than Notcurses does on sixel; i've got an open bug on that (#1452, #1724). it's a weak spot for us, but I expect to have it closed by the end of 2021.

I have notcurses releases in my RSS now, will be testing them. This library looks interesting for displaying at least static graphics in terminals (I tried ncplayer on a video - way too slow).

**Comment by dankamongmen** [comment]
well, many terminals don't have bitmap support, so they're not going to get the `pixel` blitter no matter the default.

smaller images will work with cell blitters and no scaling. `stretch` with a cell blitter ought fit your screen perfectly, as ought `scalehi`.

perhaps it would be best to make the default `pixel`+`none`, unless pixel is unavailable, in which case it ought default to `sex`+`stretch`.

**Comment by dankamongmen** [comment]
(I tried ncplayer on a video - way too slow).

I'll be threading the streamer, which ought accelerate it substantially, and again the sixel quantization needs some love.

**Comment by dankamongmen** [comment]
by the way, another pretty performant terminal with a C++ base (no bootstrapping pile) is contour; you might want to check it out.

**Comment by alex3kov** [comment]
>by the way, another pretty performant terminal with a C++ base (no bootstrapping pile) is contour; you might want to check it out.

Thanks for recommendation, I'll keep an eye on it. It's based on qt5 though,
and so far I'm very satisfied with foot https://codeberg.org/dnkl/foot. It's so
minimalist it doesn't even bother with toolkits (GTK/Qt/VTE), it just renders
to Wayland directly like a boss =]

**Comment by dankamongmen** [comment]
oh absolutely, foot is great!
