### ISSUE TITLE
Is procroller broken or am I using it wrong?

### ISSUE THREAD

**Issue by rpmohn** [dankamongmen/notcurses#2338]
Question: is procroller working as expected right now? I'm calling it e.g. `./procroller cat ~/.bashrc` and there's certainly a bit of that data output, but it's all off to the left with ANSI codes and not much of anything really. And sometimes I get a SegFault. The pressanykey works fine! What am I missing? (I'm trying to get a better understanding of the `ncsubproc_create*()` family of functions, so if there are better examples I'd take them instead!) Thank you! -Ross 
````
$ export | grep -E 'LANG|LC_CTYPE|TERM'
declare -x COLORTERM="24bit"
declare -x GDM_LANG="en_US"
declare -x LANG="en_US.UTF-8"
declare -x LANGUAGE="en_US"
declare -x TERM="xfce"

$ ./notcurses-demo -V
notcurses-demo version 2.4.8

$ xfce4-terminal -V | head -n 1
xfce4-terminal 0.8.9.1 (Xfce 4.14)

$ grep PRETTY /etc/os-release
PRETTY_NAME="Ubuntu 20.04.3 LTS"
````

**Comment by dankamongmen** [comment]
you definitely ought not be getting segfaults =]. a `valgrind` or ASAN or gdb backtrace would be very much appreciated.

i just committed a few changes to `procroller` which ought make it easier to use (keep output onscreen until you press a key, etc.). it seems to be working for me:

![2021-11-11-071601_1453x1410_scrot](https://user-images.githubusercontent.com/143473/141296610-2f15189c-c4d4-43a3-b628-d5e609b30143.png)

can you get a screenshot for me?

**Comment by rpmohn** [comment]
Pulled your changes (master f401f2b4f) and I can't get it to SegFault anymore. It also used to do a screen clear before, but doesn't now. Behavior now is that is seems to only show the first line. Here's a screenshot:

![image](https://user-images.githubusercontent.com/4296967/141338538-4f722002-def1-4966-b4f9-702c0603458b.png)

**Comment by dankamongmen** [comment]
> It also used to do a screen clear before, but doesn't now. Behavior now is that is seems to only show the first line. Here's a screenshot:

yeah i changed this purposefully, but...

> ![image](https://user-images.githubusercontent.com/4296967/141338538-4f722002-def1-4966-b4f9-702c0603458b.png)

it's not quite ready for gametime. let me pull that back out and everything ought work. i wrote this like a year and a half ago; it's not been well-loved.

**Comment by dankamongmen** [comment]
of course, using the alternate screen, you're not going to have scrollback, and thus you'll only see the bottommost material. le sigh. i ought make an improved and more useful `procroller` (these little programs are just proofs of concepts).

**Comment by rpmohn** [comment]
BTW, I just tried it on kitty and got the same results, screenshot looks the same.
```
$ export | grep -E 'LANG|LC_CTYPE|TERM'
declare -x COLORTERM="24bit"
declare -x GDM_LANG="en_US"
declare -x LANG="en_US.UTF-8"
declare -x LANGUAGE="en_US"
declare -x TERM="kitty-direct"

$ kitty -v
kitty 0.15.0 created by Kovid Goyal
```

**Comment by dankamongmen** [comment]
> $ kitty -v
> kitty 0.15.0 created by Kovid Goyal
> ```

wow that's a *really* old version of kitty btw (not that it has any effect on this particular situation).

**Comment by rpmohn** [comment]
Yikes! Sadly, that's what apt installed on my old Ubuntu 20.04.3 LTS. I need to do an OS upgrade, but don't have the time to invest--would rather program. I'll have to build a kitty from the repo.

**Comment by rpmohn** [comment]
Threw some debugging at procroller and cb() is definitely getting all the data and the correct len, but it only prints out the first line. Is ncplane_putnstr() somehow acting like the end of a line is the end of the string?

**Comment by rpmohn** [comment]
Aha! I see in the `ncplane_put()` code the comment "reject any control character for output other than newline" blah, blah, blah, and that document Mosher.otl has tab characters beginning on the 2nd line, which explains why it quit after printing the first line! OK, so I take a pure text file and I'm back to the weird output. I'll post some screenshots for you next.

**Comment by rpmohn** [comment]
Here are some screenshots of it working on the first paragraph of Mary Shelley's The Last Man, 12 lines of text. First just a regular cat for you, then a few screenshots of output from running `./procroller cat ~/TheLastMan.txt`. It seems that some internal function is attempting to interpret the text rather than just print it. I'll see if I can grab a valgrinder for you next. 
```
$ cat TheLastMan.txt
I VISITED Naples in the year 1818. On the 8th of December of that year, my
companion and I crossed the Bay, to visit the antiquities which are
scattered on the shores of Baiae. The translucent and shining waters of the
calm sea covered fragments of old Roman villas, which were interlaced by
sea-weed, and received diamond tints from the chequering of the sun-beams;
the blue and pellucid element was such as Galatea might have skimmed in her
car of mother of pearl; or Cleopatra, more fitly than the Nile, have chosen
as the path of her magic ship. Though it was winter, the atmosphere seemed
more appropriate to early spring; and its genial warmth contributed to
inspire those sensations of placid delight, which are the portion of every
traveller, as he lingers, loath to quit the tranquil bays and radiant
promontories of Baiae.
```
![image](https://user-images.githubusercontent.com/4296967/141387780-2959e33b-0b13-4142-ab36-8c0b4fadbc5c.png)
![image](https://user-images.githubusercontent.com/4296967/141387835-ba2820b5-df18-4c13-8f27-dd0279d22b3a.png)
![image](https://user-images.githubusercontent.com/4296967/141387878-04c90111-bdbd-49ec-b1c0-5188d547408e.png)
![image](https://user-images.githubusercontent.com/4296967/141387982-73b7bd04-8a2e-4d5a-b246-66d2c270a62e.png)

**Comment by dankamongmen** [comment]
ok! it's awesome that you're doing this, but just remember, `procroller` was never meant to be a deliverable or anything. is there something you're trying to do where `procroller` is your example code?

usually i just run `dmesg` through there, where everything is left-justified and pretty simple. i don't test it heavily. i'm certainly down for improving it, though!

**Comment by dankamongmen** [comment]
> Aha! I see in the `ncplane_put()` code the comment "reject any control character for output other than newline" blah, blah, bl

yeah i ought support tabs though #1233 i'll get to it, just hasn't been a priority =]

**Comment by rpmohn** [comment]
Of course, when I run that command with valgrind the output is flawless, haha! Well, what I really want to do is forkpty off a shell and interact with  it inside of notcurses. Not sure ncsubproc is the way to go, was just exploring it. Have you done something like that already that you would share?
