### ISSUE TITLE
remove screen resolution output from ncneofetch

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2341]
see #2336; `ncneofetch` doesn't know screen resolutions in wayland, as `xrandr` is not available.

**Comment by dnkl** [comment]
`wlr-randr` is probably your best bet. It's not guaranteed to exist, but is the closest thing to a "standard" utility, that I'm aware of. It's either it, or writing your own small helper utility...

```sh
% wlr-randr 
eDP-1 "Unknown 0x42ED 0x00007FC4 (eDP-1)"
  Physical size: 340x190 mm
  Enabled: yes
  Modes:
    1920x1080 px, 120.113998 Hz (preferred)
    1920x1080 px, 60.056999 Hz (current)
  Position: 0,0
  Transform: normal
  Scale: 1.000000
```

**Comment by dankamongmen** [comment]
you know, this doesn't even make sense over ssh. i'm inclined to remove it entirely.

**Comment by dankamongmen** [comment]
alright, i've dropped this field from the output entirely, along with UID, and excised a line from the infoplane.
