### ISSUE TITLE
maxpixel not being filled in with ncvgeom

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#2351]
1. When providing `NCBLIT_DEFAULT` to `ncvisual_geom`, `NCBLIT_2x1` is selected even if `NCBLIT_2x2`, or `NCBLIT_3x2` is supported.
2. `NcVGeom` created from `ncvisual_geom` is missing `maxpixely`:

example: [issue-2351.rs](https://github.com/dankamongmen/libnotcurses-sys/blob/main/examples/issue-2351.rs)

![image](https://user-images.githubusercontent.com/5832068/142273190-39336cbc-55ed-450c-87ed-d9004b4ae2e5.png)

**Comment by dankamongmen** [comment]
> 1. When providing `NcBlitter::DEFAULT` to , `NcBlitter::HALF` is selected even if `NcBlitter::QUADRANT` (or sextant) is supported.

you're probably using NCSCALE_SCALE or NCSCALE_NONE. you need
NCSCALE_SCALE_HIRES/NCSCALE_NONE_HIRES to get those picked; see
notcurses_visual(3)

**Comment by dankamongmen** [comment]
> 2. `NcVGeom` created from `ncvisual_geom` is missing `maxpixely`:

are you in an environment that enforces a maximum bitmap size? i.e. does `notcurses-info` report one?

**Comment by joseluis** [comment]
> 2. `NcVGeom` created from `ncvisual_geom` is missing `maxpixely`:
> are you in an environment that enforces a maximum bitmap size? i.e. does `notcurses-info` report one?

yea, in wezterm for example, pixel_geom reports both yx different from 0, but with ncvisual_geom I only get x as non 0.

**Comment by joseluis** [comment]
> 1. When providing `NcBlitter::DEFAULT` to , `NcBlitter::HALF` is selected even if `NcBlitter::QUADRANT` (or sextant) is supported.
> you're probably using NCSCALE_SCALE or NCSCALE_NONE. you need NCSCALE_SCALE_HIRES/NCSCALE_NONE_HIRES to get those picked; see notcurses_visual(3)

oh thanks 🤔 I'm pretty sure that must be it, I'll be able to confirm tomorrow.

**Comment by dankamongmen** [comment]
> >    you're probably using NCSCALE_SCALE or NCSCALE_NONE. you need NCSCALE_SCALE_HIRES/NCSCALE_NONE_HIRES to get those picked; see notcurses_visual(3)
> oh thanks thinking I'm pretty sure that must be it, I'll be able to confirm tomorrow.

yep, basicaly unless you're using `NCSCALE_STRETCH`, it's assumed that you want to preserve aspect ratio. only halfblock and pixel do that, so to get quadrant or sextant or braille, you need explicitly say `_HIRES`.

**Comment by joseluis** [comment]
So I think then the description of the `scale` field in `ncvisual_options` is misleading: 

> the scaling is ignored if no ncplane is provided (it ought be NCSCALE_NONE in this case). otherwise, the source is stretched/scaled relative to the provided ncplane.

because in this case the scaling is not really ignored, and I'm not providing an `ncplane`.

**Comment by dankamongmen** [comment]
tightened up the `VisualExtrinsicGeometryPixel` unit test and am reproducing this failure:

```c
===============================================================================
/home/dank/src/dankamongmen/notcurses/src/tests/visual.cpp:23:
TEST CASE:  Visual
  VisualExtrinsicGeometryPixel

/home/dank/src/dankamongmen/notcurses/src/tests/visual.cpp:99: ERROR: CHECK( nc_->tcache.sixel_maxy <= g.maxpixely ) is NOT correct!
  values: CHECK( 1411 <= 0 )

===============================================================================
/home/dank/src/dankamongmen/notcurses/src/tests/visual.cpp:23:
TEST CASE:  Visual

DEEPEST SUBCASE STACK REACHED (DIFFERENT FROM THE CURRENT ONE):
  VisualExtrinsicGeometryPixel

Aborting - too many failed asserts!
===============================================================================
[doctest] test cases:  1 |  0 passed | 1 failed | 51 skipped
[doctest] assertions: 87 | 86 passed | 1 failed |
[doctest] Status: FAILURE!
[schwarzgerat](1) $ 
```

**Comment by dankamongmen** [comment]
ok, this ought be fixed. thanks for the report!

> BTW I notice the `y`,`x` fields of `ncvisual_options` are `int`. Does they actually make use of negative values for negative offsets or should it really be `uint`? I can't find any info on that.

yes, just as we do in `ncplane_options`. they can be negative when specifying the location of a new plane being created by `ncvisual_blit()`.
