### ISSUE TITLE
unable to build notcurses from master on windows 10 under msys2

### ISSUE THREAD

**Issue by esotericist** [dankamongmen/notcurses#2352]
as per title, attempted to build notcurses using msys2, with appropriate necessary packages provided. (i opted out of libdeflate, pandoc, and the multimedia bits)

gcc 11.2.0 appears to have strong opinions about some of the code in the project:

```
FAILED: CMakeFiles/notcurses-core.dir/src/lib/direct.c.obj
C:\msys64\mingw64\bin\cc.exe -Dnotcurses_core_EXPORTS -IC:/msys64/home/eso/notcurses/include -IC:/msys64/home/eso/notcurses/src -I/usr/local/include -IC:/msys64/home/eso/notcurses/build/include -IC:/msys64/mingw64/include/ncursesw -IC:/msys64/home/eso/notcurses -O2 -g -DNDEBUG -fvisibility=hidden -Wall -Wextra -W -Wshadow -Wvla -fno-signed-zeros -fno-trapping-math -fassociative-math -fno-math-errno -freciprocal-math -funsafe-math-optimizations -fexceptions -fstrict-aliasing -std=gnu11 -MD -MT CMakeFiles/notcurses-core.dir/src/lib/direct.c.obj -MF CMakeFiles\notcurses-core.dir\src\lib\direct.c.obj.d -o CMakeFiles/notcurses-core.dir/src/lib/direct.c.obj -c C:/msys64/home/eso/notcurses/src/lib/direct.c
C:/msys64/home/eso/notcurses/src/lib/direct.c: In function 'ncdirect_box':
C:/msys64/home/eso/notcurses/src/lib/direct.c:1382:18: error: empty scalar initializer
 1382 |   mbstate_t ps = {};
      |                  ^
C:/msys64/home/eso/notcurses/src/lib/direct.c:1382:18: note: (near initialization for 'ps')
[2/206] Building C object CMakeFiles/notcurses-core.dir/src/lib/in.c.obj
FAILED: CMakeFiles/notcurses-core.dir/src/lib/in.c.obj
C:\msys64\mingw64\bin\cc.exe -Dnotcurses_core_EXPORTS -IC:/msys64/home/eso/notcurses/include -IC:/msys64/home/eso/notcurses/src -I/usr/local/include -IC:/msys64/home/eso/notcurses/build/include -IC:/msys64/mingw64/include/ncursesw -IC:/msys64/home/eso/notcurses -O2 -g -DNDEBUG -fvisibility=hidden -Wall -Wextra -W -Wshadow -Wvla -fno-signed-zeros -fno-trapping-math -fassociative-math -fno-math-errno -freciprocal-math -funsafe-math-optimizations -fexceptions -fstrict-aliasing -std=gnu11 -MD -MT CMakeFiles/notcurses-core.dir/src/lib/in.c.obj -MF CMakeFiles\notcurses-core.dir\src\lib\in.c.obj.d -o CMakeFiles/notcurses-core.dir/src/lib/in.c.obj -c C:/msys64/home/eso/notcurses/src/lib/in.c
C:/msys64/home/eso/notcurses/src/lib/in.c: In function 'process_input':
C:/msys64/home/eso/notcurses/src/lib/in.c:1805:23: error: empty scalar initializer
 1805 |   mbstate_t mbstate = {};
      |                       ^
C:/msys64/home/eso/notcurses/src/lib/in.c:1805:23: note: (near initialization for 'mbstate')
[3/206] Building C object CMakeFiles/notcurses-core.dir/src/lib/fade.c.obj
ninja: build stopped: subcommand failed.
```

requested info from issue template:
```
export | egrep 'LANG|LC_CTYPE|TERM
declare -x LANG="en_US.UTF-8"
declare -x TERM="xterm-256color"
```
notcurses is pulled from master at shorthash 741962
using windows terminal preview 1.12.2931.0

**Comment by michaelsbradleyjr** [comment]
Maybe try MSYS2's UCRT64 [environment](https://www.msys2.org/docs/environments/) instead of MINGW64.

UCRT64 is what's used in this project's GitHub Actions [workflow](https://github.com/dankamongmen/notcurses/blob/master/.github/workflows/windows_test.yml#L26) for Windows. I could be wrong, but I don't think there's been an effort yet to get notcurses building in MSYS2 MINGW64.

**Comment by esotericist** [comment]
oh weird... when I was looking at the environments the msys2 stuff set up a while ago I only saw three (msys2, mingw32, and mingw64), and i've been using the mingw64 environment to do my native builds for my project, so I didn't realize there were other remaining routes. 

next time I'm able to access my windows build environment I'll look at that closer

**Comment by dankamongmen** [comment]
that's correct. UCRT is required. note that only UCRT supports UTf8 properly, windows side:

https://developercommunity.visualstudio.com/t/create-a-utf8-c-runtime/351432

so i suspect that this will be the only one ever supported.

**Comment by esotericist** [comment]
that makes perfect sense, I think I just ran into an  obviousness issue with what it means to launch the msys2 stuff in what ways, and how many ways there are to launch it. 

just figuring out how to successfully get any native builds at all (and the involved pacman invocations) for my own project was a whole set of trials for me.

**Comment by michaelsbradleyjr** [comment]
If I remember correctly, when running the MSYS2 installer it's not completely obvious how to select UCRT64, though maybe that situation has improved lately.

At the step in the installer where it allows the installation path to be set, I changed `C:\msys2\mingw64` to `C:\msys2\ucrt64`(again, if I remember correctly) and it just worked. After the install completed, in the Start Menu (or maybe it was on the desktop), I had an icon to launch the UCR64 environment in addition to one for launching the MINGW64 environment (which I had installed previously).

**Comment by esotericist** [comment]
good news, i already had the UCRT64 environment in my start menu, i just didn't know to look for it, i guess?

blew the cmake cache, reinvoked cmake (with appropriate params), waiting for ninja to either succeed or provide errors.

**Comment by esotericist** [comment]
okay. that worked perfectly, no further hiccups.

i find it absolutely bewildering that the change in environment results in such a strangely specific error in compiling that code in question, but it works now (once i took the time to get a windows terminal profile set up with the correct UCRT64 invocation). painfully slowly for some components of the notcurses-demo, but i gather that is far from a surprise given many of the related open issues in both this project and in the windows terminal repo.

i wish i could complain and say that INSTALL.md is insufficiently specific about the requirements, but it's right there in the document, i just failed to comprehend it.

closing this since it's operator error.

**Comment by joseluis** [comment]
> i wish i could complain and say that INSTALL.md is insufficiently specific about the requirements, but it's right there in the document, i just failed to comprehend it.

Yes, but please know that if you think there's something we can improve or clarify or add more detail to something in the instructions that'd be most welcome.

**Comment by esotericist** [comment]
> > i wish i could complain and say that INSTALL.md is insufficiently specific about the requirements, but it's right there in the document, i just failed to comprehend it.
> 
> Yes, but please know that if you think there's something we can improve or clarify or add more detail to something in the instructions that'd be most welcome.

my only suggestion would be a more explicit mention of the need to use the msys2 UCRT64 environment/invocation shortcut, in case a user is unaware that it is yet a separate thing from the msys2/mingw32/mingw64 invocations. to me in my ignorance, it seemed 'obvious' that installing the packages should be enough as long as i wasn't running the cygwin-esque core msys2 environment (and even then, not all users are aware that's what what that is)

**Comment by dankamongmen** [comment]
yeah i want to put together a little "how to make things work on windows" document with pictures and shit, especially so people know to go turn on UTF8 by default in Regional Settings

**Comment by dankamongmen** [comment]
though with #2117 resolved, we're finally solid enough on Windows that i'm willing to submit builds to Windows repos (chocolatey, winget, etc.), which will hopefully alleviate some of the demand for building on windows. i wasn't down for submitting Notcurses when it still couldn't emit the majority of Unicode.

**Comment by dankamongmen** [comment]
@esotericist if you'd like to get involved with the project, i would merge a better windows installation guide with much joy and thanks

**Comment by dankamongmen** [comment]
i'd even accept a docx, the idea of which makes my asshole clench but what you gonna do

**Comment by dankamongmen** [comment]
of course, LaTeX would be fittingly more esoteric

**Comment by esotericist** [comment]
> yeah i want to put together a little "how to make things work on windows" document with pictures and shit, especially so people know to go turn on UTF8 by default in Regional Settings

today in "today i learned", i learned today you have to turn on UTF8 :grin: 

> though with #2117 resolved, we're finally solid enough on Windows that i'm willing to submit builds to Windows repos (chocolatey, winget, etc.), which will hopefully alleviate some of the demand for building on windows. i wasn't down for submitting Notcurses when it still couldn't emit the majority of Unicode.

that all makes sense. gotta be honest, i'm pretty excited about the future here for cross-platform tui apps. even though i think microsoft pushing towards windows 11 and whatnot is kinda unfortunate (since you cannot make windows terminal default on windows 10 due to them not backporting the OS hook)

> @esotericist if you'd like to get involved with the project, i would merge a better windows installation guide with much joy and thanks

i mostly work on linux, so the windows side of things is less familiar to me. but i suppose being the one most recently trying to actually do it kinda makes me boots on the ground, in a sense? not sure i'm up for volunteering for work just now though :smirk: 

> i'd even accept a docx, the idea of which makes my asshole clench but what you gonna do

terrifying.

> of course, LaTeX would be fittingly more esoteric

i never did learn how to work with that, but you are correct, that would be more fitting.

markdown is about as far as i go for this sort of thing, tho XD

**Comment by joseluis** [comment]
>> of course, LaTeX would be fittingly more esoteric

> markdown is about as far as i go for this sort of thing, tho XD

why not both? :shrug: 

[pandoc-latex-template](https://github.com/Wandmalfarbe/pandoc-latex-template) *A clean pandoc LaTeX template to convert your markdown files to PDF or LaTeX*

**Comment by esotericist** [comment]
post processing tools officially make that not my problem :grinning:

**Comment by dankamongmen** [comment]
if anything needs processing, it can be integrated into the build system (and indeed pretty much has to be in order for the resulting documentation to be distributed on e.g. debian). we've already got a pandoc step for generating man pages and xhtml. images can go in `doc/`. other than that if someone's gonna write documentation for me, i'm inclined to let them do it however they want.

feel no pressure, of course; i was just inviting you =]. heh every day i am amazed that microsoft pays me.

**Comment by dankamongmen** [comment]
> i find it absolutely bewildering that the change in environment results in such a strangely specific error in compiling that code in question, but it works now (once i took the time to get a windows terminal profile set up with the correct UCRT64 invocation). painfully slowly for some components of the notcurses-demo, but i gather that is far from a surprise given many of the related open issues in both this project and in the windows terminal repo.

yeah i was somewhat dismayed last night once i finally got `notcurses-demo` working (in swaths, anyway) on Windows Terminal/MinTTY; something in that path is **sloooooooooooooooooooooowwwww**. i suspect the biggest improvement here would come from #2127, but that's absolutely 3.x material.

**Comment by dankamongmen** [comment]
> What about the msys2 ucrt repository?

certainly seems reasonable, though iirc we are broken on windows at the moment.
