### ISSUE TITLE
missing docs for *palindex* functions

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#2360]
The following static functions are missing at least a brief description of what they do:
- [ ] ncchannel_palindex
- [x] ncchannel_set_palindex
- [x] ncchannels_fg_palindex & ncchannels_bg_palindex
- [x] ncchannels_set_fg_palindex & ncchannels_set_bg_palindex
- [x] nccell_fg_palindex & nccell_bg_palindex
- [x] nccell_fg_palindex_p & nccell_bg_palindex_p

BONUS
- [x] ncchannels_combine

**Comment by dankamongmen** [comment]
done

**Comment by dankamongmen** [comment]
https://www.youtube.com/watch?v=rMV-fenGP1g
