### ISSUE TITLE
add cool retro term to the list of terminals

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#2381]
https://github.com/Swordfish90/cool-retro-term

![image](https://user-images.githubusercontent.com/5832068/143508063-a8992e63-9e0e-47b2-b6bc-bcabf7b0b889.png)

they have precompiled appimages in case you want to watch notcurses-demo on it :smile:

**Comment by dankamongmen** [comment]
you wanna give me a PR for this?

**Comment by dankamongmen** [comment]
looks like they have it in debian actually

**Comment by dankamongmen** [comment]
ugh, no way to identify it, no distinct terminfo entry...

**Comment by dankamongmen** [comment]
ugh, no `initc` implementation despite claiming to be xterm
