### ISSUE TITLE
wrap notcurses with safe libsixel API

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2383]
Together with @ctrlcctrlv, I maintain a fork of libsixel, attempting to deal with the mess that was left. It's rife with security problems, and its current API is unsalvageable.

I've suggested a safe API (otherwise equivalent to the existing one), but rather than try to overhaul the original libsixel code, I'd like to just expose some Notcurses code. We'd first need to bring our sixel quantizer up to libsixel's level in both quality and performance (see #1452). But once we do, this seems a good way forward for the ecosystem.

**Comment by ctrlcctrlv** [comment]
Is this related to the discussion had here: https://github.com/libsixel/libsixel/issues/50#issuecomment-962622276 ?

**Comment by dankamongmen** [comment]
no, not at all =]

**Comment by dankamongmen** [comment]
having looked more closely at the libsixel API, there's way more surface area there than expected. i don't think i'll be reimplementing all that anytime soon.

**Comment by ctrlcctrlv** [comment]
@dankamongmen That's okay—all most people need is an encode/decode. If you provide that much we're fine. The rest is easy to provide via a C/Rust mashup.

**Comment by dankamongmen** [comment]
we have that already in the upcoming 3.0.3 release -- `ncvisual_from_sixel()` allows you to load up an `ncvisual` with a nul-terminated Sixel. `ncplane_at_yx()` allows you to grab the encoded Sixel control sequence. you have to go through some Notcurses convolutions (initialize the library, blit the `ncvisual` to some `ncplane`, shutdown the library) but the two tasks you mention are done (they're necessary for my `quantanal` tool, with which i'm improving notcurses's sixel algorithms).
