### ISSUE TITLE
cap [xray] running time

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2385]
`[xray]` can run awfully long on large terminals. i'd like it to take no more than 20s no matter the actual playtime. drop frames to make it so. there are ~870 expected frames, so each can take ~.023s. if a thread decodes its frame and has missed its deadline, keep decoding. we might need to share some extra state to facilitate this, or maybe it'll be self-synchronizing?

i thought we had a bug on dropping frames somewhere, but i can't seem to find it...

**Comment by dankamongmen** [comment]
we're calculating the deadline and passing it out to the threads in `dankamongmen/20sxray`, which sounds like "twenty sex ray" which is sexy

**Comment by dankamongmen** [comment]
ok, i implemented this, and it works, but oh! the flicker! which i don't quite understand....i would expect things to move in lunges, perhaps, but flicker? that doesn't make much sense.

oh! because we're deleting the image on each render where we drop, since it's no longer around...yeah, that's it. ok, let's try to keep one there until we have a new one; that makes sense. and then this ought work, and be solid.

**Comment by dankamongmen** [comment]
20.74, btw, a good bit off from the 20s target =\

**Comment by dankamongmen** [comment]
yep, that worked perfectly, and it looks beautiful. a wonderful change. huzzah!

**Comment by dankamongmen** [comment]
@joseluis , you've complained about this before -- is it now running in ~20s or so max on your machine?

**Comment by joseluis** [comment]
> @joseluis , you've complained about this before -- is it now running in ~20s or so max on your machine?

yes, almost everywhere finishes in about 15,5 seconds (alacritty, wezterm, xterm... are the ones I have with pixel support, other terminals without pixel support like xfce4-terminal run the xray demo as fast). So it runs fast everywhere for me except in kitty v0.23.1 where the terminal halts to a drag with what looks like ±0.2 FPS... ...

```
 1│   intro│   3,14s│    405│  16,41Mi│  129,2│ 8│ 2│17│ 441,96║                                                                                                                                                     
 2│    xray│ 103,43s│     51│  46,80Mi│    0,5│ 0│ 0│88│555,00m║
```

![image](https://user-images.githubusercontent.com/5832068/143848005-31a8ac19-8612-4fc8-bd35-eac23beb2d39.png)
