### ISSUE TITLE
Installation of cffi bindings with pip fails

### ISSUE THREAD

**Issue by Mukundan314** [dankamongmen/notcurses#2391]
Currently installing the package from pypi (`pip install notcurses`) fails with:
```
  ERROR: Command errored out with exit status 1:
   command: /home/mukundan/.local/share/asdf/installs/python/3.10.0/bin/python3.10 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-43hy8fg4/notcurses_cbbb76c361884c328cda087dd245a3fe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-43hy8fg4/notcurses_cbbb76c361884c328cda087dd245a3fe/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-9mw1147r
       cwd: /tmp/pip-install-43hy8fg4/notcurses_cbbb76c361884c328cda087dd245a3fe/
  Complete output (26 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-43hy8fg4/notcurses_cbbb76c361884c328cda087dd245a3fe/setup.py", line 35, in <module>
      setup(
    File "/home/mukundan/.local/share/asdf/installs/python/3.10.0/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/mukundan/.local/share/asdf/installs/python/3.10.0/lib/python3.10/distutils/core.py", line 108, in setup
      _setup_distribution = dist = klass(attrs)
    File "/home/mukundan/.local/share/asdf/installs/python/3.10.0/lib/python3.10/site-packages/setuptools/dist.py", line 455, in __init__
      _Distribution.__init__(self, {
    File "/home/mukundan/.local/share/asdf/installs/python/3.10.0/lib/python3.10/distutils/dist.py", line 292, in __init__
      self.finalize_options()
    File "/home/mukundan/.local/share/asdf/installs/python/3.10.0/lib/python3.10/site-packages/setuptools/dist.py", line 807, in finalize_options
      ep(self)
    File "/home/mukundan/.local/share/asdf/installs/python/3.10.0/lib/python3.10/site-packages/setuptools/dist.py", line 814, in _finalize_setup_keywords
      ep.load()(self, ep.name, value)
    File "/tmp/pip-install-43hy8fg4/notcurses_cbbb76c361884c328cda087dd245a3fe/.eggs/cffi-1.15.0-py3.10-linux-x86_64.egg/cffi/setuptools_ext.py", line 219, in cffi_modules
      add_cffi_module(dist, cffi_module)
    File "/tmp/pip-install-43hy8fg4/notcurses_cbbb76c361884c328cda087dd245a3fe/.eggs/cffi-1.15.0-py3.10-linux-x86_64.egg/cffi/setuptools_ext.py", line 49, in add_cffi_module
      execfile(build_file_name, mod_vars)
    File "/tmp/pip-install-43hy8fg4/notcurses_cbbb76c361884c328cda087dd245a3fe/.eggs/cffi-1.15.0-py3.10-linux-x86_64.egg/cffi/setuptools_ext.py", line 25, in execfile
      exec(code, glob, glob)
    File "src/notcurses/build_notcurses.py", line 14, in <module>
      with open('../include/notcurses/notcurses.h') as fp:
  FileNotFoundError: [Errno 2] No such file or directory: '../include/notcurses/notcurses.h'
  warning: pypandoc module not found, won't generate man pages
```

This is probably due to the [sdist](https://pypi.org/project/notcurses/#files) currently uploaded to pypi not containing the include dir

I think this can probably be fixed by copying the `include` directory somewhere inside the `cffi` directory when setup.py is run by overriding `run` in `cmdclass` (similar to the what `ManPageGenerator` is doing) then including the copied directory in [`MANIFESTS.in`](https://packaging.python.org/guides/using-manifest-in/#manifest-in-commands) and changing the `open(../include/notcurses/<header>.h)` lines to point to the location of the copied directory

**Comment by dankamongmen** [comment]
oh hrmm yes, that's definitely broken. i haven't looked at the python bindings in ages, and have never tried using them off of pip; they are unloved =\. you seem to have a good idea as to how to fix things; i'd love and cherish a PR!

**Comment by dankamongmen** [comment]
i've marked this for 3.0.0, and would love to not be shipping a totally broken pip, but i'm gonna be honest: if you or someone else who knows what they're doing with python doesn't get it, it's likely to get punted past the release (currently scheduled for tomorrow or maybe wednesday).

**Comment by dankamongmen** [comment]
also, you should know that @igo95862 wrote what are believed to be much superior wrappers in `python/` (as opposed to my naive wrappers in `cffi`, which are still being uploaded to pip). you might want to take a look at them as a better option.

the only problem with them is that i can't use them for e.g. the debian package because of missing man pages etc. or maybe that situation has even changed. sorry to come across like an uninformed idiot, but regarding python i am sadly an uninformed idiot.

**Comment by Mukundan314** [comment]
Thanks for the quick reply

> oh hrmm yes, that's definitely broken. i haven't looked at the python bindings in ages, and have never tried using them off of pip; they are unloved =. you seem to have a good idea as to how to fix things; i'd love and cherish a PR!

I too do not have much experience with packaging with cffi, though would be happy to submit a pr if I get something working.

> also, you should know that @igo95862 wrote what are believed to be much superior wrappers in python/ (as opposed to my naive wrappers in cffi, which are still being uploaded to pip). you might want to take a look at them as a better option.

@igo95862's python wrapper seems to be causing core dumps when using anything that has to do with color (including running the provided examples which use color)

**Comment by dankamongmen** [comment]
very valuable feedback, thank you kindly for testing our broken crap @Mukundan314  =]

**Comment by dankamongmen** [comment]
@Mukundan314 if you give me the sample code you ran against the `python/` bindings which crashed, i might be able to at least trace through it and see if maybe i broke it recently.

**Comment by Mukundan314** [comment]
I only tried on tag `v2.4.9`. I can try on `master` later today if you want that.

sample code that crashes:
```python
from notcurses import Notcurses

nc = Notcurses()
stdplane = nc.stdplane()
stdplane.set_fg_rgb8(0, 0, 0)
stdplane.set_fg_rgb8(255, 0, 0)  # does not crash if this line is removed
```
