### ISSUE TITLE
notcurses-input [kitty]: ctrl+alt+shift+arrow not recognized

### ISSUE THREAD

**Issue by dnkl** [dankamongmen/notcurses#2394]
Seen on kitty and foot (with the not yet merged PR [ Kitty keyboard protocol: "Disambiguate escape codes"](https://codeberg.org/dnkl/foot/pulls/811)).

<kbd>Control</kbd>+<kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>up/left/down/right/home/end</kbd> (using the Kitty keyboard protocol) are not recognized by ncurses-input. All other modifier combinations appear to work correctly for the same keys. The numpad left/right/up/down also appears to work correctly. Only the "normal" left/right/up/down keys are misbehaving.

```
acsu ASCII: [0x1b (027)] '␛'
acsu ASCII: [0x5b (091)] '['
acsu ASCII: [0x31 (049)] '1'
acsu ASCII: [0x3b (059)] ';'
acsu ASCII: [0x38 (056)] '8'
acsu ASCII: [0x41 (065)] 'A'
acsu ASCII: [0x1b (027)] '␛'
acsu ASCII: [0x5b (091)] '['
acsu ASCII: [0x31 (049)] '1'
acsu ASCII: [0x3b (059)] ';'
acsu ASCII: [0x38 (056)] '8'
acsu ASCII: [0x41 (065)] 'A'
acsu ASCII: [0x1b (027)] '␛'
acsu ASCII: [0x5b (091)] '['
acsu ASCII: [0x31 (049)] '1'
acsu ASCII: [0x3b (059)] ';'
acsu ASCII: [0x38 (056)] '8'
acsu ASCII: [0x41 (065)] 'A'
```

notcurses version: 
```
notcurses 2.4.97 on foot 1.10.1-20-g512a07fd (Linux 5.11.16-artix1-1)
68 rows (15px) 106 cols (7px) 1020x742 rgb+256 colors
gcc-11.1.0 (LE)
terminfo 6.3.20211021 libdeflate 1.8 GPM n/a
avformat 58.76.100 avutil 56.70.100 swscale 5.9.100 avcodec 58.134.100
```

**Comment by dankamongmen** [comment]
yessssssssssssssssssss already this has paid off excellent

**Comment by dankamongmen** [comment]
hrmmm, it seems to be recognized in kitty:

![2021-11-28-064158_639x249_scrot](https://user-images.githubusercontent.com/143473/143766237-9c54b2e5-5602-43b2-a21b-f89869b3f704.png)

that "ACSL down" is Alt + Ctrl + Shift + Release + down. let me try in foot...

**Comment by dankamongmen** [comment]
confirmed i do *not* recognize it in foot. i appeat to get 0x1b 0x5b 0x31 0x3b 0x38 0x42, let's see....

**Comment by dankamongmen** [comment]
so yeah i match your output, that's good at least

**Comment by dankamongmen** [comment]
so which of us is wrong? =] let me consult my https://sw.kovidgoyal.net/kitty/keyboard-protocol/

**Comment by dankamongmen** [comment]
confirmed that if i only engage kitty with `1u`, i see the same behavior there.

**Comment by dankamongmen** [comment]
so this looks like my bug, thanks much @dnkl !

**Comment by dankamongmen** [comment]
have a good fix, tested with kitty in `1u`, and with foot, good fix bothwise

**Comment by dankamongmen** [comment]
in now, gonna get these other keys that need the same fix

**Comment by dnkl** [comment]
That was quick! Thanks a bunch!
