### ISSUE TITLE
kitty kbd: keypad "begin" key pressed not recognized

### ISSUE THREAD

**Issue by dnkl** [dankamongmen/notcurses#2396]
Pressing the <kbd>5</kbd> key on the keypad, with <kbd>NumLock</kbd> **off**, emits a `KP_Begin` sequence. notcurses-input recognizes **release** and **repeat** events, but not the **press** event. The key code for it is `\E[E` (`0x1b 0x5b 0x45`).

**Comment by dankamongmen** [comment]
confirmed locally

**Comment by dankamongmen** [comment]
hrmm we ought be pulling this in from terminfo

**Comment by dankamongmen** [comment]
`kbeg=\EOE` in kitty terminfo...not seeing `kbeg` in foot's?

**Comment by dankamongmen** [comment]
interesting. in XTerm, `TERM=xterm-256color`, we have `kbeg=\EOE`, and i recognize keypad 5 as begin.
in kitty, `TERM=xterm-kitty`, we have `kbeg=\EOE`, but `\e[E` is sent, and we do not match the press event.
in foot, `TERM=foot`, we have no `kbeg` entry. `\e[E` is sent, and we do not match the press event.

so do you not agree that the foot terminfo entry ought have `kbeg=\e[E`?

**Comment by dankamongmen** [comment]
or is this part of the kitty keyboard protocol that i've missed?

**Comment by dankamongmen** [comment]
there might be a few more of these, but i just went over my keyboard quickly and didn't see any. definitely please file any more you find!

**Comment by dnkl** [comment]
Hmm, interresting. First, I don't think you should rely on the terminfo for Kitty key sequences; they all refer to the "legacy" mode implemented by XTerm.

Second, I know that a lot of keypad related keys were dropped from foot's terminfo when it was upstreamed. That's because those capabilities refer to the keypad keys **when in _application_ mode**. Foot requires private mode 1035 to be disabled to be able to enter keypad application mode (`\E=`) at all. Since the terminfo should reflect the terminal's default behavior, they were dropped. XTerm also emits `\E[E` for KP5 when the keypad is in "normal" (numerical) mode.

Since numerical/application mode is irrelevant when using the kitty protocol, I think the right course of action is to simply not depend on the terminfo. FWIW, KP-begin is listed in https://sw.kovidgoyal.net/kitty/keyboard-protocol/#functional-key-definitions. (it lists two alternatives - I don't know yet when to use which alternative, but suspect it's in one of the more detailed kitty modes, that I haven't gotten around to yet).

Third, none of my kitty terminfo's have `kbeg`; neither kitty's own, nor the ncurses provided one. `xterm-256color` does have it though.

**Comment by dankamongmen** [comment]
hrm, `infocmp -a` reveals a `/home/dank/src/dankamongmen/kitty/terminfo/x/xterm-kitty` of unknown provenance

**Comment by dankamongmen** [comment]
in any case, it ought be working for you now

**Comment by dnkl** [comment]
> in any case, it ought be working for you now

It does, thanks!

> definitely please file any more you find!

Will do :)
