### ISSUE TITLE
add `NCKEY_TAB`

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#2405]
The TAB (`\t`) should be in the same category as NCKEY_ENTER, NCKEY_BACKSPACE, NCKEY_ESC... since it's not a printable character, and that irregularity complicates input management.

**Comment by joseluis** [comment]
alternatively, or additionally, trying to output a tab into a plane maybe should not fail, or be converted to a space?

**Comment by dankamongmen** [comment]
does it not fail? it ought be failing, ack! see #1233

**Comment by dankamongmen** [comment]
added an `NCKEY_TAB` alias

**Comment by joseluis** [comment]
> does it not fail? it ought be failing, ack! see #1233

yes it does but why does it have to fail? Isn't it better to ignore it even, rather than fail?

**Comment by dankamongmen** [comment]
i am of the general opinion that if i explicitly ask you to do something, and you can't do it, you ought report a failure, and let me cope with it the way i see best.

if i call `printf()` with `\t` tabs in my strings, i expect horizontal tabs. if i don't get them, i'll be very irritated at that libc author.

i expect to support tabs in the future; that's what #1233 is all about. NCURSES allows you to reprogram tabs and do all kinds of things. i'm not certain we need all that, but we ought do something, yes.

closing this, as `NCKEY_TAB` now exists.

**Comment by joseluis** [comment]
Ok. Understood.

One more question, though shouldn't `nckey_synthesized_p` be updated to check also for `NCKEY_ESC` & `NCKEY_TAB`?

At least in the Rust bindings I have to check for them separately in order to identify them as an NcKey, and not as normal characters... But maybe you only use that function to know if it has the PRETERUNICODEBASE prefix?

I'm still a little confused regarding the ambiguity of having them with one leg here and another leg there...

**Comment by dankamongmen** [comment]
> One more question, though shouldn't `nckey_synthesized_p` be updated to check also for `NCKEY_ESC` & `NCKEY_TAB`?

nope. these aren't synthesized keys; they're just aliases.

> At least in the Rust bindings I have to check for them separately in order to identify them as an NcKey, and not as normal characters... But maybe you only use that function to know if it has the PRETERUNICODEBASE prefix?
> I'm still a little confused regarding the ambiguity of having them with one leg here and another leg there...

`NCKEY_TAB` is always 0x09, and `NCKEY_ESC` is always 0x1B. they're just aliases. you can test with `NCKEY_TAB`; you can test with 0x09. `NCKEY_TAB` is just

```c
#define NCKEY_TAB 0x09
```

whereas truly synthesized keys have no unicode equivalents, or ambiguous unicode equivalents, and are thus defined outside of Unicode.

**Comment by joseluis** [comment]
> truly synthesized keys have no unicode equivalents, or ambiguous unicode equivalents, and are thus defined outside of Unicode

:+1:
