### ISSUE TITLE
Do you need help with Rust?

### ISSUE THREAD

**Issue by thescribe11** [dankamongmen/notcurses#2418]
In the release notes for 3.0 you said that you need help porting this project to other languages such as Python and C#. Do you need help with Rust?

**Comment by dankamongmen** [comment]
nope, the good man @joseluis has it well-covered over in https://github.com/dankamongmen/notcurses-rs/, but you're welcome to see if he needs anything! =] thanks for your interest =]

**Comment by joseluis** [comment]
Well, in reality the only well-covered Rust wrapper library for now is this one https://github.com/dankamongmen/libnotcurses-sys/ which is the lowest-level one, and with the most complete documentation. Once it becomes more stable I'll continue working on notcurses-rs, but note they're not in a usable state at the moment.

@thescribe11 you're welcome to take a look and give it a try if you want
