### ISSUE TITLE
expose default colors to client code

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2432]
We look up the default colors via interrogating the terminal, but don't make them available to the user. We ought. As a first example, to achieve highcontrast atop the user's configured, arbitrary background, they might want to extract said background (actually, we should support `HIGHCONTRAST` atop default background now).

**Comment by dankamongmen** [comment]
we're now exporting the default background color.

**Comment by dankamongmen** [comment]
we're not querying and interpreting the default foreground, but it's not even being stored in the `terminfo` yet.

**Comment by dankamongmen** [comment]
default foreground color is now detected and exposed.

**Comment by joseluis** [comment]
@dankamongmen could you tell me what's being stored exactly in the `bgtrans` variable, Is it an `NCALPHA_` value? I don't quite understand the doc comment in the new `notcurses_default_background`.

BTW what does `iff` stands for? I see it's used in a couple more places in the header, but one I think is a mistake (in `ncplane_descendant_p` I believe there's an extra `f`)

**Comment by joseluis** [comment]
If there's both rgb color and transparency to be returned, I'm wondering why don't we return an ncchannel?

**Comment by dankamongmen** [comment]
transparency here is a weird concept that only applies to Kitty. maybe i ought not expose it to the user? kitty, even when you set an explicit background, interprets it as transparent if it matches the default background color. we work around this by changing such an explicit color by 1 in the blue channel.

i probably oughtn't export this to the user. good call.

**Comment by dankamongmen** [comment]
unexported.
