### ISSUE TITLE
notcurses-demo j (jungle) is permantently changing terminal colors

### ISSUE THREAD

**Issue by blackbit42** [dankamongmen/notcurses#2435]
Please include the following data:
* `export | egrep 'LANG|LC_CTYPE|TERM'`

`declare -x COLORTERM="rxvt-xpm"`
`declare -x LANG="en_US.UTF-8"`
`declare -x LANGUAGE="en_US:en"`
`declare -x TERM="rxvt-unicode-256color"`

* notcurses version (available from `notcurses-demo i`)

`notcurses 3.0.0`

* terminal name + version

`rxvt-unicode 9.26-2 (Debian testing)`

-----------------------------------------------

Before run of `notcurses-demo j`:

![image](https://user-images.githubusercontent.com/19274131/144859572-d6f858a2-1f17-427e-8cf5-b70664611f1d.png)

After run of `notcurses-demo j`:

![image](https://user-images.githubusercontent.com/19274131/144859364-d3f5b3da-4981-42a0-a1d9-dd3084e25cc9.png)

All other demos do not alter terminal colors.
I tried with `kitty`, there no alteration is happening.
The behavior observable in urxvt is probably not intended as such?
What can I do to debug this further?

**Comment by dankamongmen** [comment]
`[jungle]` is the only one which uses palette-indexed color. what i need to do is push and pop the palette, where supported. i can add this soon, though i'm not sure rxvt implements XTPUSHCOLORS.

**Comment by dankamongmen** [comment]
>  CSI # P  Push current dynamic- and ANSI-palette colors onto stack (XTPUSHCOLORS), xterm.
CSI Pm # P  Push current dynamic- and ANSI-palette colors onto stack (XTPUSHCOLORS), xterm.
CSI # Q  Pop stack to set dynamic- and ANSI-palette colors (XTPOPCOLORS), xterm.
          CSI Pm # Q  Pop stack to set dynamic- and ANSI-palette colors (XTPOPCOLORS), xterm.
          CSI # R  Report the current entry on the palette stack, and the number of palettes stored on the stack, using the same form as XTPOPCOLOR (default = 0) (XTREPORTCOLORS), xterm.

**Comment by j4james** [comment]
Just FYI, the standard way to save the palette would be with a `DECRQTSR` sequence to request the `DECCTR` color table report, and a `DECRSTS` sequence to restore things on exit. Admittedly those sequences aren't widely supported, but then neither are the `XTPUSHCOLORS`/`XTPOPCOLORS` sequences.

**Comment by dankamongmen** [comment]
nice. i'll look into doing this this weekend.

**Comment by dankamongmen** [comment]
https://vt100.net/docs/vt510-rm/DECRQTSR.html
https://www.manualslib.com/manual/1200903/Digital-Equipment-Vt520.html?page=268

i haven't been able to get anything responding to this yet, though...

**Comment by dankamongmen** [comment]
argh. i went and looked, and i've already implemented XTPUSHCOLOR/XTPOPCOLOR. i doubt rxvt supports them if you're seeing this problem. @blackbit42 , can you run `echo -e '\e[#R'` and tell me if there's any output?

**Comment by dankamongmen** [comment]
yeah, looking at http://web.fis.unico.it/public/rxvt/refer-frame.html, i don't see any way to preserve the palette.

hrmm.

**Comment by dankamongmen** [comment]
`echo -e '\e]4;1;?\e\\'`

gets us the first palette color on xterm, kitty, rxvt, xterm (configurable), VTE, *not* alacritty, *not* Konsole, mlterm, iTerm2.

requesting 256 of these is likely to noticeably affect startup time by at least a few milliseconds. let's refrain from doing so anywhere we use XTPUSHCOLORS or DECRQTSR to set the full table. maybe we refrain from doing so until we actually want to use palette-indexed color?

but this ought be able to solve things for @blackbit42 on rxvt.

**Comment by blackbit42** [comment]
> can you run `echo -e '\e[#R'` and tell me if there's any output?

```
$ echo -e '\e[#R'

$
```

No (visible) output.

**Comment by dankamongmen** [comment]
> > can you run `echo -e '\e[#R'` and tell me if there's any output?
> 
> ```
> $ echo -e '\e[#R'
> 
> $
> ```
> 
> No (visible) output.

yep, figured as much. well, we'll be able to use the other method. can you please verify that `echo -e '\e]4;1;?\e\\'` generates some output?

**Comment by blackbit42** [comment]
> yep, figured as much. well, we'll be able to use the other method. can you please verify that `echo -e '\e]4;1;?\e\\'` generates some output?

```
$ echo -e '\e]4;1;?\e\\'

$ 4;1;rgb:dc00/3200/2f00
```

**Comment by dankamongmen** [comment]
w00t!

**Comment by j4james** [comment]
> https://vt100.net/docs/vt510-rm/DECRQTSR.html https://www.manualslib.com/manual/1200903/Digital-Equipment-Vt520.html?page=268
> 
> i haven't been able to get anything responding to this yet, though...

Of the terminals you're likely to use, I think MLTerm and RLogin both support this.

And regarding `OSC 4`, that's not a terrible choice, because quite a lot of terminals do support it, but they can be a bit flaky when querying multiple colors at once, and having a separate query for each color is a bit painful.

**Comment by dankamongmen** [comment]
> And regarding `OSC 4`, that's not a terrible choice, because quite a lot of terminals do support it, but they can be a bit flaky when querying multiple colors at once, and having a separate query for each color is a bit painful.

absolutely; it would be a last-ditch solution

**Comment by dankamongmen** [comment]
i don't see any way that we can make this long series of queries conditional on use. we could for the case where we're setting palette entries, that's easy enough -- each render, if there is a set, see whether we've set them before, and if not, blast away with N queries. but if we want to be able to do things like say blend based on palette-indexed color (see #2442), we would need the palette entries as far back as the render step.

though i suppose we could apply the same logic to this -- each render, if we run into a palette index blend, see whether we've queried them before, and if not, block on a response -- though it would be a bit more complex, control-wise.

i mean we're talking up to 256 queries. that's 9 to 11 bytes per query, an average of 9+2.57 BPQ, 2962B of query. responses are a flat 24B, 6144B of response. at 50GB/s of L2 bandwidth that's .12µs if we can hide all computation under the load. there's no real reason to think we can, or that this meaningfully assesses the additional time, but it suggests we ought be able to keep the impact under the millisecond mark, at which point who cares? let's code it up and see what happens.

**Comment by dankamongmen** [comment]
we still want to use the push/pop where it's supported, as that's faster on shutdown than sending N sets. but even in this case, we'll be doing the N reads at startup.

**Comment by blackbit42** [comment]
>  at which point who cares? let's code it up and see what happens.

word.

**Comment by dankamongmen** [comment]
```
[schwarzgerat](0) $ rm query ; for i in `seq 0 255` ; do echo -en "\e]4;$i;?\e\\" >> query; done ; ls -l query
-rw-r--r-- 1 dank dank 2706 2021-12-09 19:18 query
[schwarzgerat](0) $ 
```

**Comment by dankamongmen** [comment]
i've added code to send the query, and can verify we're getting a crapton of responses

**Comment by dankamongmen** [comment]
we should probably limit it to the number of advertised colors, ooooh except we don't have that available at query time. oh well, shouldn't do anything but waste time.

**Comment by dankamongmen** [comment]
```
palette_cb:1289:index 213 0xff87ff
palette_cb:1289:index 214 0xffaf00
palette_cb:1289:index 215 0xffaf5f
palette_cb:1289:index 216 0xffaf87
palette_cb:1289:index 217 0xffafaf
palette_cb:1289:index 218 0xffafd7
palette_cb:1289:index 219 0xffafff
palette_cb:1289:index 220 0xffd700
palette_cb:1289:index 221 0xffd75f
palette_cb:1289:index 222 0xffd787
palette_cb:1289:index 223 0xffd7af
palette_cb:1289:index 224 0xffd7d7
palette_cb:1289:index 225 0xffd7ff
palette_cb:1289:index 226 0xffff00
palette_cb:1289:index 227 0xffff5f
palette_cb:1289:index 228 0xffff87
palette_cb:1289:index 229 0xffffaf
palette_cb:1289:index 230 0xffffd7
palette_cb:1289:index 231 0xffffff
palette_cb:1289:index 232 0x080808
palette_cb:1289:index 233 0x121212
palette_cb:1289:index 234 0x1c1c1c
palette_cb:1289:index 235 0x262626
palette_cb:1289:index 236 0x303030
palette_cb:1289:index 237 0x3a3a3a
palette_cb:1289:index 238 0x444444
palette_cb:1289:index 239 0x4e4e4e
palette_cb:1289:index 240 0x585858
palette_cb:1289:index 241 0x626262
palette_cb:1289:index 242 0x6c6c6c
palette_cb:1289:index 243 0x767676
palette_cb:1289:index 244 0x808080
palette_cb:1289:index 245 0x8a8a8a
palette_cb:1289:index 246 0x949494
palette_cb:1289:index 247 0x9e9e9e
palette_cb:1289:index 248 0xa8a8a8
palette_cb:1289:index 249 0xb2b2b2
palette_cb:1289:index 250 0xbcbcbc
palette_cb:1289:index 251 0xc6c6c6
palette_cb:1289:index 252 0xd0d0d0
palette_cb:1289:index 253 0xdadada
palette_cb:1289:index 254 0xe4e4e4
palette_cb:1289:index 255 0xeeeeee
[schwarzgerat](0) $ 
```

sweet

**Comment by dankamongmen** [comment]
no noticeable time impact at the millisecond level, w00t

**Comment by dankamongmen** [comment]
(using kitty, anyway)

**Comment by dankamongmen** [comment]
so now we just need route this 768 byte ball of crap out to `nc->palette`, and it's already integrated into the renderer. then we add to `notcurses_stop_minimal()` an else clause on the `XTPOPCOLORS`, and dump the originals if it's not supported. ahhh, i guess that means we'll need keep these ungainly 768 bytes copied in the terminfo. sigh, we used to be a real country.

**Comment by dankamongmen** [comment]
oh, shitfire, rxvt doesn't reply with a full ST (\e\\), just a closing escape. ugh.

**Comment by dankamongmen** [comment]
so this kinda screws me. i build an automaton to match incoming control sequences, possibly interleaved with other text. most terminals respond with a message terminated by ESC \\ aka "ST" in the parlance. rxvt doesn't include that final \. so i'd need to accept on a bare ESC. if i do that, everything else is going to look like a response followed by an actual backslash.

that sucks. i mean, i can apply a heuristic like "consume a backslash that follows this control sequence", but then what if there's a real backslash? ugh. =\

**Comment by dankamongmen** [comment]
looking at it, rxvt seems completely busted. its response to a palette definition request is ill-formed. this response ought end either in ST ("\e\\") or BEL ("\x07"). it ends instead in ESC ("\e"). it defines the `oc` (original colors) terminfo capability, but experiment shows that `oc` does not function, at least on rxvt as packaged with debian unstable. `reset` does not reset the palette. indeed, Notcurses' emission of `oc` is why we don't have any of this palette restore logic existing, and yet things work most places (although we're presumably blowing away custom palettes, which i should do something to address).

i'm thinking i might just disable palette changes on `rxvt`

**Comment by dankamongmen** [comment]
so even querying them is a no-go at the moment, since it would result in all the responses being interpreted as input on poor old rxvt. we could elide them, making an entirely `TERM`-based decision (rxvt doesn't appear to identify itself in any query-based fashion anyway, unsurprisingly). then we could at least query the palette on other terminals.

**Comment by dankamongmen** [comment]
hrmmmm...i *guess* we could just shape the automaton based on whether we're in rxvt? yeah, that's probably our best option.

**Comment by dankamongmen** [comment]
Alright, I think I've got a best-of-all-worlds solution:

* rxvt is identified early based off `TERM`. everything following **requires `TERM` to be properly set to `rxvt*`**
* iff we're rxvt, we load a custom automaton rule that is terminated with a bare ESC
* we send the 256 queries now
* we no longer issue `oc` at initialization now, preserving custom palettes
* on shutdown, if we have XTPOPCOLORS, we use that
* otherwise, if we've never touched the palette, do nothing
* otherwise, if we read the palette before (and have `initc`), reprogram it with 256 sequences
* otherwise, if we have `oc`, use it (this loses a custom palette)

rxvt is now preserving the preexisting palette across even a `[jungle]` run in my testing. this is in the `dankamongmen/getpalette` branch, which i intend to merge shortly.

**Comment by blackbit42** [comment]
Confirmed working with current HEAD.
This is really impressive. Thanks much @dankamongmen !! <3

**Comment by dankamongmen** [comment]
> Confirmed working with current HEAD. This is really impressive. Thanks much @dankamongmen !! <3

[blows smoke from fingers]

[![talk to me](http://img.youtube.com/vi/1b9n0Amr9RI/0.jpg)](http://www.youtube.com/watch?v=1b9n0Amr9RI "talk to me")
