### ISSUE TITLE
kitty kbd: ISO_Level3_Shift not recognized as a modifier

### ISSUE THREAD

**Issue by dnkl** [dankamongmen/notcurses#2439]
It looks like notcurses doesn't recognize the `ISO_Level3_Shift` modifier (and most likely, `ISO_Level5_Shift` too): https://sw.kovidgoyal.net/kitty/keyboard-protocol/#functional-key-definitions.

Instead, it treats the key code as a unicode codepoint:
![kitty-kbd-altgr](https://user-images.githubusercontent.com/14031526/145082276-f9064ce7-a637-422e-b1f1-7eef9f8f612b.png)

I believe <kbd>AltGr</kbd> is the key usually mapped to `ISO_Level3_Shift` . I don't have a physical key to `ISO_Level5_Shift`, and have no idea which key it typically corresponds to.

(I guess simply calling them ISO_LevelN_Shift, instead of AltG, is fine too).

```
notcurses 3.0.0 on foot 1.10.2-28-g72a99554 (Linux 5.11.16-artix1-1)
68 rows (15px) 161 cols (7px) 1020x1127 rgb+256 colors
gcc-11.1.0 (LE)
terminfo 6.3.20211021 libdeflate 1.8 GPM n/a
avformat 58.76.100 avutil 56.70.100 swscale 5.9.100 avcodec 58.134.100
```

**Comment by dankamongmen** [comment]
no idea what these keys are, but i'll look into it =]

**Comment by dnkl** [comment]
On European(?) layouts, <kbd>AltGr</kbd> is mapped to `ISO_Level3_Shift`, and provides a third shift level for keys. For example, my <kbd>2<kbd> key  can generate four different symbols: `2`, `"`, `@` and `²`.

`2` and `"` are the normal un-shifted and shifted (i.e. using <kbd>Shiftz/kbd>) symbols.

`@` and `²` are produced by holding <kbd>AltGr</kbd> and <kbd>AltGr</kbd>+<kbd>Shift</kbd>.

No idea what `ISO_Level5_Shift` is, but guess it's used in some XKB layouts to provide yet another shift level.

**Comment by dankamongmen** [comment]
only four shift levels? we must go deeper

**Comment by dnkl** [comment]
![inception](https://user-images.githubusercontent.com/14031526/145277060-e6ff42b0-061c-4c85-9762-f20ce0033839.gif)

**Comment by dankamongmen** [comment]
we now have the necessary definitions, and ought be mapping them up in `kitty_functional()`. i don't think we're yet treating them as modifiers, though. if you could verify that we properly register the keypresses, i'll move forward with the latter.

**Comment by dnkl** [comment]
Getting "Special [...] 'unknown'", which I suspect is the expected result? I've only been able to test `ISO_Level3_Shift`, but don't see why `ISO_Level5_Shift` shouldn't work as well.

![iso-level3-shift](https://user-images.githubusercontent.com/14031526/145712228-631fa16e-dcc0-438e-afbe-cc542a659cca.png)

**Comment by dankamongmen** [comment]
hrmmm no it ought be saying "separator"

**Comment by dankamongmen** [comment]
7107c9015 should have it saying the correct thing, sorry

**Comment by dankamongmen** [comment]
so these are modifiers, and probably ought be reported with [acsX], huh?

**Comment by dnkl** [comment]
Works!

![iso-level3-shift-2](https://user-images.githubusercontent.com/14031526/145712942-0eb50c92-5434-401b-ad27-6ba3e38068fc.png)

**Comment by dnkl** [comment]
> so these are modifiers, and probably ought be reported with [acsX], huh?

Hmm, not sure what you mean? Is that a literal `X`?

In any case, I don't see modifiers being reported differently, in neither foot nor kitty.

**Comment by dankamongmen** [comment]
sorry, so there's shift, ctrl, and alt; should l[35]shift be treated like a modifier? i.e. ought i be reporting with 'a' that level 3 shift was being held? so the [acsX] prefix on each line would be [acsX35]

**Comment by dankamongmen** [comment]
basically do i need add `l3shift` and `l5shift` to my `ncinput` struct:

```c
diff --git include/notcurses/notcurses.h include/notcurses/notcurses.h
index 0e44b8e76..23cf1df39 100644
--- include/notcurses/notcurses.h
+++ include/notcurses/notcurses.h
@@ -1120,6 +1120,8 @@ typedef struct ncinput {
   bool alt;          // was alt held?
   bool shift;        // was shift held?
   bool ctrl;         // was ctrl held?
+  bool l3shift;      // iso level 3 shift (altgr)
+  bool l5shift;      // iso level 5 shift
   // FIXME kitty protocol also exposes hyper, meta, caps_lock, num_lock
   enum {
     NCTYPE_UNKNOWN,
```

are these "Hyper" and "Meta"?

**Comment by dnkl** [comment]
> are these "Hyper" and "Meta"?

No, I don't think so. There other keys (<kbd>Hyper_{L,R}</kbd> and <kbd>Meta_{L,R}</kbd> that map to the `Hyper` and `Meta` modifiers.

The kitty protocol's encoding of modifiers includes hyper and meta, but not the ISO_LevelX_Shift shift states. So no, I don't think you should treat them as modifiers.

On the terminal side (when we generate the CSI), the ISO_LevelX_Shift modifiers are handled slightly differently. For example, <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>2</kbd> would result in a CSI where the base key is '2'. But <kbd>AltGr</kbd>+<kbd>Alt</kbd>+<kbd>2</kbd> would result in a base key of '@'.

**Comment by dnkl** [comment]
One important thing here is that there's a very distinct difference between a modifier being enabled, and a specific key being pressed.

For example, there's only **one** `Control` modifier. But there are two <kbd>Control</kbd> **keys** (<kbd>Control_R</kbd> and <kbd>Control_L</kbd>). They just so happen to enable the `Control` modifier (in most layouts).

So, `ISO_Level3_Shift` _could_ be mapped to the `Hyper` shift level. But it's not for you to bother with :)  The terminal will (through the current XKB layout).

Put another way, you shouldn't enable/disable modifier state when seeing modifier key press/release events. I.e. just rely on the encoded modifier state in the CSIs.

Clear enough? :)

**Comment by dankamongmen** [comment]
sounds good!
