### ISSUE TITLE
add functionality to allow planes to grow with output

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2440]
While working on `ncman`, it's become apparent that it would be useful to allow a plane to grow with output. My first thoughts are that a plane with scrolling enabled would grow down, and one without would grow to the right.

The question is how this ought be exposed. My first idea was a new function, `ncplane_growtext()` or whatever, that engages this behavior (and otherwise works like `ncplane_puttext()`). That would work, certainly. But ought such functionality be more general? Ought a plane be placed into "growing mode", and all output ought result in growth? There would then be no new function of this kind; you would just set the property, and now all output functions use it. This is clearly more general, but it's also worryingly broad. Should blitting an image to a growling plane grow it? etc. There would likely be a lot of places needing changing to accommodate this -- all the regular output functions go through the `ncplane_put()` chokepoint, but things like boxes, etc. If a plane was set to grow, and we tried to mergedown a larger plane, should the smaller plane grow?

I think I'm just going to do this as `ncplane_growtext()`, but I'm interested in hearing opinions.

**Comment by dankamongmen** [comment]
i was pondering this in part because we also want to introduce support for inline control sequences soon, but i don't want them blindly/always picked up, so we're approaching this cartesian of output properties:

* do we grow?
* do we scroll vertically?
* do we interpret control sequences?
* do we retain the existing styling (stain)?
* do we position ourselves before writing? align?

so if i want to right align and interpret control sequences and scroll vertically but not grow nor stain, how is that expressed?

styling fundamentally feels like a local property, whereas growing and scrolling seem global (plane-wide) properties...but i have no real reason to say that. it's just how it feels.

given that last...i think i'll make this a plane property, one you can set when creating the plane (but is not set by default), and control via a modifier. so `ncplane_growtext()` will be mercifully killed (it was never merged to master).

**Comment by dankamongmen** [comment]
alright i've added `NCPLANE_OPTION_AUTOGROW`, `ncplane_set_autogrow()`, and `ncplane_autogrow_p()` declarations and documentation, likewise `NCPLANE_OPTION_VSCROLL`.

**Comment by dankamongmen** [comment]
got all those basics implemented and unit tested. now just need to implement the actual autogrowth.

**Comment by dankamongmen** [comment]
alright, implemented it as simply as i could imagine, and immediately `ncman` got straightened out...i think we have a winnah!

![2021-12-08-010556_1453x1410_scrot](https://user-images.githubusercontent.com/143473/145156994-83674cec-5ded-4c16-a5f2-82c63bbb5c09.png)

**Comment by joseluis** [comment]
@dankamongmen what happens if both `NCPLANE_OPTION_AUTOGROW` and `NCPLANE_OPTION_VSCROLL` flags are set at the same time? should that be avoided?

**Comment by dankamongmen** [comment]
autogrow without vscroll => grow to the right
autogrow with vscroll => grow down

**Comment by joseluis** [comment]
> autogrow without vscroll => grow to the right autogrow with vscroll => grow down

thks, didn't understood at first they can work together
