### ISSUE TITLE
get sextants into cascadia code

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2443]
this is the default font for the new Microsoft Terminal, but it sadly lacks sextants. if it had them, maybe we could enable sextants for windows, and thus the `NCBLIT_3x2`.

![2021-12-07-205959_2319x1440_scrot](https://user-images.githubusercontent.com/143473/145135193-c73048d8-09be-4705-939a-f9df47fb6c99.png)

**Comment by dankamongmen** [comment]
https://github.com/microsoft/cascadia-code/issues/607 has been filed; let's see what happens

**Comment by j4james** [comment]
Just be aware that even if the font supported sextants, you're still not going to be able to use them in Windows Terminal because of the way astral plane characters are stored (they require two cell positions in the buffer). You can see the effect that has in the screenshot I did of the notcurses-info output here: https://github.com/dankamongmen/notcurses/issues/2117#issuecomment-968032849

**Comment by dankamongmen** [comment]
@j4james always up in here pouring cold water on my dreams =]

**Comment by j4james** [comment]
Sorry. 😉 If it's any consolation, it will get fixed eventually, so it'll still be good to get those characters supported in Cascadia Code. I just wanted to make sure you were aware of the current Windows limitations, so you don't feel like you've wasted your time on this when it doesn't pan out.

**Comment by dankamongmen** [comment]
i assure you your comments are worth their weight in gold; please keep them coming. on this kind of thing, i see "we need both sextant glyphs and proper display thereof to enable NCBLIT_3x2". if i can assist in getting one half done, that means i can execute as soon as the other half is completed, and hopefully provides incentive for others to do the latter half.

**Comment by dankamongmen** [comment]
so yeah, i've filed a bug and volunteered to do the work over in their repo; there's not much more we can do here.
