### ISSUE TITLE
Suggestion: Make python-pypandoc optional / Split notcurses-doc into separate AUR package

### ISSUE THREAD

**Issue by 3nprob** [dankamongmen/notcurses#2466]
For architectures without binary releases for pandoc/haskell/stack (notably arm64), building documentation is currently the major pain-point and timesink involved in getting up and running with notcurses.

It would therefore help a lot to either make pandoc an optional build-dependency for `notcurses-git`, alternatively splitting `notcurses-doc-git` into a separate package.

**Comment by dankamongmen** [comment]
so i package up prebuilt documentation and put it on the release page with each release, of the form `notcurses-doc-{version}.tar.gz`. serveral distros just download this rather than getting pandoc and building things afresh. does that work for you?

**Comment by 3nprob** [comment]
Ah right! Yes, sounds good to me.

As for what makes the most sense for `notcurses-git`, I guess the expectation for `-git` packages would be that everything is built, so the idiomatic thing would be to make pandoc optional and fall back to not having docs.

Personally I'd have a slight prefence to have the prebuilt docs included like other distros do, but I have a feeling there may be those who frown upon it.

**Comment by dankamongmen** [comment]
wait am i speaking to schoober420 with whom i'm comaintaining the arch notcurses-git package?

**Comment by dankamongmen** [comment]
well either way, i agree that this is a smart thing to do in the `notcurses-git` AUR package, though it would mean tying the package to released versions (as those are the only ones with generated docs).

**Comment by 3nprob** [comment]
> wait am i speaking to schoober420 with whom i'm comaintaining the arch notcurses-git package?

no, just a rando being a bit overexcited about the latent potential of notcurses

**Comment by dankamongmen** [comment]
i've got the new candidate `PKGBUILD` downloading the documentation tarball, just need to get it installing the pages now...i've dropped `pandoc` from the depends, and added `-DUSE_PANDOC=off`.

**Comment by dankamongmen** [comment]
i just killed all python in the `notcurses-git` package. all pandoc deps dropped.
