### ISSUE TITLE
`static inline`s makes it slightly awkward to wrap the library in languages that `dlopen` libraries to call into them

### ISSUE THREAD

**Issue by KristofferC** [dankamongmen/notcurses#2476]
In some languages (the code in this post is Julia code), the way you tend to wrap a C-library is:

- Parse the header files (and find e.g. `API ALLOC struct ncdirect* ncdirect_init(const char* termtype, FILE* fp, uint64_t flags);`).
- Emit code for a function that does an FFI call from the wrapping language into the library 
  ```jl
  const libnotcurses = "libnotcurses.so"

  mutable struct ncdirect end

  # @ccall is Julia's way of calling into a c function 
  function ncdirect_init(termtype, fp, flags)
        @ccall libnotcurses.ncdirect_init(termtype::Ptr{Cchar}, fp::Ptr{Libc.FILE}, flags::UInt64)::Ptr{ncdirect}
  end
  ```
- `dlopen` the library: 
  ```jl
  julia> using Libdl

  julia> dlopen("./libnotcurses.so")
  Ptr{Nothing} @0x0000000003dd3a50
  ```
- Call into the opened library using the earlier defined FFI function:
   ```jl
    julia> ncdirect_init(C_NULL, C_NULL, 0)
    Ptr{ncdirect} @0x0000000002bc6bc0
    ``` 

And you get a pointer to the `ncdirect` struct and everything is all gucci. However, if one now tries to do the same procedure for `notcurses_render`, then at the call into the library one is met with:

```jl
ERROR: could not load symbol "notcurses_render":
/usr/local/lib/libnotcurses.so: undefined symbol: notcurses_render
```

The reason for this is (of course) that `notcurses_render` does actually not exist in the library since it is `static inline` in a header file. There are now a few options for the author of the wrapper:

- Manually convert the inlined function into the wrapper language.
- Transpiling the C code of the function to the language that is used for the wrapper.

Both of these are somewhat annoying. Manually translating C-code is not fun and transpiling is brittle. It would be preferable (from the author of the wrapper's p.o.v) if these symbols existed in the library and could just be called like many of the other functions.

I am not really experienced enough (neither with the library nor with C-libraries in general) to know all the trade-offs here but I wonder if there is a way to have the cake (get the performance of static inline in the standard case) while still being able to eat it (allow wrapper authors to optionally create libraries with the static inline functions as present in the `libnotcurses` shared library). Or perhaps the `static inline`s are not really that important for performance and could be moved into c-files? With e.g. LTO things might get inlined anyway?

Any thoughts? Happy to provide more details if useful.

**Comment by joseluis** [comment]
i just want to share that for the Rust wrappers I opted for the first option, that is reimplementing all the static inline functions. One important thing to realize is that the work does not end there, and you'll have to keep updating them every now and then, each time their implementation is modified, which is easy to miss if you're not closely monitoring the changes to the headers/the repo commits.

**Comment by dankamongmen** [comment]
so theoretically i ought be able to emit these definitions using some gcc invocation from beyond the dawn of time. i'll look into it, but i'm not terribly optimistic; i recall having these same difficulties when writing the original python wrappers, and not being able to do much.

still, surely this problem has been encountered before. we just want, for each `static inline` function, an actual function body emitted and retained as a symbol in the library, right? that would be sufficient for your needs? i don't love the idea, since it will slow loading times and enlarge the ABI space. perhaps i can build it as a distinct shared object? that would have to be its own debian package, and go through FTPteam approval, but such is life. or maybe i just oughtn't care about those nanoseconds.

i'll look into it. i'm pretty sure there's some hoary old python bug that has some notes on this topic, way back in early 2020 or even 2019.

you all ought just write C like decent godfearing people.

**Comment by dankamongmen** [comment]
oh by the way does this also apply to macros? i.e. do you need an `NCCHANNEL_INITIALIZER` symbol? that's messy, if so; you can't just spooge the (approximately) call-by-name semantics of the C preprocessor into the rigid call-by-value semantics of the C β-reduction (function call).

**Comment by KristofferC** [comment]
If there is a good solution, perhaps it could be a build option? 

I found this in the gcc docs:

 > When a function is both inline and static, if all calls to the function are integrated into the caller, and the function’s address is never used, then the function’s own assembler code is never referenced. In this case, GCC does not actually output assembler code for the function, unless you specify the option `-fkeep-inline-functions`.

I'm not in a position to try it out now but I'll poke at it tomorrow.

**Comment by KristofferC** [comment]
> oh by the way does this also apply to macros?

Nah, the tool I am using has some support for transpiling those to the wrapping language so I'm good there at least

**Comment by dankamongmen** [comment]
yeah `-fkeep-inline-functions` is what i tried. here's the history:

https://github.com/dankamongmen/notcurses/issues/1636
https://github.com/dankamongmen/notcurses/issues/924
https://github.com/dankamongmen/notcurses/issues/800

so it looks like one of the problems involved undesirable C++ symbol leakage, but that oughtn't be a problem so long as we restrict its application to C. reading through #800, it looks like i got distracted by a self-inflicted break, and then implemented most of the static inline functionality in python, eliminating the immediate need.

so take a look through #800 and the issues raised there, and i think we can probably get this done.

**Comment by KristofferC** [comment]
I played around with this locally just to get some experience and what got me what I wanted the quickest was real foul but seems to work. Basically, I search replaced `static inline` to `API`, slapped a `add_link_options(-Wl,--allow-multiple-definition)` onto the CMake file, and then I got my hello world example working.

```
❯ nm /usr/local/lib/libnotcurses.so | grepnotcurses_render
00000000000073f0 T notcurses_render
```

I'll look through https://github.com/dankamongmen/notcurses/issues/800 now.

**Comment by KristofferC** [comment]
Some follow up question. 

What are the concrete advantages of the current static inline functions? Is it for performance, library size etc? How was it decided what functions should be static inline? 

If there is some benchmark that shows that the advantage of these are not significant, would a PR to make them normal functions be accepted? Naively it feels like with LTO the compiler should see the definitions anyway and inline them where it makes sense according to its cost model.

**Comment by dankamongmen** [comment]
> What are the concrete advantages of the current static inline functions? Is it for performance, library size etc? How was it decided what functions should be static inline?

better generated code (see below) and fewer symbols (reduces loader time and thus executable startup time). it also makes the code available without needing actual library source--someone looking at the header alone can know how simple functions work. also, by being static inline, they're not part of the ABI, allowing more flexibility in many cases. i.e. if you remove an exported symbol, a program will likely stop linking; this doesn't happen if you remove a static inline.

> If there is some benchmark that shows that the advantage of these are not significant, would a PR to make them normal functions be accepted?

it would depend on the meaningfulness of the benchmark.

> Naively it feels like with LTO the compiler should see the definitions anyway and inline them where it makes sense according to its cost model.

AFAIK, this would require the GIMPLE for the library itself to be available. such artifacts are not installed by any package manager of which i'm aware. i.e. LTO requires whole-program information to be effective, and the only way you're getting that information to an external application is.....static inline header-based functions that the compiler can see.

**Comment by dankamongmen** [comment]
i honestly think the solution in #800 will work; i just got confused by some leftover build artifacts back in the day, and have had no reason to revisit the issue.

**Comment by KristofferC** [comment]
https://github.com/dankamongmen/notcurses/issues/800#issuecomment-678831293 being the money shot?

**Comment by dankamongmen** [comment]
> [#800 (comment)](https://github.com/dankamongmen/notcurses/issues/800#issuecomment-678831293) being the solution? I'll try it out then.

lol you can say "money shot" here; this is a safe space =]. ja, ja, ich bin Feuer und Flamme

**Comment by KristofferC** [comment]
🤫
