### ISSUE TITLE
Can you clarify the use of DFSG_BUILD?

### ISSUE THREAD

**Issue by lfam** [dankamongmen/notcurses#2508]
Reading `INSTALL.md`, I was left with a question about `DFSG_BUILD`. The text seems to imply that by turning this option `OFF`, the build will omit everything not allowed under the DFSG:

`DFSG_BUILD=off: leave out all content considered non-free under the Debian Free Software Guidelines`

Is that correct? Or should it be turned `ON` to omit this content that is not freely licensed?

https://github.com/dankamongmen/notcurses/blob/v3.0.2/INSTALL.md#build-options

**Comment by dankamongmen** [comment]
you're absolutely right, of course. thanks for the heads up!

**Comment by dankamongmen** [comment]
oh ok here's what's up; the `=off` indicates the default value. i'll try to make this more clear.

**Comment by lfam** [comment]
Okay, thanks! That's what I suspected, but I wasn't sure.

**Comment by dankamongmen** [comment]
hopefully my changes just now clear this up.

**Comment by lfam** [comment]
Yes, that clears it up completely. Thanks for your help!
