### ISSUE TITLE
Arch AUR package notcurses-git doesn't actually build latest git

### ISSUE THREAD

**Issue by dnkl** [dankamongmen/notcurses#2530]
The Arch AUR package, [notcurses-git](https://aur.archlinux.org/packages/notcurses-git/), doesn't actually build git HEAD (which is what `*-git` packages typically do). Instead, it builds a specific release (currently 3.0.3). This is what the non-git version of the package (in community) is supposed to do.

**Comment by dankamongmen** [comment]
yeah i know.

so up until about two months ago, i was maintaining the `notcurses` package, and the `notcurses-git` was maintained by another AUR user. i kept the former pretty rigorously up to date; the latter languished after 2.3.8 or so, but whatever, you could get the fresh release from `notcurses`.

well an arch TU then picked up `notcurses` to move it into `community` from the AUR. this was great, as it means notcurses now gets into various arch-derived projects. unfortunately, it is now not quite kept up to date, at least not as rapidly as it might in an ideal world. note for instance that it is currently at 3.0.0. i don't want to spam the TU with update requests, so there we are.

i then got co-main rights of `notcurses-git`, which i am keeping up to date with released versions.

agreed that this is probably quite counter to how it's supposed to run, and that i'm playing pretty fast and loose with AUR best practices.

**Comment by dnkl** [comment]
Hmm, I see. Well, I'd recommend renaming the package to something else... not quite sure to what, since you _are_ breaking best practices...

If you don't want to maintain a "real" notcurses-git package by yourself, perhaps someone else will pick it up (I might).

**Comment by dankamongmen** [comment]
yeah indeed.

ugh i really wish no one would. i release on a pretty frequent cadence, usually about once a week, and between those releases, `master` is not always as stable as it perhaps ought be... but may a hundred flowers bloom.

**Comment by dnkl** [comment]
Before I reported this bug I used a patched PKGBUILD (a combination of the "old" PKGBUILD, with my own patches). But after you reminded me that you do release very often, I've switched to the "real" PKGBUILD.

And it looks like it's been cleaned up a lot - none of my old patches are no longer needed. So, I can live without a "proper" `-git` package. If I really need to test something from master, I can you build from sources myself.

I still think you should rename the AUR package, but as far as I'm concerned, this bug can be closed.

**Comment by dankamongmen** [comment]
> But after you reminded me that you do release very often, I've switched to the "real" PKGBUILD.
> I still think you should rename the AUR package, but as far as I'm concerned, this bug can be closed.

so yeah, i took over `notcurses-git` and cleaned it up. so here's my philosophical question for you:

as (co-)maintainer of the `notcurses-git` AUR package, but also the upstream author, and also devoted to frequent releases, how is what i have different from an "ideal" `-git` package? essentially, i release whenever there's a decent collection of improvements, and the tree is AFAIK stable. i aim for about once a week. my releases, therefore, are *exactly the same git commits i would use to prepare a `-git` package", save that they are tags rather than the immediately preceding commit.

put another way: if every git commit led to a "release", would that project not have a valid `-git` package?

if you see a particular commit you feel i ought update the package for, feel free to poke me or send me a bug =].

**Comment by dnkl** [comment]
The name itself signals instability. A user who's familiar with Arch, the AUR and package name conventions, but who isn't familiar with your project, is likely to prefer the outdated community package over the AUR package.

(And don't forget that most users prefer community and core packages over AUR packages in general. If they think the AUR package is unstable they are even less likely to install it).

**Comment by dankamongmen** [comment]
agreed the optimal thing would be for the community maintainer to keep it up to date, in which case i wouldn't be messing with this package at all.
