### ISSUE TITLE
query response leak in iTerm2?

### ISSUE THREAD

**Issue by michaelsbradleyjr** [dankamongmen/notcurses#2531]
See the screenshot below. You'll want to open it in a separate window and zoom to 200% so the terminal output is legible.

That sequence of inputs is received by `notcurses_get_blocking` as soon as the program starts, i.e. I haven't pressed any keys. It happens every time.

The program is my same `cli1` referenced in #2524, with some updates following that discussion.

However, what I'm seeing I've been seeing in my `cli1` in iTerm2 since I started work on it; but I spend a lot more time in Kitty these days, so I just now thought to check in iTerm2 again and report the issue.

I am not versed in the details of Notcurses queries but I've read or skimmed enough issues and PRs in this repo that I have a sense that a leaked response is what I'm looking at.

Or, maybe this is fully expected given the way in which `cli1` makes use of `notcurses_get_blocking`?
![image](https://user-images.githubusercontent.com/194260/148293607-0ecb1db9-fc10-4882-afa2-dec24f1b7ca6.png)

**Comment by dankamongmen** [comment]
nahj this is definitely query stuff bleeding through. i imagine the same thing happens running `notcurses-input`?

**Comment by dankamongmen** [comment]
any love on getting my cobra account back up btw? =]

**Comment by dankamongmen** [comment]
so this isn't bleedthrough, actually, but rather an XTSMGRAPHICS error message.

i'm seeing here `\e[?1;3;S`. that's not quite what's specified, but we can handle it. one moment please.

**Comment by michaelsbradleyjr** [comment]
> nahj this is definitely query stuff bleeding through. i imagine the same thing happens running `notcurses-input`?

Indeed.
![image](https://user-images.githubusercontent.com/194260/148308767-db5e6ebb-093c-4a58-98af-af28a45a0da4.png)

**Comment by dankamongmen** [comment]
if you could, please update from `master` and see what matter of thing we might have here. you want commit 5de0a24fe.

**Comment by dankamongmen** [comment]
i *think* that'll get it, based on what i'm seeing here. probably ought file a bug against iTerm2 for its out-of-spec response.

**Comment by michaelsbradleyjr** [comment]
> any love on getting my cobra account back up btw? =]

Whoops, forgot to do that.

However, the way the remote desktop works, as far as when I tested it, it's not per user, and I'm logged into cobra-la's desktop locally pretty much 24/7 (I needed to start working with a large monitor that my laptop wasn't driving effectively). So your account would be limited to ssh access, and I'm not sure how much use that will be. Were you at any point able to try latest iTerm2 stable/beta on that older mac laptop you have, and did it work? I think iTerm2 only supports macOS 10.14+.

**Comment by dankamongmen** [comment]
> However, the way the remote desktop works, as far as when I tested it, it's not per user, and I'm logged into cobra-la's desktop locally pretty much 24/7 (I needed to start working with a large monitor that my laptop wasn't driving effectively). So your account would be limited to ssh access, and I'm not sure how much use that will be. Were you at any point able to try latest iTerm2 stable/beta on that older mac laptop you have, and did it work? I think iTerm2 only supports macOS 10.14+.

i'm gonna sound pretty bougie here but i gave it away to my maid lol

**Comment by michaelsbradleyjr** [comment]
> I needed to start working with a large monitor that my laptop wasn't driving effectively

Sorry for the inconvenience, btw.

> I think iTerm2 only supports macOS 10.14+

And... yes, that's the case, which means that my older mac laptop isn't an option either, as it's stuck permanently on 10.13. 😦

**Comment by dankamongmen** [comment]
all good. did that commit get it?

**Comment by michaelsbradleyjr** [comment]
Seems to have fixed it, nice work!

![image](https://user-images.githubusercontent.com/194260/148309891-ebdfe31a-7e51-49a3-b254-824d87f10014.png)

![image](https://user-images.githubusercontent.com/194260/148310295-828c55ee-7b5f-4d2a-a755-32ee37bd4ebf.png)

**Comment by dankamongmen** [comment]
yay!
