### ISSUE TITLE
banners overlap last character

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#2538]
In case this is a bug.

I noticed in the example [hello-world-c.rs](https://github.com/dankamongmen/libnotcurses-sys/blob/main/examples/hello-world-c.rs) and others how, when showing banners, the first character of the banner overlaps the last character of the output. Tested in several terminals:

- output when using `NCOPTION_CLI_MODE | NCOPTION_SUPPRESS_BANNERS`:
```
hello world
```
- output of putstr when using just `NCOPTION_CLI_MODE`:
```
(...)
50 rows (20px) 94 cols (10px) 1000x940 rgb+256 colors
gcc-9.3.0 (LE)
terminfo 6.2.20200212 libdeflate 1.5 GPM n/a
avformat 58.29.100 avutil 56.31.100 swscale 5.5.100 avcodec 58.54.100
hello worl1 render, 188,79µs (188,79µs min, 188,79µs avg, 188,79µs max)
1 raster, 59,02µs (59,02µs min, 59,02µs avg, 59,02µs max)
1 write, 40,21µs (40,21µs min, 40,21µs avg, 40,21µs max)
19B (19B min, 19B avg, 19B max) 0 inputs Ghpa: 0
0 failed renders, 0 failed rasters, 0 refreshes, 0 input errors
RGB emits:elides: def 1:10 fg 0:0 bg 0:0
Cell emits:elides: 11:9389 (99,88%) 90,91% 0,00% 0,00%
Bitmap emits:elides: 0:0 (0,00%) 0B (0,00%) SuM: 0 (0,00%)
```

**Comment by dankamongmen** [comment]
probably an instance of #2414 but let me look into it right quick, thanks!

**Comment by dankamongmen** [comment]
so this definitely doesn't seem wholly general, see `cli1` for instance. that's working fine for me.

wait, are you not emitting a newline? you need `putstr("hello world\n")`. that's your problem.
