### ISSUE TITLE
consider tossing out an XTPUSHSGR/XTPOPSGR combo

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2559]
SI # }   Pop video attributes from stack (XTPOPSGR), xterm.  Popping
          restores the video-attributes which were saved using XTPUSHSGR
          to their previous state.

CSI # {
CSI Pm # {
          Push video attributes onto stack (XTPUSHSGR), xterm.  The
          optional parameters correspond to the SGR encoding for video
          attributes, except for colors (which do not have a unique SGR
          code):
            Ps = 1  ⇒  Bold.
            Ps = 2  ⇒  Faint.
            Ps = 3  ⇒  Italicized.
            Ps = 4  ⇒  Underlined.
            Ps = 5  ⇒  Blink.
            Ps = 7  ⇒  Inverse.
            Ps = 8  ⇒  Invisible.
            Ps = 9  ⇒  Crossed-out characters.
            Ps = 2 1  ⇒  Doubly-underlined.
            Ps = 3 0  ⇒  Foreground color.
            Ps = 3 1  ⇒  Background color.

          If no parameters are given, all of the video attributes are
          saved.  The stack is limited to 10 levels.

maybe we ought toss out a PUSH on startup / reentry, and a POP contrariwise?

**Comment by dankamongmen** [comment]
figure out how this is different from DECSC/DECRC, described in `console_codes(4)` thusly:

```
       ESC 7     DECSC    Save   current   state  (cursor  coordinates,  at‐
                          tributes, character sets pointed at by G0, G1).
       ESC 8     DECRC    Restore state most recently saved by ESC 7.
```

**Comment by j4james** [comment]
Other than the differences in what they store, DECSC/DECRC only stores a single instance of the state, while XTPUSHSGR/XTPOPSGR will keep a stack of values. I think hardly anyone supports the XTPUSHSGR/XTPOPSGR operations.

**Comment by dankamongmen** [comment]
so it sounds like the best thing to do might be either:

* send a DECSC followed by an XTPUSHSGR for preserve, and XTPOPSGR and DECRC for restore, or
* track explicitly those terminals supporting XTPUSHSGR, and send only that rather than DECSC when identified

the problem with the latter of course being that we'd like to send these on startup, before we know the terminal. that's probably not necessary, though -- they don't have a reply we need to wait for, so sending them with our initial real output (rather than with our queries) ought not be a problem.

if we do use either of these, we don't want to reset the SGR in `notcurses_stop_minimal()` anymore. if they're not supported, though, we do. so we'd need know which terminals supported them in any case.

actually, if these are preserving the cursor *position*, they're probably both unsuitable for us, as we want to control the cursor position on exit (we don't want it placed back at the beginning of our output). we could of course update the cursor position following emission, though that likely results in a weird, visible cursor move at the end.

given that DECSC/DECRC don't have a stack, we'd be blowing away any previous use thereof. it would only work if they used DECSC immediately before calling us, and we then use it at the very beginning (in which case we'd expect the same state to be saved both times).

i'm thinking that maybe DECSC/DECRC are better for the *calling* program. that program knows whether it needs these data preserved, whereas we don't. that program knows whether they've used DECSC, whereas we don't. furthermore, if we used them, and then any program we *called* used them, we'd be screwed. better to keep such information in our own memory, methinks.

so, after some consideration, i'm closing this as NONFIX. if anyone feels differently, reopen it and let me know why.
