### ISSUE TITLE
palette queries bleed through on at least linux console and st < 0.8.5

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#2561]
Sending all our palette queries results in a great deal of initial bleedthrough in both the Linux console and `st`. The former is to be expected, as there is no support for querying the Linux console palette (as far as I'm aware). A bit surprised by `st`.

Work around these issues.

Also, it appears that OSC4 can be used in a more compact form. See if we can cut down on the ~3KB of palette queries we send at the moment.

**Comment by j4james** [comment]
FYI, if you're planning on using the `#rrggbb` color format instead of `rgb:rr/gg/bb`, I think that's well supported - even better than the `rgb:` format actually. If you're planning on combining multiple palette entries into a single OSC operation, though, that's less likely to work.

**Comment by dankamongmen** [comment]
> FYI, if you're planning on using the `#rrggbb` color format instead of `rgb:rr/gg/bb`, I think that's well supported - even better than the `rgb:` format actually. If you're planning on combining multiple palette entries into a single OSC operation, though, that's less likely to work.

do you mean to set them? i set them using whatever terminfo gives me as `initc`.

for the query, i'm sending `\e]4;N;?\e\\` for N colors, so i'm not sure where those formats would come into play (at least from my control). ahhh, ok, so i could override `initc` i think is what you're saying to use this `#rrggbb` format? hrmmmm i don't generally gratuitously override terminfo, but i would need to to do combined OSC sets...

anyway, this issue is about palette acquisition =].

**Comment by j4james** [comment]
Doh! I misread the issue. I thought this was about setting the palette. For querying, though, my second point still applies.

When you said "it appears that OSC4 can be used in a more compact form", I figured you wanted to do something like `\e]4;0;?;1;?;2;?\e\\` to query a bunch of values at the same time. Not all terminals support that.

**Comment by dankamongmen** [comment]
> Doh! I misread the issue. I thought this was about setting the palette. For querying, though, my second point still applies.
> 
> When you said "it appears that OSC4 can be used in a more compact form", I figured you wanted to do something like `\e]4;0;?;1;?;2;?\e\\` to query a bunch of values at the same time. Not all terminals support that.

yep, this is what i wanted to investigate. if it's not broadly supported (relative to the set of terminals supporting OSC4 at all), it's probably not worth it.

**Comment by j4james** [comment]
The ones I'm aware of that do support it include XTerm, VTE, MLTerm, WezTerm, and Kitty. Rxvt and Contour sort of work, but get the format wrong, so might need some special casing (although I think you already raised an issue with Contour on this topic, so maybe that's already fixed). The tricky ones are Yaft and Mintty, which work with a single query, but not multiple colors at the same time (Mintty is a bit weird, though - sometimes it works, sometimes it doesn't). And then there's Tera Term, which looks like it works, but gets the index numbers muddled - it might be OK if you're just saving and restoring.

> relative to the set of terminals supporting OSC4 at all

Yeah, once you eliminate the ones that don't support queries at all, it's actually not as bad as I originally thought. And this is based on testing I did a while back, though, so some of the buggy ones may already be fixed. Hopefully this at least gives you an idea of the ones to watch out for.

**Comment by dankamongmen** [comment]
for `st`, the current git master works properly (well, our output starts a few rows below where i'd expect, but we don't get the flurry of `erresc: invalid color j=242, p=?`). maybe debian is behind?

**Comment by dankamongmen** [comment]
yeah the debian code (0.8.4) is totally different and has an obvious bug

**Comment by dankamongmen** [comment]
huh 0.8.5 was only released about two weeks ago `st 0.8.5 (48kb) (2022-01-07)`

**Comment by dankamongmen** [comment]
alright, bug filed on debian to update (Bug#1004100). i don't see what else we can do there.

if my OSC10/11 linux kernel patch gets accepted (https://lkml.org/lkml/2022/1/14/413), i'm going to go ahead and implement OSC4 query responses in the VT console. that'll resolve things for linux. ideally we'd only send queries up through the supported number of colors (linux is never going to respond to more than 16), but then we'd need delay that query until we'd already loaded up terminfo etc. i'd thus like to avoid it if at all possible.

i *have* changed things to send the queries in bursts of 0-7, 8-16, 17-88, and 89-256. if we move to multiquery, i'd like to keep it bunched like that, so we don't have unsupported ones in the same query as supported ones. then again, given @j4james 's report above, i don't really see us moving to multiquery, for the same reason as above -- we launch our queries before we know what terminal we're talking to. this is done both to hide the response latency, and because we prefer terminal self-attestation to user-managed `TERM` variables.

**Comment by dankamongmen** [comment]
so we *do* know when we're on a linux vt ahead of time -- i think until i implement OSC 4 in the linux kernel, we ought inhibit palette queries there. st people can just upgrade; that functionality is available now in 0.8.5.

**Comment by dankamongmen** [comment]
ok, we're no longer sending OSC4 on Linux VTs.
