### ISSUE TITLE
*{_set}?_[fb]channel() and *{_set}?_channel() ought only operate on alpha+color bits

### ISSUE THREAD

**Issue by hkatzdev** [dankamongmen/notcurses#2571]
It seems like the man pages and usage guide have gotten a bit out of sync with notcurses developments, especially relating to cells and channels.

When I was trying to use `nccell_fchannel()`, I got `warning: implicit declaration of function ‘nccell_fchannel’; did you mean ‘ncplane_fchannel’? [-Wimplicit-function-declaration]`.

While both the usage guide and man pages list `nccell_fchannel()`, it appears to not be defined. Looking through some commits and news, it appears that `cell_fchannel()` (along with `cell_bchannel()`, `cell_set_fchannel()`, and `cell_set_bchannel()`) were removed from the public API in version 2.2.3 .

However, commit [#100a892](https://github.com/dankamongmen/notcurses/commit/100a892) seems to remove some `channels_` functions rather than `cell_` functions from the man pages. To this day it seems like those four ncchannel functions are not mentioned anywhere. I am not sure if this was intentional and they are no longer part of the public API or an accident.

Additionally, `ncchannels_bchannel` and `channels_bchannel` seem to be used interchangeably in the usage guide. As a sidenote, it seems like [some python bindings](https://github.com/dankamongmen/notcurses/blob/c20e859a6d75811a3d9c77e75d7520df66357e65/cffi/src/notcurses/notcurses.py) use `channels_` instead of `ncchannels_`.

**Comment by dankamongmen** [comment]
fwiw, the man pages are considered the authoritative reference. `USAGE.md` is something i started on early, and have only kept up to date when i remembered to.

an audit of `USAGE.md` is probably due, but will take some time, and isn't high up on my list of goals. corrective patches to it would be very much welcome.

**Comment by dankamongmen** [comment]
i'm actually thinking killing off `USAGE.md` might be the way to go here, so if you find it valuable, patching it up might be the thing to do.

**Comment by hkatzdev** [comment]
> fwiw, the man pages are considered the authoritative reference. `USAGE.md` is something i started on early, and have only kept up to date when i remembered to.
> 
> an audit of `USAGE.md` is probably due, but will take some time, and isn't high up on my list of goals. corrective patches to it would be very much welcome.

The same issue is also present in the man pages - sorry if I wasn't clear on that. The man pages say that `nccell_fchannel` and some similar functions exist while they do not, and `ncchannels_fchannel` / related functions are never mentioned despite seemingly part of the API. Since I the man pages were changed this way back in v2.2.3, so I don't know the current status.

> i'm actually thinking killing off `USAGE.md` might be the way to go here, so if you find it valuable, patching it up might be the thing to do.

While the usage guide has really helped me start to learn notcurses, I understand. I would offer to help patch it to make it current but I am still using notcurses and I don't know the API myself. If the man pages are updated I might be able to help fix the usage guide based off that though.

**Comment by dankamongmen** [comment]
oh! ok i'll definitely fix it then, thanks =] 

perhaps the thing to do is to take whatever good text lives in `USAGE.md` and move it into the man pages, then kill off `USAGE.md` as a reference, and then work on the long-heralded guide in #785. but this business of having to touch four places every time i change a function has got to end.

**Comment by dankamongmen** [comment]
this also makes me wonder: why do we still have `ncplane_set_[fb]channel()`? are those safe?

**Comment by dankamongmen** [comment]
or for that matter `ncchannels_set_[fb]channel()?`

**Comment by dankamongmen** [comment]
i'm thinking we might be wise to remove all forms of `*_set_[fb]channel()`. users ought not be messing around with some of those bits.

**Comment by dankamongmen** [comment]
pretty much every use i see of `ncchannels_set_fchannel()` would be better-served with `ncchannels_set_rgb()`. yeah, i think they've gotta go. probably can kill off the accessors along with them.

**Comment by dankamongmen** [comment]
what about `ncplane_channels()` and `ncplane_set_channels()`? surely they're even more unsafe?

**Comment by dankamongmen** [comment]
if we do that, let's add `ncplane_set_rgb()` and `ncchanels_set_rgb()`, to make up for the loss and restore the ability to copy two rgb values from one channel to another.

ooooh, that doesn't work for default/palette, though. and in fact, neither is `ncchannels_set_fchannel()` cleanly replaced by `ncchannels_set_rgb()`. we need an `ncchannels_set_color()` that copies over the not-default bit, the palette bit, and the 24 rgb bits.

ooh but also alpha. so `ncchannels_set_style()`? takes as input one `uint32_t* a` and one `uint32_t b`, and copies over the 26 color and 2 alpha bits from `b` to `a`.

ok, crazy idea: what if we just changed `ncplane_set_fchannel()` and `ncchannels_set_fchannel()` to do this rather than a wholesale copy? then we don't break API/ABI =]. hell, we could even add back `nccell_{set_}?[fb]channel()`. they'd be slightly misnamed, but is that the biggest problem in the world?

**Comment by dankamongmen** [comment]
yesssssssssssssss i think this is what we ought do

**Comment by dankamongmen** [comment]
yes, we're already sensibly doing this for `ncchannels_reverse()`, it appears.

**Comment by dankamongmen** [comment]
updated the comments on `ncchannels_bchannel()` and `ncchannels_fchannel()`. need to update implementation of `ncchannels_bchannel()`...

**Comment by dankamongmen** [comment]
ok, just changing `ncchannels_bchannel()` like that breaks the world due to rampant use within `notcurses.h`, need back that out, erp!

**Comment by dankamongmen** [comment]
oh wait maybe it does work once i change up `ncchannels_set_bchannel()` and `ncchannels_set_fchannel()`?

**Comment by dankamongmen** [comment]
oh yay i think maybe it does, hurrah

**Comment by dankamongmen** [comment]
alright, so do we have everything we need here now? probably need to update docs to restore `nccell_set_[fb]channel()`?

**Comment by dankamongmen** [comment]
ok, i've reintroduced `nccell_channels()` and `nccell_set_channels()`, using new functions `ncchannels_channels()` and `ncchannels_set_channels()`. i've documented these latter. i've rewritten `ncplane_channels()` and `ncplane_set_channels()` using these safe functions. i think that addresses everything concrete in this report. thanks for bringing it to my attention!
