### ISSUE TITLE
ncplane_puttext(..., NCALIGN_UNALIGNED, ...) produces no output

### ISSUE THREAD

**Issue by alexhsamuel** [dankamongmen/notcurses#2611]
Return value indicates it consumed the string, but no output appears.  With other NCALIGN_* it works.

Demo:
```c
#include <assert.h>
#include <locale.h>
#include <notcurses/notcurses.h>
#include <unistd.h>

int main() {
  setlocale(LC_ALL, "");

  notcurses_options ncopts;
  memset(&ncopts, 0, sizeof(ncopts));
  struct notcurses* nc = notcurses_init(&ncopts, stdout);

  struct ncplane* const plane = notcurses_stdplane(nc);
  int const nbytes = ncplane_puttext(plane, -1, NCALIGN_UNALIGNED, "Hello, world!", NULL);
  assert(nbytes == 13);

  notcurses_render(nc);
  sleep(3);

  notcurses_stop(nc);
  return EXIT_SUCCESS;
}
```

This appears to be because `notcurses_align` has no case for `NCALIGN_UNALIGNED` so returns `-INT_MAX,` and `ncplane_putline` doesn't check the result for error.

**Comment by dankamongmen** [comment]
will look into this tonight ideally.

appreciate the test code; feel free/encouraged to add such things as unit tests! `src/tests`

**Comment by alexhsamuel** [comment]
> feel free/encouraged to add such things as unit tests! src/tests

Is there a way to inspect whether any text has actually been rendered?  Without this, it's not worth too much as a test.  I guess I can check the cells in the plane, but even better to be able to peek at the rendered framebuffer, to to speak.

**Comment by dankamongmen** [comment]
> > feel free/encouraged to add such things as unit tests! src/tests
> 
> Is there a way to inspect whether any text has actually been rendered? Without this, it's not worth too much as a test. I guess I can check the cells in the plane, but even better to be able to peek at the rendered framebuffer, so to speak.

yeah, there are two levels of doing so (there are lots of examples in e.g. `output.cpp` and `planes.cpp`):

* after writing to the plane, you can check plane contents with `ncplane_at_yx()`
* after rendering, you can check virtual screen contents with `notcurses_at_yx()`

**Comment by dankamongmen** [comment]
> > > feel free/encouraged to add such things as unit tests! src/tests
> > 
> > 
> > Is there a way to inspect whether any text has actually been rendered? Without this, it's not worth too much as a test. I guess I can check the cells in the plane, but even better to be able to peek at the rendered framebuffer, so to speak.
> 
> yeah, there are two levels of doing so (there are lots of examples in e.g. `output.cpp` and `planes.cpp`):
> 
> * after writing to the plane, you can check plane contents with `ncplane_at_yx()`
> * after rendering, you can check virtual screen contents with `notcurses_at_yx()`

you can also do a large-scale check with `ncplane_contents()`, and a large-scale check of what was rendered with `ncpile_render_to_buffer()`. i haven't found much need for these in the testing code, though.

a good example might be `AlignRightFull`:

```cpp
  // we ought be able to fill up the plane using any alignment, even if we                                                          
  // spill over                                                                                                                     
  SUBCASE("AlignRightFull") {                                                                                                       
    struct ncplane_options nopts{};                                                                                                 
    nopts.rows = 1;                                                                                                                 
    nopts.cols = 10;                                                                                                                
    auto n = ncplane_create(n_, &nopts);                                                                                            
    REQUIRE(n);                                                                                                                     
    CHECK(-10 == ncplane_putstr_aligned(n, 0, NCALIGN_RIGHT, "0123456789L"));                                                       
    CHECK(0 == notcurses_render(nc_));                                                                                              
    for(unsigned x = 0 ; x < ncplane_dim_x(n) ; ++x){                                                                               
      auto egc = notcurses_at_yx(nc_, 0, x, nullptr, nullptr);                                                                      
      char expected[2] = {0};                                                                                                       
      REQUIRE(egc);                                                                                                                 
      expected[0] = x + '0';                                                                                                        
      CHECK(0 == strcmp(egc, expected));                                                                                            
      free(egc);                                                                                                                    
    }                                                                                                                               
    CHECK(0 == ncplane_destroy(n));                                                                                                 
  }                 
```

**Comment by dankamongmen** [comment]
hrmmm we're coming out with our cursor at 0,0, despite emitting 13 characters.

`avail: 79 off: -2147483647` there's our problem

**Comment by dankamongmen** [comment]
so `notcurses_align()` is returning -1 there; i think we ought only be calling it if `align != NCALIGN_UNALIGNED`?

**Comment by dankamongmen** [comment]
yep that fixes it. thanks much for the good find!

**Comment by dankamongmen** [comment]
should be fixed in master. let's see if your test now passes!
