### ISSUE TITLE
`ncprogbar_options` is different in implementation and in docs

### ISSUE THREAD

**Issue by OBenjaminT** [dankamongmen/notcurses#2639]
I have no context but this is confusing and seems wrong.

# Documentation

Claims it's made of three `uint64_t`.

`USAGE.md`
```h
typedef struct ncprogbar_options {
  // channels for the maximum and minimum points. linear interpolation will be
  // applied across the domain between these two.
  uint64_t maxchannels;
  uint64_t minchannels;
  uint64_t flags;
} ncprogbar_options;
```

`doc/man/man3/notcurses_progbar.3.md`
```h
typedef struct ncprogbar_options {
  uint64_t maxchannels;
  uint64_t minchannels;
  uint64_t flags;
} ncprogbar_options;
```

# Implementation

Assumes it's actually four `uint32_t` and one `uint64_t`

`include/notcurses/notcurses.h`
```h
typedef struct ncprogbar_options {
  uint32_t ulchannel; // upper-left channel. in the context of a progress bar,
  uint32_t urchannel; // "up" is the direction we are progressing towards, and
  uint32_t blchannel; // "bottom" is the direction of origin. for monochromatic
  uint32_t brchannel; // bar, all four channels ought be the same.
  uint64_t flags;
} ncprogbar_options;
```

`src/lib/progbar.c`
```c
ret->ulchannel = opts->ulchannel;
ret->urchannel = opts->urchannel;
ret->blchannel = opts->blchannel;
ret->brchannel = opts->brchannel;
ret->retrograde = opts->flags & NCPROGBAR_OPTION_RETROGRADE;
```

**Comment by dankamongmen** [comment]
love love love this close reading you're doing of the docs vis-a-vis the implementation! i should be able to get to this and your other one this evening, hopefully. thanks so much!

**Comment by OBenjaminT** [comment]
I'm just reporting what I stumble across.

There's no real rush, I'm working on `v3.0.7` and not master, and this isn't a coding bug that breaks stuff anyway.

I do love the responsiveness though! Definitely encouraging me to keep going and trust the project's progress.

**Comment by dankamongmen** [comment]
Updated!
