### ISSUE TITLE
Will this work on a headless FreeBSD 13.1 environment?

### ISSUE THREAD

**Issue by rajhlinux** [dankamongmen/notcurses#2656]
I have a desktop PC with a graphics card which is capable of displaying quad 4K monitors.

The thing is that I use this desktop PC as a headless environment using FreeBSD 13.1

Can notcurses be used for my situation?

Thanks.

**Comment by dankamongmen** [comment]
Yes, there ought be no problem, so long as `TERM` is defined.

What exactly it ought be defined as in a headless environment is questionable; for unit testing, we usually define `TERM=xterm`. Whatever you use, you'll need to have the proper libterminfo terminal definition installed.

I regularly build on FreeBSD, and we're in the Ports collection.

Thanks for your interest in Notcurses!
