### ISSUE TITLE
Probably a misguided

### ISSUE THREAD

**Issue by crisdosyago** [dankamongmen/notcurses#2678]
Hi this is probably just a stupid drunk idea from me but I was thinking doesn't seem like there's a JavaScript binding for this should I make one?

I think this is probably a long ugly difficult rabbit hole of impossible problems so I probably shouldn't do it but maybe should i? Try maybe 🤔🤷‍♂️😬

**Comment by dankamongmen** [comment]
you're more than welcome to attempt to do so. you might want to test with xterm.js, but i'm woefully ignorant regarding javascript and its environs. don't hesitate to reach out for help!

**Comment by crisdosyago** [comment]
Thanks, @dankamongmen I won't do this. It was a silly idea I had last night.
