### ISSUE TITLE
Higher level abstractions

### ISSUE THREAD

**Issue by ankitkk** [dankamongmen/notcurses#2680]
I was looking for "user" facing code for building TUIs specifically scientific plotting based on notcurses, but couldn't find anything. For example a high quality terminal backend for Imgui/Implot would be amazing. My question is if a notcurses backend for IMGUI/IMPLOT is even possible using notcurses? (there's an exiting ImTui backend, but that's not sufficient). Do you have any suggestions?

**Comment by dankamongmen** [comment]
i'm not intimately familiar with IMGUI/IMPLOT, but a quick look suggests it's just a canvas backend. such a thing is easily mapped to notcurses using the generic image backends. there are also specific plot ui widgets that will probably work better, if they conform to your needs.
