### ISSUE TITLE
C++ usage, documentation, and examples question

### ISSUE THREAD

**Issue by gunqqer** [dankamongmen/notcurses#2701]
I am looking to use notcurses' C++ implementation. I am looking for this implementation's documentation, but cannot find anything anywhere. If there is any docs having them in a more front and center place would be a good idea. On the same token, having a very basic usage of this lib as an example would be nice (if it exists please link it).
Finally I'm trying to compile a hello world on Ubuntu and think I am linking the library wrong, are there any examples of a cmake file for how to compile a program using the c++ implementation?

**Comment by dankamongmen** [comment]
there is no documentation on the c++ wrappers of which i am aware, sorry =[

the best example i know of would be `play.cpp` from `src/player` and the `tetris` source.

the primary top-level CMake builds those cpp tools, and is probably the best example.

sorry i can't help you more! patches welcome =].
