### ISSUE TITLE
Nim wrapper for Notcurses

### ISSUE THREAD

**Issue by dfsxn** [dankamongmen/notcurses#2708]
Hi,

I have been noticed that there's available a Nim wrapper for Notcurses:

https://github.com/michaelsbradleyjr/nim-notcurses

It can be also installed through Nimble (package manager for the Nim programming language): https://nimble.directory/pkg/notcurses

Could be added to https://github.com/dankamongmen/notcurses#wrappers?

Thank you.

Kind regards,

**Comment by michaelsbradleyjr** [comment]
No problems with it. But note, for awhile now (whenever I've had bits of time including tonight), I've been working on a total refactor of the wrapper on the [`version_3_revamp`](https://github.com/michaelsbradleyjr/nim-notcurses/tree/version_3_revamp) of my repo.

So, as the [README.md](https://github.com/michaelsbradleyjr/nim-notcurses/tree/version_3_revamp#readme) indicates on that branch, you'd want to have:
```nimble
requires "notcurses#version_3_revamp"
```
in a dependent project's `.nimble` file.

With a few more big pushes I should have all (or almost all) of Notcurse's C API wrapped per the low-level wrapper. The high-level wrapper, porting more of the examples, adapting the docs to Nim's DocGen ... those things will take a bit longer, but they're on my roadmap for nim-notcurses.
