### ISSUE TITLE
Duplicate declarations for notcurses_stdplane/_const?

### ISSUE THREAD

**Issue by michaelsbradleyjr** [dankamongmen/notcurses#2710]
Should one pair of these declarations be removed in favor of the other, or do they serve different purposes?

[L1108-L1114](https://github.com/dankamongmen/notcurses/blob/master/include/notcurses/notcurses.h#L1108-L1114)
```c
// Get a reference to the standard plane (one matching our current idea of the
// terminal size) for this terminal. The standard plane always exists, and its
// origin is always at the uppermost, leftmost cell of the terminal.
API struct ncplane* notcurses_stdplane(struct notcurses* nc)
  __attribute__ ((nonnull (1)));
API const struct ncplane* notcurses_stdplane_const(const struct notcurses* nc)
  __attribute__ ((nonnull (1)));
```
[L1388-L1392](https://github.com/dankamongmen/notcurses/blob/master/include/notcurses/notcurses.h#L1388-L1392)
```c
// Get a reference to the standard plane (one matching our current idea of the
// terminal size) for this terminal. The standard plane always exists, and its
// origin is always at the uppermost, leftmost cell of the terminal.
API struct ncplane* notcurses_stdplane(struct notcurses* nc);
API const struct ncplane* notcurses_stdplane_const(const struct notcurses* nc);
```

**Comment by dankamongmen** [comment]
one is the `const` variant, one is not `const`. if you have a `const` handle on the `notcurses` object, you can only use the `const` forms. they're provided so that you can use `const notcurses` more easily.

**Comment by michaelsbradleyjr** [comment]
Right, but there are two different pairs of const and not const. One pair uses `__attribute__ ((nonnull (1)))` the other does not.

**Comment by dankamongmen** [comment]
oh! so there is

**Comment by dankamongmen** [comment]
thanks, resolved!
