### ISSUE TITLE
F3 is not decoded properly in kitty

### ISSUE THREAD

**Issue by neurocyte** [dankamongmen/notcurses#2720]
Please include the following data:
* `export | egrep 'LANG|LC_CTYPE|TERM'`
```
COLORTERM truecolor
GDM_LANG en_US.UTF-8
LANG en_US.UTF-8
TERM xterm-kitty
TERMINAL kitty
```
* notcurses version (available from `notcurses-demo i`)
```
notcurses 3.0.9 on Kitty 0.28.1 (Linux 6.4.3-1-MANJARO)
57 rows (24px) 189 cols (9px) 1368x1701 rgb+256 colors
gcc-12.2.1 20230211 (LE)
terminfo 6.4.20230520 libdeflate 1.18 GPM 2.1.0
```
* terminal name + version
`kitty 0.28.1 created by Kovid Goyal`

When running in kitty the F3 key gets passed through to my application as a raw escape sequence instead of an F3 key event. The same thing happens in notcurses-input which you can see in this screenshot:
![image](https://github.com/dankamongmen/notcurses/assets/1552770/56512af3-6824-4d18-ba2c-831c28aa54b5)

This seems to be kitty specific. None of the other terminals I have tested seem to show this F3 specific decoding problem.

**Comment by dankamongmen** [comment]
taking a look at this, approximately eighteen months later. great find! so the only terminals i know of which use the kitty keyboard protocol are wezterm and foot, iirc. also ghostty i believe. so other terminals besides those are using classic F3.

**Comment by dankamongmen** [comment]
but wezterm sends F3 just fine...

**Comment by dankamongmen** [comment]
oh it's also used in iTerm2 and alacritty now, apparently. good on kovid!

**Comment by dankamongmen** [comment]
https://sw.kovidgoyal.net/kitty/keyboard-protocol/ does indeed spec `13 ~`, which is what we're seeing, so this is a bug on our side. there's nothing to work around here. let me look at your PR...

**Comment by dankamongmen** [comment]
ok, your PR looks great, except it has some big chunks that i don't think you intended to include. if you see this, you can update it, or i'll pull it into a branch and remove those elements. but we'll merge this today. thanks for your contribution to notcurses!
