### ISSUE TITLE
How do I set one of the lines of text to be highlighted?

### ISSUE THREAD

**Issue by SiyerBOBO** [dankamongmen/notcurses#2722]
In a multi line text printing task, should I highlight a particular line? (I am trying to customize a radio and need to highlight one of the rows, but I couldn't find a suitable method, which is very painful)

**Comment by dankamongmen** [comment]
can you show me some sample code so i understand better what you're trying to do?

**Comment by SiyerBOBO** [comment]
emmmm，我了解您的项目中包含单选以及多选，但是恕我直言，布局方式实在是太难以令人接受了（选项与描述实现了奇怪的中轴线居中方式），很庆幸的是昨天我已经找到了办法，使用 ncplane_stain 方法最终可以实现如下效果。
![2023-08-03_09-15-26](https://github.com/dankamongmen/notcurses/assets/47243555/c055f2d2-ebe7-4bb0-8f01-a39d78182394)
