### ISSUE TITLE
How can I hide the log printing at the end of the program?

### ISSUE THREAD

**Issue by SiyerBOBO** [dankamongmen/notcurses#2730]
![image](https://github.com/dankamongmen/notcurses/assets/47243555/f4b18484-fa49-4c88-bf19-57e8eadd89ce)
![image](https://github.com/dankamongmen/notcurses/assets/47243555/eee35cec-9a9f-408d-a9fe-e83d6300627f)

As shown in the figure, I have already done this, but I still have printing and have not found a solution to the problem in the API.

**Comment by dankamongmen** [comment]
```
// Notcurses typically prints version info in notcurses_init() and performance                                                      
// info in notcurses_stop(). This inhibits that output.                                                                             
#define NCOPTION_SUPPRESS_BANNERS    0x0020ull    
```

using this with `notcurses_init()` ought eliminate the trailing banner.

**Comment by SiyerBOBO** [comment]
Thank you very much for your help in our project.

**Comment by dankamongmen** [comment]
of course! did that work for you?

**Comment by dankamongmen** [comment]
btw i'll get to the other issues you filed last week as soon as i can =]
