### ISSUE TITLE
C++ wrapper: Plane::set_bg_rgb8 has a typo

### ISSUE THREAD

**Issue by zhiayang** [dankamongmen/notcurses#2748]
notcurses 3.0.9.

this should be setting bg: https://github.com/dankamongmen/notcurses/blob/d0ae40415228871c68fc9cebe6a7f9ef0f476082/include/ncpp/Plane.hh#L904

but it seems like the c++ bindings haven't been updated in 2 years?

**Comment by dankamongmen** [comment]
well, they are only wrappers -- they shouldn't need changing unless there's an API change.

and you're absolutely right. thanks!

**Comment by dankamongmen** [comment]
I believe this to have been fixed in 051a1b8bb.
