### ISSUE TITLE
USAGE.md references non-existing constant `NC_FG_ALPHA_MASK`

### ISSUE THREAD

**Issue by mulle-nat** [dankamongmen/notcurses#2757]
[here](https://github.com/dankamongmen/notcurses/blob/051a1b8bbd3f299137bb40d869daf6c9dd8ea037/USAGE.md?plain=1#L3196)

**Comment by dankamongmen** [comment]
indeed!

**Comment by dankamongmen** [comment]
i've updated USAGE.md with the current `ncchannels_reverse()` definition, thanks!
