### ISSUE TITLE
[question]: abandoned notcurses matrix room, and new IRC room

### ISSUE THREAD

**Issue by Richard-Rogalski** [dankamongmen/notcurses#2786]
The official matrix room (`#notcursesdev:matrix.org`) has been mostly abandoned, except some people asking unanswered questions, a spam bot, and people asking about an IRC. 

I decided to make an unofficial IRC room (`#notcurses` on `irc.libera.chat`) because of that (plus it's what most devs seem to use), and I'd be happy to hand over the chanserv registration to you if you joined IRC (which you should!!)

I could also host a matrix <> IRC relaybridge for the two rooms, would that be something you'd be alright with me doing?

and besides the dead matrix, is there any other place for folks to ask questions or get support involving notcurses to direct people to?

Thanks,
 -- Rich

**Comment by dankamongmen** [comment]
thanks much for the effort! i hang on irc ... rarely. i'm more of an email guy.

questions are always welcome here! i'd like things to be collected in one (open, searchable) place.

i encourage you to do all things you consider helpful and wise. i'm unlikely to hang out in irc/matrix/slack/discord personally, but may one thousand flowers bloom!

**Comment by dankamongmen** [comment]
i'd be welcome to a PR which removes references to dysfunctional spaces btw

**Comment by Richard-Rogalski** [comment]
Alright, I bridged the matrix and IRC, and set up a notice to let users know that the best places to get support is the GH issues and mailing list.

I also gave `dankamongmen` founders flags for the IRC room, assuming that is your account.

**Comment by dankamongmen** [comment]
it is =] thanks!
