### ISSUE TITLE
Tag and version descrepency

### ISSUE THREAD

**Issue by bevanjkay** [dankamongmen/notcurses#2795]
Hi 👋,
Homebrew maintainer here.

We are trying to build the latest version of notcurses here - https://github.com/Homebrew/homebrew-core/pull/192615

It looks like a tag was added for `3.10.0` where the latest release is `3.0.10` - and also the internal version is showing `3.10.0`

Perhaps correcting this with a new tag `3.10.1` and release may be the best course of action?

**Comment by dankamongmen** [comment]
good lord, i must be losing my mind. on it. thanks.

**Comment by dankamongmen** [comment]
should be good now. sorry about that =\

**Comment by dankamongmen** [comment]
i've also renamed the `.tar.gz` artifact. let me make sure it's not misnamed internally...

**Comment by dankamongmen** [comment]
ahh it was the `.tar.gz.asc` that needed renaming. ok, things look fine maybe hopefullly...

**Comment by dankamongmen** [comment]
i have marked 3.0.10 as `Cursed` in the release notes, and am cutting 3.0.11. please don't use 3.0.10, as it is, as mentioned, cursed.
