### ISSUE TITLE
RPM package for fedora

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#328]
Let's literally take it back to '99. Prep RPM packaging for inclusion in Rawhide.

https://docs.fedoraproject.org/en-US/quick-docs/creating-rpm-packages/index.html
https://docs.fedoraproject.org/en-US/packaging-guidelines/
https://fedoraproject.org/wiki/Join_the_package_collection_maintainers

**Comment by dankamongmen** [comment]
@dcantrell if you happen to be handling this, let me know.

**Comment by dcantrell** [comment]
Yeah, I can take a look at this one and submit it for Fedora.  If you also want to co-maintain it, create a Fedora Account and then I sponsor you and add you to the package.

**Comment by dankamongmen** [comment]
I don't know what retardation I was engaging in previously, but this morning I had no difficulty sending mail to the fedora-devel list (I also got my FAS and redhat bugzilla accounts synced up). It looks like the next step will be installing a Rawhide VM and getting the developer tools set up.

But first, I need go do some actual paying work!

**Comment by dankamongmen** [comment]
I've added `USE_TESTS` to `CMakeLists.txt`, defaulting to on. Setting this to `off` together with the preexisting `USE_FFMPEG=off` allows for a Fedora Core build. I'm preparing the spec file now. Dependencies in Core include: `gnupg2 cmake xz make g++ ncurses-devel pandoc python3-devel`

**Comment by dankamongmen** [comment]
@dcantrell is there any kind of "give me a c++ compiler" metadependency i can use? I'm pretty sure we build with either gcc or clang, but I'm not seeing anything of that nature at https://docs.fedoraproject.org/en-US/packaging-guidelines/C_and_C++/. For now I'm just `BuildRequires: gcc-c++`

**Comment by dcantrell** [comment]
There's no generic C++ compiler dependency since the introduction of LLVM/Clang alongside gcc/g++.  The default buildroot no longer provides any compilers either, so you need an explicit BuildRequires for the one you want to use.  There's no rule that you need to use one over the other.  I'd recommend just adding:

BuildRequires: g++

to the spec file.

**Comment by dankamongmen** [comment]
> BuildRequires: g++ 

i think they actually want gcc-g++, which decays to this. that's what i've got in my specfile.

**Comment by dankamongmen** [comment]
Alright, I've got a specfile in master which I believe will work with 1.2.6, when I cut that. @dcantrell , if you could take a look and let me know anything you'd like to have fixed up, I'd appreciate it. If things look good to you, I'll cut 1.2.6 and file a Redhat bug with the source+binary RPMs.

**Comment by dankamongmen** [comment]
> Alright, I've got a specfile in master which I believe will work with 1.2.6, when I cut that. @dcantrell , if you could take a look and let me know anything you'd like to have fixed up, I'd appreciate it. If things look good to you, I'll cut 1.2.6 and file a Redhat bug with the source+binary RPMs.

https://github.com/dankamongmen/notcurses/blob/master/tools/notcurses.spec

**Comment by dankamongmen** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1822971 is the fedora bug; gonna reply to reviewers tonight and hopefully have this wrapped up this week.
