### ISSUE TITLE
split out libnotcurses-minimal without ffmpeg linkage

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#339]
@edmonds thinks it would be a good idea to split out a libnotcurses1 package sans ffmpeg linkage. I'm inclined to agree, though I think we differ a little on exactly how we'd like to see it done. This is not a blocker for uploading and sponsorship.

**Comment by dankamongmen** [comment]
Obviously we'll have to move to a `dlopen()`-based load of ffmpeg to do this properly.

**Comment by dankamongmen** [comment]
It sounds like we'll need to do something similar for Fedora (see #328), since FFMpeg isn't allowed in Fedora Core. putting the ffmpeg portion in Fedora Fusion ought suffice, though.

**Comment by dankamongmen** [comment]
As noted in #453, OpenImageIO can apparently do a number of video formats. If so, I think we should perhaps just make it the default, making this much less important.

**Comment by dankamongmen** [comment]
I think we might want to go ahead and move on this. The one thing I'd like to do is continue to *allow* a libnotcurses.so to be built containing full multimedia support. You can also build them as plugin libraries, but I want a single-file solution for people who want that (it's much simpler administration). Can a shared object call itself with `dlopen()`, and extract its own functions with `dlsym()` on the result? If so, that ought be easy.

Packaging might be a pain in the ass. It'll certainly involve a trip through accursed debain NEW, fml.

**Comment by dankamongmen** [comment]
The Alpine people need this sooner rather than later for work on their installer. Let's move forward on this.

**Comment by dankamongmen** [comment]
Looks like you can get a handle to your own binary with `dlopen(NULL)`.

**Comment by dankamongmen** [comment]
So @kaniini I've been thinking about this all day, and I'd really rather not set up a whole dynamic module loading-and-interrogating apparatus, i.e. I'd very much like to avoid:

 * usr/lib/libnotcurses.so dlopen()s
 * usr/lib/notcurses-plugins/multimedia-ffmpeg.so links to
 * usr/lib/libavcodec.so

I want to retain

 * usr/lib/libnotcurses.so links to
 * usr/lib/libavcodec.so

or

 * usr/lib/libnotcurses.so links to nothing

So this is no problem for people building it themselves; they just supply

`-DUSE_MULTIMEDIA=none` or `-DMULTIMEDIA=oiio` or whatever

the question is one of packaging. I see four possibilities:

 * libnotcurses.so packaged by multiple exclusive packages, only one on system at a time
 * libnotcurses*.so packaged by multiple non-exclusive packages, you can have multiple installed, but now the user needs pick which one they want to link against (and there are no real space/depends savings)
 * libnotcurses.so with multiple independently-named multimedia objects, you can have multiple installed, but the user needs pick one of these to install (on which libnotcurses.so can't depend, at best recommend) to get multimedia capabilities
 * libnotcurses.so with a single multimedia bridge object packaged by potentially multiple exclusive packages, only one on a system at a time, same recommendation/discoverabilty problem as above

the only downside of option A seems to be (a) distribution archive space (since all three copies are "full editions"), and (b) that it requires suitable packaging infrastructure (the ability for multiple packages to Provide a dependency, the ability for multiple packages to Conflict with one another, and that multiple packages in the archive can contain the same file). Debian can definitely support this. Can Alpine's apk? I need check Arch and Fedora.

If everyone can, I imagine the following:

* Virtual package: libnotcurses-any
* Virtual package: libnotcurses-multimedia
* Debian: build against ffmpeg, Providing both virtual packages. build against none, Providing libnotcurses-any
*  Fedora: build against OIIO, Providing both virtual packages. build against none, Providing libnotcurses-any
  * who knows, maybe we build against ffmpeg in Fusion, which would provide both
 * Alpine: build against ffmpeg, Providing both virtual packages. build against none, Providing libnotcurses-any
 * Arch: build against ffmpeg, Providing both virtual packages. build against none, Providing libnotcurses-any

and the different builds on each distro would Conflict with one another.

Now when you're packaging your app, you can depend on either libnotcurses-any (if you don't need multimedia), or libnotcurses-multimedia (if you do). The former is satisfied by any notcurses binary package. The latter is satisfied only by a notcurses binary package that linked against ffmpeg or oiio. Would that fly?

**Comment by dankamongmen** [comment]
Confirmed that we can do this on Fedora: https://docs.fedoraproject.org/en-US/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch-advanced-packaging.html

**Comment by dankamongmen** [comment]
After some extensive discussion with my wise friend @pkern, we're going to do the following:

* there will be libnotcurses.so, representing the Notcurses core
* there will be a directory $PREFIX/lib/notcurses containing shared objects
* these shared objects will be populated with strong symbols
* Notcurses will export some weak symbols -- for now, all symbols related to multimedia
* Distros will get a single new additive (i.e. non-conflicting) package, covering multimedia

getting this done before Debian's Bullseye freeze and Fedora's F34 freeze seems highly desirable, so i'm going to take this as my #1 priority. @kaniini , any idea on when Alpine 3.13 will freeze? also, it would be good to hear from you that this approach will satisfy your needs as expressed in #1224.

**Comment by dankamongmen** [comment]
if @edmonds has any thoughts he'd like to chime in with, i'd also be interested in hearing from him.

**Comment by dankamongmen** [comment]
speaking of which, @dcantrell i wouldn't mind hearing your perspective as a Fedora doyen.

**Comment by dcantrell** [comment]
Hmmm, my first thought is this is relying too much on the package manager to control and advertise library functionality.  Personally, I would prefer the dlopen plugin approach.  Have a single libnotcurses and additional functionality provided by plugins that are dlopen'ed at runtime.  Going the other way, programs will have to be built and linked against specific libnotcurses builds and across distributions what those DT_SONAMEs are and where they live will vary.  I would prefer instead to install a notcurses application that fails to load but gives me an error about missing functionality which I can then Google for and see oh, I need to install notcurses-ffmpeg from RPM Fusion.  The user can enable and disable functionality by adding and removing packages.  You don't also need to yank and replace variant builds of programs you were using.

The way gstreamer and gdk-pixbuf do this is understandable from an end user point of view and allows for functionality to be split across repos.

**Comment by kaniini** [comment]
3.13 is already in soft freeze.  The installer project is not urgent, that's something I plan to work on in the new year.

I think using plugins makes more sense than depending on package managers to behave in some specific way though.  A lot of package managers cannot handle those kind of dependency relationships.

**Comment by kaniini** [comment]
Anyway my proposal wouldn't be to use plugins but to simply have the core notcurses functionality in a `libnotcurses-core`, which `libnotcurses` (with the bling) would link to.  Developers would continue to link against `libnotcurses` unless they wanted just the base TUI lib, in which case they could link against `libnotcurses-base` instead.

**Comment by dankamongmen** [comment]
@kaniini the problem with your approach, so far as i understand, is that if you do not have the blingful version installed, you have to use `-lnotcurses-core`, since `-lnotcurses` won't find anything. right? now, it's very possible that you can work around that with ldconfig or something, but then you've either got a conflict, or you have to have logic to determine if both are installed.

**Comment by dankamongmen** [comment]
I'm thinking (and i think @dcantrell is on the same wavelength) that we invert your idea, and instead we have:

PREFIX/libnotcurses.so
PREFIX/notcurses/libnotcurses-ffmpeg.so  <---- /notcurses/ here is optional

you have (say) two packages: libnotcurses2 and libnotcurses2-ffmpeg. former Recommends the latter. latter Depends on the former.

in `notcurses_init()` we do a `dlopen()` run against known names, or against all the files in a directory (i don't really care, but lean towards the former). we then dlsym() out the desired symbols. alternatively, libnotcurses.so implements them as weak stubs, while the other .sos ship strong implementations. i believe this saves us a pointer lookup + indirect jump per function call, if nothing else :D.

**Comment by dankamongmen** [comment]
hrmmm this whole concept breaks static binaries, doesn't it :/. or maybe not?

the approach i have above doesn't really leave you any way to link against *only* the core, should you want to. i don't see any advantage to doing so, though (especially with an option to `ncdirect_init()`/`notcurses_init()` that inhibits dlopen() runs). but we have to make a choice regarding which static library we're installing.

**Comment by dankamongmen** [comment]
actually, we could just have libnotcurses-dev install two .a files, one with multimedia support, one without (since it wouldn't lead to another runtime dep). you'd have to know to link against -lnotcurses-multimedia.a, but you'd be able to choose...

**Comment by dankamongmen** [comment]
so, i'm envisioning:

- libnotcurses2 installs libnotcurses.so
- libnotcurses-multimedia2 installs libnotcurses-multimedia.so, and Depends on libnotcurses2
- libnotcurses-dev installs libnotcurses.a and libnotcurses-multimedia.a, built with different objects (ffmpeg.o vs visual.o)

libnotcurses2 is compiled with the expected install location of libnotcurses-multimedia2 (it also uses default search paths; see `dlopen(3)`). it attempts to `dlopen()` that shared object in `notcurses_init()` / `ncdirect_init()`. this can be inhibited with an option. if it successfully opens the object, it `dlsym()s` up the necessary symbols.

for unit tests, we export `LD_LIBRARY_PATH` maybe.

we perhaps still support a monolithic model, preferred when developing.

this avoids any weak/strong symbol chicanery, which appears to be pretty nonportable. it avoids trying to load a shared object from a static binary. it uses additive shared objects.

**Comment by kaniini** [comment]
My idea doesn't involve dlopen at all.

You would just have two packages in this case: libnotcurses and libnotcurses-multimedia.  If you link against the latter, you get the multimedia support.

That all still works with static linking, it just splits out the functions related to multimedia to its own library (which depends on the base library of course).

So, for example, growlight would link with `-lnotcurses`, but notcurses-view would link with `-lnotcurses -lnotcurses-multimedia`.

Then the latter could be shipped in RPM Fusion or such for Fedora.

**Comment by pkern** [comment]
To clarify: My proposal was identical to @kaniini. You'd likely need two separate pkg-config files, though, to let consuming packages make it clear which one they need.

**Comment by dankamongmen** [comment]
If we're gonna do this for Bullseye, we need to have it done ASAP, as no new packages will be allowed past 2021-02-12.

**Comment by dankamongmen** [comment]
I'm beginning work on this, and expect it to be the defining feature of 2.1.6, and indeed of 2.2.0 It is quite possible that I'll release 2.2.0 shortly after completing this.

**Comment by dankamongmen** [comment]
Alright, looking at all available options:

* Any acceptable option MUST result in two distinct packages -- the goal, after all, is to allow a notcurses app that does not require multimedia to not provoke its installation
* `dlopen()` complicates things at runtime, but simplifies things for users (you don't need to know about -lnotcurses-multimedia)
* -lnotcurses-multimedia simplifies things at runtime, but complicates things for users
* in any solution, the static libraries must be kept separate, to avoid duplication, but pkgconfig ought make this not a problem

So it comes down to: do we make things more complicated for the user, or for us at runtime? Well, I'd like to propose a third solution that I believe *complicates things only for the advanced user*: **`-lnotcurses` and `-lnotcurses-core`**

* No dlopen. 
* `libnotcurses.so` requires `libnotcurses-core.so`, which pkgconfig assists in
* `libnotcurses.a` requires `libnotcurses-core.a`, which pkgconfig assists in
* using a bare `-lnotcurses` now breaks, but who cares? you ought be using pkgconfig. there might be other failures when people don't use pkgconfig, so i like the idea of forcing it.
* `pkg-config --libs notcurses` outputs `-lnotcurses-core -lnotcurses`
* `pkg-config --libs notcurses-core` outputs `-lnotcurses-core`
* `libnotcurses.so` corresponds to `libnotcurses-multimedia.so` in @pkern  and @kaniini 's proposals, just as `libnotcurses-core.so` corresponds to their `libnotcurses.so`
* packaging wise, there's now libnotcurses-core2 and libnotcurses2, with the latter depending on the former, and the former recommending the latter. likewise libnotcurses-core-dev and libnotcurses-dev.
** `growlight` Build-Depends on `libnotcurses-core-dev` and Depends on `libnotcurses-core2`
** `notcurses-bin` will Depend on `libnotcurses2`

This way, a minimum-knowledge user just runs `pkg-config --libs notcurses` as expected, and gets full functionality, saving me bug reports. A more knowledgeable user looking to prune down their dependency stack can specify `notcurses-core`.

I think this is the best of all worlds, and am inclined to proceed this way. @pkern, @kaniini , what say ye?

**Comment by dankamongmen** [comment]
I think I can get this done tonight. @pkern , if you accept this approach and are willing to upload it to NEW, we ought be able to get in comfortably ahead of the 2021-02-12 freeze.

**Comment by dankamongmen** [comment]
We'll need to update at the very least `USAGE.md` and `notcurses.3.md`.

**Comment by dankamongmen** [comment]
There's also the question of library wrappers. Unless we split all of them up as well, they all need to depend on the full `libnotcurses`, as they do now. If any of them choose to split, they can support thin notcurses, but no changes are needed at this time AFAICT.

**Comment by dankamongmen** [comment]
Ick, the one thing that's bad about this idea (under *any* implementation AFAICT) is that we're going to have to start exporting some symbols we're not currently exporting (and that I hadn't really wanted to export). Unless we make them all `static inline`, of course.

**Comment by dankamongmen** [comment]
One other tricky element would be `notcurses_canopen_video()` and `notcurses_canopen_images()`. We need these available to `notcurses-core`, but they need to behave differently when `notcurses` is present. I see two ways to handle it:

* They report using a dynamic element from the `notcurses` struct which is set to `true` by a `notcurses` library constructor. Not necessarily portable beyond gcc.
> The constructor attribute causes the function to be called automatically before execution enters main (). Similarly, the destructor attribute causes the function to be called automatically after main () has completed or exit () has been called. Functions with these attributes are useful for initializing data that will be used implicitly during the execution of the program.
* We use a weak symbol in `notcurses-core` for these two functions, and override them in `notcurses`.

**Comment by dankamongmen** [comment]
Maybe those symbols just shouldn't exist without `libnotcurses.so`. That way you can't get a successful link that ends up failing to do what you want it to do. Is there really any good use case for a source base that can use multimedia when it's available, but still work otherwise?

Hrmmm, I clearly though so once, or else `notcurses_canopen_image()` wouldn't exist in the first place... =[

**Comment by dankamongmen** [comment]
We'll likewise need to split `direct.h`, though this will only be an `#include` deal, since ncdirect isn't its own library.

**Comment by dankamongmen** [comment]
Hrmmm so with `-DUSE_MULTIMEDIA=none` do we simply no longer build `notcurses++`? I guess not, at least for the time being, hrmm.

**Comment by dankamongmen** [comment]
Urk...how are we going to get `ncvisual_init()` called from `notcurses_init()`? =[

**Comment by dankamongmen** [comment]
> Urk...how are we going to get `ncvisual_init()` called from `notcurses_init()`? =[

Hrmmm, perhaps a `dlsym()` check on ourselves? Might that work? Would it work on Windows one day?

**Comment by dankamongmen** [comment]
> > Urk...how are we going to get `ncvisual_init()` called from `notcurses_init()`? =[
> 
> Hrmmm, perhaps a `dlsym()` check on ourselves? Might that work? Would it work on Windows one day?

Except it won't work for static linking :(

**Comment by dankamongmen** [comment]
Ok so what if we just did an interposition layer using function pointers and library constructors?

So each public API call implemented by `libnotcurses.so` is exported by `libnotcurses-core.so`. Each one has structure of the form (except we roll all of these into one interface struct with an atomic pointer, and replace the `pthread_mutex_t` with either a rwlock held across the invocation, or better yet an atomic guaranteed via explicit semantics):

```
static pthread_mutex_t ncvisual_decode_lock = PTHREAD_MUTEX_INITIALIZER;
static int (*ncvisual_decode_real)(ncvisual* nc);
int notcurses_internal_set_ncvisual_decode(int (*fxn)(ncvisual* nc)){
  int ret = -1;
  pthread_mutex_lock(&ncvisual_decode_lock);
  if(ncvisual_decode_real == NULL){
    ncvisual_decode_real = fxn;
    ret = 0;
  }
  pthread_mutex_unlock(&ncvisual_decode_lock);
  return ret;
}
// would synchronize callers to ncvisual_decode, so use rwlock or atomic instead
int ncvisual_decode(ncvisual* nc){
  int ret = -1;
  pthread_mutex_lock(&ncvisual_decode_lock);
  if(ncvisual_decode_real){
    ret = ncvisual_decode_real(nc);
  }
  pthread_mutex_lock(&ncvisual_decode_lock);
  return ret;
}
```

and now `libnotcurses.so` has no public symbols. Except we then must expose whatever functionality sets the function interface =[.

**Comment by pkern** [comment]
> Is there really any good use case for a source base that can use multimedia when it's available, but still work otherwise?

That cycles back to my original question what this is used for (without having additional context about notcurses myself). If you think e.g. about a file viewer, it's fine if that degrades to "without multimedia support" on headless systems. However in such a case it feels like one'd potentially want to have multiple plugins that register themselves for file types. And that boils down to a dlopen kind of system with additional modules that are optional. And that's sort of what we discarded.

I guess there's also the question of constraining yourself to only the supported set at compile time, rather than at link time. And that'd require splitting headers potentially (into a core/non-core set)?

I was also thinking about `dlsym()`, but AIUI that's only guaranteed to work with `dlopen()`.

**Comment by dankamongmen** [comment]
> I guess there's also the question of constraining yourself to only the supported set at compile time, rather than at link time. And that'd require splitting headers potentially (into a core/non-core set)?

I've worked around this by using a `__attribute__((constructor))` to inject an implementation at load time. this works for both static and dynamic objects, apparently (fingers crossed regarding BSD, which i'll test momentarily). i'm committing this literally right now (to a branch).

**Comment by pkern** [comment]
Whatever you pick should follow the principle of least surprise, I think. Maybe it'd help to think about this from an API point of view rather than an ABI one?

> I've worked around this by using a __attribute__((constructor)) to inject an implementation at load time. this works for both static and dynamic objects, apparently (fingers crossed regarding BSD, which i'll test momentarily). i'm committing this literally right now (to a branch).

I saw that while researching too and thought it'd be GCC specific. But I didn't check the other compilers. ;)

**Comment by dankamongmen** [comment]
I *really* don't want to have to enumerate file types, and IMHO file type determination oughtn't be done off of file extension anyway, like a caveman would. ffmpeg can just be fed a file (or memory buffer, which is another critical interface, and which *can't* provide extension-based detection), and it'll spit back frames, as will OIIO. so long as i'm using panformat interfaces like these, file extension <-> implementation mapping seems a terrible thing to introduce.

**Comment by dankamongmen** [comment]
> I saw that while researching too and thought it'd be GCC specific. But I didn't check the other compilers. ;)

i verified it on Clang, and between those we have everything but windows that matters according to my executive judgement =]

**Comment by pkern** [comment]
So we are really just talking about the few ncvisual symbols, yes?

**Comment by dankamongmen** [comment]
bleh, we can't directly inline `ncvisual_details` into `ncvisual` under this scheme, yet another annoyance. we'll have to replace `ncvisual_details_init()` with `ncvisual_details_alloc()` (just add a heap allocation), and free it up in `ncvisual_details_destroy()`. hide the `ncvisual_details` behind a pointer in `ncvisual` and we're good there. implementation details.

@pkern in terms of what we're talking about...i mean ultimately i need your sign-off on this scheme to get it uploaded to NEW =]. so to run through things now that i've got actual code down on paper:

* there will be two new Debian packages, `libnotcurses-core2` and `libnotcurses-core-dev`. Both will `Recommend` their corresponding `libnotcurses{2, -dev}`, but can be installed without them
* the vast majority of Notcurses moves to `libnotcurses-core.so`, which gets a new `pkg-config` file, along with a new `CMake` file
* all symbols previously available from `libnotcurses.so` are now available from `libnotcurses-core.so`.
** `libnotcurses.so` no longer exports any symbols
** there is a shitty new public symbol in `libnotcurses-core.so`, `notcurses_set_ncvisual_implementation()`. this is not part of the documented API. its existence makes me sad. It sets the static `ncvisual_implementation` interface pointer.
** the shim implementations of the `ncvisual` API from `visual.c` are no longer compiled only for `USE_MULTIMEDIA=none`. they are now always compiled. they check the static `ncvisual_implementation` interface, and call through it if an implementation has been registered, adding the cost of a lock+static pointer deref+unlock to each of these calls.
* `libnotcurses.so` is built only for `USE_MULTIMEDIA=oiio` or `USE_MULTIMEDIA=ffmpeg`
** `libnotcurses.so` is built with a `__attribute__((constructor))` and `__attribute__((destructor))`
** constructor calls `notcurses_set_ncvisual_implementation()`, stashing the function pointer return value
** destructor calls function pointer return value from above to zero out implementation pointer
* users linking `libnotcurses.so` get a full-bodied implementation, with all the trimmings
* 3l33t hax0rs can link `libnotcurses-core.so` to get a stripped-down bullet train implementation
* only packages which require multimedia will Depend on libnotcurses2 instead of libnotcurses-core2
** the mastodonic multimedia dependency stack will be pulled in only as necessary
* no `dlopen()` nor `dlsym()` involved, but we do use non-standard `__attribute__`s, alas, zorn
* w00t

i think that covers everything.

**Comment by dankamongmen** [comment]
> @pkern in terms of what we're talking about...i mean ultimately i need your sign-off on this scheme to get it uploaded to NEW =]. so to run through things now that i've got actual code down on paper:

(if it isn't clear, i control my own packaging on most other distros. fedora will get two new packages as well, but only new source specs need run through review (there are exceptions to this rule). arch will get new libs in their one package because the AUR is a garbage dump. alpine will get whatever is appropriate, which i will figure out. freebsd will get whatever is appropriate, which someone will inscrutably inject into my merge request. pure OS will do whatever debian does, a few days later. parrot OS will do whatever debian does, a few weeks later. conan will remain fucking indecipherable. the dude who maintains void will keep promptly kicking ass--i <3 you, void maintainer, if you're reading this.)

**Comment by dankamongmen** [comment]
![2021-01-17-131234_802x1417_scrot](https://user-images.githubusercontent.com/143473/104851884-ae3d8100-58c5-11eb-965d-f24d8a52138e.png)

first successful run under the new scheme, using ffmpeg

**Comment by dankamongmen** [comment]
unit tests pass with `USE_MULTIMEDIA=ffmpeg`!

**Comment by dankamongmen** [comment]
hrmmm, looks like we've broken the rust build. looking at it, it's clearly using `-lnotcurses`, so i'm unsure why it's not getting necessary symbols..ahh, it probably explicitly needs list `-lnotcurses-core`, and isn't...which would be coming from `pkg-config`...which would fit in with eg ncpp compiling...let's go look...

**Comment by dankamongmen** [comment]
ja, i am a stupid, this ought fix it.

**Comment by dankamongmen** [comment]
Yeah that fixed the rust build. Also, now that we're defining all symbols, we can go ahead and get back to compiling ncpp in all instances etc, right? Excellent.

**Comment by dankamongmen** [comment]
I'm thinking in the case where we're build with `USE_MULTIMEDIA=none`, we want to go ahead now and continue to build a shim, all -1 returns `libnotcurses.so` (remember, `libnotcurses-core2` is *not* a result of building with `USE_MULTIMEDIA=none`; it emerges from *any* build). Yeah.

**Comment by pkern** [comment]
Note that the old ABI had the canopen functions in libnotcurses.so.2 anyway, so you don't really need to bother providing them from libnotcurses-core.so.2, I think? I'm a bit surprised that you want to keep the shim functions rather than dropping them and making them explicitly part of the other, fully featured library. Because that'd then truly only add a dependency on the fully featured one if it is being used. But probably I'm missing something.

**Comment by dankamongmen** [comment]
if you don't want the multimedia-enabled lib, you link explicitly against notcurses-core. there is absolutely no need to link against notcurses.so when it's all shims, *unless* you're a program that can operate in both modes, determining at runtime (`notcurses-demo` is an example of this). such a program can this way just link against `libnotcurses.so`, and on an install without media support, it gets `notcurses_canopen_*()` `false` returns at runtime.

otherwise, AFAICT such a program would have to detect installs lacking `notcurses.so`, and explicitly use `notcurses-core.so` there (because it was the only thing available).

the only downside here is for someone who *does not check with `notcurses_canopen_*()`*, **and** *does not check return values*, as they're going to have no images where they presumably expected some on minimal installs. the alternative would be that their link failed (if there was no `notcurses.so`).

as another example of such a program, i've been thinking of an aptitude-like program that also showed images from screenshots.debian.org or wherever. it can operate happily without media support, but wants to use it if possible.

**Comment by dankamongmen** [comment]
I've got ffmpeg fixed up. The only place where we're still seeing problems is with `USE_MULTIMEDIA=none`, where our shims don't seem to be getting injected, and thus `ncvisual_from_rgba()` etc. are broken. This ties into the one thing I want to change: the whole shared library constructor approach doesn't look like it will work with static linking after all. I seem to recall that there's a C++ feature that allows certain initializers to be run at startup in a thread-safe way. If we can leverage those, we ought be able to do this without the library constructor....good, good.

**Comment by dankamongmen** [comment]
The `null` layer is now working. It's no longer being installed as a third `libnotcurses.so`, either; it's present in the `libnotcurses-core` as the fallback.

**Comment by dankamongmen** [comment]
Everything now seems to work properly, at least with dynamic linking.

**Comment by dankamongmen** [comment]
> I've got ffmpeg fixed up. The only place where we're still seeing problems is with `USE_MULTIMEDIA=none`, where our shims don't seem to be getting injected, and thus `ncvisual_from_rgba()` etc. are broken. This ties into the one thing I want to change: the whole shared library constructor approach doesn't look like it will work with static linking after all. I seem to recall that there's a C++ feature that allows certain initializers to be run at startup in a thread-safe way. If we can leverage those, we ought be able to do this without the library constructor....good, good.

alas, this applies to block-scoped statics, and we don't have a block to traverse here.

i'm thinking weak symbols might be the best way to go after all: https://eli.thegreenplace.net/2013/07/09/library-order-in-static-linking.
