### ISSUE TITLE
Investigate interrogation of font

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#366]
I'm not saying it's desirable, or even possible, but it would be to our advantage to be able to interrogate the font. This is definitely possible in the console, I think. In X, I'm not sure how we discover our font, or when our font changes, or if this is even a meaningful concept. But we could do a lot with this information, if we can get it.

Obviously, a huge win would be knowing the precise rendered width of various EGCs.

**Comment by dankamongmen** [comment]
#201 is the equivalent for the console

**Comment by dankamongmen** [comment]
It looks like we'd want to be querying the text shaping enginer, ala harfbuzz: https://harfbuzz.github.io/getting-started.html#id-1.2.4.2. assuming harfbuzz is used everywhere.

**Comment by joseluis** [comment]
...continuing the conversation from #967 

> When you say "already checked the character should have", what method do you propose for that?

I meant manually! We visually check in a CLI text editor how many columns wide the glyph is, using a good reference font for that unicode block. And only as many as we want to, in a need-basis, it doesn't have to be complete and cover all corner cases for it to be better than what we have now.

**Comment by dankamongmen** [comment]
> I meant manually! We visually check in a CLI text editor how many columns wide the glyph is, using a good reference font for that unicode block.

I'm not sure what "a good reference font" would be. Furthermore, even using the same font, some glyphs will be different sizes depending on the font rendering engine. If you watch suckless's `st`, it observes `wcwidth()` exactly everywhere that i can see. others do so much less. some seem not to support emoji at all. the list goes on and on.

> And only as many as we want to, in a need-basis, it doesn't have to be complete and cover all corner cases for it to be better than what we have now.

i disagree. it would IMHO be a fool's errand, go out of date almost as quickly as it was developed, complicate debugging, and provide a false sense of correctness.

i have no intention of working on such a thing. if others do, and prove out something that seems to work reliably, i might consider using it. i believe the proper thing to do is to query the font rendering engine as it's being used.

besides, this is only a problem for pretty weird characters. watch the `whiteout` and `allglyph` demos -- they usually work pretty well.

**Comment by joseluis** [comment]
Well, I already assume not every terminal will work well, like not everyone works well with emoji...

And by "a good refefencefont"... sometimes there's only one (or two fonts) for specific ranges containing the symbols of weird alphabets.

But yes, I see what you mean, it could be a real mess to maintain...

Of course if the rendering engine could be queried that would be a blast.

**Comment by dankamongmen** [comment]
Dmitry Sapozhnikov (aka @o_SDN_o) mentions https://www.cl.cam.ac.uk/~mgk25/ucs/scw-proposal.html, which is rather unappealing, but perhaps could be forced into some successful use.

**Comment by dankamongmen** [comment]
The Set Character Width proposal was last modified in 2002, and does not seem to have been picked up by any terminal emulators (I could of course be wrong). I don't think it's happening. And I don't see any way to go about investigating font data, especially in any portable way. Closing this as infeasible.
