### ISSUE TITLE
Staining paired half blocks hides half the rows

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#397]
For the book's Tetris example, I've got tetriminos that, when rotated, are redrawn with paired half blocks (see #351 for rotation mechanisms). When this happens, I'm staining them with a gradient. Since half blocks rely on the background color, they're losing half their rows when this happens. See attached.

![2020-03-07-220008_722x857_scrot](https://user-images.githubusercontent.com/143473/76155780-065d0180-60bf-11ea-917a-66114090567f.png)

**Comment by dankamongmen** [comment]
I'm not sure this is a bug, per se. The staining is functioning correctly according to any reasonable definition. If we pull the gradient effect, everything looks correct. Hrmmm.,,

**Comment by dankamongmen** [comment]
![2020-03-07-222901_722x857_scrot](https://user-images.githubusercontent.com/143473/76156077-0eb73b80-60c3-11ea-9513-cf4fada1ce03.png)

**Comment by dankamongmen** [comment]
Yeah, this was just a bug in usage, I think.

**Comment by barathrm** [comment]
Hi and thanks for notcurses!

I've been working through [your entertaining book](https://nick-black.com/dankwiki/index.php?title=Hacking_The_Planet!_with_Notcurses) and hit on this while working my way through implementing as I read through the text. Due to this and what's captured by https://github.com/dankamongmen/notcurses/issues/828 I'd recommend putting a disclaimer on the github repo's and wiki's pages mentioning that the API and examples won't necessarily work as expected, especially since the wiki page currently says that all errata have been fixed.

**Comment by dankamongmen** [comment]
> Hi and thanks for notcurses!
> 
> I've been working through [your entertaining book](https://nick-black.com/dankwiki/index.php?title=Hacking_The_Planet!_with_Notcurses) and hit on this while working my way through, implementing as I read. Due to this and what's captured by #828 I'd recommend putting a disclaimer on the github repo's and wiki's pages mentioning that the API and examples won't necessarily work as expected, especially since the wiki page currently says that all errata have been fixed.

you're absolutely right. i keep telling myself i'm going to update the book Really Soon Now, and other stuff gets in the way. it ought indeed have a disclaimer. i'll try to put that in and upload the book anew this evening.

I updated the wiki: https://nick-black.com/dankwiki/index.php?title=Hacking_The_Planet!_with_Notcurses

I'm glad you're enjoying the book otherwise!

**Comment by dankamongmen** [comment]
https://github.com/dirty-south-supercomputing/technicalreports/commit/a3f873feb8e3831efd06db404c2922fad705ac59 updated the book to include a warning on the first page. https://nick-black.com/htp-notcurses.pdf now has the updated text. thanks, @barathrm !
