### ISSUE TITLE
install python module on fedora

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#462]
We install `notcurses-pydemo` on Fedora, and dep on `python3-devel`, and build our python module, but don't install it so far as I can tell. This is lame, especially as `notcurses-pydemo` will promptly crap itself if run.

Ugh I don't want to hold back 1.3.0 but there's really no excuse for this. augh, blocker.

@dcantrell i am a very poor python developer; if you toss this up to me, it'll be taken with gratitude. otherwise, i will tomorrow read:

* https://docs.fedoraproject.org/en-US/packaging-guidelines/Python/
* https://fedoraproject.org/wiki/User:Churchyard/Packaging:Python
* https://docs.fedoraproject.org/en-US/packaging-guidelines/Python_Appendix/

and hopefully this'll be a lot less unpleasant than python packaging was for debian.

**Comment by dankamongmen** [comment]
we also don't install the rust wrappers on fedora, but we're not doing that anywhere. i have no enthusiasm regarding that can of worms.

**Comment by dcantrell** [comment]
I can look at this tomorrow [the Python part].  While I spent more than a decade in Python daily, the somewhat recent Python 2.x vs 3.x stuff has left me sort of bored and uninterested in Python.  But I don't mind looking at this and fixing it up for Fedora.

I've not used Rust, but I feel I have enough programming languages in my life.  C, and the other ones.

**Comment by dankamongmen** [comment]
So I believe all we need is to insert a `cd BUILDLOCATION/python && python3 setup.py install --prefix=/usr`. This is at least sufficient to get `notcurses-pydemo` running.

I'm trying to integrate something like this into the specfile---I'm running into issues, but I'm sure I can resolve them. With this added, I think we're good for 1.3.0.

**Comment by dankamongmen** [comment]
I'm thinking maybe the best way to do this is to stick it in CMake, guarded by `USE_PYTHON`. Debian sets `USE_PYTHON=off` and does its own thing. If Arch will work this way, we're good, and shouldn't need to touch our specfile.

**Comment by dankamongmen** [comment]
```sh
override_dh_auto_configure:
	dh_auto_configure -- -DDFSG_BUILD=ON -DUSE_PYTHON=OFF
```

yep, this won't affect Debian

**Comment by dankamongmen** [comment]
```sh
prepare() {
  mkdir -p "${pkgname}-${pkgver}/build"
  cd "${pkgname}-${pkgver}/build"
  cmake .. -DCMAKE_INSTALL_PREFIX="/usr" \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DUSE_PYTHON=OFF
}
```

won't affect Arch either. let's do it.

**Comment by dankamongmen** [comment]
Alright, I've added the necessary `install` rule, and I believe this has a good chance of working.

**Comment by dankamongmen** [comment]
Why, oh, why must python packaging be such a gigantic pain in my ass?

1.2.9 fails to build the RPM, due to missing the python module for `python3-notcurses`. I snagged an `rpmbuild` log, and the issue is that we're trying to install directly to `/usr` rather than `BUILDROOT/usr`. I recall this being the same problem we were seeing on Arch, which btw I checked last night, and 1.2.8 on Arch seems to ship a broken `notcurses-pydemo`.

I'm beginning to strongly consider moving the Python wrappers out of the main Notcurses tree, so that we can just use setuptools from the toplevel, like every packaging system on earth seems to expect.

**Comment by dcantrell** [comment]
Splitting it out may be less painful.  If you have a purely Python project to package in RPM, Fedora has enough macros to make that easy.  Mixed with other languages it's frustrating.

I also haven't looked at this at all.  Friday was a company holiday and today I'm messing around with radio.

**Comment by dankamongmen** [comment]
I've fixed the Arch install up solely by touching the `PKGBUILD` file there, so I ought be able to do something similar on Fedora, and not require a new release (i.e. only the specfile will change).

```
@@ -14,9 +14,7 @@ source=("https://github.com/dankamongmen/notcurses/archive/v${pkgver}.tar.gz")
 prepare() {
   mkdir -p "${pkgname}-${pkgver}/build"
   cd "${pkgname}-${pkgver}/build"
-  cmake .. -DCMAKE_INSTALL_PREFIX="/usr" \
-    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
-    -DUSE_PYTHON=OFF
+  cmake .. -DCMAKE_INSTALL_PREFIX="/usr" -DCMAKE_BUILD_TYPE=RelWithDebInfo
 }
 
 build() {
@@ -32,6 +30,8 @@ check() {
 package() {
   cd "${pkgname}-${pkgver}/build"
   make install DESTDIR="$pkgdir"
+  cd python
+  python setup.py install --root="$pkgdir" --optimize=1
 }
 
 sha256sums=('929eb4078a636d9ce1477bf8e534921836e0cf201ab437ab7d5a4859b73f56e0')
[grimes](0) $ 
```

this fixed things for Arch, as released in notcurses 1.2.8-2.

**Comment by dankamongmen** [comment]
ok right so to do this I need to bundle a `cd foo && python` into my specfile, which I was running into that "no job control" error when i tried the obvious thing. if i can do that, i'm good. if there's somehow no way to do such a thing in rpm spec language, i'll throw a goddamn shell script in there that does it, cut 1.2.10, and be done with this bullshit.

**Comment by dankamongmen** [comment]
oh wait if each % isn't its own shell in spec, i can just put the cd and the python on different lines, duh. let's see!

**Comment by dankamongmen** [comment]
oh fuck i'm retarded. ok, so i was trying to invoke macros like a goddamned idiot. i just need to drop that leading % and it ought be smooth sailing. augh!

**Comment by dankamongmen** [comment]
i think we've got it....!

**Comment by dankamongmen** [comment]
![2020-04-11-140327_1024x797_scrot](https://user-images.githubusercontent.com/143473/79051256-3d15c280-7bfd-11ea-9bd5-a97a96f866fd.png)

woohoo!

**Comment by dankamongmen** [comment]
Staged at https://www.dsscaw.com/repos/dnf/:

```sh
[vps](0) $ sha256sum *
0dc1a2005681b0310ca40067d40983b8ca561b9ec6b06b67a17d59e13ef74f00  notcurses-1.2.9-1.fc32.src.rpm
3b56a6201c8d86feff0a5efa123fc82d0fece15f709ca9429088975e367ac6c8  notcurses-1.2.9-1.fc32.x86_64.rpm
34177677d99d49e43e1462867b7e34d9ea4dc0ed5bb4238af41524921ecb5016  notcurses-debuginfo-1.2.9-1.fc32.x86_64.rpm
33bcd6f0f59b5880ba81c170fa2abceb98c84bfcf73411362a31682e5d4d90d2  notcurses-debugsource-1.2.9-1.fc32.x86_64.rpm
4e3f5f748c73606b395912e6fd2cdaa7fc7c1e9a4d2ba5ac611d8c549aeeaaf9  notcurses-devel-1.2.9-1.fc32.x86_64.rpm
5e526f85bb6df403060eb612ef88cfe56304fe4ef02beeaa9edce764d3938db1  notcurses-static-1.2.9-1.fc32.x86_64.rpm
d29620de08e6ac0877d4c1b23edcc27a6d83bfbaea3d678a90bda6280d061e56  python3-notcurses-1.2.9-1.fc32.x86_64.rpm
2be5429abb7daf2eb9c6758682af19209830f35917e3841e2099bf6102c86dbe  python3-notcurses-debuginfo-1.2.9-1.fc32.x86_64.rpm
[vps](0) $ 
```

**Comment by dankamongmen** [comment]
Installed python3-notcurses and notcurses 1.2.9 on a fresh F32 install, and `notcurses-pydemo` worked beautifully =] =] =] :dagger: 

I likewise confirmed that `notcurses-tetris` starts up just fine despite the absence of FFMpeg.

we're done here, bitches!
![2020-04-11-140700_1024x797_scrot](https://user-images.githubusercontent.com/143473/79051363-cf1dcb00-7bfd-11ea-8300-754f3ff966b8.png)

**Comment by dankamongmen** [comment]
updated https://bugzilla.redhat.com/show_bug.cgi?id=1822971 with invitation to review.

https://www.youtube.com/watch?v=Bu1uytWWjkA

Yes y'all, Uptown
The sound, is shakin into war
And for all y'all, this is it

I'm never alone, I'm in a zone and stoned
I never leave home without my microphone
I break backbones like a stone, I roam
I knick knack paddy wack and give a dog a bone
Like Al Capone I am a dog, I foam
At the mouth, shout it out when I groan in tone
I go Uptown, I come back home
(With who?) Me, myself and my microphone!

I go Uptown, I come back home with who?
Me, myself and my microphone!

It's like this y'all, it don't stop
You see I'm Uptown and rockin the dope spot
So I dip to the dive, thrive and come alive
The two MCs that make ya name survive
For alla y'all, my name is Run
I rock big parties, have big fun
The mind blowin, body rockin MC fiend
Who came along and made his home and chained the toll on my team
The cool calm brother from around the way
Where I'm from, DJ Run met a kid named "Jay"
We go Uptown, and come back home
(With who?) Me, myself and my microphone!

Get much respect when I flex my Tek
Unique when I speak and wreck your set
I used to take the train to public school
The microphone holdin on the golden rule
Pop pop pop, you can't stop my flow
I rock it in my pocket every time I go
Straight Uptown and come back home
(With who?) Me, myself and my microphone!
