### ISSUE TITLE
Extract Debian packaging into git-buildpackage

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#497]
During our FTPMasters review for Debian, we were admonished to extract the `debian/` content from our package proper (as we always knew ought happen). MTecknology would like to see us properly using `gbp` with an external `debian/`. Make @MTecknology happy (and do the right thing).

**Comment by MTecknology** [comment]
For the record, FTP-Masters have no opinion on this matter. I made the multiple recommendations that are only related to maintainer experience.

From an FTP-Master perspective, the only critical problems are the lack of sources for an avi file and an incorrect package version.

**Comment by dankamongmen** [comment]
I've created the repository https://github.com/dirty-south-supercomputing/debian-gbp. This will hold our debian packaging materials until moved onto e.g. salsa.debian.org (as I understand things).

Using this, I can run e.g.:

```
gbp buildpackage --git-pristine-tar --git-pristine-tar-commit --git-upstream-tag=v1.3.0 
```

I'm now going to remove the `debian/` directory from the notcurses repo proper. I'll then cut 1.3.1, and its tarball oughtn't include `debian/`. If we can build the result as expected using `gbp buildpackage`, I'll consider this issue done. We should then make 1.3.1 available on DSSCAW, and ping MTeck or @edmonds for a reupload.

**Comment by dankamongmen** [comment]
I cut 1.3.1, having removed `debian/` (after pulling recent changes into dsscaw's debian-gbp, of course). I then ran `gbp import-orig --uscan` and verified that it pulled down 1.3.1, stripped DFSG-unclean files, and packed up ../notcurses_1.3.1+dfsg.orig.tar.xz as expected. Yay!
