### ISSUE TITLE
get into intel clear linux

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#525]
Clear Linux is pretty fly, and doesn't seem to be pulling its packages from anywhere else (i.e. it is not a derivative). `autospec` looks like it might be worth learning. Let's aim to place the project into Clear Linux.

**Comment by WSLUser** [comment]
I'd love to use notcurses in Clear Linux. Can you publish a stand-alone binary for now if we're waiting on some package maintainer to declare it supports this library?

**Comment by dankamongmen** [comment]
Oh we're just waiting for someone (me, I suppose) to prepare a Clear Linux package. Either way, I'd need get a Clear Linux VM going. I might be able to do this over the break. I've meant to mess around with it for some time now.

**Comment by WSLUser** [comment]
Might be faster to spin up a docker instance. Appreciate you looking into it! (Full discretion, I'm running Clear Linux under WSL2 and don't have space for another distro).

**Comment by dankamongmen** [comment]
https://github.com/clearlinux/clr-bundles/tree/master/bundles it looks like we would want to land in here

**Comment by dankamongmen** [comment]
i believe that clear linux has been retired, at least for interactive use

**Comment by WSLUser** [comment]
It's very much still active.  Intel hasn't abandoned it yet
