### ISSUE TITLE
package doctest on fedora

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#528]
Now that we're on Fedora, it would be nice to run our unit tests there. Doing so requires doctest being available. Package it up, and once added, remove `USE_TESTS=off` from our specfile.

**Comment by dankamongmen** [comment]
@dcantrell this is a header-only library. I'm thinking that I want it to be `Name: doctest-devel`, with only that one package. Does that seem right to you, or are `-devel` packages strictly based off a common prefix (i.e. I want `Name: doctest` and `%package devel`)?

**Comment by dankamongmen** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1828205

**Comment by dcantrell** [comment]
Saw and I've taken the review.  Working on the notcurses review and the doctest review now.

**Comment by dankamongmen** [comment]
really appreciate your shepherding on this, @dcantrell

**Comment by dankamongmen** [comment]
This doesn't need to hold up 1.4.0, which I want to cut today.

**Comment by dankamongmen** [comment]
doctest is now in fedora rawhide! w00t!

**Comment by dankamongmen** [comment]
https://src.fedoraproject.org/rpms/doctest
