### ISSUE TITLE
Missing qr-code-generator isn't detected by a cmake script

### ISSUE THREAD

**Issue by yurivict** [dankamongmen/notcurses#572]
```
/usr/ports/devel/notcurses/work/notcurses-1.3.4/src/lib/fill.c:579:10: fatal error: 'qrcodegen/qrcodegen.h' file not found
#include <qrcodegen/qrcodegen.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dankamongmen** [comment]
That's surprising. It definitely ought be, and I've seen it do so on Fedora/Debian. Thanks for the report! I'll hopefully have this fixed shortly.

**Comment by dankamongmen** [comment]
Nope, I'm just entirely missing the necessary validation. How did I ever see this work? Perhaps it was only a dream. Fix incoming.

**Comment by dankamongmen** [comment]
Oh lame, it doesn't look like libqrcodegen installs the pkg-config file CMake would key off of. I guess we'll just test for the header, then, bleh.

**Comment by dankamongmen** [comment]
```
[schwarzgerat](0) $ cmake ..
-- Requested multimedia engine: ffmpeg
-- Requested build mode: RelWithDebInfo
CMake Error at CMakeLists.txt:65 (message):
  USE_QRCODEGEN is active, but couldn't find qrcodegen.h


-- Configuring incomplete, errors occurred!
See also "/home/dank/src/dankamongmen/notcurses/build/CMakeFiles/CMakeOutput.log".
See also "/home/dank/src/dankamongmen/notcurses/build/CMakeFiles/CMakeError.log".
[schwarzgerat](1) $
```

I then installed `libqrcodegen-dev`, and the test successfully passed.

**Comment by dankamongmen** [comment]
Our FreeBSD makefile now includes:

`LIB_DEPENDS=libqrcodegen.so:graphics/qr-code-generator`
