### ISSUE TITLE
Make a FreeBSD Port

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#575]
If we're going to make FreeBSD a first-class Notcurses platform, we ought at least be in the Ports Collection. I've got a preliminary BSD Makefile in `doc/FreeBSD-Makefile`, but it probably needs a bit of work before submission, and Notcurses as a whole definitely needs work (on FreeBSD) before submission.

Perhaps we can lasso @yurivict into helping us get the Port upstream, once it meets our quality expectations. I don't see this happening in the 1.4.0 timeframe, but who knows.

**Comment by yurivict** [comment]
I tried to create a FreeBSD port, but there are a few bugs to fix.

* https://github.com/dankamongmen/notcurses/issues/573

**Comment by dankamongmen** [comment]
I fixed the compiler problem #573. I fixed up the eventfd issue, replacing it with a `pipe2()` (#578). Remaining issues seem to be #576 (clone3 for ncsubproc) and #581 (doctest).

One thing we'll need deal with is getting CMake to look at `/usr/local` so it can find e.g. `graphics/qr-code-generator`.

**Comment by dankamongmen** [comment]
#574 is knocked out. Still need #577, but I think we'll be compiling on FreeBSD by morning.

**Comment by dankamongmen** [comment]
#577 is done. We now build on FreeBSD 12, with no warnings :D.

**Comment by yurivict** [comment]
The port is added: https://www.freshports.org/devel/notcurses/

Thank you for making it compatible with FreeBSD.

**Comment by dankamongmen** [comment]
oh awesome dude, thanks!!!! now, how do i go about pushing new versions when i have them? will that be taken of automatically by freebsd? if not, i'm happy to learn the process and manage it as part of my release cycle. we can carry on the conversation here, or you can mail me at nickblack@linux.com.

**Comment by dankamongmen** [comment]
ahhh, i see it already has 1.4.1 from this morning, nice! was that automatic, or did it require your assistance?

**Comment by dankamongmen** [comment]
BTW, I think you probably want py-cffi as a build dep.

I'd love to become a co-maintainer and start my journey back along the FreeBSD Path, if you're interested in bringing me on.

**Comment by yurivict** [comment]
Nick, I've replied to you via e-mail.

Yuri
