### ISSUE TITLE
Package doctest for FreeBSD Ports Collection

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#581]
On some platforms, doctest is unavailable. This seems to be the case on FreeBSD, and I've got an active bug out on Fedora support (see #528 ). Given that doctest can be acquired as a single header, we probably ought fetch it in such a case iff `USE_NETWORK` is ON.

I'm not sure whether FreeBSD Ports are allowed to go grabbing source during the compilation step. If not, this probably isn't worth doing, and we ought just construct our Port using both notcurses and doctest.h as sources (i.e. `portsnap` or whatever would be grabbing it).

**Comment by dankamongmen** [comment]
@yurivict if you have any advice here, I'd appreciate it. Perhaps I've just missed doctest in the Ports Collection, even?

**Comment by dankamongmen** [comment]
I think I'd rather just package up doctest for FreeBSD than do this hack.

**Comment by dankamongmen** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246653 Port created! Hopefully it will be accepted and we can close this up.

**Comment by dankamongmen** [comment]
Yuri picked up our Port and committed it. Huzzah!

**Comment by yurivict** [comment]
Cool!
