### ISSUE TITLE
ncpp_build breaks with segfault in ncuplot_create

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#616]
Running `ncpp_build` or `ncpp_build_exceptions` on HEAD post 1.4.2.3 results in a segfault where I don't believe one to be intended:

```
std::ios_base::Init::Init()(0x55e7bb880491, 0x7ffca6adc6b8, 0x7ffca6adc6c8, 224) = 0
__cxa_atexit(0x7f3d23377940, 0x55e7bb880491, 0x55e7bb880168, 6) = 0
setlocale(LC_ALL, "")                                           = "en_US.UTF-8"
ncpp::NotCurses::NotCurses(notcurses_options const&, _IO_FILE*)(0x7ffca6adc570, 0x55e7bb880340, 0, 0Term: 104x78 alacritty (alacritty terminal emulator)
) = 0
notcurses_version(0x7f3d23512240, 0, 0, 0x7f3d231d3673)         = 0x7f3d23503bb3
ncpp::Root::get_notcurses() const(0x7ffca6adc590, 0, 0, 0x7f3d231d3673) = 0x55e7bc519000
ncplane_new(0x55e7bc519000, 1, 1, 0)                            = 0x55e7bc553570
ncpp::Plane::map_plane(ncplane*, ncpp::Plane*)(0x55e7bc553570, 0x7ffca6adc590, 16, 0x55e7bc553620) = 0x7ffca6adc590
ncuplot_create(0x7ffca6adc590, 0x55e7bb880320, 0, 0 <no return ...>
--- SIGSEGV (Segmentation fault) ---
--- SIGSEGV (Segmentation fault) ---
+++ killed by SIGSEGV +++
```

I probably broke this somehow recently. Speaks to the value of #538 , though. Taking it.

**Comment by dankamongmen** [comment]
An interesting observation: this is the result when built in optimized mode. When built in `Debug` mode, we instead see:

```
[schwarzgerat](130) $ ./ncpp_build
Term: 104x78 alacritty (alacritty terminal emulator)

 notcurses 1.4.2 by nick black et al
  78 rows, 104 columns (126.75KiB), 256 colors (direct)
  compiled with gcc-Clang 9.0.1
  terminfo from ncurses 6.2.20200212
  avformat 58.43.100
  avutil 56.44.100
  swscale 5.6.101
Initialization error: notcurses failed to create a new plot
[schwarzgerat](1) $ 
```

**Comment by dankamongmen** [comment]
Hrmmm, if we're seeing that, it' spresumably generated from here:

```cpp
      if (plot == nullptr)
        throw init_error ("Notcurses failed to create a new plot");
```

how am i seeing that in `build-ncpp`? shouldn't that only be with `build-ncpp-exceptions`?

**Comment by dankamongmen** [comment]
Either way, we're definitely passing an invalid `ncplane` down into the notcurses layer. This is similar to what I was seeing with `ncpp:Selector`.

**Comment by dankamongmen** [comment]
@grendello if you could take a look at this, I'd appreciate it. I've got a minimum unit test now which just tries to instantiate a `PlotU` atop the standard plane. It fails out inside notcurses at the `sdimy` check, which is based off the provided `ncplane`. I've verified that the `ncplane` passed in is *not* the standard plane, and that if I create my own plane and use it, the `ncplane` ultimately passed in is *not* the original `ncplane` returned by notcurses.

I get now that the `operator *` in `Plane` is a user-defined conversion operator, but something's definitely amiss in the `Plot` constructor delegation forest.

**Comment by grendello** [comment]
@dankamongmen I'll take a look later today, or tomorrow. Regarding "why do I see the exception" - we always throw exceptions from constructors (RAII)

**Comment by dankamongmen** [comment]
> @dankamongmen I'll take a look later today, or tomorrow. Regarding "why do I see the exception" - we always throw exceptions from constructors (RAII)

yeah, realized this after sending it, my bad :). that's interesting -- i thought the point of not using exceptions was to allow `-fno-exceptions` to be used, thus eliminating the small distributed overhead of exception handling. Which now makes me wonder -- how does `-fno-exceptions` even work, when constructors only have exceptions as a means to indicate failure? Do you have to then design all your constructors to be small wrappers around factory-style creators, which only then return failures? Yuck.
