### ISSUE TITLE
RFE: add cmake ioption to not build and install static libraries

### ISSUE THREAD

**Issue by kloczek** [dankamongmen/notcurses#625]
Yeah .. it would be good to have such option :P

**Comment by dankamongmen** [comment]
I'm happy to add this, but can I ask about the motivation? Are you running into problems building them? Are they giving you problems? Is the static library particularly large?

**Comment by kloczek** [comment]
In most of the cases if shared library is available using static one is only asking for trouble from point of view of long term maintenance packages using package providing exact library..

**Comment by kloczek** [comment]
And building and discarding such static library on building package is only waste of time.

I've added on top of you code two patches for drop building html documentation (man pages are GoodEnough(tm)) and install *.md files from project root tree as documentation. Those files are not needed and producing them and discarding as well is waste of time.

I've not submitted those patches because my hacks are removed that parts unconditionally (which you may not like). If you want I can share my modification with you.

**Comment by dankamongmen** [comment]
For not doing the HTML documentation, you can just provide `-DUSE_PANDOC=off`, though this will also disable manpage generation. Adding an option to disable HTML generation without affecting man page generation will involve correlation with `USE_PANDOC`, and I don't want any more CMake complexity than is necessary.

I can go ahead and add an option to disable the static libs. It'll be present in 1.4.3. I'm surprised that you don't want them, though -- usually it's wise to make these available for people who want to do static linking. In Debian, they're included in the `libnotcurses-devel` package, for instance.

What distro are you packaging for, if you don't mind me asking?

**Comment by kloczek** [comment]
> I'm surprised that you don't want them, though -- usually it's wise to make these available for people who want to do static linking

Try to search why on systems like Solaris you will not be able to find even single static libarary from more than 15 years. Yep Debian still has a lot to catch up. from systems like Solaris :)

> What distro are you packaging for, if you don't mind me asking?

I'm using distro on which I'm working now which soon will be publically available product.

**Comment by dankamongmen** [comment]
I've added `USE_STATIC` to the set of CMake variables, and documented it in README.me and NEWS.md. It defaults to `ON`. If turned off, the static libraries will not be built or installed.

**Comment by dankamongmen** [comment]
Note that even if `USE_STATIC=off` is provided to CMake, it is still possible to explicitly build the static libraries by providing their names to the system builder (Make, Ninja, etc.). My change just excludes them from the default target.
