### ISSUE TITLE
Console never uses fullwidth glyphs

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#666]
The linux console appears to have no capability to emit wide chars, and the FreeBSD console seems similar (I'm not certain, though). Certainly during the `whiteout` and `uniblock` demos never seem to have emitted a wide glyph in the console. Given this fact, while it's certainly only a partial solution to the general problem of true glyph width, we ought consider `wcwidth()` to be capped at 1 for the console.

Interpose ourselves between `wcwidth()` and all callers (and consider making this function public). Accept the same argument(s) as `wcwidth()`, along with a `const struct notcurses*`. If we're in the console of Linux or FreeBSD (how precisely do we determine this?), clip all positive return values to 1.

This ought resolve #229, if nothing else.

**Comment by dankamongmen** [comment]
I am apparently entirely wrong about this, as the new `a`llglyphs (see #668 ) demo proves. Indeed, this "fix" makes the `whiteout` demo line up far less accurately than it did before. Do not apply the proposed changes. Our problems in `whiteout` are due to something else.

(A wide glyph on the Linux console is rendered, when not present in the console font, as a box followed by a space).

**Comment by jquast** [comment]
You might be interested in my solution for detecting the Unicode Version support level of a given terminal emulator, https://github.com/jquast/ucs-detect/ could be used to detect such things. I wrote a more detailed article at https://jeffquast.com/post/terminal_wcwidth_solution/

**Comment by dankamongmen** [comment]
> You might be interested in my solution for detecting the Unicode Version support level of a given terminal emulator, https://github.com/jquast/ucs-detect/ could be used to detect such things. I wrote a more detailed article at https://jeffquast.com/post/terminal_wcwidth_solution/

interesting (and i agree with your assessment of Thomas E. Dickey, a great man). so far as i understand, even your solution here is incomplete, because (independently of the terminal's level of unicode support) the particular font engine + font ultimately set the width of a given glyph. i.e. the same terminal can definitely display the same EGC at two different widths, depending on the font being used. i know this latter to be true. does your solution somehow work around it?

**Comment by jquast** [comment]
Well it is true that a font can display 2 cells wide, but if the emulator doesn’t understand it to be so, it will usually “blot” over it in my tests. I think that shows in the first screenshot of the article if we understand each other correctly

Yes, wide characters will print beyond 1 cell in some emulators, even if they don’t understand it to be wide, but they will still report their cursor (y,x) in response to “Report Cursor Position” query, and report that only 1 cell advanced, even if the font is larger. I think even if a font was a theoretical 15 cells wide, most emulators understand their rendering as cells in a grid, advance the cursor by 1 or 2, and display the next font character, sometimes blotting right over the previous one, the font’s draw width is hardly ever perceived by any of the emulators I’ve worked with, they just draw and trust

Given time I hope to make something of a wide character display test program along with ucs-detect, and test all of the popular terminals (of their default fonts) and publish a report. Maybe I will include screenshots, too. I’ll be sure to share it.
