### ISSUE TITLE
[python] debian 10.3 pip3 install fail

### ISSUE THREAD

**Issue by thenger** [dankamongmen/notcurses#698]
Hello,
I tried to install python3 library like so:

`pip3 install [--user] notcurses` and `sudo python3 -m pip install notcurses`

and it failed like this:
```
  creating build/temp.linux-x86_64-3.7/build/temp.linux-x86_64-3.7
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -c build/temp.linux-x86_64-3.7/_notcurses.c -o build/temp.linux-x86_64-3.7/build/temp.linux-x86_64-3.7/_notcurses.o
  build/temp.linux-x86_64-3.7/_notcurses.c:541:14: fatal error: notcurses/notcurses.h: No such file or directory
       #include <notcurses/notcurses.h>
                ^~~~~~~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

I also tired with this Dockerfile (same error):
```
FROM debian:10.3

RUN apt update
RUN apt install -y python3 python3-pip gcc

RUN pip3 install notcurses
```

Am I doing it correctly ?

Sorry if this is not the good place to ask this but I figured it would be the best if it is actually an issue

**Comment by dankamongmen** [comment]
Here is absolutely fine :). You need to have the notcurses library and development files installed for the python module to build, since it's basically just CFFI around said library. If you're on a Debian Unstable or Ubuntu Groovy Gorilla machine, you can just install `python3-notcurses`, and get everything. If you're on a Fedora machine, you can run `dnf install python-notcurses`. On Arch, install the `notcurses` package from the AUR.

If you're not on such a distribution, or otherwise can't install things through your package manager, you'll need check out the notcurses repo (this one) and build the library from source. On the plus side, this will also build the Python modules.

Sorry that things aren't simpler =[. Let me know if you need any more information, and otherwise please close this bug. Thanks!

(also, thanks for reminding me to push 1.5.0 to PyPi, just done).

**Comment by thenger** [comment]
Thank you for the instant reply

Ok so I finally figured out (x
I almost never build stuffs but I'm glad I did : very nice demo haha

I am on windows using putty to a debian10.4 VM and building `notcurses` inside a docker debian:unstable 
unstable=
```text
# cat /etc/debian_version
bullseye/sid
```

<details><summary>Here are my results</summary>

```text
root@c20cb1c56e70:/notcurses/build# ./notcurses-demo -p ../data
Term: 48x186 xterm (xterm terminal emulator (X Window System))

 notcurses 1.5.0 by nick black et al
  48 rows, 186 columns (139.50KiB), 8 colors (direct)
  compiled with gcc-9.3.0
  terminfo from ncurses 6.2.20200212
  avformat 58.29.100 avutil 56.31.100 swscale 5.5.100

 Warning! Advertised TrueColor but no 'ccc' flag

 Warning! Encoding is not UTF-8.

14281 renders, 33.59s total (235.43s min, 568.87ms max, 2.35ms avg)
125.65MiB total (0.00B min, 168.96KiB max, 9.01KiB avg)
425.2 theoretical FPS, 0 failed renders
RGB emits:elides: def 118143:44809 fg 599872:7688177 bg 6403843:1736646
 Elide rates: 27.50% 92.76% 21.33%
Cell emits:elides: 8303441/119277679 (93.49%)

              runtime│ frames│output(B)│rendering│ %r│    FPS│TheoFPS║
══╤═════════╤════════╪═══════╪═════════╪═════════╪═══╪═══════╪═══════╣
 0│    intro│  11.98s│      0│     0.00│    0.00s│  0│    0.0│    0.0║SKIPPED
 1│     xray│   5.05s│    302│   9.69Mi│ 670.94ms│ 13│   59.8│  450.1║
 2│    eagle│  20.61s│    534│  43.31Mi│    9.48s│ 45│   25.9│   56.3║
 3│ allglyph│  23.26s│      0│     0.00│    0.00s│  0│    0.0│    0.0║SKIPPED
 4│    yield│  10.88s│    788│ 663.32Ki│ 317.47ms│  2│   72.4│ 2482.1║
 5│    trans│  16.31s│    821│   3.67Mi│ 494.71ms│  3│   50.3│ 1659.6║
 6│  highcon│   2.86s│   4371│ 298.88Ki│    2.19s│ 76│ 1529.6│ 1993.0║
 7│   normal│   5.55s│    144│ 383.17Ki│  71.15ms│  1│   26.0│ 2023.9║
 8│      box│   3.85s│     51│   5.06Mi│ 203.92ms│  5│   13.2│  250.1║
 9│   chunli│   6.31s│    106│ 904.48Ki│  84.94ms│  1│   16.8│ 1248.0║
10│     grid│792.34ms│    768│  13.03Ki│ 266.58ms│ 33│  969.3│ 2880.9║
11│     reel│   5.07s│     29│   1.12Mi│  55.68ms│  1│    5.7│  520.8║
12│ whiteout│  27.90s│      0│     0.00│    0.00s│  0│    0.0│    0.0║SKIPPED
13│ uniblock│  25.61s│      0│     0.00│    0.00s│  0│    0.0│    0.0║SKIPPED
14│     view│  24.34s│    855│  55.18Mi│   16.70s│ 68│   35.1│   51.2║
15│    luigi│   2.65s│    438│   2.36Mi│ 326.12ms│ 12│  165.0│ 1343.1║
16│  sliders│   5.58s│    551│   1.33Mi│ 385.20ms│  6│   98.7│ 1430.4║
17│  fallin'│  12.08s│   4521│   1.70Mi│    2.34s│ 19│  374.2│ 1932.3║
18│   jungle│  49.11s│      0│     0.00│    0.00s│  0│    0.0│    0.0║SKIPPED
19│   qrcode│  21.29s│      0│     0.00│    0.00s│  0│    0.0│    0.0║SKIPPED
20│    outro│  21.00s│      0│     0.00│    0.00s│  0│    0.0│    0.0║SKIPPED
══╧═════════╪════════╪═══════╪═════════╪═════════╪═══╪═══════╪═══════╝
            │ 121.94s│  14279│ 125.64Mi│   33.59s│ 27│  117.1│
root@c20cb1c56e70:/notcurses/build#

```
</details>



<details><summary>Here's my Dockerfile I used</summary>

```Dockerfile
FROM debian:unstable

RUN apt update
RUN apt install -y python3 python3-pip gcc git vim bash bash-completion make cmake ncurses* libavformat-dev libswscale-dev libqrcodegen-dev pkg-config libavcodec-dev
RUN git clone https://github.com/dankamongmen/notcurses.git && mkdir /notcurses/build/

# v--- lol: not env vars, cmake options
#ENV USE_PANDOC="OFF"

WORKDIR /notcurses/build/
RUN cmake -D USE_PANDOC=OFF -D BUILD_TESTING=OFF .. && make
make test' returned a non-zero code: 2
RUN make install

CMD ["/bin/bash"]
```

</details>

-----
### Pre build thoughts 

I think you can add what are default options in the ReadMe 

## post build 

### make test

When I tried `make test` I got:
```text
make[1]: Leaving directory '/notcurses/build'
make: *** No rule to make target 'test'.  Stop.
The command '/bin/sh -c cmake -D USE_PANDOC=OFF -D BUILD_TESTING=OFF .. && make && make test' returned a non-zero code: 2
```

### Warnings

#### ccc

`Warning! Advertised TrueColor but no 'ccc' flag`
I used COLORTERM="24bit"
Inside my vm debian10.4 : echo $TERM = xterm-256color
inside my docker debian:unstable : echo $TERM = xterm

#### utf8
`Warning! Encoding is not UTF-8.`
I really don't know why I got this one.
Use utf-8 everywhere 🤷‍♀️

Do you know how I can remove them ?

**Comment by dankamongmen** [comment]
It's not gettign UTF8 presumably because you either 

(1) don't have the environment variable `LANG` set to something like `en_US.UTF-8` (insert your own country code), and/or
(2) you haven't generated the locale in your Dockerfile

if it's a Debian Docker, the easiest thing to do will be to run `dpkg-reconfigure locales` (install `locales` first if you don't have it). select the correct environment. for me this looks like:

![2020-06-10-190643_1144x1092_scrot](https://user-images.githubusercontent.com/143473/84327537-8c209b00-ab4d-11ea-9fdd-d00ad955257b.png)

next, you'll be able to set a default. select the UTF8 one. log back in and verify that export | grep LANG shows the following:

```sh
[schwarzgerat](0) $ export | grep LANG
declare -x LANG="en_US.UTF-8"
[schwarzgerat](0) $
```

you'll now have a working UTF8 locale.

**Comment by dankamongmen** [comment]
> Thank you for the instant reply
> 
> Ok so I finally figured out (x
> I almost never build stuffs but I'm glad I did : very nice demo haha
> 
> I am on windows using putty to a debian10.4 VM and building `notcurses` inside a docker debian:unstable
> unstable=
> 
> ```
> # cat /etc/debian_version
> bullseye/sid
> ```
> 
> Here are my results
> Here's my Dockerfile I used
> ### Pre build thoughts
> I think you can add what are default options in the ReadMe
> 
> ## post build
> ### make test
> When I tried `make test` I got:
> 
> ```
> make[1]: Leaving directory '/notcurses/build'
> make: *** No rule to make target 'test'.  Stop.
> The command '/bin/sh -c cmake -D USE_PANDOC=OFF -D BUILD_TESTING=OFF .. && make && make test' returned a non-zero code: 2
> ```
> 
> ### Warnings
> #### ccc
> `Warning! Advertised TrueColor but no 'ccc' flag`
> I used COLORTERM="24bit"
> Inside my vm debian10.4 : echo $TERM = xterm-256color
> inside my docker debian:unstable : echo $TERM = xterm
> 
> #### utf8
> `Warning! Encoding is not UTF-8.`
> I really don't know why I got this one.
> Use utf-8 everywhere 
> 
> Do you know how I can remove them ?

answered about UTF8 above. things will look a lot better once you do this, also (unless you're in console, where things can actually look worse -- for now. in a terminal in wayland/x, this will improve things muchly).

**Comment by dankamongmen** [comment]
and yeah, everything showing SKIPPED is being SKIPPED because you're in ASCII mode. switching to UTF8 must be done on a per-program basis, and is usually done by calling `setlocale(LC_ALL, "")`. this requires `LANG` to be set. and even if `LANG` is set, things are no good without the locale existing on disk.

be aware that the console has very limited font support for utf-8 (it can only load 256 glyphs in its font).

**Comment by dankamongmen** [comment]
Did that get the remaining demos working? Please close this bug if so =].

**Comment by thenger** [comment]
Sorry I struggled with the second warning. (I tired modify terminfo database which looks like it is not a good idea 🙃)

I managed to get it work together inside docker:
```Dockerfile

FROM debian:unstable

RUN apt update
RUN apt install -y python3 python3-pip gcc git vim bash bash-completion make cmake ncurses* libavformat-dev libswscale-dev libqrcodegen-dev pkg-config libavcodec-dev locales locales-all
RUN git clone https://github.com/dankamongmen/notcurses.git && mkdir /notcurses/build/

# Maybe some of these 5 lines are redundant didn't have time to check
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
RUN cat /etc/default/locale
RUN echo -e 'LANG="en_GB.UTF-8"\nLANGUAGE="en_GB:en"' > /etc/default/locale

WORKDIR /notcurses/build/
RUN cmake -D USE_PANDOC=OFF -D BUILD_TESTING=OFF .. && make
RUN make install
ENV COLORTERM=24bit
ENV TERM=xterm-256color

CMD ["/bin/bash"]
```
So.
My VM Debian:10.4 (not docker) already has TERM set to `xterm-256color` by Putty.
When I attach docker container using `docker run -ti` The TERM var is set to `xterm`.

From now on I'll try things with python.

Thank you a lot for your time and insights !
