### ISSUE TITLE
cmake caches negative qrcodegen.h lookup result

### ISSUE THREAD

**Issue by MaxBarraclough** [dankamongmen/notcurses#711]
CMake configuration fails on Ubuntu 20.04 AMD64.

I have installed the `libqrcodegen-dev` package. `/usr/include/qrcodegen/qrcodegen.h` exists but CMake fails to find it.

This is shown:

    USE_QRCODEGEN is active, but couldn't find qrcodegen.h

Also, I suggest the 'Building' section of the README.md should not say `cmake ..`, it should say `cmake -G "Unix Makefiles"`. To someone not already familiar with CMake, this should be clear.

**Comment by dankamongmen** [comment]
Thanks for the report, @MaxBarraclough ! I'll look into this ASAP. And I appreciate the suggestion--would you like to prepare it as a PR, so that you get credit for the change? If not, I'll do it myself.

**Comment by dankamongmen** [comment]
In the meantime, if you want to build without qrcode capability, you can provide `-DUSE_QRCODEGEN=off` to `cmake` (you probably already know this).

**Comment by dankamongmen** [comment]
FWIW, notcurses is only officially supported on Groovy Gorilla. focal is a reasonable enough target, though, so I'll try to get this working.

**Comment by dankamongmen** [comment]
Hrmmm, it's working fine for me on a 20.04 Docker:

```
root@37d651053d1a:~/notcurses/build# cmake ..
-- Requested multimedia engine: ffmpeg
-- Requested build mode: RelWithDebInfo
-- Checking for module 'libswscale>=5.0'
--   Found libswscale, version 5.5.100
-- Looking for qrcodegen/qrcodegen.h
-- Looking for qrcodegen/qrcodegen.h - found
CMake Error at CMakeLists.txt:384 (message):
  pandoc not found.  USE_PANDOC=OFF to disable.


-- Configuring incomplete, errors occurred!
See also "/root/notcurses/build/CMakeFiles/CMakeOutput.log".
See also "/root/notcurses/build/CMakeFiles/CMakeError.log".
root@37d651053d1a:~/notcurses/build#
```

hrmmm...

```
root@37d651053d1a:~/notcurses/build# apt show libqrcodegen-dev
Package: libqrcodegen-dev
Version: 1.5.0-2build1
Priority: optional
Section: universe/libdevel
Source: qr-code-generator
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Yangfl <mmyangfl@gmail.com>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 56.3 kB
Depends: libqrcodegen1 (= 1.5.0-2build1)
Homepage: https://github.com/nayuki/QR-Code-generator
Download-Size: 15.7 kB
APT-Manual-Installed: yes
APT-Sources: http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages
Description: QR Code generator library in multiple languages - C development headers

root@37d651053d1a:~/notcurses/build#
```

**Comment by dankamongmen** [comment]
Can you verify that `/usr/include/qrcodegen/qrcodegen.h` exists on your system?

```
root@37d651053d1a:~/notcurses/build# ls /usr/include/qrcodegen/qrcodegen.h
/usr/include/qrcodegen/qrcodegen.h
root@37d651053d1a:~/notcurses/build# sha256sum /usr/include/qrcodegen/qrcodegen.h
5cf3668ff08a12febbc9197f3895271106da4d7603b92c8ce6897566d7f6c980  /usr/include/qrcodegen/qrcodegen.h
root@37d651053d1a:~/notcurses/build#
```

**Comment by MaxBarraclough** [comment]
It seems the issue only occurs if `libqrcodegen-dev` is installed after having first run the CMake command. When CMake is re-run, it fails to detect the file.

The issue went away when I deleted the notcurses directory and re-extracted the tarball. Presumably there's an issue with the CMake cache/change-detection.

Regarding the readme change, I'll make a pull request soon.

![cmakeIssue](https://user-images.githubusercontent.com/1122128/84593362-c2a73000-ae43-11ea-978c-2f5243031ce2.png)

**Comment by dankamongmen** [comment]
Awesome, thanks for digging into this. Yeah, I've seen that behavior before, but when I tried to reproduce it, I wasn't able to. That's really annoying and I'm tempted to submit a pkg-config patch to libqrcodegen so that a sane interface can be used. I might very well do that. In the meantime, it probably deserves a FAQ entry. Feel free to include it in your PR =].

**Comment by dankamongmen** [comment]
BTW, looking at your output above, I'm hesitant to recommend behavior that is going to trigger a warning (and be illegal in the future)...

**Comment by dankamongmen** [comment]
Via the magic of `unset()`, we now remove the `HAVE_QRCODEGEN_H` variable from cache prior to the `check_include_file()` check. It now discovers libqrcodegen following an install *in media res*, at the cost of rerunning this check every time one runs cmake (though not make). I think that ought solve the issue. Marking closed.

**Comment by dankamongmen** [comment]
Verified that this resolved the issue on Ubuntu Focal.
