### ISSUE TITLE
notcurses++ isn't being compiled with the specified options

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#722]
In `CMakeLists.txt`, we have:

```
set(NCPP_COMPILE_OPTIONS
  -Werror=format-security
  -Wnull-dereference
  -Wmisleading-indentation
  -Wunused
  -Wpedantic
  -Wsuggest-override
  -Wno-c99-extensions
  -fno-strict-aliasing
  -ffunction-sections
  -funswitch-loops
  -finline-limit=300
  -fstack-protector
  -fno-rtti
  -fno-exceptions
  -fpic
  )
```

and then

```
target_compile_options(notcurses++
  PRIVATE
  ${NCPP_COMPILLE_OPTIONS}
  )

target_compile_options(notcurses++-static
  PRIVATE
  ${NCPP_COMPILLE_OPTIONS}
  )
```

alas, "compile" remains spelled with only a single 'L', and thus these compiler options have never, so far as I can tell, been applied. Removing the rogue 'L' results in massive compilation breakage. Let's either kill these options or actually use them. I'd probably accept a PR that fixed up `notcurses.h` to work with this (indeed, compiling it from C++ programs is a requirement, though not necessarily with these flags), but I'm disinclined to do that dirty work myself right at the moment.

**Comment by grendello** [comment]
Bummer... Typo + cut'n'paste... Fix coming up

**Comment by dankamongmen** [comment]
w00t thanks for the quick turnaround -- i hope this didn't sound bitchy; it was meant to sound amused! =] merging your PR shortly

**Comment by grendello** [comment]
Wasn't bitchy, no worries :)
