### ISSUE TITLE
Alpine Edge fails due to missing tinfo

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#734]
So far as I can tell, `libtinfo.so` does not exist on Alpine Linux, nor does a `tinfo` pkg-config entry. I'm not sure why they're different from every other Linux I'm aware of on this issue, but so it goes. On Alpine, we need check for `ncurses`, and link with that; it has subsumed `libtinfo`. Ugh. How do we detect distro in CMake? FML.

**Comment by dankamongmen** [comment]
It looks like we can solve this with `pkg_search_module()`. As JRO said, "when something's technically sweet, you go for it."

**Comment by dankamongmen** [comment]
See also #733.

**Comment by orgads** [comment]
Reported upstream: https://gitlab.alpinelinux.org/alpine/aports/-/issues/16434

**Comment by sertonix** [comment]
Citing from the arch package here ([link](https://gitlab.archlinux.org/archlinux/packaging/packages/ncurses/-/blob/6aca7831ad2e892867722905ece5df058a0bdeba/PKGBUILD#L98)):
> tic and ticinfo functionality is built in by default

Which means alpine is just packaging closer to upstream defaults than other distros do. So could the code comment please be corrected to something like `tinfo is bundled in by default. The library may or may not be separate`!

**Comment by dankamongmen** [comment]
are we failing to build on alpine? please reopen this if so.

**Comment by orgads** [comment]
No, you already fixed it. I just came across this issue because sipp cmake shows a warning when tinfo is not found.

**Comment by dankamongmen** [comment]
thanks for the clarification!
