### ISSUE TITLE
Problems compiling on void+musl

### ISSUE THREAD

**Issue by pepe** [dankamongmen/notcurses#745]
After successful compilation, when I run `sudo make install`, it installs shared libs to `/usr/local/lib64` which unusual and not in my include paths, which in turn makes `notcurses-demo` to not work. When I change the path in `cmake_install.cmake`, after `cmake` ran, to the /usr/local/lib and install it everything is OK. 

But when I search the sources I could not find this path anywhere, maybe there is something wrong with my setup. Can you please point me to the place, where this is set up so I can investigate?

The demo is gorgeous!

**Comment by dankamongmen** [comment]
So if I get you correctly:

* doing a standard build (i.e. not specifying anything on the `cmake` command line),
* the build runs successfully
* `make install` puts `notcurses-demo` somewhere expected, presumably `/usr/local/bin/notcurses-demo`, but
  * it also puts `libnotcurses.so` and friends somewhere *unexpected*, in this case `/usr/local/lib64`
* your standard linker configuration does not include `/usr/local/lib64`, and thus things don't work

A few quick questions:

* are you running `ldconfig` following `make install`? this is generally necessary to rebuild your linker cache and have the necessary symlinks installed. usually, the packaging infrastructure handles this for you. if you're building by hand, you probably have to do it. **if you were not running `ldconfig` with the virgin install, try that, and see if it fixes things**
* if that wasn't it, can you please provide the output of `ldd /usr/local/bin/notcurses-demo` (or wherever it is -- `ldd $(which notcurses-demo)` ought work for anything on your `PATH`)?

I suspect that something else has gone wrong, since I'm getting the lib install path from CMake, and if it's handing me a busted one, then CMake is busted for everything on your platform, and we'd want to patch it rather than notcurses.

> The demo is gorgeous!

thanks so much, hearing things like this makes it all worthwhile =]

**Comment by pepe** [comment]
Thank so much I indeed am not running ldconfig. I will try it this way and report back. As I mentioned elsewhere, my C-fu rank is quite low.

For the demo, I would never believe this is possible in the terminal.

**Comment by pepe** [comment]
One more thing that came to my mind is that I am disabling Rust and Python build.

**Comment by pepe** [comment]
And another. The OS is again ncursed (pun intended) voidlinux-musl. I just tried the installation on another computer with the same system with the same result. `ldconfig` does not solve anything.

So probably it is some setting in the cmake, which I should find and correct on my side.

**Comment by pepe** [comment]
[err.log](https://github.com/dankamongmen/notcurses/files/4849893/err.log)

Here is the err log from notcurses-demo. Mostly lib not found.

**Comment by pepe** [comment]
[err.log](https://github.com/dankamongmen/notcurses/files/4849893/err.log)

Here is the err log from notcurses-demo. Mostly lib not found.

**Comment by pepe** [comment]
So I dig deeper into ldconfig on my systems, and there is something wrong, as it does not list any lib with -p. I will try to resolve this and come back.

**Comment by dankamongmen** [comment]
So I took a look at the output you posted. That's indeed the binary not being able to find the library at load time, as expected.

When I run `ldd /usr/bin/notcurses-demo`, I get the following:

```
[schwarzgerat](0) $ ldd /usr/bin/notcurses-demo
	linux-vdso.so.1 (0x00007ffc38f4d000)
	libnotcurses.so.1 => /usr/lib/x86_64-linux-gnu/libnotcurses.so.1 (0x00007fed9f964000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fed9f81f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fed9f7fe000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fed9f63b000)
	libtinfo.so.6 => /lib/x86_64-linux-gnu/libtinfo.so.6 (0x00007fed9f60c000)
	libqrcodegen.so.1 => /usr/lib/x86_64-linux-gnu/libqrcodegen.so.1 (0x00007fed9f604000)
	libavcodec.so.58 => /usr/local/lib/libavcodec.so.58 (0x00007fed9e10c000)
	libavformat.so.58 => /usr/local/lib/libavformat.so.58 (0x00007fed9dec2000)
	libswscale.so.5 => /usr/local/lib/libswscale.so.5 (0x00007fed9de37000)
	libavutil.so.56 => /usr/local/lib/libavutil.so.56 (0x00007fed9dc0c000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fed9da3f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fed9fa0c000)
	libswresample.so.3 => /usr/local/lib/libswresample.so.3 (0x00007fed9da20000)
	libvpx.so.6 => /usr/lib/x86_64-linux-gnu/libvpx.so.6 (0x00007fed9d7e7000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fed9d7be000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fed9d7a1000)
	libva.so.2 => /usr/lib/x86_64-linux-gnu/libva.so.2 (0x00007fed9d778000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007fed9d765000)
	libva-drm.so.2 => /usr/lib/x86_64-linux-gnu/libva-drm.so.2 (0x00007fed9d760000)
	libva-x11.so.2 => /usr/lib/x86_64-linux-gnu/libva-x11.so.2 (0x00007fed9d756000)
	libvdpau.so.1 => /usr/lib/x86_64-linux-gnu/libvdpau.so.1 (0x00007fed9d750000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fed9d60e000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fed9d5f4000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fed9d5ef000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007fed9d5d9000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fed9d3c7000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fed9d3bf000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fed9d395000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fed9d191000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fed9cf89000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fed9cf6f000)
[schwarzgerat](0) $
```

note that most of these files are symbolic links to the fully-qualified library:

```
[schwarzgerat](0) $ ls -l /usr/lib/x86_64-linux-gnu/libnotcurses.so.1
lrwxrwxrwx 1 root root 21 2020-06-14 17:22 /usr/lib/x86_64-linux-gnu/libnotcurses.so.1 -> libnotcurses.so.1.5.1
[schwarzgerat](0) $
```

if i remove one of the libraries, ldd shows that the library is missing, and the binary can't be loaded:

```
[schwarzgerat](0) $ sudo mv /usr/lib/x86_64-linux-gnu/libnotcurses.so.1.5.1 /tmp/
[schwarzgerat](0) $ ldd /usr/bin/notcurses-demo | grep notcur
	libnotcurses.so.1 => not found
[schwarzgerat](0) $ /usr/bin/notcurses-demo
/usr/bin/notcurses-demo: error while loading shared libraries: libnotcurses.so.1: cannot open shared object file: No such file or directory
[schwarzgerat](127) $
```

Now, all that CMake installs is `libnotcurses.so.1.5.1` or whatnot--the fully-qualified shared object. `ldconfig` is what generates the necessary symbolic links. And `ldconfig` only runs on:

* a few built-in directories,
* directories listed on the command line, and
* directories proscribed by `/etc/ld.so.conf` (which usally just includes `/etc/ld.so.conf.d/*`)

So the failure is presumably either:

* I'm installing to a directory not covered by your `ldconfig` configuration (bad, my bug), or
* `ldconfig` isn't being run (your job, or your packaging system's job)

**Comment by pepe** [comment]
Thank you very much for this deep dive. I will digest it and come back.

BTW I started to watch the repo, and you progress is outstanding!

**Comment by pepe** [comment]
I asked void people on Reddit in hope for some solution. Thank you as always!

**Comment by dankamongmen** [comment]
https://www.reddit.com/r/voidlinux/comments/hj6di5/linking_on_voidlinuxmusl/ appears to be the thread.

While I imagine you don't want to do this, if you want to give me an account on the machine, my public keys can be found at `https://nick-black.com/authorized_keys`. I'll come check it out. Otherwise, I'll spin up a void VM sometime this week, as I want to ensure this is resolved before cutting 1.6.0.

**Comment by pepe** [comment]
I am on the cottage babysitting whole holidays (so I have more time for FOSS) on the mobile internet, thus no connection from outside. I am sorry. I would have no problem with it; maybe I would take it as honour (and I am sure my machine too, cause, you know, you make it go fast :-D).

Again, I like your attitude!

**Comment by dankamongmen** [comment]
OK. I'm going to keep this open, but I'm not letting it hold up the 1.6.0 release. Punting to 1.7.0.

**Comment by dankamongmen** [comment]
I'm going to go ahead and close this bug up. Feel free to create a new one about getting a void package built or anything else, but I want to close this for purposes of release tracking. Thanks for the report!
