### ISSUE TITLE
Make a Gentoo ebuild

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#746]
Looking at repology.org, Gentoo seems the next distro to target for inclusion. Get an Ebuild prepped up.

**Comment by dankamongmen** [comment]
https://wiki.gentoo.org/wiki/Submitting_ebuilds

**Comment by dankamongmen** [comment]
I've stood up a Gentoo environment. We built pretty easily with `cmake` and `ffmpeg` plus `-DUSE_DOCTEST=off -DUSE_QRCODEGEN=off -DUSE_PANDOC=off`. qrcodegen and doctest don't appear to be available in Gentoo. pandoc didn't want to install on amd64 for who knows what reason. Notcurses then builds without complaints/warnings, and `notcurses-demo` works just fine. Let's roll an ebuild!

**Comment by dankamongmen** [comment]
Fortune smiles upon thee, DANK! One less stupid shitty thing you don't have any idea how to do!

```
daf3e2fda3f8 /var/db # pwd && cat repos/notcurses/notcurses-2.1.8.ebuild compile/var/db
# Copyright 2021 Nick Black <nickblack@linux.com>
# Distributed under the terms of the GNU General Public License v2

EAPI=7

inherit cmake

DESCRIPTION="A blingful library for TUIs and character graphics"
HOMEPAGE="https://nick-black.com/dankwiki/index.php/Notcurses"
SRC_URI="https://github.com/dankamongmen/notcurses/archive/v2.1.8.tar.gz"

LICENSE="Apache-2.0"
SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND="${DEPEND}"
BDEPEND=""

src_prepare() {
  cmake_src_prepare
}

src_configure() {
  local mycmakeargs=(
    -DUSE_DOCTEST=off
	-DUSE_PANDOC=off
	-DUSE_QRCODEGEN=off
  )
  cmake_src_configure
}
cat: compile: No such file or directory
daf3e2fda3f8 /var/db # 
```

this at least builds when we run `ebuild compile`.

**Comment by dankamongmen** [comment]
Looks like it packages everything up, too. w00t!

Let's do the necessary basic culling and enhancing. We need establish deps on ffmpeg / readline / unistring / ncurses, of course, and probably tie those into the general `USE` flags.

**Comment by dankamongmen** [comment]
Implement `info` with `pkg_info()`, it appears

**Comment by dankamongmen** [comment]
```
07ae97526b60 /var/db/repos/my-local-portage/dev-cpp/notcurses # cat notcurses-2.2.1.ebuild 
# Copyright 2021 nick black
# Distributed under the terms of the GNU General Public License v2

EAPI=7

CMAKE_ECLASS="cmake"
inherit cmake-multilib

DESCRIPTION="Blingful TUIs and character graphics"
HOMEPAGE="https://notcurses.com"
SRC_URI="https://github.com/dankamongmen/notcurses/archive/v2.2.1.tar.gz"

LICENSE="APACHE-2.0"
SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND="app-text/pandoc dev-libs/unistring media-video/ffmpeg sys-libs/readline"
RDEPEND="${DEPEND}"
BDEPEND=""

src_prepare() {
	cmake_src_prepare
}

src_configure() {
	local mycmakeargs=(
		-DUSE_DOCTEST=OFF
		-DUSE_QRCODEGEN=OFF
		-DUSE_PANDOC=OFF
	)
	cmake-multilib_src_configure
}

src_compile() {
	cmake-multilib_src_compile
}

src_test() {
	multilib_src_test
}
07ae97526b60 /var/db/repos/my-local-portage/dev-cpp/notcurses # 
```

**Comment by dankamongmen** [comment]
https://bugs.gentoo.org/769875

**Comment by dankamongmen** [comment]
https://github.com/gentoo/gentoo/pull/19402

**Comment by dankamongmen** [comment]
hey @igo95862 @joseluis @grendello , I can apparently put several translations into ebuild metadata, so if y'all want to translate the following, go for it and i'll add it:

```
<longdescription>
 Notcurses facilitates the creation of modern TUI programs,
 making full use of Unicode and 24-bit TrueColor. It presents
 an API similar to that of Curses, and rides atop Terminfo.
</longdescription>
```

**Comment by dankamongmen** [comment]
We're warning-free in our ebuild now, just waiting for a merge!

**Comment by dankamongmen** [comment]
We got approval!

**Comment by joseluis** [comment]
En español:

Notcurses facilita la creación de programas TUI actuales,
haciendo un uso completo de Unicode y color real de 24 bits.
Presenta una API similar a la de Curses y funciona sobre Terminfo.

**Comment by dankamongmen** [comment]
> Notcurses facilita la creación de programas TUI actuales,
> haciendo un uso completo de Unicode y color real de 24 bits.
> Presenta una API similar a la de Curses y funciona sobre Terminfo.

added! es bonito!

**Comment by dankamongmen** [comment]
I've updated the ebuild to 2.2.2. just waiting on a merge (it's already approved).

**Comment by dankamongmen** [comment]
got another round of feedback which i'll need address

**Comment by dankamongmen** [comment]
We're just about done, supposedly. I need to expose the FFmpeg/OIIO/none choice in Gentoo language, and unconditionally install man pages from the doc package, which also needs be rebuilt -- it apparently contains objects?!

**Comment by dankamongmen** [comment]
Alright, I've done that work, and hopefully we'll get merged soon.

**Comment by dankamongmen** [comment]
....and we are now in Gentoo =].

**Comment by dankamongmen** [comment]
and we got LiGurOS for free, whatever that is! neat =]
