### ISSUE TITLE
Build doctest+notcurses for EPEL7/EPEL8

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#851]
We want both doctest and notcurses in EPEL8, so we should get on that ASAP.

**Comment by dankamongmen** [comment]
Doctest is now being built. I've requested a branch for notcurses.

**Comment by dankamongmen** [comment]
Notcurses in EPEL8 will require `python-pypandoc` and `libqrcodegen-dev`.

**Comment by dankamongmen** [comment]
https://src.fedoraproject.org/rpms/python-pypandoc  (maintainer: https://admin.fedoraproject.org/accounts/user/view/zbyszek)
https://src.fedoraproject.org/rpms/qr-code-generator (maintainer: https://admin.fedoraproject.org/accounts/user/view/xvitaly)

Hah, I know xvitaly; I bet he'll be happy to do qr-code-generator. I've mailed zbyszek as well.

**Comment by dankamongmen** [comment]
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.14 or higher is required.  You are running version 3.11.4

ugh!

**Comment by dankamongmen** [comment]
I have set our minimum CMake version to 3.11.4 in `dankamongmen/reel-talk-about-reels`. Let's see if it works. AFAIK, 3.14 was an arbitrary decision based off what was in Debian Unstable at the time.

**Comment by dankamongmen** [comment]
Vitaly has built qr-code-generator for EPEL8: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-2ad7a8c5e4

And in a strange turn of events, I'm now a Fedora maintainer for python-pypandoc.

**Comment by dankamongmen** [comment]
Requested an EPEL8 branch for `python-pypandoc`: https://pagure.io/releng/fedora-scm-requests/issue/27423

**Comment by dankamongmen** [comment]
it looks like `python-pypandoc` will require `pandoc-citeproc`:

```
DEBUG util.py:793:  child environment: None
DEBUG util.py:719:  Executing command: ['/usr/bin/dnf', 'builddep', '--installroot', '/var/lib/mock/epel8-playground-build-22053019-1854279/root/', '--setopt=install_weak_deps=0', '--disableplugin=local', '--disableplugin=spacewalk', '/var/lib/mock/epel8-playground-build-22053019-1854279/root//builddir/build/SRPMS/python-pypandoc-1.5-3.epel8.playground.src.rpm', '--setopt=tsflags=nocontexts'] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/var/lib/mock/epel8-playground-build-22053019-1854279/root/installation-homedir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8', 'LC_MESSAGES': 'C.UTF-8', 'LD_PRELOAD': '/var/tmp/tmp.mock.ewtm6pt2/$LIB/nosync.so'} and shell False
DEBUG util.py:621:  No matches found for the following disable plugin patterns: local, spacewalk
DEBUG util.py:621:  No matching package to install: 'pandoc-citeproc'
```

**Comment by dankamongmen** [comment]
I have mailed jens, the maintainer of `pandoc-citeproc`, and requested an EPEL8 build.

**Comment by dankamongmen** [comment]
Haven't heard back from jens yet. We could package for EPEL8 now though, if we left out man pages.

**Comment by dankamongmen** [comment]
And I think that's actually only used for the `notcurses-pydemo.1` man page. We can still build most of them.

**Comment by dankamongmen** [comment]
I have better ways to spend my life than fucking with old versions of CMake. Restore our old minimum CMake version, and consign this idea to the heap of idle hopes and dashed dreams.

**Comment by dankamongmen** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1858941 EPEL 8.4 will have a new CMake, it appears, though it won't be released until October.

**Comment by dankamongmen** [comment]
Still running into:

```
+ /usr/bin/cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -DUSE_MULTIMEDIA=oiio -DDFSG_BUILD=on -DUSE_QRCODEGEN=off .
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.14.0 or higher is required.  You are running version 3.11.4
-- Configuring incomplete, errors occurred!
```

https://koji.fedoraproject.org/koji/taskinfo?taskID=53505728

**Comment by dankamongmen** [comment]
We can go back to CMake 3.13.0 if we drop `NAME_WLE`, which can be accomplished with `-DUSE_PANDOC=off -DUSE_STATIC=off`. Not sure if there are other problems on the way back to 3.11.4, though.

**Comment by dankamongmen** [comment]
Cmake 3.13.0 added `target_link_directories()`, which we use. 3.12 added `CONFIGURE_DEPENDS`, which we use extensively. Bleh.

**Comment by dankamongmen** [comment]
```
Carl George 🤠 2020-09-26 04:08:20 UTC
A non-modular cmake-3.18.2-7.el8 has been pushed to git.centos.org [0].  This is planned to be included in RHEL 8.4, and will be published in CentOS Stream soon.  Adding any kind of modular or non-modular cmake to EPEL 8 doesn't make any sense at this point, so I'm going to go ahead and close this bug out.

https://git.centos.org/rpms/cmake/c/09b85a86fd26251b569658b4ecb5db9ace298606?branch=c8s
```

**Comment by dankamongmen** [comment]
> ```
> Carl George 🤠 2020-09-26 04:08:20 UTC
> A non-modular cmake-3.18.2-7.el8 has been pushed to git.centos.org [0].  This is planned to be included in RHEL 8.4, and will be published in CentOS Stream soon.  Adding any kind of modular or non-modular cmake to EPEL 8 doesn't make any sense at this point, so I'm going to go ahead and close this bug out.
> 
> https://git.centos.org/rpms/cmake/c/09b85a86fd26251b569658b4ecb5db9ace298606?branch=c8s
> ```

8.3 was released just 4 days ago, 2020-10-29. We might get 8.4 in a few months. We're not worrying about this until we get 8.4, at which point it ought be easy.

**Comment by h1z1** [comment]
Curious, did you run into issues with libunistring?

https://github.com/dankamongmen/notcurses/commit/604747c8f2ed7506484b4b8fda24b13ee2828ee3#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR89  added a check for uniwbrk.h, and states 0.9.10+ is required, but doesn't actually check what version is found just that one header is.

The build fails though because it requires another header from libunistring that was added later

```
[  0%] Building C object CMakeFiles/notcurses.dir/src/lib/blit.c.o
In file included from /dev/shm/notcurses/src/lib/internal.h:41:0,
                 from /dev/shm/notcurses/src/lib/blit.c:2:
/dev/shm/notcurses/src/lib/egcpool.h:12:21: fatal error: unigbrk.h: No such file or directory
 #include <unigbrk.h>
```

unigbrk.h was added in 0.9.4.   Don't know what other distros have but CentOS 7 at least shipped with 0.9.3.  Yes, it's old... very old. Stupid old.

**Comment by dankamongmen** [comment]
> [604747c#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR89](https://github.com/dankamongmen/notcurses/commit/604747c8f2ed7506484b4b8fda24b13ee2828ee3#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR89) added a check for uniwbrk.h, and states 0.9.10+ is required, but doesn't actually check what version is found just that one header is.

hey there, friend! i listed 0.9.10 as a requirement because that is the oldest version i've tested with. notcurses may well be able to use older versions.

> The build fails though because it requires another header from libunistring that was added later
> unigbrk.h was added in 0.9.4. Don't know what other distros have but CentOS 7 at least shipped with 0.9.3. Yes, it's old... very old. Stupid old.

i'd be interested in supporting centos7, especially if you're in a position to validate it (if not, i can VM up a centos7 box, but it would be low on my priorities). if you'd like, please file a bug requesting libunistring 0.9.3 support, and i'll look into whether it can be done.

0.9.3 was...2010!?!?!?! so that's unicode 6.0 support at best. hmmmm. well, i'm happy to take a stab at it.

**Comment by h1z1** [comment]
Yeah it's bizarre and pretty old but I can't find when uniwbrk.h was even added.  I'm sure it's burred in their svn or something but the gnu archives don't go back far enough.   Spose a option is shipping the header?

I can of course build the lib from source wasn't sure if there was a reason that version was chosen *shrug*

**Comment by dankamongmen** [comment]
> Yeah it's bizarre and pretty old but I can't find when uniwbrk.h was even added. I'm sure it's burred in their svn or something but the gnu archives don't go back far enough. Spose a option is shipping the header?
> 
> I can of course build the lib from source wasn't sure if there was a reason that version was chosen _shrug_

let's not go adding headers :). there's no guarantee that such a header represents the library installed. if 9.0.3 supports all necessary functionality, i'd want to just change our check in CMake to look for some other, common header.

iirc, i can't check the version of libunistring because it doesn't install a pkg-config .pc file.

but yeah, i just put down 9.0.10 because i know we work with 9.0.10. i'm not aware of any reason why we wouldn't work with older ones.

**Comment by h1z1** [comment]
Re API yeah, I meant from an intree build but that could break other things too.  

FWIW they don't ship any pkg-config at all though it uses autoconf.  Guessing it's just that old.   Could check for unistring/version.h and _LIBUNISTRING_VERSION.

**Comment by dankamongmen** [comment]
from source i can, but not (easily) from CMake, though i suppose so long as we error out it doesn't really matter. either way, i'd prefer a behavior-based check, since i don't intend to go test with four thousand versions of GNU libunistring =]

**Comment by h1z1** [comment]
Hopefully they didn't change anything else

CMake can, not sure how portable it is nor when the module was added.

ex

```
include(CheckPrototypeDefinition)
...

check_prototype_definition("extern void ulc_wordbreaks (const char *s, size_t n, char *p)", "NULL", "uniwbrk.h", HAVE_UNIWBRK_H)
check_prototype_definition("extern void  ulc_grapheme_breaks (const char *s, size_t n, char *p)","NULL", "unigbrk.h", HAVE_UNIGBRK_H)
```

**Comment by dankamongmen** [comment]
this is a good point

**Comment by dankamongmen** [comment]
I've now got a doctest epel7 package, queued for inclusion.

I'm able to get notcurses up through to cmake in epel7, at which point it can't find ncurses(?). Need to look into this more, but an epel7 package seems possible in the near future.

**Comment by dankamongmen** [comment]
Readline is 6.2. OpenImageIO is 1.5. NCURSES is 5.9. Unistring is 0.9.3. old, old, old. Most of these `-devel` packages lack pkgconfig files, let alone CMake modules. No `uc_is_grapheme()` in Unistring. This stuff is all too old. We're not wasting any more time on this. If EPEL8 ever gets a newer CMake, give me a call.

**Comment by dankamongmen** [comment]
holy fucking shit i built an epel8 package.

https://koji.fedoraproject.org/koji/taskinfo?taskID=70744034
