### ISSUE TITLE
Discussing the Rust port of the static inline functions

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#861]
Related: #800 

I'm opening this issue to discuss the different possibilities that can come up, regarding how close to the original way of doing things make these Rust functions and how welcomed are the deviations.

In general I believe the best would be to remain very close to the original functions. Except when using the type system can save runtime checkings and error returns.

### type aliases

First of all, I'd start using type aliases to leverage the type system guarantees. E.g.:
```rust
pub type Channel = u32;
```

### r g b components

Right now are treated as u32 and checked for overflow. But if we alias them as `type Component = u8` we no longer need to do runtime checks.

E.g. `channel_set_rgb()`, `channels_set_fg_rgb()` and `channels_set_bg_rgb()` can no longer fail, and `channel_set_rgb_clipped()`, `channels_set_fg_rgb_clipped()` and `channels_set_bg_rgb_clipped()` should no longer be necessary.

### alpha component

This one is a bit trickier. For now I've basically tried to diverge the least from the original C source code. I.e.:

```rust
type IntResult = i32
pub type Alpha = u32;

pub fn channel_alpha(channel: Channel) -> Alpha {
    channel & ffi::NCCHANNEL_ALPHA_MASK
}

pub fn channel_set_alpha(channel: &mut Channel, alpha: Alpha) -> IntResult {
    if (alpha & !ffi::NCCHANNEL_ALPHA_MASK) != 0 {
        return -1;
    }
    *channel = alpha | (*channel & !ffi::NCCHANNEL_ALPHA_MASK);
    if alpha != ffi::CELL_ALPHA_OPAQUE {
        *channel |= ffi::CELL_BGDEFAULT_MASK;
    }
    0
}
```

This means the alpha functions remains as the only ones that can return an error (for what I've seen so far). But that should be easily fixable. I'm very tempted to change them like this, but I wanted to check with you first:

```rust
pub type Alpha = u8;

pub fn channel_alpha(channel: Channel) -> Alpha {
    ((channel & ffi::NCCHANNEL_ALPHA_MASK) >> 28) as Alpha
}

pub fn channel_set_alpha(channel: &mut Channel, alpha: Alpha) {
    let mut a = alpha;
    if alpha > (ffi::NCCHANNEL_ALPHA_MASK >> 28) as u8 {
        a = ffi::CELL_ALPHA_OPAQUE as u8;
    }
    *channel = (a as u32) << 28 | (*channel & !ffi::NCCHANNEL_ALPHA_MASK);
    if a != ffi::CELL_ALPHA_OPAQUE as u8 {
        *channel |= ffi::CELL_BGDEFAULT_MASK;
    }
}
```
Where if alpha overflows the value is converted to 0 (OPAQUE), which it's probably better than converting it to HIGHCONTRAST.

what do you think @dankamongmen?

**Comment by joseluis** [comment]
Here is what I've done so far: [channels.rs](https://github.com/joseluis/notcurses/blob/static-inline-fn/rust/notcurses/src/channels.rs)

**Comment by dankamongmen** [comment]
everything i see here, within the scope of my understanding, is exactly what i want. i'd like to see things stay as close to the defined functions as possible, and have them enter the Rust typing system and leave `unsafe` as quickly as possible. everything here is reasonable for inclusion in `libnotcurses-sys`. the `notcurses` crate sits atop this and should IMHO be the location of all code beyond the declared notcurses API. i.e. `libnotcurses-sys` is tight `unsafe` wrappers, type promotion, and ideally pure rust implementations of `static inline` elements of the C api.

error handling seems a very controversial topic in the rust world. what you propose is what i would default to. so yeah, this all sounds great. hack on.

**Comment by joseluis** [comment]
Oh I think you're right, I should probably move the `channels.rs` file to the libnotcurses-sys crate, beacuse I added it to the notcurses crate...

**Comment by joseluis** [comment]
Done. Now this way is much better organized indeed. I don't know what I was thinking...

**Comment by dankamongmen** [comment]
BTW regarding "Blessings", watch out for:

https://github.com/erikrose/blessings
https://github.com/chjj/blessed

**Comment by joseluis** [comment]
Ouch, oh well, thanks for the tip.

I thought that it was the perfect name with a play on words, and so lucky to be available in the Rust repository.

Here are options I like:
1. notblesses
2. notcurses-rs
3. notnotcurses

Do you have any favorite?
