### ISSUE TITLE
make the rust library compatible with no_std

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#872]
I've created the branch `rust-no_std` for this, which already works, and is almost finished.
The only block that remains is https://github.com/Amanieu/cstr_core/issues/4 for which I already sent a PR.

Making the library compatible with no_std has no real disadvantages and increases its compatibility with many more projects that couldn't embed the standard library.

**Comment by dankamongmen** [comment]
Awesome, I'd figured `no-std` would be a much more difficult goal.

**Comment by joseluis** [comment]
Yeah me too, it turns out it was easier than I thought
