### ISSUE TITLE
Maybe consider changing the licence of the Rust crate to exactly the same as Rust

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#874]
Which is a [dual licence Apache 2.0/MIT](https://www.rust-lang.org/policies/licenses).

I think the technical differences are minimal, but it could make it easier for business to decide to use it if they're already using Rust, since it would ease out any licence compatibility related concerns.

**Comment by dankamongmen** [comment]
I'd like to read up a little bit about the effects of dual-licensing, but I explicitly chose a non-viral, permissive license for easy business use, and as far as I'm aware, MIT works largely the same way.

We'd need @grendello to buy in. No one else has significant code present.

The one annoyance here is that Debian is very strident about copyrights and such, and I'll need to ensure there's a way to easily indicate a duallicense within their machine-readable copyrights system. Possible gains are not worth having to have another fight with the Debian FTPmasters. With that said, I'm sure plenty of people are already doing this, so I expect no issues.

**Comment by dankamongmen** [comment]
Oh, wait, we're only talking about the rust crate? Yeah that's fine I'm down for changing that, and @grendello has no code there. As for the overall project, I think I'd prefer to keep it as it is. If I have to wonder about the effects of dual-licensing myself, that's definitely one more thing that must be explained to a Free Software-fearing boss, IMHO. I'd like to keep that licensing story as simple as possible.

Feel free to seed the new notcurses 2.0 crate with a dual license. I'm thinking libnotcurses-sys can also change without problems, since it's not yet packaged up anywhere.

**Comment by joseluis** [comment]
> Oh, wait, we're only talking about the rust crate?

Yes! sorry I just put the label and forgot to mention it.

> Yeah that's fine I'm down for changing that, and @grendello has no code there.

Fantastic

> As for the overall project, I think I'd prefer to keep it as it is.

Of course, that's what I'd do too.


> Feel free to seed the new notcurses 2.0 crate with a dual license. I'm thinking libnotcurses-sys can also change without problems, since it's not yet packaged up anywhere.

Ok!

**Comment by dankamongmen** [comment]
Looks to me like this has been accomplished; I see two LICENSE files in `notcurses-rs`, and `license = "MIT OR Apache-2.0"`.

Thanks @joseluis !

**Comment by joseluis** [comment]
@dankamongmen I'm reopening this issue because we forgot to dual license the libnotcurses-sys crate. :sweat_smile: 

> I'm thinking libnotcurses-sys can also change without problems, since it's not yet packaged up anywhere.

I'm just checking whether this could be a problem. And does it mean we must wait for 2.3.0 or even for 3.0 for a license change.

**Comment by dankamongmen** [comment]
> @dankamongmen I'm reopening this issue because we forgot to dual license the libnotcurses-sys crate. 
> 
> > I'm thinking libnotcurses-sys can also change without problems, since it's not yet packaged up anywhere.
> 
> I'm just checking whether this could be a problem. And does it mean we must wait for 2.3.0 or even for 3.0 for a license change.

i don't see any problems, no.

**Comment by joseluis** [comment]
Ok, fixed in https://github.com/dankamongmen/notcurses/commit/a38ccc40257ba7c0d67660f491ab6252f242d0a1
