### ISSUE TITLE
can we not overlay palette-indexed colors atop rgb, given selection bits?

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#884]
As I recall, there are two bits governing color type selection:

 * `NOT_DEFAULT` must be set, or else the channel is assumed to be the default color
 * `PALETTE_COLOR` must **not** be set in this case, or else the channel is RGB color
 * otherwise, it is palette color

why do we ever need to keep both the RGB and palette index live at the same time? why can't we just overlay palette index atop the rgb bits? 8 of the 24 would suffice. i seem to recall wanting to be able to keep both around, but can't remember why, and it would be a fine thing indeed to reclaim 16 bits of the attrword.

**Comment by dankamongmen** [comment]
If we *could* do this, then we can harvest the eight most significant bits of the attrword as a last-ditch NUL terminator (i.e. they are always zeroes, or at least for any inlined EGC, see #830), which would rescue the entire inlined-EGC idea from the performance brick wall it hit when we started having to `strndup()` out every inlined EGC.....yessssssssssss

**Comment by dankamongmen** [comment]
I've made this change in trunk, and it looks good! I'm only worried because this seems to have been a weird way to do things in the first place, and surely I had a good reason for such cavalier wastage of 1/8 of our `Cell` structure?

**Comment by joseluis** [comment]
Very good!

I'll have to study the changes to this structure, I'm still going throught the awesomely detailed info on types you sent me. You can see the progress in: https://github.com/dankamongmen/notcurses/blob/master/rust/src/types.rs

**Comment by dankamongmen** [comment]
> I'll have to study the changes to this structure, I'm still going throught the awesomely detailed info on types you sent me. You can see the progress in: https://github.com/dankamongmen/notcurses/blob/master/rust/src/types.rs

mainly head-down at professional work today, but giving this the old side-eye, it looks great
