### ISSUE TITLE
found weird print & styling  behaviour in direct mode

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#890]
I've just created the example [`direct-text.rs`](https://github.com/dankamongmen/notcurses-rs/blob/master/examples/direct-text.rs) on the high-level wrapper, and it's interesting that italic style don't work, except when I pass `NCSTYLE_MASK` to `ncdirect_styles_off()`. I prefer to tell you now in case this is related with the recent cell structure changes.

![imagen](https://user-images.githubusercontent.com/5832068/90246388-d6b3e180-de34-11ea-85b5-5b774cf617b5.png)

I've not yet investigated where this is coming from, I'll try to dig later into this.

I also encountered other shenanigans like `ncdirect_bg` and `ncdirect_bg` not working for me (may be my fault), and when calling `ncdirect_putstr` and then rust's `println!` it gets printed in the previous row, (instead of on the same row, and if adding an extra newline it then gets printed in the next row...

**Comment by dankamongmen** [comment]
I doubt it's tied to recent changes (possible) -- remember, those haven't been merged, so you shouldn't see them unless you're in my branch, or merged it into yours. This is `xfce4-terminal`, right?

These are likely just dumb bugs of mine because `ncdirect` has never seen much attention. I ought be able to knock them out early today unless they're unexpectedly mysterious. Thanks for the report!

**Comment by dankamongmen** [comment]
```
    /// Turns off all the styling
    pub fn styles_off_all(&mut self) -> Result<(), NcError> {
        unsafe {
            if nc::ncdirect_styles_off(self.data, nc::NCSTYLE_MASK) < 0 {
                return Err(NcError::GenericError);
            }
        }
        Ok(())
```

ok, yeah, i see the reason why the italic is staying on -- my bug -- and am looking at the rest.

**Comment by dankamongmen** [comment]
just for my sanity can you please provide the output of `infocmp | egrep ton\|toff\|sgr`? it ought have a form similar to the following:

[schwarzgerat](1) $ infocmp | egrep ton\|toff\|sgr
	am, bce, ccc, mir, msgr, xenl,
	sgr=\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p5%t;2%;%?%p7%t;8%;%?%p1%p3%|%t;7%;m%?%p9%t\016%e\017%;,
	sgr0=\E[0m\017, sitm=\E[3m, smacs=^N, smam=\E[?7h,
[schwarzgerat](0) $

**Comment by dankamongmen** [comment]
Your italics problem ought be resolved in head.

**Comment by dankamongmen** [comment]
As for your reordering issues (2 vs 1), that's surely due to c standard I/O buffering interacting unfortunately with rust's own I/O. flushing at the end of `putstr()` would prevent this, but i'm not sure we want to flush every time `putstr()` is called. let me think about this (feel free to relay your own thoughts!).

but your italics ought work.

**Comment by joseluis** [comment]
> can you please provide the output of infocmp | egrep ton\|toff\|sgr\|sitm\|ritm? it ought have a form similar to the following:

$ infocmp | egrep ton\|toff\|sgr\|sitm\|ritm
	am, bce, ccc, km, mc5i, mir, msgr, npc, xenl,
	ri=\EM, rin=\E[%p1%dT, ritm=\E[23m, rmacs=\E(B,
	sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p5%t;2%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
	sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h

**Comment by dankamongmen** [comment]
behold lovely direct mode italics going off and on as opposed to only on

![2020-08-14-083648_722x1417_scrot](https://user-images.githubusercontent.com/143473/90249970-575ce880-de09-11ea-8541-d008ec4e6f88.png)

**Comment by dankamongmen** [comment]
gotta do paying work for a bit, but this all ought be resolved sometime today, rien n'est simple, mais tout est facile...

**Comment by joseluis** [comment]
Oh I forgot to tell you italic works well now. I still not fully understand the relationship between bold and italics though. Gotta do more tests

**Comment by dankamongmen** [comment]
The `trans` demo uses some bold+italic, fwiw. Looking into your other issue now.

**Comment by dankamongmen** [comment]
I can't seem to download direct-text.rs anymore from this bug :/.

**Comment by dankamongmen** [comment]
Here, I'm gonna mark this closed regarding the styling transitions. Open a new one on the reordering, s'il vous plaît.
