### ISSUE TITLE
palette_size() should probably return unsigned

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#891]
also in the underlying `tcache.colors`...

right now they return int, but the value couldn't possible be negative, right?

**Comment by dankamongmen** [comment]
Is there any error case? If not, unsigned is good with me.

As you may or may not be aware, doing so is slightly unidiomatic C. Idiomatic C (as seen in both K&&R and Stroustrup) tends to use unsigned only when the extra values are needed. There's a plausible argument here in that unsigned has more rigorous specifications regarding behavior under overflow, etc., and thus int can be faster. I don't really buy it.

If there are no error cases to indicate via sentinel -1, I concur.

**Comment by dankamongmen** [comment]
why is `colors` int in `struct tinfo`? this ought return whatever type that is, which is currently `int`.
