### ISSUE TITLE
Can't publish libnotcurses-sys crate

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#898]
while attempting to publish the 1.6.13 crate, i got:

```
[schwarzgerat](0) $ cargo publish
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `cstr_core` does not specify a version
Note: The published dependency will use the version from crates.io,
the `git` specification will be removed from the dependency declaration.
[schwarzgerat](101) $
```

**Comment by joseluis** [comment]
you can publish it now! the dependency finally got updated few days ago, and I just made the necessary update

**Comment by dankamongmen** [comment]
awesome, thanks! gonna put 1.6.15 out the door. 1.6.13 and 1.6.14 were both failed releases due to my favorite thing in the world, python wrappers
