### ISSUE TITLE
functions that modify the received value and also return it

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#911]
Functions that does that: `channels_set_fchannel`, `channels_set_bchannel`, `channels_set_fg_default` and `channels_set_bg_default`.

Functions that doesn't: `channels_set_fg_alpha`, `channels_set_bg_alpha`, `channels_set_fg_rgb` and `channels_set_bg_rgb`.

I wonder why. To me right now it feels somewhat inconsistent and confusing.

**Comment by dankamongmen** [comment]
These are exactly the kinds of diversions from orthogonality that I want to normalize by 2.0 (see #627), so thanks for filing them. Let me look into these.

**Comment by dankamongmen** [comment]
`channels_set_*channel`: takes channel, returns channels
`channels_set_*g_alpha`: takes alpha, returns success or failure
`channels_set_*g_rgb`: takes rgb, returns success or failure
`channels_set_*g_default: takes channels, returns channels

so what's going on here is that those which need to indicate success or failure do so using the return value. those which can only succeed return the modified VR [0] parameter so that it can be further used without needing a new statement. for example:

`uint64_t c2 = channels_set_fchannel(&c1, fchan);`

they could return void, but why waste a perfectly good lvalue? the one downside is you can't mechanically churn out

```
if(channels_set_fg_rgb()){ errorpath; }
if(channels_set_fg_alpha()){ errorpath; }
```

and if you try, things will break at runtime (whereas if we returned void, the compiler would throw an error). i have limited sympathy for such a case, though.

please mark this closed/NONFIX unless you have further comments/suggestions.

[0] value-result aka in+out

**Comment by dankamongmen** [comment]
BTW for these functions, a return type of `int` is typically indication that the return is success or failure.

Yeah, I know, C definitely shows its age when it comes to error-handling.

**Comment by joseluis** [comment]
> so what's going on here is that those which need to indicate success or failure do so using the return value. those which can onlsucceed return the modified VR [0] parameter so that it can be further used without needing a new statement.

I see, so for convinience, in the cases where you have the possibility of returning the value, in order to consume that way or the other, depending on the situation.

> they could return void, but why waste a perfectly good rvalue?

Sometimes is better to not overcomplicate things, but I'm also a fan of versatility. Tough choice.

Now the the million dollar question would be:
Since I'm using the type system in Rust and those other functions can't fail, would you like that I make those functions return the modified channels too?

I guess you're gonna prefer not to, since that differentiates a little bit more the Rust bindings from the C code. Either way the freedom in the higher level bindings design makes the issue of secondary importance.

**Comment by dankamongmen** [comment]
> > so what's going on here is that those which need to indicate success or failure do so using the return value. those which can onlsucceed return the modified VR [0] parameter so that it can be further used without needing a new statement.
> 
> I see, so for convinience, in the cases where you have the possibility of returning the value, in order to consume that way or the other, depending on the situation.

well, mostly for convenience, though if a gun was pointed at my head and i had to justify it with a better reason, i'd point to:

`const int flargle = rvalue_function(&bargle)`

though you could then say "well that's unconvincing, why not

```
rvalue_function(&bargle);
const int flargle = bargle;
```

?" at which point i'd mumble something about having to interface with external code having non-robust macros designed for one statement and one statement only. in truth, i hoard vertical space.

**Comment by dankamongmen** [comment]
> Now the the million dollar question would be: Since I'm using the type system in Rust and those other functions can't fail, would you like that I make those functions return the modified channels too?

`libnotcurses-rs` ought return whatever Notcurses is returning, shimmed only as needed to make it compile as Rust. anything atop this ought be idiomatic Rust, written so that your heart is light, and full of song.

**Comment by dankamongmen** [comment]
> > Now the the million dollar question would be: Since I'm using the type system in Rust and those other functions can't fail, would you like that I make those functions return the modified channels too?
> 
> `libnotcurses-rs` ought return whatever Notcurses is returning, shimmed only as needed to make it compile as Rust. anything atop this ought be idiomatic Rust, written so that your heart is light, and full of song.

Put another way, this interface is as it is due to the limited type and parameter passing mechanisms of C.

A better API is almost certainly doable with stronger, more precise mechanisms of expression. I see no reason not to do that, and hope you do.

**Comment by joseluis** [comment]
I also like inlining and brevity as much as possible, as long as it doesn't become like unreadable perl. Thank you for reminding me that it's most important to keep a tight consistency between Rust's libnotcurses-sys and C's notcurses. I'll leave the work on light and songs, bells and whistles, (ergonomy, encapsulation, error managing and conciseness) mainly for the higher lever wrapper.

It will make maintenance easier too.

**Comment by joseluis** [comment]
Reopening for another case I found I'd like to discuss: `channels_blend`

This function receives 2 channels, returns a blend of both according to some rules.
But internally operates modifying the first channel, and this time I don't see the ergonomics in that, and we're making it complicated if you want to preserve the first channel as it was.

In Rust it's uglier to use since I have to pass both channels in a different way:
```rust
pub fn channels_blend(channel1: &mut Channel, channel2: Channel, blends: &mut u32) -> Channel {
```

I think it would be much better to receive both channels as read-only (const in C), and create a new mutable one internally to return.

**Comment by dankamongmen** [comment]
> Reopening for another case I found I'd like to discuss: `channels_blend`
> 
> This function receives 2 channels, returns a blend of both according to some rules.
> But internally operates modifying the first channel, and this time I don't see the ergonomics in that, and we're making it complicated if you want to preserve the first channel as it was.
> 
> In Rust it's uglier to use since I have to pass both channels in a different way:
> 
> ```rust
> pub fn channels_blend(channel1: &mut Channel, channel2: Channel, blends: &mut u32) -> Channel {
> ```
> 
> I think it would be much better to receive both channels as read-only (const in C), and create a new mutable one internally to return.

i have to do work crap for a bit, but wanted you to know i read this thinking of "Channel" as those message-passing abstractions in Go, and was brutally mind-fucked for a solid five seconds. should respond within a few hours.

**Comment by dankamongmen** [comment]
> Reopening for another case I found I'd like to discuss: `channels_blend`

`channels_blend` has been removed from the public API, so i think we're good here.

> I think it would be much better to receive both channels as read-only (const in C), and create a new mutable one internally to return.

D: that's an unnecessary allocation! my grandmother, herself a software witch, would rise from the grave and whip me with wet reeds

**Comment by dankamongmen** [comment]
> D: that's an unnecessary allocation! my grandmother, herself a software witch, would rise from the grave and whip me with wet reeds

as i understand things, rust would be able to track lifetime, realize that this allocation was only used immediately after, and both remove the need for a manual `free()` and possibly even inline this fixed-size allocation as some local, right? man the future is nice.

**Comment by dankamongmen** [comment]
> > D: that's an unnecessary allocation! my grandmother, herself a software witch, would rise from the grave and whip me with wet reeds
> 
> as i understand things, rust would be able to track lifetime, realize that this allocation was only used immediately after, and both remove the need for a manual `free()` and possibly even inline this fixed-size allocation as some local, right? man the future is nice.

to be fair c++ can accomplish all this for you, so long as you don't fuck it up any of 40,006 ways
