### ISSUE TITLE
clarifying gcluster usage in cell_load, cell_prime & cells_load_box

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#918]
I'm confused regarding the use of gcluster by these functions. It conflicts with my knowledge of a grapheme cluster as shown in:  https://github.com/dankamongmen/notcurses/blob/master/rust/src/types.rs#L143

E.g.:
`cell_load()`
```C
// Breaks the UTF-8 string in 'gcluster' down, setting up the cell 'c'. Returns                                         
// the number of bytes copied out of 'gcluster', or -1 on failure. The styling                                          
// of the cell is left untouched, but any resources are released.                                                       
__attribute__ ((nonnull (1, 2, 3)))                                                                                     
API int cell_load(struct ncplane* n, cell* c, const char* gcluster);
```
it appears to treat it as an array of characters instead of an unsigned long.

Also in `cells_load_box` it's named `gclusters`, adding to the confusion. What's really happening here?

**Comment by joseluis** [comment]
This is of course related to the renaming of functions in https://github.com/dankamongmen/notcurses/issues/912

**Comment by dankamongmen** [comment]
An EGC can't generally be encoded as a 4-byte integer (or an integer of any fixed size), as it can  be composed of arbitrarily many Unicodes:






j̲̝͖͎̯͓͕̑̂̎̿́o̖͖̬̤̞̯̊͛̀̉̉s̮͙̤̮̞͇̣̲̪̘͔͍̓͋̍̽ê͖̘͍͙̠͙̳͖͙̠̟͌̀̀̿͛̓̉̀̌̋l͖͍̩̰̬͕͙̥̆͗͛̈́̿̎͌̍̿͛͒̚ͅu͙͈̯͓̝͔̅̎̆̔̚ḭ̩̮̗̙̤̰͕͙̪̟̉͛̌̒̔͆̎̚ͅṣ̭̳̥͕͈̖͍̣̦̀͂̇͋͑̂̑̈̈̽









that's only 8 EGCs, despite being 275 bytes. So an EGC's most natural representation is a UTF8-encoded multibyte `char *` or a UCS32-encoded wide character `wchar_t *`. Either way, you need a dynamic array (a string).

A `cell` contains a single EGC. Iff that EGC can be UTF8 encoded in 4 bytes or less, it is inlined into `cell->gcluster` -- but still **interpreted** as a NUL-terminated `char *` (technically, `&cell->gcluster` is treated as a `char*`). If it is more than 4 bytes, `cell->gcluster` has a first byte of 0x01, and the remaining 24 bits are an index into the plane's egcpool, which is carved into NUL-terminated chunks of arbitrary length.

So `gcluster` as an input to these functions means "the EGC i'm providing" or more correctly "a string prefixed by the EGC i'm providing". `gluster` in the `cell` context means "the one particular EGC corresponding to this `cell`, either as inlined within `gcluster` itself, or pointed at within the egcpool."

renaming the parameters `egc[s]` from `gcluster` is probably a winning move here.

**Comment by dankamongmen** [comment]
The Official Word on EGCs/segmentation btw is https://unicode.org/reports/tr29/ (and note #882).

**Comment by joseluis** [comment]
> A cell contains a single EGC. Iff that EGC can be UTF8 encoded in 4 bytes or less, it is inlined into cell->gcluster -- but still interpreted as a NUL-terminated char *

ok! so it's always interpreted like an array, now it makes sense, thank you

I'm working on the Rust castings an EGC into byte arrays and it would help to make it safe if the `cell_load` function would take an `unsigned char* gcluster`, since all the `to_xx_bytes()` standard conversion functions work with `u8`.

I could always `transmute` it like YOLO but I think it would make more sense if everytime a gluster is interpreted as a char* it would be unsigned for type consistency. What do you think?

Oh and BTW then I can choose to interpret the the bytes in le, ge o native orders... What do you recommend me?

**Comment by dankamongmen** [comment]
yes, i have been considering a move to `unsigned char*`, which is more correct. the only worry is that you pretty much have to then write your own shadow unsigned `string.h`, and compilers sometimes have specific rules for `string.h`, but you won't get them, or maybe you will, or who knows. the fact that it has to be done at all is always dismaying, and i try not to think about it.

but yeah it's probably time.

you should ideally never have to deal with endianness. why do you think you'll need to?

**Comment by joseluis** [comment]
Maybe I wont... I'm trying to understand how the pieces fit together, while trying to avoid pointer math, trying to use safer abstractions that better indicate the nature and use of the data.

Like if gclusters are ALWAYS being used as byte arrays it doesn't make sense for its Rust type to be u32 but &[u8]... And so on... And going from *const u8 (or i8 for now...) to the safe abstraction...

I was even taking a look to utf8_egc_len and the egcpool.h file because I still feel insecure thinking about inner model...

**Comment by joseluis** [comment]
Closing this, since I finally could safe-wrap the functions receiving EGC all receive a Rust char, which internally are converted to *const i8 or *mut i8 if needed.

I'll update the conversions should you change those to unsigned char in C later.

**Comment by dankamongmen** [comment]
> I'll update the conversions should you change those to unsigned char in C later.

I'm thinking that this is likely, probably this weekend. I'll put it up as a PR for you to review, so you know it's happening.
