### ISSUE TITLE
What is the reason for all functions being y first x second?

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses#925]
There must be a good one and I'm wondering since for me is completely unfamiliar, even when dealing with columns and rows it seems way more common to expect first the width in columns...

**Comment by dankamongmen** [comment]
Following the lead of NCURSES. I wanted to make it easier to port NCURSES to Notcurses. Whether this was a good decision is debatable (it probably was not); whether we can gratuitously change it at this point is less so (we probably can not, if only because I don't want to go change my own ~10000 lines of Notcurses code).

```
[schwarzgerat](16) $ man getyx
getyx(3NCURSES)                                                getyx(3NCURSES)

NAME
       getyx,  getparyx, getbegyx, getmaxyx - get curses cursor and window co‐
       ordinates

SYNOPSIS
       #include <curses.h>

       void getyx(WINDOW *win, int y, int x);
       void getparyx(WINDOW *win, int y, int x);
       void getbegyx(WINDOW *win, int y, int x);
       void getmaxyx(WINDOW *win, int y, int x);
...
```

**Comment by joseluis** [comment]
I see now, thanks.

Well, at least in the high level rust bindings I really want to swap the order, since I want to reduce the cognitive weight there AMAP. But I'll leave the low-level bindings with the ncurses order, I think that's what makes more sense.

**Comment by dankamongmen** [comment]
If you'd like to swap them there, I will not object.

**Comment by dankamongmen** [comment]
I will not deny that I have several times considered changing them throughout (obviously before 2.0), and that I agree with you regarding x,y being a more standard convention. I've always concluded the other way. I will give it more thought.

**Comment by joseluis** [comment]
> If you'd like to swap them there, I will not object

do you mean in libnotcurses-sys ?

**Comment by dankamongmen** [comment]
> > If you'd like to swap them there, I will not object
> 
> do you mean in libnotcurses-sys ?

no i mean in notcurses-rs, as you propose above. please leave libnotcurses-sys as is (as you likewise propose above).
