### ISSUE TITLE
Consider cxx as replacement for bindgen

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#927]
I stumbled upon this article this morning:

https://github.com/dtolnay/cxx

I'm kinda immediately turned off by the requirement to keep yet another list of FFIs in sync (rather than bindgen's automatic generation), but some of the other capabilities sound provocative. @joseluis , have you any thoughts on this? This is by no means an immediate-term thing.

**Comment by joseluis** [comment]
Do you mean to replace bindgen? Well it would be a lot more work I didn't count on for sure...

And right now I'm very happy with the advanced stable status of libnotcurses-sys, and very comfortable with bindgen, knowing its limitations and the extent of its bugs affecting this project gives me peace.

In times like this I like to remember the wise eternal words of the profet: "if it works... don't touch it".

At the moment I don't have any desire to tinker with that kind of low level fire, I want to enjoy the working bindings while I climb to the highest levels of Rusty APIness and I try to do useful pretty things with your lib as a dependecy...

But it's a good alternative to know, which I didn't know BTW.

**Comment by dankamongmen** [comment]
oh i wouldn't be asking you to do this at all. i consider myself responsible for the lowest layer (the one without any fun design freedom, the mechanistic one), because why would any non-robot want to mess with that?

yeah after studying this in more detail, it seems more beneficial for projects making use of c++ features, which we obviously are not. thanks for taking a look. shelving this idea, though if @dtolnay would like to make a case for his fine library, i'd be honored to hear it.

**Comment by joseluis** [comment]
I'm gonna add here a couple more links of related info and discussion, for the record:
- [The CXX debate (August 22, 2020)](https://steveklabnik.com/writing/the-cxx-debate)
  - [reddit discussion](https://www.reddit.com/r/rust/comments/ielvxu/the_cxx_debate/)

**Comment by dankamongmen** [comment]
> I'm gonna add here a couple more links of related info and discussion, for the record:
> 
> * [The CXX debate (August 22, 2020)](https://steveklabnik.com/writing/the-cxx-debate)
>   
>   * [reddit discussion](https://www.reddit.com/r/rust/comments/ielvxu/the_cxx_debate/)

hah topmost comment right now is about the difference in unsigned vs signed definedness under overflow

**Comment by joseluis** [comment]
And this one too: it seems it's the topic of the week...

https://www.abubalay.com/blog/2020/08/22/safe-bindings-in-rust
