### ISSUE TITLE
build rust and python as part of CI

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#930]
Our CI (https://drone.dsscaw.com:4443) currently just builds the C/C++ targets and runs the tests as specified for CMake. We ought also check the python and rust. This requires

* [x] amending `.drone.yaml` to run `make install` on success of `make test` or maybe even just `make`
* [x] changing directory to python
* [x] running `python3 setup.py build`
* [x] changing directory to rust
* [x] running `cargo update`, `cargo build`, `cargo test`

note that running the Rust unit tests will require parameters to cargo; see #766

@joseluis , feel free to pitch in, but i'll get to this if not; fucking with drone is not particularly enlightening nor rewarding imho

**Comment by joseluis** [comment]
Ok but there's no need to run `cargo update`, since the `Cargo.lock` file isn't even in the repo, as customary with libs.

And you may run just `cargo t` for easy peasy testing, since already made an alias in `.cargo/config.toml`

**Comment by joseluis** [comment]
We can also create a more explicit -longer- alias for the CI if you prefer.

**Comment by joseluis** [comment]
BTW you're reminding me of the importance of finishing the unit tests...

**Comment by dankamongmen** [comment]
https://drone.dsscaw.com:4443/dankamongmen/notcurses/3851/2/2 ubuntu built everything successfully. we're missing some llvm thing on the debian builder, whoops.
