### ISSUE TITLE
ncplane_putc_yx/ncplane_putegc_yx allow wide chars on last column with specific x

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#967]
While they properly guard against placing a wide character on the rightmost column when the cursor is already there and `x` is -1, they **do not** appear to protect against specifying `x == dimx - 1` and placing a wide character. Sacre bleu! I have verified this with a new unit test, `RejectWideAsianPlaced`, and sure enough it fails. I'm shocked that this has been a bug for however long it's existed, ugh.

**Comment by dankamongmen** [comment]
Resolved in `dankamongmen/ncput`.

**Comment by joseluis** [comment]
Hi @dankamongmen I think it'd be a good idea to test also against [the longest wide characters](https://www.reddit.com/r/Unicode/comments/5qa7e7/widestlongest_unicode_characters_list/)

**Comment by dankamongmen** [comment]
> Hi @dankamongmen I think it'd be a good idea to test also against [the longest wide characters](https://www.reddit.com/r/Unicode/comments/5qa7e7/widestlongest_unicode_characters_list/)

heheheheheheheheheheheheheehehehe. yes, that would be nice.

in our world, glyphs are only 1 or 2 columns, because that's all `wcwidth()`, our canonical source for width information, thinks they are. this is, in truth, false.

glyph width is a function of POSIX locale, c library, font, font layout engine, and terminal. we can query the first two.

querying further is #366. i hope to one day do it.

i can assure you that (a) throwing U+FDFD ARABIC LIGATURE BISMILLAH AR-RAHMAN AR-RAHEEM ﷽ **anywhere** using notcurses is going to be exciting times and (b) solving it is perhaps the greatest outstanding challenge for notcurses.

**Comment by dankamongmen** [comment]
> > Hi @dankamongmen I think it'd be a good idea to test also against [the longest wide characters](https://www.reddit.com/r/Unicode/comments/5qa7e7/widestlongest_unicode_characters_list/)
> 
> heheheheheheheheheheheheheehehehe. yes, that would be nice.
> 
> in our world, glyphs are only 1 or 2 columns, because that's all `wcwidth()`, our canonical source for width information, thinks they are. this is, in truth, false.
> 
> glyph width is a function of POSIX locale, c library, font, font layout engine, and terminal. we can query the first two.
> 
> querying further is #366. i hope to one day do it.
> 
> i can assure you that (a) throwing U+FDFD ARABIC LIGATURE BISMILLAH AR-RAHMAN AR-RAHEEM ﷽ **anywhere** using notcurses is going to be exciting times and (b) solving it is perhaps the greatest outstanding challenge for notcurses.

I quote `include/notcurses/notcurses.h`:

```
// Multi-column characters can only have a single style/color throughout.
// Existence is suffering, and thus wcwidth() is not reliable. It's just
// quoting whether or not the EGC contains a "Wide Asian" double-width
// character. This is set for some things, like most emoji, and not set for
// other things, like cuneiform. Fucccccck. True display width is a *property
// of the font*. Fuccccccccckkkkk. Among the longest Unicode codepoints is
//
//    U+FDFD ARABIC LIGATURE BISMILLAH AR-RAHMAN AR-RAHEEM ﷽
//
// wcwidth() rather optimistically claims this suicide bomber of a glyph to
// occupy a single column, right before it explodes in your diner. BiDi text
// is too complicated for me to even get into here. It sucks ass. Be assured
// there are no easy answers. Allah, the All-Powerful, has fucked us again!
```

**Comment by joseluis** [comment]
> in our world, glyphs are only 1 or 2 columns, because that's all `wcwidth()`, our canonical source for width information, thinks they are. this is, in truth, false.

I see... quoting from [`wcwidth.c`](https://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c):

```
 * Much less clear is the choice of width for the Not East Asian
 * (Neutral) class. Existing practice does not dictate a width for any
 * of these characters. It would nevertheless make sense
 * typographically to allocate two character cells to characters such
 * as for instance EM SPACE or VOLUME INTEGRAL, which cannot be
 * represented adequately with a single-width glyph. The following
 * routines at present merely assign a single-cell width to all
 * neutral characters, in the interest of simplicity. This is not
 * entirely satisfactory and should be reconsidered before
 * establishing a formal standard in this area. At the moment, the
 * decision which Not East Asian (Neutral) characters should be
 * represented by double-width glyphs cannot yet be answered by
 * applying a simple rule from the Unicode database content. Setting
 * up a proper standard for the behavior of UTF-8 character terminals
 * will require a careful analysis not only of each Unicode character,
 * but also of each presentation form, something the author of these
 * routines has avoided to do so far.
``` 
So it leaves us blind regarding those characters.

I knew there was a [Rust library](https://github.com/unicode-rs/unicode-width) for that functionality, and I just checked [it has the same limitation](https://github.com/unicode-rs/unicode-width/blob/master/src/lib.rs#L70), since it follows the standard and... there's no standard for those characters, e.g. it treats the \u1242B character as having a width of 1.

> glyph width is a function of POSIX locale, c library, font, font layout engine, and terminal. we can query the first two.

Well, until the probing could be added, I believe that could be enough.

But if we need to address it we would need to add an additional comprobation on top of `wcwidth.c` checking for the most [obvious | common | simple] unicode ranges having the widest characters, and return the hardcoded real widths we've already checked the character should have, like e.g. `𒐫` ( \u1242B ) = 6

what do you think?

**Comment by dankamongmen** [comment]
When you say "already checked the character should have", what method do you propose for that?

The simplest proposal is to interrogate the font. Unfortunately, that's not completely correct in and of itself, because things can change based on surrounding glyphs -- see [Complex Text Layouts](https://en.wikipedia.org/wiki/Complex_text_layout). So you need to query the text layout engine. For us, that's usually going to be Harfbuzz, but building in such a requirement makes the porting effort much more complex (for that matter, how the fuck does one go talking to Harfbuzz? i'm sure it can be done, just saying, gah).

So let's say you query Harfbuzz. Unfortunately, that's not completely correct in and of itself, because the terminal can lay things out differently than recommended. See for instance in #881, the example of ㉉ and friends. for one text sequence, it's lain out five different ways in as many terminal families. So you've gotta ask the terminal. OK, that's easily enough done: you can send a CSI requesting cursor position, write the sequence, and send another CSI requesting cursor position, taking the difference.

Except given sequences like the above, you have to do this for arbitrary sequences almost. It ends up all being hellish. I'm open to good ideas, but I very much fear the idea of interrogating the terminal every time we see a Wide Asian character--especially when `wcwidth()` works *pretttttttttty* well in practice...

let's move further discussion to #366 or similar. i've put a lot of thought and research into this topic, most of which i haven't written down anywhere, so these are good questions regarding a super shitty problem.

**Comment by dankamongmen** [comment]
oh and even if you do all of the above, you still need to deal with (1) detecting a font change somehow, and (2) invalidating everything upon such a change, which good fucking luck
