### ISSUE TITLE
implement remaining readline shortcuts in ncreader

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#983]
We want most of the libreadline editing shortcuts supported in ncreader. Foremost among them would be:

* [x] ^A: cursor to beginning of line
* [x] ^B: cursor one backwards
* [x] ^E: cursor to end of line
* [x] ^F: cursor one forwards
* [x] ^U: clear the line before cursor
* [x] ^W: clear the word before cursor
* [x] Alt+B: cursor one word backwards
* [x] Alt+F: cursor one word forwards

**Comment by joseluis** [comment]
Could these be optional?

**Comment by dankamongmen** [comment]
> Can the shortcodes be disabled/customized?

of course, `NCREADER_OPTION_NOEMACS_KEYS` or something. maybe they'll even be opt-in.

**Comment by dankamongmen** [comment]
> of course, `NCREADER_OPTION_NOEMACS_KEYS` or something. maybe they'll even be opt-i

`NCREADER_OPTION_NOCMDKEYS`, and it's opt-out.

**Comment by dankamongmen** [comment]
> `NCREADER_OPTION_NOCMDKEYS`, and it's opt-out.

(mainly because what exactly the hell does e.g. ctrl-b mean if not "go backwards"? i can't represent it sanely)
