### ISSUE TITLE
2.0 API review

### ISSUE THREAD

**Issue by dankamongmen** [dankamongmen/notcurses#985]
Since we're committing to a stable API following 2.0's release, it would serve us well to ensure that said API bears as few flaws as possible. We will thus be undertaking a top-to-bottom review of the public Notcurses API before cutting 2.0. Issues found should be listed in this bug, or in #627 if they have to do with widgets.

* [x] anything having a `channels` member ought provide the standard set of channels functionality to directly modify it
  * set fg, bg alpha
  * set fg, bg palindex
  * set fg, bg rgb as components (maybe rename this rgb8)
  * set fg, bg rgb as 24-bit value (maybe rename this rgb)
  * set fg, bg default
  * set fg, bg as 32-bit value -- problematic, as we never want the wide bit set (except when we do), etc.
  * per-channel `palindex_p`, `default_p`, 
* [x] any output method ought support the standard forms:
  * default (do it at cursor using plane state)
  * yx (do it at specified position using plane state)
  * aligned (do it at specified y, aligned as specified relative to the plane)
  * stainable (do it at cursor, honoring existing styling)
* [x] try to cut down parameters to a minimum
  * use cursor as implicit y, x when possible
* [ ] normalize semantics across related functions
  * does -1 for y, x mean "keep current", or "to the left and above the plane's origin"?
* [x] kill `ncplane_bound()` etc. since all planes are now bound

**Comment by dankamongmen** [comment]
The nice thing about replacing y, x with the current cursor position (thus eliminating them as parameters) is that we then can't get crap values for y, x (we can be offplane in two directions instead of four, and only a little offplane).

**Comment by dankamongmen** [comment]
#627 has been completed, which achieves this goal for the widgets. Let's go ahead and finalize the remaining API for 2.0.

**Comment by dankamongmen** [comment]
@joseluis , @grendello , i'm thinking one change i want to make is:

`foo_[set_]fchannel` -> `foo_[set_]fg` (set 32 bits)
`foo_[set_]fg` -> `foo_[set_]fg_rgb` (set 24 bits RGB, set up to use RGB (not default nor palindex))
`foo_[set_]fg_rgb` -> `foo_[set_]fg_rgb8` (set 8x3 bits RGB as three components, set up to use RGB)

This:

* normalizes all partial sets to `foo_[set_]{bf}g_bar` (matching e.g. `foo_[set_]{bf}g_alpha`, `channel_set_{bf}`)
* complete set makes more sense now as `foo_[set_]{bf}g`, a prefix of the partial sets
* eliminates linguistic abominations like `channels_set_fchannel()`
* don't have to remember difference between `_set_fchannel()` and `_set_fg()`, which is non-obvious
  * instead, you now have `_set_fg()` and `_set_fg_rgb()`, quite clear
* failure to convert to `_set_fg_rgb8()`  will throw a compilation error (wrong # of arguments)
* failure to convert to `_set_fg()` will throw a compilation error (`_set_fchannel()` no longer exists)
* **failure to convert to `_set_fg_rgb()` will NOT throw a compilation error**, *but....*
  * all such a failure can do is blow away alpha values, not too terrible (intended `_set_fg_rgb()` remains `_set_fg()`)
  * cannot be avoided unless we pick a different name for what was `_set_fchannel()` (maybe leave it as `_set_fchannel()`)

I know this is kind of a late change, but it's now or never, and I'm very dissatisfied with the current `_set_{bf}channel()` v `_set_{bf}g` dichotomy for 32-vs-24 bit set. At the very least, I want to shift `_fg()` down to `_fg_rgb()` and `fg_rgb()` down to `_fg_rgb8()`. I'm less wedded to the `_fchannel()` -> `_fg()` conversion.

Thoughts?

**Comment by dankamongmen** [comment]
Maybe `_{fb}channel` -> `_{fb}32`?

**Comment by joseluis** [comment]
I really like what you're trying to do here, and this is the perfect moment for it.

What do you feel about `_{fb}channel` → `_{fb}_rgba`?

**Comment by dankamongmen** [comment]
> I really like what you're trying to do here, and this is the perfect moment for it.

=]

> What do you feel about `_{fb}channel` → `_{fb}_rgba`?

i don't like it, because a channel is **not** a 32-bit 4x8 RGBA value. it's 3x8 RGB + 2 bits of A + some other bits. i'm floating `_{fb}32` at the moment, but am in no way wedded to that.

i think i hear from you that ensuring all missed transitions result in compiler errors is more important than conceptual clarity (i.e. `channel` -> `fg` is a no-go). i am inclined to agree.

**Comment by dankamongmen** [comment]
Actually, I see no real advantage of `32` over `channel`; it reeks of churn for churn's sake. I'm leaning towards leaving `channel` as-is.

**Comment by dankamongmen** [comment]
Currently, when we create a bound plane with `ncplane_bound()` and friends, we're providing global coordinates. Ought we not be providing coordinates relative to the binding plane, given that this is how coordinates will be interpreted for the plane going forward?

**Comment by dankamongmen** [comment]
For that matter, why do we even have `ncplane_bound()` anymore, given that all planes are now bound?

**Comment by dankamongmen** [comment]
I have inspected the full API, and can find no function where both (1) `int y, int x` are specified and (2) there are other `int` parameters. so we're good regarding the "implicit cursor" item in the original issue.

**Comment by dankamongmen** [comment]
output forms:

* `putc`: output a `cell`. only have `putc` and `putc_yx`
* `putchar`: output a (7-bit, unenforced) `char`. `putchar`, `putchar_yx`, `putchar_stainable`
* `putwc`: output a `wchar_t`. `putwc`, `putwc_yx`
* `putegc`: output an EGC taken from `const char*`. `putegc`, `putegc_yx`, `putegc_stainable`
* `putwegc`: output an EGC taken from `const wchar_t*`. `wegc`, `wegc_yx`, `wegc_stainable`
* `putstr`: output a series of EGCs from `const char*`. `putstr`, `putstr_yx`, `putstr_stainable`, `putstr_aligned`
* `putnstr`: output a bounded series of EGCs from `const char*`: `putnstr`, `putnstr_yx`, `putnstr_aligned`
* `putwstr`: output a series of EGCs from `const wchar_t*`. `putwstr`, `putwstr_yx`, `putwstr_stainable`
* there's no `putwnstr`
* `printf`: formatted output. `print`, `printf_yx`, `printf_aligned`, `printf_stainable`
* `vprintf`: formatted output. `vprintf`, `vprintf_yx`, `vprintf_aligned`, `vprintf_stainable`
* `puttext`: flowing output. `puttext`

**Comment by dankamongmen** [comment]
I think we can continue living fine without `_aligned` form of single-EGC (or even sub-EGC) output modes. No need to add them.

**Comment by dankamongmen** [comment]
Likewise, there's no reason to have a `putc_stainable()`: the whole point of a `cell` is that it specifies its own formatting.

We might as well add `putwnstr`, yawn.

Either finish out or eliminate `putwc`, do it or don't.

`puttext_stainable()` sounds like it could be hella useful, definitely want to add that, though it's not necessary to do it for 2.0.

need `putwstr_aligned()`

Also, some of these take `int*sbytes` as a final parameter, some don't. Analyze and normalize. Likewise return values.
